### ISSUE TITLE
[Bug]: Cancel the project application task should have a second confirmation notes

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1003]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/4c1e2912-2301-4446-8d67-59603c71d772)
There is no second prompt for canceling the project permission task

### What did you expect to happen?

A double confirmation should be added when cancelling.

### How can we reproduce it (as minimally and precisely as possible)?

Cancel a project permission application task.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/39df0b18-9ae9-4aed-a3f5-88a0e6f69d57)

pass
