### ISSUE TITLE
[Bug]: The role of the creator in the ticket details is incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1004]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

The role of the creator in the ticket details is sysadmin.
![image](https://github.com/oceanbase/odc/assets/46598871/429e6fda-bdc4-4bf6-9489-3cc2995b260d)
In fact the user does not have any role.
![image](https://github.com/oceanbase/odc/assets/46598871/bf3afc1d-32bd-4b62-ab63-ad05d39083a6)

### What did you expect to happen?

Show the right role.

### How can we reproduce it (as minimally and precisely as possible)?

View the role of the creator in the ticket details.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/378b511c-5fff-4929-9742-28d6a3428501)

pass
