### ISSUE TITLE
[Bug]: inWhiteListExpression configuration field must be enclosed in double quotes

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1007]
### ODC version

ODC423

### OB version

independent

### What happened?

inWhiteListExpression configuration field must be enclosed in double quotes
![image](https://github.com/oceanbase/odc/assets/59468957/43db8c4e-87fd-4b95-aaa7-a7d4f7091c31)

### What did you expect to happen?

maybe can optimize

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by smallsheeeep** [comment]
This is by design 🤪🤪🤪
