### ISSUE TITLE
[Bug]: there is no action when I attempt to drop a jdbc parameter

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1009]
### ODC version

4.2.3

### OB version

not related

### What happened?

I attempt to drop a jdbc parameter but there is no action:
<img width="542" alt="截屏2023-12-05 17 33 56" src="https://github.com/oceanbase/odc/assets/22992296/c47c0ed7-1e6c-4773-809a-831279221935">

### What did you expect to happen?

I can see it deleted clearly

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [9bcd26a5b614e108cc6bacb259f77bfd3b762855](https://github.com/oceanbase/odc-client/commit/9bcd26a5b614e108cc6bacb259f77bfd3b762855)
            ------
            咏和
            Fri Dec 8 11:40:28 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/05510ec0-48b7-45de-a9e6-cc7f3e4d5402)

pass
