### ISSUE TITLE
[Bug]: remove name check for primary key def

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#102]
### ODC version

4.2.0

### OB version

not related

### What happened?

we create a table as follow:
```SQL
create table test_tbl(
    id varchar(64) primary key
);
```
SQL-Check will give a violation message: "Index definition is not named"
<img width="707" alt="截屏2023-08-31 17 42 16" src="https://github.com/oceanbase/odc/assets/22992296/6d12df3c-45c5-45b6-a4b5-294ae77def7b">

### What did you expect to happen?

primary key's def is different from general index def, and we can create a new sql-check rule to check if user's create table def give a name to a primary key.

### How can we reproduce it (as minimally and precisely as possible)?

follow "what happened"

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6f4c986f-3423-444e-9167-ba1ca3714be5)

pass
