### ISSUE TITLE
[Bug]: oracle mode When the constraint names are consistent, the two constraints will be merged and displayed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1020]
### ODC version

odc423

### OB version

*

### What happened?
![image](https://github.com/oceanbase/odc/assets/143492234/878ac56b-5000-4278-98cb-88d27d6c862b)
![image](https://github.com/oceanbase/odc/assets/143492234/d506951b-156e-493c-a48f-6d9763ed81a6)
![image](https://github.com/oceanbase/odc/assets/143492234/2e0b64d9-0a82-4ee6-a97a-d36f84670d01)

### What did you expect to happen?

Separate display

### How can we reproduce it (as minimally and precisely as possible)?

Create a unique constraint within the primary key table that matches the primary key name

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/d87dd143-7542-4985-9aea-45cd22564a16)
