### ISSUE TITLE
[Bug]: The DLM task checks the log and reports that the log does not exist or has expired.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1022]
### ODC version

ODC423

### OB version

independent

### What happened?

The DLM task checks the log and reports that the log does not exist or has expired.
![image](https://github.com/oceanbase/odc/assets/59468957/ef901015-8ac3-4ee2-a3df-c0c28d6b42f2)

### What did you expect to happen?

chat priavtely

### How can we reproduce it (as minimally and precisely as possible)?

chat priavtely

**Comment by guowl3** [comment]
This task failed during the scheduling but logging started from the scheduling stage, so the results were as expected.
