### ISSUE TITLE
[Bug]: The time units of the entire chain trace will overlap

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1027]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/8eb5de21-f81f-448d-961b-a89bb41ff10f)

### What did you expect to happen?

Time units will not overlap

### How can we reproduce it (as minimally and precisely as possible)?

View full link trace

**Comment by HSunboy** [comment]
Fixed In Commit [0c38b12ccd322799e5ce878e1fbdbd8fe3c88fd0](https://github.com/oceanbase/odc-client/commit/0c38b12ccd322799e5ce878e1fbdbd8fe3c88fd0)
            ------
            陈朝俊
            Tue Dec 19 19:07:50 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/fafd8be9-1252-4899-9351-ec7633a9cb9a)
PASS
