### ISSUE TITLE
[Bug]: export task，Check the sys account. If the password is wrong, you can also click Next.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1031]
### ODC version

ODC423

### OB version

independent

### What happened?

Check the sys account. If the password is wrong, you can also click Next.
![image](https://github.com/oceanbase/odc/assets/59468957/7fe5a3d9-4915-4e13-a784-757a6cac81b5)

### What did you expect to happen?

The password is wrong, you cannot click Next

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by bluesky-xyh** [comment]
The password is optional, and the creation task itself does not verify the validity of the password
