### ISSUE TITLE
[Bug]: Data archiving, the task is in a waiting state after half execution

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1033]
### ODC version

ODC423

### OB version

independent

### What happened?

Data archiving, the task is in a waiting state after half execution
![image](https://github.com/oceanbase/odc/assets/59468957/c446b430-2b95-4987-9823-7a6ec03c2a41)
![image](https://github.com/oceanbase/odc/assets/59468957/06faafdf-4b4c-4d95-aad5-b93f7789cb3a)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Fixed In Commit [9de6d4368cdd53534dc280f33e9e6ce2286bcfeb](https://github.com/oceanbase/odc-client/commit/9de6d4368cdd53534dc280f33e9e6ce2286bcfeb)
            ------
            陈朝俊
            Tue Dec 12 09:57:37 2023 +0800

**Comment by UnknownAdventurer** [comment]
My problem. I got the wrong issue

> Fixed In Commit [9de6d4368cdd53534dc280f33e9e6ce2286bcfeb](https://github.com/oceanbase/odc-client/commit/9de6d4368cdd53534dc280f33e9e6ce2286bcfeb) ------ 陈朝俊 Tue Dec 12 09:57:37 2023 +0800

My problem. I got the wrong issue, this commit is fix the other one. [odc1103](https://github.com/oceanbase/odc/issues/1103)
