### ISSUE TITLE
[Bug]: Invalid database search when adding sensitive columns

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1034]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/0358b82c-73f5-468e-a9d1-6d3cd158e7d9)

### What did you expect to happen?

Can search the database

### How can we reproduce it (as minimally and precisely as possible)?

When you add sensitive columns to a project, search the database

**Comment by HSunboy** [comment]
Fixed In Commit [d24064af237c2cce91fe63d0948956224817ae48](https://github.com/oceanbase/odc-client/commit/d24064af237c2cce91fe63d0948956224817ae48)
            ------
            陈朝俊
            Tue Dec 12 11:20:11 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/952f3991-935c-4a51-97ef-3b3c3a46bba7)

pass
