### ISSUE TITLE
[Bug]: failed to locate the line of an issue when sql script is modified

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1036]
### ODC version

4.2.3

### OB version

not related

### What happened?

1. type sql:
<img width="438" alt="截屏2023-12-06 20 31 37" src="https://github.com/oceanbase/odc/assets/22992296/21215b3c-5efd-4b42-9669-338d154e1848">

2. click sql-check button and we get the check result, we can locate the issue line when we don't modify the original content:
<img width="1033" alt="截屏2023-12-06 20 32 50" src="https://github.com/oceanbase/odc/assets/22992296/2a6950c5-2b08-4dbc-88f3-a4ac3b7b8edd">

3. the location is not right when we modify/remove the sql content:
<img width="922" alt="截屏2023-12-06 20 34 01" src="https://github.com/oceanbase/odc/assets/22992296/5adae4de-d958-4265-9b3b-b1193bbf9f75">

### What did you expect to happen?

do not failed to locate 

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
We can disable the location button when the sql content is modified and give user a notice (just like 'can not locate the issue line cause that you have modified the content') when he/she hover the button.

**Comment by HSunboy** [comment]
Fixed In Commit [ed34629907e549565ce3d350aab88e829f4868e8](https://github.com/oceanbase/odc-client/commit/ed34629907e549565ce3d350aab88e829f4868e8)
            ------
            陈朝俊
            Thu Dec 7 19:56:45 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/7c0aad92-c6e9-4551-8fc9-e07b01c65a6f)

pass
