### ISSUE TITLE
[Bug]: The application ticket in a project should only show this project's tasks

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1037]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

The ticket in the project shows the request ticket for other projects.
![image](https://github.com/oceanbase/odc/assets/46598871/06cc8e8b-a287-4c7a-a0a7-166b287c2c35)

### What did you expect to happen?

The application ticket in a project should only show this project's tasks

### How can we reproduce it (as minimally and precisely as possible)?

Enter the project and view the project application ticket

**Comment by smallsheeeep** [comment]
It appears that all types of task orders are not presented as separate project
