### ISSUE TITLE
[Bug]: The operation record does not show the title of the project application

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1038]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

The operation record does not show the title of the project application
![image](https://github.com/oceanbase/odc/assets/46598871/bbb6339a-507b-4f22-99a5-2e4b949ddaab)

### What did you expect to happen?

The operation record shows the title of the project application

### How can we reproduce it (as minimally and precisely as possible)?

View the operation record

**Comment by HSunboy** [comment]
Fixed In Commit [3961b7f20fd0a8c20e2434aa383386e6e62556a4](https://github.com/oceanbase/odc-client/commit/3961b7f20fd0a8c20e2434aa383386e6e62556a4)
            ------
            咏和
            Thu Dec 7 19:55:36 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3da28564-dbba-48e4-9546-af96f140d8e7)

pass
