### ISSUE TITLE
[Bug]: session management do not show the SQL being executed

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#104]
### ODC version

4.2.0

### OB version

4.1.0 MySQL mode

### What happened?

1、To execute a SQL statement in a window，for example :select sleep(600);
2、To view the corresponding session in session management；
![image](https://github.com/oceanbase/odc/assets/15030999/c38b6050-f276-46c3-904a-f28d5b5ff033)

### What did you expect to happen?

Session Management  show the SQL being execute

### How can we reproduce it (as minimally and precisely as possible)?

1、To execute a SQL statement in a window，for example :select sleep(600);
2、To view the corresponding session in session management；

**Comment by yhilmare** [comment]
Personal testing proves it is solved

**Comment by runzi389205** [comment]
PASS


![Image](https://github.com/oceanbase/odc/assets/141202865/9a4b67a9-ba83-43ee-9765-a2369b68eb2a)



![Image](https://github.com/oceanbase/odc/assets/141202865/9d3493b2-e72d-4acc-99a1-19897c5d622f)
