### ISSUE TITLE
[Bug]: sql check's violation panel is not expected

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1044]
### ODC version

4.2.3

### OB version

not related

### What happened?

execute a sql and odc gives several sql check violation:
<img width="1084" alt="截屏2023-12-07 12 04 28" src="https://github.com/oceanbase/odc/assets/22992296/08e68686-9a0b-40e5-823c-9db0b3b86d38">

as you can see, the back end gives enough.

### What did you expect to happen?

the front end should show these violations just like the way of new design, just like this:
<img width="585" alt="截屏2023-12-07 12 07 06" src="https://github.com/oceanbase/odc/assets/22992296/17cec9e6-a96b-439a-8cac-a1eaa3d39e8d">

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [f7de18b7fae938488489828a3ca0fc4614012c40](https://github.com/oceanbase/odc-client/commit/f7de18b7fae938488489828a3ca0fc4614012c40)
            ------
            陈朝俊
            Wed Dec 13 09:27:46 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f492efc3-79c3-42cc-aee9-d0d6d6989c25)

pass
