### ISSUE TITLE
[Bug]: front end will show an empty table cell for a sql without any voilations

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1045]
### ODC version

4.2.3

### OB version

not related

### What happened?

1. type several sql that some of them get violations and some of them get no violation, just like this:
<img width="792" alt="截屏2023-12-07 12 12 57" src="https://github.com/oceanbase/odc/assets/22992296/19801f78-92ba-46a6-9012-f93a93281a55">

2. execute them directly and the execution will be interrupted by security policy, the database change task panel will be shown:
<img width="847" alt="截屏2023-12-07 12 13 58" src="https://github.com/oceanbase/odc/assets/22992296/8f86677f-44c3-43c9-ae58-58a187ad456e">

as you can see: `select 1 from dual` gets no violation but it is still be shown at violation panel which will confused user.

### What did you expect to happen?

just show the sqls that get violation.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [31c2184378df969ee13b8138cbe5d3a348e88ecd](https://github.com/oceanbase/odc-client/commit/31c2184378df969ee13b8138cbe5d3a348e88ecd)
            ------
            陈朝俊
            Mon Dec 11 11:44:26 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/110abd5f-34b1-4f4e-94ff-7f5e039d4cfc)

pass
