### ISSUE TITLE
[Bug]: the sql content is not highlighted when the database change task panel is shown at first

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1046]
### ODC version

4.2.3

### OB version

not related

### What happened?

1. execute several sqls that can not executed directly and the database change task panel will be shown:
<img width="847" alt="截屏2023-12-07 12 13 58" src="https://github.com/oceanbase/odc/assets/22992296/11577d56-ba72-4f62-9c2b-5303c395888b">

as you can see: the content is not highlighted and the violation location function does work, we need to wait for a while.

### What did you expect to happen?

the content should be highlighted when task panel is shown.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [f7de18b7fae938488489828a3ca0fc4614012c40](https://github.com/oceanbase/odc-client/commit/f7de18b7fae938488489828a3ca0fc4614012c40)
            ------
            陈朝俊
            Wed Dec 13 09:27:46 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9a2970f4-7d77-464b-bd2f-2c119673bbbd)

pass
