### ISSUE TITLE
[Bug]: incomplete DBMS output displayed on the front-end

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#1051]
### ODC version

4.2.2

### OB version

ob-oracle

### What happened?

Incomplete DBMS output displayed on the front-end. It seems that only some blank spaces were displayed.

![image](https://github.com/oceanbase/odc/assets/36879124/bb5bc1e8-7013-45c4-95d9-84a915172cd6)

### What did you expect to happen?

All spaces should be displayed.

### How can we reproduce it (as minimally and precisely as possible)?

``` sql
begin
  dbms_output.put_line('dfd' || ' asd   sdf  ' || 'bb');
end;
/
```

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8990b839-b5f9-4d49-b05f-a0d3d960e457)

pass
