### ISSUE TITLE
[Feature]: Prohibit setting desensitization columns for MySQL data sources.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#1054]
### Is your feature request related to a problem?

Since the support for data desensitization for MySQL data sources is currently incomplete, this capability will be disabled  for security reasons.

### Describe the solution you'd like

Since the support for data desensitization for MySQL data sources is currently incomplete, this capability will be disabled first for security reasons.

**Comment by HSunboy** [comment]
Fixed In Commit [a9c5e1ef1cc074045aed5fd9bf768ad672f01d19](https://github.com/oceanbase/odc-client/commit/a9c5e1ef1cc074045aed5fd9bf768ad672f01d19)
            ------
            陈朝俊
            Mon Dec 11 11:13:19 2023 +0800
