### ISSUE TITLE
[Bug]: Cancel directly after modifying the table data, and the modified data will be displayed in the table data

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1055]
### ODC version

odc423

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/54d9bb43-05bc-416c-9eae-03d1c3ab3c04

### What did you expect to happen?

data recovery

### How can we reproduce it (as minimally and precisely as possible)?

1. Modifying Table Data
2. Click to cancel

**Comment by HSunboy** [comment]
Fixed In Commit [1b2c594c3d5380977c8ae3c16680adf3f120da86](https://github.com/oceanbase/odc-client/commit/1b2c594c3d5380977c8ae3c16680adf3f120da86)
            ------
            咏和
            Wed Dec 13 10:56:10 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/b0e8e5bc-df12-4b92-9f26-bfc5b97da5bc)
pass
