### ISSUE TITLE
[Bug]: Initiate a result set task, and after manual approval, "Task expired or does not exist" is reported.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1057]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

Initiate a result set task, and after manual approval, "Task expired or does not exist" is reported.
![image](https://github.com/oceanbase/odc/assets/59468957/4cce7e2e-f06a-49b4-83a3-b3e5dc12b26a)

### What did you expect to happen?

chat privately

### How can we reproduce it (as minimally and precisely as possible)?

chat privately
`-- 查询 `test` 数据库中的数据并存储在临时表中
CREATE TABLE temp_table_test AS SELECT * FROM test.case_cf_baseinfo_new_555;

-- 查询 `test4` 数据库中的数据并存储在临时表中
CREATE TABLE temp_table_test4 AS SELECT * FROM test4.case_cf_baseinfo_new_555;

-- 对比两个临时表中的数据
SELECT * FROM temp_table_test
EXCEPT
SELECT * FROM temp_table_test4;`
发起手动审批

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/828c12b8-db40-4a14-8f70-a79daa8f9e9f)

pass
