### ISSUE TITLE
[Bug]: Built-in database in the datasource still belongs to the previous project when unbind a project

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1058]
### ODC version

4.2.3

### OB version

any

### What happened?

I create a data source and bind a project. Then I manually add the built-in database oceanbase to the project. Now I unbind the datasource to the project, but the oceanbase database is still bound to the previous project.

### What did you expect to happen?

The interal database should unbind the previous project.

### How can we reproduce it (as minimally and precisely as possible)?

(see above)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5c344ec3-c4c6-4657-a886-8c40b7394486)

pass
