### ISSUE TITLE
[Bug]: Import the sql file, if the primary key is repeated, the error log is not printed in full

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#106]
### ODC version

ODC420

### OB version

any environment

### What happened?

Import the sql file, if the primary key is repeated, the error log is not printed in full

### What did you expect to happen?

Checking the logs shows duplicate primary key errors

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a primary key index table and insert a piece of data
![image](https://github.com/oceanbase/odc/assets/59468957/1f8c7630-cc14-4810-abc0-2a8bbcb4fc3f)

2. Import sql format file
![image](https://github.com/oceanbase/odc/assets/59468957/6c7f5a24-1cf4-4d55-ae20-e219a8ff8356)

4. View logs
It is found that the import is successful, but the log does not have a primary key duplicate error
3. View logs
It is found that the import is successful, but the log does not have a primary key duplicate error
![image](https://github.com/oceanbase/odc/assets/59468957/78dfaa5e-a53a-4db3-8cba-e3b06786dbaa)
ob-loader
![image](https://github.com/oceanbase/odc/assets/59468957/92fb2427-17fa-41cc-85a7-4441d9a7152e)

**Comment by LuckyPickleZZ** [comment]
The error printed here is only Java's printing of exceptions. In fact, based on the log of ob loader, this error will not be printed, which is the same as ODC.
Won't fix this.
