### ISSUE TITLE
[Enhancement]: the sql editor can scroll to the line that I located when the position is not in current screen

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1060]
### What would you like to be added?

I type too many sqls in the editor and I click check button. I choice an issue to locate the position. Unfortunately, the position I located is not in the screen, It seems like that the location button does not work. 

![截屏2023-12-07 19 56 03](https://github.com/oceanbase/odc/assets/22992296/4e3df5a3-d1e3-4eb9-be53-688d224a64a0)

I wish that the sql editor can scroll to the line which I locate when the line is not in the current screen~

### Why is this needed?

To improve the user's experience

**Comment by HSunboy** [comment]
Fixed In Commit [f7de18b7fae938488489828a3ca0fc4614012c40](https://github.com/oceanbase/odc-client/commit/f7de18b7fae938488489828a3ca0fc4614012c40)
            ------
            陈朝俊
            Wed Dec 13 09:27:46 2023 +0800
