### ISSUE TITLE
[Bug]: ob-archiver executes ob2mysql archiving, and the query time format will be followed by a 0

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1063]
### ODC version

ODC423

### OB version

Oceanbase324
mysql5.7

### What happened?

ob-archiver executes ob2mysql archiving, and the query time format will be followed by a 0
![image](https://github.com/oceanbase/odc/assets/59468957/9487c8fc-2666-46cc-b721-2b08395b5f29)

### What did you expect to happen?

chat privately

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by PeachThinking** [comment]
The value inserted by the timestamp type of mysql 5.7 cannot currently exceed the year after '2038-01-19 03:14:07' UTC
see : https://stackoverflow.com/questions/22806870/incorrect-datetime-value-database-error-number-1292
