### ISSUE TITLE
[Bug]: The dba should not be successfully removed from the project

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1064]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

I successfully removed the dba user from the project.
![image](https://github.com/oceanbase/odc/assets/46598871/078058a0-8eb6-477e-92d6-39f6c52a2776)

### What did you expect to happen?

The dba user cannot be removed from the project.

### How can we reproduce it (as minimally and precisely as possible)?

Remove the dba user from the project.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/c8645e28-0a45-413a-835b-12351b89ee97)

pass
