### ISSUE TITLE
[Bug]: Removing developer from the project causes an error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1065]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

Removing developer from the project causes an error.
![image](https://github.com/oceanbase/odc/assets/46598871/2d5ee245-1852-4b3b-b08f-7e731523eb17)

### What did you expect to happen?

Remove developer from the project without error.

### How can we reproduce it (as minimally and precisely as possible)?

1.Remove the dba user from the project
2.Remove the developer from the project

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/372ed6ed-eedb-44e8-a85e-26444bb9a587)

pass
