### ISSUE TITLE
[Bug]: When I create a new project, I cannot select security administrators and participants

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1066]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

When I create a new project, I cannot select security administrators and participants.
![image](https://github.com/oceanbase/odc/assets/46598871/c0c462ed-7889-4ae3-855d-85f7c284145b)

### What did you expect to happen?

Add options for security administrators and participants.

### How can we reproduce it (as minimally and precisely as possible)?

Create a new project.

**Comment by HSunboy** [comment]
Fixed In Commit [b103f3d708f8234d26208a001808e91bea0053fc](https://github.com/oceanbase/odc-client/commit/b103f3d708f8234d26208a001808e91bea0053fc)
            ------
            陈朝俊
            Tue Dec 12 09:54:37 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/098107f2-99c0-403d-8e35-2f2bc08ad31b)

pass
