### ISSUE TITLE
[Bug]: Result set missing content

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1069]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/41ee18ed-e6bf-4cdc-bbb7-ff4a3363a477)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/70cc21c0-7d35-4dab-ab3e-ba7eb9611977)

### How can we reproduce it (as minimally and precisely as possible)?

View result set

**Comment by HSunboy** [comment]
Fixed In Commit [d159ed302f3b0dc56ea571c7166e65cf8a72ae94](https://github.com/oceanbase/odc-client/commit/d159ed302f3b0dc56ea571c7166e65cf8a72ae94)
            ------
            咏和
            Sun Dec 10 10:59:51 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/5149f031-c5f6-424c-95d9-b0bcef129abf)
pass
