### ISSUE TITLE
[Bug]: The column mode is invalid

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#107]
### ODC version

4.2.0

### OB version

4.1.0

### What happened?

1、Using SQL query for table data；
2、View result set in column mode；
![image](https://github.com/oceanbase/odc/assets/15030999/b6232854-e19e-48b9-98f4-0e1d2fef8307)

### What did you expect to happen?

The column mode is functioning normally

### How can we reproduce it (as minimally and precisely as possible)?

1、Using SQL query for table data；
2、View result set in column mode；

**Comment by HSunboy** [comment]
It works on dev-4.2.1 version

**Comment by runzi389205** [comment]
PASS


![Image](https://github.com/oceanbase/odc/assets/141202865/4d17ffa7-e2ac-465b-9136-b7ab06e32235)
