### ISSUE TITLE
[Bug]: fix lock user failed when ob mysql user host is not '%'

### ISSUE THREAD

**Issue by krihy** [oceanbase/odc#1074]
### ODC version

4.2.2

### OB version

ob  mysql

### What happened?

odc try to lock user failed when query user list like:
MySQL [(none)]> select user,host from mysql.user where user = 'test1';
+---------+-------+
| user    | host  |
+---------+-------+
| test1 | 11.% |
+---------+-------+
1 row in set (0.05 sec)
 when osc lock user will lock user use:
> alter user opsdb_r account lock;
ERROR 1396 (HY00@) : Operation LOCK USER failed for 'opsdb_r'@'%'****

### What did you expect to happen?

osc lock user normally and execute lock user use sql:
alter user  test1@'11.%' account lock;

### How can we reproduce it (as minimally and precisely as possible)?

create user and set user request assigned ip

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/663cdc42-db6a-400f-838d-0fe1023ad0ed)
pass
