### ISSUE TITLE
[Bug]: The original name is incorrect when restoring the recycle bin

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1075]
### ODC version

odc423

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/eab8ddab-80e7-45bc-af90-58b2725afaca

### What did you expect to happen?

The original table name is the selected table name

### How can we reproduce it (as minimally and precisely as possible)?

Restore the table again after the recycle bin restores the table

**Comment by bluesky-xyh** [comment]
fixed

**Comment by sl01388797** [comment]
pass
