### ISSUE TITLE
[Bug]: There is no SQL execution window for restoring tables in the recycle bin

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1077]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b896a11f-c843-4609-8631-bc16262471d8)

### What did you expect to happen?

After clicking on the restore button, the SQL execution window will pop up

### How can we reproduce it (as minimally and precisely as possible)?

Click to restore in the recycle bin

**Comment by bluesky-xyh** [comment]
423 feature
