### ISSUE TITLE
[Bug]: sql check gives an error result on table&column comment when execute a sql

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#108]
### ODC version

4.2.0

### OB version

not related

### What happened?

I want to execute a sql as follow:
```SQL
create table date_test_tbl(
    id varchar2(64) primary key,
    col date
);
comment on table date_test_tbl is 'asdasdasd';
```
The database change panel is popped up:
<img width="564" alt="截屏2023-09-01 10 51 57" src="https://github.com/oceanbase/odc/assets/22992296/199268dc-f0db-4c9e-aca8-f7790985f431">

### What did you expect to happen?

I do write the table comment on the table, and there is the same problem on column comment check. What I expect is that I can execute these sqls directly.

### How can we reproduce it (as minimally and precisely as possible)?

follow "What happened"

**Comment by yhilmare** [comment]
sql-check works when we trigger it directly:
<img width="610" alt="截屏2023-09-01 10 59 36" src="https://github.com/oceanbase/odc/assets/22992296/4a807e1b-e740-4afd-854f-c5006b0e7b81">

it dose not work only in sql-execute scenario. sql-check will consider the sql script as a whole when we trigger it directly, and sql-check will first divide the sql script into independent sql statements and then detect it. this differences lead to this bug.

**Comment by yhilmare** [comment]
It is special to detect whether tables and columns contain comments in oracle mode: oracle cannot directly add table comments or column comments in the table creation statement, but can only be set through an independent comment statement, as follows:
```SQL
comment on table xxx is 'aaaaa';
```

**Comment by runzi389205** [comment]
PASS
execute sqls directly.


![Image](https://github.com/oceanbase/odc/assets/141202865/72cecec8-12d7-4292-b080-9bee48bcb9c3)
