### ISSUE TITLE
[Bug]: When creating foreign key constraints, the associated schema cannot display content

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1082]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2319d181-c1a2-4470-baad-c670dc786124)

### What did you expect to happen?

There is content within the associated schema

### How can we reproduce it (as minimally and precisely as possible)?

Create foreign key constraints

**Comment by HSunboy** [comment]
Fixed In Commit [d159ed302f3b0dc56ea571c7166e65cf8a72ae94](https://github.com/oceanbase/odc-client/commit/d159ed302f3b0dc56ea571c7166e65cf8a72ae94)
            ------
            咏和
            Sun Dec 10 10:59:51 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/1cef1d53-9884-4a6d-9dc9-ba81f23cafc1)
pass
