### ISSUE TITLE
[Bug]: Display still after deleting partition

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1084]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/ac8118b8-e5c1-4f29-973d-8e833ee7ecac)
![image](https://github.com/oceanbase/odc/assets/143492234/e2a2c194-05eb-4579-82cc-c06193121348)

### What did you expect to happen?

No Q partition exists after deletion

### How can we reproduce it (as minimally and precisely as possible)?

Delete partitions after creating a multi partition table

**Comment by sl01388797** [comment]
Creating a partition will not display it either
![image](https://github.com/oceanbase/odc/assets/143492234/66a49ea2-ad68-4b2b-88cc-e9e3b8b3a4f6)
![image](https://github.com/oceanbase/odc/assets/143492234/e85cceb3-97e1-4e44-85a7-9450d605e07d)

**Comment by HSunboy** [comment]
Fixed In Commit [d159ed302f3b0dc56ea571c7166e65cf8a72ae94](https://github.com/oceanbase/odc-client/commit/d159ed302f3b0dc56ea571c7166e65cf8a72ae94)
            ------
            咏和
            Sun Dec 10 10:59:51 2023 +0800

**Comment by sl01388797** [comment]
pass
