### ISSUE TITLE
[Bug]: Empty table click to modify result set page crashes

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1086]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/d0d93d92-f79e-4e26-a8f8-bd0f165f7c0e)
![image](https://github.com/oceanbase/odc/assets/143492234/beee7f22-d79d-460a-a55a-597526d812d3)

### What did you expect to happen?

The page will not crash

### How can we reproduce it (as minimally and precisely as possible)?

Click to modify the result set in an empty table

**Comment by HSunboy** [comment]
Fixed In Commit [d159ed302f3b0dc56ea571c7166e65cf8a72ae94](https://github.com/oceanbase/odc-client/commit/d159ed302f3b0dc56ea571c7166e65cf8a72ae94)
            ------
            咏和
            Sun Dec 10 10:59:51 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/25ce052d-de1f-49bb-98ae-4c2307bb0081)
pass
