### ISSUE TITLE
[Bug]: If a check rule that must be corrected is triggered, the expected effect is that the SQL will be directly intercepted.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#1090]
### ODC version

4.2.3

### OB version

All

### What happened?

若执行 SQL ，命中必须改进的规则，现在跳转到了发起工单页面
![image](https://github.com/oceanbase/odc/assets/15030999/5b510a2f-96f6-483b-9c7c-a82d8aa536ff)

### What did you expect to happen?

若执行 SQL ，命中必须改进的规则，直接拦截，不发起工单
![image](https://github.com/oceanbase/odc/assets/15030999/e3a55e72-fd61-44d6-b99c-00448fd9b46c)

### How can we reproduce it (as minimally and precisely as possible)?

As shown in the screenshot, create a new table.

**Comment by HSunboy** [comment]
Fixed In Commit [f7de18b7fae938488489828a3ca0fc4614012c40](https://github.com/oceanbase/odc-client/commit/f7de18b7fae938488489828a3ca0fc4614012c40)
            ------
            陈朝俊
            Wed Dec 13 09:27:46 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9f494bf1-29ed-4dca-a0a9-3d7dbb2780e8)

PASS
