### ISSUE TITLE
[Bug]: failed to flashback an object in recyclebin

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1091]
### ODC version

4.2.3

### OB version

not related

### What happened?

1. select an object and click 'flashback' button.
<img width="920" alt="截屏2023-12-08 19 16 50" src="https://github.com/oceanbase/odc/assets/22992296/2c314f20-ba4c-4f12-983c-43e22283b7db">

2. give the object another name:
<img width="373" alt="截屏2023-12-08 19 18 41" src="https://github.com/oceanbase/odc/assets/22992296/fd184af9-6cb1-456f-85fe-e903738f50e2">

3. click 'submit' button, the object can be flashback normally.
4. select another object and click 'flashback' button:
<img width="1269" alt="截屏2023-12-08 19 24 41" src="https://github.com/oceanbase/odc/assets/22992296/d6b8acbc-b388-44fa-b6fc-5006dc72bad9">

5. click submit button:
<img width="1399" alt="截屏2023-12-08 19 22 16" src="https://github.com/oceanbase/odc/assets/22992296/449815ca-d747-4fdb-9c8f-757f0ab53b51">

### What did you expect to happen?

I can flashback the object normally

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
the pic of the step 4 and step 5 got some problems, I can give a brief a desp:
1. step 4: the object name in table is different from the selected one;
2. step 5: the request object is different from the selected one;

**Comment by HSunboy** [comment]
Fixed In Commit [d159ed302f3b0dc56ea571c7166e65cf8a72ae94](https://github.com/oceanbase/odc-client/commit/d159ed302f3b0dc56ea571c7166e65cf8a72ae94)
            ------
            咏和
            Sun Dec 10 10:59:51 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e9537458-6272-49fe-b8b0-733af4b1190b)

PASS
