### ISSUE TITLE
[Bug]: Failed to create an sql window for oracle schema database name in lower case

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1092]
### ODC version

ODC 4.2.3

### OB version

OB 4.2.1

### What happened?

Failed to create an sql window for oracle schema database name in lower case
![image](https://github.com/oceanbase/odc/assets/46598871/a0bb0ad2-c292-436e-82b9-cd51fc7dee77)

### What did you expect to happen?

Databases with lower-case names can also create sql Windows.

### How can we reproduce it (as minimally and precisely as possible)?

datasource:oracle42222221
database:test新建
Open a sql window

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3a8d2af6-a7f3-43e1-97a9-0a1f6cddc880)

pass
