### ISSUE TITLE
[Bug]: Participants can add databases to the project

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1094]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

The user has manageable rights to the data source and is a project participant ，and he can create and add databases to the project.
![image](https://github.com/oceanbase/odc/assets/46598871/d8322fac-e36b-4f67-b51d-2a023bcc4720)
![image](https://github.com/oceanbase/odc/assets/46598871/217c56f8-1dbf-40f1-97bf-ec14007d8d7f)

### What did you expect to happen?

Participants cannot add databases to a project.

### How can we reproduce it (as minimally and precisely as possible)?

test_user:tonghan_participate
test_project:tonghan_1208
test_data source:test_create_db
Add the database to the data source and bind the project.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4fdb7edb-61f4-417c-a864-0eaad9467d45)

pass
