### ISSUE TITLE
[Bug]: The odc421 version number is still 420

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#110]
### ODC version

odc421

### OB version

any

### What happened?

The odc421 version number is still 420

### What did you expect to happen?

The version number shows 421

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/59468957/facc7e67-2fb4-4fdc-aaa4-683df247b170)

**Comment by HSunboy** [comment]
Fixed In Commit [4addb150b0d9b61da0f1736e96b31dd3911cd30b](https://github.com/oceanbase/odc-client/commit/4addb150b0d9b61da0f1736e96b31dd3911cd30b)
            ------
            晓康
            Tue Sep 5 10:26:25 2023 +0800

**Comment by runzi389205** [comment]
PASS


![Image](https://github.com/oceanbase/odc/assets/141202865/3dcbc436-7472-4f49-8e91-ebadf32f4aab)
