### ISSUE TITLE
[Bug]: If the check result does not contain sql to be approved, the approval button should be gray

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1103]
### ODC version

ODC 423

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/2c702986-a4bf-48ee-be65-fbf4a2a208a7)
If the check result does not contain sql to be approved, the approval button can be clicked.

### What did you expect to happen?

If the check result does not contain sql to be approved, the approval button should be gray.

### How can we reproduce it (as minimally and precisely as possible)?

Perform sql checks on sql.

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [9de6d4368cdd53534dc280f33e9e6ce2286bcfeb](https://github.com/oceanbase/odc-client/commit/9de6d4368cdd53534dc280f33e9e6ce2286bcfeb)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4b380147-f655-4d8a-91d8-f797e325cf30)

pass
