### ISSUE TITLE
[Bug]: The desktop version does not have the sendConnectionAttributes parameter

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1105]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/1cbbabe4-ce70-4cf3-bb76-eb3e90e3bd65)

### What did you expect to happen?

Test link is normal

### How can we reproduce it (as minimally and precisely as possible)?

Desktop version attribute configuration sendConnectionAttributes parameter, click on the test link

**Comment by LuckyPickleZZ** [comment]
known issue, caused by a jdbc bug. Upgrading jdbc to 2.4.8 will fix this.

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/638928d3-97aa-48c5-b47a-41976c7112bb)
pass
