### ISSUE TITLE
[Bug]: Text adjustment when there is no database connection

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#111]
### ODC version

ODC 4.2.1

### OB version

Any version of OceanBase

### What happened?

ODC4.2.0 has removed the connection apply function
![image](https://github.com/oceanbase/odc/assets/46598871/1b04a188-272a-4f3d-af08-be7cf10ae9a9)

### What did you expect to happen?

Remove the request for database connection permission text

### How can we reproduce it (as minimally and precisely as possible)?

View the data source interface when there is no data source connection

**Comment by HSunboy** [comment]
Fixed In Commit [6040651e2e51bea28c817c2b54f831ae30da5ec5](https://github.com/oceanbase/odc-client/commit/6040651e2e51bea28c817c2b54f831ae30da5ec5)
            ------
            晓康
            Tue Sep 5 10:32:07 2023 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/9a2bcc57-91c0-4355-b309-1de03916053b)
pass
