### ISSUE TITLE
[Bug]: osc log is not show and flow task is done unnormally

### ISSUE THREAD

**Issue by krihy** [oceanbase/odc#1113]
### ODC version

4.2.3

### OB version

any

### What happened?

submit osc task and flow task status is done but osc task is not completed， lack many log

![image](https://github.com/oceanbase/odc/assets/51393259/3c6a4166-961c-46ae-b665-874c88fcfa1f)

### What did you expect to happen?

flow task status is done after all osc tasks is completed, show oms step log

![image](https://github.com/oceanbase/odc/assets/51393259/abed6c20-d0c6-4f6d-9430-d2198c1a5bbe)

### How can we reproduce it (as minimally and precisely as possible)?

use odc 4.2.3 to create osc task

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/7132e242-6d7e-4706-9028-b741bb4d8dd7)
pass
