### ISSUE TITLE
[Bug]: The approval initiated in the sql check result contains sql that did not perform the sql check

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1116]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/278b0023-34f2-4e0b-a880-b522d48ab833)
The approval initiated in the sql check result contains sql that did not perform the sql check.

### What did you expect to happen?

Initiate approval for the sql that performs the sql check.

### How can we reproduce it (as minimally and precisely as possible)?

1.Write some sql statements into the sql window.
2.sql check is performed on only part of the sql statements.
3.Initiate approval in sql result.

**Comment by HSunboy** [comment]
Fixed In Commit [f7de18b7fae938488489828a3ca0fc4614012c40](https://github.com/oceanbase/odc-client/commit/f7de18b7fae938488489828a3ca0fc4614012c40)
            ------
            陈朝俊
            Wed Dec 13 09:27:46 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/cc5d92a1-4a1b-45b2-aea5-228aa17e1a29)

pass
