### ISSUE TITLE
[Bug]: There are too many sql check results and can't scroll through the results.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1117]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?
![image](https://github.com/oceanbase/odc/assets/46598871/e7e18049-5de4-4cdc-86ea-7387c84266b2)
There are too many sql check results and can't scroll through the results.

### What did you expect to happen?

Could scroll through the results.

### How can we reproduce it (as minimally and precisely as possible)?

Generate more than 30 sql check results.

**Comment by HSunboy** [comment]
Fixed In Commit [f7de18b7fae938488489828a3ca0fc4614012c40](https://github.com/oceanbase/odc-client/commit/f7de18b7fae938488489828a3ca0fc4614012c40)
            ------
            陈朝俊
            Wed Dec 13 09:27:46 2023 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/fc160f29-3102-4a07-b3d1-c643467af0bc)
pass
