### ISSUE TITLE
[Bug]: sql check results for tables with the same name are incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1118]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/7911b68b-d675-4503-8f65-ae98d0342a1a)
The results for test_null are shown in the results for TEST_NULL.

### What did you expect to happen?

Display the correct sql check results.

### How can we reproduce it (as minimally and precisely as possible)?

CREATE TABLE "GSH"."TEST_NULL" ("A" NUMBER(38),"B" NUMBER(38));
insert into "GSH"."TEST_NULL"("A","B") values(DEFAULT,2),(1,DEFAULT),(3,3);
create table test_null(a int,b int);
insert into test_null values(1,null),(null,2),(3,3);

Create these tables and execute SQL check.

**Comment by yhilmare** [comment]
fixed:
<img width="1061" alt="截屏2023-12-13 11 36 14" src="https://github.com/oceanbase/odc/assets/22992296/47b34157-1e2e-4c44-9ab1-30af282d1494">

**Comment by Huangxiao-mas** [comment]
passed
