### ISSUE TITLE
[Bug]: The highlighting position is incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1120]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/6d99df5e-433b-4560-b9f9-9cf8c12bd238)
The highlighting position is incorrect.

### What did you expect to happen?

The highlight position is correct.

### How can we reproduce it (as minimally and precisely as possible)?

sql check your sql.

**Comment by HSunboy** [comment]
Fixed In Commit [f7de18b7fae938488489828a3ca0fc4614012c40](https://github.com/oceanbase/odc-client/commit/f7de18b7fae938488489828a3ca0fc4614012c40)
            ------
            陈朝俊
            Wed Dec 13 09:27:46 2023 +0800

**Comment by tonghan-gsh** [comment]
![Uploading image.png…]()
pass
