### ISSUE TITLE
[Bug]: README  document wrong password explaination

### ISSUE THREAD

**Issue by krihy** [oceanbase/odc#1123]
### ODC version

4.2.2

### OB version

any

### What happened?

 README password explain is about ODC_ADMIN_INITIAL_PASSWORD, but not other user

### What did you expect to happen?
![image](https://github.com/oceanbase/odc/assets/51393259/91b07cf4-93d4-442c-b212-ff595141f5dc)

1.optimize sample command in README document wrapped  by single quote

### How can we reproduce it (as minimally and precisely as possible)?

use odc 4.2.2

**Comment by yizhouxw** [comment]
'init password support more special character' should be a separated feature, and we already have plan, let's remove from current issue
