### ISSUE TITLE
[Bug]: sql that matches a violation with level of 'have to correct' can start a database change task

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1128]
### ODC version

4.2.3

### OB version

not related

### What happened?

1. type a sql that get a violation with a level of 'have to correct'
<img width="1002" alt="截屏2023-12-12 10 21 41" src="https://github.com/oceanbase/odc/assets/22992296/60542478-65b7-46a1-926f-c344831644fd">

2. execute it directly and database change task panel is appeared:
<img width="1055" alt="截屏2023-12-12 10 22 22" src="https://github.com/oceanbase/odc/assets/22992296/baaae829-b146-477c-aff5-498a69b86ac6">

this is not expected cause that a sql hit a violation with a level of 'have to correct' is not allowed to executed in any cases. the task will not be executed even you start a task:
<img width="375" alt="截屏2023-12-12 10 24 16" src="https://github.com/oceanbase/odc/assets/22992296/c0673ddd-199f-40cd-bea9-a8fc0d4c1c4b">

### What did you expect to happen?

do not start a database change task when a sql hit a violation with 'have to correct' level.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [f7de18b7fae938488489828a3ca0fc4614012c40](https://github.com/oceanbase/odc-client/commit/f7de18b7fae938488489828a3ca0fc4614012c40)
            ------
            陈朝俊
            Wed Dec 13 09:27:46 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/501b09e5-622c-4a21-8b60-6703e2dd6ae2)

PASS
