### ISSUE TITLE
[Bug]: drop index do not generate drop index ddl

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1130]
### ODC version

4.2.3

### OB version

all

### What happened?

<img width="1019" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/4ffd2cef-24aa-41e5-99c0-b0b1db6298b4">
<img width="1592" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/173bfaa6-17d6-47b2-9780-474c3fea4a93">

### What did you expect to happen?

generate drop index success

### How can we reproduce it (as minimally and precisely as possible)?

drop index in table editor

**Comment by HSunboy** [comment]
Fixed In Commit [38cb6946e7b726a4c34231a11e6190e5df20927e](https://github.com/oceanbase/odc-client/commit/38cb6946e7b726a4c34231a11e6190e5df20927e)
            ------
            咏和
            Tue Dec 12 16:35:54 2023 +0800

**Comment by sl01388797** [comment]
pass
