### ISSUE TITLE
[Bug]: Stored procedure view details are displayed in English

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1140]
### ODC version

odc4.2.3

### OB version

oracle324

### What happened?

Stored procedure view details are displayed in English
![image](https://github.com/oceanbase/odc/assets/59468957/6050075f-fda4-4500-8797-750e3a890383)

### What did you expect to happen?

chinese

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
fixed in dev-4.2.3

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f0942fef-a54a-496b-9442-6b11934cb082)

pass
