### ISSUE TITLE
[Bug]: Provide relevant prompts to users for high-risk operations such as index changes when generate update table ddl

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1142]
### ODC version

4.2.3

### OB version

all

### What happened?

Provide relevant prompts to users for high-risk operations such as index changes when generate update table ddl

### What did you expect to happen?

Provide relevant prompts to users for high-risk operations such as index changes when generate update table ddl

### How can we reproduce it (as minimally and precisely as possible)?

White screen creates or deletes an index on a table

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3bc706f7-e5ab-4a74-8b8c-9a8911095efc)

pass

**Comment by sl01388797** [comment]
Public Cloud
create
![image](https://github.com/oceanbase/odc/assets/143492234/15100640-f762-4011-be26-94dbf861c4e9)
delete
![EDCA6726-2838-4c0d-BF9F-81678FE75876](https://github.com/oceanbase/odc/assets/143492234/f671933c-18ca-4db2-adc4-6f17a1543b14)
delete and create
![56EB2B06-4774-4572-9B96-748FA7C895BE](https://github.com/oceanbase/odc/assets/143492234/7484b1c2-4c61-461a-a80f-3272df93d26d)
