### ISSUE TITLE
[Bug]: Execute two identical sql, sql check content is incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1144]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/2e935459-e3db-4ecc-a96c-d5ba0a673170)
The second sql test result is shown in the first one.

### What did you expect to happen?

Display the correct sql check results.

### How can we reproduce it (as minimally and precisely as possible)?

Perform a sql check on two same sql.

**Comment by MarkPotato777** [comment]
The root cause is the same as #1118

**Comment by yhilmare** [comment]
fixed:
<img width="901" alt="截屏2023-12-13 11 31 35" src="https://github.com/oceanbase/odc/assets/22992296/ad60bd60-1ed0-498a-a6eb-0fdaec7cad7c">

**Comment by Huangxiao-mas** [comment]
pass
