### ISSUE TITLE
[Bug]:  The highlight color of need approval and must improver is incorrect in dark mode

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1146]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/448a785e-4c68-4028-a00b-bc577c3fd240)
The highlight color of need approval and must improve is incorrect in dark mode.

### What did you expect to happen?

Swap highlights of need approval and must improve.

### How can we reproduce it (as minimally and precisely as possible)?

Perform sql checks in dark mode.

**Comment by HSunboy** [comment]
Fixed In Commit [f7de18b7fae938488489828a3ca0fc4614012c40](https://github.com/oceanbase/odc-client/commit/f7de18b7fae938488489828a3ca0fc4614012c40)
            ------
            陈朝俊
            Wed Dec 13 09:27:46 2023 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/2ae5c344-d49b-400f-a8db-2e2d08e7c82e)
pass
