### ISSUE TITLE
[Bug]: Every time a DLM task is edited, one more editing record will be added to the task list I initiated.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1149]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

Every time a DLM task is edited, one more editing record will be added to the task list I initiated.

### What did you expect to happen?

chat privately

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by guowl3** [comment]
The record is an approval order, and this order type will be filtered out later.
