### ISSUE TITLE
[Bug]: The task of deploying database changes encountered an error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1150]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/6ed657ac-a033-40fc-b372-0ef0c5140552)
The task of deploying database changes encountered an error

### What did you expect to happen?

The task of deploying database changes completed without any errors.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver a database change task

**Comment by MarkPotato777** [comment]
duplicate with #1067
