### ISSUE TITLE
[Bug]: There is no cancel button for SQL check.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1152]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/b98127f3-3e92-442b-87b1-650fb8f0a316)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/49ed4a70-593f-4a8c-87e7-a5206c45760e)

### How can we reproduce it (as minimally and precisely as possible)?

Perform SQL check in the database change task.

**Comment by UnknownAdventurer** [comment]
this feature is deprecated.
