### ISSUE TITLE
[Bug]: The SQL check content in the approval initiated by executing the statement is incomplete.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1154]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/cbd5fbd7-8148-4a0f-aef0-37c5afded2b8)
![image](https://github.com/oceanbase/odc/assets/46598871/3a21f9fc-eb04-4804-a3dd-177384156642)
The three checks that do not require improvement for this statement are not displayed in the SQL check for the database change.

### What did you expect to happen?

The SQL check for the database change should display all the check contents.

### How can we reproduce it (as minimally and precisely as possible)?

create table test(a int,PRIMARY key(a));

**Comment by yhilmare** [comment]
fixed:
<img width="893" alt="截屏2023-12-13 12 19 42" src="https://github.com/oceanbase/odc/assets/22992296/0976ba91-488e-4188-96d8-9cda5171a51d">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/565bfe6d-8ee8-47be-bc93-cfc02afff9b2)

pass
