### ISSUE TITLE
[Bug]: The environment for creating objects was not updated after changing the data source.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1155]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/6a471d5d-524d-4959-b9ea-f8ea5139f591)
The environment for creating objects was not updated after changing the data source.

### What did you expect to happen?

The environment for creating objects will be updated together with the change of the data source.

### How can we reproduce it (as minimally and precisely as possible)?

1.Update the environment of the data source.
2.Open the interface for creating table objects.

**Comment by HSunboy** [comment]
Fixed In Commit [38a60fe2d8535f341c8720fbe05073b42daac70d](https://github.com/oceanbase/odc-client/commit/38a60fe2d8535f341c8720fbe05073b42daac70d)
            ------
            xiaokang
            Wed Dec 13 14:55:26 2023 +0800

**Comment by tonghan-gsh** [comment]
![Uploading image.png…]()
pass
