### ISSUE TITLE
[Bug]: The results of SQL checks should be displayed when initiating the approval.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1156]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?
![image](https://github.com/oceanbase/odc/assets/46598871/be861ad7-22f4-44a6-a862-2ea93b1b1d42)
The results of SQL checks were not displayed.

### What did you expect to happen?
The results of SQL checks should be displayed when initiating the approval.

### How can we reproduce it (as minimally and precisely as possible)?

nitiating the approval for the results of SQL checks.

**Comment by HSunboy** [comment]
Fixed In Commit [289b5cee4aae7120e114bd6f65e2ccb0460abf87](https://github.com/oceanbase/odc-client/commit/289b5cee4aae7120e114bd6f65e2ccb0460abf87)
            ------
            陈朝俊
            Fri Dec 15 09:38:00 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/119057ff-6dc5-4fd3-9218-1504ff306dd3)

pass
