### ISSUE TITLE
[Bug]: Violation of rules in dark mode with black font that cannot be seen clearly

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1157]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/0323ea0e-e393-403b-bf26-ed3d5b81310d)

### What did you expect to happen?

The font color is white

### How can we reproduce it (as minimally and precisely as possible)?

Check SQL statements

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/ac3e5458-3dc9-4a88-a54c-1beff117ea6b)

**Comment by HSunboy** [comment]
Fixed In Commit [289b5cee4aae7120e114bd6f65e2ccb0460abf87](https://github.com/oceanbase/odc-client/commit/289b5cee4aae7120e114bd6f65e2ccb0460abf87)
            ------
            陈朝俊
            Fri Dec 15 09:38:00 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/608258d9-3ffb-4dd5-a14a-2d840a323c2f)

PASS
