### ISSUE TITLE
[Bug]: Failed to check global snapshot in oracle mode

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1158]
### ODC version

ODC423

### OB version

Oceanbase2277

### What happened?

Failed to check global snapshot in oracle mode
![image](https://github.com/oceanbase/odc/assets/59468957/6cd75a26-63db-4a3e-a627-5b75241ea200)

### What did you expect to happen?

export normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/df4a275c-ab2f-4608-b8c9-eb6d71be7e5b)

pass
