### ISSUE TITLE
[Bug]: SQL statements that violate SQL window guidelines should be intercepted.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1159]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/3d79e802-a23c-4a73-8749-a364d4ceb986)
The SQL statement that violates the SQL window guidelines was not intercepted, and a database change task has been initiated.

### What did you expect to happen?

SQL statements that violate SQL window guidelines should be intercepted.

### How can we reproduce it (as minimally and precisely as possible)?

Executing SQL statements that violate SQL window guidelines.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/88aaf337-c2ea-415d-8362-6a1ea548987c)

pass
