### ISSUE TITLE
[Bug]: OceanBase 4.2.0 executes the DEBUG_ON function, and the page is always in the request

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#116]
### ODC version

odc421

### OB version

ob420

### What happened?

The front-end page is always in the request

### What did you expect to happen?

Execute normally or give a hint

### How can we reproduce it (as minimally and precisely as possible)?

Execute：
CALL DBMS_DEBUG.DEBUG_ON();
![image](https://github.com/oceanbase/odc/assets/59468957/00a74ef8-515b-417d-a8a0-373d825da30b)

**Comment by yhilmare** [comment]
it can not be reproduced for me:
<img width="726" alt="截屏2023-09-01 15 52 45" src="https://github.com/oceanbase/odc/assets/22992296/754f6196-2f74-488a-90dd-cc4e8f3e426b">

you may retry it by obclient @Huangxiao-mas

**Comment by Huangxiao-mas** [comment]
![image](https://github.com/oceanbase/odc/assets/59468957/70771362-f0ff-4a51-9b55-826c844433a0)

**Comment by yhilmare** [comment]
we can reproduce this issue by obclient as follow:
<img width="565" alt="截屏2023-09-01 16 16 12" src="https://github.com/oceanbase/odc/assets/22992296/0a7145da-eb74-4280-9aa7-e60bd352af44">

**Comment by yhilmare** [comment]
This is a normal phenomenon. ODC will execute the logic of DBMS output query after executing a SQL:
```SQL
DECLARE
  L_LINES       DBMS_OUTPUT.CHARARR;
  L_NUM         INTEGER := 2000;
  L_LINES_ARRAY CLOB;
BEGIN
  DBMS_OUTPUT.GET_LINES(L_LINES, L_NUM);
  IF L_NUM > 0 THEN
    FOR i IN 1 .. L_NUM LOOP
      IF i = 1 THEN
          L_LINES_ARRAY := L_LINES(i);
      ELSE
          L_LINES_ARRAY := L_LINES_ARRAY || '
' || L_LINES(i);
      END IF;
    END LOOP;
  END IF;
END;
```

When debug_on is executed, debugging will be enabled, and the kernel will hang while waiting for debugging when the next sql is executed.

**Comment by runzi389205** [comment]
PASS

![Image](https://github.com/oceanbase/odc/assets/141202865/a747206d-c04e-466f-8e81-8ea0d0f71759)
