### ISSUE TITLE
[Bug]: No error prompt when violating SQL specification detection and SQL window specification in creating a new table

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1160]
### ODC version

odc423

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/91025f8b-ed0f-40ed-a577-fcc316e0a67c

![image](https://github.com/oceanbase/odc/assets/143492234/e59c9130-ab10-48c7-a030-86826ce05a13)

### What did you expect to happen?

SQL execution successful or error reported

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL violation detection or SQL window specification in the newly created table

**Comment by HSunboy** [comment]
Fixed In Commit [289b5cee4aae7120e114bd6f65e2ccb0460abf87](https://github.com/oceanbase/odc-client/commit/289b5cee4aae7120e114bd6f65e2ccb0460abf87)
            ------
            陈朝俊
            Fri Dec 15 09:38:00 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e2db32fd-4f80-49c3-8742-34687398335a)

PASS
