### ISSUE TITLE
[Bug]: sql check can not prompt user a table without table comment when there exists two table with same name

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1161]
### ODC version

4.2.3

### OB version

not related

### What happened?

1. type two table definitions with the same table name:
```SQL
create table asdasd(
    id varchar2(64)
);
create table asdasd(
    id varchar2(64)
);
``` 
2. click `sql-check` button:
<img width="932" alt="截屏2023-12-13 11 46 00" src="https://github.com/oceanbase/odc/assets/22992296/67aa4eb8-8200-45dd-8d50-b659f9ae1950">

3. as you can see: the second table get no violation that table without table comments.
4. the sql-check can give violation if the second table with a different name:
<img width="959" alt="截屏2023-12-13 11 47 29" src="https://github.com/oceanbase/odc/assets/22992296/276e1b0b-ca64-42fc-a28d-f608e7c68a83">

### What did you expect to happen?

the sql-check can prompt user even there exists two tables with same name

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
fixed:
<img width="1033" alt="截屏2023-12-13 12 22 12" src="https://github.com/oceanbase/odc/assets/22992296/9be5d2d6-384f-47ac-8685-a11905071c45">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8310bed2-3275-40b9-bbf4-bf782039c6bc)

pass
