### ISSUE TITLE
[Bug]: If the SQL execution violates the SQL window inspection specification, no SQL inspection is performed.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1166]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

If the executed sql violates the sql window specification, there is no sql check for the sql.

### What did you expect to happen?

Perform sql check on executed sql.

### How can we reproduce it (as minimally and precisely as possible)?

Execute sql that violates sql window specification.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9ffe5558-2aae-4999-b08e-3bd237030957)

pass
