### ISSUE TITLE
[Bug]: User name input box, background will overlap with input

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1167]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/72b90879-a557-4a11-a781-d3109003341f)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/d7edb707-e131-4bc1-9041-dccfa6a31e43)

### How can we reproduce it (as minimally and precisely as possible)?

Enter username in the login window

**Comment by HSunboy** [comment]
Probably a chrome bug
