### ISSUE TITLE
[Bug]: Executing sql, the front end crashes

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1168]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

Executing sql, the front end crashes
![image](https://github.com/oceanbase/odc/assets/59468957/2c279d12-0ef9-4451-9ff3-5a59b482f308)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by MarkPotato777** [comment]
The root cause is the same as #1067
