### ISSUE TITLE
[Bug]: If the dlm condition does not enter a value, click Save, and the front end reports an undefined error.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1169]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

If the dlm condition does not enter a value, click Save, and the front end reports an undefined error.
![image](https://github.com/oceanbase/odc/assets/59468957/e6e110c9-9077-4b73-8c62-e86c52f8fa96)

### What did you expect to happen?

chat priavtely

### How can we reproduce it (as minimally and precisely as possible)?

chat priavtely

**Comment by HSunboy** [comment]
Fixed In Commit [9dcb61170f79ea716c4d03fdff5a6267013b1daf](https://github.com/oceanbase/odc-client/commit/9dcb61170f79ea716c4d03fdff5a6267013b1daf)
            ------
            咏和
            Tue Dec 19 09:16:15 2023 +0800
