### ISSUE TITLE
[Bug]: The sql audit integration intercepts the execution of sql, but there is no output on the console.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1175]
### ODC version

ODC423

### OB version

independent

### What happened?

The sql audit integration intercepts the execution of sql, but there is no output on the console.
![image](https://github.com/oceanbase/odc/assets/59468957/3091eac2-98dc-4a09-8f7c-c234662b3eff)

### What did you expect to happen?

show normally

### How can we reproduce it (as minimally and precisely as possible)?

chat priavtely

**Comment by HSunboy** [comment]
Fixed In Commit [289b5cee4aae7120e114bd6f65e2ccb0460abf87](https://github.com/oceanbase/odc-client/commit/289b5cee4aae7120e114bd6f65e2ccb0460abf87)
            ------
            陈朝俊
            Fri Dec 15 09:38:00 2023 +0800
