### ISSUE TITLE
[Bug]: failed to view the white space in dbms output

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1176]
### ODC version

4.2.3

### OB version

not related

### What happened?

1. type such a anonymous block:
```SQL
DECLARE
i char(30) default '09     d        c     n';
BEGIN
dbms_output.put_line('aaa'||i||'bbb'||''||'ccc');
END;
```
2. execute it and we expect that the dbms_output contains several white space:
![CF0744DB-6187-459D-A9E0-B0658C4849B9](https://github.com/oceanbase/odc/assets/22992296/73fada7f-ef0e-4eae-971f-870d2977361f)

as you can see, there is no several white space and the api's response is normal

### What did you expect to happen?

show dbms_output normally

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [c1fede16e3ffc7523a89325c550087a46ad09534](https://github.com/oceanbase/odc-client/commit/c1fede16e3ffc7523a89325c550087a46ad09534)
            ------
            xiaokang
            Wed Dec 20 11:21:05 2023 +0800
