### ISSUE TITLE
[Bug]: table columns disappear when drag table name  left object tree to sql console in different mode

### ISSUE THREAD

**Issue by krihy** [oceanbase/odc#1178]
### ODC version

4.2.2

### OB version

4.0

### What happened?

table columns disappear when drag table name  left object tree to sql console in different mode

### What did you expect to happen?

show table columns in sql console

### How can we reproduce it (as minimally and precisely as possible)?

create table in ob mysql and drag to ob oracle sql console

**Comment by HSunboy** [comment]
Fixed In Commit [3a16839bf05149f6af9732baa55f2da6c070cc78](https://github.com/oceanbase/odc-client/commit/3a16839bf05149f6af9732baa55f2da6c070cc78)
            ------
            xiaokang
            Wed Feb 28 09:41:22 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3d36aec7-bad3-428d-b336-f86aa7a863a3)

pass
