### ISSUE TITLE
[Bug]: When the current account does not have the task, an error message will appear when entering through the sharing link

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1180]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b1bdf2f5-ec60-4b40-8f03-d0d5b163bb3b)

### What did you expect to happen?

Jump to login page

### How can we reproduce it (as minimally and precisely as possible)?

1. Copy a task
2. Open a link in an account without changing tasks

**Comment by HSunboy** [comment]
Fixed In Commit [c1fede16e3ffc7523a89325c550087a46ad09534](https://github.com/oceanbase/odc-client/commit/c1fede16e3ffc7523a89325c550087a46ad09534)
            ------
            xiaokang
            Wed Dec 20 11:21:05 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6cfdf2eb-e3ee-4631-9db6-3725030e3123)

pass
