### ISSUE TITLE
[Bug]: In the desktop version, if the Oracle schema library name is in lowercase letters, the database cannot be opened.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1185]
### ODC version

ODC423

### OB version

Oceanbase2277

### What happened?

In the desktop version, if the Oracle schema library name is in lowercase letters, the database cannot be opened.
![image](https://github.com/oceanbase/odc/assets/59468957/37b449f2-544e-41c2-becd-92dd8d7a5af5)
![image](https://github.com/oceanbase/odc/assets/59468957/a823cb86-3b97-4c53-9c37-870db132e358)

### What did you expect to happen?

The web version can open this table, just like the web version

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/22a36edd-935a-436b-b34c-8df13fd8e2f6)

pass
