### ISSUE TITLE
[Bug]: Quickly generate select statements and prompt that the table does not exist

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1187]
### ODC version

ODC4.2.3

### OB version

Oceanbase2277

### What happened?

Quickly generate select statements and prompt that the table does not exist
![image](https://github.com/oceanbase/odc/assets/59468957/e1d551a7-7024-4de6-b10b-f813af3f2692)
![image](https://github.com/oceanbase/odc/assets/59468957/5988e4fc-e7e6-436d-b950-e48cf63fe9af)

### What did you expect to happen?

can execute normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Cross-database dragging is not supported
