### ISSUE TITLE
[Bug]: it shows duplicated environment info on the top if the screen when creating a view

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#1189]
### ODC version

4.2.3

### OB version

not related

### What happened?

In the last step of creating a view, it shows duplicated environment information on the top of the screen.
![image](https://github.com/oceanbase/odc/assets/39962741/63f9f15a-bb68-48a1-a71b-28ab73fe3530)

### What did you expect to happen?

It is supposed to show only one line of environment info.

### How can we reproduce it (as minimally and precisely as possible)?

create a view

**Comment by HSunboy** [comment]
Fixed In Commit [5c9f4a6b0f0e3dc2349aba5392c06092e953c1ca](https://github.com/oceanbase/odc-client/commit/5c9f4a6b0f0e3dc2349aba5392c06092e953c1ca)
            ------
            陈朝俊
            Wed Dec 20 11:22:32 2023 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/039b54df-a106-4166-92c9-627f9a9ce3ef)

pass
