### ISSUE TITLE
[Bug]: When disabling the export of result sets, the table data can be exported

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1191]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/c867c2e0-5834-4f43-b4b2-5d47639590a6)
![image](https://github.com/oceanbase/odc/assets/143492234/67c38d20-29d6-45a3-9f86-77c5b3c1394c)

### What did you expect to happen?

Unable to export table data

### How can we reproduce it (as minimally and precisely as possible)?

Enable the prohibition of exporting result sets
Viewing Table Data

**Comment by MarkPotato777** [comment]
![Image](https://github.com/oceanbase/odc/assets/39962741/7698a9d7-e64d-4691-8a99-73ef845770ea)

**Comment by HSunboy** [comment]
Fixed In Commit [54622ce47d898da7c82fec32f7f956612c64f361](https://github.com/oceanbase/odc-client/commit/54622ce47d898da7c82fec32f7f956612c64f361)
            ------
            陈朝俊
            Tue Dec 19 09:17:20 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/1956e664-1750-4c3c-ab63-04fb9183d59d)
PASS
