### ISSUE TITLE
[Bug]: After creating a function or stored procedure that triggers database change approval, the creation fails and a syntax error is reported.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1192]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

After creating a function or stored procedure that triggers database change approval, the creation fails and a syntax error is reported.
![image](https://github.com/oceanbase/odc/assets/59468957/bf3f53d8-94f8-4eeb-8695-9847149ee710)

### What did you expect to happen?

can exectute nornamlly

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by smallsheeeep** [comment]
The same procedure works for me:
<img width="639" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/7d2d1989-1781-4f3b-bec5-5a1e379b08ee">

**Comment by smallsheeeep** [comment]
When init  a database change task, we must set a right delimiter here:
