### ISSUE TITLE
[Bug]: Sys account click test link error

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1193]
### ODC version

odc423

### OB version

*

### What did you expect to happen?

No error will be reported

### How can we reproduce it (as minimally and precisely as possible)?

Set up a sys account within the link, click to test

**Comment by yhilmare** [comment]
<img width="845" alt="截屏2023-12-18 10 22 23" src="https://github.com/oceanbase/odc/assets/22992296/e156aeb6-1092-499a-9b49-b1a91657d356">

can not reproduced. It looks like the encryption problem, you ,ay refresh the web page to refresh the cipher
