### ISSUE TITLE
[Bug]: The data source is exported after configuring the SYS user. The user permissions are incorrect.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1195]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

The data source is exported after configuring the SYS user. The user permissions are incorrect.
![image](https://github.com/oceanbase/odc/assets/59468957/92b73f57-b06a-4e3c-87b8-088024bbac1c)

### What did you expect to happen?

The data source is exported after configuring the SYS user. can export normally

### How can we reproduce it (as minimally and precisely as possible)?

create datasource 
configuring  the sys

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3db25197-cb03-420f-be32-ae78d052e850)

pass
