### ISSUE TITLE
[Bug]: Desktop version execution plan details check box optimization

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1197]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

Desktop version execution plan details check box optimization
![image](https://github.com/oceanbase/odc/assets/59468957/88a149db-1690-44c2-8edb-55e99ca2e2a8)
![image](https://github.com/oceanbase/odc/assets/59468957/837c43ae-54b1-4293-855b-314a0c5d00be)

### What did you expect to happen?

Maybe this box can be moved a little to the left

### How can we reproduce it (as minimally and precisely as possible)?

---

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8ea63782-7603-4a42-9f5f-bda0ce38672e)

pass
