### ISSUE TITLE
[Bug]: ODP cannot connect

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1199]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

ODP cannot connect
![Uploading image.png…]()

### What did you expect to happen?

can connect

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by yhilmare** [comment]
![20231218112802](https://github.com/oceanbase/odc/assets/22992296/864ccf83-1f3e-4104-9634-afdb48d0435f)

the observer may be crashed.

**Comment by Huangxiao-mas** [comment]
PASS
