### ISSUE TITLE
[Bug]: Exporting the result set to excel failed, and converting csv to excel failed.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1201]
### ODC version

ODC4.2.3

### OB version

OCeanbase2277

### What happened?

Exporting the result set to excel failed, and converting csv to excel failed.
![image](https://github.com/oceanbase/odc/assets/59468957/3668ea49-65bd-4f31-9839-3ecb6da67adb)

### What did you expect to happen?

can export normmally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

### Anything else we need to know?

chat privately

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/37a76dad-945f-4d38-8fbe-fa2135fd9226)

pass
