### ISSUE TITLE
[Bug]: oceanbase version is lower than 4.x，Desktop version does not have export file limit option

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1203]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

Desktop version does not have export file limit option
![image](https://github.com/oceanbase/odc/assets/59468957/fef48f47-f1a7-4c31-928f-02b5f1327a0a)

### What did you expect to happen?

has this box

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Fixed In Commit [c1fede16e3ffc7523a89325c550087a46ad09534](https://github.com/oceanbase/odc-client/commit/c1fede16e3ffc7523a89325c550087a46ad09534)
            ------
            xiaokang
            Wed Dec 20 11:21:05 2023 +0800
