### ISSUE TITLE
[Bug]: do not disable adding sensitive columns for mysql datasource 

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#1204]
### ODC version

4.2.3

### OB version

none

### What happened?

now when adding sensitive columns ,  the front-end will filter mysql datasource. We hope to cancel this restriction. 

### What did you expect to happen?

cancel this restriction. 

### How can we reproduce it (as minimally and precisely as possible)?

-

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [54622ce47d898da7c82fec32f7f956612c64f361](https://github.com/oceanbase/odc-client/commit/54622ce47d898da7c82fec32f7f956612c64f361)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/07d48b02-b72f-4e56-a1b6-e840c889f70a)

PASS
