### ISSUE TITLE
[Bug]: After creating an export task in the desktop version, the log file first prompts that the task has expired, and then displays normally after a while.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1205]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

After creating an export task in the desktop version, the log file first prompts that the task has expired, and then displays normally after a while.
![image](https://github.com/oceanbase/odc/assets/59468957/7e80ef29-1d72-481a-83b4-19a6e1879a8a)

### What did you expect to happen?

can execute normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5f698d0f-e8e4-4f4c-97e7-c13a67db0162)

pass
