### ISSUE TITLE
[Bug]: The second time scanning the sensitive column, there are still settings from the previous time

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1207]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/69f4a6dd-93fc-453c-abbc-4302d3882b6c)

### What did you expect to happen?

No previous settings exist

### How can we reproduce it (as minimally and precisely as possible)?

1. Open scan to add sensitive columns
2. Turn on scanning sensitive columns again

**Comment by HSunboy** [comment]
Fixed In Commit [d33bbd70f07d2a78465a204fde1c0dd9d5a08ba7](https://github.com/oceanbase/odc-client/commit/d33bbd70f07d2a78465a204fde1c0dd9d5a08ba7)
            ------
            陈朝俊
            Tue Dec 19 19:07:12 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/986e69eb-49d4-4701-85c3-97cb5e7bc04a)

PASS
