### ISSUE TITLE
[Bug]: When clicking to view the table in the desktop version, the front end crashes

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1209]
### ODC version

ODC4.2.3

### OB version

OCeanbase420

### What happened?

When clicking to view the table in the desktop version, the front end crashes
![image](https://github.com/oceanbase/odc/assets/59468957/b06974aa-8395-4afe-8278-fc7b9b4be828)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/17d86f22-1807-4666-908e-031ccab932f4)

PASS
