### ISSUE TITLE
[Bug]: Unable to execute SQL generated after modifying the result set

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1210]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/079fda6b-5e7a-40a6-886a-3682cd4df6d4)

### What did you expect to happen?

Can execute SQL or provide prompts

### How can we reproduce it (as minimally and precisely as possible)?

Modify the result set and execute SQL

**Comment by HSunboy** [comment]
Fixed In Commit [a85b7ba57951e1d6358c56563eed4669d27db5bf](https://github.com/oceanbase/odc-client/commit/a85b7ba57951e1d6358c56563eed4669d27db5bf)
            ------
            陈朝俊
            Tue Dec 19 19:07:01 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/3d6df162-def3-4b5e-b167-aa7e0382d362)
PASS
