### ISSUE TITLE
[Bug]: The front end of the partition plan task is blocked

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1211]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/8a945ab7-c062-4b33-a983-48a44d579138)
When creating a new partition plan, the front end for editing the partition strategy is blocked.

### What did you expect to happen?

The front end of editing partition policy is not blocked.

### How can we reproduce it (as minimally and precisely as possible)?

Create a partition plan

**Comment by HSunboy** [comment]
Fixed In Commit [9dcb61170f79ea716c4d03fdff5a6267013b1daf](https://github.com/oceanbase/odc-client/commit/9dcb61170f79ea716c4d03fdff5a6267013b1daf)
            ------
            咏和
            Tue Dec 19 09:16:15 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e18e04c2-899d-40be-aebb-80859a917e0e)

pass
