### ISSUE TITLE
[Bug]: executing sql is not recorded in audit event

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#1214]
### ODC version

4.2.3

### OB version

not related

### What happened?

I executed SQL in the SQL console, but I cannot see records in audit events.

### What did you expect to happen?

I can see records of executing SQLs in audit events.

### How can we reproduce it (as minimally and precisely as possible)?

As I said in 'When happened'.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/45f949ad-6b44-46ba-a2bf-539ed15578ef)

pass
