### ISSUE TITLE
[Bug]: The partition plan execution cycle has cached values

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1226]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/57b16348-6ea7-4601-86f6-12d631af7f12)
Create a partition plan, and the data displayed in the execution cycle is the cycle of the previous task

### What did you expect to happen?

Clear execution cycle data

### How can we reproduce it (as minimally and precisely as possible)?

After issuing a partition planning task, issue another one again.

**Comment by HSunboy** [comment]
Fixed In Commit [1928d46a5a4a27e1e71111a51d67191949b4edb7](https://github.com/oceanbase/odc-client/commit/1928d46a5a4a27e1e71111a51d67191949b4edb7)
            ------
            咏和
            Tue Dec 19 19:06:12 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/54d0fe21-96d1-441d-8817-ffbc4fe3aa53)

pass
