### ISSUE TITLE
[Bug]: large queries of OceanBase Oracle 4.2 are very slow even if already set the query limit on ODC

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#1229]
### ODC version

4.2.2

### OB version

OceanBase Oracle 4.2

### What happened?

large queries of OceanBase Oracle 4.2 are very slow even if already set the query limit on ODC

### What did you expect to happen?

when I set the query limit, large queries should not be such slow.

### How can we reproduce it (as minimally and precisely as possible)?

1. Set the query limit in the SQL console.
2. Query a table with a large number of rows.

**Comment by Huangxiao-mas** [comment]
test pass
