### ISSUE TITLE
[Bug]: GET DIAGNOSTICS Statement does not supported for mysql mode

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#123]
### ODC version

4.2.0

### OB version

4.1.0

### What happened?

does not support syntax `GET DIAGNOSTICS`.

while use  ` GET DIAGNOSTICS CONDITION 1 res_desc= MESSAGE_TEXT;`

result into syntax error, SQL Check result:
You have an error in your SQL syntax; check the manual for the right syntax to use near 'N\n\n GET DIAGNOSTICS...' at line 67, col 12

 and the parameters will be empty.
![image](https://github.com/oceanbase/odc/assets/54161870/cbf2b339-230a-4dd4-bb33-80883d0d710c)

### What did you expect to happen?

no  syntax error, the parameters can shown in detail page of procedure

### How can we reproduce it (as minimally and precisely as possible)?

smply use below statement.

```
GET DIAGNOSTICS @p1 = NUMBER, @p2 = ROW_COUNT;
```

refer more from https://dev.mysql.com/doc/refman/5.7/en/get-diagnostics.html

**Comment by yhilmare** [comment]
OceanBase 4.1.0 adds several new syntaxes, and I have updated the g4, but we need to update maven central repo and upgrade version number to make theses changed work which cost too much, can we move it to 4.2.2
@yizhouxw

**Comment by yhilmare** [comment]
fixed:
<img width="726" alt="截屏2023-09-04 16 37 46" src="https://github.com/oceanbase/odc/assets/22992296/fdab71da-3a32-451a-8de6-eb1fb8ca752b">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b99430b7-aa8c-4162-9812-2dfd3246e176)

pass
