### ISSUE TITLE
[Bug]: Clicking on the add variable page in data cleaning crashes

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1230]
### ODC version

odc423

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/fbbcb086-c2c4-488d-807b-b150dd5d9254

### What did you expect to happen?

The page will not crash

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by bluesky-xyh** [comment]
fixed

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/d8d0e29d-7b5a-4fd1-a546-79041f9c6738)
pass
