### ISSUE TITLE
[Bug]: The SQL window will not disappear after the execution of SQL within the table data is completed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1239]
### ODC version

odc423

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/7aa860b9-9a83-448f-bc4e-44b1449f298a

### What did you expect to happen?

After SQL execution is completed, the SQL window disappears

### How can we reproduce it (as minimally and precisely as possible)?

Execute generated SQL within table data

**Comment by HSunboy** [comment]
Fixed In Commit [935690bb4b3296061a4872ab69e02e090525eef1](https://github.com/oceanbase/odc-client/commit/935690bb4b3296061a4872ab69e02e090525eef1)
            ------
            陈朝俊
            Wed Dec 20 11:23:16 2023 +0800
