### ISSUE TITLE
[Bug]: show table partition name with "`"

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1244]
### ODC version

4.2.2、4.2.3

### OB version

ob 4.2.1

### What happened?

If the partition name in the table's ddl contains an identifier, the displayed partition name also contains the identifier.
<img width="667" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/9d1e2190-a293-45e9-928f-69e02995e4cd">

### What did you expect to happen?

partition name do not contains the identifier.

### How can we reproduce it (as minimally and precisely as possible)?

in ob mysql 4.2.1 create a parition table and the partition name in the table's ddl contains an identifier

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/23088c18-d386-4980-a30f-fe3eb20a6138)

pass
