### ISSUE TITLE
[Bug]: ODP type data source, simulation data list cannot be displayed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1245]
### ODC version

ODC423

### OB version

ODP

### What happened?

ODP type data source, simulation data list cannot be displayed
![image](https://github.com/oceanbase/odc/assets/59468957/389dda69-69c1-4bc5-b104-fa163a4c43fd)

### What did you expect to happen?

Be able to show

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by PeachThinking** [comment]
ODP sharding mysql mode donnot support mock data


![Image](https://github.com/oceanbase/odc/assets/140503120/d4aeb533-2e85-4676-90a8-b9fd25c678a4)

**Comment by HSunboy** [comment]
Fixed In Commit [a43e6654852465c9d6802f12f69010d9bce57e48](https://github.com/oceanbase/odc-client/commit/a43e6654852465c9d6802f12f69010d9bce57e48)
            ------
            xiaokang
            Thu Dec 21 09:51:42 2023 +0800
