### ISSUE TITLE
[Bug]: Pre-inspect first and then perform the inspection. The results are not displayed and require approval.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1255]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/cb5d2744-1b1d-41b5-891e-d973ee7c55bc)
Pre-inspect first and then perform the inspection. The results are not displayed and require approval.

### What did you expect to happen?

Inspection results display requires approval prompts

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened

**Comment by HSunboy** [comment]
Fixed In Commit [229a92c633a8943259a5bb92a4a9b8d0082ddc44](https://github.com/oceanbase/odc-client/commit/229a92c633a8943259a5bb92a4a9b8d0082ddc44)
            ------
            陈朝俊
            Thu Dec 21 13:51:31 2023 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/b635ff92-b207-4e3c-bbcb-db133586ddf6)

pass
