### ISSUE TITLE
[Bug]: When SQL checks that there is no statement that requires approval, it still prompts that approval is required.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1256]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/c017674c-282f-41f8-8d81-dafd6eb567a8)
When SQL checks that there is no statement that requires approval, it still prompts that approval is required.

### What did you expect to happen?

When sql checks that there is no statement that requires approval, there will be no prompt that approval is required.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened

**Comment by HSunboy** [comment]
Fixed In Commit [229a92c633a8943259a5bb92a4a9b8d0082ddc44](https://github.com/oceanbase/odc-client/commit/229a92c633a8943259a5bb92a4a9b8d0082ddc44)
            ------
            陈朝俊
            Thu Dec 21 13:51:31 2023 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/13419f37-e525-4bc5-8539-ed620baa5eec)

pass
