### ISSUE TITLE
[Bug]: creates shadow tables and optimizes the speed of database structure analysis

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1257]
### ODC version

ODC423

### OB version

Oceanbase420-mysql

### What happened?

Oceanbase420MYSQL creates shadow tables and optimizes the speed of database structure analysis
![image](https://github.com/oceanbase/odc/assets/59468957/4f4ffc8a-2905-4954-865d-dd61b59898a6)

### What did you expect to happen?

optimizes

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by MarkPotato777** [comment]
There exists a performance issue when querying database object metadata. Your test case has 603 tables and 3731 indexes. The problem happened in querying indexes as we needed to query each table's ddl to find out if the index was local or global.
