### ISSUE TITLE
[Bug]: click log out of the personal space and report that "CSRF TOKEN" is missing

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1258]
### ODC version

ODC423

### OB version

independent

### What happened?

Click to log out of the personal space and report that "CSRF TOKEN" is missing.
![image](https://github.com/oceanbase/odc/assets/59468957/22d0e7d0-1931-42ca-9183-a2803d2ee3da)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

Click to log out of the personal space

**Comment by HSunboy** [comment]
Fixed In Commit [9f266b438e30b208c8632ab305df78d3c876cde6](https://github.com/oceanbase/odc-client/commit/9f266b438e30b208c8632ab305df78d3c876cde6)
            ------
            xiaokang
            Thu Dec 21 13:49:03 2023 +0800
