### ISSUE TITLE
[Bug]:  project-A's "pending approval" tickets shows project-B's "pending approval" tickets

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#1259]
### ODC version

4.2.3

### OB version

not related

### What happened?

 project-A's "pending approval" tickets show project-B's "pending approval" tickets

### What did you expect to happen?

 project-A's "pending approval" tickets only show project-A's "pending approval" tickets

### How can we reproduce it (as minimally and precisely as possible)?

1. create a ticket that needs approving in project A;
2. view project-B's "pending approval" tickets

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/72ab1757-42f2-442b-a857-c2b4ad1fde33)



![Image](https://github.com/oceanbase/odc/assets/143492234/8f1918cb-af16-4bae-aed1-0adb4d87f575)

pass
