### ISSUE TITLE
[Feature]: add a sql check rule to guide user change index safely

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1261]
### Is your feature request related to a problem?

yeah, related to a user

### Describe the solution you'd like

User can user this sql script: `alter table xxx drop index xxx, add index xxx` to drop the old index and create a new one in native mysql, cause that this operation in mysql is atomic which is not atomic in ob mysql, so that the dbms will face the risk (including cpu high overload).

I want to add a new sql check rule to guide user how to change the index:
1. we should create a new index that can replace the older one
2. delete the older index

**Comment by Jane201510** [comment]
![Uploading image.png…]()
