### ISSUE TITLE
[Bug]: SQL security rule management for operation records not translated into English

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1262]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2c28244e-c98a-4f42-b986-80cdaad70900)

### What did you expect to happen?

Translate SQL security rule management into English

### How can we reproduce it (as minimally and precisely as possible)?

1. Translate English
2. View operation records

**Comment by HSunboy** [comment]
Fixed In Commit [54b46a92db5de96bfe911eadd0809a3e1390ae18](https://github.com/oceanbase/odc-client/commit/54b46a92db5de96bfe911eadd0809a3e1390ae18)
            ------
            xiaokang
            Thu Dec 21 17:21:43 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9c46cb65-14d0-4a67-a7fe-ffbcd0cfd79f)

pass
