### ISSUE TITLE
[Bug]: View the inspection results in task details, click to turn the page, and the front end crashes.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1263]
### ODC version

ODC423

### OB version

independent

### What happened?

View the inspection results in task details, click to turn the page, and the front end crashes.
![image](https://github.com/oceanbase/odc/assets/59468957/5aa8c64d-dcef-48b7-a7b2-ac6e6c504561)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [6086aaeadb0d2d3bf9d4edb0280769ad5f9b308a](https://github.com/oceanbase/odc-client/commit/6086aaeadb0d2d3bf9d4edb0280769ad5f9b308a)
