### ISSUE TITLE
[Bug]: Check result page turning component displays NAN

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1264]
### ODC version

odc423

### OB version

independent

### What happened?

Check result page turning component displays NAN
![image](https://github.com/oceanbase/odc/assets/59468957/34240f40-eb7e-4780-8b09-35a315c533b4)

### What did you expect to happen?

There is only one data, no page turning is displayed

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [6086aaeadb0d2d3bf9d4edb0280769ad5f9b308a](https://github.com/oceanbase/odc-client/commit/6086aaeadb0d2d3bf9d4edb0280769ad5f9b308a)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/c0f84a0a-4a01-49a2-96f0-2776a86cfaa0)

pass
