### ISSUE TITLE
[Bug]: The column of date type cannot display the time properly.

### ISSUE THREAD

**Issue by liuwy1005** [oceanbase/odc#1267]
### ODC version

4.2.2

### OB version

4.2.1

### What happened?

select sysdate from dual return only date no time.
![image](https://github.com/oceanbase/odc/assets/76543602/803a2177-60fc-47b1-b2da-8206349a1207)

### What did you expect to happen?

return date and time

### How can we reproduce it (as minimally and precisely as possible)?

select sysdate from dual 
or select any column(s) which type is date.

**Comment by yhilmare** [comment]
we have fixed this issue at #1008, we will release this version today or tomorrow, you can upgrade the odc to fix this issue

**Comment by yhilmare** [comment]
duplicated as #975
