### ISSUE TITLE
[Bug]: Native MySQL failed to execute simulated data

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1269]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/4a47baf8-ba82-4af8-a529-236a4b655b01)

### What did you expect to happen?

Simulated data successful

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/143492234/4ee8f574-52ec-4846-a13d-e8018d15e5a9)

**Comment by yhilmare** [comment]
fixed:
<img width="379" alt="截屏2023-12-21 18 03 30" src="https://github.com/oceanbase/odc/assets/22992296/bad81287-9046-409f-a992-5ceabb5108c2">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/aec1aea2-eff2-4dae-8974-3be467b960ad)

pass
