### ISSUE TITLE
[Bug]: Database change generation backup rollback plan failed on desktop version

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#127]
### ODC version

odc4.2.1

### OB version

ob4.2.0.1

### What happened?

Choose to generate a backup rollback plan when executing database changes

### What did you expect to happen?

Download backup rollback after execution is completed

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/143492234/e3fdc438-d9ff-43d7-8101-0115c13db607)
![image](https://github.com/oceanbase/odc/assets/143492234/5c043828-ebe6-40fd-9afd-87607649fbb1)

**Comment by tonghan-gsh** [comment]
![Uploading image.png…]()
pass
