### ISSUE TITLE
[Bug]: The page turning component of the check result page displays abnormally

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1278]
### ODC version

ODC423

### OB version

independent

### What happened?

The page turning component of the check result page displays abnormally
![image](https://github.com/oceanbase/odc/assets/59468957/c9a583e4-7010-4224-95c7-d2030c4364ab)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

### Anything else we need to know?

chat privately

**Comment by UnknownAdventurer** [comment]
This bug is fixed
