### ISSUE TITLE
[Bug]: The optionally supported data source types in the security specification are incorrect

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1279]
### ODC version

4.2.3

### OB version

all

### What happened?

The optionally supported data source types in the security specification are incorrect：
<img width="1631" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/49ebc4ca-b2fe-48f0-9772-829c11973ad8">

### What did you expect to happen?

show ODP_sharding_mysql type

### How can we reproduce it (as minimally and precisely as possible)?

as above

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/4a69418f-a1ad-4edc-af74-fd09f71b6afb)
pass
