### ISSUE TITLE
[Bug]: cannot create a column which is not null default '' by UI

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#1291]
### ODC version

4.2.2

### OB version

not related

### What happened?

![image](https://github.com/oceanbase/odc/assets/39962741/4b1d9d80-4aaf-4403-bcf4-b68f398fce6c)

### What did you expect to happen?

I can create a column that is not null default '' 

### How can we reproduce it (as minimally and precisely as possible)?

create table by UI

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/0709fbb0-c7a6-4d1f-b5c4-68bb15f05d97)

pass
