### ISSUE TITLE
[Bug]: View database changes task reports file path not found

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1315]
### ODC version

4.2.3

### OB version

any

### What happened?

If the result file in a database change task is missing, viewing the task details will result in an error: xxx.json file not found.

### What did you expect to happen?

Even if the file is missing, it should not report an error when viewing the work order details.

### How can we reproduce it (as minimally and precisely as possible)?

Initiate a database change task, then delete the JSON result file generated by the task, and then view the task details.

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/5bac5fd8-29d1-4332-b6cb-524a7b5a3431)

Download without error after file is lost.
