### ISSUE TITLE
[Bug]: The prompt for successful task creation needs to be optimized

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1320]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/a2e6963c-cdb6-4012-896f-6a52b651cb7c)
The export task is created successfully, and the prompt text is: Export successful. In fact, the task still needs approval

### What did you expect to happen?

The task is created successfully, and the prompt text is: The task is created successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Create a task.

**Comment by HSunboy** [comment]
Fixed In Commit [7ea7f1ae8cf0ea19b645384cbbd8a08939da390e](https://github.com/oceanbase/odc-client/commit/7ea7f1ae8cf0ea19b645384cbbd8a08939da390e)
            ------
            咏和
            Fri Mar 8 09:45:18 2024 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/32736d3f-65f0-41ab-b8f9-b211d81206fd)
pass
