### ISSUE TITLE
[Bug]: SQL detection specification and SQL window specification failed to support data source filtering in SQL

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1324]
### ODC version

odc

### OB version

odc423

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/9178d761-8c2f-4c0a-9058-656ce22f123b)

### What did you expect to happen?

Disappear after filtering

### How can we reproduce it (as minimally and precisely as possible)?

SQL detection specification and SQL window specification support data source filtering

**Comment by HSunboy** [comment]
Fixed In Commit [f3e598d835be2a0ca97a1453b74f2d3d5de46bde](https://github.com/oceanbase/odc-client/commit/f3e598d835be2a0ca97a1453b74f2d3d5de46bde)
            ------
            陈朝俊
            Tue Jan 2 09:32:58 2024 +0800

**Comment by sl01388797** [comment]
pass
