### ISSUE TITLE
[Bug]: Query database change task details throw flow instance not found exception

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1326]
### ODC version

4.2.3

### OB version

any

### What happened?

When an project owner query the details of database change task created by SQL Plan. Then not found exception is thrown.

### What did you expect to happen?

Work as usual and no exception thrown.

### How can we reproduce it (as minimally and precisely as possible)?

Use project common user create a SQL plan, and then use project owner query ticket list and query details of the database change task created by the SQL plan.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/a2bb0a95-8fc4-443d-8cf6-6a8aa570e594)

pass
