### ISSUE TITLE
[Bug]: The label in the task status filter in the SQL plan execution record does not match the actual status

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1330]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/e27d42dd-af4e-47d6-981b-704e07c2a98e)
![image](https://github.com/oceanbase/odc/assets/143492234/f87b3b4d-9679-45d7-89b9-1246bc54f24c)

### What did you expect to happen?

There are labels indicating execution failure

### How can we reproduce it (as minimally and precisely as possible)?

Filter task status within the execution records of SQL plans

**Comment by HSunboy** [comment]
Fixed In Commit [7ea7f1ae8cf0ea19b645384cbbd8a08939da390e](https://github.com/oceanbase/odc-client/commit/7ea7f1ae8cf0ea19b645384cbbd8a08939da390e)
            ------
            咏和
            Fri Mar 8 09:45:18 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/c838a239-e252-4d91-abaf-70c65d53d929)
pass
