### ISSUE TITLE
[Bug]: I can create a data source of mysql5.6 version

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1335]
### ODC version

ODC 4.2.3

### OB version

MySQL 5.6

### What happened?

I can create a mysql5.6 version of the data source, but I get an error when viewing the table structure.
![image](https://github.com/oceanbase/odc/assets/46598871/bed48e99-04f3-42d8-83a3-88c2d0379e23)

### What did you expect to happen?

View the table structure without reporting an error

### How can we reproduce it (as minimally and precisely as possible)?

Create a data source for mysql5.6.

**Comment by guowl3** [comment]
Giant Interactive Group also encountered the same problem.

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/b8928a76-a799-4376-bc0d-779d65a8af94)
pass
