### ISSUE TITLE
[Bug]: failed to approval or reject a ticket when ConnectionConfig has been changed

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1336]
### ODC version

4.2.3

### OB version

not related

### What happened?

1. upgrade odc from 4.2.2 to 4.2.3
2. there are several tickets pending
3. approval or reject any one of them and an exception will be thrown:
```shell
详情
预期外异常，错误详情：Unhandled exception, type=PersistenceException, message= ### Error querying database. Cause: org.flowable.common.engine.api.FlowableException: Couldn't deserialize object in variable 'connectionConfig' ### Cause: org.flowable.common.engine.api.FlowableException: Couldn't deserialize object in variable 'connectionConfig'
```

### What did you expect to happen?

approval or reject the ticket normally

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
flowable use `ObjectOutputStream`/`ObjectInputStream` serialize/deserialize an object and we don't set `serialVersionUID` manually so that flowable can not deserialize the object when the object has been changed

**Comment by jonas303615108** [comment]
great

**Comment by jonas303615108** [comment]
great

**Comment by zijiacj** [comment]
great

**Comment by Huangxiao-mas** [comment]
test pass
