### ISSUE TITLE
[Enhancement]: SQL window specification Adjustments

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#1339]
### What would you like to be added?

 PL debugging is not allowed by default in a production environment.If a user enables PL debugging, alert them to the potential risks.
提示示例：PL 调试会有工作线程卡住的风险，恐影响生产系统的稳定，不建议启用 PL 调试。

![image](https://github.com/oceanbase/odc/assets/15030999/577169e7-ee64-4a20-a0d2-90db8ef51289)

### Why is this needed?

In the debugging scenario for OB PL, initiating debugging may cause the working thread to become stuck.
It is not recommended to enable PL debugging in a production environment.

**Comment by JessieWuJiexi** [comment]
提示示例：PL 调试会有工作线程卡住的风险，恐影响生产系统的稳定，不建议开启。

EN version: Enabling PL debugging poses a risk of work threads getting stuck, potentially impacting the stability of the production system. It is not recommended to enable it.

**Comment by HSunboy** [comment]
Fixed In Commit [b8cddfa9aab80415e81a98af86300c048910d89e](https://github.com/oceanbase/odc-client/commit/b8cddfa9aab80415e81a98af86300c048910d89e)
            ------
            陈朝俊
            Wed Mar 6 17:33:59 2024 +0800
