### ISSUE TITLE
[Bug]: When the sql window query result is in the request, click to log out and the front end crashes.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1347]
### ODC version

ODC423

### OB version

independent

### What happened?

When the sql window query result is in the request, click to log out and the front end crashes.
![image](https://github.com/oceanbase/odc/assets/59468957/9ffbfc59-19d0-4c69-8baa-0d502b9ca948)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

When the sql window query result is in the request, click to log out and the front end crashes.

**Comment by sl01388797** [comment]
pass
