### ISSUE TITLE
[Bug]: osc full migrate is completed  and not show swap table name button when swap table is manual model

### ISSUE THREAD

**Issue by krihy** [oceanbase/odc#1356]
### ODC version

4.2.3

### OB version

ob mysql

### What happened?

osc full migrate is completed  and  percentage is 90% and not show swap table name button when swap table is manual model
![image](https://github.com/oceanbase/odc/assets/51393259/d29df0c1-71d2-4aa8-99e6-eee93f8f5764)

### What did you expect to happen?

when osc full migrate percentage is 90%, show swap table name button in subtask

### How can we reproduce it (as minimally and precisely as possible)?

create osc task which swap table is manual model

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/8f3b879d-48a4-4c96-bbbb-aafc2f676e9f)
pass
