### ISSUE TITLE
[Bug]: Unable to select any specified data in the result set

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1363]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/475d42c3-74a3-40c5-8bb1-516ee66a4f26)
I selected column 15, but the display selects column 12.

### What did you expect to happen?

Select the specified result.

### How can we reproduce it (as minimally and precisely as possible)?

Construct a table with many columns. After selecting one piece of data, scroll right and select another piece of data.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/dec89b50-add9-45e8-b138-74188b5a4a73)

pass
