### ISSUE TITLE
[Bug]: Crashing of the front-end page after switching databases after executing DQL to display result sets

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1368]
### ODC version

4.2.3

### OB version

any

### What happened?

I successfully executed a DQL in the SQL window and returned the result set. At this point I switch databases at the top of the SQL window and the front-end page just crashes!
![image](https://github.com/oceanbase/odc/assets/84772536/0ab72dd1-8ba9-49e5-819e-5421f3f22b02)

### What did you expect to happen?

Successful database switch.

### How can we reproduce it (as minimally and precisely as possible)?

执行 DQL，等返回了结果集后在SQL窗口上方切换数据库

**Comment by HSunboy** [comment]
Fixed In Commit [ea3843f9938aa9938d615fa75f527d05aeb9c3dd](https://github.com/oceanbase/odc-client/commit/ea3843f9938aa9938d615fa75f527d05aeb9c3dd)
            ------
            xiaokang
            Wed Jan 10 09:52:14 2024 +0800

**Comment by sl01388797** [comment]
pass
