### ISSUE TITLE
[Bug]: kill session result into 'not owner of the threadid' error while connect to ob cloud instance

### ISSUE THREAD

**Issue by xsssssc** [oceanbase/odc#1375]
### ODC version

all 

### OB version

all

### What happened?

kill session result into 'not owner of the threadid' error while connect to ob cloud instance

### What did you expect to happen?

kill session success

**Comment by yizhouxw** [comment]
currently it is by design due oceanbase session mechanism.
oceanbase v4.3.0 offer new client session, odc should may the new design.
notice the new session mechanism requires ODP version v4.2.3+ & OBServer v4.3.0+ 。

we can use `select proxy_version()` to get ODP version.

**Comment by yizhouxw** [comment]
@yhilmare @Jane201510 @tonghan-gsh  I suggest change this bug to feature, milestone 4.3.1
