### ISSUE TITLE
[Bug]: When the rollback content is an attachment, there are no attachments in the SQL content during the rollback

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1379]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/128e7cc8-1028-4411-a3d2-aee8d686072f)
![image](https://github.com/oceanbase/odc/assets/143492234/4fc1f5ca-a4f0-4146-acad-8704d86d1fcd)

### What did you expect to happen?

Attachment with rollback content appearing in SQL content during rollback

### How can we reproduce it (as minimally and precisely as possible)?

1. Create database changes and upload attachments within the rollback content
2. Rollback after execution is complete

**Comment by HSunboy** [comment]
Fixed In Commit [eb8289eb551b883e10882d00e56aedafcbc9c3eb](https://github.com/oceanbase/odc-client/commit/eb8289eb551b883e10882d00e56aedafcbc9c3eb)
            ------
            咏和
            Thu Mar 28 17:24:28 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e44e2dc9-1330-430d-9eea-173f74969ea1)

pass
