### ISSUE TITLE
[Bug]:failed to query using dblink in ODC

### ISSUE THREAD

**Issue by rondon9799** [oceanbase/odc#1380]
### ODC version

ODC4.1.3BP3

### OB version

OB4.2.1.2 for Oracle tenant

### What happened?

SQL： select a.* from t1@test_dblink a;
ODC ERROR：
select ROWID AS "__ODC_INTERNAL_ROWID__", a.* from t1@test_dblink a;
ErrorCode = 1410, SQLState = HY000, Details = ORA-01410: invalid ROWID

### What did you expect to happen?

SQL statement execute without errors

### How can we reproduce it (as minimally and precisely as possible)?

Using dblink to execute SQL in ODC4.1.3BP3

**Comment by yhilmare** [comment]
odc will add an user config to solve this problem, user can disable this feature to work around:
<img width="220" alt="截屏2024-03-22 17 11 07" src="https://github.com/oceanbase/odc/assets/22992296/4ec3c3cd-19a8-453e-9e51-dec56f46d3f1">

**Comment by HSunboy** [comment]
Fixed In Commit [e79dfe7d35a7a5c28b7fbfcb576424015ae0e358](https://github.com/oceanbase/odc-client/commit/e79dfe7d35a7a5c28b7fbfcb576424015ae0e358)
            ------
            xiaokang
            Mon Mar 25 10:53:11 2024 +0800

**Comment by Huangxiao-mas** [comment]
test pass
