### ISSUE TITLE
[Bug]: After selecting the entire database for data cleaning, the page layout changes.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1382]
### ODC version

ODC423

### OB version

independent

### What happened?

After selecting the entire database for data cleaning, the page layout changes.
![image](https://github.com/oceanbase/odc/assets/59468957/c2ba84c8-e969-4824-bd8a-6555bff96e19)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/81ff41bb-d729-4a8d-859e-ad9a3aae6121)


pass
