### ISSUE TITLE
[Bug]: querying a column of type datetime(3), the result set displays a precision of only 2 bits

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1388]
### ODC version

4.2.3

### OB version

3.2.4.3 （May any version）

### What happened?

ODC query for a column of type datetime(3) shows only two millisecond values, while the command line displays them normally.

### What did you expect to happen?

Demonstrate correct accuracy.

### How can we reproduce it (as minimally and precisely as possible)?

(Ditto)

**Comment by zijiacj** [comment]
great

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/de95533e-0c2f-497e-bc41-22303e8dc4c3)

pass
