### ISSUE TITLE
[Bug]: Extra 'S' in Type Body Definition

### ISSUE THREAD

**Issue by alvinloong** [oceanbase/odc#1404]
### ODC version

版本号：4.2.3
Server: 4.2.3-20231225
Release Date: 2023-12-25

### OB version

Server version: OceanBase 4.2.1.3 (r103030022024011313-c6afef2be5748fc54b1b0159b5224ae288491424) (Built Jan 13 2024 13:36:43)

### What happened?

Here is the test case:
[test_odc_import_issue.zip](https://github.com/oceanbase/odc/files/13947879/test_odc_import_issue.zip)

Extra 'S' is always in Type Body Definition
![image](https://github.com/oceanbase/odc/assets/10559143/ad969820-937b-4e62-b629-9b369abe31b1)

### What did you expect to happen?

No extra 'S' in Type Body Definition

### How can we reproduce it (as minimally and precisely as possible)?

Run the sqls manually in ODC sql window or import using ODC, the check the Type DDL:

[test_odc_import_issue.zip](https://github.com/oceanbase/odc/files/13947879/test_odc_import_issue.zip)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/93d014f8-23e8-476b-86d2-e1a6aec79024)

pass
