### ISSUE TITLE
[Bug]: When executing create TABLE or truncate table in odc oracle mode, a semicolon will be added to the built-in execution record table.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1409]
### ODC version

ODC423

### OB version

Oceanbase324 
Oracle

### What happened?

When executing create TABLE or truncate table in odc oracle mode, a semicolon will be added to the built-in execution record table.
![image](https://github.com/oceanbase/odc/assets/59468957/a7312f06-f1e7-4950-a702-c2fe4a4c42f3)

### What did you expect to happen?

execute normally with obclient

### How can we reproduce it (as minimally and precisely as possible)?

`truncate TABLE TEST1`

executing the sql  with obclient and ODC

obclient> SELECT * from __all_virtual_ddl_operation where tenant_id=1003 order by gmt_modified desc limit 10;

**Comment by yhilmare** [comment]
can not reproduce this:
1. I execute a sql `truncate table number_range_parti_tbl`
<img width="685" alt="截屏2024-03-19 17 53 35" src="https://github.com/oceanbase/odc/assets/22992296/7ac8814f-6dda-4f63-bcce-3dafa1fd636a">

2. I look up this sql in `__all_virtual_ddl_operation`:
<img width="632" alt="截屏2024-03-19 17 54 40" src="https://github.com/oceanbase/odc/assets/22992296/487f7ae1-d208-425d-86aa-cc586243bdb5">

as you can see: there is no semicolon at the end of the statement.
