### ISSUE TITLE
[Bug]: SQL checks containing delimiters will report an error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1412]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/06a0a5d4-3032-4786-9bd7-1ce20ffe4d54)
No error will be reported when checking the sql statement of the delimiter alone, but an error will be reported when checking together with pl.

### What did you expect to happen?

Checking it together with pl will not report an error.

### How can we reproduce it (as minimally and precisely as possible)?

delimiter //;
create function `fun_loop` (p1 int) returns int(11) begin
      declare v1 int;
      set v1 = 0;
      loop1:LOOP
      IF v1 > 10 THEN
      LEAVE loop1;
      END IF;
      set v1 = v1 + p1;
      END LOOP;
      return v1;
      end;

**Comment by yhilmare** [comment]
this is not caused by sql-check, you can reproduce this issue by sqls as follow
<img width="572" alt="截屏2024-01-17 14 27 33" src="https://github.com/oceanbase/odc/assets/22992296/07fa9797-e564-4f1a-b89d-c4eeb5a3b10b">

as you can see, any delimiter longer than 2 will cause this problem.

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/3704b5f4-3d93-4cd5-8f8e-5add33b039de)
pass
