### ISSUE TITLE
[Bug]: A one-line comment in procedure becomes two lines when executing in ODC SQL window

### ISSUE THREAD

**Issue by alvinloong** [oceanbase/odc#1413]
### ODC version

版本号：4.2.3
Server: 4.2.3-20231225
Release Date: 2023-12-25

### OB version

Server version: OceanBase 4.2.1.3 (r103030022024011313-c6afef2be5748fc54b1b0159b5224ae288491424) (Built Jan 13 2024 13:36:43)

### What happened?

The comment happened to change to two lines after executing the scripts in ODC SQL window:

```
-- aaa := pn_OperatorID;
```
changed to
```
    -- aaa := pn_Operato
ID;
```
Open the package body DDL in ODC, you can see :

![image](https://github.com/oceanbase/odc/assets/10559143/d06a362d-51dc-404a-b42a-8dbfddf8e77a)

### What did you expect to happen?

The 'ID' at the end of the comment should NOT be in the next line.

### How can we reproduce it (as minimally and precisely as possible)?

Just run following scripts in ODC SQL Window manually, then check the package status.

![image](https://github.com/oceanbase/odc/assets/10559143/90858638-1bd6-47da-acfe-fece99c61c8c)

```
DELIMITER $$
create or replace PACKAGE pkg_test_c IS 
PROCEDURE test
  (
    pn_OperatorID IN INT
  );
END pkg_test_c;
$$

DELIMITER $$
create or replace PACKAGE BODY pkg_test_c IS 
PROCEDURE test
  (
    pn_OperatorID IN INT
  ) IS
  ln_OperatorID INT;
  BEGIN
    -- aaa := pn_OperatorID;
    ln_OperatorID := pn_OperatorID;
  END test;
END pkg_test_c;
$$

DELIMITER ;
SHOW ERRORS;
```

### Anything else we need to know?

Run the scripts manually on obclient command line, it works well:

![image](https://github.com/oceanbase/odc/assets/10559143/7a4d19d7-b7d4-4d7f-8dab-63734583d4b6)

```
Server version: OceanBase 4.2.1.3 (r103030022024011313-c6afef2be5748fc54b1b0159b5224ae288491424) (Built Jan 13 2024 13:36:43)

Copyright (c) 2000, 2018, OceanBase and/or its affiliates. All rights reserved.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

obclient [TEST_USER_C]> DELIMITER $$
obclient [TEST_USER_C]> create or replace PACKAGE pkg_test_c IS
    -> PROCEDURE test
    ->   (
    ->     pn_OperatorID IN INT
    ->   );
    -> END pkg_test_c;
    -> $$
Query OK, 0 rows affected (0.148 sec)

obclient [TEST_USER_C]> DELIMITER $$
obclient [TEST_USER_C]> create or replace PACKAGE BODY pkg_test_c IS
    -> PROCEDURE test
    ->   (
    ->     pn_OperatorID IN INT
    ->   ) IS
    ->   ln_OperatorID INT;
    ->   BEGIN
    ->     -- aaa := pn_OperatorID;
    ->     ln_OperatorID := pn_OperatorID;
    ->   END test;
    -> END pkg_test_c;
    -> $$
Query OK, 0 rows affected (0.144 sec)

obclient [TEST_USER_C]>
obclient [TEST_USER_C]> DELIMITER ;
obclient [TEST_USER_C]> SHOW ERRORS;
Empty set (0.352 sec)
```

**Comment by yhilmare** [comment]
![Image](https://github.com/oceanbase/odc/assets/22992296/b4da1fb4-6b24-4b0a-bf16-96354e91db25)



![Image](https://github.com/oceanbase/odc/assets/22992296/8ee8c6d7-39bb-43a3-a578-b635d0d80924)

as you can see, everything goes well~can not reproduce it
