### ISSUE TITLE
[Bug]: After the dlm log size exceeds the limit of 1M, the downloaded log is still 1M.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1416]
### ODC version

ODC423

### OB version

independent

### What happened?

After the dlm log size exceeds the limit of 1M, the downloaded log is still 1M.
![image](https://github.com/oceanbase/odc/assets/59468957/9f9ce201-695f-4c72-a600-1ffee0a0ac9f)

### What did you expect to happen?

Download all logs

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by smallsheeeep** [comment]
This PR(#1940) fix the issue for download full log file, but do not care about task framework scenario. Please help to adapt for task framework @krihy
