### ISSUE TITLE
[Bug]: SQL console empty status page has no guidance content

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1417]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/06295bc4-4dfc-4174-a4a1-a35a29dbbdf0)
SQL window empty status page has no guidance content

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/e1695bea-3b65-4556-8f05-e6c4768e5204)

### How can we reproduce it (as minimally and precisely as possible)?

Close all sql windows.

**Comment by HSunboy** [comment]
Fixed In Commit [0608b2fec5273bead02e20edd99c10d13e07a735](https://github.com/oceanbase/odc-client/commit/0608b2fec5273bead02e20edd99c10d13e07a735)
            ------
            xiaokang
            Tue Jan 30 09:44:08 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6b7089ab-a6df-4f19-9e1f-884b8fb9839c)

pass
