### ISSUE TITLE
[Bug]: Open the SQL type that is allowed to be executed, then execute the anonymous block and an error will be reported.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1422]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

Open the SQL type that is allowed to be executed in the window specification, and then execute the anonymous block and an error will be reported.
![image](https://github.com/oceanbase/odc/assets/46598871/6bcd7a73-3d62-4c0b-bbe7-de9190871f94)
![image](https://github.com/oceanbase/odc/assets/46598871/51cb6391-5a47-4cc5-b79b-5090a08f0eef)

### What did you expect to happen?

Execute anonymous blocks without reporting errors.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by yhilmare** [comment]
@MarkPotato777 what's our security policy for anonymous block? there is not sql type called anonymous and anonymous block does not belong to the rule 'not-allowed-create-pl'

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/d2d726ec-31e6-4d0d-9fb3-50ab4a76d3ca)

pass
