### ISSUE TITLE
[Bug]: The desktop version cannot be opened on UOS

### ISSUE THREAD

**Issue by ungreat** [oceanbase/odc#1423]
### ODC version

4.2.3

### OB version

* 

### What happened?

The desktop version cannot be opened on UOS
pretty name: UnionTech OS Desktop 20 Pro
version_id : 20
version_codename=eagle

### What did you expect to happen?

The desktop version can be opened normally.

### How can we reproduce it (as minimally and precisely as possible)?

.

**Comment by tonghan-gsh** [comment]
#2941
