### ISSUE TITLE
[Bug]: Non empty items added through SQL cannot be cancelled

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1444]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/7c4737e1-c0be-4fce-a48c-bac7a504a234)

### What did you expect to happen?

Can cancel non empty

### How can we reproduce it (as minimally and precisely as possible)?

1.Create Table
CREATE TABLE "SUOYINBIAO" (
  "A" NUMBER(*,0) DEFAULT NULL CONSTRAINT "AF552FB676B0A42659DB5F59468D2EA21" NOT NULL ENABLE,
  "B" NUMBER(*,0) DEFAULT NULL,
  "C" NUMBER(*,1) DEFAULT NULL,
  CONSTRAINT "AE4E1BE6D477040AE9A529A5099C5906E" PRIMARY KEY ("A")
)
2. Execute SQL
ALTER TABLE "SUOYINBIAO" MODIFY ("B" NUMBER(*,0) NOT NULL);

**Comment by HSunboy** [comment]
Fixed In Commit [b69e026bcef5b33b0142c266c47be1734c7b2eaf](https://github.com/oceanbase/odc-client/commit/b69e026bcef5b33b0142c266c47be1734c7b2eaf)
            ------
            xiaokang
            Thu Mar 28 17:23:19 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b8a0efc6-f5bc-4c34-bcc6-8eda22711069)

pass
