### ISSUE TITLE
[Bug]: Error adding data to the result set

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1445]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/01b7eb3c-7b7e-4d60-815d-84a8aab7c850)

### What did you expect to happen?

The operation should be insert, and the front-end request was sent as update

### How can we reproduce it (as minimally and precisely as possible)?

Add data to the result set

**Comment by bluesky-xyh** [comment]
fixed: https://code.alipay.com/oceanbase/oceanbase-developer-center/pull_requests/312

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ae3e8cb1-dcca-4005-b81c-669efb0875c8)

pass
