### ISSUE TITLE
[Bug]: After table indexing and filtering within constraints, clicking filter again will only display the selected content

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1449]
### ODC version

odc423

### OB version

*

### What happened?

![6e16d1172e870032a84508d2db5d62fe](https://github.com/oceanbase/odc/assets/143492234/ec23f76a-d74d-4169-9565-7221dc0700e9)
![53e8a067e2bbd65f2a3c897cb636c4a8](https://github.com/oceanbase/odc/assets/143492234/627c7ecd-274e-4463-8d1b-4d175af4de76)

### What did you expect to happen?

422
![5ca505892770e69a4b7d3d879b8c6ddb](https://github.com/oceanbase/odc/assets/143492234/274192fb-de72-49b4-933f-13b29f3a0ca1)

### How can we reproduce it (as minimally and precisely as possible)?

Create multiple indexes or constraints click filter

**Comment by bluesky-xyh** [comment]
fixed: https://code.alipay.com/oceanbase/oceanbase-developer-center/pull_requests/312

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/828ad29f-f816-4061-a17d-211f33544c9e)

pass
