### ISSUE TITLE
[Bug]: Failed to create database session in personal space

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1460]
### ODC version

4.2.4

### OB version

not care

### What happened?

Failed to create database session in personal space

### What did you expect to happen?

Create database session successfully in personal space.

### How can we reproduce it (as minimally and precisely as possible)?

Create database session in personal space.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/a749bdb0-04e5-42c2-9df3-0a82875155e9)

pass
