### ISSUE TITLE
[Bug]: The client version should disables partition planning task

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1461]
### ODC version

all

### OB version

all

### What happened?

The client version is not suitable for partition plans. The normal scheduling of the partition plan relies on the continuous running of this client program. We strongly do not recommend using any periodic tasks on the client. The effectiveness of this schedule cannot be guaranteed. The ODC process must be resident to ensure the normal operation of periodic scheduling tasks.

### What did you expect to happen?

The client version process exits and partition plan scheduling fails.

### How can we reproduce it (as minimally and precisely as possible)?

The client version process exits and partition plan scheduling fails.

**Comment by tonghan-gsh** [comment]
The client version does not have partition planning task
![Image](https://github.com/oceanbase/odc/assets/46598871/375e844b-8a27-4643-88a2-b93a0aaed213)
