### ISSUE TITLE
[Bug]: sys tenant connection ob oracle mode test connection successful

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1462]
### ODC version

4.2.3

### OB version

all

### What happened?

sys tenant connection ob oralce mode test connection successful.
<img width="493" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/38fcdb72-9a7b-4850-94cb-92649d5deba8">
After creating a new data source with sys tenant account, the data source is grayed out.
<img width="667" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/66ea6fbf-2d77-40a8-aa70-2a7c58bfdec5">

### What did you expect to happen?

sys tenant connection ob oralce mode test connection successful.

### How can we reproduce it (as minimally and precisely as possible)?

Create a new data source and select ob oracle mode. Testing the connection with the sys tenant should return connection failure information. odc 4.1.3 works fine：

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/f56610a0-fd6b-4b41-ac12-4c9c01962839)
pass
