### ISSUE TITLE
[Bug]: Personal space can not view the database list

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1466]
### ODC version

4.2.4

### OB version

any

### What happened?

I am a participant of a project. I switch to individual space and create a new databsource, but I can not view the database list and create a ticket due to no permission.

### What did you expect to happen?

View all databases and create any type of tickets.

### How can we reproduce it (as minimally and precisely as possible)?

Switch into individual space and create a datasource, then view the database list.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/80c4cba0-4a88-4698-b2b3-06ba0ccd6e81)

pass
