### ISSUE TITLE
[Bug]: Pre-check in database change task executing failed when upload SQL files

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1469]
### ODC version

4.2.4

### OB version

any

### What happened?

Pre-check in database change task executing failed when upload SQL files

### What did you expect to happen?

Pre-check successfully.

### How can we reproduce it (as minimally and precisely as possible)?

.

### Anything else we need to know?

The reason is that the `bucket` is using wrong `userId`:
```java
this.creatorId = FlowTaskUtil.getTaskCreator(execution).getCreatorId();
```

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/0fe09c77-d722-419c-83cf-480e6e6dbc69)

pass
