### ISSUE TITLE
[Bug]: When using the ob2230 version, an error occurs when executing sql.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1475]
### ODC version

ODC 4.2.3

### OB version

OB 2.2.3.0

### What happened?

When using the ob2230 version, an error occurs when executing sql.
![image](https://github.com/oceanbase/odc/assets/46598871/b7c7e100-40e8-4154-9de5-c3073b5c9f56)
![image](https://github.com/oceanbase/odc/assets/46598871/5d94fa38-4e83-4b57-b08d-8168f132fbfe)

### What did you expect to happen?

Use ob2230 version to execute sql successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1fd07974-b089-4234-8a86-5925cb33efd0)

pass
