### ISSUE TITLE
[Bug]:There will be an error when creating the sql window using the ob2230 version.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1476]
### ODC version

ODC 4.2.3

### OB version

OB 2.2.3.0

### What happened?

There will be an error when creating the sql window using the ob2230 version.
![image](https://github.com/oceanbase/odc/assets/46598871/d990c365-56b7-4415-98ef-e714326f6aec)

### What did you expect to happen?

Open sql window without error.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6341e99b-8932-4cae-8e65-af0ada04fdcf)

pass
