### ISSUE TITLE
[Bug]: No comments in the selected columns within the table data

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1482]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/1f543738-55a6-4d07-8c0e-8254f5b3ae1f)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/e0a1491e-51d2-4c6d-8a40-a5027cb26bd0)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Table
CREATE TABLE `全类型表` (
  `col1` int(11) NOT NULL AUTO_INCREMENT COMMENT '第一列',
  `COL2` decimal(10,2) DEFAULT NULL COMMENT '第二列',
  `第三列3` decimal(10,2) DEFAULT NULL COMMENT '第三列',
  `!@#$4` bit(8) DEFAULT NULL COMMENT '第四列',
  `col5` tinyint(4) DEFAULT NULL COMMENT '第五列',
  `col6` smallint(6) DEFAULT NULL COMMENT '第六列',
  `col7` mediumint(9) DEFAULT NULL COMMENT '第七列',
  `col8` bigint(20) DEFAULT NULL COMMENT '第八列',
  `col9` float(10,2) DEFAULT NULL COMMENT '第九列',
  `col10` double(10,2) DEFAULT NULL COMMENT '第十列',
  `col11` varchar(10) DEFAULT NULL COMMENT '第十一列',
  `col12` char(10) NOT NULL DEFAULT '中文字段' COMMENT '第十二列',
  `col13` text DEFAULT NULL COMMENT '第十三列',
  `col14` tinytext DEFAULT NULL COMMENT '第十四列',
  `col15` mediumtext DEFAULT NULL COMMENT '第十五列',
  `col16` longtext DEFAULT NULL COMMENT '第十六列',
  `col17` blob DEFAULT NULL COMMENT '第十七列',
  `col18` tinyblob DEFAULT NULL COMMENT '第十八列',
  `col19` longblob DEFAULT NULL COMMENT '第十九列',
  `col20` mediumblob DEFAULT NULL COMMENT '第二十列',
  `col21` binary(16) DEFAULT NULL COMMENT '第二十一列',
  `col22` varbinary(16) DEFAULT NULL COMMENT '第二十二列',
  `col23` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '第二十三列',
  `col24` time DEFAULT NULL COMMENT '第二十四列',
  `col25` date DEFAULT NULL COMMENT '第二十五列',
  `col26` datetime DEFAULT NULL COMMENT '第二十六列',
  `col27` year(4) DEFAULT NULL COMMENT '第二十七列',
  PRIMARY KEY (`col1`)
)
2. Add data
3. View content in table data

**Comment by bluesky-xyh** [comment]
<img width="1043" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/8142e8f9-f4d8-44b6-9774-b2603318e2a3">
<img width="1097" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/526d5568-9b6c-42c8-b5b6-dd9bcaeab8f2">

**Comment by bluesky-xyh** [comment]
<img width="979" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/08a4f00f-c32e-452f-ba57-b2dd0831863b">
<img width="1270" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/fb1ad611-a019-4675-a6b7-1c0b88c08791">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/555144f7-66a6-42a4-bcd6-39a5320e9838)

pass
