### ISSUE TITLE
[Feature]: Support for Custom Environment Tags

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#1484]
### Is your feature request related to a problem?

Now, ODC provides four environment tags: Development, Testing, Production, and Default. However, I also require additional environment tags, such as Performance Testing. It is hoped that ODC can offer the capability to customize environment tags in order to meet practical usage demands.

### Describe the solution you'd like

It is hoped that ODC can offer the capability to customize environment tags in order to meet practical usage demands.

**Comment by HSunboy** [comment]
Fixed In Commit [251a0c04099411c98b68717b70345f25577ef2c5](https://github.com/oceanbase/odc-client/commit/251a0c04099411c98b68717b70345f25577ef2c5)
            ------
            陈朝俊
            Tue Jan 30 19:03:32 2024 +0800
