### ISSUE TITLE
[Bug]: # $disappears after formatting

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1490]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/a94dd8b1-cd4a-441f-825a-731a5d1eb1b2)
![image](https://github.com/oceanbase/odc/assets/143492234/ce1ca94e-f8f4-4a3d-b9b9-f1a50cd97c8b)

### What did you expect to happen?

#Does not disappear after formatting with $

### How can we reproduce it (as minimally and precisely as possible)?

1. Add within SQL
SELECT `col1`, `COL2`, `第三列3`, `!@#$4`, `col5`, `col6`, `col7`, `col8`, `col9`, `col10`, `col11`, `col12`, `col13`, `col14`, `col15`, `col16`, `col17`, `col18`, `col19`, `col20`, `col21`, `col22`, `col23`, `col24`, `col25`, `col26`, `col27` FROM `全类型表`;
2. Perform formatting

**Comment by HSunboy** [comment]
Fixed In Commit [09ab4c2f138d4c990c2e5db744ca20eba3945a9b](https://github.com/oceanbase/odc-client/commit/09ab4c2f138d4c990c2e5db744ca20eba3945a9b)
            ------
            xiaokang
            Mon Apr 1 14:32:22 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9fdf63b6-1fb8-41c1-abf8-b971c82f073a)

pass
