### ISSUE TITLE
[Bug]: The desktop version exports the result set twice in a row without a default database.

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#150]
### ODC version

odc4.2.1

### OB version

ob4.2.0.1

### What happened?

The second export result set has no default database
![image](https://github.com/oceanbase/odc/assets/143492234/ee318ed2-0e98-4c87-8c17-a05233f64282)

### What did you expect to happen?

Default database exists

### How can we reproduce it (as minimally and precisely as possible)?

Export the result set twice in a row

**Comment by HSunboy** [comment]
Fixed In Commit [2dea9e85a6313d0d9f5066cf55d789bc6d564806](https://github.com/oceanbase/odc-client/commit/2dea9e85a6313d0d9f5066cf55d789bc6d564806)
            ------
            咏和
            Wed Sep 6 16:36:59 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/4dc633d2-52e4-4a21-8ade-e35941fccb27)
pass
