### ISSUE TITLE
[Bug]: The maximum value of the partition table is not displayed in full

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1501]
### ODC version

4.2.3

### OB version

all

### What happened?

When a partition table has multiple maximum values, the front end only displays one：
<img width="1640" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/c54dfe5c-f3d8-447f-8940-46e7198d21ab">

### What did you expect to happen?

table ddl:
```
CREATE TABLE "SHANLU"."RANGE_PARTI_TIME_TYPE" (
  "C1" DATE,
  "C2" TIMESTAMP(9),
  "C5" VARCHAR2(64)
) 
 partition by range(c1, c2)
(partition P0 values less than (TO_DATE(' 2022-12-31 23:59:59', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'),Timestamp '2022-12-31 23:59:59.000000000'));
```

### How can we reproduce it (as minimally and precisely as possible)?

no

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f59f08c8-3fa8-424b-8911-e0d26686f115)

pass
