### ISSUE TITLE
[Bug]: transaction timeout error while bind more than 300 databases into project

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#151]
### ODC version

4.2.0

### OB version

not related

### What happened?

transaction timeout error while bind more than 300 databases into project.

the MetaDB unit config was 1C4G, may not sufficient.

### What did you expect to happen?

bind databases to project success

### How can we reproduce it (as minimally and precisely as possible)?

bind more than 300 databases into project

### Anything else we need to know?

there also exists slow sql for table `SPRING_SESSION`, update operation

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6a5b1f56-f5f7-4c68-ade9-8397aa994e00)

pass
