### ISSUE TITLE
[Bug]: Project list selects the database to export a single table, and finally exports the entire table

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1514]
### ODC version

ODC424

### OB version

independent

### What happened?

Project list selects the database to export a single table, and finally exports the entire table
![image](https://github.com/oceanbase/odc/assets/59468957/090470d8-4687-4c2b-995f-0668e736f3e9)

### What did you expect to happen?

export single table

### How can we reproduce it (as minimally and precisely as possible)?

Project list selects the database to export a single table

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f5185466-857a-486f-ba1f-7fe2feb6e11b)

pass
