### ISSUE TITLE
[Bug]: SQL plan cannot be edited, no permissions

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1526]
### ODC version

ODC424

### OB version

independent

### What happened?

SQL plan cannot be edited, no permissions
![image](https://github.com/oceanbase/odc/assets/59468957/7b51465d-91b7-4081-8d80-7cc13c7cab0d)

### What did you expect to happen?

can edict

### How can we reproduce it (as minimally and precisely as possible)?

edict sqlplan

**Comment by smallsheeeep** [comment]
It works for me, please check whether the meta DB has some dirty data.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ec99f521-6fdf-4c41-b1c9-168952b57d19)

pass
