### ISSUE TITLE
[Bug]: Edit the PL object so that the PL content can be modified during initialization

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#153]
### ODC version

421

### OB version

all mysql schema

### What happened?

When editing PL, the PL contents can be modified during initialization

### What did you expect to happen?

The PL of the mysql schema can not be edited

### How can we reproduce it (as minimally and precisely as possible)?

Trigger the PL editing function to modify the PL content during initialization

**Comment by HSunboy** [comment]
Fixed In Commit [cbdee53be86e7702447bb38c18ae3066308ea4c4](https://github.com/oceanbase/odc-client/commit/cbdee53be86e7702447bb38c18ae3066308ea4c4)
            ------
            晓康
            Wed Sep 6 15:46:29 2023 +0800

**Comment by Huangxiao-mas** [comment]
test passed
