### ISSUE TITLE
[Feature]: For message notification, click the test link and then fill in the description. You also need to send a test message to save it.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1536]
### ODC version

ODC424

### OB version

independent

### What happened?

For message notification, click the test link and then fill in the description. You also need to send a test message to save it.
![image](https://github.com/oceanbase/odc/assets/59468957/04d6a2ad-3d60-4570-a9d8-6e1e9736cd2e)
![image](https://github.com/oceanbase/odc/assets/59468957/6d6590e6-3315-4741-ac3a-fe9f6394b721)

### What did you expect to happen?

After clicking on the test message, you can modify it again without requiring a test link to save it.

### How can we reproduce it (as minimally and precisely as possible)?

For message notification, click the test link and then fill in the description. You also need to send a test message to save it.

**Comment by HSunboy** [comment]
Fixed In Commit [f2b658cbf65f806c325feac3313d1b89cd50bb1a](https://github.com/oceanbase/odc-client/commit/f2b658cbf65f806c325feac3313d1b89cd50bb1a)
            ------
            陈朝俊
            Mon Feb 26 17:10:50 2024 +0800
