### ISSUE TITLE
[Bug]: The project added databases without filtering deleted databases

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#154]
### ODC version

ODC 4.2.0

### OB version

Any version of OceanBase

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/985cf922-56b3-420a-945c-5de316b61ed6)
The project added databases without filtering deleted databases

### What did you expect to happen?

Database is added to the project should be filtered out database has been deleted

### How can we reproduce it (as minimally and precisely as possible)?

1. create database test_delete;
2. drop database test_delete;
3. Add a database to the project

**Comment by HSunboy** [comment]
Fixed In Commit [80ec85e98864e0a0b2b12da022170ee2433d0e0a](https://github.com/oceanbase/odc-client/commit/80ec85e98864e0a0b2b12da022170ee2433d0e0a)
            ------
            晓康
            Fri Oct 20 17:13:08 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/a097f8a1-2c88-487a-b420-a7eb72b79d11)


![Image](https://github.com/oceanbase/odc/assets/143492234/5e2dbc50-05e7-4cd5-ad55-02b67703195e)
pass
