### ISSUE TITLE
[Bug]: 使用odc查看latin1编码的中文出现乱码

### ISSUE THREAD

**Issue by zanefish** [oceanbase/odc#1545]
### ODC version

4.2.2-20231107

### OB version

5.7.25-OceanBase_CE-v4.2.0.0

### What happened?

我使用mysql的命令行客户端连接了ob，然后使用set names latin1可以正常看到表中的中文，但是在odc中，无论使用set names latin1还是修改高级设置中的驱动属性characterEncoding，都显示乱码，但这些方法我看到show variables like '%charac%'的结果都是一样的：
character_set_client	latin1
character_set_connection	latin1
character_set_database	utf8mb4
character_set_filesystem	binary
character_set_results	latin1
character_set_server	utf8mb4
character_set_system	utf8mb4

### What did you expect to happen?

能够正常显示中文

### How can we reproduce it (as minimally and precisely as possible)?

set names latin1后再命令行插入中文数据

**Comment by yhilmare** [comment]
latin1原本就是不支持中文的，之所以mysql客户端 set names latin1 可以显示原因是有些复杂的，set names命令实际上是告诉connection和数据库，网络上的包内容的编码，如果这里的编码和数据库或connection的一致，那么就不会再对其进行编码而直接落库。

那么，我们就可以分析一下这个问题：
1. 数据库的编码是 latin1
2. 用户本地机器的编码极大概率不是 latin1，可能是 utf8 或者 gbk
3. 调用 set names latin1 就是说，声明本地机器的编码是 latin1，connection 的编码也是 latin1等等
4. 此时再发送一个中文，由于本地机器是 utf8 或 gbk 编码，那么此时这个中文实际上是会被这两种编码中的一种编码成二进制
5. 发送的时候客户端会比较客户端编码和connection编码，如果不一致会有一次编码转换（ps，这个过程同样会发生在connection和server），否则就原样传输。由于 set names latin1 的缘故，导致客户端编码（正常应该是utf8或者gbk）被错误地设置为 latin1，这个编码和 connection 一致，就不会对文本的二进制内容做重新编码而是直接传输。同理，这个过程同样发生在 connection 到 server 的过程中，最终的效果就是数据库中实际存储的是该中文使用utf8或者gbk编码的二进制内容。读出的时候能显示正常同理，就是逆过程。
6. odc 之所以不行就是因为odc作为客户端的编码不受 set names 的控制，只能通过 jdbc url参数控制

**Comment by yhilmare** [comment]
https://zhuanlan.zhihu.com/p/424868844
