### ISSUE TITLE
[Bug]: Create a link using a custom environment, but there is no database within the link

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1546]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/0d7b1e91-2dc2-419a-bccd-a2ae52a55e83)

### What did you expect to happen?

Create a link using a custom environment, where the link is stored in the database

### How can we reproduce it (as minimally and precisely as possible)?

Create a custom environment and use it to create links

**Comment by MarkPotato777** [comment]
Not reproduced. Maybe your data source in invalid?
