### ISSUE TITLE
[Bug]: LDAP prefix error

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1553]
### ODC version

ODC424

### OB version

independent

### What happened?

LDAP prefix error
![image](https://github.com/oceanbase/odc/assets/59468957/acfb9e39-64b3-43fe-b13c-7ab1684672df)

### What did you expect to happen?

should ldap://

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/59468957/4b096604-e797-4408-9c6c-af81c639ca03)

**Comment by HSunboy** [comment]
Fixed In Commit [f8eef63320d2673614971d14f83f768eab8bc5e2](https://github.com/oceanbase/odc-client/commit/f8eef63320d2673614971d14f83f768eab8bc5e2)
            ------
            陈朝俊
            Mon Feb 19 17:37:10 2024 +0800
