### ISSUE TITLE
[Bug]: LDAP test link not working

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1554]
### ODC version

ODC424

### OB version

independent

### What happened?

LDAP test link not working
![image](https://github.com/oceanbase/odc/assets/59468957/e1004db4-1b4b-4f94-8667-c5d32e8c2212)

### What did you expect to happen?

can work

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/59468957/bc23b561-caf7-42c3-a172-65e207f4f9b7)

**Comment by HSunboy** [comment]
Fixed In Commit [f8eef63320d2673614971d14f83f768eab8bc5e2](https://github.com/oceanbase/odc-client/commit/f8eef63320d2673614971d14f83f768eab8bc5e2)
            ------
            陈朝俊
            Mon Feb 19 17:37:10 2024 +0800
