### ISSUE TITLE
[Bug]: There is no entrance to apply for database permissions in the project

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1556]
### ODC version

ODC4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/7e70f63d-1db7-4bf5-afca-05a06ae9f1a9)
There is no entrance to apply for database permissions in the project.

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/ca63d5a7-ef50-4a44-9a44-b4882a4517ee)

### How can we reproduce it (as minimally and precisely as possible)?

Enter a project

**Comment by bluesky-xyh** [comment]
已 fixed

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/22f64bd6-9c2f-41a9-ab54-b89917d62b69)
pass
