### ISSUE TITLE
[Bug]: Already contains database query permission, the login database button is still grayed out

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1557]
### ODC version

ODC4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/6da31f8f-c21e-4076-96d4-0fa33f4e2089)
Already contains database query permission, the login database button is still grayed out

### What did you expect to happen?

button available

### How can we reproduce it (as minimally and precisely as possible)?

The user has the query permission of the database and enters the project.

**Comment by bluesky-xyh** [comment]
No recurrence：
<img width="1721" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/0d5253d0-23c6-4fa1-8ab7-e1f9c5927629">

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/7f74e5f5-a33f-4fa3-b8e2-b9e17a647379)
pass
