### ISSUE TITLE
[Bug]: Select database operation optimization

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1558]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/3fa09728-49f7-42e9-81fa-9ae3f9ecf028)
Cannot select database  when clicking on them,I can only click on the selection box on the left.

### What did you expect to happen?

I can also select the database content by clicking on it.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by HSunboy** [comment]
Fixed In Commit [9cbb7d5bad2e32d15014951f4d0d9d2e688a45af](https://github.com/oceanbase/odc-client/commit/9cbb7d5bad2e32d15014951f4d0d9d2e688a45af)
            ------
            咏和
            Mon Mar 11 10:55:33 2024 +0800

**Comment by tonghan-gsh** [comment]
pass
