### ISSUE TITLE
[Bug]: Prompt for inconsistency with the design draft when the name is duplicated or starts with a space

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1563]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/a105f532-d575-4bf0-b43c-626059f79a15)
![image](https://github.com/oceanbase/odc/assets/143492234/2d8aa1c4-82fa-4638-a522-41fb33f3b1cf)
![image](https://github.com/oceanbase/odc/assets/143492234/b233b19b-b3d9-427d-a8c1-c9e5e4add053)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/da824611-bab6-45fd-839e-b4341154e360)
![image](https://github.com/oceanbase/odc/assets/143492234/5d5e702a-71ee-46b9-96aa-c8b51d059a18)

### How can we reproduce it (as minimally and precisely as possible)?

Create a custom environment with duplicate names

**Comment by HSunboy** [comment]
Fixed In Commit [f403ce9d29fa6429e0389d00f6fcd204da56e0e8](https://github.com/oceanbase/odc-client/commit/f403ce9d29fa6429e0389d00f6fcd204da56e0e8)
            ------
            陈朝俊
            Tue Feb 20 18:36:45 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/095886b1-6cd2-4442-9120-a58b61ec6cf6)
Inconsistent with the design draft when the name is duplicated

**Comment by HSunboy** [comment]
Fixed In Commit [575dbf9bf5215cf46ea8f34aa9a017c66f659bc5](https://github.com/oceanbase/odc-client/commit/575dbf9bf5215cf46ea8f34aa9a017c66f659bc5)
            ------
            陈朝俊
            Wed Mar 6 17:34:24 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/5673a666-ee84-4ef6-bbc9-a40daaaccfa6)
pass
