### ISSUE TITLE
[Bug]: There is no prompt that cannot be modified after creating a custom environment

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1564]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b6097ed3-4687-4dc4-a1b0-6c9ec85c8825)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/b8db9094-fca3-440e-8044-8a668d951869)

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [f403ce9d29fa6429e0389d00f6fcd204da56e0e8](https://github.com/oceanbase/odc-client/commit/f403ce9d29fa6429e0389d00f6fcd204da56e0e8)
            ------
            陈朝俊
            Tue Feb 20 18:36:45 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/416d1f76-5da1-48cf-b1ae-903ed8be9e8d)
pass
