### ISSUE TITLE
[Bug]: Obtained incorrect ddl while viewing Oracle table structure

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#1565]
### ODC version

4.2.4

### OB version

oracle

### What happened?

![image](https://github.com/oceanbase/odc/assets/36879124/95c8d0c0-b3ff-485a-befc-abc890d567ed)

### What did you expect to happen?

Show the correct ddl

### How can we reproduce it (as minimally and precisely as possible)?

Create oracle tables with index.

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/de863446-263f-4744-a158-10449f7105dd)
pass
