### ISSUE TITLE
[Bug]: After the target data source is invalid, the dlm task rolls back and reports that it has no permissions.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1567]
### ODC version

ODC424

### OB version

independent

### What happened?

After the target data source is invalid, the dlm task rolls back and reports that it has no permissions.
![image](https://github.com/oceanbase/odc/assets/59468957/365247e6-5b75-4d17-b909-2a7a52ee54a0)

### What did you expect to happen?

execute failed

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by guowl3** [comment]
#1640
