### ISSUE TITLE
[Bug]: The create table statement containing index is not recognized as a create type

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1568]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/03ff7ee2-517f-498f-8190-0a2cb2564dce)
The create table statement containing index is not recognized as a create type,even if create is selected as the SQL type that is allowed to be executed, it will be intercepted during execution.

### What did you expect to happen?

Executing a create table statement containing index is recognized as a create type.

### How can we reproduce it (as minimally and precisely as possible)?

1.Select create for the sql type allowed to be executed in the sql check specification.
2.
```sql
CREATE TABLE user_fav_app_0 (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `department_id` INT,
    `user_id` INT,
    `app_id` INT,
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `cancel_time` DATETIME,
    `state` TINYINT DEFAULT 0 COMMENT '1代表收藏，0代表取消收藏',
    INDEX (`user_id`, `app_id`)
) COMMENT='记录每个用户的收藏应用';
```

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b03be3e4-c250-4588-90d9-f2bfc55a8818)

pass
