### ISSUE TITLE
[Bug]: Install the desktop version has antivirus error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#157]
### ODC version

ODC 4.2.0 desktop version

### OB version

Any version of OceanBase

### What happened?

The installation of Qianxin Tianqing's anti-virus software caused the installation of ODC420 error.
![image](https://github.com/oceanbase/odc/assets/46598871/2b09987c-40de-439b-915d-4df2a52a5f87)

### What did you expect to happen?

Install without error

### How can we reproduce it (as minimally and precisely as possible)?

1.Install Qianxin Tianqing antivirus software
2.install ODC 4.2.0 desktop version

**Comment by HSunboy** [comment]
This is not a code-level problem. To solve this problem, we need to apply for a code signing certificate.
