### ISSUE TITLE
[Bug]: When comparing structures, there is no content in the compared table when the content is consistent

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1570]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/0745bd10-5d37-4994-8adb-574a1d6472cb)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/f8a4403c-db07-418f-848b-901e7f8dd688)

### How can we reproduce it (as minimally and precisely as possible)?

Comparing two identical tables

**Comment by HSunboy** [comment]
Fixed In Commit [ad7d77e455e6947e048a85310dc7be8b8f2505bb](https://github.com/oceanbase/odc-client/commit/ad7d77e455e6947e048a85310dc7be8b8f2505bb)
            ------
            陈朝俊
            Mon Feb 26 17:11:28 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/8d44838a-e000-42c7-af3b-2f86231d7a02)
pass
