### ISSUE TITLE
[Bug]: Structural comparison did not download SQL and initiate structural synchronization during execution

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1572]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2d94cede-bcf4-45ec-a82b-f538356120e5)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/fada8a1f-2ac7-4fc2-a8c4-fbc9c5ee000d)

### How can we reproduce it (as minimally and precisely as possible)?

Comparison of execution structures

**Comment by HSunboy** [comment]
Fixed In Commit [08f990dbc02a477c8d24d5daaedb3595b1d6e112](https://github.com/oceanbase/odc-client/commit/08f990dbc02a477c8d24d5daaedb3595b1d6e112)
            ------
            陈朝俊
            Tue Feb 20 18:37:07 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/445c3eb7-3029-4465-be7e-c96c8f164f35)

pass
