### ISSUE TITLE
[Bug]: LDAP integration, userSearchFilter and userSearchBase are required

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1573]
### ODC version

ODC424

### OB version

independent

### What happened?

LDAP integration, userSearchFilter and userSearchBase are required
![image](https://github.com/oceanbase/odc/assets/59468957/28b1fbff-cfe4-4c40-8f47-5ea9f247aeed)
### 

### What did you expect to happen?

required

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Fixed In Commit [64b68c113c7c0c54ff60676a94c78da943824b00](https://github.com/oceanbase/odc-client/commit/64b68c113c7c0c54ff60676a94c78da943824b00)
            ------
            陈朝俊
            Tue Feb 20 18:36:26 2024 +0800
