### ISSUE TITLE
[Bug]: When selecting a partial table for structural comparison and there are no tables on the source end, click on "New" and the "New" button will continue to rotate in circles

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1576]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/26d24cf0-43a4-43dd-a4dd-a2359fcf4168)

### What did you expect to happen?

New button does not rotate in circles

### How can we reproduce it (as minimally and precisely as possible)?

When selecting partial tables for structural comparison and there are no tables on the source side, click on "New"

**Comment by HSunboy** [comment]
Fixed In Commit [08f990dbc02a477c8d24d5daaedb3595b1d6e112](https://github.com/oceanbase/odc-client/commit/08f990dbc02a477c8d24d5daaedb3595b1d6e112)
            ------
            陈朝俊
            Tue Feb 20 18:37:07 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9369f167-2b6f-4184-b34d-0637dbf59fde)

pass
