### ISSUE TITLE
[Bug]: SQL did not pass structure comparison when initiating structure synchronization

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1577]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/fd4bcf95-ef90-411f-ac5c-69b4f71d77de)

![image](https://github.com/oceanbase/odc/assets/143492234/1c115a3f-0261-4783-b76d-569867fff7c4)

### What did you expect to happen?

The structure comparison SQL preview SQL has been passed into the database change

### How can we reproduce it (as minimally and precisely as possible)?

After completing the structure comparison, click to initiate structure synchronization

**Comment by HSunboy** [comment]
Fixed In Commit [08f990dbc02a477c8d24d5daaedb3595b1d6e112](https://github.com/oceanbase/odc-client/commit/08f990dbc02a477c8d24d5daaedb3595b1d6e112)
            ------
            陈朝俊
            Tue Feb 20 18:37:07 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/ac1bc223-eabe-4298-9a30-49926898f695)
pass
