### ISSUE TITLE
[Bug]: When skipping a table, the front-end does not return

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1579]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2ebb5c32-7c97-4e4d-b2b8-95d3f2d39605)

### What did you expect to happen?

Front end display

### How can we reproduce it (as minimally and precisely as possible)?

Delete the selected source side table when creating result comparison

**Comment by HSunboy** [comment]
Fixed In Commit [ad7d77e455e6947e048a85310dc7be8b8f2505bb](https://github.com/oceanbase/odc-client/commit/ad7d77e455e6947e048a85310dc7be8b8f2505bb)
            ------
            陈朝俊
            Mon Feb 26 17:11:28 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/089e3085-9566-4713-91f2-0e80c9f57736)
pass
