### ISSUE TITLE
[Bug]: "Path" identification scan table to add desensitization, report error and Submit exception

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#158]
### ODC version

421

### OB version

oracle shcema 4.1.0

### What happened?

report error

re-entry, failure to submit function
![image](https://github.com/oceanbase/odc/assets/141202865/0df3f23d-9b46-400e-a56d-9c4ecf78ad4a)

### What did you expect to happen?

no error and can be resubmitted

### How can we reproduce it (as minimally and precisely as possible)?

Identification rules create a path identification method:     
`*.*.*`

scan a library

**Comment by Huangxiao-mas** [comment]
test passed
