### ISSUE TITLE
[Bug]: There is no database change permission, and the creation of pl objects is not intercepted.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1581]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/388fdc2d-d224-40eb-aa54-3171cd2c6605)
There is no database change permission, and the creation of pl objects is not intercepted.

### What did you expect to happen?

Without database change permissions, creating pl objects should be intercepted and prompted to apply for database permissions.

### How can we reproduce it (as minimally and precisely as possible)?

1. Turn on the switch that allows the sql window to create pl
2. The user does not have permission to change the database
3. create function `fun_tinyint1` (`p1` tinyint(4)) returns tinyint(4) begin      return p1; end;

**Comment by smallsheeeep** [comment]
Notes:
If you create/drop/alter a function/procedure/trigger, then the database name will be detected and DB permission interceptor   will be valid. But, if you try to access a database inner PL body, then I cannot detect the source database name, and the DB permission interceptor may be invalid yet.  
This behavior can be treated as a known bug and I can't deal with it at the moment.

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/0deff20b-4f03-44cf-9347-800eb5958e39)
pass
