### ISSUE TITLE
[Bug]: The user does not have the permission to change the database. If an object is deleted, an alarm will be issued.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1582]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/449baa7d-583c-487b-9749-adf6f4725a01)
The user does not have the permission to change the database, no error is reported when deleting the object, and the object is not deleted.

### What did you expect to happen?

When the user does not have the permission to change the database, the user should be prompted when deleting

### How can we reproduce it (as minimally and precisely as possible)?

Delete objects in the object tree when the user does not have the permission to change the database.

**Comment by HSunboy** [comment]
Fixed In Commit [06af8981c3c0ddb27b4e64f6412a33f4999b962d](https://github.com/oceanbase/odc-client/commit/06af8981c3c0ddb27b4e64f6412a33f4999b962d)
            ------
            咏和
            Mon Mar 11 19:10:01 2024 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/744c6729-fb74-4f03-9f60-bbb98df05b47)
pass
