### ISSUE TITLE
[Bug]:Viewing partitions within the table structure shows blank space

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1584]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b4291f78-3ebe-42b9-86bd-4f19ceaf90e7)

### What did you expect to happen?

Display partition content

### How can we reproduce it (as minimally and precisely as possible)?

1. Create partition table

2. View partition

**Comment by HSunboy** [comment]
Fixed In Commit [8ba4e001b5133b2a697a12c4e49d3cf90044fe55](https://github.com/oceanbase/odc-client/commit/8ba4e001b5133b2a697a12c4e49d3cf90044fe55)
            ------
            咏和
            Wed Mar 6 13:55:08 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/14e3a102-a215-474f-9c41-24b5ef37c898)
pass
