### ISSUE TITLE
[Bug]: LDAP login prompt error

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1586]
### ODC version

ODC424

### OB version

independent

### What happened?

LDAP login prompt error
![image](https://github.com/oceanbase/odc/assets/59468957/e064ac8f-99d8-4320-be9e-e987eaa1fe2c)
![image](https://github.com/oceanbase/odc/assets/59468957/9f970b7f-08a8-4543-b1f9-553a158c5831)

### What did you expect to happen?

give a normally message

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Fixed In Commit [5eb5f35444f350162fdea61524277f6922cae1b4](https://github.com/oceanbase/odc-client/commit/5eb5f35444f350162fdea61524277f6922cae1b4)
            ------
            陈朝俊
            Mon Feb 26 17:11:00 2024 +0800
