### ISSUE TITLE
[Bug]: Create a Boolean type field table, which will become tinyint type after successful creation.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#159]
### ODC version

ODC421

### OB version

Oceanbase410 or others

### What happened?

Create a Boolean type field table, which will become tinyint type after successful creation.

### What did you expect to happen?

Created successfully

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a table, select the field as boolean type
2. View table DDL
![image](https://github.com/oceanbase/odc/assets/59468957/89e1a106-be9b-43dc-9947-291750f9d543)
![image](https://github.com/oceanbase/odc/assets/59468957/50c353bc-3d49-4646-9a69-b8b84aa0d097)
![image](https://github.com/oceanbase/odc/assets/59468957/18401307-bb63-4b2d-81bd-ea08290b554c)

**Comment by yhilmare** [comment]
boolean is a synonym of tinyint, you can reproduce it by obclient:
<img width="548" alt="截屏2023-09-05 17 19 26" src="https://github.com/oceanbase/odc/assets/22992296/b5b542b3-63df-4d6e-8e89-4c30e9d21a3a">
