### ISSUE TITLE
[Bug]: Structural comparison: When there are too many tables on the source side, the page may crash

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1596]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/78f3124c-a92d-48eb-8f1b-7263e8271c4c)

![image](https://github.com/oceanbase/odc/assets/143492234/3eeba636-2f88-4f20-a750-2a2e24549caa)

### What did you expect to happen?

The page will not crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Source end with multiple selection tables for structural comparison

**Comment by HSunboy** [comment]
Fixed In Commit [fb5ee156d4b4afdf3ac1a77aaf7db5f742293a53](https://github.com/oceanbase/odc-client/commit/fb5ee156d4b4afdf3ac1a77aaf7db5f742293a53)
            ------
            陈朝俊
            Thu Feb 22 17:12:22 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/52107794-7f11-49dc-8d52-68560849584d)
pass
