### ISSUE TITLE
[Bug]: Database change execution failed but task status still shows success

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1600]
### ODC version

4.2.x  when `odc.task-framework.enabled=true`

### OB version

all

### What happened?

1. create a new database change task which will definitely fail.
![image](https://github.com/oceanbase/odc/assets/140503120/516d01ce-e08c-40d7-ba1c-87a29be604b5)
but the task status shows that the task was executed successfully:
![image](https://github.com/oceanbase/odc/assets/140503120/fb30f42c-66d0-4052-9a66-326da79a89c3)
![image](https://github.com/oceanbase/odc/assets/140503120/344340c4-7ab6-4381-bb2a-8cbf4d796927)

### What did you expect to happen?

Correctly display task execution results

### How can we reproduce it (as minimally and precisely as possible)?

as above

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e9b92671-b6ba-4c9e-8ba1-58a13774ce5c)

pass
