### ISSUE TITLE
[Bug]: database change task do not show log

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1603]
### ODC version

424

### OB version

all

### What happened?

database change task do not show log when `odc.task-framework.enabled=true`
<img width="738" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/63983b2b-6bd1-44aa-88ef-2fde03b46fde">

### What did you expect to happen?

show log successfully

### How can we reproduce it (as minimally and precisely as possible)?

create a new database change task when `odc.task-framework.enabled=true` in `config_system_configuration` metaDB

**Comment by krihy** [comment]
this bug has fixed,
Refer PR: https://github.com/oceanbase/odc/pull/1513/files
