### ISSUE TITLE
[Bug]: No return when the internal SQL preview is greater than 1M for structural comparison

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1607]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/dd6ac018-ec1e-402f-89b5-a33b2bfc10f1)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/ecffb663-eb48-4408-9907-7ca8088c918f)

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/143492234/46db6cd7-8d02-4289-92d0-6c6988eaa4b2)
Structure comparison SQL preview with SQL size greater than 1M

**Comment by HSunboy** [comment]
Fixed In Commit [ad7d77e455e6947e048a85310dc7be8b8f2505bb](https://github.com/oceanbase/odc-client/commit/ad7d77e455e6947e048a85310dc7be8b8f2505bb)
            ------
            陈朝俊
            Mon Feb 26 17:11:28 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b202d57b-4cd9-4d06-abb1-5633688a1621)

pass
