### ISSUE TITLE
[Bug]: Oracle mode, right-click to copy to sql, the time type copied sql content is null

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1615]
### ODC version

ODC423

### OB version

independent

### What happened?

Oracle mode, right-click to copy to sql, the time type copied sql content is null
![image](https://github.com/oceanbase/odc/assets/59468957/8e3d166e-bf8f-4a8d-82c4-dca97361d113)
![image](https://github.com/oceanbase/odc/assets/59468957/ca4502fa-60fb-4912-b304-4a3e5f517562)

### What did you expect to happen?

not null

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/59468957/2e01f6ee-6e8a-46de-956f-b34ae2cab333)

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/bd605681-cecc-44f6-9dfc-755d19d0a530)

pass
