### ISSUE TITLE
[Bug]: failed to debug and execute an anonymous block ending with '/' at anonymous block window

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#162]
### ODC version

4.2.0

### OB version

OceanBase 4.1.0.1

### What happened?

debug an anonymous block:
```SQL
declare 
  var_ename varchar2(50);
  var_job varchar2(50);
  cursor cur_emp 
      is select ename,job from employees;
  begin 
      open cur_emp;
      fetch cur_emp into var_ename,var_job; 
      if cur_emp%found then 
          dbms_output.PUT_LINE('游标现在的行号: '||cur_emp%found);
          dbms_output.PUT_LINE('编号是7499的雇员名称为: '||var_ename||'，职务是: '||var_job);
          fetch cur_emp into var_ename,var_job;
      else 
          dbms_output.PUT_LINE('无数据记录: '||cur_emp%notfound);
      end if;
      
      if cur_emp%ISOPEN THEN 
          dbms_output.PUT_LINE('游标是否开启：'||cur_emp%ISOPEN);
          CLOSE cur_emp; -- 关闭游标
          dbms_output.PUT_LINE('游标关闭成功！');
      end if;
  end;
/
```
and some errors happened:
![image1](https://github.com/oceanbase/odc/assets/22992296/c926073f-7c68-4a76-9deb-3971e271d200)
![image2](https://github.com/oceanbase/odc/assets/22992296/db476c30-79bb-4fb8-90ab-f4e8e1fed6d6)

### What did you expect to happen?

Debugging can proceed normally

### How can we reproduce it (as minimally and precisely as possible)?

same as "What happened"

**Comment by yhilmare** [comment]
the front end sets the `split` flag `false`, so that odc will not split the sql which cause the second pics's exception:
<img width="552" alt="截屏2023-09-05 20 25 56" src="https://github.com/oceanbase/odc/assets/22992296/fdc36c5a-39de-47fd-b718-176563e3b5ff">

@HSunboy may take a look at this

**Comment by yhilmare** [comment]
> the front end sets the `split` flag `false`, so that odc will not split the sql which cause the second pics's exception: <img alt="截屏2023-09-05 20 25 56" width="552" src="https://user-images.githubusercontent.com/22992296/265696938-fdc36c5a-39de-47fd-b718-176563e3b5ff.png">
> 
> @HSunboy may take a look at this

I think this is normal, cause anonymous block window is only for one anonymous block, and user may not write several blocks. Does the front end do the same thing before?

**Comment by Huangxiao-mas** [comment]
test passed


![Image](https://github.com/oceanbase/odc/assets/59468957/4e1bcaf1-fb5f-4269-a16f-e4c453a5342d)
