### ISSUE TITLE
[Bug]: Oracle failed to create foreign key constraint

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1622]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/db5c591b-5f42-4c0d-98a9-8844ede56531)

### What did you expect to happen?

Created successfully

### How can we reproduce it (as minimally and precisely as possible)?

Oracle selects different databases to create foreign key constraints

**Comment by LuckyPickleZZ** [comment]
When creating cross library foreign keys, you need to execute `grant references on userA.tableA to userB`
