### ISSUE TITLE
[Bug]: Unable to select MySQL database for structural comparison

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1633]
### ODC version

odc424

### OB version

*

### What happened?

![708d0e54de1815ac6e20853e7cddd06c](https://github.com/oceanbase/odc/assets/143492234/bff9204a-dd5b-4326-a62f-077b715e8002)

### What did you expect to happen?

You can choose a MySQL database

### How can we reproduce it (as minimally and precisely as possible)?

Comparison of execution structures

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [cea31ec22170e4217984b7ba17b37823e0063395](https://github.com/oceanbase/odc-client/commit/cea31ec22170e4217984b7ba17b37823e0063395)

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/42db61a5-188e-4cff-99ac-247d09990b2f)
pass
