### ISSUE TITLE
[Bug]: DLM task, SQL preview window needs to be disabled for editing

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1648]
### ODC version

ODC424

### OB version

independent

### What happened?

Edit the DLM generated statement in the sql preview window, but it is not echoed after editing and saving.
![image](https://github.com/oceanbase/odc/assets/59468957/dac4e6fe-3218-4893-86d2-08b4fe7e9ca2)
![image](https://github.com/oceanbase/odc/assets/59468957/b0d3c1d9-7f18-4e49-87fa-ecb99a0eb835)

### What did you expect to happen?

can echo after editing and saving.

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Fixed In Commit [f35f340b944f118de92e7563716f08feb1f1bf37](https://github.com/oceanbase/odc-client/commit/f35f340b944f118de92e7563716f08feb1f1bf37)
            ------
            咏和
            Tue Mar 5 09:33:13 2024 +0800
