### ISSUE TITLE
[Bug]: SQL execution timeout error during database change modification index modification

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1651]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/c2b31a05-076c-4b70-830d-40b98b6607e2)

### What did you expect to happen?

Prompt modified to 120 hours

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [94477387e8bad409736b55be42058068ba858c76](https://github.com/oceanbase/odc-client/commit/94477387e8bad409736b55be42058068ba858c76)
            ------
            陈朝俊
            Wed Feb 28 19:47:44 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/4ff863a0-f93a-4f89-acb9-30f36535558b)
pass
