### ISSUE TITLE
[Bug]: The user has the export permission of the database, and the login database button is grayed out.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1652]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

The user has the export permission of the database, and the login database button is grayed out.
![image](https://github.com/oceanbase/odc/assets/46598871/d3bba56b-5742-415e-981d-f7a7117d1991)
![image](https://github.com/oceanbase/odc/assets/46598871/414cf692-d4b1-4835-ab4b-47992cfcdddf)

### What did you expect to happen?

The user has export permissions for the database, and the login database button should not be grayed out.

### How can we reproduce it (as minimally and precisely as possible)?

The user has the export permission of the database and views the database list.

**Comment by bluesky-xyh** [comment]
fixed: https://github.com/oceanbase/odc/issues/1665#issuecomment-1990796243

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/82ffb5b3-2541-4df4-8670-5482db0d7ff4)

pass
