### ISSUE TITLE
[Bug]: Remove the OK button from the management database permissions interface

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1653]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

Remove the OK button from the management library permissions interface.
![image](https://github.com/oceanbase/odc/assets/46598871/94c97162-06a5-4fe0-8cd0-41559681ff96)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/1118b553-89c7-40d3-9ebe-8582eecd155a)

### How can we reproduce it (as minimally and precisely as possible)?

Enter the management database permissions interface.

**Comment by HSunboy** [comment]
Fixed In Commit [f35f340b944f118de92e7563716f08feb1f1bf37](https://github.com/oceanbase/odc-client/commit/f35f340b944f118de92e7563716f08feb1f1bf37)
            ------
            咏和
            Tue Mar 5 09:33:13 2024 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/8492d75c-6cf1-4e5e-9fe4-d03deee7d1a1)
pass
