### ISSUE TITLE
[Bug]: Manual addition of sensitive columns and selection of database prompt without uniformity

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1654]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/f7339d54-6c67-4fee-84e0-19e65d3fec63)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/b05ae7e9-f1c6-46bc-af69-41cd9c64c82c)
![image](https://github.com/oceanbase/odc/assets/143492234/fe625ff2-b32b-48b8-90c6-2b1bba9931a7)

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
工单和数据源是统一的，脱敏那边场景不一样，选择的是当前项目内的数据库列表，统一必要性不大
