### ISSUE TITLE
[Bug]: The instance stored procedure cannot be run by right-clicking and reports "Incorrect number of arguments"

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1655]
### ODC version

ODC424

### OB version

Oceanbase421

### What happened?

The instance stored procedure cannot be run by right-clicking and reports "Incorrect number of arguments"
![image](https://github.com/oceanbase/odc/assets/59468957/b4ad7d47-5bc3-4c1c-810c-75fb6d6ef060)
![image](https://github.com/oceanbase/odc/assets/59468957/4a07c703-bdda-41a8-9a2c-19d5bdf5ce1a)

### What did you expect to happen?

can execute it

### How can we reproduce it (as minimally and precisely as possible)?

```sql
CREATE TABLE json_table (
    id INT AUTO_INCREMENT PRIMARY KEY,
    data JSON
);

DELIMITER //

CREATE PROCEDURE InsertJsonData(IN num_rows INT)
BEGIN
    DECLARE i INT DEFAULT 1;
    DECLARE json_data JSON;
    WHILE i <= num_rows DO
        SET json_data = JSON_OBJECT(
            'name', CONCAT('Name', i),
            'age', FLOOR(RAND() * 30 + 20),
            'email', CONCAT('user', i, '@example.com')
        );
        INSERT INTO json_table (data) VALUES (json_data);
        SET i = i + 1;
    END WHILE;
END //

DELIMITER ;
```
Right click and run

**Comment by Huangxiao-mas** [comment]
But CALL InsertJsonData(10); can be executed

**Comment by yhilmare** [comment]
parser's bug: "json_table" is a key word and we don't accept it as an object name such as table name.

I fix this.
<img width="679" alt="截屏2024-03-19 19 23 02" src="https://github.com/oceanbase/odc/assets/22992296/96b2e6df-45bb-48a9-bd83-f5b250661fba">
<img width="755" alt="截屏2024-03-19 19 23 23" src="https://github.com/oceanbase/odc/assets/22992296/fb59a613-ffd6-40dc-8924-d6ce315c655d">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1dcb92ee-f550-4d89-8634-8795be80285c)



![Image](https://github.com/oceanbase/odc/assets/143492234/dbf28807-c547-4a9c-99d6-9f1abbf65cf4)

pass
