### ISSUE TITLE
[Bug]: The user only has export permissions, and the selectable databases for the export result set task are not grayed out.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1656]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

The user only has export permissions, and the selectable databases for the export result set task are not grayed out.
![image](https://github.com/oceanbase/odc/assets/46598871/93f22fc9-0891-4391-952a-86003be23fa9)

### What did you expect to happen?

Users only have export permissions, and the databases that can be selected for the export result set task must be grayed out.

### How can we reproduce it (as minimally and precisely as possible)?

The user only has export permissions and creates an export result set task.

**Comment by HSunboy** [comment]
Fixed In Commit [7ea7f1ae8cf0ea19b645384cbbd8a08939da390e](https://github.com/oceanbase/odc-client/commit/7ea7f1ae8cf0ea19b645384cbbd8a08939da390e)
            ------
            咏和
            Fri Mar 8 09:45:18 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/bd94b88d-7324-4df0-a226-af8d5e08746f)

Incorrect name display
