### ISSUE TITLE
[Bug]: Only has the export permission of the database,running a function containing select type can return results.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1659]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/89af10de-8979-469a-bd19-f8d9b62a29d0)
Only has the export permission of the database,running a function containing select type can return results.

### What did you expect to happen?

If the user does not have query permissions for the database, an error will be reported when running pl of the query class.

### How can we reproduce it (as minimally and precisely as possible)?

```
create table test(a int);

insert into test values(1),(2),(1),(3),(3);

create function `get_a_column_data` () returns text BEGIN
    DECLARE result TEXT;
    
    SELECT GROUP_CONCAT(a SEPARATOR ', ') INTO result FROM test;
    
    RETURN result;
    end;
```

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/50cd7544-f5bb-4c6e-aaa0-9e49da7e6674)

pass
