### ISSUE TITLE
[Bug]: When creating a new data source in personal space, no connectivity check is performed

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#166]
### ODC version

4.2.0

### OB version

4.0

### What happened?

1、Use the wrong information to create a new data source in  personal space.
2、The data source is successfully created and the database under the data source is empty.
![image](https://github.com/oceanbase/odc/assets/15030999/2c9ce852-f011-4923-8954-0b1c2e6e33a7)

### What did you expect to happen?

Perform information verification when creating a new data source. If the connectivity check fails, the new data source is not allowed to be created

### How can we reproduce it (as minimally and precisely as possible)?

1、Use the wrong information to create a new data source in  personal space.
2、The data source is successfully created and the database under the data source is empty.

**Comment by HSunboy** [comment]
Fixed In Commit [cbdee53be86e7702447bb38c18ae3066308ea4c4](https://github.com/oceanbase/odc-client/commit/cbdee53be86e7702447bb38c18ae3066308ea4c4)
            ------
            晓康
            Wed Sep 6 15:46:29 2023 +0800

**Comment by Huangxiao-mas** [comment]
PASS
