### ISSUE TITLE
[Bug]: Only has the permission to change the database, and the login database button is grayed out

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1665]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/9a6b2123-34c4-48ff-b33b-4846c560429f)
Only has the permission to change the database, and the login database button is grayed out

### What did you expect to happen?

Only has the permission to change the database, and the login database button is not grayed out.

### How can we reproduce it (as minimally and precisely as possible)?

Only have change permissions for databases.

**Comment by HSunboy** [comment]
Fixed In Commit [139342f8bae6009995f303971e8d83bb141a6d6a](https://github.com/oceanbase/odc-client/commit/139342f8bae6009995f303971e8d83bb141a6d6a)
            ------
            咏和
            Tue Mar 12 14:07:26 2024 +0800
