### ISSUE TITLE
[Bug]: After modifying the package subroutine content, multiple triggering save, error

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#167]
### ODC version

4.2.1

### OB version

oracle shcema 4.1.0.1

### What happened?

first save
![image](https://github.com/oceanbase/odc/assets/141202865/bcb6553b-d1e7-4583-84ef-70e59deb19e7)
second save
![image](https://github.com/oceanbase/odc/assets/141202865/983529a2-3ab1-4565-811c-cd383bb41936)

### What did you expect to happen?

Multiple save triggers were successful

### How can we reproduce it (as minimally and precisely as possible)?

modify subroutine content, save multiple times

**Comment by Huangxiao-mas** [comment]
test passed
