### ISSUE TITLE
[Bug]: The name in the structural comparison is inconsistent with the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1670]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/d8d4b1a3-d266-426e-a159-739a5f4a0afa)
![image](https://github.com/oceanbase/odc/assets/143492234/74ac46e4-3537-4c98-8775-3dc6bbef7c35)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/3f732c68-2d00-490a-9dec-a9ff7925d03d)
![image](https://github.com/oceanbase/odc/assets/143492234/f7801b8e-bfbd-4dc7-b322-a72e9964bd38)

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [b89b8f6fd1f02f46b118709c1d78553537267a1a](https://github.com/oceanbase/odc-client/commit/b89b8f6fd1f02f46b118709c1d78553537267a1a)
            ------
            陈朝俊
            Mon Mar 4 15:58:52 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/ab892188-538e-40cc-937d-bd232ccb8abc)
![image](https://github.com/oceanbase/odc/assets/143492234/e2dc6320-aafb-43ee-87d6-47ed0cd5f355)
Still inconsistent with the design draft

**Comment by HSunboy** [comment]
Fixed In Commit [53580382ef6a9a792f9e23fc5d5c843e135bbe84](https://github.com/oceanbase/odc-client/commit/53580382ef6a9a792f9e23fc5d5c843e135bbe84)
            ------
            陈朝俊
            Tue Mar 12 10:04:02 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/7dc786e2-050f-4b88-ab73-742ca210c066)

There are still issues

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e8301fbc-7870-43bc-8098-2e4c13db0ecd)

pass
