### ISSUE TITLE
[Bug]: precision is lost when displaying timestamps

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1671]
### ODC version

4.2.4

### OB version

not related

### What happened?

precision is lost when displaying timestamps

### What did you expect to happen?

precision should not be lost

### How can we reproduce it (as minimally and precisely as possible)?

1. create a table and insert table:
```sql
create table ts_tbl(
    col_ts_3 timestamp(3),
    col_ts_6 timestamp(6)
);
insert into ts_tbl values('2022-12-12 12:12:12.0','2022-12-12 12:12:12.0');
```
2. query this data:
<img width="642" alt="截屏2024-02-29 16 43 07" src="https://github.com/oceanbase/odc/assets/22992296/8eccd3b9-bcd0-4442-bdeb-2f1a20651826">

we will see more precision if we query this data by obclient:
<img width="578" alt="截屏2024-02-29 16 44 11" src="https://github.com/oceanbase/odc/assets/22992296/0521f16b-5cd6-4cca-859e-297a3a2c6338">

**Comment by zijiacj** [comment]
have done

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/926f4795-7eef-4523-8993-7f015f6854e5)

pass
