### ISSUE TITLE
[Bug]: if query timestamp(6) value with trailing 0, then 0 will be truncated in MySQL dialect type

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#1672]
### ODC version

4.2.3

### OB version

not related

### What happened?

While selecting values of column timestamp(6), the trailing 0 will be truncated.

### What did you expect to happen?

The trailing 0 should be retained.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a table with a timestamp(6) column
2. Insert a value with trailing 0
3. query from the table

**Comment by yhilmare** [comment]
dup with #1671

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/00c16bfd-448a-49ad-a9e3-ad9253af6cb9)

pass
