### ISSUE TITLE
[Bug]: Unable to search for items when creating data source binding

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1681]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/05d8515c-a980-4878-9570-eb3b66707021)
Unable to search for items when creating data source binding

### What did you expect to happen?

Search function works

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened

**Comment by HSunboy** [comment]
Fixed In Commit [b02e6b6ad04d979bd9631bc30a97ac70a3010310](https://github.com/oceanbase/odc-client/commit/b02e6b6ad04d979bd9631bc30a97ac70a3010310)
            ------
            xiaokang
            Thu Mar 7 15:02:34 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/01654c4e-d9ee-4ae1-a4ea-82879369067f)

pass
