### ISSUE TITLE
[Bug]: The database permission application initiated in the sql window does not automatically select the database.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1683]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/cc1b8fb3-30ea-4bea-9eac-f5a21134e636)
The database permission application initiated in the sql window does not automatically select the database.

### What did you expect to happen?

Automatically select the database

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by HSunboy** [comment]
Fixed In Commit [139342f8bae6009995f303971e8d83bb141a6d6a](https://github.com/oceanbase/odc-client/commit/139342f8bae6009995f303971e8d83bb141a6d6a)
            ------
            咏和
            Tue Mar 12 14:07:26 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/53f141dc-28b7-43bb-915e-a553a80287a2)

No automatic database selection after clicking on the application

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/47b9198c-3b5f-4f3b-afca-0214a30a951e)

pass
