### ISSUE TITLE
[Bug]: Applying for library permissions is above applying for project permissions.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1684]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/780c852a-3034-4d48-a2a7-b46825d72144)
Applying for library permissions is above applying for project permissions.

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/f727573f-83a4-4a80-93ba-de73027c7086)

### How can we reproduce it (as minimally and precisely as possible)?

Open the work order list

**Comment by HSunboy** [comment]
Fixed In Commit [7ea7f1ae8cf0ea19b645384cbbd8a08939da390e](https://github.com/oceanbase/odc-client/commit/7ea7f1ae8cf0ea19b645384cbbd8a08939da390e)
            ------
            咏和
            Fri Mar 8 09:45:18 2024 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/0812e58d-c08a-4a96-96d3-cbb8238e414d)
pass
