### ISSUE TITLE
[Bug]: The database selected in the task details for applying for database permissions is not paginated.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1685]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/bf51d4a8-865d-441e-afbc-078b0a5f034e)
The database selected in the task details for applying for database permissions is not paginated.

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/965d9a1d-f640-459d-bce1-756e7917c4d5)

### How can we reproduce it (as minimally and precisely as possible)?

Select more than 10 databases to deliver tasks.

**Comment by HSunboy** [comment]
Fixed In Commit [2261f7c7be9dfef8053d8f251039b9b2845b3a24](https://github.com/oceanbase/odc-client/commit/2261f7c7be9dfef8053d8f251039b9b2845b3a24)
            ------
            咏和
            Thu Mar 7 10:33:56 2024 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/e1d90cf8-616b-478a-953c-59ed65748137)
pass
