### ISSUE TITLE
[Bug]: There is no tips when the mouse hover operation does not have permission.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1687]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/341c189b-8014-4cf9-af09-20bf3fc2df29)
There is no tips when the mouse hover operation does not have permission.

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/cde54c84-eaf1-498c-98a1-c5ee09f28560)

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by HSunboy** [comment]
Fixed In Commit [6169a89a7eb6d5c4ffdcfd6ffb1b654aaa6ea2dd](https://github.com/oceanbase/odc-client/commit/6169a89a7eb6d5c4ffdcfd6ffb1b654aaa6ea2dd)
            ------
            咏和
            Tue Mar 12 18:31:00 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/736eb1a7-efda-4efa-bbad-9a0f61e2d9c3)



![Image](https://github.com/oceanbase/odc/assets/143492234/0a5f8cc1-28b7-4aa0-855b-81becf679adc)



![Image](https://github.com/oceanbase/odc/assets/143492234/d6f23d0d-8192-499a-a208-43a3cc201e93)

pass
