### ISSUE TITLE
[Bug]: When the structural comparison results are only consistent, initiating structural synchronization should not be available

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1688]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/acc4ef23-2db7-40b6-af42-42ff86012351)

### What did you expect to happen?

Initiate structure synchronization should be grayed out

### How can we reproduce it (as minimally and precisely as possible)?

Select two identical tables to initiate structural comparison

**Comment by HSunboy** [comment]
Fixed In Commit [d5975f2e39efb8f003a60dc52b710c41182ac7ca](https://github.com/oceanbase/odc-client/commit/d5975f2e39efb8f003a60dc52b710c41182ac7ca)
            ------
            陈朝俊
            Mon Mar 4 15:59:03 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/332a9fef-7a55-44a1-9e09-e7bad4a7a87f)
pass
