### ISSUE TITLE
[Bug]: The value passed in the custom time when applying for database permission is incorrect.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1692]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

The value passed in the custom time when applying for database permission is incorrect.
![image](https://github.com/oceanbase/odc/assets/46598871/d4b9e56d-2bd4-4500-9830-bb98530a5b50)
![image](https://github.com/oceanbase/odc/assets/46598871/0ff7ba62-d66a-415b-9c12-cd005db5f1a4)

### What did you expect to happen?

Custom time displays selected time.

### How can we reproduce it (as minimally and precisely as possible)?

Issue a database permission application task, and select a custom time for the validity period.

**Comment by HSunboy** [comment]
Fixed In Commit [6ae03a531e70710341e124fc456375bb59d54f54](https://github.com/oceanbase/odc-client/commit/6ae03a531e70710341e124fc456375bb59d54f54)
            ------
            咏和
            Mon Mar 4 16:38:08 2024 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/ef153ba7-b8d5-44f8-a52a-d2c447bbfeaa)
pass
