### ISSUE TITLE
[Bug]: The application for project and task permissions was not initiated again

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1695]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/0637c00f-5ce8-4126-9c6b-ce0b88318ed0)
![image](https://github.com/oceanbase/odc/assets/143492234/f2afdd1e-77ef-4be7-a09f-9f2ee3756a4e)

### What did you expect to happen?

Initiated again

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by bluesky-xyh** [comment]
the display of re-initiation is subject to conditions, as shown above: In the scenario where the status is EXECUTION_SUCCEEDED, it must be met at the same time. The person currently viewing the details is the creator of the work order, and then it will be displayed.
