### ISSUE TITLE
[Bug]: When searching all work orders according to the work order number, occasionally the task cannot be found.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1696]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

I used the admin user to log in to view all work orders. I did not find the task 75, but this task can be viewed in the sql plan list.
![image](https://github.com/oceanbase/odc/assets/46598871/c1445d18-0760-4c3d-9931-d86084bdb778)
![image](https://github.com/oceanbase/odc/assets/46598871/56644959-cf18-41d9-bd37-b1cd069e541e)

### What did you expect to happen?

I can search for tasks based on task id.

### How can we reproduce it (as minimally and precisely as possible)?

Search for tasks with id 75.

**Comment by guowl3** [comment]
schedule will not appear in lists
