### ISSUE TITLE
[Bug]: sql plan terminate button invalid

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1698]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

sql plan terminate button invalid
![image](https://github.com/oceanbase/odc/assets/46598871/7a8af386-203a-4ad1-be40-41bbb09c5a51)

### What did you expect to happen?

Successfully terminated sql plan.

### How can we reproduce it (as minimally and precisely as possible)?

Terminate sql scheduled task.

**Comment by bluesky-xyh** [comment]
<img width="979" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/82d39302-be18-4745-b0e5-cbae1c864eff">
<img width="825" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/b51dc6ec-e034-4cd2-8f91-2407cefa1b4a">
