### ISSUE TITLE
[Bug]: When the admin user views the details of a shadow table task issued by an ordinary user, NPE occurs.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1699]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/fb115143-5262-47d0-8263-b720e24df670)
When the admin user views the details of a shadow table task issued by an ordinary user, NPE occurs.

### What did you expect to happen?

View task details without reporting errors

### How can we reproduce it (as minimally and precisely as possible)?

Use an ordinary user to deliver shadow table synchronization tasks, and use the admin user to view task details.

**Comment by MarkPotato777** [comment]
It occurs when the ticket is auto-approval

**Comment by MarkPotato777** [comment]
The structure comparing task has this issue too.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/63e16684-011a-4211-b084-674b735f8d49)



![Image](https://github.com/oceanbase/odc/assets/143492234/d595d560-8fbc-462d-86ed-7b43fa909735)

PASS
