### ISSUE TITLE
[Bug]: DLM task, the task is being executed, but the outer task shows that it has been completed.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1705]
### ODC version

ODC424

### OB version

independent

### What happened?

DLM task, the task is being executed, but the outer task shows that it has been completed.
![image](https://github.com/oceanbase/odc/assets/59468957/583fba36-a506-4aab-b576-db65ae756c54)

### What did you expect to happen?

。。

### How can we reproduce it (as minimally and precisely as possible)?

。。

**Comment by krihy** [comment]
duplicate issue refer to @guowl3
