### ISSUE TITLE
[Bug]: DLM task, the task report field type is not supported, and the task is not stopped.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1707]
### ODC version

ODC424

### OB version

independent

### What happened?

DLM task, the task report field type is not supported, and the task is not stopped.
![image](https://github.com/oceanbase/odc/assets/59468957/6b33fabd-91ce-445f-9998-bec052a4720b)
![image](https://github.com/oceanbase/odc/assets/59468957/4aaf10cc-08a0-45eb-bc66-9db5b3d07e75)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by krihy** [comment]
duplicate issue has assigned to @guowl3
