### ISSUE TITLE
[Bug]: The source table or target table is deleted during the archiving task, but the task does not stop.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1708]
### ODC version

ODC424

### OB version

independent

### What happened?

The source table or target table is deleted during the archiving task, but the task does not stop.
![image](https://github.com/oceanbase/odc/assets/59468957/c3b5e316-6c5c-4180-b49e-6ae7a0d7f4ba)

### What did you expect to happen?

。。

### How can we reproduce it (as minimally and precisely as possible)?

。。

**Comment by krihy** [comment]
![Image](https://github.com/oceanbase/odc/assets/51393259/2a83d63a-3462-41fe-9b00-621fb817672f)
task log suspended on 6/10, time from 2024-03-05 21:45:33 to 2024-03-05 21:55:33, and still be suspend

**Comment by krihy** [comment]
expect: when target table deleted,  dml final status is failed @guowl3
