### ISSUE TITLE
[Bug]: When data archiving is initiated again, the archiving table and filtering conditions will not be inherited

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1712]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b917bc7f-7e7f-4209-8ba8-8eaa3736b680)

### What did you expect to happen?

Existing archive table and filtering conditions

### How can we reproduce it (as minimally and precisely as possible)?

Initiate data archiving again

**Comment by HSunboy** [comment]
Fixed In Commit [7ea7f1ae8cf0ea19b645384cbbd8a08939da390e](https://github.com/oceanbase/odc-client/commit/7ea7f1ae8cf0ea19b645384cbbd8a08939da390e)
            ------
            咏和
            Fri Mar 8 09:45:18 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/416a7111-6197-48e5-ac72-90ea6d729486)
pass
