### ISSUE TITLE
[Bug]: The first click to download database changes may result in query failure

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1713]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/1953b5cc-1386-443d-ac46-ceac54b23e4a)

### What did you expect to happen?

Download successful

### How can we reproduce it (as minimally and precisely as possible)?

1. Execute query statements in database changes
2. Click to download the query result set

**Comment by smallsheeeep** [comment]
Sorry, I can not reproduce it according to your description.
