### ISSUE TITLE
[Bug]: Clicking to initiate page crash again when there is variable configuration in data cleaning

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1714]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/41141d9f-7787-46ab-9b4b-799e020091e2)
![image](https://github.com/oceanbase/odc/assets/143492234/3b006709-2617-40a7-a322-91d781e9e635)

### What did you expect to happen?

The page will not crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Create data cleaning and clean up existing variable configurations
2. After successful creation, click to initiate again

**Comment by HSunboy** [comment]
Fixed In Commit [f35f340b944f118de92e7563716f08feb1f1bf37](https://github.com/oceanbase/odc-client/commit/f35f340b944f118de92e7563716f08feb1f1bf37)
            ------
            咏和
            Tue Mar 5 09:33:13 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/539880c5-4717-4471-9bf7-82fd435dc362)
pass
