### ISSUE TITLE
[Bug]: Native ORACLE export does not support global snapshots and file size limits, and these two options need to be hidden.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1715]
### ODC version

ODC424

### OB version

independent

### What happened?

Native ORACLE export does not support global snapshots and file size limits, and these two options need to be hidden.
![image](https://github.com/oceanbase/odc/assets/59468957/df030217-94c8-40bd-bb1c-82b3f737da59)

### What did you expect to happen?

hidding it

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3d0ad25e-d78e-4812-994f-8e1ae06fb6b7)

pass
