### ISSUE TITLE
[Bug]: Use native oracle to open session management and report an error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1716]
### ODC version

ODC 4.2.4

### OB version

oracle19c

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/841cee45-0f51-478d-bf38-81e090af1ecc)
Use native oracle to open session management and report an error

### What did you expect to happen?

Use native Oracle to open session management without reporting errors

### How can we reproduce it (as minimally and precisely as possible)?

Open session management using native oracle.

**Comment by PeachThinking** [comment]
Oracle 19c version has not been adapted yet. Currently it is only adapted to oracle11g.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5528fa1f-2657-4296-8980-c95fcb654f66)

pass
