### ISSUE TITLE
[Bug]: MYSQL database does not associate data dictionaries

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1718]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/7cb79734-6003-4e37-9a16-f2eabc712e29)

### What did you expect to happen?

View of Lenovo information_schema

### How can we reproduce it (as minimally and precisely as possible)?

Make associations within the SQL window of MySQL

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/e05ec17b-63fd-4f8c-9402-ea5103c36b0c)

**Comment by HSunboy** [comment]
Fixed In Commit [40f3508360809d997a4f93cbec27592c332dff0e](https://github.com/oceanbase/odc-client/commit/40f3508360809d997a4f93cbec27592c332dff0e)
            ------
            xiaokang
            Tue Mar 5 17:12:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8b882033-d7b9-4d77-b687-52c8405ff66d)

pass
