### ISSUE TITLE
[Bug]: Native oracle exports TIMESTAMP type data into sql format without the function TO_TIMESTAMP

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1722]
### ODC version

ODC424

### OB version

independent

### What happened?

Native oracle exports TIMESTAMP type data into sql format without the function TO_TIMESTAMP
![image](https://github.com/oceanbase/odc/assets/59468957/177bb9ac-d20d-4967-bfdb-5207e0afbae7)
![image](https://github.com/oceanbase/odc/assets/59468957/88a527a2-a91f-472d-8a75-db09e129db1d)

### What did you expect to happen?

`INSERT INTO MY_TIMESTAMP_TABLE (ID, TIMESTAMP_COLUMN)
VALUES (1, TO_TIMESTAMP('2023-04-01 14:30:00', 'YYYY-MM-DD HH24:MI:SS'));`

### How can we reproduce it (as minimally and precisely as possible)?

.

**Comment by LuckyPickleZZ** [comment]
We cannot fix this for now. DataX does not support.
