### ISSUE TITLE
[Bug]: When viewing RAW type data in native Oracle, the display is inconsistent with DBEAVER

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1725]
### ODC version

ODC424

### OB version

independent

### What happened?

When viewing RAW type data in native Oracle, the display is inconsistent with DBEAVER
![image](https://github.com/oceanbase/odc/assets/59468957/cdf11b2f-8579-4f3b-9694-ad34683b687b)
![image](https://github.com/oceanbase/odc/assets/59468957/3dd8d7a5-57aa-4d32-9952-ccc1634abcb9)

### What did you expect to happen?

。。

### How can we reproduce it (as minimally and precisely as possible)?

`CREATE TABLE my_table (
  id NUMBER PRIMARY KEY,
  raw_column RAW(500)
);
INSERT INTO my_table (id, raw_column)
VALUES (1, HEXTORAW('7D'));

`

**Comment by PeachThinking** [comment]
![Image](https://github.com/oceanbase/odc/assets/140503120/20d9da36-a711-474e-8cb7-5bcf65d196df)



![Image](https://github.com/oceanbase/odc/assets/140503120/9d9642c2-a89f-4309-853f-c450eddce1e9)
