### ISSUE TITLE
[Bug]: The oracle mode stored procedure cannot be run by right-clicking and the parameter input box cannot be displayed.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1728]
### ODC version

ODC424

### OB version

independent

### What happened?

The oracle mode stored procedure cannot be run by right-clicking and the parameter input box cannot be displayed.
![image](https://github.com/oceanbase/odc/assets/59468957/28618c45-4eb9-442d-900a-5432cebf7b4a)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

`create table TC_TARCHIVES
(
    VC_TENANT_ID         VARCHAR2(32) not null,
    VC_ARCHIVES_NO       VARCHAR2(24) not null,
    VC_REQUEST_NO        VARCHAR2(32),
    C_ARCHIVES_TYPE      CHAR(2),
    B_ARCHIVES_CONTENT   BLOB,
    VC_OP_TIME           VARCHAR2(14),
    VC_OPERATOR_NO       VARCHAR2(16),
    C_AUDIT_FLAG         CHAR(1),
    VC_AUDIT_NO          VARCHAR2(16),
    C_ARCHIVES_STATE     CHAR(1),
    VC_CUST_NO           VARCHAR2(12),
    L_SERIAL_NO          NUMBER,
    VC_DESCRIBE          VARCHAR2(256),
    VC_STORAGE_FILE_NAME VARCHAR2(255),
    VC_TRADE_ACCO        VARCHAR2(32),
    VC_MANAGER_CODE      VARCHAR2(18),
    VC_REJECT_REASON     VARCHAR2(100),
    VC_REMARK            VARCHAR2(256),
    VC_PRODUCT_CODE      VARCHAR2(32),
    VC_STORAGE_FILE_PATH VARCHAR2(256),
    VC_STORAGE_FILE_NO   VARCHAR2(100),
    VC_BATCH_NO          VARCHAR2(32),
    constraint PK_TC_TARCHIVES primary key (VC_TENANT_ID, VC_ARCHIVES_NO)
);
CREATE OR REPLACE PROCEDURE generate_tarchives_data(p_records IN NUMBER) IS
BEGIN
  -- 一个简单的循环来生成模拟数据
  FOR i IN 1..p_records LOOP
    INSERT INTO TC_TARCHIVES (
      VC_TENANT_ID,
      VC_ARCHIVES_NO,
      VC_REQUEST_NO,
      C_ARCHIVES_TYPE,
      B_ARCHIVES_CONTENT,
      VC_OP_TIME,
      VC_OPERATOR_NO,
      C_AUDIT_FLAG,
      VC_AUDIT_NO,
      C_ARCHIVES_STATE,
      VC_CUST_NO,
      L_SERIAL_NO,
      VC_DESCRIBE,
      VC_STORAGE_FILE_NAME,
      VC_TRADE_ACCO,
      VC_MANAGER_CODE,
      VC_REJECT_REASON,
      VC_REMARK,
      VC_PRODUCT_CODE,
      VC_STORAGE_FILE_PATH,
      VC_STORAGE_FILE_NO,
      VC_BATCH_NO
    ) VALUES (
      'TENANT_' || TO_CHAR(tarchives_seq.NEXTVAL),
      'ARCHIVE_' || TO_CHAR(tarchives_seq.NEXTVAL),
      'REQ' || LPAD(TO_CHAR(tarchives_seq.CURRVAL), 10, '0'),
      'AT',
      EMPTY_BLOB(), -- Placeholder for BLOB, consider using real binary data
      TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
      'OPER' || LPAD(TO_CHAR(tarchives_seq.CURRVAL), 5, '0'),
      'Y',
      'AUDIT' || LPAD(TO_CHAR(tarchives_seq.CURRVAL), 5, '0'),
      'S',
      'CUST' || LPAD(TO_CHAR(tarchives_seq.CURRVAL), 5, '0'),
      tarchives_seq.CURRVAL,
      'Mock description',
      'MockFilename.pdf',
      LPAD(TO_CHAR(tarchives_seq.CURRVAL), 10, '0'),
      'MANAGER' || LPAD(TO_CHAR(tarchives_seq.CURRVAL), 5, '0'),
      'No reason',
      'Mock remark',
      'PROD' || LPAD(TO_CHAR(tarchives_seq.CURRVAL), 5, '0'),
      '/path/to/file',
      'FILENO' || LPAD(TO_CHAR(tarchives_seq.CURRVAL), 5, '0'),
      'BATCH' || LPAD(TO_CHAR(tarchives_seq.CURRVAL), 5, '0')
    );
  END LOOP;
  
  -- 提交事务
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    -- 如果有错误，输出错误信息并回滚事务
    DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
    ROLLBACK;
END generate_tarchives_data;

`

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/e0a19306-d004-4e89-a3c7-26b7de72d6ca)
It seems to be a parser problem

**Comment by HSunboy** [comment]
oracle do not support running

**Comment by HSunboy** [comment]
Fixed In Commit [0dcd7443f1f343be5ac9395aba06427deef4608a](https://github.com/oceanbase/odc-client/commit/0dcd7443f1f343be5ac9395aba06427deef4608a)
            ------
            xiaokang
            Tue Mar 5 17:01:06 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f9fe7032-a8c2-40be-b98b-115e9fc0e507)

pass
