### ISSUE TITLE
[Bug]: The value of partition type in setting partition policy is incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1732]
### ODC version

ODC4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/8644c501-bb0c-4c5e-a073-bb00179d8656)
The value of partition type in setting partition policy is incorrect

### What did you expect to happen?

Display the correct section type content

### How can we reproduce it (as minimally and precisely as possible)?

Create a partition scheduled task and view the partition type

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/04132ed9-79ac-487a-920b-9e491e4f755c)

pass
