### ISSUE TITLE
[Bug]: "Only show unset tables" button works incorrectly

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1734]
### ODC version

ODC4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/3dba3340-c4c7-4168-b3d3-90ee55ca1cb7)
None of these three tables has a partition plan set. After checking "Only show unset tables", no table is displayed.

### What did you expect to happen?

Correctly filter out unset tables

### How can we reproduce it (as minimally and precisely as possible)?

There are tables with no partition plan set, check "Only show unset tables"

**Comment by HSunboy** [comment]
Fixed In Commit [5bd5724fb30e7e74ac1078b75aee65eac346da49](https://github.com/oceanbase/odc-client/commit/5bd5724fb30e7e74ac1078b75aee65eac346da49)
            ------
            咏和
            Tue Mar 5 11:44:20 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/a95a5785-2894-48a1-a7af-31900b107d28)



![Image](https://github.com/oceanbase/odc/assets/143492234/e641463d-bfd3-48db-b4d8-5b9c96844b27)

pass
