### ISSUE TITLE
[Bug]: The partition plan does not load the partition table in obmysql mode

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1736]
### ODC version

ODC4.2.4

### OB version

OBMySQL

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/cffa3c9c-6b09-4f68-ab77-fc1ce83c3246)
![image](https://github.com/oceanbase/odc/assets/46598871/ce52b907-f30f-4f22-bc70-d5fd527d8048)
The partition plan does not load the partition table in obmysql mode

### What did you expect to happen?

The partition plan loads the partition table in obmysql mode

### How can we reproduce it (as minimally and precisely as possible)?

Deliver partition planning tasks in mysql mode

**Comment by yhilmare** [comment]
the api gives the right data:
<img width="1246" alt="截屏2024-03-04 21 31 55" src="https://github.com/oceanbase/odc/assets/22992296/43b499e9-05be-4185-92e4-68a11b48b364">

**Comment by HSunboy** [comment]
Fixed In Commit [5bd5724fb30e7e74ac1078b75aee65eac346da49](https://github.com/oceanbase/odc-client/commit/5bd5724fb30e7e74ac1078b75aee65eac346da49)
            ------
            咏和
            Tue Mar 5 11:44:20 2024 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/3594fa7d-eb92-4bad-8a58-712961b84595)
pass
