### ISSUE TITLE
[Bug]: The tips for setting the partition policy is not fully displayed.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1737]
### ODC version

ODC4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/f64da76f-32e8-475b-996d-43c245ab48b4)
The tips for setting the partition policy is not fully displayed.

### What did you expect to happen?

Show complete tips

### How can we reproduce it (as minimally and precisely as possible)?

Create partition scheduled tasks and set partition strategies

**Comment by HSunboy** [comment]
Fixed In Commit [2261f7c7be9dfef8053d8f251039b9b2845b3a24](https://github.com/oceanbase/odc-client/commit/2261f7c7be9dfef8053d8f251039b9b2845b3a24)
            ------
            咏和
            Thu Mar 7 10:33:56 2024 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/ba372a08-8d1c-45b4-9de3-d3c7dca03383)
pass
