### ISSUE TITLE
[Bug]: There is no sql preview content when deleting a partition in the partition plan.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1738]
### ODC version

ODC4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/2e019200-9cfe-47da-b595-a53078ec7f20)
There is no sql preview content when deleting a partition in the partition plan.

### What did you expect to happen?

Show delete partition sql preview content

### How can we reproduce it (as minimally and precisely as possible)?

Create Partition Plan Settings Delete Partition Policy

**Comment by yhilmare** [comment]
you may check that if your drop settings will lead to any dropping operation?
