### ISSUE TITLE
[Bug]: Oracle database exists when selecting databases for data archiving and data cleaning

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1739]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/922aabbd-7872-4cc1-9d12-b097e7aaa12d)
![image](https://github.com/oceanbase/odc/assets/143492234/f080e750-e47a-4619-9728-de0550b2db02)

### What did you expect to happen?

No Oracle database exists

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by bluesky-xyh** [comment]
@guowl3 need to confirm

**Comment by guowl3** [comment]
Version 424 already supports DLM tasks for OBOracle
