### ISSUE TITLE
[Bug]: PL parameter not escaped

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#174]
### ODC version

4.2.0

### OB version

ob-mysql, any version.

### What happened?

As shown in the following figure, the single quotation mark in the input parameter is not escaped

![image](https://github.com/oceanbase/odc/assets/36879124/8d634202-a745-43cc-ae9e-f29a675e85cf)

### What did you expect to happen?

Single quote would be escaped.

### How can we reproduce it (as minimally and precisely as possible)?

Execute 
```
create function `print_message` (`message` varchar(255)) returns varchar(255) BEGIN
  declare result  varchar(255);
  SELECT message into result;
  return result;
END;
```
Call it in ODC, then input any param with single quote.

**Comment by Huangxiao-mas** [comment]
passed
