### ISSUE TITLE
[Bug]: Native ORACLE exports public synonyms, the object type displayed in task details, and the structure processing status is displayed as empty

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1741]
### ODC version

ODC424

### OB version

independent

### What happened?

Native ORACLE exports public synonyms, the object type displayed in task details, and the structure processing status is displayed as empty
![image](https://github.com/oceanbase/odc/assets/59468957/7209c40e-6347-472c-a3fe-bb2545b25c53)

### What did you expect to happen?

non empty

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/504e3da7-c4b9-4e35-9660-74cf5cd49fd2)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3c4cd2f4-d97c-4f63-b823-f8307ba36bfa)

pass
