### ISSUE TITLE
[Bug]: Clicking to disable data cleaning will not trigger the interface

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1745]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/a4928b11-2952-43f5-b9da-e089cd217d3d)

### What did you expect to happen?

Click to disable and pop up a pop-up window

### How can we reproduce it (as minimally and precisely as possible)?

1. Create data cleaning for the cycle
2. Disable data cleaning

**Comment by bluesky-xyh** [comment]
Duplicate cases #
https://github.com/oceanbase/odc/issues/1692
