### ISSUE TITLE
[Bug]: Export the stored procedure structure to a table, DELIMITER $$ does not have line breaks

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1746]
### ODC version

ODC424

### OB version

independent

### What happened?

Export the stored procedure structure to a table, DELIMITER $$ does not have line breaks
![image](https://github.com/oceanbase/odc/assets/59468957/c304eb19-180e-445d-bde2-c54a821602bc)

### What did you expect to happen?

`
DROP PROCEDURE GENERATE_TARCHIVES_BULK_DATA;
DELIMITER $$

CREATE OR REPLACE PROCEDURE "GENERATE_TARCHIVES_BULK_DATA" (p_record_count IN NUMBER) IS
BEGIN
  FOR i IN 1..p_record_count LOOP
    INSERT INTO TC_TARCHIVES (
      VC_ARCHIVES_NO,
      VC_REQUEST_NO,
      C_ARCHIVES_TYPE,
      B_ARCHIVES_CONTENT,
      VC_OP_TIME,
      VC_OPERATOR_NO,
      C_AUDIT_FLAG,
      VC_AUDIT_NO,
      C_ARCHIVES_STATE,
      VC_CUST_NO,
      L_SERIAL_NO,
      VC_DESCRIBE,
      VC_STORAGE_FILE_NAME,
      VC_TRADE_ACCO,
      VC_MANAGER_CODE,
      VC_REJECT_REASON,
      VC_REMARK,
      VC_PRODUCT_CODE,
      VC_STORAGE_FILE_PATH,
      VC_STORAGE_FILE_NO,
      VC_BATCH_NO
    ) VALUES (
      'ARCHIVES_' || LPAD(TO_CHAR(i), 10, '0'), -- 示例档案编号
      'REQ_' || LPAD(TO_CHAR(i), 10, '0'), -- 示例请求编号
      'TY', -- 档案类型示例值
      EMPTY_BLOB(), -- BLOB字段的模拟数据，这里是空BLOB
      TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'), -- 操作时间
      'OPER_' || LPAD(TO_CHAR(i), 5, '0'), -- 操作员编号
      'Y', -- 审计标志示例值
      'AUD_' || LPAD(TO_CHAR(i), 5, '0'), -- 审计编号
      'A', -- 档案状态示例值
      LPAD(TO_CHAR(i), 12, '0'), -- 客户编号
      i, -- 序列号
      '描述信息 ' || TO_CHAR(i), -- 描述
      '文件名' || TO_CHAR(i) || '.txt', -- 存储文件名
      'TRADE_' || LPAD(TO_CHAR(i), 10, '0'), -- 交易账号
      'MANAGER_' || LPAD(TO_CHAR(i), 5, '0'), -- 管理员代码
      '无', -- 拒绝理由
      '备注信息 ' || TO_CHAR(i), -- 备注
      'PROD_' || LPAD(TO_CHAR(i), 5, '0'), -- 产品代码
      '/fake/path/to/file/' || TO_CHAR(i), -- 存储文件路径
      'FILENO_' || LPAD(TO_CHAR(i), 5, '0'), -- 存储文件编号
      'BATCH_' || LPAD(TO_CHAR(i), 5, '0') -- 批量编号
    );
  END LOOP;
  
  COMMIT; -- 提交事务
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK; -- 出现异常，回滚事务
    RAISE; -- 抛出异常以供调试
END generate_tarchives_bulk_data;
$$

`

### How can we reproduce it (as minimally and precisely as possible)?

.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6e797e3c-ad11-42cf-a324-99101d49ba2d)

pass
