### ISSUE TITLE
[Bug]: Database list search error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1747]
### ODC version

ODC4.2.4

### OB version

-

### What happened?

Jump to page 5 in the database list, but the corresponding database cannot be searched.
![image](https://github.com/oceanbase/odc/assets/46598871/e91a4767-8b79-4941-b855-d0a749415e53)
![image](https://github.com/oceanbase/odc/assets/46598871/bc3e2c9a-0ff4-491c-a5f1-ebc08682b4c2)

### What did you expect to happen?

Search the corresponding database

### How can we reproduce it (as minimally and precisely as possible)?

Jump to page five and search

**Comment by HSunboy** [comment]
Fixed In Commit [88ac0482c86cf8d3b9551a38f15c3657e1b2b553](https://github.com/oceanbase/odc-client/commit/88ac0482c86cf8d3b9551a38f15c3657e1b2b553)
            ------
            xiaokang
            Mon Mar 25 13:32:29 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9876a908-6526-47ff-9202-df4a709fae66)

pass
