### ISSUE TITLE
[Bug]: When exporting a program package, the object type in the task details does not display the corresponding package body.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1755]
### ODC version

ODC424

### OB version

independent

### What happened?

When exporting a program package, the object type in the task details does not display the corresponding package body.
![image](https://github.com/oceanbase/odc/assets/59468957/f75e64d1-ee49-4efb-810e-d916761243d1)
![image](https://github.com/oceanbase/odc/assets/59468957/88f5dd7c-69e4-4656-8aa8-75db7f4e07c0)

### What did you expect to happen?

Display the corresponding data object

### How can we reproduce it (as minimally and precisely as possible)?

export package

**Comment by bluesky-xyh** [comment]
<img width="562" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/0f897c2a-198c-4bb6-8212-4ec687a30fac">
Expected PACKAGE_BODY

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5c31a868-aeb8-4327-8f6f-d211cefdb078)

pass
