### ISSUE TITLE
[Bug]: the location of a sql-check's violation is not correct 

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#1758]
### ODC version

4.2.4

### OB version

not related

### What happened?

I input a statement and add some break lines before it
<img width="520" alt="截屏2024-03-05 21 09 01" src="https://github.com/oceanbase/odc/assets/22992296/9379bf14-423f-4f21-a76d-c42cde5f3f24">

I click sql-check button, the location of these violations is not correct:
<img width="614" alt="截屏2024-03-05 21 09 43" src="https://github.com/oceanbase/odc/assets/22992296/5ae31379-cdee-4a56-8dee-58395ebee5a3">

as you can see, the offset is zero:

<img width="204" alt="截屏2024-03-05 21 10 15" src="https://github.com/oceanbase/odc/assets/22992296/8c0af872-84fc-4735-98ba-37ab63bc6b54">

### What did you expect to happen?

location should be right

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by yhilmare** [comment]
remember don't add ";" at the end of the statement or you will not reproduce it~

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/db2d7ce1-5840-4a38-815d-7c3253e3333b)

The problem still exists

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e989b10d-719f-4cd9-a670-5714459d169c)

pass
