### ISSUE TITLE
[Bug]: Approval task report TaskEntities can not be empty

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#176]
### ODC version

ODC4.2.0

### OB version

Oceanbase 4.1.0

### What happened?

Approval task report TaskEntities can not be empty

### What did you expect to happen?

Execute the task normally

### How can we reproduce it (as minimally and precisely as possible)?

1. Create approval tasks
2. click through
![image](https://github.com/oceanbase/odc/assets/59468957/4d8740c7-0a15-4cae-b3a0-b7a71b46dff8)
![image](https://github.com/oceanbase/odc/assets/59468957/226419a8-cb29-4503-bd15-505cb6aba553)

**Comment by Huangxiao-mas** [comment]
Clicking through on the taskbar I initiated will trigger this error。 @guowl3

**Comment by HSunboy** [comment]
Fixed In Commit [191775bd9857bd21d60ae684d990f666e084a541](https://github.com/oceanbase/odc-client/commit/191775bd9857bd21d60ae684d990f666e084a541)
            ------
            咏和
            Wed Sep 6 17:56:12 2023 +0800
