### ISSUE TITLE
[Bug]: Native Oracle import function, after import, some fields in the function are missing

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1761]
### ODC version

ODC424

### OB version

independent

### What happened?

Native Oracle import function, after import, some fields in the function are missing
![image](https://github.com/oceanbase/odc/assets/59468957/13db36b0-f52d-4ef4-b19e-687dbfb95b18)
![image](https://github.com/oceanbase/odc/assets/59468957/506b90d9-0c37-4b34-a827-e26cffb3e5df)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

[58774_export_file (1).zip](https://github.com/oceanbase/odc/files/14503644/58774_export_file.1.zip)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6e6e9bc6-b59f-4a08-b6ce-42330e71d06b)

pass
