### ISSUE TITLE
[Bug]: Cancel modification in configuration center without secondary confirmation

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1764]
### ODC version

odc424

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/729d3f9e-a475-49ca-b346-92a30b0755b3

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/9b285366-e496-4683-9465-6694333209b8)

### How can we reproduce it (as minimally and precisely as possible)?

1. Modify Configuration Center
2. Click to cancel

**Comment by HSunboy** [comment]
Fixed In Commit [b02e6b6ad04d979bd9631bc30a97ac70a3010310](https://github.com/oceanbase/odc-client/commit/b02e6b6ad04d979bd9631bc30a97ac70a3010310)
            ------
            xiaokang
            Thu Mar 7 15:02:34 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/0119961c-523f-4539-9cb5-88280220b4cb)
pass
