### ISSUE TITLE
[Bug]: Native ORACLE import trigger, the ddl after import does not match the original statement

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1765]
### ODC version

ODC424

### OB version

independent

### What happened?

Native ORACLE import trigger, the ddl after import does not match the original statement
![image](https://github.com/oceanbase/odc/assets/59468957/46b4b99f-fba5-42da-81e4-f704b428e439)
![image](https://github.com/oceanbase/odc/assets/59468957/a05978f0-3d13-4c2c-af60-97675a7ce5de)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

`CREATE TABLE "ODC_TEST"."TC_TARCHIVES" 
   (	"VC_TENANT_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"VC_ARCHIVES_NO" VARCHAR2(24) NOT NULL ENABLE, 
	"VC_REQUEST_NO" VARCHAR2(32), 
	"C_ARCHIVES_TYPE" CHAR(2), 
	"B_ARCHIVES_CONTENT" BLOB, 
	"VC_OP_TIME" VARCHAR2(14), 
	"VC_OPERATOR_NO" VARCHAR2(16), 
	"C_AUDIT_FLAG" CHAR(1), 
	"VC_AUDIT_NO" VARCHAR2(16), 
	"C_ARCHIVES_STATE" CHAR(1), 
	"VC_CUST_NO" VARCHAR2(12), 
	"L_SERIAL_NO" NUMBER, 
	"VC_DESCRIBE" VARCHAR2(256), 
	"VC_STORAGE_FILE_NAME" VARCHAR2(255), 
	"VC_TRADE_ACCO" VARCHAR2(32), 
	"VC_MANAGER_CODE" VARCHAR2(18), 
	"VC_REJECT_REASON" VARCHAR2(100), 
	"VC_REMARK" VARCHAR2(256), 
	"VC_PRODUCT_CODE" VARCHAR2(32), 
	"VC_STORAGE_FILE_PATH" VARCHAR2(256), 
	"VC_STORAGE_FILE_NO" VARCHAR2(100), 
	"VC_BATCH_NO" VARCHAR2(32), 
	 CONSTRAINT "PK_TC_TARCHIVES" PRIMARY KEY ("VC_TENANT_ID", "VC_ARCHIVES_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("B_ARCHIVES_CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING );
`
[58859_export_file.zip](https://github.com/oceanbase/odc/files/14503873/58859_export_file.zip)

**Comment by LuckyPickleZZ** [comment]
We use dbms_metadata.get_ddl to get this ddl, and it could be executed successfully. So we won't fix this.
