### ISSUE TITLE
[Bug]: Failed to apply for project permissions

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1769]
### ODC version

4.2.4

### OB version

no

### What happened?

Failed to apply for project permissions for a new user：
<img width="564" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/a4e1b4a1-86cc-484b-8495-e615ff8e2364">

![image](https://github.com/oceanbase/odc/assets/140503120/ea1beb9b-4592-481a-a8b7-8c733039ed22)
![image](https://github.com/oceanbase/odc/assets/140503120/177857a3-687b-49fb-bcc7-8e6a54d0582f)

### What did you expect to happen?

Successfully applied for project permissions

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a new user with the master account
2. Log in to odc with new user
3. Apply for project permissions as a new user

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e14429f4-3253-4911-8d1e-88e550b19d41)

pass
