### ISSUE TITLE
[Bug]: Oceanbase data source import file failed, array out of bounds

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1781]
### ODC version

ODC424

### OB version

independent

### What happened?

Oceanbase data source ORACLE mode import file failed, array out of bounds
![image](https://github.com/oceanbase/odc/assets/59468957/94ddcd8e-c86f-44a7-acca-02c7be68f5e0)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

`CREATE TABLE "NON_PARTRANGES_LIST_PRI2" 
   (	"COL1" NUMBER(*,0), 
	"COL2" NUMBER, 
	"COL3" CHAR(10), 
	"COL4" VARCHAR2(10), 
	"COL5" BLOB, 
	"COL6" CLOB, 
	"COL7" DATE, 
	"COL11" RAW(10)
)`
[NON_PARTRANGES_LIST_PRI2.csv](https://github.com/oceanbase/odc/files/14506960/NON_PARTRANGES_LIST_PRI2.csv)

**Comment by LuckyPickleZZ** [comment]
Invalid date in file.
![image](https://github.com/oceanbase/odc/assets/36879124/3711de34-3402-4a17-a33b-0043909e042e)
