### ISSUE TITLE
[Bug]: The execution record is not within the current SQL window, but also includes the execution records of other windows

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1784]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/4c5d4fe1-2db1-49b0-a78c-a312f1572c1c)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/06eeeb32-3d62-4675-a5ea-1685ecbb324a)

### How can we reproduce it (as minimally and precisely as possible)?

1. Execute SQL
2. Open an SQL window in another database to view execution records

**Comment by HSunboy** [comment]
it's not 4.2.4 work
