### ISSUE TITLE
[Bug]: View annotation not displayed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1787]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/30c4eded-1e9b-46d0-a350-dc496d51781a)

### What did you expect to happen?

display comments

### How can we reproduce it (as minimally and precisely as possible)?

1. Execute SQL
-- 创建一个名为 "employees" 的表
CREATE TABLE employees (
    employee_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    department_id NUMBER,
    salary NUMBER
);

-- 为 "employees" 表加入一些示例数据
INSERT INTO employees (employee_id, first_name, last_name, department_id, salary)
VALUES (1, 'John', 'Doe', 10, 50000);
INSERT INTO employees (employee_id, first_name, last_name, department_id, salary)
VALUES (2, 'Jane', 'Smith', 10, 60000);
INSERT INTO employees (employee_id, first_name, last_name, department_id, salary)
VALUES (3, 'Jim', 'Bean', 20, 55000);

-- 创建一个名为 "department_10_view" 的视图，展示 department_id 为 10 的员工
CREATE VIEW department_10_view AS
SELECT employee_id, first_name, last_name, salary
FROM employees
WHERE department_id = 10;

-- 为视图添加注释
COMMENT ON TABLE department_10_view IS 'This view displays information about employees in department 10, including their ID, first name, last name, and salary.';

**Comment by HSunboy** [comment]
Fixed In Commit [b02e6b6ad04d979bd9631bc30a97ac70a3010310](https://github.com/oceanbase/odc-client/commit/b02e6b6ad04d979bd9631bc30a97ac70a3010310)
            ------
            xiaokang
            Thu Mar 7 15:02:34 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/e9d66de5-a887-42f6-bf6d-d1751d867073)
pass
