### ISSUE TITLE
[Bug]: Users without data source management permissions will not display data source navigation

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1788]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/ce4d16e8-9a85-48a2-ad52-4494d79d0517)
![image](https://github.com/oceanbase/odc/assets/143492234/95850fa2-37e4-4ad2-8648-9f057cf1a7e1)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/f528fbfb-393e-4f17-bdc0-a5a67027c795)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a role without data source permissions
2. Create a user using this role
3. Login User

**Comment by HSunboy** [comment]
Fixed In Commit [b02e6b6ad04d979bd9631bc30a97ac70a3010310](https://github.com/oceanbase/odc-client/commit/b02e6b6ad04d979bd9631bc30a97ac70a3010310)
            ------
            xiaokang
            Thu Mar 7 15:02:34 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/fd56b9a2-e869-4500-b0eb-62b31b109448)
pass
