### ISSUE TITLE
[Bug]: login failed，Data must not be longer than 128 bytes

### ISSUE THREAD

**Issue by zxbange** [oceanbase/odc#1790]
### ODC version

4.2.3

### OB version

4.2.1 bp 3

### What happened?

![image](https://github.com/oceanbase/odc/assets/26746322/8c8acc09-6f1d-448b-832c-e3a8a042aa28)

`[2024-03-06 17:17:40.824][http-nio-8989-exec-1][,,][INFO][com.oceanbase.odc.service.common.util.WebResponseUtils][150]: ODC_REQUEST_TRACE, httpMethod=POST, fullURL=http://10.20.52.120:8989/api/v2/
iam/login?currentOrganizationId&ignoreError=true, method=JSON, clientAddress=10.18.3.252, userId=Not-Required, result={"code":"BadRequest","durationMillis":null,"error":{"code":"BadRequest","detai
ls":[{"code":"BadRequest","message":"BadRequest exception, type=IllegalBlockSizeException, message=Data must not be longer than 128 bytes","target":null}],"message":"Bad request, details: BadReque
st exception, type=IllegalBlockSizeException, message=Data must not be longer than 128 bytes"},"httpStatus":"BAD_REQUEST","message":"Bad request, details: BadRequest exception, type=IllegalBlockSi
zeException, message=Data must not be longer than 128 bytes","requestId":null,"server":null,"successful":false,"timestamp":null,"traceId":null}, userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10
_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
[2024-03-06 17:17:41.675][http-nio-8989-exec-9][,,][WARN][com.oceanbase.odc.server.web.filter.ExceptionHandlerFilter][56]: Request failed, uri: /api/v2/iam/login
java.lang.IllegalStateException: Unable to invoke Cipher due to illegal block size`

### What did you expect to happen?

login success

### How can we reproduce it (as minimally and precisely as possible)?

.

**Comment by smallsheeeep** [comment]
I can not reproduce this issue, and add log output in #1994 . This issue will be closed and reopen if repeated.
