### ISSUE TITLE
[Bug]: Failed to apply for project and library permissions

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1791]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/300bf59d-83cd-4404-9bb4-449ffb4588a8)
![image](https://github.com/oceanbase/odc/assets/143492234/a8a4f06b-8db7-4575-a5bd-fa659288aea3)

### What did you expect to happen?

Created successfully

### How can we reproduce it (as minimally and precisely as possible)?

Apply for project and library permissions

**Comment by smallsheeeep** [comment]
Duplicated with #1769 and has been fixed.
