### ISSUE TITLE
[Bug]: The recycle bin does not filter mysql and oracle types, and an error is reported when opening

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1798]
### ODC version

ODC 4.2.4

### OB version

Oracle11g

### What happened?

Recycle bin switching database list is not filtered for mysql and oracle data sources
![image](https://github.com/oceanbase/odc/assets/46598871/93c738d0-d7e5-4021-9258-854d5c466c65)

### What did you expect to happen?

mysql and oracle data sources do not support the recycle bin

### How can we reproduce it (as minimally and precisely as possible)?

Enter the recycle bin and switch databases

**Comment by HSunboy** [comment]
Fixed In Commit [88ac0482c86cf8d3b9551a38f15c3657e1b2b553](https://github.com/oceanbase/odc-client/commit/88ac0482c86cf8d3b9551a38f15c3657e1b2b553)
            ------
            xiaokang
            Mon Mar 25 13:32:29 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1ace46cb-e539-4889-87c6-3751f97ebd25)

pass
