### ISSUE TITLE
[Bug]: failed to purge a specific object in recyclebin

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#180]
### ODC version

4.2.0

### OB version

OceanBase 4.x

### What happened?

I want to purge a specific table object in recyclebin, but there is an exception thrown:
![image (1)](https://github.com/oceanbase/odc/assets/22992296/6ca1276e-caa9-4840-ae91-a4b2a1da880d)

I can do this on OceanBase 3.x without any errors.

### What did you expect to happen?

I can do this without any errors

### How can we reproduce it (as minimally and precisely as possible)?

purge a specific table object on OceanBase 4.x

**Comment by yhilmare** [comment]
this issue is caused by odc 4.2.0, the root cause of it is that OceanBase can not allow user purge an object located in A schema by. a connection that connected to B schema

**Comment by yhilmare** [comment]
<img width="1114" alt="截屏2023-10-31 16 51 41" src="https://github.com/oceanbase/odc/assets/22992296/2f6daa3a-ccf4-4b2f-a74b-b46b36452153">

as you can see, we use recyclebin in datasource management panel, the connection we use will connect to any other schema that can not be controlled by user but the object in recyclebin that you want to purge is located in a specific schema. that is why we will get an error when we attempt to purge it.

**Comment by yhilmare** [comment]
we will switch schema when we attempt to purge an object

**Comment by HSunboy** [comment]
Fixed In Commit [597ec21486460ffebed6156c85168a47b650f6fb](https://github.com/oceanbase/odc-client/commit/597ec21486460ffebed6156c85168a47b650f6fb)
            ------
            晓康
            Mon Nov 13 14:21:20 2023 +0800
