### ISSUE TITLE
[Bug]: Structural comparison: After selecting the target database and then selecting the source database again, the target database did not disappear

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1803]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/6daf8354-bd4c-406e-87f7-6ee0596fc2d6)

### What did you expect to happen?

After reselecting the source database, the target database did not disappear

### How can we reproduce it (as minimally and precisely as possible)?

1. Select source and target databases
2. Select the source database again

**Comment by HSunboy** [comment]
Fixed In Commit [f11883339450cbaecb0d2dcf8804cacd83fcfa50](https://github.com/oceanbase/odc-client/commit/f11883339450cbaecb0d2dcf8804cacd83fcfa50)
            ------
            陈朝俊
            Mon Mar 11 14:50:37 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/14afda2b-8261-491a-8217-31729ff8f567)

pass
