### ISSUE TITLE
[Bug]: 9 tasks are executed concurrently, one of which is always in the created state

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1806]
### ODC version

ODC424

### OB version

independent

### What happened?

9 tasks are executed concurrently, one of which is always in the created state
![image](https://github.com/oceanbase/odc/assets/59468957/8e0b4055-2ac5-4147-8858-e07123bd6d58)
![image](https://github.com/oceanbase/odc/assets/59468957/5a0ba84b-a777-42db-a358-51ea62f36a9d)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

chat priavtely

**Comment by krihy** [comment]
![Image](https://github.com/oceanbase/odc/assets/51393259/28802cfa-46fd-49f4-b444-832c063c8d73)

`DefaultJobTerminateListener`  heart time out job status update to `CANCELED`, dlm task should set to `CANCELD` or `FAILED`

@guowl3
