### ISSUE TITLE
[Bug]: partition plan got Unsupported partition expression if partition column name does not match column name case sensitive

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#1821]
### ODC version

4.2.3

### OB version

not related

### What happened?

partition plan got Unsupported partition expression if partition column name does not match column name case sensitive

### What did you expect to happen?

column name match should be case insensitive

### How can we reproduce it (as minimally and precisely as possible)?

create a table with range coulmns partition,
refer column name in partition expression use a lowser case name while column name definition was UPPER CASE.

**Comment by yhilmare** [comment]
this issued has been fixed in new partition plan impl
