### ISSUE TITLE
[Enhancement]: partition plan set a stable pre-creation count as default

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#1823]
### What would you like to be added?

 partition plan set a stable pre-creation count as default.

such as
- default  15 pre-creation count for daily parition
- default  7 pre-creation count for weely/montly partition
- default 3 pre-creation count for yearly partition

more, tip user why should we use a stable pre-creation strategy

### Why is this needed?

product level partition maintain

**Comment by bluesky-xyh** [comment]
fixed: https://github.com/oceanbase/odc/issues/1881#issuecomment-1994320009
