### ISSUE TITLE
[Bug]: cannot view/edit table while connect to SofaODP 1.21.6

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#1826]
### ODC version

4.2.3

### OB version

SofaODP 1.21.6

### What happened?

cannot view/edit table while connect to SofaODP 1.21.6

### What did you expect to happen?

can view/edit table while connect to SofaODP 1.21.6

### How can we reproduce it (as minimally and precisely as possible)?

connect to SofaODP 1.21.6

**Comment by yhilmare** [comment]
@tonghan-gsh QAer may not care about this issue cause that there is no sofaodp env to verify this issue and I have verified my solution on user's env~
