### ISSUE TITLE
[Bug]: DLM, task error 'unknown type -101, idx = 8'

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1833]
### ODC version

ODC424

### OB version

independent

### What happened?

DLM, task error 'unknown type -101, idx = 8'
![image](https://github.com/oceanbase/odc/assets/59468957/78304a94-3ca2-4f5b-80a7-df0be4b1fef9)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

`CREATE TABLE "DLM_SOURCE"."DONE_ASD" (
  "COL1" NUMBER(38) DEFAULT NULL,
  "COL2" NUMBER DEFAULT NULL,
  "COL3" CHAR(120) DEFAULT NULL,
  "COL4" VARCHAR2(120) DEFAULT NULL,
  "COL6" CLOB DEFAULT NULL,
  "COL7" DATE DEFAULT NULL,
  "COL8" TIMESTAMP(6) DEFAULT NULL,
  "COL9" TIMESTAMP(6) WITH TIME ZONE DEFAULT NULL,
  "COL10" TIMESTAMP(6) WITH LOCAL TIME ZONE DEFAULT NULL,
  "COL11" NVARCHAR2(120) DEFAULT NULL,
  "COL12" NCHAR(120) DEFAULT NULL,
  CONSTRAINT "PASOD" PRIMARY KEY ("COL1")
)`

**Comment by guowl3** [comment]
The field types of TIMESTAMPLTZ & TIMESTAMPTZ are not supported in the current version.
