### ISSUE TITLE
[Bug]: When the query result set is 0000-00-00 00:00:00, download the result set as 0001-01-01 00:00:00:00

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1840]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/58c6a0f2-858d-4b50-8753-41b6c37a9f6f)

### What did you expect to happen?

Download result set is 0000-00-00 00:00:00

### How can we reproduce it (as minimally and precisely as possible)?

DROP table t0;
create table t0(c0 datetime);
insert into t0 values(0);
select * from t0;
2. Download result set

**Comment by LuckyPickleZZ** [comment]
After https://github.com/oceanbase/odc/pull/2455 , user could control zeroDateBehavior himself~
