### ISSUE TITLE
[Bug]: The identification rules with high risk levels are not effective

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1841]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/764e3b39-5f23-4118-b484-b37ecb8cb06b)
![image](https://github.com/oceanbase/odc/assets/143492234/cd93ae42-6fa9-4f66-b2b9-1db1a1d2ccb4)
![image](https://github.com/oceanbase/odc/assets/143492234/d67a1aef-5d35-4583-9a3d-735775bddf42)

### What did you expect to happen?

The risk level is displayed as high

### How can we reproduce it (as minimally and precisely as possible)?

1. Set the risk identification rules as the default environment and export the result set
2. Export result set in default environment

**Comment by MarkPotato777** [comment]
Your high-risk level detection rule contains 'AND database_name = 123' while your ticket's related database name is not 123, therefore it doesn't match the high-risk level.
