### ISSUE TITLE
[Bug]: The database will not pass during SQL plan editing

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1842]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/6851d6a9-d22a-468f-9f93-cf12cb3374f3)

### What did you expect to happen?

Database passed during editing

### How can we reproduce it (as minimally and precisely as possible)?

Modify SQL plan

**Comment by HSunboy** [comment]
Fixed In Commit [139342f8bae6009995f303971e8d83bb141a6d6a](https://github.com/oceanbase/odc-client/commit/139342f8bae6009995f303971e8d83bb141a6d6a)
            ------
            咏和
            Tue Mar 12 14:07:26 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8710cfd2-c0f8-4dbe-8299-b859ed6b3485)

pass
