### ISSUE TITLE
[Bug]: SQL preview in DLMoracle mode requires functions

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1845]
### ODC version

ODC424

### OB version

independent

### What happened?

SQL preview in DLMoracle mode requires functions
![image](https://github.com/oceanbase/odc/assets/59468957/40c6b28b-49d9-4889-870b-07b501c073d0)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by guowl3** [comment]
Usage of this function requires declaration by the user. For example, I configure the following expression: CREATE_TIME < TO_DATE('${sys}','YYYY-MM-DD'), and the parsing result is as follows:
select * from AUDIT_LOG where CREATE_TIME < TO_DATE('2024-06-02','YYYY-MM-DD');
