### ISSUE TITLE
[Bug]: Description will not be passed when modifying custom environments

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1850]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/c5a796b4-bd06-4187-a010-98dd1f7b7034)

### What did you expect to happen?

Transferred description

### How can we reproduce it (as minimally and precisely as possible)?

Modify custom environment, modify description

**Comment by HSunboy** [comment]
Fixed In Commit [11a2b04ebfce90cd22f1cc385a2ef3f1464f2db8](https://github.com/oceanbase/odc-client/commit/11a2b04ebfce90cd22f1cc385a2ef3f1464f2db8)
            ------
            陈朝俊
            Tue Mar 12 14:01:43 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/36911076-29d7-48f4-a6af-c1b428727d47)

pass
