### ISSUE TITLE
[Bug]: The user does not have the permission to change the database. When right-clicking the object tree, the simulate data button should be grayed out.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1852]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/5d9cea6e-202a-4088-b89e-90611ca54f8f)
The user does not have the permission to change the database. When right-clicking the object tree, the simulate data button should be grayed out.

### What did you expect to happen?

The user does not have the permission to change the database. When right-clicking the object tree, the simulate data button should be grayed out.

### How can we reproduce it (as minimally and precisely as possible)?

The user does not have the permission to change the database. View the object tree simulation data button

**Comment by HSunboy** [comment]
Fixed In Commit [139342f8bae6009995f303971e8d83bb141a6d6a](https://github.com/oceanbase/odc-client/commit/139342f8bae6009995f303971e8d83bb141a6d6a)
            ------
            咏和
            Tue Mar 12 14:07:26 2024 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/5b8c9795-8c76-4734-bea0-97241da09faa)
pass
