### ISSUE TITLE
[Bug]: The second deletion of the custom environment is inconsistent with the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1853]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b25b0be8-105b-4ee5-9c12-793de8b42fc2)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/5b7ecb5b-d8cf-4446-9e28-9c6a118b2e1a)

### How can we reproduce it (as minimally and precisely as possible)?

Delete custom environment

**Comment by HSunboy** [comment]
Fixed In Commit [e4fbbdbad75ee9c0b4f7111c64ce4d7dc1e93cb6](https://github.com/oceanbase/odc-client/commit/e4fbbdbad75ee9c0b4f7111c64ce4d7dc1e93cb6)
            ------
            陈朝俊
            Tue Mar 12 18:32:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f8d28a51-c4f5-4376-8c6f-3486047ee6f3)

pass
