### ISSUE TITLE
[Bug]: Adding an auto-increment column does not match the offline detection

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1871]
### ODC version

ODC4.2.4

### OB version

OB4.2

### What happened?

 Adding an auto-increment column does not match the offline detection
![image](https://github.com/oceanbase/odc/assets/46598871/017a3da3-f1aa-4ab8-a70b-b708aa8120e3)

### What did you expect to happen?

Adding an auto-increment column must match the offline detection

### How can we reproduce it (as minimally and precisely as possible)?

create table test_identity(a int);
ALTER TABLE test_identity ADD (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY);

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/28b8e958-52bd-4873-ab04-34ad9eb60713)

pass
