### ISSUE TITLE
[Bug]: Mixed column operations did not match the offline check

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1872]
### ODC version

ODC 4.2.4

### OB version

OBOracle 4.2

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/58068388-b2ba-4bb5-a704-3a2557eb87fa)
Mixed column operations did not match the offline check

### What did you expect to happen?

Mixed column operations match to offline check

### How can we reproduce it (as minimally and precisely as possible)?

BEGIN;
    CREATE TABLE test_columns3 (
    id NUMBER,
    name VARCHAR2(100)
);
INSERT INTO test_columns3 (id, name) VALUES (1, 'John');
INSERT INTO test_columns3 (id, name) VALUES (2, 'Jane');
CREATE INDEX idx_new_table_id3 ON test_columns3(id);
ALTER TABLE test_columns3 ADD email VARCHAR2(100);
    COMMIT;

**Comment by yhilmare** [comment]
mixed column operation have to include offline ddls
