### ISSUE TITLE
[Bug]: The delete primary key button is grayed out and cannot be clicked.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1874]
### ODC version

ODC 4.2.4

### OB version

OBOracle 4.2

### What happened?

I can delete the primary key by executing the sql statement, but the delete button on the white screen interface is grayed out.
![image](https://github.com/oceanbase/odc/assets/46598871/5cafe4a3-bd22-456e-98ee-19fc58f26530)
![image](https://github.com/oceanbase/odc/assets/46598871/8f1b72ce-c8cd-4ad8-b9f2-583f22652593)

### What did you expect to happen?

Delete primary key button is not grayed out.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/a1b984b4-2fd1-4c77-a063-11ebd4dc90c3)
