### ISSUE TITLE
[Bug]: Deleting the primary key through alter table drop constraint is not recognized as offline

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1875]
### ODC version

ODC 4.2.4

### OB version

OBOracle 4.2

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/956173c9-76fb-495c-8f8b-0857cfce02e8)
Deleting the primary key through alter table drop constraint is not recognized as offline

### What did you expect to happen?

Delete the primary key identified as offline through alter table drop CONSTRAINT

### How can we reproduce it (as minimally and precisely as possible)?

create table test_identity(a int);
ALTER TABLE test_identity ADD CONSTRAINT constraint_name PRIMARY KEY (a);
ALTER TABLE test_identity DROP CONSTRAINT constraint_name;

**Comment by yhilmare** [comment]
fixed:
<img width="1062" alt="截屏2024-03-13 15 12 21" src="https://github.com/oceanbase/odc/assets/22992296/e214867f-93bd-469f-8d33-2f3fed9066bf">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1e7d63de-7da8-487d-b5a7-2e85a4469327)

pass
