### ISSUE TITLE
[Bug]: Apply for project permissions, click OK, and it will report 'The approval instance is not on this machine'

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1878]
### ODC version

ODC424

### OB version

independent

### What happened?

Apply for project permissions, click OK, and it will report 'The approval instance is not on this machine'
![image](https://github.com/oceanbase/odc/assets/59468957/a43e3781-2707-44ee-b405-a6ad581c64ac)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by smallsheeeep** [comment]
The root cause is the charset of mete DB is gbk and the emoji is not supported. So if insert a field with emoji into SQL will throw an exception.

**Comment by smallsheeeep** [comment]
The character set of the meta database has been described in the ODC user documentation: https://www.oceanbase.com/docs/common-odc-1000000000468256
