### ISSUE TITLE
[Bug]: `ZHSGB2312` is not supported in mock data task 

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#188]
### ODC version

4.2.0

### OB version

not related

### What happened?

failed to start a mock data task on a table that encoded by `ZHSGB2312`.

### What did you expect to happen?

start a mock data task succeed.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'What happened'

**Comment by Huangxiao-mas** [comment]
PASS
