### ISSUE TITLE
[Bug]: When the data archiving task is initiated again, the SQL window preview is empty and the front-end does not call the interface.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1881]
### ODC version

ODC424

### OB version

independent

### What happened?

When the data archiving task is initiated again, the SQL window preview is empty and the front-end does not call the interface.
![image](https://github.com/oceanbase/odc/assets/59468957/dab936ba-0d0a-4047-b14c-8d645627c21f)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/59468957/5dbfc96f-bbef-4c94-9327-01cd4fb61027)

**Comment by HSunboy** [comment]
Fixed In Commit [fe95c91eee54adb9c70db2877073d2e793f6b4de](https://github.com/oceanbase/odc-client/commit/fe95c91eee54adb9c70db2877073d2e793f6b4de)
            ------
            咏和
            Wed Mar 13 20:11:17 2024 +0800
