### ISSUE TITLE
[Bug]: Apply for project permissions and launch the unrequested interface again

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1882]
### ODC version

ODC424

### OB version

independent

### What happened?

Apply for project permissions and launch the unrequested interface again
![image](https://github.com/oceanbase/odc/assets/59468957/2c00b722-679a-4237-bc0a-f237823b73f1)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [fe95c91eee54adb9c70db2877073d2e793f6b4de](https://github.com/oceanbase/odc-client/commit/fe95c91eee54adb9c70db2877073d2e793f6b4de)
            ------
            咏和
            Wed Mar 13 20:11:17 2024 +0800
