### ISSUE TITLE
[Bug]: The LDAP login name needs to be the same as the name filled in by the user

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1884]
### ODC version

ODC424

### OB version

independent

### What happened?

The LDAP login name needs to be the same as the name filled in by the user
![image](https://github.com/oceanbase/odc/assets/59468957/51a6e319-499d-46c4-9eb6-eb9afbcd35bf)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [f5c517ac5a98d30fa0633505c565f109838fc889](https://github.com/oceanbase/odc-client/commit/f5c517ac5a98d30fa0633505c565f109838fc889)
            ------
            陈朝俊
            Wed Mar 13 20:11:37 2024 +0800
