### ISSUE TITLE
[Bug]: SQL plan to view task details ‘could not extract ResultSet’

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1885]
### ODC version

ODC424

### OB version

independent

### What happened?

SQL plan to view task details ‘could not extract ResultSet’
![image](https://github.com/oceanbase/odc/assets/59468957/2076c44b-8fb9-451a-9101-0c00d9aec745)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by Huangxiao-mas** [comment]
性能问题

**Comment by krihy** [comment]
this bug has fixed by @guowl3
