### ISSUE TITLE
[Bug]: failed to mock data on `bit` data type with length less than 8

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#189]
### ODC version

4.2.0

### OB version

not related

### What happened?

failed to mock data on `bit` data type with length less than 8, as follow:
```SQL
create table bit_t (
id varchar(64),
bit_c bit
);
```

### What did you expect to happen?

start mock data task succeed

### How can we reproduce it (as minimally and precisely as possible)?

follow 'What happened'

**Comment by yhilmare** [comment]
I use char data generator to mock data for bit type~

**Comment by Huangxiao-mas** [comment]
PASS
