### ISSUE TITLE
[Bug]: Mixed columns executed in mysql mode are not recognized as offline

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1891]
### ODC version

ODC 4.2.4

### OB version

OBMySQL4.2

### What happened?

Mixed columns executed in mysql mode are not recognized as offline
![image](https://github.com/oceanbase/odc/assets/46598871/cef86072-7909-423b-a01e-2d32c5959fdb)

### What did you expect to happen?

Identified as offline

### How can we reproduce it (as minimally and precisely as possible)?

ALTER TABLE test ADD email varchar(100),drop column a;

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/7d7221be-b885-49a4-a1d8-4b85dd87c861)

pass
