### ISSUE TITLE
[Bug]: No space after the comment symbol is recognized as a syntax error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1892]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

No space after the comment symbol is recognized as a syntax error
![image](https://github.com/oceanbase/odc/assets/46598871/f08872c9-f151-4bb4-8d0c-917f939593aa)

### What did you expect to happen?

execution succeed

### How can we reproduce it (as minimally and precisely as possible)?

--混合列操作
ALTER TABLE test ADD email varchar(100),drop column a;

**Comment by HSunboy** [comment]
mysql parser bug

**Comment by tonghan-gsh** [comment]
This is a front-end parsing problem. If there is no space after --, it should not be recognized as a comment.
![image](https://github.com/oceanbase/odc/assets/46598871/a97c5510-d575-4a95-a05d-3d0652204856)

**Comment by HSunboy** [comment]
fixed in dev-4.3.1



![Image](https://github.com/oceanbase/odc/assets/14886044/d792c5d1-edf0-4cd9-b870-65a71036e532)

**Comment by Huangxiao-mas** [comment]
pass
