### ISSUE TITLE
[Bug]: Modify the column as the primary key and match two offline lines.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1893]
### ODC version

ODC 4.2.4

### OB version

OBMySQL

### What happened?

Modify the column as the primary key and match two offline lines.
![image](https://github.com/oceanbase/odc/assets/46598871/2b2f50a5-09f4-4b5e-9854-3dbb8faddefb)

### What did you expect to happen?

Matches only one

### How can we reproduce it (as minimally and precisely as possible)?

ALTER TABLE test
MODIFY COLUMN a INT PRIMARY KEY;

**Comment by yhilmare** [comment]
if table `test`'s ddl is as follow:
<img width="1020" alt="截屏2024-03-14 10 26 42" src="https://github.com/oceanbase/odc/assets/22992296/b1280f9d-7213-4da8-8915-86994cb156cd">

the behavior is expected cause that the alter statement hit two offline rule:
1. modify column's data type, from `varchar` to `int`.
2. modify column a as primary key.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/27b48f1e-0b7d-427f-9a5e-44fe2790b68e)

pass
