### ISSUE TITLE
[Bug]: After the creation of the data source is completed, the front-end page has been in a "spinning" state.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1899]
### ODC version

ODC424

### OB version

independent

### What happened?

After the creation of the data source is completed, the front-end page has been in a "spinning" state.
![image](https://github.com/oceanbase/odc/assets/59468957/e6a25dee-523d-4860-ab82-c6e45cb5336b)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [ed33e1a54eca20333667323c7e14d3a04fa55a69](https://github.com/oceanbase/odc-client/commit/ed33e1a54eca20333667323c7e14d3a04fa55a69)
            ------
            xiaokang
            Mon Mar 25 15:26:15 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f0f05d07-b041-4501-9b94-33b645ada1cb)

pass
