### ISSUE TITLE
[Bug]: NPE occurs when batch import user

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#1900]
### ODC version

4.2.4

### OB version

-

### What happened?

When batch import user from xlsx file and set roles, there will be an NPE . 
![image](https://github.com/oceanbase/odc/assets/36879124/10c8d804-2d01-43df-8016-063d729db454)

![image](https://github.com/oceanbase/odc/assets/36879124/cd47ada0-b560-4a8f-8dbf-59fa935aaccc)

### What did you expect to happen?

import should succeed

### How can we reproduce it (as minimally and precisely as possible)?

.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6db4cada-bcb3-4feb-989e-23271f44c4e6)



![Image](https://github.com/oceanbase/odc/assets/143492234/a27a36d5-2df9-44de-ab85-067b692af5a4)

pass
