### ISSUE TITLE
[Bug]: The user guide document is different with actual ODC UI

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1905]
### ODC version

4.2.3

### OB version

-

### What happened?

The user document is:
![image](https://github.com/oceanbase/odc/assets/84772536/464bedc3-858e-46b3-993e-57db0e4340d9)
 But actual is:
<img width="716" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/6dfc804d-3c02-48e2-a827-b7f37bc7d8f0">

### What did you expect to happen?

Revision of documentation errors.

### How can we reproduce it (as minimally and precisely as possible)?

-

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/3dae63b3-cf69-4b85-a721-9c131fdcbc94)

pass
