### ISSUE TITLE
[Bug]: NPE during SQL rule checking

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#1906]
### ODC version

4.2.3

### OB version

any

### What happened?

I create a database change task and input SQL:
```sql
create table t_123 as select * from t_456;
```

Then SQL check failed:
![image](https://github.com/oceanbase/odc/assets/84772536/647a84af-6639-4279-9d1f-129203cfd293)

Debug:
<img width="1029" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/6aa84f2c-dc21-4811-bfd6-eb9652b85127">

### What did you expect to happen?

-

### How can we reproduce it (as minimally and precisely as possible)?

-

**Comment by yhilmare** [comment]
okay, all npes have been fixed

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/71d8b128-16e3-4475-9fb8-88a390f59b00)

pass
