### ISSUE TITLE
[Bug]: Check the ddl of view has an empty line.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1907]
### ODC version

ODC 4.2.4

### OB version

Oracle 11g

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/ddf5612a-788c-4d01-bb94-fe10247a8dbb)
Check that the ddl of view has an empty line.

### What did you expect to happen?

Remove blank lines

### How can we reproduce it (as minimally and precisely as possible)?

view ddl of view

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/d1505fb7-61fd-47ee-a3a9-5ba8c73c7568)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/a658daf6-ec42-4365-b405-e2996fb3be29)

pass
