### ISSUE TITLE
[Bug]: failed to use skip strategy while mocking data

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#191]
### ODC version

4.2.0

### OB version

not related

### What happened?

here is my table ddl:
```SQL
CREATE TABLE `t3` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) DEFAULT NULL,
  `gmt_create` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
)
```
and my mock data config:
![image](https://github.com/oceanbase/odc/assets/22992296/d1eb2605-4366-48ef-89b6-9cba63b03cc2)
mock data task failed with such logs:
```shell
2023-04-21 10:16:18 WARN c.o.o.s.f.t.MockDataRuntimeFlowableTask - Mock data task failed, taskId=52031476
com.oceanbase.tools.datamocker.model.exception.MockerException: Data type for column "t3.id" can not be null
    at com.oceanbase.tools.datamocker.core.task.AbstractMockerFactory.create(AbstractMockerFactory.java:130) ~[ob-mocker-0.1.3-SNAPSHOT.jar!/:?]
```

### What did you expect to happen?

mock data succeed.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'What happened'

**Comment by yhilmare** [comment]
fix:
<img width="733" alt="截屏2023-12-07 21 31 23" src="https://github.com/oceanbase/odc/assets/22992296/28f61397-f061-4985-bb2f-04058d80112b">

**Comment by Huangxiao-mas** [comment]
pass
