### ISSUE TITLE
[Bug]: Native Oracle anonymous blocks cannot be executed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1929]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/69596cb1-3bff-43ea-a0aa-4dd01d57a671)

### What did you expect to happen?

There are execution and stop buttons present

### How can we reproduce it (as minimally and precisely as possible)?

Open anonymous block

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/56b337d3-8265-49ac-b3f2-f82ce2194256)

No termination button

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/3fe20b36-cc4a-43f1-8590-eca9e1e95f7e)

**Comment by PeachThinking** [comment]
works for me:

![Image](https://github.com/oceanbase/odc/assets/140503120/447c2469-cf2c-4c20-913a-795d619e21a2)

**Comment by sl01388797** [comment]
pass
