### ISSUE TITLE
[Bug]: the progress of load/dump task is confused

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#193]
### ODC version

4.2.0

### OB version

not related

### What happened?

the progress of data transfer task will first reach 100%, then drop to 0%, and finally reach 100% again.

### What did you expect to happen?

Task progress will not repeatedly appear from 0% to 100%.

### How can we reproduce it (as minimally and precisely as possible)?

start a data transfer task with loading schema and loading data or exporting schema and exporting data.

**Comment by yhilmare** [comment]
odc will start up two sub-tasks when you load/dump both schema and data. the progress shows each sub-task's progress rather than the whole task's progress, so that the whole task's progress will be zero when the first sub-task finished.

**Comment by LuckyPickleZZ** [comment]
This has already been fixed in #680 .
