### ISSUE TITLE
[Bug]: Unable to execute SQL generated in Oracle mode

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1936]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/08e2e700-1748-41ab-a625-40fb813e7af4)

### What did you expect to happen?

Execution succeeded

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL statements automatically generated by creating tables

**Comment by PeachThinking** [comment]
According to the description of PRD, the editing operation backend of all database objects has not been adapted.
