### ISSUE TITLE
[Bug]: Error when exporting result set in native oracle mode

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1943]
### ODC version

ODC 4.2.4

### OB version

Oracle

### What happened?
![image](https://github.com/oceanbase/odc/assets/46598871/4594b929-7cd8-4128-969f-cba40d125ce6)
Error when exporting result set in native oracle mode

### What did you expect to happen?

Export result set without error

### How can we reproduce it (as minimally and precisely as possible)?

Export result set using native oracle

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b4ab989d-be9b-4772-8f3d-385044338521)

pass
