### ISSUE TITLE
[Bug]: REVOKE ALL PRIVILEGES FROM Statement cannot be executed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1944]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/988eb627-a26d-41cd-923a-3fefed9404d7)
![image](https://github.com/oceanbase/odc/assets/143492234/29eedb44-b8a3-4475-990a-68f18dba9e7b)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/3b2181c2-9e17-4b6a-9c3f-69c18bde540f)

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a user  CREATE USER 'user1'@'%' IDENTIFIED BY '123456';
2. Granting user permissions   GRANT ALL PRIVILEGES ON shilin.* TO 'user1'@'%';
3. Revoke all user permissions  REVOKE ALL PRIVILEGES FROM user1;

**Comment by PeachThinking** [comment]
It has nothing to do with ODC, it's a kernel problem
