### ISSUE TITLE
[Bug]: Structure comparison will only display the first task when opening details

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#1946]
### ODC version

odc424

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/399bc4aa-c732-4b1b-8af1-55c384b47c08

https://github.com/oceanbase/odc/assets/143492234/fcf9944d-ecd4-4268-ab7f-2a9c84b30e56

### What did you expect to happen?

Normal display task

### How can we reproduce it (as minimally and precisely as possible)?

View details of structural comparison task

**Comment by HSunboy** [comment]
Fixed In Commit [017dccc99e78bc533f08e6786864e4dad6088ad4](https://github.com/oceanbase/odc-client/commit/017dccc99e78bc533f08e6786864e4dad6088ad4)
            ------
            陈朝俊
            Mon Mar 25 17:22:08 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/2b347af7-a28a-41ea-b50c-52f2c5250797)

pass
