### ISSUE TITLE
[Bug]: The native oracle mode should remove the compilation entry of the package

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1949]
### ODC version

ODC4.2.4

### OB version

Oracle 11g

### What happened?

Native oracle mode shows the compilation entry of the package
![image](https://github.com/oceanbase/odc/assets/46598871/73d24318-a6a9-4994-a503-1e281b208dca)

### What did you expect to happen?

The native oracle mode should remove the compilation entry of the package

### How can we reproduce it (as minimally and precisely as possible)?

View the package of native oracle mode

**Comment by HSunboy** [comment]
Fixed In Commit [ed33e1a54eca20333667323c7e14d3a04fa55a69](https://github.com/oceanbase/odc-client/commit/ed33e1a54eca20333667323c7e14d3a04fa55a69)
            ------
            xiaokang
            Mon Mar 25 15:26:15 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/dfdbc5d0-0d86-48b9-be4c-6b40f8899f92)

pass
