### ISSUE TITLE
[Bug]: Native oracle mode trigger hides compile and disable buttons

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1950]
### ODC version

ODC4.2.4

### OB version

Oracle11g

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/0f09d84e-78ce-48ff-b9ba-5aae9eaf072f)
![image](https://github.com/oceanbase/odc/assets/46598871/2cd088ea-d0d0-4f8e-ba34-395f9a31bdab)

### What did you expect to happen?

Native oracle mode trigger hides compile and disable buttons

### How can we reproduce it (as minimally and precisely as possible)?

View native oracle mode triggers

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/373b7d4d-6f84-4c77-afc1-c8c7068e73e5)



![Image](https://github.com/oceanbase/odc/assets/143492234/3ce836d0-5e35-4b02-87c2-ba61d217e281)

pass
