### ISSUE TITLE
[Bug]: Trigger's ddl is not aligned

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1954]
### ODC version

ODC4.2.4

### OB version

Oracle 11g

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/62feca8d-d8dc-4cae-a943-cb3d2491658d)
Trigger's ddl is not aligned

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/1fa254b0-410e-413f-9559-71e07cefb1d0)

### How can we reproduce it (as minimally and precisely as possible)?

View the ddl of the trigger.

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/01696bfb-ea70-44b7-b5d0-92f26a92f415)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/57b8b5e5-3934-472b-86eb-525135a1d7fd)

pass
