### ISSUE TITLE
[Bug]: Type of varray type has no display type

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1955]
### ODC version

ODC4.2.4

### OB version

Oracle11g

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/70992190-8a53-44af-9f07-890f7fd7eb76)
![image](https://github.com/oceanbase/odc/assets/46598871/ce9b4332-02ab-4091-826d-f0c6f5b68fe5)
The type returned by the oracle mode backend is collection, which is not displayed on the front end. The type returned by the oboracle mode backend is varray

### What did you expect to happen?

Front-end display array type

### How can we reproduce it (as minimally and precisely as possible)?

CREATE OR REPLACE TYPE "GSH"."TYPE_VARRAY"  IS VARRAY(10) OF number(38)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3518d12b-5179-4037-b602-cfe1bf0f6f9a)

pass
