### ISSUE TITLE
[Bug]: could not spawn a new process during runtime

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#1958]
### ODC version

4.2.4

### OB version

-

### What happened?

Now ODC could not start any data transfer job for `Oracle` and `MySQL` datasource on Mac.

After debug I found during runtime,  neither 'Runtime#exec' nor 'ProcessBuilder#start' can execute ANY commands.

According to https://stackoverflow.com/a/31015371 , this is because the bundled jre missing executable permission for `lib/jspawnhelper`. And after I execute `chmod +x jspawnhelper`, the program works normally!

### What did you expect to happen?

The relative path of this file on mac is `Contents/Resources/libraries/jre/Home/lib/jspawnhelper`. We should grant executable permission to it.

### How can we reproduce it (as minimally and precisely as possible)?

Start a data transfer job for mysql datasource

**Comment by HSunboy** [comment]
Fixed In Commit [9472776a079ead5467f204611effe42e93ba413a](https://github.com/oceanbase/odc-client/commit/9472776a079ead5467f204611effe42e93ba413a)
            ------
            xiaokang
            Tue Mar 19 14:22:13 2024 +0800
