### ISSUE TITLE
[Bug]: The commit mode setting in personal settings is not taking effect for the Oracle database.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#1962]
### ODC version

4.2.4

### OB version

NULL

### What happened?

When I set the commit mode to manual for the Oracle database, the transaction commits are still occurring automatically.
![image](https://github.com/oceanbase/odc/assets/15030999/d724b5d6-113b-489b-a52c-f68c792d658a)

### What did you expect to happen?

When I configure the Oracle mode to manual commit, the transactions are committed manually.

### How can we reproduce it (as minimally and precisely as possible)?

open an oracle database，then djusting commit mode

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/0a1c789b-c886-4b7d-9efe-bbe3ff587451)

pass
