### ISSUE TITLE
[Bug]: For users without  permissions, disable the entry point for creating new environments.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#1964]
### ODC version

4.2.4

### OB version

ALL

### What happened?

If the user does not have permission to create a new environment, the corresponding entry should be disabled.

### What did you expect to happen?

If the user does not have permission to create a new environment, the corresponding entry should be disabled.
![image](https://github.com/oceanbase/odc/assets/15030999/d182cb6c-08dc-4bd7-b01e-1627319c1501)

### How can we reproduce it (as minimally and precisely as possible)?

1、Create a new regular user,
2、Use this user to log in to ODC, and navigate to the security specifications module 
3、try to add a new environment.

**Comment by HSunboy** [comment]
Fixed In Commit [e4ed50effe5fdd1e77f54814de94e09fd05c3ea0](https://github.com/oceanbase/odc-client/commit/e4ed50effe5fdd1e77f54814de94e09fd05c3ea0)
            ------
            陈朝俊
            Fri Mar 22 09:46:14 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/61cdbfbc-ae74-41fd-b2df-1a8c3a882fd5)

pass
