### ISSUE TITLE
[Bug]: The execution time of alter type is displayed as 0

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1965]
### ODC version

ODC 4.2.4

### OB version

Oracle 11g

### What happened?

The execution time of alter type sql cannot be obtained, but it is displayed as 0 in the ODC sql console
![image](https://github.com/oceanbase/odc/assets/46598871/56bd1b19-dff0-4670-8ce0-0413d6619274)
![image](https://github.com/oceanbase/odc/assets/46598871/1a192bbe-364a-44fc-b751-8fc4d14c5c45)

### What did you expect to happen?

f the execution time cannot be queried, it will be displayed as '-'.

### How can we reproduce it (as minimally and precisely as possible)?

Execute the following sql statement and check the execution time
alter table test add y int;

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/d87a8a8a-08f3-4ebc-822f-76d769e32c64)

pass
