### ISSUE TITLE
[Bug]: The object view is missing a locator key.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#1966]
### ODC version

4.2.4

### OB version

All

### What happened?

When viewing information about tables, views, and other such objects, the ability to locate their position within the resource tree of the target database is not available.
 
![image](https://github.com/oceanbase/odc/assets/15030999/5c3d15ac-2273-43f4-a0c7-653b811ea8e8)

### What did you expect to happen?

Supplemental locator keys

### How can we reproduce it (as minimally and precisely as possible)?

open a table or other objects.

**Comment by HSunboy** [comment]
not bug
