### ISSUE TITLE
[Bug]: Database list display exception

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#1967]
### ODC version

4.2.4

### OB version

ALL

### What happened?

 As a participant entering a project, I noticed that there is a lack of textual prompt indicating the absence of a nonexistent database.

![image](https://github.com/oceanbase/odc/assets/15030999/cb8760ae-38a9-4f0d-998f-46491a538b7c)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/15030999/cf54c5a1-8a09-451e-b30c-272425df90d6)

### How can we reproduce it (as minimally and precisely as possible)?

As described above.

**Comment by UnknownAdventurer** [comment]
Fixed

**Comment by UnknownAdventurer** [comment]
Fixed in commit [0c76182e8c9a37b24ea973a7000aef1553a31e85](https://github.com/oceanbase/odc-client/commit/0c76182e8c9a37b24ea973a7000aef1553a31e85)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/251aee67-e871-47cd-8aea-46adbe0a99af)

pass
