### ISSUE TITLE
[Bug]: Data cleaning view details do not display the data source name corresponding to the database

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1971]
### ODC version

ODC424

### OB version

independent

### What happened?

Data cleaning view details do not display the data source name corresponding to the database
![image](https://github.com/oceanbase/odc/assets/59468957/80198c0f-45e5-405a-9d98-c614df7ca523)

### What did you expect to happen?

llike this
![image](https://github.com/oceanbase/odc/assets/59468957/f9f20331-0877-434e-90d1-df390cba2700)

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by bluesky-xyh** [comment]
<img width="374" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/d3090564-c38a-4dc7-a527-ef29758d4fa5">
