### ISSUE TITLE
[Bug]: The export task field type is BigDecimal, Rounding necessary

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#1978]
### ODC version

ODC424

### OB version

Oceanbase422 oracle

### What happened?

The export task field type is BigDecimal, Rounding necessary
![image](https://github.com/oceanbase/odc/assets/59468957/e4eb2b5a-0a26-46f6-bf08-98da197191e4)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

`CREATE TABLE `onothing_86` (
  `col1` int(11) NOT NULL AUTO_INCREMENT,
  `col2` decimal(10,2) DEFAULT NULL,
  `col3` decimal(10,2) DEFAULT NULL,
  `col5` tinyint(4) DEFAULT NULL,
  `col6` smallint(6) DEFAULT NULL,
  `col7` mediumint(9) DEFAULT NULL,
  `col8` bigint(20) DEFAULT NULL,
  `col9` float(10,2) DEFAULT NULL,
  `col10` double(10,2) DEFAULT NULL,
  `col11` varchar(10) DEFAULT NULL,
  `col12` char(10) DEFAULT NULL,
  `col13` text DEFAULT NULL,
  `col14` tinytext DEFAULT NULL,
  `col15` mediumtext DEFAULT NULL,
  `col16` longtext DEFAULT NULL,
  `col17` blob DEFAULT NULL,
  `col18` tinyblob DEFAULT NULL,
  `clo19` longblob DEFAULT NULL,
  `col20` mediumblob DEFAULT NULL,
  `col21` binary(16) DEFAULT NULL,
  `col22` varbinary(16) DEFAULT NULL,
  `col23` timestamp NULL DEFAULT NULL,
  `col24` time DEFAULT NULL,
  `col25` date DEFAULT NULL,
  `col26` datetime DEFAULT NULL,
  `col27` year(4) DEFAULT NULL,
  PRIMARY KEY (`col1`)
) `
mock data

**Comment by Huangxiao-mas** [comment]
Known issues with the jdbc driver, which need to be reproduced by upgrading the jdbc driver

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/a5fc80dd-e582-4af7-9558-4cc799e18330)
pass
