### ISSUE TITLE
[Bug]: failed to get flow task result

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#1979]
### ODC version

4.2.4

### OB version

all

### What happened?

the response of interface :/api/v2/flow/flowInstances/39/tasks/result?currentOrganizationId=1 is null
<img width="675" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/55b24d76-1e86-485d-8690-a5d58dac8089">

### What did you expect to happen?

return taskResult success

### How can we reproduce it (as minimally and precisely as possible)?

1. create a new mock data or database change or structure compare task
2. Click to view task details

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ce5d0052-2855-4c68-8f9c-51338a9ce9da)

pass
