### ISSUE TITLE
[Bug]: The first partition created by the partition plan should be larger than the existing partition or the partition start time

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#1986]
### ODC version

ODC 4.2.4

### OB version

Oracle430

### What happened?

The existing partitions are 20240401 and 20240701. The planned starting time for creating the partition is the current time and the time interval is 1 month. The created partitions are 20240501 and 20240601.
![image](https://github.com/oceanbase/odc/assets/46598871/2452fdc0-e619-44f8-974a-b07003163562)
![image](https://github.com/oceanbase/odc/assets/46598871/69074700-cc5a-4668-957d-22338577490a)
![image](https://github.com/oceanbase/odc/assets/46598871/35d3bff9-cceb-4d0d-bab0-dceffc0940a7)

### What did you expect to happen?

The created partition should be larger than the existing partition or the starting time. The first partition should be 20240801

### How can we reproduce it (as minimally and precisely as possible)?

CREATE TABLE oracle_range_date (
    id NUMBER,
    date_column DATE
)
PARTITION BY RANGE (date_column)
(
    PARTITION p1 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')),
    PARTITION p2 VALUES LESS THAN (TO_DATE('2022-04-01', 'YYYY-MM-DD')),
    PARTITION p3 VALUES LESS THAN (TO_DATE('2022-07-01', 'YYYY-MM-DD')),
    PARTITION p4 VALUES LESS THAN (TO_DATE('2022-10-01', 'YYYY-MM-DD')),
    PARTITION p5 VALUES LESS THAN (TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    PARTITION p6 VALUES LESS THAN (TO_DATE('2024-07-01', 'YYYY-MM-DD'))
);

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4f998284-a20a-4555-87e4-29a337fd74b3)

pass
