### ISSUE TITLE
[Bug]: Bad performance when batch generate UPDATE modifying SQL

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#2005]
### ODC version

4.2.4

### OB version

~

### What happened?

I preview table data, and update 1 column for about 100 rows, then generate modifying SQL cost about 16 seconds.

### What did you expect to happen?

Complete above operation in 5 seconds.

### How can we reproduce it (as minimally and precisely as possible)?

Modify query result set, update 100+ rows.

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/c82b8bdf-4e15-456d-afc0-59ce6832147d)
pass
