### ISSUE TITLE
[Bug]: Partition plan generates incorrect partition names

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2009]
### ODC version

ODC4.2.4

### OB version

OBOracle 430

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/d20d1e09-6216-4781-9c7a-4433800f7d09)
The partition name is 20240901

### What did you expect to happen?

I think the partition name should be 20240801

### How can we reproduce it (as minimally and precisely as possible)?
```sql
CREATE TABLE oracle_range_date (
    id NUMBER,
    date_column DATE
)
PARTITION BY RANGE (date_column)
(
    PARTITION p1 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')),
    PARTITION p2 VALUES LESS THAN (TO_DATE('2022-04-01', 'YYYY-MM-DD')),
    PARTITION p3 VALUES LESS THAN (TO_DATE('2022-07-01', 'YYYY-MM-DD')),
    PARTITION p4 VALUES LESS THAN (TO_DATE('2022-10-01', 'YYYY-MM-DD')),
    PARTITION p5 VALUES LESS THAN (TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    PARTITION p6 VALUES LESS THAN (TO_DATE('2024-07-01', 'YYYY-MM-DD'))
);
```
![image](https://github.com/oceanbase/odc/assets/46598871/a386c565-d12c-4c7f-aff0-fd3453647a39)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/40dd5d56-12e2-42c2-8e7b-d5ac5dfa43dd)

There are still issues

**Comment by sl01388797** [comment]
Meet expectations

**Comment by yhilmare** [comment]
the partition name is ref this partition key's (DATE_COLUMN) upper bound and here is the ddl of this table:
```sql
CREATE TABLE oracle_range_date (
    id NUMBER,
    date_column DATE
)
PARTITION BY RANGE (date_column)
(
    PARTITION p1 VALUES LESS THAN (TO_DATE('2022-01-01', 'YYYY-MM-DD')),
    PARTITION p2 VALUES LESS THAN (TO_DATE('2022-04-01', 'YYYY-MM-DD')),
    PARTITION p3 VALUES LESS THAN (TO_DATE('2022-07-01', 'YYYY-MM-DD')),
    PARTITION p4 VALUES LESS THAN (TO_DATE('2022-10-01', 'YYYY-MM-DD')),
    PARTITION p5 VALUES LESS THAN (TO_DATE('2024-04-01', 'YYYY-MM-DD')),
    PARTITION p6 VALUES LESS THAN (TO_DATE('2024-07-01', 'YYYY-MM-DD'))
);
```
as you can see, the last partition's upper bound is `TO_DATE('2024-07-01', 'YYYY-MM-DD')` and the partition name is as expected~
