### ISSUE TITLE
[Bug]: There is a blank in the operation record filtering

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2012]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/9cc646b9-2f86-46df-8ce4-7c6c0c23d902)

### What did you expect to happen?

Not blank

### How can we reproduce it (as minimally and precisely as possible)?

Filter within the operation record

**Comment by UnknownAdventurer** [comment]
Fixed in commit [48569648836828da2640457077130c34c5867513](https://github.com/oceanbase/odc-client/commit/48569648836828da2640457077130c34c5867513)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1ba8307a-fcac-4539-b597-5e2efd726469)

Filter name does not match actual name

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/569acac3-fbb1-4f7e-85da-ec79be44bcb5)

pass
