### ISSUE TITLE
[Bug]: Failed to enter command line

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2018]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/807d49b6-f506-416a-a688-12fe5c31c38e)

### What did you expect to happen?

Successfully entered the command line

### How can we reproduce it (as minimally and precisely as possible)?

Click on the command line within the data source

**Comment by LuckyPickleZZ** [comment]
This is because using old version of obclient. After updating, it works correctly.

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/e115616d-7350-448d-af3a-a4b648a6cda3)
pass
