### ISSUE TITLE
[Bug]: desktop version start up failed after set odc parameters in user settings

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#2019]
### ODC version

4.2.4

### OB version

not related

### What happened?
after set odc parameters in user settings

next start up will failed.

root cuase was below command argument transfer to odc-server

--spring.config.import=\"optional:file:/Users/yizhou.xw/Library/Application Support/odc/odc.temp.properties\"",

### How can we reproduce it (as minimally and precisely as possible)?
set odc paramters in user settings

![image](https://github.com/oceanbase/odc/assets/54161870/6ad83dc5-6f21-448a-9cf4-d3134af82f2f)

then exit odc, reopen to start.

**Comment by HSunboy** [comment]
Fixed In Commit [0268b543e5dc64c3a93895df9f0d7e6df7155c07](https://github.com/oceanbase/odc-client/commit/0268b543e5dc64c3a93895df9f0d7e6df7155c07)
            ------
            xiaokang
            Fri Mar 22 17:25:54 2024 +0800

**Comment by Huangxiao-mas** [comment]
test pass
