### ISSUE TITLE
[Bug]: The field order of the constraint may be different from that of the ddl

### ISSUE THREAD

**Issue by ungreat** [oceanbase/odc#2023]
### ODC version

*

### OB version

*

### What happened?

The field order of the constraint may be different from that of the ddl

### What did you expect to happen?

The field order of the constraint is same to the ddl

### How can we reproduce it (as minimally and precisely as possible)?

Create a multi-field constraint

**Comment by PeachThinking** [comment]
fixed :https://github.com/oceanbase/odc/pull/1948

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/edabad6a-d89a-4593-8f92-6b225a21a313)
![image](https://github.com/oceanbase/odc/assets/143492234/37145cde-360b-4fc3-9965-8e944395ed04)
pass
