### ISSUE TITLE
[Bug]: Tables with virtual columns do not match sqlcheck detection

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2028]
### ODC version

ODC 4.2.4

### OB version

OBOracle430

### What happened?

I created a partitioned table with virtual columns, but no sqlcheck detection was found.
![image](https://github.com/oceanbase/odc/assets/46598871/bb18b762-b49d-4403-80bb-7c1be8d3be25)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/9cffd21e-5da4-4010-9453-a23d5e13abfc)

### How can we reproduce it (as minimally and precisely as possible)?

```sql
CREATE TABLE ORACLE_RANGE_VARCHAR_2(
    id INT,
    char_column VARCHAR(64),
    char_column_number GENERATED ALWAYS AS (TO_NUMBER(char_column)) VIRTUAL
) PARTITION BY RANGE (char_column_number) (
    PARTITION p20240101 VALUES LESS THAN (20240101),
    PARTITION p20240201 VALUES LESS THAN (20240201),
    PARTITION p20240301 VALUES LESS THAN (20240301),
    PARTITION p20240401 VALUES LESS THAN (20240401)
);
```

**Comment by yhilmare** [comment]
<img width="724" alt="截屏2024-03-25 11 25 25" src="https://github.com/oceanbase/odc/assets/22992296/1ed0fabf-cade-45cd-98f9-28fc0e7c005e">

fixed

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/7496b69e-df33-44c8-a3b4-6ba22bb1f536)

pass
