### ISSUE TITLE
[Bug]: Unable to detect violations during SQL check within Doris

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2029]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/68491361-b6d6-4ca0-b8db-9ea2c6917846)
![image](https://github.com/oceanbase/odc/assets/143492234/a30a7e3c-04b7-4a88-b0e2-8b9774b17f57)
![image](https://github.com/oceanbase/odc/assets/143492234/d5fe1032-8cf6-458c-a411-fe7266ad0df5)

### What did you expect to happen?

SQL check prompt failed

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by MarkPotato777** [comment]
Duplicated with https://github.com/orgs/oceanbase/projects/7/views/1?sliceBy%5Bvalue%5D=MarkPotato777&pane=issue&itemId=56178120
