### ISSUE TITLE
[Bug]: Doris did not have default character encoding and sorting rules when creating the database

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2032]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/185cc544-d301-4888-89a1-933129c183bd)

### What did you expect to happen?

There are default character encoding and sorting rules

### How can we reproduce it (as minimally and precisely as possible)?

Creating a database

**Comment by smallsheeeep** [comment]
This issue should be fixed by the front end. The default charset is `utf-8` and collation is `utf8_general_ci `.

**Comment by ISADBA** [comment]
Get,Please take it  to me for fix.

**Comment by ISADBA** [comment]
https://github.com/oceanbase/odc-client/pull/46

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5381303a-8e28-43b1-91e7-54302e37f49f)

pass
