### ISSUE TITLE
[Bug]: Doris database can be selected for data cleaning

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2038]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/8ec8768c-c7eb-4981-b4e5-dd7f5ce9b093)

### What did you expect to happen?

There is no Doris database in data cleaning

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [244edc70de1f216b7fd3c934518e918428ea1b02](https://github.com/oceanbase/odc-client/commit/244edc70de1f216b7fd3c934518e918428ea1b02)
            ------
            畅晚
            Mon Apr 1 15:17:12 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/0c283f3e-a20e-46ab-87cb-34019551830a)

pass
