### ISSUE TITLE
[Bug]: SQL check error on virtual columns

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2040]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/6c946a46-55c6-42cc-b47e-daa8ff748407)

### What did you expect to happen?

No error reported

### How can we reproduce it (as minimally and precisely as possible)?

1. Enter in SQL window
CREATE TABLE ORACLE_RANGE_VARCHAR_2(
    id INT,
    char_column VARCHAR(64),
    char_column_number GENERATED ALWAYS AS (TO_NUMBER(char_column)) VIRTUAL
) 
2. Perform SQL check

**Comment by yhilmare** [comment]
this issue has been fixed by this pr #2031 and duplicated with this issue #2028
