### ISSUE TITLE
[Bug]: Partition plan does not support fuzzy searches on tables

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2044]
### ODC version

ODC 4.2.4

### OB version

-

### What happened?

Table ORACLE_RANGE_VARCHAR_2 exists. Entering range cannot search out the table.
![image](https://github.com/oceanbase/odc/assets/46598871/0e83f397-233e-4215-a8c7-3b43f17bb6c4)

### What did you expect to happen?

To support fuzzy search

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened

**Comment by HSunboy** [comment]
Fixed In Commit [1c3bcdffe222871c8b3624266deea17713516a5f](https://github.com/oceanbase/odc-client/commit/1c3bcdffe222871c8b3624266deea17713516a5f)
            ------
            咏和
            Tue Mar 26 13:31:20 2024 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/65851774-1141-4918-b713-b50234d1ed98)

pass
