### ISSUE TITLE
[Bug]: Use custom method to create partition report npe

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2045]
### ODC version

ODC 424

### OB version

OBOracle

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/b7ae2dd9-1ed4-497d-ada4-b3495a13105e)
Use custom method to create partition report npe

### What did you expect to happen?

Successfully created partition policy using custom method

### How can we reproduce it (as minimally and precisely as possible)?

```
CREATE TABLE t3(
    id INT,
    char_column CHAR(64) ,
    varchar_column varchar(64) 
    ) PARTITION BY RANGE (varchar_column) (
    PARTITION p20240101 VALUES LESS THAN('2024/01/01'),
    PARTITION p20240201 VALUES LESS THAN('2024/02/01'),
    PARTITION p20240301 VALUES LESS THAN('2024/03/01'),
    PARTITION p20240401 VALUES LESS THAN('2024/04/01')
);
```
The partition interval is：NUMTOYMINTERVAL(1, 'MONTH')
The partition expression is：TO_CHAR(SYSDATE + ${INTERVAL}, '''YYYY/MM/"01"''')

**Comment by bluesky-xyh** [comment]
Fixed

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/2f3a988a-66ff-40c3-a681-ba8a9a65cc47)

pass
