### ISSUE TITLE
[Bug]: The front-end interface crashes when viewing the created deletion policy in the partition plan details.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2046]
### ODC version

ODC 4.2.4

### OB version

OBOracle

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/4e248f32-0620-49f1-a030-84e0cd85b51c)
![image](https://github.com/oceanbase/odc/assets/46598871/1b78b209-8c98-4703-837e-7d5784337519)
The front-end interface crashes when viewing the created deletion policy in the partition plan details.

### What did you expect to happen?

I can view the created deletion policy within the partition plan details

### How can we reproduce it (as minimally and precisely as possible)?

Create a deletion policy for the partition table and view the deletion policy details in the task details.

**Comment by HSunboy** [comment]
Fixed In Commit [1c3bcdffe222871c8b3624266deea17713516a5f](https://github.com/oceanbase/odc-client/commit/1c3bcdffe222871c8b3624266deea17713516a5f)
            ------
            咏和
            Tue Mar 26 13:31:20 2024 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/df9db528-7c3b-4fde-9115-983c3ed431e0)

pass
