### ISSUE TITLE
[Bug]: There is no need to restrict users’ permissions to access to schemas like  sys, information_schema

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#2048]
### ODC version

4.2.3

### OB version

all

### What happened?

If the sys schema is not added to the current project, you need to add it to the project to access it.
![image](https://github.com/oceanbase/odc/assets/140503120/d0b55440-aa2c-4d65-86c9-28aea8644d7b)

### What did you expect to happen?

There is no need to restrict users’ permissions to access schema like sys、 information_schema and mysql.

### How can we reproduce it (as minimally and precisely as possible)?

like above

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ec55751c-4e33-4734-bdc1-9685f2f27f3c)

pass
