### ISSUE TITLE
[Bug]: Abnormal display of partition plan box in dark mode

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2049]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/21f738fb-8742-408a-b557-7d842aba7b8d)

### What did you expect to happen?

Normal display

### How can we reproduce it (as minimally and precisely as possible)?

Open partition plan

**Comment by HSunboy** [comment]
Fixed In Commit [1c3bcdffe222871c8b3624266deea17713516a5f](https://github.com/oceanbase/odc-client/commit/1c3bcdffe222871c8b3624266deea17713516a5f)
            ------
            咏和
            Tue Mar 26 13:31:20 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5eee1fba-1839-4419-ac71-b7dc3d0c38fd)

pass
