### ISSUE TITLE
[Bug]: Mysql mode editing function intelligent completion lacks return

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#205]
### ODC version

4.2.0

### OB version

mysql 4.1.0

### What happened?

Lack of return, only reurns
![image](https://github.com/oceanbase/odc/assets/141202865/433b6ee5-8ea4-4288-9c29-1b0a84e32493)

### What did you expect to happen?

Show return, returns

### How can we reproduce it (as minimally and precisely as possible)?

New/Edit Function

**Comment by HSunboy** [comment]
Fixed In Commit [880e6dea4074dd2a29cb8c9d410bf120001e6bcf](https://github.com/oceanbase/odc-client/commit/880e6dea4074dd2a29cb8c9d410bf120001e6bcf)
            ------
            xiaokang
            Mon Jul 8 14:10:47 2024 +0800

**Comment by tonghan-gsh** [comment]
pass
![image](https://github.com/user-attachments/assets/8a9b3c7d-f55a-489b-8eb5-bf7d669b640c)
