### ISSUE TITLE
[Bug]: failed to execute a sql with a single comment

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2053]
### ODC version

4.2.4

### OB version

not related

### What happened?

I write a sql with a single comment and an syntax exception will be thrown.

```sql
select
  -- this is a comment
1 from dual;
```
<img width="637" alt="截屏2024-03-26 14 10 16" src="https://github.com/oceanbase/odc/assets/22992296/6ddffb28-01eb-443a-a516-9f47a2c12ea8">

### What did you expect to happen?

execute it successfully~

### How can we reproduce it (as minimally and precisely as possible)?

execute the sql above, remember add two white space at the beginning of the single comment.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/2276780f-4c65-4b1f-bc4c-51314d9474d2)

pass
