### ISSUE TITLE
[Bug]: The data in all work orders is less than the work orders I initiated

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2056]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b7146476-f38b-45db-87ef-a315ddfba1e7)
![image](https://github.com/oceanbase/odc/assets/143492234/d2fd5826-9494-47d8-bb6c-af5575638192)

### What did you expect to happen?

The number of all work orders is greater than the number of work orders I initiated

### How can we reproduce it (as minimally and precisely as possible)?

View my initiated work orders and all work orders

**Comment by tonghan-gsh** [comment]
The java version of the test environment is too high,the environment deployed with docker is fine.
