### ISSUE TITLE
[Bug]: The sql display of the database change task is incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2058]
### ODC version

ODC 4.2.4

### OB version

OBOracle430

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/b1c175f6-df87-429c-945b-9b285c07ec69)
he sql of the database change task is not fully displayed

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/871b819a-5249-40e3-bac4-7796ca0dcade)

### How can we reproduce it (as minimally and precisely as possible)?

View database change task details.

**Comment by HSunboy** [comment]
Fixed In Commit [f5d46e54171bfde05ebc026e70278f9341af6d96](https://github.com/oceanbase/odc-client/commit/f5d46e54171bfde05ebc026e70278f9341af6d96)
            ------
            咏和
            Wed Mar 27 15:56:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1fdde6ef-f653-41ce-9e1e-f63225196175)

pass
