### ISSUE TITLE
[Bug]: CREATE TYPE in the SQLWindow Unable to execute, syntax error reported, can be executed separately

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#206]
### ODC version

4.1.2

### OB version

oracle shcema 4.0.0

### What happened?

```SQL
CREATE TYPE my_type AS OBJECT (
    id NUMBER,
    name VARCHAR2(50),
    MEMBER PROCEDURE my_procedure(p_param1 IN NUMBER, p_param2 IN VARCHAR2)
);
CREATE TYPE BODY my_type AS
    MEMBER PROCEDURE my_procedure(p_param1 IN NUMBER, p_param2 IN VARCHAR2) AS
    BEGIN
        -- 执行自定义逻辑
        dbms_output.put_line('参数1: ' || p_param1 || ', 参数2: ' || p_param2);
    END;
END;
```
excute sql in the sqlwindow
syntax error reported
![image](https://github.com/oceanbase/odc/assets/141202865/9e0cf38f-9732-4666-8838-c25f255e222a)
Do It alone,success!
![image](https://github.com/oceanbase/odc/assets/141202865/abe5751f-d4bd-401d-adbd-4bb6c5daa878)

### What did you expect to happen?

Together excute, success!

### How can we reproduce it (as minimally and precisely as possible)?

Together excute create type sql

**Comment by LuckyPickleZZ** [comment]
'CREATE OR REPLACE TYPE' is PL syntax and requires `/` as delimiter.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/2fd40af7-7f8b-437c-9068-60f09df67aef)

pass
