### ISSUE TITLE
[Bug]: Edit the existing deletion policy of the partition table, but the number of reserved partitions is not displayed.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2062]
### ODC version

ODC4.2.4

### OB version

OBOracle

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/cad9157d-c513-4fc8-ab1b-6bdde6935cf0)
Edit the existing deletion policy of the partition table, but the number of reserved partitions is not displayed.

### What did you expect to happen?

Show the number of reserved partitions

### How can we reproduce it (as minimally and precisely as possible)?

A partition plan with a deletion policy already exists. Create a new partition plan task and edit the deletion policy.

**Comment by HSunboy** [comment]
Fixed In Commit [f5d46e54171bfde05ebc026e70278f9341af6d96](https://github.com/oceanbase/odc-client/commit/f5d46e54171bfde05ebc026e70278f9341af6d96)
            ------
            咏和
            Wed Mar 27 15:56:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/dcfb97a9-8657-4841-94a5-69e510875872)

pass
