### ISSUE TITLE
[Bug]: When editing the start time of an existing creation policy, the front-end interface crashes

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2066]
### ODC version

ODC4.2.4

### OB version

OBOracle

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/ce50006b-d9f7-4af0-b9b5-c173c99af972)
![image](https://github.com/oceanbase/odc/assets/46598871/e824d702-1892-4663-a406-588340b46297)
When editing the start time of an existing creation policy, the front-end interface crashes

### What did you expect to happen?

I can edit the partition start time.

### How can we reproduce it (as minimally and precisely as possible)?

A partition planning task already exists. Edit the starting time of the partition.

**Comment by HSunboy** [comment]
Fixed In Commit [f5d46e54171bfde05ebc026e70278f9341af6d96](https://github.com/oceanbase/odc-client/commit/f5d46e54171bfde05ebc026e70278f9341af6d96)
            ------
            咏和
            Wed Mar 27 15:56:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/851b9774-c7b0-4309-972f-fe2593a56cea)

pass
