### ISSUE TITLE
[Bug]: The partition name in the sql statement of the delete partition plan must be enclosed in quotation marks

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2067]
### ODC version

ODC 4.2.4

### OB version

OBOracle

### What happened?

There is a partition named 20240501,and the sql generated by deleting the policy is:
![image](https://github.com/oceanbase/odc/assets/46598871/3016b378-623e-4a9e-8ee0-16070ce6eaab)
Execution will report a syntax error
![image](https://github.com/oceanbase/odc/assets/46598871/b3dcf9d9-eac1-4fef-af9f-ae171b017a92)

### What did you expect to happen?

Use quotation marks to enclose the partition name.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6685afe5-a3ce-44bd-bf54-725fb44d5975)

pass
