### ISSUE TITLE
[Bug]: users could edit the built-in default environment's sql rules

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#2069]
### ODC version

ODC 4.2.4

### OB version

not related

### What happened?

Users could edit the built-in default environment's SQL rules while is opposite against the description.
![image](https://github.com/oceanbase/odc/assets/39962741/31683597-d693-4e0c-8935-88a2e0a66ea1)

### What did you expect to happen?

Disable the edition of the default environment.

### How can we reproduce it (as minimally and precisely as possible)?

As I said in what happened.

**Comment by HSunboy** [comment]
Fixed In Commit [bed88383dadf42291064cc3d6543b7856199b179](https://github.com/oceanbase/odc-client/commit/bed88383dadf42291064cc3d6543b7856199b179)
            ------
            陈朝俊
            Thu Mar 28 15:45:10 2024 +0800
