### ISSUE TITLE
[Bug]: Export data + structure failed, no error log

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#207]
### ODC version

4.1.2

### OB version

mysql mode 2.2.77

### What happened?

Export a name of table that is：`123!@#$%^&*()_+-=[]{}\|;':""'`
![image](https://github.com/oceanbase/odc/assets/141202865/5e843ba4-900d-4e10-b2cd-6857abca90cf)
![image](https://github.com/oceanbase/odc/assets/141202865/75d33b38-ac22-4505-bc13-fc84186c86c5)

### What did you expect to happen?

There are error logs

### How can we reproduce it (as minimally and precisely as possible)?

Export a name of table that is：`123!@#$%^&*()_+-=[]{}\|;':""'`

**Comment by LuckyPickleZZ** [comment]
Depends on ob-loader-dumper. Delay
