### ISSUE TITLE
[Bug]: It still shows 'Connection' rather than 'DataSource' in operation records

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#2070]
### ODC version

4.2.4

### OB version

not related.

### What happened?

Since ODC 4.2.4 introduced 'DataSource' to an alternative with 'Connection', the operation records still show 'Connection'.
![image](https://github.com/oceanbase/odc/assets/39962741/5db8b6d4-3957-4f89-a43d-68cde2ec9753)
![image](https://github.com/oceanbase/odc/assets/39962741/7c343030-61fd-4cbe-bbab-6ea75e76bec1)

### What did you expect to happen?

It shows 'DataSource' instead of 'Connection'.

### How can we reproduce it (as minimally and precisely as possible)?

Open operation records.

**Comment by HSunboy** [comment]
Fixed In Commit [77ad728956062508dda106afe1e3b4f6caa870f5](https://github.com/oceanbase/odc-client/commit/77ad728956062508dda106afe1e3b4f6caa870f5)
            ------
            陈朝俊
            Fri Mar 29 09:31:54 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/0df67004-7a80-4f40-b11f-f44736401cc2)

There are still issues
