### ISSUE TITLE
[Bug]: Users cannot remove the inexistent databases from the project

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#2071]
### ODC version

4.2.4

### OB version

Not related to the OB version.

### What happened?

Users cannot remove the database from the project even if the database has been nonexistent.
![image](https://github.com/oceanbase/odc/assets/39962741/d0386f07-d4d5-42a1-81a8-b0e9910f48fa)

### What did you expect to happen?

Users can remove the database from the project no matter what the database's status is.

### How can we reproduce it (as minimally and precisely as possible)?

1. Add a database into a project.
2. Drop the database.
3. Open the database list in the project.

**Comment by smallsheeeep** [comment]
Database can only be deleted in the database list inner Datasource page. So I think the current performance meets expectations.
