### ISSUE TITLE
[Bug]: For the doris data source, odc reported an exception when creating a databas

### ISSUE THREAD

**Issue by zijiacj** [oceanbase/odc#2075]
### ODC version

ODC4.2.4

### OB version

doris, maybe any version

### What happened?

odc failed to create doris database. 
![截屏2024-03-27 10 52 03](https://github.com/oceanbase/odc/assets/135618909/1419a36c-5643-4f2c-9503-a7eb109f086c)

### What did you expect to happen?

odc successfully creates the doris database.

### How can we reproduce it (as minimally and precisely as possible)?

Click a specific doris data source to enter the data source details page, click the New database button to open the details page, enter the relevant parameters and click OK to reproduce the scene.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/7db812bd-d03a-4c24-9fcc-dfeb63725374)

pass
