### ISSUE TITLE
[Bug]: Manually increase desensitization columns Some added columns are not grayed out

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#208]
### ODC version

4.2.0

### OB version

mysql 4.1.0

### What happened?

Temporarily found that bit, time_x and other time types, enum, and set types are not grayed out, so they can be selected to report prompts
![image](https://github.com/oceanbase/odc/assets/141202865/24585c37-13a0-4246-b666-80aae8638206)

### What did you expect to happen?
Added selections will be grayed out

### How can we reproduce it (as minimally and precisely as possible)?

Add desensitization column manually

**Comment by UnknownAdventurer** [comment]
This has deprecated , and  has been merged at the latest branch in ver 4.2.2( or 4.2.3)
https://github.com/oceanbase/odc-client/commit/feab842a22d6d2c6e29630c3a55d800f5679cd8f
