### ISSUE TITLE
[Bug]: The SQL window will not automatically select the permission type when initiating a database permission application

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2082]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/f5eba5ba-d007-4e75-ade6-5e1a58417444)
![image](https://github.com/oceanbase/odc/assets/143492234/d792f506-a42d-464b-8b4e-2fe67fa8dadc)

### What did you expect to happen?

The permission type will be automatically filled in

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by bluesky-xyh** [comment]
Currently, the database can only be selected by default, and the permissions can be selected by yourself.
