### ISSUE TITLE
[Bug]: Incorrect display prompt when selecting no export result set weights when exporting result sets

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2084]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/948b170f-0dff-45b6-b396-991d911e9dec)

### What did you expect to happen?

Prompt for correct display

### How can we reproduce it (as minimally and precisely as possible)?

The user only has export permissions and creates an export result set task.

**Comment by HSunboy** [comment]
Fixed In Commit [ab3a10fb4840caa3023d3e74352eb8d4c5fd7947](https://github.com/oceanbase/odc-client/commit/ab3a10fb4840caa3023d3e74352eb8d4c5fd7947)
            ------
            陈朝俊
            Thu Mar 28 15:00:21 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8a94674e-d76d-4616-a7f2-9085c5915e87)

pass
