### ISSUE TITLE
[Bug]: The sql statement generated by the partition plan must enclose the lowercase table name in quotation marks.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2086]
### ODC version

ODC 4.2.4

### OB version

OBOracle

### What happened?

If there is a lowercase table name in the generated SQL statement, a syntax error will be reported during execution.
![image](https://github.com/oceanbase/odc/assets/46598871/333ab263-e30c-4bfa-8883-11307d11f99e)

### What did you expect to happen?

The sql statement generated by the partition plan must enclose the lowercase table name in quotation marks.

### How can we reproduce it (as minimally and precisely as possible)?

Create a partitioned table with a lowercase table name and create a partition scheduled task for it.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/61f4a938-1c4b-467e-8d21-d39769e06555)

pass
