### ISSUE TITLE
[Bug]: Partition plans requiring approval do not display partition strategy details

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2089]
### ODC version

ODC4.2.4

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/aa120978-ad90-4247-8a26-4639ff2fd958)
Partition plans requiring approval do not display partition strategy details.

### What did you expect to happen?

Partition plans requiring approval need to display partition strategy details.

### How can we reproduce it (as minimally and precisely as possible)?

Add partition planning tasks to high-risk tasks and initiate tasks. Approvers view the details of tasks to be approved.

**Comment by yhilmare** [comment]
fixed：
<img width="742" alt="截屏2024-03-27 22 09 07" src="https://github.com/oceanbase/odc/assets/22992296/87f80898-44e7-47f3-b9a1-42e38a6dc043">
