### ISSUE TITLE
[Bug]: Vertex the divisor in the function is incompatible with the Source Command in Oracle Mode ODC command line

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#209]
### ODC version

4.1.2

### OB version

all schema

### What happened?

```SQL
CREATE or REPLACE PROCEDURE test_divide
as 
    ln_ret NUMBER(22,6);
BEGIN
    ln_ret := 1/2;
END;
/
```
1、sql save it on ODC as test_divide.sql file
![image](https://github.com/oceanbase/odc/assets/141202865/298ec57f-1cbe-45b8-bb19-277d6e7741d1)
and the error is then reported from the command line source command line
2、However, there is no error after the division sign is removed
3、Successful execution via obclient command line. Note: same problem with Obclient 2.2.1, no problem with upgrading obclient 2.2.3

```
/u01/obclient/bin/obclient --version
/u01/obclient/bin/obclient  Ver 2.2.3 Distrib 10.4.18-MariaDB, for Linux (x86_64) using readline 5.1

Server version: OceanBase 3.2.3.3 (r107040032023032910-c59670fcc6f48d0f6d7ba107e85d43efe85e6615) (Built Mar 29 2023 10:50:14)

Copyright (c) 2000, 2018, OceanBase and/or its affiliates. All rights reserved.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

obclient [ALVIN]> source test_divide.sql
Query OK, 0 rows affected (0.016 sec)
```

### What did you expect to happen?

ln_ret := 1/2 in the sql,execute through

### How can we reproduce it (as minimally and precisely as possible)?

-

**Comment by LuckyPickleZZ** [comment]
We have upgraded obclient's version from 1.2.8 to 2.2.4 in #861 . This cases has been tested tet.
