### ISSUE TITLE
[Bug]: commit and rollback button does not sync with transaction status for oceanbase 4.2

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#2096]
### ODC version

4.1.0~4.2.3

### OB version

4.2.1.1~4.2.1.4

### What happened?

 commit and rollback button does not sync with transaction status for oceanbase 4.2

after check flow, rootcause was got transaction state failed.

below query return empty resultset.
```sql
SELECT * FROM SYS.GV$OB_PROCESSLIST WHERE ID=userenv('sessionid')
```

![image](https://github.com/oceanbase/odc/assets/54161870/da19caf7-afc6-4ad7-a40d-89d9fa4f867a)

### What did you expect to happen?

if set autocommit OFF, commit and rollback button shoudl sync with transaction status 

### How can we reproduce it (as minimally and precisely as possible)?

1. set autocommit OFF
2. execute some DML statement
3. check the commit/rollback button, should clickable
4. do commit
5. check the commit/rollback button, should be gray, not clickable

**Comment by Huangxiao-mas** [comment]
test pass


![Image](https://github.com/oceanbase/odc/assets/59468957/31e941ee-7d77-42af-934c-aeee1445ecec)
