### ISSUE TITLE
[Bug]: Structure comparison does not open corresponding details

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2100]
### ODC version

odc424

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/66e6accd-5ff3-4491-8d7e-6248154d0573

### What did you expect to happen?

Open the correct details

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [f9d946a8aa17c7c08cd49c6698fbbe2380c4f655](https://github.com/oceanbase/odc-client/commit/f9d946a8aa17c7c08cd49c6698fbbe2380c4f655)
            ------
            陈朝俊
            Fri Mar 29 09:32:16 2024 +0800

**Comment by sl01388797** [comment]
pass
