### ISSUE TITLE
[Bug]: Add rules within the risk level, there is no structural comparison within the task type

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2102]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/da73b3a3-7ae9-499d-a84b-20432761fd79)

### What did you expect to happen?

Structural comparison exists

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [74f93cf6c9925ab1a8dcf54be1695b5be2b64f45](https://github.com/oceanbase/odc-client/commit/74f93cf6c9925ab1a8dcf54be1695b5be2b64f45)
            ------
            陈朝俊
            Thu Mar 28 14:57:33 2024 +0800
