### ISSUE TITLE
[Bug]: There is an unknown task type in the operation record after agreeing to compare the approval structure

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2108]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/5da98f51-3c2c-40c0-8f97-e9de7662f813)

### What did you expect to happen?

Unknown task type changed to structural comparison

### How can we reproduce it (as minimally and precisely as possible)?

Approval or rejection of structural comparison

**Comment by HSunboy** [comment]
Fixed In Commit [d8de1deaf4a42d6f29de12847571c3a63062e0d2](https://github.com/oceanbase/odc-client/commit/d8de1deaf4a42d6f29de12847571c3a63062e0d2)
            ------
            陈朝俊
            Sat Mar 30 15:45:48 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9d04cc0e-9555-40e7-a4f8-05525789e7b5)

pass
