### ISSUE TITLE
[Bug]: Setting internal shutdown to obtain Row ID, but Row ID still exists

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2109]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/8dff8714-1765-4798-b6da-0e243a555aa2)

### What did you expect to happen?

 Row ID not displayed

### How can we reproduce it (as minimally and precisely as possible)?

1. Close Get Row ID
2. Execute SQL

**Comment by HSunboy** [comment]
Rowid is not traceid
