### ISSUE TITLE
[Bug]: When the query result is "0000-00-00 00:00:00", the result set download is null

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#211]
### ODC version

4.1.3

### OB version

4.1.0bp2

### What happened?

```SQL
DROP table t0;
create table t0(c0 datetime);
insert into t0 values(0);
select * from t0;
```
Download result set
![image](https://github.com/oceanbase/odc/assets/141202865/b35ab0be-a02e-4980-ac0c-7585f6abd62b)

### What did you expect to happen?

no response

### How can we reproduce it (as minimally and precisely as possible)?

no response

**Comment by LuckyPickleZZ** [comment]
This bug is related to a jdbc param `zeroDateTimeBehavior`. In the earlier version, ODC used `round` as it's value, while ob-loader-dumper used `convertToNull`. Now we have set it to be consistent.
