### ISSUE TITLE
[Bug]: The deleted database still exists within manual desensitization

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2110]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/238e9c56-5efd-49d9-a980-0139fa331922)
![c38241b2615b77b7deeb88a9127063a6](https://github.com/oceanbase/odc/assets/143492234/7cad6dd5-b650-41fd-9898-fb93075f81b6)
![2bfcf79492e591b3082dbe3ec47a9cc1](https://github.com/oceanbase/odc/assets/143492234/2937045f-d250-4dcf-8c55-8f4e1845311f)
![9a3579f1ad45b66063939032af81b91f](https://github.com/oceanbase/odc/assets/143492234/e5d715f3-7d01-4233-b100-0516f8258e94)

### What did you expect to happen?

The deleted database is still displayed in the list after manually adding the desensitization column

### How can we reproduce it (as minimally and precisely as possible)?

1. remove data sources
2. Select the database to be deleted in the sensitive column

**Comment by smallsheeeep** [comment]
The front-end transfer wrong request parameters:
<img width="1456" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/f170b01e-3e87-49ec-902b-995bfa423666">
@UnknownAdventurer

**Comment by HSunboy** [comment]
Fixed In Commit [7b550ef06bb09160a9f671103d2b1a0298a2909a](https://github.com/oceanbase/odc-client/commit/7b550ef06bb09160a9f671103d2b1a0298a2909a)
            ------
            陈朝俊
            Fri Mar 29 09:55:27 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f92c285f-a505-4a1b-b250-00482425cf73)

pass
