### ISSUE TITLE
[Bug]: JDBC socket timeout is 60 seconds in Export data

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#2115]
### ODC version

424

### OB version

all

### What happened?

![image](https://github.com/oceanbase/odc/assets/140503120/287e55fc-0b17-468c-be9b-0e1adc7e4a08)

### What did you expect to happen?

Make the socketTimeout of the export task a configurable item

### How can we reproduce it (as minimally and precisely as possible)?

create new Export tasks

**Comment by Huangxiao-mas** [comment]
test pass
