### ISSUE TITLE
[Bug]: show trace result set download sql data only one line of data

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#212]
### ODC version

4.2.0

### OB version

oracle_3.2.3.2

### What happened?

```SQL
select * from emp; -- emp empty table
```
Execute show trace in the sql window; download the result set

![image](https://github.com/oceanbase/odc/assets/141202865/7837983c-619d-4afa-af62-dd2c9b55c2b8)

### What did you expect to happen?

All data in the result set

**Comment by LuckyPickleZZ** [comment]
Show trace's should not be downloaded currently.
