### ISSUE TITLE
[Bug]: The settings in the desktop version did not disappear after clicking save

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2120]
### ODC version

odc424

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/4fea8293-0696-4449-9419-d7d62f83a353

### What did you expect to happen?

Settings disappear after clicking save

### How can we reproduce it (as minimally and precisely as possible)?

Click save in the settings section

**Comment by HSunboy** [comment]
fixed

**Comment by sl01388797** [comment]
pass
