### ISSUE TITLE
[Bug]: The link in the operation record is not a data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2123]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/7cee5e5d-da54-468f-a298-a9bba95c9892)

### What did you expect to happen?

It shows 'DataSource' instead of 'Connection'.

### How can we reproduce it (as minimally and precisely as possible)?

Open operation records.

**Comment by HSunboy** [comment]
Fixed In Commit [b821eda67f0e71168229661a9568c337e382a0b0](https://github.com/oceanbase/odc-client/commit/b821eda67f0e71168229661a9568c337e382a0b0)
            ------
            陈朝俊
            Mon Apr 1 10:30:24 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f4fd927b-66a0-43c9-adbc-191b8a2bbd6d)

pass
