### ISSUE TITLE
[Bug]: Initiate a failed approval task again

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#213]
### ODC version

4.2.0

### OB version

oracle_4.1.0

### What happened?

![image](https://github.com/oceanbase/odc/assets/141202865/cf6a5102-a47b-420a-8696-d0fcf8939e4f)
![image](https://github.com/oceanbase/odc/assets/141202865/0d24f52d-70b2-46c1-845c-da2af8e98a31)

### What did you expect to happen?

Execute approval again

### How can we reproduce it (as minimally and precisely as possible)?

Initiate a failed approval task again

**Comment by smallsheeeep** [comment]
@runzi389205 It seems a outdated bug which has been fixed in 4.2.0 release. I can not reproduce it in latest version.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/df340a19-2647-4ba0-9d25-4bad3eb6b7cd)

pass
