### ISSUE TITLE
[Enhancement]: The default environment should allow editing of SQL check rules/windowing rules.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#2131]
### What would you like to be added?

默认环境应该允许编辑 SQL 检查规则/窗口规则。调整默认环境的描述文案，去掉不可编辑。

### Why is this needed?

关于允许理由：
1、禁止编辑可能会影响某些现存用户的体验，比如有些用户没有使用其它环境标，默认情况下数据源会使用默认环境标，这导致默认环境标上很可能有关联大量数据源。
2、会影响灵活性，即使默认环境的规则设置得默认值再好，也很难完全符合用户的实际情况。

**Comment by HSunboy** [comment]
Fixed In Commit [c81a60664cc76924610ca7c87bd43f04e6d35191](https://github.com/oceanbase/odc-client/commit/c81a60664cc76924610ca7c87bd43f04e6d35191)
            ------
            陈朝俊
            Tue Apr 2 16:53:23 2024 +0800
