### ISSUE TITLE
[Bug]: Close the task framework, the historical task is not stopped or the task is stopped immediately

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2133]
### ODC version

ODC424

### OB version

independent

### What happened?

Close the task framework, the historical task is not stopped or the task is stopped immediately
![image](https://github.com/oceanbase/odc/assets/59468957/00ccd134-1e82-44c5-a1a3-4fa52fcb7ad3)
![image](https://github.com/oceanbase/odc/assets/59468957/93480d58-ab4b-4760-82f9-1f8695409c06)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

1. Open task frame
2. Create task
3. Close the frame during task execution
4. Restart docker

**Comment by krihy** [comment]
PR [https://github.com/oceanbase/odc/pull/2119]

**Comment by Huangxiao-mas** [comment]
The page status does not change to execution failure
