### ISSUE TITLE
[Bug]: the description of the cron expression is illegal

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2139]
### ODC version

4.2.4

### OB version

not related

### What happened?

1. open partition plan task panel
2. select "custom mode" option in schedule strategy and type cron expression as follow: `* 22 14 2 4 ?`:
<img width="374" alt="截屏2024-04-02 14 24 12" src="https://github.com/oceanbase/odc/assets/22992296/b30c9581-8fe9-4fdf-af26-da2aaac9fb29">

as you can see the notice "每年 4 月 2 日 14 点 22 分" is wrong

### What did you expect to happen?

the cron expression stands for "每秒"

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [29528084deeb56f8d2a1bcf064198310000fbf79](https://github.com/oceanbase/odc-client/commit/29528084deeb56f8d2a1bcf064198310000fbf79)
            ------
            畅晚
            Fri May 31 13:55:27 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/888c1583-622a-435e-b56a-94ee537f48d8)

pass
