### ISSUE TITLE
[Bug]: can not echo the specific time when a table is configured in partition plan

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2140]
### ODC version

4.2.4

### OB version

not related

### What happened?

1. I create a partition plan on a table with specific time:
<img width="899" alt="截屏2024-04-02 14 33 23" src="https://github.com/oceanbase/odc/assets/22992296/9a45c3b7-de87-4638-b197-4189cf84104d">

2. I submit this task and the task is executed successfully
<img width="925" alt="截屏2024-04-02 14 35 18" src="https://github.com/oceanbase/odc/assets/22992296/dd789151-26f5-4043-a612-4de7958eae17">

as you can see: the detail is right

3. I want to start up a partition plan on this table again:
<img width="896" alt="截屏2024-04-02 14 36 21" src="https://github.com/oceanbase/odc/assets/22992296/2b4b8c0a-d1eb-4af4-b6f0-a6fc56543662">

the start up time is missing and the api has given the right value:
<img width="335" alt="截屏2024-04-02 14 37 28" src="https://github.com/oceanbase/odc/assets/22992296/34d237ff-a639-425f-a692-79fae3abef54">

btw, the missing time value can be appeared when I select "specific time":

<img width="709" alt="截屏2024-04-02 14 38 25" src="https://github.com/oceanbase/odc/assets/22992296/26668244-480a-49c0-825b-252cfcbf1f0a">

### What did you expect to happen?

echo the start up time correctly

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [ff703ccc3b28eaa76cfdb514aa80c6ad96ff9098](https://github.com/oceanbase/odc-client/commit/ff703ccc3b28eaa76cfdb514aa80c6ad96ff9098)
            ------
            畅晚
            Tue Apr 2 17:23:05 2024 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/50d7f048-d59a-4e7e-838a-d5dff210c778)
pass
