### ISSUE TITLE
[Bug]: the partition key refs a column which does not exist

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2144]
### ODC version

4.2.4

### OB version

not related

### What happened?

1. I config the partition plan on a table A:
<img width="445" alt="截屏2024-04-02 16 30 27" src="https://github.com/oceanbase/odc/assets/22992296/77703a07-1b45-4838-9c01-139a487b7d95">

as you can see: the partition name config ref the partition key 'FLOW_TIME', please remember this.

2. I click okay and quit. I continue set partition plan on another table B:
<img width="908" alt="截屏2024-04-02 16 31 59" src="https://github.com/oceanbase/odc/assets/22992296/808ed432-aa1e-48f9-ad9e-b2cfc77d3660">

as you can see: the partition name config alse ref the partition key 'FLOW_TIME', but the table B doesn't have this partition key and cause an exception when I attempt to preview it:
<img width="803" alt="截屏2024-04-02 16 33 17" src="https://github.com/oceanbase/odc/assets/22992296/d4b29813-854f-48b6-8d1e-f135e3001909">

### What did you expect to happen?

I can set partition plan normally

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [ff703ccc3b28eaa76cfdb514aa80c6ad96ff9098](https://github.com/oceanbase/odc-client/commit/ff703ccc3b28eaa76cfdb514aa80c6ad96ff9098)
            ------
            畅晚
            Tue Apr 2 17:23:05 2024 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/4c22bc32-cee3-47a0-a042-c57fabecdfe2)
pass
