### ISSUE TITLE
[Bug]: Desktop version export related interface request speed optimization

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#215]
### ODC version

4.2.0

### OB version

all mode

### What happened?

Right click and select table export
1、Export panel object display interface
![image](https://github.com/oceanbase/odc/assets/141202865/3018738c-5e89-4583-b611-54d3f6d033f8)
2、选择导出flowInstances接口
![image](https://github.com/oceanbase/odc/assets/141202865/178cff83-6b3c-4cdd-8921-8e1e99ce44e2)

### What did you expect to happen?

faster

### How can we reproduce it (as minimally and precisely as possible)?

_No Response_

**Comment by LuckyPickleZZ** [comment]
This operation is related to create session. There is no solution currently.
