### ISSUE TITLE
[Bug]: partition plan data migration may be failed 

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2156]
### ODC version

4.2.4

### OB version

not related

### What happened?

user do not set any partition plan or make all partition plan disable.
odc will startup failed.

### What did you expect to happen?

odc can start up succeed~

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by yhilmare** [comment]
if we disable all partition plan configs for a specific database will encounter this bug, and the odc.log will print like this:
![截屏2024-04-07 10 40 08](https://github.com/oceanbase/odc/assets/22992296/071850b2-78ea-44de-963b-d91b9096c5d8)

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/bd9f37ee-bfc5-409b-901d-3c83749801ec)
The 423 version can be successfully upgraded to 424 even if no partition plan is configured
