### ISSUE TITLE
[Bug]: alter ddl could not be executed in ODC

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#2157]
### ODC version

4.2.4

### OB version

4.2.1.4

### What happened?

DDL could be executed in obclient, but could not be executed in odc.

![image](https://github.com/oceanbase/odc/assets/36879124/f0fe54b1-70cb-4536-80d2-c8a8eb889510)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

CREATE TABLE "ACCT_CUST_JZ"("CUSTNO" NUMBER(38),
"APPCUSTNO" VARCHAR2(32),
"CUSTTP" CHAR(2),
"CUSTGROUP" CHAR(2),
"CUSTCLASS1" VARCHAR2(255),
"CUSTCLASS2"VARCHAR2(255),
"OPENDATE" CHAR(8),
"MODIDATE" CHAR(8),
"CERTIFICATETYPE" CHAR(1),
"CERTIFICATENO" VARCHAR2(32),
"CUSTNAME" VARCHAR2(128),
"INVTP" CHAR(1),
"NICKNAME" VARCHAR2(32),
"STATUS" CHAR(1),
"LAST STATUS" CHAR(1),
"OPENCUSTMANAGER" VARCHAR2(8),
"SIGNFASTREDEEMSTATUS" CHAR(1),
"DIRCUSTTYPE" CHAR(1),
"INVESTACCT" CHAR(20),
"USERTP" CHAR(1),
"CUSTACCTTYPE" CHAR(1));

`alter table "ACCT_CUST_JZ" modify custname varchar2(128)`;

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6b13a455-8971-4420-b92e-4e8f59b2208b)

pass
