### ISSUE TITLE
[bug]: cannot access to DBLink in SQL console

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#217]
### Is your feature request related to a problem?

When executing SQL to access DBLink, it prompts that there is no access permission to the database.
<img width="1082" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/2c3c09e2-090e-4c27-b679-5050e1812a31">

### Describe the solution you'd like

It seems that DBLink is treated as a normal database during SQL parse. Special processing is required here for DBLink.

**Comment by Huangxiao-mas** [comment]
PASS


![Image](https://github.com/oceanbase/odc/assets/59468957/5df91f26-bcc0-4156-8c90-6c7167ad1158)
