### ISSUE TITLE
[Bug]: Multiple nodes, use IP to access, create data archive, task log cannot be viewed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2171]
### ODC version

ODC424

### OB version

independent

### What happened?

Multiple nodes, use IP to access, create data archive, task log cannot be viewed
![image](https://github.com/oceanbase/odc/assets/59468957/194b5b42-1a86-4cf1-aa10-bf2aa2440d05)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

1. Create multiple nodes
2. access by ip
3. Create archiving task

**Comment by tonghan-gsh** [comment]
pass
