### ISSUE TITLE
[Bug]: failed to debug a pl that contains a sql costing more than 10 minutes

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2172]
### ODC version

4.2.4

### OB version

not related

### What happened?

1. create a pl that contains a sql costing more that 10 mintues
2. try to debug this pl
3. debug will timeout at this sql

### What did you expect to happen?

we can increase the timeout setting using session init script

### How can we reproduce it (as minimally and precisely as possible)?

follow 'What happened'

**Comment by yhilmare** [comment]
`delete from tbl where 1=1` will cost too much time. the default timeout settings is 10 min and we can debug this pl if we don't modify the timeout setting.
<img width="718" alt="截屏2024-04-09 11 51 18" src="https://github.com/oceanbase/odc/assets/22992296/4ba064b1-0106-490f-a172-5ab26f7453b7">

and then I modify the timeout settings to 1 secs:
<img width="540" alt="截屏2024-04-09 11 53 18" src="https://github.com/oceanbase/odc/assets/22992296/c0333d99-c269-4c52-b8d9-23dbadfb4c98">

and I debug it again:

<img width="1123" alt="截屏2024-04-09 11 56 50" src="https://github.com/oceanbase/odc/assets/22992296/3f9da3f0-aa4d-4dbe-9808-c597402d93b1">

as you can see the delete statement is timeout which means that out timeput settings has overwritten the default timeout settings~

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/f18168fb-8b81-41fd-b2df-88f8feaac8e0)
![image](https://github.com/oceanbase/odc/assets/46598871/5000686d-4880-4ae6-8d89-035f9f801d4a)
I changed ob_query_timeout for the data source to 1s, debug timeout.Then, I adjusted to 10 minutes, it can debug completed
