### ISSUE TITLE
[Bug]: web hook channel test send message failed, throw JSON parser error

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#2173]
### ODC version

4.2.4

### OB version

not related

### What happened?

web hook channel test send message failed, throw JSON parser error

![image](https://github.com/oceanbase/odc/assets/54161870/06981447-260f-4e17-a5c4-b2cf78bdcc40)

### What did you expect to happen?

test send message should success

### How can we reproduce it (as minimally and precisely as possible)?

1. create a notification channel with sign secryt value
2. update the created channel, change to self defined
3. test send message

**Comment by HSunboy** [comment]
Fixed In Commit [c9afb824d68d72961f8b55fbcfc81ad6f0b9f524](https://github.com/oceanbase/odc-client/commit/c9afb824d68d72961f8b55fbcfc81ad6f0b9f524)
            ------
            陈朝俊
            Thu Apr 11 10:50:24 2024 +0800
