### ISSUE TITLE
[Bug]: fail to import a zip exported by ODC

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#2176]
### ODC version

4.2.4

### OB version

-

### What happened?

Fail to import a zip exported by ODC.

### What did you expect to happen?

-

### How can we reproduce it (as minimally and precisely as possible)?

1. Export some data in CSV format. 
2. Download zip file.
3. Import.

**Comment by tonghan-gsh** [comment]
pass
