### ISSUE TITLE
[Enhancement]: notification policy ease of use

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#2177]
### What would you like to be added?

1. Notification policy could be filtered by enabled.
2. When selecting all policies, only policies in current page are selected.

![image](https://github.com/oceanbase/odc/assets/36879124/c101dcb1-d3bc-4a4a-90b6-a141d3dd842c)

### Why is this needed?

ease of use

**Comment by HSunboy** [comment]
Fixed In Commit [2e0ee283794f9f5f4ec6bfb890054c4fd7f3eb7b](https://github.com/oceanbase/odc-client/commit/2e0ee283794f9f5f4ec6bfb890054c4fd7f3eb7b)
            ------
            陈朝俊
            Sat May 25 21:16:30 2024 +0800
