### ISSUE TITLE
[Bug]: faied to Automatically complete table names when database user lack mysql schema permissions

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#2182]
### ODC version

4.2.4

### OB version

all

### What happened?

failed to listTables in `api/v2/connect/sessions/{sessionId}/metadata/identities` interface when lack mysql schema permissions:
![image](https://github.com/oceanbase/odc/assets/140503120/1ff224eb-03fc-4bc8-92f0-9c5f4a05e585)
root cause :
![image](https://github.com/oceanbase/odc/assets/140503120/11d30389-e79b-4166-a65b-d175c25da919)

### What did you expect to happen?

1. create a user without msyql schema permissions.
2. Enter relevant sql in the sql window to trigger the `api/v2/connect/sessions/{sessionId}/metadata/identities` interface

### How can we reproduce it (as minimally and precisely as possible)?

The identify interface does not report an error

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/56748182-adb3-4eac-a915-f5b59ce032d0)
The current user does not have mysql permissions, and no error is reported in the sql window auto-complete
