### ISSUE TITLE
[Bug]: fail to reject ticket because of notification exception

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#2183]
### ODC version

4.2.4

### OB version

-

### What happened?

When a datasource was configured without cluster, it would lead to failure of enqueue event.
And reject ticket would fail.

### What did you expect to happen?

1. The event should be enqueued normally.
2. It should not affect original transaction.

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a datasource without cluster. 
2. Configure notification policy.
3. Reject a ticket.

**Comment by tonghan-gsh** [comment]
pass
