### ISSUE TITLE
[Bug]: Unable to invoke Cipher due to bad padding error while test connection in datasource edit page

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#2186]
### ODC version

4.2.3

### OB version

not related

### What happened?

Test connection for sys tenant failed.

![image](https://github.com/oceanbase/odc/assets/54161870/1cb96a31-e9ee-4b34-a8b2-98d2c9fc7031)

error message details:

JSON parse error: Unable to invoke Cipher due to bad padding; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to invoke Cipher due to bad padding (through reference chain: com.oceanbase.odc.service.connection.model.TestConnectionReq["password"])

### What did you expect to happen?

test connection should success

### How can we reproduce it (as minimally and precisely as possible)?

login metadb
```sql
update config_system_configuration set `value` = 'true' where `key`='odc.features.task.osc.enabled';
```

test connection

### Anything else we need to know?

while odc.features.task.osc.enabled set 'false', the problem not occurs

**Comment by smallsheeeep** [comment]
It works for me when cerate or update a data source and test the connect to SYS tenant:
<img width="752" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/87c1cee4-53af-4138-932d-577f3ddedf15">
This PR (#1994) add log output when failed to decrypt, so please provide log file when you reproduce this issue.
