### ISSUE TITLE
[Bug]: When switching the ending symbol to $while continuing execution with an error message enabled, an error message indicates an error mark

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2193]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/4f66bdec-51c9-4345-85bb-40b283bc747f)

### What did you expect to happen?

Only the first row displays red

### How can we reproduce it (as minimally and precisely as possible)?

1. Enable error reporting to continue execution, switch Delimiter to$
2. Simultaneously executing incorrect SQL and correct SQL

**Comment by HSunboy** [comment]
Fixed In Commit [f7f8d011871d36ed12c11e82f855ffdb65abccaf](https://github.com/oceanbase/odc-client/commit/f7f8d011871d36ed12c11e82f855ffdb65abccaf)
            ------
            xiaokang
            Wed May 29 14:58:29 2024 +0800
