### ISSUE TITLE
[Bug]: table with virtual columns cannot insert data

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#221]
### ODC version

ODC 420

### OB version

Any version of OceanBase

### What happened?

Virtual column fill or not fill, generate sql will have a value; Removing the value manually did not work
![image](https://github.com/oceanbase/odc/assets/46598871/1b79df87-dd04-4361-a3df-fe3eb6aaa8b3)
![image](https://github.com/oceanbase/odc/assets/46598871/1b5df3f3-6f0f-4ca6-8132-c7ccd09aab28)

### What did you expect to happen?

Don't need to insert data to the virtual columns

### How can we reproduce it (as minimally and precisely as possible)?

1.Create a table with virtual columns
2.Inserts a value into a virtual column

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/190697be-62f8-4af0-aaf4-a303a8ebf872)

PASS
