### ISSUE TITLE
[Bug]: data archiving fails in OBOracle when the 'update on duplicates' policy is selected

### ISSUE THREAD

**Issue by guowl3** [oceanbase/odc#2213]
### ODC version

4.2.4

### OB version

Unrelated to version.

### What happened?

data archiving fails in OBOracle when the 'update on duplicates' policy is selected

### What did you expect to happen?

In Oracle mode, data archiving operates correctly when the 'update on duplicates' policy is selected.

### How can we reproduce it (as minimally and precisely as possible)?

Create a task and select 'update on duplicates' policy.

**Comment by Huangxiao-mas** [comment]
test pass
