### ISSUE TITLE
[Bug]: full link trace is unavailable on OB 4.1.x

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#2218]
### ODC version

4.2.4

### OB version

4.1.x

### What happened?

Full link trace is unavailable on OB 4.1.x, sometimes it would return empty set.
And this would cause empty trace id.
![image](https://github.com/oceanbase/odc/assets/36879124/c48a8159-4796-4ca2-bd82-aea9b30dda5b)

### What did you expect to happen?

This should not be enabled on OB 4.1.x

### How can we reproduce it (as minimally and precisely as possible)?

Execute `show trace` on OB 4.1.x .

**Comment by Huangxiao-mas** [comment]
test pass
