### ISSUE TITLE
[Enhancement]: Optimize database object tree query performance

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#222]
### What would you like to be added?

Optimize database object tree query performance

### Why is this needed?

Compared with 4.1.x, 4.2.0 takes significantly more time to view the database objects.

**Comment by PeachThinking** [comment]
The reason is that every time a database object is viewed, the front end calls the interface to create a session, In some cases, the interface to create a session takes more time than viewing the database object.
