### ISSUE TITLE
[Bug]: error message of resource role permission is not readable

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2226]
### ODC version

4.2.4

### OB version

not related

### What happened?

1. create a new odc user
2. login odc based on this user
3. attempt visit a project that isn't belong to him/her
<img width="1415" alt="截屏2024-04-16 10 11 33" src="https://github.com/oceanbase/odc/assets/22992296/5779864b-a835-481c-b70f-5d8d357cc5f0">

as you can see, the error message is not readable.

### What did you expect to happen?

the error message of resource role permission should be readable~

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
<img width="738" alt="截屏2024-04-16 11 28 44" src="https://github.com/oceanbase/odc/assets/22992296/06b821dc-5112-43d2-a53f-8a72c2635b76">

fixed

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/a51e7a28-c3f4-473b-a0df-e01144214cd6)

PASS
