### ISSUE TITLE
[Bug]: Selecting multiple cells for table data editing. Right clicking only affects the current cell

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2238]
### ODC version

odc424

### OB version

*

### What happened?

If columns 2-9 are selected here, the behaviors of Set to null and Set as Default all affect single row data
![image](https://github.com/oceanbase/odc/assets/143492234/238aea7e-df85-42dd-99e1-2f3d091dd026)

### What did you expect to happen?

Change all selected columns

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [f7f8d011871d36ed12c11e82f855ffdb65abccaf](https://github.com/oceanbase/odc-client/commit/f7f8d011871d36ed12c11e82f855ffdb65abccaf)
            ------
            xiaokang
            Wed May 29 14:58:29 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/c6ecf80d-3089-49ce-8a2b-c460b7586fe7)
pass
