### ISSUE TITLE
[Bug]: Unable to open a table with uppercase names under a tenant lower_case_table_names=2

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2239]
### ODC version

ODC4.2.4-bp

### OB version

OBMysql lower_case_table_names=2

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/d1ce6963-5e55-4f6f-9b11-91d846b20b67)
Unable to open a table with uppercase names under a tenant lower_case_table_names=2.

### What did you expect to happen?

I can open tables with uppercase names.

### How can we reproduce it (as minimally and precisely as possible)?

Creates a table with uppercase names under the lower_case_table_names=2 tenant

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/c844ecaa-d95c-4db9-86dd-bc03c1765ed0)



![Image](https://github.com/oceanbase/odc/assets/40919496/2c9c6507-ea26-4bdf-8cbf-6bda10a47077)



![Image](https://github.com/oceanbase/odc/assets/40919496/0a738179-c1bb-40dc-808b-c48c6862a6e2)

Tables with lower_case_table_names=2 can be opened normally

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/8656733c-cd88-4e5f-802f-99149572b4fa)
