### ISSUE TITLE
[Bug]: The exportable list does not show packages that contain only package bodies

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#224]
### ODC version

ODC 4.2.0

### OB version

Any version of OceanBase

### What happened?

The package contains only the package body, the package is not displayed in the export list.Actual right-click can be exported successfully, the back-end has passed parameters, the front-end has not rendered.
![image](https://github.com/oceanbase/odc/assets/46598871/ea47b641-e735-4294-aa1b-192738ab1903)
![image](https://github.com/oceanbase/odc/assets/46598871/be3dafff-5773-4e2e-9933-5e394bae7534)

### What did you expect to happen?

Displays packages containing only package bodies in the export list.

### How can we reproduce it (as minimally and precisely as possible)?

1.Create a package that contains only the package body
2.Export the package

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/a7bba0ed-17d2-4835-8971-45db825397a9)

pass
