### ISSUE TITLE
[Bug]: Native oracle double-click to view synonyms reported an error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2243]
### ODC version

ODC424-bp1

### OB version

Oracle

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/6c3fdad8-f01b-4b37-b371-865a49c58ebd)
Native oracle double-click to view synonyms reported an error

### What did you expect to happen?

Double-click could view public synonyms.

### How can we reproduce it (as minimally and precisely as possible)?

Double-click to view public synonyms.

**Comment by HSunboy** [comment]
![Image](https://github.com/oceanbase/odc/assets/14886044/6f8a1f82-d441-4ae8-8b6f-3009f6247ffc)

`api/v1/synonym/list/`

**Comment by HSunboy** [comment]
Fixed In Commit [aa134fef34ddf68d81593de5c88a60ba9259568c](https://github.com/oceanbase/odc-client/commit/aa134fef34ddf68d81593de5c88a60ba9259568c)
            ------
            xiaokang
            Tue Apr 23 16:49:54 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b461b8e6-3177-49b1-b792-4a2f7bef4b06)

pass
