### ISSUE TITLE
[Bug]: Long time elapsed when querying big table(millions of rows) data, and crashed when click terminate

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#225]
### ODC version

4.2.0

### OB version

Not yet provided

### What happened?

Long time elapsed when querying big table(millions of rows) data, and crashed when click terminate.

### What did you expect to happen?

Silky smooth operation.

### How can we reproduce it (as minimally and precisely as possible)?

View a table with 10 million rows of data.

**Comment by PeachThinking** [comment]
the root cause is similar to ：https://github.com/oceanbase/odc/issues/573
