### ISSUE TITLE
[Bug]: When comparing, initiate structural synchronization without graying out

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2251]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/4868b00d-d967-42a4-8e40-21e0306f7adc)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/8098fc33-6a34-42d3-912e-1048eaf50374)

### How can we reproduce it (as minimally and precisely as possible)?

Perform structural comparison

**Comment by HSunboy** [comment]
Fixed In Commit [8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a](https://github.com/oceanbase/odc-client/commit/8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a)
            ------
            畅晚
            Wed Sep 11 10:00:03 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/d617878b-d071-4cd8-8caf-9c53c2a43546)
pass
