### ISSUE TITLE
[Bug]: failed to stop a executing sql

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2252]
### ODC version

4.2.4

### OB version

not related

### What happened?

1. switch off 'stop when error':
<img width="506" alt="截屏2024-04-18 16 10 58" src="https://github.com/oceanbase/odc/assets/22992296/8cd3cb6b-55db-4787-8580-76984eaf6934">

2. execute such sqls:
<img width="547" alt="截屏2024-04-18 16 11 31" src="https://github.com/oceanbase/odc/assets/22992296/360691f4-b933-4312-9449-47a8e0958b0c">

3. execute these sqls and kill query
<img width="909" alt="截屏2024-04-18 16 12 10" src="https://github.com/oceanbase/odc/assets/22992296/1787a880-0c5f-48ba-88e1-521729ca6210">

as you can see, I just interrupt the first sql and the remaining sql is still executed which is not expected.

### What did you expect to happen?

I can interrupt all execution.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/2cea18cc-9234-4416-9b1e-eaaaacde3c1c)


pass
