### ISSUE TITLE
[Bug]: Cannot access SQL console when using both OAuth and bastion integration

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#2254]
### ODC version

4.2.4

### OB version

~

### What happened?

When I using OAuth for account integration, then I can not use bastion integration to access a temp SQL console.

### What did you expect to happen?

Access a temp SQL console using bastion integration.

### How can we reproduce it (as minimally and precisely as possible)?

~

**Comment by Huangxiao-mas** [comment]
test pass
