### ISSUE TITLE
[Bug]: The user name of the multi-cloud connection string using Intelligent analysis is incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2256]
### ODC version

ODC 4.2.4-bp1

### OB version

OBCloud

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/7d2e1a6b-2039-4885-a638-4768cea9617f)
The intelligent user name does not contain the content after "@".

### What did you expect to happen?

The intelligent user name contains the content after "@".
### How can we reproduce it (as minimally and precisely as possible)?

Connect multi-cloud connection strings and perform intelligent parsing.

**Comment by HSunboy** [comment]
Fixed In Commit [4fc8134e901c6c6a020f2d9703b68757b9cd8217](https://github.com/oceanbase/odc-client/commit/4fc8134e901c6c6a020f2d9703b68757b9cd8217)
            ------
            xiaokang
            Tue Apr 23 16:35:21 2024 +0800

**Comment by tonghan-gsh** [comment]
pass
