### ISSUE TITLE
[Bug]: csrf token returns everywhere

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2263]
### ODC version

4.2.4

### OB version

not related

### What happened?

clear all cookies and visit any api that need login 

<img width="928" alt="截屏2024-04-19 15 30 40" src="https://github.com/oceanbase/odc/assets/22992296/fca1c711-ee76-4403-8ee4-439edc6b49f0">

as you can see, the api returns a xsrf token which is not expected~

### What did you expect to happen?

we expect that only login and csrf token api can return this token

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yizhouxw** [comment]
'returns everywhere' was expected, we use cookie based csrf token repository.
the real problem was API csrfToken does not resutn xsrf token in cookie, fixed in odc v4.2.4bp2.
