### ISSUE TITLE
[Bug]: Mouse cannot hover and copy content in session management

### ISSUE THREAD

**Issue by xsssssc** [oceanbase/odc#2264]
### ODC version

424

### OB version

421

### What happened?

![22137147-12FE-4765-A1E4-D95BFDB39C8C](https://github.com/oceanbase/odc/assets/144298859/6debde82-28fa-414f-b801-cf75c3f4449c)

### What did you expect to happen?

Mouse can hover and copy content in session management

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened

**Comment by HSunboy** [comment]
Fixed In Commit [f7f8d011871d36ed12c11e82f855ffdb65abccaf](https://github.com/oceanbase/odc-client/commit/f7f8d011871d36ed12c11e82f855ffdb65abccaf)
            ------
            xiaokang
            Wed May 29 14:58:29 2024 +0800
