### ISSUE TITLE
[Bug]: Failed to terminate pending task

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2265]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/6bfc8d98-d203-4c50-a189-db1fd175b45d)

### What did you expect to happen?

Termination successful

### How can we reproduce it (as minimally and precisely as possible)?

Terminate pending tasks

**Comment by krihy** [comment]
fix pr [https://github.com/oceanbase/odc/pull/2272](url)

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/9330534f-906a-44bb-84fe-113af0fe683c)
pass
