### ISSUE TITLE
[Bug]: If the user joins a project that has been archived, deleting the user fails

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2284]
### ODC version

ODC 4.2.4-bp1

### OB version

-

### What happened?

If the user joins a project that has been archived, deleting the user fails.
PS: Only when the user is the administrator/DBA of the project will it not be deleted.

### What did you expect to happen?

The user can be successfully deleted.

### How can we reproduce it (as minimally and precisely as possible)?

1. Add a user to a project
2. Archive the project
3. Delete the user

**Comment by yiminpeng** [comment]
PS: Only when the user is the administrator/DBA of the project will it not be deleted.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ada49848-d8e6-4031-97ac-11470ff73859)

pass
