### ISSUE TITLE
[Bug]: An error occurs when the partition plan is delivered using a version earlier than ob3.x

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2285]
### ODC version

ODC 4.2.4-bp1

### OB version

OB 1479，ob2.x

### What happened?

An error occurs when the partition plan is delivered using a version earlier than ob3.x
![image](https://github.com/oceanbase/odc/assets/46598871/00f7e8b2-ec3a-4822-81ca-19c33cb3a998)

### What did you expect to happen?

The partition plan task is successfully delivered. 

### How can we reproduce it (as minimally and precisely as possible)?

Use OB1479 and OB2.x versions to deliver partition plan tasks.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/cc2a24c4-83a2-4a24-9afd-57a7ad08d823)

pass
