### ISSUE TITLE
[Bug]: In the English interface for creating a partition plan, the interval value is covered by the horizontal scroll bar and cannot be filled in.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2286]
### ODC version

ODC424bp

### OB version

independent

### What happened?

In the English interface for creating a partition plan, the interval value is covered by the horizontal scroll bar and cannot be filled in.
![image](https://github.com/oceanbase/odc/assets/59468957/79858cd0-84d4-45f2-9cff-4e988645eab6)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b0bc58cc-472f-4a16-9f5c-0237221e94e4)

The problem still exists
