### ISSUE TITLE
[Bug]: Personal space is restricted and can still be accessed

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#2290]
### ODC version

4.2.3

### OB version

.

### What happened?

After the `OceanbaseFullAccess` permission is introduced, personal space is restricted and can still be accessed

### What did you expect to happen?

If the personal space is restricted, you cannot access it.

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by MarkPotato777** [comment]
It is an ODC cloud issue, please close it in github.
