### ISSUE TITLE
[Bug]: The command line window displays an incorrect sql file that is too long

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2301]
### ODC version

ODC 4.2.4-bp

### OB version

-

### What happened?

Typing too long sql in the command-line window does not display correctly.
![image](https://github.com/oceanbase/odc/assets/46598871/0097a741-4447-43f5-a627-5577aeef11a6)

### What did you expect to happen?

Typing long sql in a command-line window displays correctly.

### How can we reproduce it (as minimally and precisely as possible)?

Enter the following sql in the command line window.
```
SELECT TENANT_ID, TENANT_NAME, TENANT_ROLE, STATUS, SWITCHOVER_STATUS, SYNC_SCN, REPLAYABLE_SCN,READABLE_SCN, RECOVERY_UNTIL_SCN FROM oceanbase.DBA_OB_TENANTS where tenant_type<>'META';
```

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/ec33932d-27f8-4046-b3f8-ed4b49907f58)

**Comment by LuckyPickleZZ** [comment]
The `\r` is a character directly returned by the obclient, we are currently unable to process it.

![image](https://github.com/oceanbase/odc/assets/36879124/76b5c02e-d736-4121-b2d0-d46ec03e692f)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/73077b75-81fc-4169-a85a-fd9ceeafba7f)

pass
