### ISSUE TITLE
[Bug]: failed to cancel a task

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2306]
### ODC version

4.2.4

### OB version

not related

### What happened?

1. startup a task
2. try to cancel it
3. exception is thrown
![cb8fda496205cca274167306ba39f3c0](https://github.com/oceanbase/odc/assets/22992296/e8c05cfb-6d47-42b5-9dcc-4cd6c8d58b02)

### What did you expect to happen?

cancel it successfully~

### How can we reproduce it (as minimally and precisely as possible)?

difficult to reproduce it~

**Comment by yhilmare** [comment]
we add too much logic in cancel method which may cost too much time:

![截屏2024-04-29 19 20 05](https://github.com/oceanbase/odc/assets/22992296/e8a7dff8-39bf-48c2-9c40-c4a616c60ab9)

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/e94dfc80-4923-4c5c-9387-901be7d79b61)

pass
