### ISSUE TITLE
[Bug]: After the upgrade, historical partition plan tasks do not display the content of the partition policy

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2310]
### ODC version

ODC4.2.4-bp1

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/15fc2c15-22b9-42de-9dc0-2d97429319ba)
After the upgrade, historical partition plan tasks do not display the content of the partition policy.

### What did you expect to happen?

The content of the partition policy must also be displayed after the upgrade.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver partition plan tasks, upgrade ODC, and view partition plan details.

**Comment by HSunboy** [comment]
partitionkey cannot be null
