### ISSUE TITLE
[Bug]: shortcut keys do not work

### ISSUE THREAD

**Issue by guowl3** [oceanbase/odc#2311]
### ODC version

4.2.4bp1

### OB version

any version

### What happened?

shortcut keys do not work
![image](https://github.com/oceanbase/odc/assets/70270140/c5bb351a-4738-435c-a0c2-b0ac4dfb03f3)

### What did you expect to happen?

Shortcut keys are effective

### How can we reproduce it (as minimally and precisely as possible)?

Use Ctrl + Enter as a shortcut key

**Comment by HSunboy** [comment]
duplicate with https://github.com/oceanbase/odc/issues/2312
