### ISSUE TITLE
[Bug]: No table is displayed for the partition plan delivered using OB version 1479

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2321]
### ODC version

ODC 4.2.4-bp1

### OB version

OB 1.4.79

### What happened?

No table is displayed when the partition plan is delivered.
![image](https://github.com/oceanbase/odc/assets/46598871/0f8a4a92-c778-41d4-9549-3b8ab38eef34)

### What did you expect to happen?

Can be delivered successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Use ob 1.4.79 to deliver a partition plan task.

**Comment by yhilmare** [comment]
odc needs tenant name to query all partition info but it gives a null tenant name:

![截屏2024-05-07 10 47 31](https://github.com/oceanbase/odc/assets/22992296/7b0402e2-da90-4085-98dc-dfc946609ae8)

**Comment by yhilmare** [comment]
fixed:
<img width="891" alt="截屏2024-05-07 14 01 34" src="https://github.com/oceanbase/odc/assets/22992296/2f313f40-ea3d-4fd9-bb63-77f23d4ef51a">

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/ce51d32c-3f6e-4ecc-8ace-90eb9326576f)
pass
