### ISSUE TITLE
[Bug]: quartz job is deleted when osc job with database not exist

### ISSUE THREAD

**Issue by krihy** [oceanbase/odc#2322]
### ODC version

4.2.4bp2

### OB version

any

### What happened?

 quartz job is deleted when submit osc job with database id is not exists

### What did you expect to happen?

osc job execute normal

### How can we reproduce it (as minimally and precisely as possible)?

submit a osc job

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/dd612c9d-36ae-4ad7-978b-9e60eb054c9c)
pass
