### ISSUE TITLE
[Bug]: ODC v4.2.4 cannot connect to ODP Sharding 

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#2337]
### ODC version

4.2.4

### OB version

not related

### What happened?

ODC v4.2.4 cannot connect to ODP Sharding, ODC v4.2.3 is okay.

### What did you expect to happen?

ODC v4.2.4 can connect to ODP Sharding 

### How can we reproduce it (as minimally and precisely as possible)?

create a ODP Sharding datasource,
try connect.

**Comment by Huangxiao-mas** [comment]
test pass
