### ISSUE TITLE
[Bug]: fail to export result set for sql with * and nvl function

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#2343]
### ODC version

4.2.4

### OB version

4.2.x oboracle

### What happened?

When export result set for sql with * and nvl function like `select *, nvl(1,0) from whatever_tbl`, it would fail.
This is because ODC would rewrite table to add `select * from (xxx) fetch first x rows only` statement on the sql.
It may cause ` invalid SQL statement` error.
![image](https://github.com/oceanbase/odc/assets/36879124/85f15ebd-042e-4bbe-9272-20454e5359be)

### What did you expect to happen?

do not rewrite user's sql

### How can we reproduce it (as minimally and precisely as possible)?

-

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/de167b6c-83bc-4e8f-8ba0-c0dc382066c3)
![Image](https://github.com/user-attachments/assets/fe71c0d8-860b-4fc8-b839-9270e8a20ce4)
pass
