### ISSUE TITLE
[Bug]: The parentheses for database changes are in English

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2345]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/7aad968e-0479-48fb-89de-6b612ec804f0)

### What did you expect to happen?

Brackets in Chinese

### How can we reproduce it (as minimally and precisely as possible)?

Execute database changes

**Comment by yhilmare** [comment]
this bug is involved by this pr #1941

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/baf54c8e-88b0-4234-9be4-6d1c948e999c)

pass

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/efda62da-3242-4194-8bbe-64640d11ddcd)

PASS
