### ISSUE TITLE
[Bug]: Remove permission request from Personal Space task list

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2364]
### ODC version

ODC 424-bp1

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/3749ae75-babc-4a95-8c3f-9d2a3dc1a478)

### What did you expect to happen?

Remove permission request from Personal Space task list

### How can we reproduce it (as minimally and precisely as possible)?

Enter Personal Space to view the task list

**Comment by HSunboy** [comment]
Fixed In Commit [2cfbb4684d8b7bae190ab9e76d551c9a1ebe60fe](https://github.com/oceanbase/odc-client/commit/2cfbb4684d8b7bae190ab9e76d551c9a1ebe60fe)
            ------
            xiaokang
            Mon May 13 10:35:10 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/86cbc5e8-34fe-4d05-bbd7-23cf311005cb)

pass
