### ISSUE TITLE
[Bug]: Oracle mode batch compilation function, the interface reports 'message=stateId'

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2366]
### ODC version

ODC424bp2

### OB version

Oracle4215

### What happened?

Oracle mode batch compilation function, the interface reports 'message=stateId'
![image](https://github.com/oceanbase/odc/assets/59468957/851e7603-5fd9-4422-8544-3d90314495cc)

### What did you expect to happen?

can do it

### How can we reproduce it (as minimally and precisely as possible)?

chat privately
project: tonghan
  oracle4215: GSH

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1ab0d737-9268-4387-aa75-f638e8d0ba7e)

pass
