### ISSUE TITLE
[Bug]: csrf prevension intercept basic authentication request

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#2367]
### ODC version

4.2.4

### OB version

not related

### What happened?

csrf prevension intercept basic authentication request

### What did you expect to happen?

csrf prevension should not intercept basic authentication request

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/54161870/28d5b1ef-2e49-4eca-acb1-a28142a5f5c0)

**Comment by Huangxiao-mas** [comment]
test pass
