### ISSUE TITLE
[Bug]: fail to decrypt password

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#2368]
### ODC version

4.2.4

### OB version

no

### What happened?

fail to decrypt password,log:
[com.oceanbase.odc.service.encryption.SensitivePropertyHandlerImpl][137]: Failed to decrypt sensitive property, [org.springframework.web.servlet.handler.AbstractHandlerExceptionResolver][208]: Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Unable to invoke Cipher due to illegal block size; nested exception is com.fasterxml.jackson.databind.JsonMappingException: Unable to invoke Cipher due to illegal block size (through reference chain: 

### What did you expect to happen?

decrypt password success

### How can we reproduce it (as minimally and precisely as possible)?

Concurrent decryption password

**Comment by Huangxiao-mas** [comment]
test pass
