### ISSUE TITLE
[Bug]: Set scheduled tasks within data cleaning to not display specific execution times

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2369]
### ODC version

odc424

### OB version

*

### What happened?

Create a scheduled task, the task details do not show the scheduled execution time
![image](https://github.com/oceanbase/odc/assets/143492234/46fd06b1-baa9-408f-9657-530ccc0e4be2)

### What did you expect to happen?

can display the execute time

### How can we reproduce it (as minimally and precisely as possible)?

Create a scheduled task

**Comment by HSunboy** [comment]
Fixed In Commit [9e997860475545af0e4b0a6c6bdd568eacf725fa](https://github.com/oceanbase/odc-client/commit/9e997860475545af0e4b0a6c6bdd568eacf725fa)
            ------
            畅晚
            Mon May 13 18:02:17 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8259d3db-ea45-4512-a131-76cb9a99aa47)

pass
