### ISSUE TITLE
[Bug]: MySQL mode Export then Import null Timestamp value result into query error

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#2375]
### ODC version

4.2.x

### OB version

not related

### What happened?

MySQL mode Export then Import null Timestamp value result into query error

![image](https://github.com/oceanbase/odc/assets/54161870/1263f5c8-514d-4716-ab49-268d2df2bab6)

check the imported value, it is not null, but '1970-01-01 00:00:00', which is an invalid timestamp value
![image](https://github.com/oceanbase/odc/assets/54161870/87e621f0-e0f6-4902-8524-75db414836ab)

### What did you expect to happen?

MySQL mode Export then Import null Timestamp value result should keep null value 

### How can we reproduce it (as minimally and precisely as possible)?

see What happended

### Anything else we need to know?

origin from ask oceanbase: https://ask.oceanbase.com/t/topic/35608139/7

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/563304d9-0569-4b3b-be5f-b0fa48022b2c)

When exporting and importing Timestamp time types with null values, null is displayed normally
