### ISSUE TITLE
[Bug]: ODP intelligently parses the connection string, and the user name does not include the tenant name.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2384]
### ODC version

ODC424bp2

### OB version

independent

### What happened?

ODP intelligently parses the connection string, and the user name does not include the tenant name.

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Fixed In Commit [3e634447c8cf794bcebee66603d3c058f98bc030](https://github.com/oceanbase/odc-client/commit/3e634447c8cf794bcebee66603d3c058f98bc030)
            ------
            xiaokang
            Tue May 14 16:11:12 2024 +0800
