### ISSUE TITLE
[Bug]: The project owner and users with approvable permissions cannot terminate the task

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2387]
### ODC version

ODC 424-bp1

### OB version

~

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/6937a049-3581-4926-b05a-1d66639b56c2)
The project owner and users with approvable permissions cannot terminate the task.

### What did you expect to happen?

The project owner and users with approvable permissions can terminate the task.

### How can we reproduce it (as minimally and precisely as possible)?

The developer of the project executes a task and terminates it using the project owner.

**Comment by yhilmare** [comment]
the back end has already supported this feature, the only thing we need to do is adding a button 'abort' for project owner @HSunboy

**Comment by HSunboy** [comment]
Fixed In Commit [a380e82977f3e873950e15cc9d885026b7e4d8b2](https://github.com/oceanbase/odc-client/commit/a380e82977f3e873950e15cc9d885026b7e4d8b2)
            ------
            畅晚
            Fri Jun 7 16:21:43 2024 +0800

**Comment by qymsummer** [comment]
When the user has a single role, there is a termination button. If the user has multiple roles, there is no termination button.

**Comment by HSunboy** [comment]
Fixed In Commit [efa7991f25303ecc7dfeaeb300c2cc8722c7913f](https://github.com/oceanbase/odc-client/commit/efa7991f25303ecc7dfeaeb300c2cc8722c7913f)
            ------
            畅晚
            Tue Jun 11 15:39:43 2024 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/a220fe1e-6bb6-48f7-a427-cfd8c4f7022d)

pass
