### ISSUE TITLE
[Bug]: Roles do not take effect for the user's view-only rights

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#239]
### ODC version

ODC 4.2.0

### OB version

Any version of OceanBase

### What happened?

The role of the user has the view-only permission can not view the user. Users can only be seen if they have administrative rights
![image](https://github.com/oceanbase/odc/assets/46598871/2d68a01c-927e-47fb-b8bd-6f46c35ac85c)
![image](https://github.com/oceanbase/odc/assets/46598871/07287b7e-80ab-45cb-9a02-5ac042e9e1e0)

### What did you expect to happen?

If you have the view-only permission of a user, you can view the user.

### How can we reproduce it (as minimally and precisely as possible)?

1.Create a role that has view-only rights for users
2.Log in with a user who has this role
3.View user

**Comment by HSunboy** [comment]
Fixed In Commit [d159ed302f3b0dc56ea571c7166e65cf8a72ae94](https://github.com/oceanbase/odc-client/commit/d159ed302f3b0dc56ea571c7166e65cf8a72ae94)
            ------
            咏和
            Sun Dec 10 10:59:51 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f6847234-5389-468c-8b02-8e54f9735858)

PASS
