### ISSUE TITLE
[Bug]: failed to call dbms package in oracle mode

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2391]
### ODC version

4.2.4

### OB version

not related

### What happened?

type a dbms calling statement and execute it:
<img width="1104" alt="截屏2024-05-15 11 25 58" src="https://github.com/oceanbase/odc/assets/22992296/442d5a77-bf47-4b5a-b419-8cf84e3914c6">

### What did you expect to happen?

the package starts with dbms is the internal package in oracle mode, we shouldn't stop them~ and there no work around method to execute them.

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened~

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3061761a-046f-488e-a7ab-2a9d78c969a9)

pass
