### ISSUE TITLE
[Bug]: Desktop version right click database has scheduled tasks

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2394]
### ODC version

odc424

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/dae9dd69-5b3a-4f0d-afd9-0ab4501ee62b)

### What did you expect to happen?

Desktop version does not have scheduled tasks

### How can we reproduce it (as minimally and precisely as possible)?

Desktop version right-click database

**Comment by HSunboy** [comment]
Fixed In Commit [32f81a2f7dfcb38dcd3bd242fdb2260c878217a9](https://github.com/oceanbase/odc-client/commit/32f81a2f7dfcb38dcd3bd242fdb2260c878217a9)
            ------
            畅晚
            Wed May 29 09:54:15 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f0ce1f16-56ef-4f44-b910-1c92d313aa20)

pass
