### ISSUE TITLE
[Bug]: When the result set is filtered, the column mode shows incorrect data

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#24]
**Describe the bug**
When the result set is filtered, the column mode shows incorrect data

**Environment**

  
- Component Version: ODC 4.1.2

**Fast Reproduce Steps(Required)**

original resultset：
<img width="452" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/d3c78cec-e443-4afc-9d00-6e370968f9f8">
Conditionally filter the result set：
<img width="417" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/9c0454a0-1b60-4d0a-a0ff-5d44c3f88eb2">
column mode show data error：
<img width="924" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/9c60980b-c428-4360-b3d8-0f0562dce6f3">

**Expected behavior**
column mode show result set data correctly.

**Actual Behavior**

**Additional context**

**Comment by HSunboy** [comment]
Fixed

**Comment by runzi389205** [comment]
pass
![Image](https://github.com/oceanbase/odc/assets/141202865/56ffcdd2-9f78-4d85-b3cf-8dee96090db7)
