### ISSUE TITLE
[Bug]: Create a function return type add a sys_refcursor type drop-down options

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#240]
### ODC version

ODC 4.2.0

### OB version

Any version of OceanBase

### What happened?

Function now supports sys_refcursor return type
![image](https://github.com/oceanbase/odc/assets/46598871/94410dab-a7c1-4e44-ad4a-5e6e4b651217)

### What did you expect to happen?

Added sys_refcursor type option

### How can we reproduce it (as minimally and precisely as possible)?

create function and return type is sys_refcursor

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3d9219d8-57e8-4b99-9e96-96926afeb891)

pass
