### ISSUE TITLE
[Bug]: The database under the project does not display the data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2406]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/a5df383e-cb43-4912-b44e-40da68f95e8a)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/863e7b93-0ac8-4836-b830-a09dc3af4765)

### How can we reproduce it (as minimally and precisely as possible)?

Open the search box within the project and click on all databases

**Comment by HSunboy** [comment]
Fixed In Commit [d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0](https://github.com/oceanbase/odc-client/commit/d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0)
            ------
            畅晚
            Thu May 23 09:58:17 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/e553e2d9-3974-49a6-b878-b69d6b88d3eb)
pass
