### ISSUE TITLE
[Bug]: Display the data source when opening the search box to view the database within the data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2407]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/7abe4231-1a89-4f95-9aaa-99a5e7de399a)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/8f17c50a-48ff-40fa-9436-95116d4e5acf)

### How can we reproduce it (as minimally and precisely as possible)?

Open the search box in the data source and click on all databases

**Comment by HSunboy** [comment]
Fixed In Commit [d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0](https://github.com/oceanbase/odc-client/commit/d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0)
            ------
            畅晚
            Thu May 23 09:58:17 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/878074ba-f56f-42a9-b1af-a1e25e174858)
pass
