### ISSUE TITLE
[Bug]: Unable to apply for project permissions

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2409]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/a575eb06-b4e7-4ac6-9413-c16eea3ae4b7)

### What did you expect to happen?

Can apply for

### How can we reproduce it (as minimally and precisely as possible)?

Apply for project permissions

**Comment by smallsheeeep** [comment]
The problem occurs when there is some error of deployment environment. Please re-deploy and retry.
