### ISSUE TITLE
[Bug]: Global search without table permissions, no request for table permissions button

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2410]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/35b526a4-36e2-40d6-a41c-130d9d6217e7)

### What did you expect to happen?

Application form permission button exists

### How can we reproduce it (as minimally and precisely as possible)?

Search tables in databases without permission

**Comment by HSunboy** [comment]
Fixed In Commit [d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0](https://github.com/oceanbase/odc-client/commit/d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0)
            ------
            畅晚
            Thu May 23 09:58:17 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/b569f6bb-60b0-4d39-b5d1-a782a9b1bc97)
pass
