### ISSUE TITLE
[Bug]: Inconsistency between Oracle keyword search and design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2414]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/d5b515ef-6fca-46a2-83a8-7e3210041992)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/9d159311-d747-4753-8c78-8dd112b64019)

### How can we reproduce it (as minimally and precisely as possible)?

Select a database for keyword search

**Comment by HSunboy** [comment]
Fixed In Commit [d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0](https://github.com/oceanbase/odc-client/commit/d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0)
            ------
            畅晚
            Thu May 23 09:58:17 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/4a16e043-6b47-461d-894e-84a28f720791)
Unchanged

**Comment by HSunboy** [comment]
Fixed In Commit [e5538d5d1f305c5599dae9f992ab086aae6a13d5](https://github.com/oceanbase/odc-client/commit/e5538d5d1f305c5599dae9f992ab086aae6a13d5)
            ------
            畅晚
            Thu May 30 09:33:28 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/4f03b0c3-09bc-4d82-ae5b-3ab71a4ead4d)
pass
