### ISSUE TITLE
[Bug]: Clicking to locate within SQL window cannot take effect

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2415]
### ODC version

odc430

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/cbf9ce02-414b-448e-8085-29f05114f009

### What did you expect to happen?

Click to locate and automatically jump to the link

### How can we reproduce it (as minimally and precisely as possible)?

1. Enter the link and open the SQL window
2. Exit link, click to locate

**Comment by HSunboy** [comment]
Fixed In Commit [2546a1d6597cde4d2ead58e57e90c24a3471701d](https://github.com/oceanbase/odc-client/commit/2546a1d6597cde4d2ead58e57e90c24a3471701d)
            ------
            畅晚
            Mon May 27 16:36:08 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/fa75c309-8b3e-49d7-8af5-29341e464975)

pass
