### ISSUE TITLE
[Bug]: failed to set nls parameter by execution sql for native oracle

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2421]
### ODC version

4.2.4

### OB version

not related

### What happened?

execute `alter session set nls_date_format='yyyy-mm-dd hh24:mi:ss'` in odc and query a table which contains date column.

and the date column is not formatted as expected:
<img width="461" alt="截屏2024-05-17 14 46 02" src="https://github.com/oceanbase/odc/assets/22992296/b136af1a-686a-485f-9508-8c849f02be4d">
  

### What did you expect to happen?

format the date column by 'yyyy-mm-dd hh24:mi:ss'

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e5e8b353-69b7-4e5f-ad23-6f035a427dd5)

pass
