### ISSUE TITLE
[Bug]: failed to dump data on standby ob cluster

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2429]
### ODC version

4.2.4

### OB version

not related

### What happened?

there is a standby cluster and I set weak read in session init script, I can execute sql in sql-console normally but I can not dump data.

### What did you expect to happen?

I can dump data normally

### How can we reproduce it (as minimally and precisely as possible)?

find a standby cluster and dump data on it.

**Comment by Huangxiao-mas** [comment]
pass
