### ISSUE TITLE
[Bug]: Display garbled characters when the table name is in Chinese

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2437]
### ODC version

odc430

### OB version

ob4215

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/92a82cd6-ce0c-44af-bc65-2209a51d75e8)

### What did you expect to happen?

Table names are not garbled

### How can we reproduce it (as minimally and precisely as possible)?

Create a Chinese table
CREATE TABLE "创建sql计划1" (
  "col1" NUMBER(*,0),
  "col2" VARCHAR2(120)
)
View Table Details

**Comment by yhilmare** [comment]
It looks like a kernel problem: I use `show create table xxx` and I get a normal result, I use `dbms_metadata.get_ddl` and I get a result with garbled characters:

![截屏2024-06-03 18 06 03](https://github.com/oceanbase/odc/assets/22992296/013619b3-8762-4efa-a68d-5f4a6fa0cceb)

every thing looks good if I change another ob-oracle env:

<img width="1068" alt="截屏2024-06-03 18 07 21" src="https://github.com/oceanbase/odc/assets/22992296/38658271-89fe-4d8a-93be-82d0673a699d">

**Comment by tonghan-gsh** [comment]
The ob4218 version solves this problem
