### ISSUE TITLE
[Bug]: getting table details cost too much time

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2440]
### ODC version

4.2.4

### OB version

4.2.15

### What happened?

1. create a table which is big:
<img width="183" alt="截屏2024-05-21 11 38 09" src="https://github.com/oceanbase/odc/assets/22992296/975c70b4-a359-42ac-aee4-1ea75414221c">

2. double click this table and cost too much time to get the result:
![截屏2024-05-21 11 44 25](https://github.com/oceanbase/odc/assets/22992296/a6a17f01-9f7a-497e-972b-06e7aa2866bc)

### What did you expect to happen?

I test the query sql of this table, such as ddl's query sql, column's query sql and etc. any of these sql does not cost too much time.

I expect that I can get this table' detail immediately, 20s+ so long that exceed that max api's timeout 

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened', you can ask @yhilmare to get the test ddl~

**Comment by yhilmare** [comment]
the root cause of this issue is that:
1. the sql is too big and the sql parser cost too much time to parse(about 3000ms). It is difficult to optimize it.
![截屏2024-05-21 11 49 11](https://github.com/oceanbase/odc/assets/22992296/ef769385-ad5a-44bd-9c83-9d44d24cc82a)

as you can see: getting columns, getting indexes and getting options cost too much time but the query sql of them doesn't cost so much time, the reason is that we parse it separately but don't reuse the parse results.

we should add a cache in db-browser~

**Comment by yhilmare** [comment]
<img width="832" alt="截屏2024-06-03 21 29 53" src="https://github.com/oceanbase/odc/assets/22992296/1bedc9fb-54bb-49d7-8df4-9624be4dca8f">

fixed

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4c5c77a8-88b9-42ef-8912-b26b029e765a)

pass
