### ISSUE TITLE
[Bug]: Unclear viewing in global search dark mode

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2447]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/0cb4d90a-54d3-46bc-90ea-d8a9ac499a35)
![image](https://github.com/oceanbase/odc/assets/143492234/dcaa72cd-ee59-4a54-90ef-66d67c428a25)
![image](https://github.com/oceanbase/odc/assets/143492234/0e40d9e2-3b57-4a1b-9968-7161bda7046a)

### What did you expect to happen?

Should be white

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0](https://github.com/oceanbase/odc-client/commit/d35bc4e7ac6ea2e3b751a8393690ab6f43d98dd0)
            ------
            畅晚
            Thu May 23 09:58:17 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/1c0b932f-1887-4734-9c8a-8e5f64669bb0)
![image](https://github.com/oceanbase/odc/assets/143492234/15c11c22-098c-4992-ba6f-338fb02ac379)
pass
