### ISSUE TITLE
[Enhancement]: Exposing open source repository information in the interactive user interface

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#2451]
### What would you like to be added?

1. Add GitHub issue link in [Feedback].
2. After a period of use, users are guided to the GitHub repository by a pop-up window to rate the ODC product.

### Why is this needed?

Direct users' attention to ODC open source projects and increase community activity.

**Comment by HSunboy** [comment]
Fixed In Commit [1d728663a539209034c47048896039a33abdf8f9](https://github.com/oceanbase/odc-client/commit/1d728663a539209034c47048896039a33abdf8f9)
            ------
            之瑛
            Tue Aug 6 14:18:14 2024 +0800
