### ISSUE TITLE
[Bug]: DLM task, source table cleanup has no execution details

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2459]
### ODC version

ODC430

### OB version

Oceanbase430

### What happened?

DLM task, source table cleanup has no execution details
![image](https://github.com/oceanbase/odc/assets/59468957/cdff7160-8382-443a-b771-ed68b0dc7cc3)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [70bbe4a5acc08abc46c281f135c63d06df2d4995](https://github.com/oceanbase/odc-client/commit/70bbe4a5acc08abc46c281f135c63d06df2d4995)
            ------
            畅晚
            Thu May 23 15:42:08 2024 +0800
