### ISSUE TITLE
[Bug]: When creating a DLM table, the table structure synchronization task is not enabled. The task details show that the table structure synchronization is enabled by default.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2461]
### ODC version

ODC430

### OB version

Oceanbase430

### What happened?

When creating a DLM table, the table structure synchronization task is not enabled. The task details show that the table structure synchronization is enabled by default.
![image](https://github.com/oceanbase/odc/assets/59468957/8c4baf9e-4fed-4cfc-bf2e-30ec010ef3c0)
![image](https://github.com/oceanbase/odc/assets/59468957/542b63a7-b24b-4c26-867e-d77376d53504)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a table structure synchronization task without enabling it
2. View task details after creation is complete

**Comment by HSunboy** [comment]
Fixed In Commit [fb421a7aef014523b01e66fbc0b9c6b0c88d9922](https://github.com/oceanbase/odc-client/commit/fb421a7aef014523b01e66fbc0b9c6b0c88d9922)
            ------
            畅晚
            Mon May 27 16:36:22 2024 +0800
