### ISSUE TITLE
[Bug]: Unable to issue a multi-database change task from a multi-selected database in a project

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2466]
### ODC version

ODC 430

### OB version

No related

### What happened?

Unable to issue a multi-database change task from a multi-selected database in a project
![image](https://github.com/oceanbase/odc/assets/46598871/14b93149-ebb7-4e4f-b991-520b0aa216bd)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/5f38fbd4-fe93-4c1b-b8e0-fc6aa4e3e610)

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by HSunboy** [comment]
Fixed In Commit [2e0ee283794f9f5f4ec6bfb890054c4fd7f3eb7b](https://github.com/oceanbase/odc-client/commit/2e0ee283794f9f5f4ec6bfb890054c4fd7f3eb7b)
            ------
            陈朝俊
            Sat May 25 21:16:30 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/45af6e0b-39d9-4f46-a862-31a48cc3a0db)

pass
