### ISSUE TITLE
[Bug]: The sql check result of multi-database change is missing

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2470]
### ODC version

ODC430

### OB version

No related

### What happened?

The sql check ‘the initial value of the auto-increment column’ is not matched when the ‘create  table gsh.ttt(a int)’ statement is executed
![image](https://github.com/oceanbase/odc/assets/46598871/82160365-bdff-4c22-9047-855f87edfd81)
Executing in the sql window matches the sql check
![image](https://github.com/oceanbase/odc/assets/46598871/d450c406-e532-4291-8833-b7305acbc188)

### What did you expect to happen?

Multi-database changes accurately match sqlcheck

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/bfcbf2ef-1506-4d3b-a9f6-df83d60a9332)

pass
