### ISSUE TITLE
[Bug]: The multi-database change highlight block is not synchronized

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2471]
### ODC version

ODC430

### OB version

No related

### What happened?

The multi-database change highlight block is not synchronized
![image](https://github.com/oceanbase/odc/assets/46598871/d7b6f823-1a09-40b5-b82d-9f4abc6e2e89)

### What did you expect to happen?

The multi-database change highlights are synchronized with the corresponding content

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by HSunboy** [comment]
Fixed In Commit [2e0ee283794f9f5f4ec6bfb890054c4fd7f3eb7b](https://github.com/oceanbase/odc-client/commit/2e0ee283794f9f5f4ec6bfb890054c4fd7f3eb7b)
            ------
            陈朝俊
            Sat May 25 21:16:30 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b9c26dad-b72c-41fc-9f08-90cad833b55a)

pass
