### ISSUE TITLE
[Bug]: Structure Comparison  task failed when source table contains spatial type column.

### ISSUE THREAD

**Issue by kiko-art** [oceanbase/odc#2475]
### ODC version

dev/4.3.0

### OB version

Oceanbase oracle420

### What happened?

Structure Comparison  task failed when source table contains spatial type column, the create target table sql is wrong.

![L1VzZXJzL2Z1eml5YW4vTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L2lEaW5nVGFsay80NDE3NzQ0OTQ2X3YyL0ltYWdlRmlsZXMvMTcxNjM3NjAxMDU5M180MTI5QzA1RC01QTBFLTRGRTQtQUZGNC00NzcwOTM5QUU4REMucG5n](https://github.com/oceanbase/odc/assets/65022285/38d93a65-807d-46c6-a801-9f0550b5c489)

### What did you expect to happen?

I expect the task success.

### How can we reproduce it (as minimally and precisely as possible)?

.

### Anything else we need to know?

.

**Comment by PeachThinking** [comment]
![Image](https://github.com/oceanbase/odc/assets/140503120/0c99afd9-bd6a-4f42-9b3d-5a09faf793c5)
