### ISSUE TITLE
[Bug]: The amount of data for the paged query of the tickets is not fully displayed

### ISSUE THREAD

**Issue by zijiacj** [oceanbase/odc#2480]
### ODC version

424

### OB version

uncorrelated

### What happened?

In odc 424, even if the user is admin, when you click to view all lists、export、export result sets、import、mock data、async、shadow_async、 structure comparison、partition plan、data cleaning、and apply for database permission, the result of the back-end response is only one page of data. But in fact ,the number of records in the database is  greater than that. As shown in the following picture
![image](https://github.com/oceanbase/odc/assets/135618909/dac9a7ac-129a-4564-a7db-4694a12a0999)

### What did you expect to happen?

Expect to return the correct totalElements and totalPages in the paged query. For example, clicking on 'I initiated' is currently getting the correct response. As shown in the following picture
![image](https://github.com/oceanbase/odc/assets/135618909/897d49c6-5d1b-4fad-9094-1ae8f8c40391)

### How can we reproduce it (as minimally and precisely as possible)?

click to view all lists、export、export result sets、import、mock data、async、shadow_async、 structure comparison、partition plan、data cleaning、or apply for database permission.using one of the above operations you can reproduce it.
![image](https://github.com/oceanbase/odc/assets/135618909/a9424a6b-a363-4862-878e-0c85439b546b)

**Comment by yizhouxw** [comment]
@zijiacj  @yhilmare @smallsheeeep  please follow moudle owner while assign issue.

**Comment by MarkPotato777** [comment]
The admin user has no differences with any other users while listing the tickets.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/84ee158f-0e2f-4b21-a369-19df10b35f78)

pass
