### ISSUE TITLE
[Bug]: Unable to create entire database archiving task

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2481]
### ODC version

ODC430

### OB version

independent

### What happened?

Unable to create entire database archiving task
![image](https://github.com/oceanbase/odc/assets/59468957/acc8586d-2594-4983-acf8-7fbeb4078322)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

create entire database archiving task

**Comment by HSunboy** [comment]
Fixed In Commit [fb421a7aef014523b01e66fbc0b9c6b0c88d9922](https://github.com/oceanbase/odc-client/commit/fb421a7aef014523b01e66fbc0b9c6b0c88d9922)
            ------
            畅晚
            Mon May 27 16:36:22 2024 +0800
