### ISSUE TITLE
[Bug]: Oracle creation archive task synchronization table structure failed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2482]
### ODC version

ODC430

### OB version

independent

### What happened?

Oracle creation archive task synchronization table structure failed
![image](https://github.com/oceanbase/odc/assets/59468957/49213524-6f0a-41bb-83c0-df527bcdce08)

![image](https://github.com/oceanbase/odc/assets/59468957/c2a7d847-6496-4419-b712-2828d8cae692)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

1. The oracle table is created on the source side but not on the target side.
2. Create an archiving task and uncheck the synchronization table structure
```
CREATE TABLE "NON_PARTRANGE_RANGE_PRI" (
  "COL1" NUMBER(*,0) NOT NULL ENABLE,
  "COL2" NUMBER,
  "COL3" CHAR(10),
  "COL4" VARCHAR2(10),
  "COL7" DATE,
  "COL8" TIMESTAMP(6),
  CONSTRAINT "NON_PARTRANGE_RANGE_PRI_PK" PRIMARY KEY ("COL1")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0
 partition by range("COL1")
(partition "P1" values less than (0),
partition "P2" values less than (10000),
partition "P3" values less than (100000),
partition "P4" values less than (MAXVALUE));
```

**Comment by guowl3** [comment]
[#2491](https://github.com/oceanbase/odc/issues/2491)

**Comment by Huangxiao-mas** [comment]
pass
