### ISSUE TITLE
[Bug]: Initiate the archiving task again for the specified partition, but the partition is not included.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2483]
### ODC version

ODC430

### OB version

independent

### What happened?

Initiate the archiving task again for the specified partition, but the partition is not included.
![image](https://github.com/oceanbase/odc/assets/59468957/9f606ff2-523a-46f2-8194-a87397a8827d)
![image](https://github.com/oceanbase/odc/assets/59468957/84a4f827-3798-46e6-bb12-5cdc89f8b300)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [fb421a7aef014523b01e66fbc0b9c6b0c88d9922](https://github.com/oceanbase/odc-client/commit/fb421a7aef014523b01e66fbc0b9c6b0c88d9922)
            ------
            畅晚
            Mon May 27 16:36:22 2024 +0800
