### ISSUE TITLE
[Bug]: For tasks with specified partitions, click to initiate again, but the task cannot be delivered.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2488]
### ODC version

ODC430

### OB version

independent

### What happened?

For tasks with specified partitions, click to initiate again, but the task cannot be delivered.
![image](https://github.com/oceanbase/odc/assets/59468957/de4556a3-530f-435f-882c-1fbfde14c109)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by Huangxiao-mas** [comment]
Click to initiate again, the task cannot be created

**Comment by HSunboy** [comment]
Fixed In Commit [fb421a7aef014523b01e66fbc0b9c6b0c88d9922](https://github.com/oceanbase/odc-client/commit/fb421a7aef014523b01e66fbc0b9c6b0c88d9922)
            ------
            畅晚
            Mon May 27 16:36:22 2024 +0800
