### ISSUE TITLE
[Bug]: Manually add sensitive columns, after selecting a column, you cannot switch to select other columns

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#25]
**Describe the bug**

**Environment**

- OS Version and CPU Arch(`uname -a`):
- Component Version:ODC4.2.0
  

**Fast Reproduce Steps(Required)**

steps:
```
1. Go to the project
2. Click Sensitive Data
3. Manually add sensitive columns, select data source, database, table
4. After selecting one of the column fields
It was found that the column field cannot be switched
```
![image](https://github.com/oceanbase/odc/assets/59468957/0ffbe532-a977-41e7-9ab1-31804f24c1b7)

**Expected behavior**

**Actual Behavior**

**Additional context**

**Comment by UnknownAdventurer** [comment]
this issue has fixed at previous commit

**Comment by runzi389205** [comment]
PASS



![Image](https://github.com/oceanbase/odc/assets/141202865/087ff531-0814-49d1-b513-b2efb97d943c)


![Image](https://github.com/oceanbase/odc/assets/141202865/eb0c0206-b7fc-403c-aa5b-13f0fadfa0f3)
