### ISSUE TITLE
[Bug]: The ODC desktop version failed to be upgraded from 4.2.2 to 4.2.4.

### ISSUE THREAD

**Issue by zijiacj** [oceanbase/odc#2500]
### ODC version

 desktop version from 4.2.2 to 4.2.4.

### OB version

not related

### What happened?

The ODC desktop version failed to be upgraded from 4.2.2 to 4.2.4. When starting an upgraded project, inserting records into the iam_permission table will report a primary key id conflict error.

### What did you expect to happen?

After the upgrade, the odc can be successfully started without any exception

### How can we reproduce it (as minimally and precisely as possible)?

Creating data source on ODC Desktop version 4.2.2. Then upgrade ODC Desktop version from 4.2.2 to 4.2.4. Finally start the upgraded project

**Comment by yhilmare** [comment]
# About how to reproduce it

1. remove all metadb files
2. download the desktop odc with 3.2.0, install it and open the odc (you may create a connection config)
3. uninstall the odc and **do not delete the metadb file**
4. download the desktop odc with 4.2.4, install it and open the odc

you will reproduce the issue when you are at the step 4
