### ISSUE TITLE
[Bug]: trigger a format error when format a "like replace" sql with content has "\\"

### ISSUE THREAD

**Issue by UnknownAdventurer** [oceanbase/odc#2502]
### ODC version

4.2.2

### OB version

\*

### What happened?

trigger a format error when sql content has "like replace ...'\', '\\' ...."
'\\' will be transform to ' \ \ '
![image](https://github.com/oceanbase/odc/assets/141202334/76c203cd-d90f-4ee1-a083-40e8be3e6d88)
![image](https://github.com/oceanbase/odc/assets/141202334/a2b33a24-24bf-4682-87d8-c019dc6d0d6a)

![image](https://github.com/oceanbase/odc/assets/141202334/0c0c8f97-92f5-4d72-943c-8118c1399358)
![image](https://github.com/oceanbase/odc/assets/141202334/9cc1a05a-be72-4588-83e5-f0e573cca6bf)

### What did you expect to happen?
show tables;
select
  *
from
  employee
where
  (
    name like in (
      '\', '\\'));

### How can we reproduce it (as minimally and precisely as possible)?
show tables;
select * from employee where (name like in ('\', '\\'));

// after format 
show tables;
select
  *
from
  employee
where
  (
    name like in (
      '\', ' \ \ '));

**Comment by yizhouxw** [comment]
verify in v4.2.4:
-  '\' '\\'  handle correct
- '1000' will add blank wrap, to ' 1000 '

**Comment by HSunboy** [comment]
Fixed In Commit [a992a871cc59ca41f4c115ca777682efaa8a5281](https://github.com/oceanbase/odc-client/commit/a992a871cc59ca41f4c115ca777682efaa8a5281)
            ------
            xiaokang
            Mon Jun 17 16:24:19 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/924b83cb-c002-4883-ad6c-16987dbf9f12)

pass
