### ISSUE TITLE
[Bug]: SQL error in spatial data type production

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2503]
### ODC version

odc430

### OB version

ob4310

### What happened?

https://github.com/oceanbase/odc/assets/143492234/c1684270-604d-49a6-ad35-2ead12a9401e
![image](https://github.com/oceanbase/odc/assets/143492234/cb21a922-3be9-4712-876d-5f6d62684f4f)

### What did you expect to happen?

SQL execution successful

### How can we reproduce it (as minimally and precisely as possible)?

1. Creating Tables
CREATE TABLE spatial_table (
    id INT PRIMARY KEY,
    point SDO_GEOMETRY,
    linestring SDO_GEOMETRY,
    polygon SDO_GEOMETRY,
    multipoint SDO_GEOMETRY,
    multilinestring SDO_GEOMETRY,
    multipolygon SDO_GEOMETRY,
    collection SDO_GEOMETRY
);
2. Add data
INSERT INTO spatial_table (id, point) VALUES (1, SDO_GEOMETRY(2001, NULL, SDO_POINT_TYPE(12, 34, NULL), NULL, NULL));
3. Copy the current row within the table data
4. Copy and execute again

**Comment by yhilmare** [comment]
we may check the input parameter for the first time and second time:

first time:

![截屏2024-06-04 18 24 00](https://github.com/oceanbase/odc/assets/22992296/28fc0127-706b-4ea6-80c3-aa13e00eb549)

second time:
![截屏2024-06-04 18 25 45](https://github.com/oceanbase/odc/assets/22992296/e0cb220f-a838-4ae9-8ba2-845595d7ced9)

we take column 'POINT' as an example, the front end set the column type to 'SDO_GEOMETRY' for the first time and set to 'GEOMETRY' for the second time and this is the direct reason of this issue.

further more, the back end use `OBOracleGeometryConverter` to generate sql literal, this class can only support `geometry`.

**Comment by yhilmare** [comment]
@HSunboy may check that why does the front end give different parameters between the first time and second time
