### ISSUE TITLE
[Bug]: Hover the template name does not show the contained database.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2506]
### ODC version

ODC 4.3.0

### OB version

No related.

### What happened?

Hover database template name does not show the contained database.
![image](https://github.com/oceanbase/odc/assets/46598871/3e039901-8acc-4627-9201-57254fbb5d27)

### What did you expect to happen?

Hover the template name shows the database that is contained.

### How can we reproduce it (as minimally and precisely as possible)?

Create a multi-library change template and hover it.

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/0cb44d88-981e-4d9b-9237-9e2834373bc0)



![Image](https://github.com/oceanbase/odc/assets/143492234/639aebc8-04a2-4117-903f-20d167c43211)

pass
