### ISSUE TITLE
[Bug]: The database in the multi-database change template cannot be edited.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2508]
### ODC version

ODC 4.3.0

### OB version

No related.

### What happened?

The database in the multi-database change template cannot be edited.If I want to add a database to the template, I need to create a new template, which is inconvenient to use.

### What did you expect to happen?

Support for editing templates.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5ff56bdc-ca07-47e4-85c8-990b1ce843a5)

pass
