### ISSUE TITLE
[Bug]: No execution record is generated before or during a multi-database change task

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2516]
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

No execution record is generated before or during a multi-database change task.
![image](https://github.com/oceanbase/odc/assets/46598871/cec0fb78-ccaf-4217-b69c-2fd9d29b3cc7)
![image](https://github.com/oceanbase/odc/assets/46598871/daf4e8ec-d3f0-453a-bd70-ba874d9cece1)

### What did you expect to happen?

The execution record of a multi-library change task must be generated before and during the task execution.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver a multi-database change task and view the task record before and during the execution.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/c65a38d5-9083-4710-babd-b2e19a2501d5)

pass
