### ISSUE TITLE
[Bug]: After selecting the database, the first search returns empty

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2517]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/28c468b4-96c3-457c-8ba4-a36c710a3fed)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/ed95a289-7803-4525-8d69-73e5b22839c8)

### How can we reproduce it (as minimally and precisely as possible)?

Open the search box to search

**Comment by smallsheeeep** [comment]
Front-end API parameter error：
<img width="1426" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/ef34b7af-3012-422c-ad92-26b2c9218121">

<img width="1416" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/67de75e0-7a56-40f0-9c12-2c6a0b4bf19b">

**Comment by HSunboy** [comment]
Fixed In Commit [32f81a2f7dfcb38dcd3bd242fdb2260c878217a9](https://github.com/oceanbase/odc-client/commit/32f81a2f7dfcb38dcd3bd242fdb2260c878217a9)
            ------
            畅晚
            Wed May 29 09:54:15 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/3f7e88f3-b029-4e4d-b1b7-d340493ba789)
pass
