### ISSUE TITLE
[Bug]: SQL editor code auto completion always includes code snippets

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2518]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/686e8952-cbee-4a47-ac65-9823e25a913e)
![image](https://github.com/oceanbase/odc/assets/143492234/a889067e-c241-477d-a437-12e0bc2c3155)

### What did you expect to happen?

Does not include code snippets during automatic completion

### How can we reproduce it (as minimally and precisely as possible)?

input   SELECT * FROM oceanbase.

**Comment by HSunboy** [comment]
fixed in dev-4.3.1

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/fe503f65-9ce7-4e6f-aeab-663ddfe41ce5)
![image](https://github.com/oceanbase/odc/assets/143492234/161c94d0-0345-453d-bbf5-d9824e9c971a)
pass
