### ISSUE TITLE
[Bug]: Oceanbase database global search, unable to find columns

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2519]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/a02128f1-3258-40ce-8aab-07ab013a338e)
![image](https://github.com/oceanbase/odc/assets/143492234/b545f32b-c95a-46af-98a1-6ea3f891dca4)

### What did you expect to happen?

Search for columns

### How can we reproduce it (as minimally and precisely as possible)?

Select Oceanbase database for search

**Comment by smallsheeeep** [comment]
The expected behaviour is: if a blank character is entered, the retrieval result is empty.

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/bf87f123-8e6f-4b0a-9fcb-8ecfedb053be)
![image](https://github.com/oceanbase/odc/assets/143492234/3143f7f8-3404-4d59-888f-002299d4a555)
The Oceanbase database is unable to retrieve content

**Comment by smallsheeeep** [comment]
It works for me:
<img width="962" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/23f1a4df-8247-4584-a568-3536e1f14b65">
