### ISSUE TITLE
[Bug]: Search box dropdown database page crashes

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2521]
### ODC version

odc430

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/06825943-4ff8-4ac6-b8bf-fc5a960e6131

### What did you expect to happen?

Page does not crash

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [32f81a2f7dfcb38dcd3bd242fdb2260c878217a9](https://github.com/oceanbase/odc-client/commit/32f81a2f7dfcb38dcd3bd242fdb2260c878217a9)
            ------
            畅晚
            Wed May 29 09:54:15 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/6594e093-1612-4aef-91c5-a864bb3177b7)
pass
