### ISSUE TITLE
[Bug]: When data cleaning requires verification, the target table should be optional.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2526]
### ODC version

ODC430

### OB version

independent

### What happened?

When data cleaning requires verification, the target table should be optional.
![image](https://github.com/oceanbase/odc/assets/59468957/72250329-8041-4fc9-a55a-1f86009089c3)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [21d507e702c985bb40f50c165ada87dea04b8feb](https://github.com/oceanbase/odc-client/commit/21d507e702c985bb40f50c165ada87dea04b8feb)
            ------
            畅晚
            Wed May 29 09:57:35 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f3171622-394a-4489-8aba-3ce6e7ebfd14)

pass
