### ISSUE TITLE
[Bug]: There is a problem with displaying multi-database changes in dark mode

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2529]
### ODC version

ODC4.3.0

### OB version

No related

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/b2757a03-f38d-45c0-b165-0549781be6fb)
There is a problem with displaying multi-database changes in dark mode

### What did you expect to happen?

Display normal.

### How can we reproduce it (as minimally and precisely as possible)?

Switch to dark mode and perform the multi-database change task.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/21556c5b-88c1-4418-80e1-50d5fb029776)

pass
