### ISSUE TITLE
[Bug]: Incorrect recognition statement

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2530]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/3d7abd9a-a636-475e-bc32-8a373b6d67ba)

### What did you expect to happen?

The check result is the execution statement

### How can we reproduce it (as minimally and precisely as possible)?

1. Set * not recommended for SELECT statement to no need for improvement and open it
2. Execute statements containing *
3. Modify result set

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/bff7439b-de62-42dc-8794-094aac8cf2b7)

pass
