### ISSUE TITLE
[Bug]: Search database and select, the database displayed is incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2531]
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/8c8ce22a-d9ca-4e79-8f8c-6bfe63930cd7)
Search the database and select, showing not the database name but the search content.

### What did you expect to happen?

Select and display the database name.

### How can we reproduce it (as minimally and precisely as possible)?

Select the database by searching.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/485c162e-6297-4f67-a513-892a366306af)



![Image](https://github.com/oceanbase/odc/assets/40919496/c985de4d-80e6-4951-b824-dd376dba21ba)

pass
