### ISSUE TITLE
[Bug]: If a database is selected on multiple pages in the database list, the multi-database change task does not contain all databases

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2535]
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

If a database is selected on multiple pages in the database list, the multi-database change task does not contain all databases;

### What did you expect to happen?

The task should contain the database for all page selections.

### How can we reproduce it (as minimally and precisely as possible)?

Select two databases on the first page and three databases on the second page of the database list and deliver the multi-database change task.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/58e56bab-2f5b-4a57-b7a5-e0550760fcec)
pass
