### ISSUE TITLE
[Bug]: The progress status of the multi-database change execution node is incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2539]
### ODC version

ODC 430

### OB version

No related

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/7c4c8d54-ed4a-447e-b3ca-d82310d4415f)
The progress status of the multi-database change execution node is incorrect.

### What did you expect to happen?

The progress status of the multi-library change node must be consistent with the actual progress.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver a multi-database change task with multiple execution nodes.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/60524584-2098-4b1c-b262-cd0955890b14)

pass
