### ISSUE TITLE
[Bug]: Optimize error messages when the database is empty during template creation

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2541]
### ODC version

ODC4.3.0

### OB version

No related.

### What happened?

Optimize error messages when the database is empty during template creation.
![image](https://github.com/oceanbase/odc/assets/46598871/14537543-6743-413d-93ac-c14ea33611c1)

### What did you expect to happen?

Error messages should be optimized，such as：The number of databases must be greater than 1 and not more than 100.

### How can we reproduce it (as minimally and precisely as possible)?

Do not select the database when creating the template and save it.

**Comment by qymsummer** [comment]
Save the template and when the data is empty, it will prompt correct

![Image](https://github.com/oceanbase/odc/assets/40919496/105d8185-48e0-43af-9c78-3c1c4c2d37a9)
