### ISSUE TITLE
[Bug]: Uncheck Do not set a library administrator. Do not select a library administrator at this time. When you click OK, the library administrator is not checked.

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2543]
### ODC version

4.3.0

### OB version

No related.

### What happened?

Uncheck Do not set a library administrator. Do not select a library administrator at this time. When you click OK, the library administrator is not checked.
![image](https://github.com/oceanbase/odc/assets/40919496/90c7e94d-99ea-45ac-800b-2fe4cc92fab7)

### What did you expect to happen?

If you uncheck the option of not setting a library administrator, the library administrator is a required item. If you do not select a library administrator, you must check the required items.

### How can we reproduce it (as minimally and precisely as possible)?

In Project Management, select a database, set the database administrator, uncheck Do not set an administrator, do not select a database administrator, and click OK

**Comment by HSunboy** [comment]
Fixed In Commit [e5538d5d1f305c5599dae9f992ab086aae6a13d5](https://github.com/oceanbase/odc-client/commit/e5538d5d1f305c5599dae9f992ab086aae6a13d5)
            ------
            畅晚
            Thu May 30 09:33:28 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/3ec68479-1e62-4ca0-91c0-5c79881b045c)

pass
