### ISSUE TITLE
[Bug]: In the data source, create a new database, do not select "Project", directly select a library administrator, click OK, the system reports an error

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2544]
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

![截屏2024-05-29 10 30 38](https://github.com/oceanbase/odc/assets/40919496/f2a0748e-5251-44ee-bc61-29d742672554)
In the data source, create a new database, do not select "Project", directly select a library administrator, click OK, the system reports an error

### What did you expect to happen?

If no project is selected, the library administrator cannot display

### How can we reproduce it (as minimally and precisely as possible)?

When you click Create Database for the first time, since no project is selected, click Library Administrator. At this time, the list is empty. Select a project and click Library Administrator again. At this time, the program displays the Library Administrators related to the selected project. Then do not make any selections and click Cancel. Click Create Database again to view the Library Administrator. At this time, the Administrator list should still show "empty" normally, but it shows the Library Administrators of the project selected when it was closed last time.

**Comment by HSunboy** [comment]
Fixed In Commit [e5538d5d1f305c5599dae9f992ab086aae6a13d5](https://github.com/oceanbase/odc-client/commit/e5538d5d1f305c5599dae9f992ab086aae6a13d5)
            ------
            畅晚
            Thu May 30 09:33:28 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8ddd0044-e34c-4e28-adc7-5df0aed68e59)

pass
