### ISSUE TITLE
[Bug]: The user is deactivated. The user is a library administrator of a project. At this time, the user can still approve work orders.

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2548]
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

The user is deactivated. The user is a library administrator of a project. At this time, the user can still approve work orders.
![image](https://github.com/oceanbase/odc/assets/40919496/65f119e1-f629-4574-b126-bbccddbcfd1b)
![截屏2024-05-29 13 46 23](https://github.com/oceanbase/odc/assets/40919496/119101a1-9fb2-486e-81df-2ac40c54f72f)

### What did you expect to happen?

The user is deactivated and cannot approve work orders

### How can we reproduce it (as minimally and precisely as possible)?

First, create a work order that requires approval from the library administrator. At this time, change the library administrator account to deactivated. Then, in the library administrator approval work order menu, click the approved work order and click OK.

**Comment by smallsheeeep** [comment]
The root cause is that ODC cannot force the disabled user to logout. It is hard to fix it completely, I just make the disabled user cannot approve the flow.

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/27e89b64-9166-400e-ac68-88a25d3e6864)

pass
