### ISSUE TITLE
[Bug]: The work order execution result is inconsistent with the approval status

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2554]
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

When approving a database change, enter a processing opinion of more than 200 characters and click "Approve". The interface prompts "Error accessing the metadata database, please contact the administrator". The interface reports 500. Click Execute and the result sql has been executed normally. However, when clicking the task flow, the processing status is Rejected.
And the execution results and task flow are inconsistent.
![image](https://github.com/oceanbase/odc/assets/40919496/708b2d76-123a-468f-99d6-3c69f1e2294d)
![image](https://github.com/oceanbase/odc/assets/40919496/a9a616eb-cc22-444f-afa6-a96e2b92384f)

### What did you expect to happen?

When reviewing, enter more than 200 characters and click Confirm. At this time, the front-end and back-end should have verification. 

### How can we reproduce it (as minimally and precisely as possible)?

When approving a work order, enter more than 200 characters to view the status of the work order

**Comment by smallsheeeep** [comment]
The Issue description is misleading; in fact, entering an approval comment with more than 1024 characters will result in an "Error accessing metadatabase" error.

**Comment by smallsheeeep** [comment]
The core of this problem is that when an exception was made for approval to go through, the process did not abort as expected, but continued to execute.

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/c03fb922-5199-47c1-9d15-5e4816333e39)

pass

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/c03fb922-5199-47c1-9d15-5e4816333e39)

pass
