### ISSUE TITLE
[Bug]: After the column storage table is exported, the column storage definition statement is missing in the schema file

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2555]
### ODC version

ODC430

### OB version

Oceanbase430

### What happened?

After the column storage table is exported, the column storage definition statement is missing in the schema file
![image](https://github.com/oceanbase/odc/assets/59468957/458353e3-cee4-4f19-98a7-4886456bc31f)
![image](https://github.com/oceanbase/odc/assets/59468957/ca5c3daa-838f-433d-af60-46163b732322)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

```
CREATE TABLE tt_column_store (c1 int PRIMARY KEY, c2 int , c3 int) WITH COLUMN GROUP (each column);
```
export it

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/bfc186e4-fa85-45a2-871b-afff437d683e)

pass
