### ISSUE TITLE
[Bug]: When the library administrator approves the work order whose library administrator privileges have been deleted, click OK or Reject, and two prompt boxes with the same prompt will pop up.

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2556]
### ODC version

ODC 4.3.0

### OB version

 No related

### What happened?

When the library administrator approves the work order whose library administrator privileges have been deleted, click OK or Reject, and two prompt boxes with the same prompt will pop up.
![截屏2024-05-29 15 11 33](https://github.com/oceanbase/odc/assets/40919496/3b95442e-72e8-4b21-8cea-88c28a81890c)

### What did you expect to happen?

The same error only pops up once

### How can we reproduce it (as minimally and precisely as possible)?

Use the library administrator to approve a work order and enter the confirmation or rejection page. At this time, use an account with the project library administrator's deletion permission to delete the administrator. At this time, return to the library administrator's approval or rejection interface and click approve or reject. Two identical error messages will pop up on the interface.

**Comment by HSunboy** [comment]
Fixed In Commit [29528084deeb56f8d2a1bcf064198310000fbf79](https://github.com/oceanbase/odc-client/commit/29528084deeb56f8d2a1bcf064198310000fbf79)
            ------
            畅晚
            Fri May 31 13:55:27 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/0c3a22d1-a5cb-466a-bfa0-e3ee0268daf4)

PASS
