### ISSUE TITLE
[Bug]: Unable to edit multi-database changes when delivered again.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2557]
### ODC version

ODC 4.3.0

### OB version

No related.

### What happened?

Unable to edit multi-dababase changes when delivered again.
![image](https://github.com/oceanbase/odc/assets/46598871/8fb8839e-2a51-4640-9d36-b04911fa2d00)

### What did you expect to happen?

I can edit the multi-database change content when it is delivered again.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver multi-database change again.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/035a3fd3-7650-4e55-abd8-0f90721a00bf)

pass
