### ISSUE TITLE
[Bug]: The multi-database changes are not shown in the operation record.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2559]
### ODC version

ODC 4.3.0

### OB version

No related.

### What happened?

The multi-database changes are not shown in the operation record.
![image](https://github.com/oceanbase/odc/assets/46598871/2275c6c9-8742-4788-9bb4-889b15490a26)
![image](https://github.com/oceanbase/odc/assets/46598871/df004630-1db0-4f98-8841-c4d3a6d52f51)

### What did you expect to happen?

Show multi-library changes.

### How can we reproduce it (as minimally and precisely as possible)?

View operation record.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8adc6bfb-2d7f-428f-b233-f483c23ad0e0)



![Image](https://github.com/oceanbase/odc/assets/143492234/6c0faab7-f3ab-486f-b944-2511f0c9415c)

pass
