### ISSUE TITLE
[Bug]:Create a new database, select the library administrator, click OK, and the system reports an error 

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2560]
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

Select a data source, click New Database, select a project, and select a library administrator, click OK, and the interface reports an error request, details: standby tenant is read only
![截屏2024-05-29 16 43 57](https://github.com/oceanbase/odc/assets/40919496/cba27111-680e-45fb-8429-27e25861a470)

### What did you expect to happen?

在数据源新建数据库时，可正常添加库管理员 

### How can we reproduce it (as minimally and precisely as possible)?

Select a data source, click New Database, select a project, and select a library administrator, click OK, and the interface reports an error request, details: standby tenant is read only

**Comment by smallsheeeep** [comment]
Attention to the error message, standby tenant is readonly and cannot create new database. It is by design.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/56d03747-0a2c-4f88-809d-95e88e3566e1)

pass
