### ISSUE TITLE
[Bug]: Multi-database changes should filter out projects that the user do not have permissions

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2566]
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

This user does not have the permission on the odc_4.2.0 project. An error message is displayed after the project is selected.
![image](https://github.com/oceanbase/odc/assets/46598871/848f9d9c-0e30-42e8-9eb7-96c83248975c)

### What did you expect to happen?

Projects that the user does not have permission for should not be displayed.

### How can we reproduce it (as minimally and precisely as possible)?

Select project odc_4.2.0 when delivering multi-library change tasks using a user who does not have project odc_4.2.0 permissions.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/52ff06ab-db82-469a-b4ee-25e43177133f)

pass
