### ISSUE TITLE
[Bug]: The pre-check for multi-database changes fails,and the permission check result is not displayed

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2568]
### ODC version

ODC4.3.0

### OB version

No related.

### What happened?

The pre-check for multi-database changes fails,and the permission check result is not displayed.
![image](https://github.com/oceanbase/odc/assets/46598871/35c42504-f5d8-41fb-9f62-88dab27ee88a)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/46598871/424827cf-a67d-42f4-a3ba-c75a9ebd2e43)

### How can we reproduce it (as minimally and precisely as possible)?

Enter a sql statement for a library that has no permissions.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/39c186c1-872f-4c42-b3a9-82075e659602)

pass
