### ISSUE TITLE
[Bug]: When the OB version is 3. x, the backup database cannot open the table

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2570]
### ODC version

odc430

### OB version

ob3.x

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/526ac330-297f-4480-9946-f02684554d50)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/acd7204b-0aa0-4963-9834-183828b54be8)

### How can we reproduce it (as minimally and precisely as possible)?

Create a backup database for ob3. x
Open Table

**Comment by yhilmare** [comment]
fixed:


![Image](https://github.com/oceanbase/odc/assets/22992296/1bd19267-893a-4472-a8f8-679d1c5a38a2)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4d7564a2-b6ab-4d68-a9e9-9324af149eb4)

MySQL backup database unable to open table

**Comment by yhilmare** [comment]
![Image](https://github.com/oceanbase/odc/assets/22992296/cf8a6539-c710-45e3-a1e4-16aaf0b3deab)

the api gives response bug the front end miss it~

**Comment by HSunboy** [comment]
fixed in dev-4.3.0

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/43a967a2-bf8c-4b61-a700-7e9781d8e377)

Incorrect error report

**Comment by HSunboy** [comment]
Fixed In Commit [5c3a2ebf39c3814e65651b9a605fe2b690f504db](https://github.com/oceanbase/odc-client/commit/5c3a2ebf39c3814e65651b9a605fe2b690f504db)
            ------
            xiaokang
            Fri Jun 7 11:02:37 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/d23acee0-f05c-41bf-bab7-a3c43546c9b8)

pass
