### ISSUE TITLE
[Bug]: When binding a project to a data source, you cannot select a library administrator when creating a new database

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2571]
### ODC version

ODC4.3.0

### OB version

no related

### What happened?

When binding a project to a data source, you cannot select a library administrator when creating a new database
![Uploading 截屏2024-05-30 11.32.03.png…]()

### What did you expect to happen?

Data bound to the project can still be selected as a library administrator

### How can we reproduce it (as minimally and precisely as possible)?

First, in the database editor, bind a project, then enter the data source menu, select the database of the bound project, and click New Database.

**Comment by HSunboy** [comment]
Fixed In Commit [29528084deeb56f8d2a1bcf064198310000fbf79](https://github.com/oceanbase/odc-client/commit/29528084deeb56f8d2a1bcf064198310000fbf79)
            ------
            畅晚
            Fri May 31 13:55:27 2024 +0800
