### ISSUE TITLE
[Bug]: View the execution details and then view the log to show the optimization

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2575]
### ODC version

ODC430

### OB version

Oceanbase430 mysql

### What happened?

View the execution details and then view the log to show the optimization

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

chat priavtely

**Comment by HSunboy** [comment]
Fixed In Commit [29528084deeb56f8d2a1bcf064198310000fbf79](https://github.com/oceanbase/odc-client/commit/29528084deeb56f8d2a1bcf064198310000fbf79)
            ------
            畅晚
            Fri May 31 13:55:27 2024 +0800
