### ISSUE TITLE
[Bug]: The official website document needs to provide information about externally integrated template variables

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#258]
### ODC version

ODC 4.2.0

### OB version

Any version of OceanBase

### What happened?

The official website documentation lacks information about external integration template variables.
![image](https://github.com/oceanbase/odc/assets/46598871/46356003-8a3f-4b96-be85-5845c4740c2c)

### What did you expect to happen?

The official website document needs to provide information about externally integrated template variables

### How can we reproduce it (as minimally and precisely as possible)?

Check the website document external integration module

**Comment by smallsheeeep** [comment]
The document has been updated at: https://www.oceanbase.com/docs/common-odc-1000000000090970#cce13d81-4099-4cad-8a2e-4c415a8adb5d

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b1af4e41-6638-44bd-a859-ba76b0b7d0cf)

pass
