### ISSUE TITLE
[Bug]: Personal space execution database change generates rollback statement, download error

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2580]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/bf20c9c1-20ab-4a6f-9f3d-4faf1feb9671)

### What did you expect to happen?

Normal download

### How can we reproduce it (as minimally and precisely as possible)?

1. Creating database changes in personal space, selecting rollback statements, and manually executing them
2. Download rollback statement

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/3722b7fb-c82a-420a-bc98-469585e46394)

The backup rollback solution can be downloaded normally
