### ISSUE TITLE
[Bug]: Personal space blocks multi-database change entry

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2581]
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

Personal space does not support multi-database changes, and the entrance is not blocked.
![image](https://github.com/oceanbase/odc/assets/46598871/bede4628-8669-4577-8627-97dd2e21e431)

### What did you expect to happen?

Personal space blocks multi-database change entry.

### How can we reproduce it (as minimally and precisely as possible)?

Enter personal space.

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8b4da102-3f51-4bf6-b654-5402796ad595)

pass
