### ISSUE TITLE
[Bug]: data loading would not be executed when schema was imported failed

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#2583]
### ODC version

4.2.4

### OB version

-

### What happened?

When schema was imported failed, the data task would not be executed even user configured continue on error.

### What did you expect to happen?

The data task would be continued if schema task failed.

### How can we reproduce it (as minimally and precisely as possible)?

-

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/877f2a1a-a5e7-4460-b8ff-d413c7f537c7)

pass
