### ISSUE TITLE
[Bug]: If a database change is initiated again during execution, it will become a rollback work order

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2586]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/7d09fcd7-2b8f-49cd-bd54-9ec47bf751e1)

### What did you expect to happen?

Initiating a work order again is not rolling back the work order

### How can we reproduce it (as minimally and precisely as possible)?

Select a database change task and click to initiate again

**Comment by smallsheeeep** [comment]
The root cause is that the front-end transfer a bad arguments:
<img width="1433" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/a4bb6f7f-41d3-4944-b4ce-3e3c7bdcecb4">
@HSunboy  Please review and solve it.

**Comment by HSunboy** [comment]
Fixed In Commit [af3b00619b23afac5d27a010c0b1bc5bffdbae67](https://github.com/oceanbase/odc-client/commit/af3b00619b23afac5d27a010c0b1bc5bffdbae67)
            ------
            畅晚
            Tue Jun 4 15:46:46 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/af37e2d2-df04-4da9-a494-0c020dcafd97)
pass
