### ISSUE TITLE
[Bug]: After the sql window is changed to a dark theme, the work order sql plan window on the home page or the export result set input sql window becomes a dark theme

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#26]
**Describe the bug**

**Environment**

- OS Version and CPU Arch(`uname -a`):
 
- Component Version:ODC4.2.0
  

**Fast Reproduce Steps(Required)**

`steps:
1. Change the window theme to dark black
2. Return to the home page
3. Click on the work order to create a sql plan
It is found that the input sql window becomes dark black`
![image](https://github.com/oceanbase/odc/assets/59468957/d9f25087-05e5-4b25-8b9b-96fe124118af)

**Expected behavior**

**Actual Behavior**

**Additional context**

**Comment by e-bluesky** [comment]
Fixed

**Comment by runzi389205** [comment]
PASS


![Image](https://github.com/oceanbase/odc/assets/141202865/b6439d7c-8345-4436-bdf8-62c758750ab3)
