### ISSUE TITLE
[Bug]: Simultaneously execute the statement that sets nls and the query statement, and the nls statement is not invalidated

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2603]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/91628673-c378-4a7c-8b33-1449b56d768d)

### What did you expect to happen?

format the date column by 'yyyy-mm-dd'

### How can we reproduce it (as minimally and precisely as possible)?

1. Creating Tables and Adding Data
CREATE TABLE "TIME_TBL_" (
  "ID" VARCHAR2(64),
  "CREATE_TIME_" DATE
);

insert into "TIME_TBL_"("ID","CREATE_TIME_") values('1',to_date('2024-06-03 10:36:13', 'YYYY-MM-DD HH24:MI:SS'));
insert into "TIME_TBL_"("ID","CREATE_TIME_") values('2',to_date('2024-06-03 10:36:19', 'YYYY-MM-DD HH24:MI:SS'));

2. Open a new SQL window

alter session set nls_date_format='yyyy-mm-dd ';

SELECT "ID", "CREATE_TIME_" FROM "TIME_TBL_";

**Comment by yhilmare** [comment]
this is as expect.

we cannot set nls time format in multiple sql executions at the same time, this is because odc must wait until the alter statement that sets nls is executed to know whether the setting is correct.
