### ISSUE TITLE
[Bug]: Structure synchronization, the corresponding field of the check box is not displayed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2605]
### ODC version

ODC430

### OB version

independent

### What happened?

Structure synchronization, the corresponding field of the check box is not displayed
![image](https://github.com/oceanbase/odc/assets/59468957/a640680d-05a2-4077-abd1-4378f6ff794a)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [625431e52624377539c41c36e68a8b196cb12cdc](https://github.com/oceanbase/odc-client/commit/625431e52624377539c41c36e68a8b196cb12cdc)
            ------
            畅晚
            Tue Jun 4 10:34:20 2024 +0800
