### ISSUE TITLE
[Bug]: When changing multiple databases without selecting a project, you can click to select a template

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2608]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/4f7a3ac9-6441-481b-b89b-f33168328b4d)

### What did you expect to happen?

Cannot click to select template without selecting project

### How can we reproduce it (as minimally and precisely as possible)?

Cannot click to select template without selecting project

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/182980c5-6cdb-4780-bc18-f5da3c8be081)

pass
