### ISSUE TITLE
[Bug]: The multi-database change approval node does not match any database administrator that can be approved

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2609]
### ODC version

ODC 4.3.0

### OB version

No related.

### What happened?

Both databases have database administrators, but there is no approveable person when the multi-database change is approved.
![image](https://github.com/oceanbase/odc/assets/46598871/3682cc55-0499-4fd2-8553-6c047e84bb6f)
![image](https://github.com/oceanbase/odc/assets/46598871/59f2b405-2020-4919-a703-822b4108b756)
![image](https://github.com/oceanbase/odc/assets/46598871/f5273983-b1b2-443b-9ff2-b7b3fd991514)

### What did you expect to happen?

Matches the corresponding database administrator.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/327897f3-19ef-4d21-812c-09692f8a7337)



![Image](https://github.com/oceanbase/odc/assets/143492234/1e960a3e-70c3-41e2-8956-f1921ed4e572)

pass
