### ISSUE TITLE
[Bug]: The operation record is blank

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2611]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/8682fd13-d9b7-49e4-a63d-b77a601464d9)

### What did you expect to happen?

No blank space present

### How can we reproduce it (as minimally and precisely as possible)?

View operation records

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8cbfb579-77f3-4107-922f-696a3ac9ae8c)

pass
