### ISSUE TITLE
[Bug]: When applying for database permissions, the display of the database name is abnormal.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#2614]
### ODC version

ODC 4.2.4

### OB version

ALL

### What happened?

As shown in the picture, there is only one database name, but it is displayed across multiple lines.
![image](https://github.com/oceanbase/odc/assets/15030999/fa5ac4ad-7289-4b1c-99ca-4c55ed67a133)

### What did you expect to happen?

A more readable presentation format is desired.

### How can we reproduce it (as minimally and precisely as possible)?

Apply for database permissions according to the screenshot.

**Comment by HSunboy** [comment]
Looks like it's been fixed in 4.3.0

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6fa330a2-f000-4cc9-9df5-8a4e87b2a687)

pass
