### ISSUE TITLE
[Bug]: When selecting a template for a multi-database change task without a template, an error will be reported

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2615]
### ODC version

ODC 4.3.0

### OB version

no related

### What happened?

Create a new multi-database change, select a project, select a database (a database without a template) in the execution node, click Select Template, and an error will be reported.
![image](https://github.com/oceanbase/odc/assets/40919496/0b4a03f8-10dd-42aa-b8da-481db9e74d1a)
![image](https://github.com/oceanbase/odc/assets/40919496/82c05c03-927a-41c5-a7dd-68cf06b43a71)

### What did you expect to happen?

When the data source has no template, clicking Select Template should not result in an error

### How can we reproduce it (as minimally and precisely as possible)?

Create a new multi-database change, select a project, select a database (a database without a template) in the execution node, click Select Template, and an error will be reported.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8b26d19a-5238-416b-b3eb-69a612d88051)

pass
