### ISSUE TITLE
[Bug]: procedure is not ordered by its name in ob mysql mode

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2617]
### ODC version

4.2.4

### OB version

not related

### What happened?

procedures is not ordered by its name

### What did you expect to happen?

procedure should be ordered by its name

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3a5effe8-8327-496b-a707-023615c24109)

pass
