### ISSUE TITLE
[Bug]: fix start debugger occur dettach debuggee session id failed

### ISSUE THREAD

**Issue by krihy** [oceanbase/odc#262]
### ODC version

4.2.1

### OB version

ob 3.2.4

### What happened?

when start a debugger action, debugger session will try to attach the session id by generated from debuggee,  If they connect to different database host, the attach action will be failed。

### What did you expect to happen?

Normal execute debugger action step by step 

### How can we reproduce it (as minimally and precisely as possible)?

Try to debug a ob oracle procedure in ob server 3.2.4 cluster

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5bf80049-962c-42ed-a93c-a3dfd0afb286)

pass
