### ISSUE TITLE
[Bug]: From the project to the database, there is no sql option when importing data

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2622]
### ODC version

ODC 4.3.0

### OB version

no related

### What happened?

From the project to the database, there is no sql option when importing data
![image](https://github.com/oceanbase/odc/assets/40919496/b076d5d3-64f2-47c5-8f6d-6c0f8022e043)
![image](https://github.com/oceanbase/odc/assets/40919496/d80652d5-2066-4d50-bef2-1c4c89206619)

### What did you expect to happen?

From the project to the database, there should be a sql option to import data

### How can we reproduce it (as minimally and precisely as possible)?

From the project to the database, there is no sql option when importing data

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/09b5d959-bdf1-4cc5-83d0-5454835eb6a8)

Unable to upload file

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/566babba-a6e0-41bc-b869-987ed2c5e74a)

pass
