### ISSUE TITLE
[Bug]: In oracle mode, archiving fails when table field name is the same as type

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2627]
### ODC version

ODC424

### OB version

independent

### What happened?

In oracle mode, archiving fails when table field name is the same as type
![image](https://github.com/oceanbase/odc/assets/59468957/c9a38e0c-780a-45ba-825d-87528cbefaa5)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

```
CREATE TABLE "TEST_DLM" (
  "ID" NUMBER(*,0) DEFAULT NULL NOT NULL ENABLE,
   "DATE" DATE DEFAULT NULL,
  CONSTRAINT "pk1" PRIMARY KEY ("ID")
) 
```

**Comment by Huangxiao-mas** [comment]
test pass

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/1da7d199-310e-4549-b37a-00801a0e0a4e)
pass
