### ISSUE TITLE
[Bug]: Expired databases can still be selected for multi database changes

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2629]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/07197374-c561-4895-bb8c-34f57fe5cd2a)

### What did you expect to happen?

Invalid databases cannot be selected for multi database changes

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824](https://github.com/oceanbase/odc-client/commit/ffbf2c9250018c2aef3f11dbf83c70f0c7fa8824)
            ------
            陈朝俊
            Tue Jun 4 20:45:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/89625df8-ba9f-4914-9c8d-ab5bc7db26a5)

You can still choose when there are issues with the database

**Comment by HSunboy** [comment]
Fixed In Commit [c1771da43ce0fb4f57ced3c7211e057475dd25ac](https://github.com/oceanbase/odc-client/commit/c1771da43ce0fb4f57ced3c7211e057475dd25ac)
            ------
            陈朝俊
            Thu Jun 6 16:20:14 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/03ec0fb2-ac57-4c16-a9df-523a596dde2b)

pass
