### ISSUE TITLE
[Bug]: Import file without data failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2633]
### ODC version

odc430

### OB version

ob430

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/10938431-80a5-4680-9a2c-35b14b13fa0a)

### What did you expect to happen?

Import successful

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Table
CREATE TABLE tt_column_store (c1 int PRIMARY KEY, c2 int , c3 int) WITH COLUMN GROUP (each column);
2. Export Table
3. Import file

**Comment by LuckyPickleZZ** [comment]
![Image](https://github.com/oceanbase/odc/assets/36879124/12575455-22f5-4e36-9e33-08ab19b7ad9b)
