### ISSUE TITLE
[Bug]: Disabled users can set up library administrators

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2635]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/743e0c51-a059-4ee0-8b13-d47b62b413e5)

### What did you expect to happen?

Disabled user unable to display

### How can we reproduce it (as minimally and precisely as possible)?

1. Create users, disable users
2. Add users within the project

**Comment by HSunboy** [comment]
Fixed In Commit [af3b00619b23afac5d27a010c0b1bc5bffdbae67](https://github.com/oceanbase/odc-client/commit/af3b00619b23afac5d27a010c0b1bc5bffdbae67)
            ------
            畅晚
            Tue Jun 4 15:46:46 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/914c7a79-d809-463b-830c-c73f36ad409a)

pass
