### ISSUE TITLE
[Bug]: there is no alert when testing a standby cluster

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2643]
### ODC version

4.3.0

### OB version

not related

### What happened?

1. prepare a standby cluster
2. test it
<img width="219" alt="截屏2024-06-04 20 18 11" src="https://github.com/oceanbase/odc/assets/22992296/eb2dd3e1-8932-4f56-9c46-84b54d472fe7">

```json
{
    "data": {
        "active": false,
        "errorCode": "ObWeakReadConsistencyRequired",
        "errorMessage": "当前数据源是备实例，仅支持弱一致性读。您可以在数据源高级设置中，设置连接初始化脚本 set ob_read_consistency = 'WEAK'; 来解决。",
        "type": null
    },
    "durationMillis": 667,
    "httpStatus": "OK",
    "requestId": "xxx",
    "server": "xxx",
    "successful": true,
    "timestamp": 1717503479.001000000,
    "traceId": "xxx"
}
```

as you can see, the back end gives a new error code and the front end need to adapt for it.

### What did you expect to happen?

the front end should notice user that it is a stand by cluster~

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened' and you may ask @yhilmare to get the test env

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/031a050c-d027-4d3c-bbb7-455231831895)

pass
