### ISSUE TITLE
[Bug]: failed to select multi people when adding project member

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2652]
### ODC version

4.2.4

### OB version

not related

### What happened?

1. add project owner:
<img width="782" alt="截屏2024-06-05 12 23 46" src="https://github.com/oceanbase/odc/assets/22992296/7e837f86-8e65-4be2-8db9-cfab35151913">

2. select one:
<img width="789" alt="截屏2024-06-05 12 24 16" src="https://github.com/oceanbase/odc/assets/22992296/cc09c8dc-0387-49df-82a2-20570b56ee8b">

3. search a person and select he/she:
<img width="768" alt="截屏2024-06-05 12 25 01" src="https://github.com/oceanbase/odc/assets/22992296/1c6b8d79-7cdf-4b12-a1e9-e71673d2fc9a">

### What did you expect to happen?

I have selected the person lalala and I should maintain my selection when I search and select another person.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yizhouxw** [comment]
another consideration is username should ordered, currenttly it is order by accoutName, not username (nickNam)

**Comment by yhilmare** [comment]
> another consideration is username should ordered, currenttly it is order by accoutName, not username (nickNam)

okay, I will fix this~

**Comment by HSunboy** [comment]
Fixed In Commit [062b0f234e2debe9408d924e796e477a722a9d16](https://github.com/oceanbase/odc-client/commit/062b0f234e2debe9408d924e796e477a722a9d16)
            ------
            畅晚
            Thu Jun 6 16:18:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ca6b2d8a-e08d-4e63-b26e-832ffc84e008)

pass
