### ISSUE TITLE
[Bug]: The read and write performance in the archive task details needs to be displayed in units

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2653]
### ODC version

ODC430

### OB version

independent

### What happened?

The read and write performance in the archive task details needs to be displayed in units
![image](https://github.com/oceanbase/odc/assets/59468957/42f0c2c7-77e9-4777-92d3-83dad38b525b)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [062b0f234e2debe9408d924e796e477a722a9d16](https://github.com/oceanbase/odc-client/commit/062b0f234e2debe9408d924e796e477a722a9d16)
            ------
            畅晚
            Thu Jun 6 16:18:36 2024 +0800
