### ISSUE TITLE
[Bug]: After checking to enable target table structure synchronization, the prompt about not enabling it should be hidden

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2654]
### ODC version

ODC430

### OB version

independent

### What happened?

After checking to enable target table structure synchronization, the prompt about not enabling it should be hidden
![image](https://github.com/oceanbase/odc/assets/59468957/45c89d37-3575-4daf-9554-c7a458e27d40)
![image](https://github.com/oceanbase/odc/assets/59468957/b863fe47-d2f3-41ea-a0b3-bb7de51de25e)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [062b0f234e2debe9408d924e796e477a722a9d16](https://github.com/oceanbase/odc-client/commit/062b0f234e2debe9408d924e796e477a722a9d16)
            ------
            畅晚
            Thu Jun 6 16:18:36 2024 +0800
