### ISSUE TITLE
[Bug]: Adjust the task timeout to 0.0000001, check the task details, and the task duration becomes unlimited，Limit input to non-integer

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2656]
### ODC version

ODC430

### OB version

independent

### What happened?

Adjust the task timeout to 0.0000001, check the task details, and the task duration becomes unlimited
![image](https://github.com/oceanbase/odc/assets/59468957/42c57b8e-51cc-4a1b-b161-9fbba0888c3e)

### What did you expect to happen?

Limit input to non-integer

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [062b0f234e2debe9408d924e796e477a722a9d16](https://github.com/oceanbase/odc-client/commit/062b0f234e2debe9408d924e796e477a722a9d16)
            ------
            畅晚
            Thu Jun 6 16:18:36 2024 +0800
