### ISSUE TITLE
[Bug]: New data archiving task click Submit but no translation

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2657]
### ODC version

ODC 4.3.0

### OB version

no related

### What happened?

When you create a new data archiving task, the first click on Create will result in an error message, and then the interface will not respond when you click Create again.
![image](https://github.com/oceanbase/odc/assets/40919496/da709cb3-a1ed-457d-a902-52a457a8fab4)

### What did you expect to happen?

Create a new data archiving task. Clicking Create for the first time will cause an error. Modify some parameters and then click Create again. The interface should respond accordingly.

### How can we reproduce it (as minimally and precisely as possible)?

When you create a new data archiving task, the first click on Create will result in an error message, and then the interface will not respond when you click Create again.

**Comment by HSunboy** [comment]
Fixed In Commit [062b0f234e2debe9408d924e796e477a722a9d16](https://github.com/oceanbase/odc-client/commit/062b0f234e2debe9408d924e796e477a722a9d16)
            ------
            畅晚
            Thu Jun 6 16:18:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4b94d164-80f4-46e5-be18-4ee262c38f1e)

pass
