### ISSUE TITLE
[Bug]: multiple data sql files will be generated when exporting data

### ISSUE THREAD

**Issue by caizequan** [oceanbase/odc#266]
### ODC version

4.2.0

### OB version

2.2.77-bp12

### What happened?

When exporting data, multiple data sql files will be generated.

### What did you expect to happen?

When exporting data, only one SQL file is exported.

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/42692197/7cb00a51-6162-4785-b35a-06531e8cad94)

![image](https://github.com/oceanbase/odc/assets/42692197/e248040f-3043-4969-b37a-cf77bd694a30)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/56121964-ff1c-41a4-8ad0-1e5d4507d90e)

pass
