### ISSUE TITLE
[Bug]: Check the log and the interface reports a null pointer，Log page is refreshing execution details request

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2660]
### ODC version

ODC430

### OB version

independent

### What happened?

Check the log and the interface reports a null pointer
![image](https://github.com/oceanbase/odc/assets/59468957/509eb293-1329-4d5c-95f8-ae3c48b17ceb)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

chat priavtely

**Comment by HSunboy** [comment]
Fixed In Commit [062b0f234e2debe9408d924e796e477a722a9d16](https://github.com/oceanbase/odc-client/commit/062b0f234e2debe9408d924e796e477a722a9d16)
            ------
            畅晚
            Thu Jun 6 16:18:36 2024 +0800
