### ISSUE TITLE
[Bug]: After initiating the task again, click Create New Archive Task, and the Structure Synchronization option will be checked by default.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2665]
### ODC version

ODC430

### OB version

independent

### What happened?

After initiating the task again, click Create New Archive Task, and the Structure Synchronization option will be checked by default.
![image](https://github.com/oceanbase/odc/assets/59468957/6b525905-fe3b-4e0a-a576-7d9e12adc0ce)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

1. Initiate a task again,
2. Create a new task

**Comment by HSunboy** [comment]
Fixed In Commit [062b0f234e2debe9408d924e796e477a722a9d16](https://github.com/oceanbase/odc-client/commit/062b0f234e2debe9408d924e796e477a722a9d16)
            ------
            畅晚
            Thu Jun 6 16:18:36 2024 +0800
