### ISSUE TITLE
[Bug]: Before it is disabled, the library can still be selected by setting the library again for the project's librarian

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2669]
### ODC version

ODC 4.3.0

### OB version

no related

### What happened?

The disabled user was the librarian of the project before it was disabled, and after the disabling user, set the librarian of the project again, click OK, and the save can still be successful
![image](https://github.com/oceanbase/odc/assets/40919496/ba80a7c1-4fd5-4765-af77-90eed1cc350a)

### What did you expect to happen?

A disabled user is a librarian of a project before being disabled, and after being disabled, a librarian for the project is set again, and the disabled user should not be a librarian of the library again

### How can we reproduce it (as minimally and precisely as possible)?

The disabled user was the librarian of the project before it was disabled, and after the disabling user, set the librarian of the project again, click OK, and the save can still be successful

**Comment by HSunboy** [comment]
Fixed In Commit [062b0f234e2debe9408d924e796e477a722a9d16](https://github.com/oceanbase/odc-client/commit/062b0f234e2debe9408d924e796e477a722a9d16)
            ------
            畅晚
            Thu Jun 6 16:18:36 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/c2ed2431-b0f9-4a9d-bafa-1b80f0b0bbcc)

pass
