### ISSUE TITLE
[Bug]: SYS database type view failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2678]
### ODC version

odc430

### OB version

ob4215

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/8953cb28-9bb7-4a95-aae4-ae96605fac60)

### What did you expect to happen?

View successful

### How can we reproduce it (as minimally and precisely as possible)?

View sys database types

**Comment by yhilmare** [comment]
external issue id: 38268884

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/user-attachments/assets/d005bb02-d583-4a5b-9d45-7815fc3584e4)

pass
