### ISSUE TITLE
[Bug]: ODC desktop version, scheduled task template error

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2680]
### ODC version

ODC4.3.0

### OB version

No related

### What happened?

Use the odc desktop version to view the odc.log log and report errors
![image](https://github.com/oceanbase/odc/assets/40919496/cebd18ed-bdc7-43e4-b10b-f7de4c6ce402)

### What did you expect to happen?

Scheduled task update template is normal

### How can we reproduce it (as minimally and precisely as possible)?

Use the odc desktop version to view the odc.log log and report errors

**Comment by zijiacj** [comment]
When the collection id to be updated is empty. Do not access the database. The code has been merged with other PRS
