### ISSUE TITLE
[Bug]: An error occurred when applying for database permission

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2683]
### ODC version

ODC 430

### OB version

No related.

### What happened?

The database permission task cannot be delivered.
![image](https://github.com/oceanbase/odc/assets/46598871/ec3852aa-40c0-4629-846d-76a9326850b2)
![image](https://github.com/oceanbase/odc/assets/46598871/c4216af8-71da-4db0-acce-0ae8dc553ae8)
![image](https://github.com/oceanbase/odc/assets/46598871/f029b7a6-dd64-4bdb-896b-e789e817a782)

### What did you expect to happen?

The database permission task is successfully delivered.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver the database permission task.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1ea5c4d8-8c9a-434a-ad6f-9c60635e50b3)

pass
