### ISSUE TITLE
[Feature]: view the formatted content of debug variables

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2685]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

the variable value is not formatted and It will not be display when the length of it is too long:
<img width="1094" alt="截屏2024-06-06 15 23 55" src="https://github.com/oceanbase/odc/assets/22992296/b8ab10e0-0fd3-48fe-b133-e5cd5d979664">

as you can see: the content of variables contain several white space and breaking lines but the variable panel doesn't display them.

### Additional context

we may add a 'View' button to display formatted content

**Comment by yhilmare** [comment]
![截屏2024-06-11 11 11 56](https://github.com/oceanbase/odc/assets/22992296/0a716a67-da4f-41fb-a81c-e8e3ed12cece)
![截屏2024-06-11 11 12 06](https://github.com/oceanbase/odc/assets/22992296/397ad70a-0581-4edd-810d-eebfdc7392dc)

**Comment by HSunboy** [comment]
Fixed In Commit [8eb8f0c10308e069733ae00451a2f902820125b4](https://github.com/oceanbase/odc-client/commit/8eb8f0c10308e069733ae00451a2f902820125b4)
            ------
            xiaokang
            Thu Sep 5 10:31:17 2024 +0800

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/user-attachments/assets/bf7f7ce0-5f1c-4007-8d1f-85d9b5ef837f)
pass
