### ISSUE TITLE
[Bug]: failed to view table data

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2689]
### ODC version

4.2.4

### OB version

not related

### What happened?

`api/v2/datasource/sessions/${session_id}/queryData` is a sync api and this api may cost too much time~ it will lead to api timeout, we should make it async.

### What did you expect to happen?

do not timeout

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by zijiacj** [comment]
have fixed via pr https://github.com/oceanbase/odc/pull/2848. The problem was that the timeout unit for the result set was wrong and was reduced by 1000
