### ISSUE TITLE
[Bug]: The first synchronization of library metadata will not take effect, but it will take effect the second time

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2691]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/ebf044a6-97e5-47d2-bffc-76d4f013e67a)
![image](https://github.com/oceanbase/odc/assets/143492234/9ce3eb0f-9559-487c-ac0d-7f4900bc522d)

### What did you expect to happen?

The first synchronization of library metadata takes effect

### How can we reproduce it (as minimally and precisely as possible)?

Synchronize library metadata

**Comment by smallsheeeep** [comment]
I cannot understand what you want to explain!

**Comment by HSunboy** [comment]
Fixed In Commit [a380e82977f3e873950e15cc9d885026b7e4d8b2](https://github.com/oceanbase/odc-client/commit/a380e82977f3e873950e15cc9d885026b7e4d8b2)
            ------
            畅晚
            Fri Jun 7 16:21:43 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4b1f6a88-167c-4713-b2e9-0dbab8dd3f64)

pass
