### ISSUE TITLE
[Bug]: Create a periodic task, approval execution failed 'ODC_SCHEDULE_TRIGGER not found'

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2692]
### ODC version

ODC430

### OB version

independent

### What happened?

Create a periodic task, and the approval execution fails
![image](https://github.com/oceanbase/odc/assets/59468957/440b5d6b-d9de-45e0-a0e1-151de1d4200a)
![image](https://github.com/oceanbase/odc/assets/59468957/40d800fa-3671-46d1-89b0-ba61000a40db)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

.

**Comment by guowl3** [comment]
When the task is configured for immediate execution, editing and disabling operations are not allowed.

**Comment by HSunboy** [comment]
Fixed In Commit [26908a624285c7c3c9b0347faacaeec650e9225f](https://github.com/oceanbase/odc-client/commit/26908a624285c7c3c9b0347faacaeec650e9225f)
            ------
            畅晚
            Fri Jun 7 09:54:57 2024 +0800
