### ISSUE TITLE
[Bug]: The pre-check does not fail when a multi-database change task is delivered for a database that has no change permission

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2696]
### ODC version

ODC 430

### OB version

No related.

### What happened?

Execute the create statement on a database that does not have permission to change, and the pre-check does not fail.
![image](https://github.com/oceanbase/odc/assets/46598871/55d988f9-f524-4ed9-9ce4-8fa8e7b6b162)

### What did you expect to happen?

For database without permissions, the precheck should fail.
![image](https://github.com/oceanbase/odc/assets/46598871/7e6f7187-eb11-4975-8610-1550dd6d7785)

### How can we reproduce it (as minimally and precisely as possible)?

The user does not have the permission to change the chz database. In the multi-database change, execute “create table chz.table(a int);”

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/7099e6ee-dd68-4162-aa96-ecd634190961)

Database without change permission cannot be selected
