### ISSUE TITLE
[Bug]: Unable to initiate deletion request after clicking delete on invalid template for multi library changes

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2711]
### ODC version

odc430

### OB version

*

### What happened?

Unable to initiate deletion request after clicking delete on invalid template for multi library changes
![image](https://github.com/oceanbase/odc/assets/143492234/16c8cfe1-3b70-4e2c-9b58-a30223712218)

### What did you expect to happen?

Invalid templates can be deleted

### How can we reproduce it (as minimally and precisely as possible)?

Delete Invalid Template

**Comment by HSunboy** [comment]
Fixed In Commit [5ba68dc36371b683967d1d15a7852071110946a9](https://github.com/oceanbase/odc-client/commit/5ba68dc36371b683967d1d15a7852071110946a9)
            ------
            xiaokang
            Fri Jun 7 16:07:17 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/acea44bd-128e-4e13-a914-1316a8e03ded)

pass
