### ISSUE TITLE
[Bug]: Inconsistency between comments and reality

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2715]
### ODC version

odc430

### OB version

ob4310

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/95e0394e-9f4d-41a2-b4ae-3d5be0ba1189)
![image](https://github.com/oceanbase/odc/assets/143492234/90c12353-7687-4b00-97c7-e553225a9085)

### What did you expect to happen?

Col2 is not a primary key and does not have auto increment

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Table
CREATE TABLE  "NON_PARTRANGE_RANGE_PRI2" (
  "COL1" NUMBER(*,0) DEFAULT NULL NOT NULL ENABLE,
  "COL2" NUMBER DEFAULT NULL,
  "COL3" CHAR(10) DEFAULT NULL,
  "COL4" VARCHAR2(10) DEFAULT NULL,
  "COL8" TIMESTAMP(6) DEFAULT NULL,
  CONSTRAINT "NON_PARTRANGE_RANGE_PRI2_OBPK_1716531531720584" PRIMARY KEY ("COL1")
) COMPRESS FOR ARCHIVE REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0
 partition by range("COL1")
(partition "P1" values less than (500),
partition "P2" values less than (1000),
partition "P3" values less than (1500),
partition "P4" values less than (2000),
partition "P5" values less than (MAXVALUE));
COMMENT ON COLUMN "SHILIN"."NON_PARTRANGE_RANGE_PRI2"."COL1" IS '11';
2. Add data
3. query

**Comment by HSunboy** [comment]
Fixed In Commit [456a182a2dc91b7b9664456bb9e8bc5d810a642b](https://github.com/oceanbase/odc-client/commit/456a182a2dc91b7b9664456bb9e8bc5d810a642b)
            ------
            xiaokang
            Fri Jun 7 17:34:49 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ca1f9bb0-3bf4-4897-89f0-e7208c42f256)

pass
