### ISSUE TITLE
[Bug]: Personal space viewing task error

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2717]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2ee4d0ca-5a80-4396-8c44-9b16d921690b)

### What did you expect to happen?

No error reported

### How can we reproduce it (as minimally and precisely as possible)?

Personal Space Viewing Tasks

**Comment by yhilmare** [comment]
the front end attempt get detail of a project having id -1

**Comment by HSunboy** [comment]
Fixed In Commit [efa7991f25303ecc7dfeaeb300c2cc8722c7913f](https://github.com/oceanbase/odc-client/commit/efa7991f25303ecc7dfeaeb300c2cc8722c7913f)
            ------
            畅晚
            Tue Jun 11 15:39:43 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/430921ac-10c0-4013-b3ff-91773b177069)

pass
