### ISSUE TITLE
[Bug]: The sql generated by clicking on the recycle bin to restore is very slow

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#272]
### ODC version

ODC4.2.1

### OB version

Oceanbase4.1.0

### What happened?

The sql generated by clicking on the recycle bin to restore is very slow

### What did you expect to happen?

Click Restore in the recycle bin, and the corresponding sql will be displayed immediately

### How can we reproduce it (as minimally and precisely as possible)?

1. open recycle bin
2. delete table
3. Enter the Recycle Bin, click Restore
![image](https://github.com/oceanbase/odc/assets/59468957/0a7e7b14-67c5-481a-8c57-5514f0f1a9b0)

**Comment by MarkPotato777** [comment]
It has not been reproduced yet.
