### ISSUE TITLE
[Bug]: The task I initiated shows all the extra tasks

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2722]
### ODC version

odc430

### OB version

*

### What happened?

I initiated it
![image](https://github.com/oceanbase/odc/assets/143492234/686540e4-5c18-43bb-9ba2-976135af9855)
All tasks
![image](https://github.com/oceanbase/odc/assets/143492234/e4fb456f-9800-4090-bd8d-b050a9d51ddf)

### What did you expect to happen?

All tasks are extra than the ones I initiated

### How can we reproduce it (as minimally and precisely as possible)?

View all tasks and tasks initiated by me

**Comment by yhilmare** [comment]
the project id of the tickets that appeared in 'I created' and not appeared in 'total ticket' is -1, that is to say those tickets are created in individual space~

**Comment by yhilmare** [comment]
these tickets are generated by sql plan, partition plan ant etc.

**Comment by sl01388797** [comment]
SQL plan

![Image](https://github.com/oceanbase/odc/assets/143492234/89f34a74-9506-4520-8465-10f17314fdbd)



![Image](https://github.com/oceanbase/odc/assets/143492234/d9fce898-939b-4490-abfb-90132be66f49)

Partition plan


![Image](https://github.com/oceanbase/odc/assets/143492234/78ee86f6-f628-4e43-b922-311973cdab2d)



![Image](https://github.com/oceanbase/odc/assets/143492234/f34df3ca-b6d1-4031-8ed2-755acd32798a)
