### ISSUE TITLE
[Bug]: No database tab in global search

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2727]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/514b0625-93e0-46b0-9f2a-9e1baac9b35b)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/6f04a316-633d-4e7b-a040-25cc3e217874)

### How can we reproduce it (as minimally and precisely as possible)?

Conduct a global search

**Comment by HSunboy** [comment]
Fixed In Commit [7e9548985c9d1dae81911e06802b50444f4cd502](https://github.com/oceanbase/odc-client/commit/7e9548985c9d1dae81911e06802b50444f4cd502)
            ------
            畅晚
            Mon Jul 8 21:28:40 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/0e11bd61-e481-41bf-9aaa-b7146a82ebd7)

pass
