### ISSUE TITLE
[Bug]: Missing metabase synchronization button when global search fails to find content

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2728]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/839f07ae-d3be-4ce5-af1e-c8359f7edbcf)

### What did you expect to happen?

When there is no content found in the global search, there is a metabase synchronization button present

### How can we reproduce it (as minimally and precisely as possible)?

Global search is empty

**Comment by HSunboy** [comment]
Fixed In Commit [7e9548985c9d1dae81911e06802b50444f4cd502](https://github.com/oceanbase/odc-client/commit/7e9548985c9d1dae81911e06802b50444f4cd502)
            ------
            畅晚
            Mon Jul 8 21:28:40 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/4bc9f6c9-4f1d-4fa2-92bd-d49374034523)

pass
