### ISSUE TITLE
[Bug]: The data of the cleanup task is processed with delay and the statistics are incorrect

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#2731]
### ODC version

odc4.3.0

### OB version

no related

### What happened?

![image](https://github.com/oceanbase/odc/assets/40919496/083d3cdb-5681-4fed-badd-b869a26a865a)
When a data cleanup task is executed, the task shows that the task has been completed, the actual number of processed rows is 0, and the number of scanned rows is 0, but the actual data is delayed for cleaning. The statistics are displayed incorrectly

### What did you expect to happen?

The data is cleaned in real time and the statistics are displayed correctly

### How can we reproduce it (as minimally and precisely as possible)?

When a data cleanup task is executed, the task shows that the task has been completed, the actual number of processed rows is 0, and the number of scanned rows is 0, but the actual data is delayed for cleaning. The statistics are displayed incorrectly

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/071e5845-f499-41f6-9572-a8ef6ad31227)
The problem still exists

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/44d0e9ab-2e94-4ebd-8722-9ffcdc8fe9a9)
pass
