### ISSUE TITLE
[Bug]: oracle datasource nls_date_format do not use "set "command

### ISSUE THREAD

**Issue by onthewayaways** [oceanbase/odc#2736]
### ODC version

ODC 4.3.0 

### OB version

it is not ob ,it is oracle

### What happened?

set command is used to mysql or ob database ,not use to oracle. 
<img width="1011" alt="截屏2024-06-13 10 08 13" src="https://github.com/oceanbase/odc/assets/22992296/296692f9-774c-4c6b-a782-bd374ce7241c">

### What did you expect to happen?

"set parameter_xxx=aaa"  change to "alter session set parameter_xxx=aaa"

### How can we reproduce it (as minimally and precisely as possible)?

"set parameter_xxx=aaa"  change to "alter session set parameter_xxx=aaa"

**Comment by tonghan-gsh** [comment]
pass
