### ISSUE TITLE
[Bug]: Unable to see database name column when the browser is zoomed out

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2741]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/f98d1dfd-2692-43b2-9cd8-dc841880f178)

### What did you expect to happen?

Even when the browser is zoomed out, the database name column can still be seen

### How can we reproduce it (as minimally and precisely as possible)?

Zoom out browser on project page

**Comment by HSunboy** [comment]
Fixed In Commit [73ec2d8b7d03d56a040bf47a8a61c3f1c6a8c715](https://github.com/oceanbase/odc-client/commit/73ec2d8b7d03d56a040bf47a8a61c3f1c6a8c715)
            ------
            xiaokang
            Tue Jun 18 18:20:45 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/629f17c5-292d-4902-a10a-1544ee9e4f31)

pass
