### ISSUE TITLE
[Bug]: Global search item font size is too small, line spacing is too small

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2742]
### ODC version

odc430

### OB version

*

### What happened?

Global search item font size is too small, line spacing is too small
![image](https://github.com/oceanbase/odc/assets/143492234/e4b75500-fc37-4eee-b500-924f2e3c9c51)

### What did you expect to happen?

Increase font size and line spacing

### How can we reproduce it (as minimally and precisely as possible)?

View global search

**Comment by HSunboy** [comment]
Fixed In Commit [7e9548985c9d1dae81911e06802b50444f4cd502](https://github.com/oceanbase/odc-client/commit/7e9548985c9d1dae81911e06802b50444f4cd502)
            ------
            畅晚
            Mon Jul 8 21:28:40 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/84325a63-181b-46ec-b353-21a3eeb5bfa0)

pass
