### ISSUE TITLE
[Bug]: After importing the data source, the front-end only retrieves one more data source per refresh

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2743]
### ODC version

odc430

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/f22b6f6a-9e2e-4690-8751-4f3b52b92dcd)

### What did you expect to happen?

Obtain all data sources at once

### How can we reproduce it (as minimally and precisely as possible)?

Refresh after importing multiple data sources

**Comment by HSunboy** [comment]
![Image](https://github.com/oceanbase/odc/assets/14886044/50ec518c-7a16-443b-87bc-ca80e03c5bed)

The server did not return all the imported data

**Comment by HSunboy** [comment]
Fixed In Commit [1a67d8ffc7741ac195123f9886ccb5606ccb8710](https://github.com/oceanbase/odc-client/commit/1a67d8ffc7741ac195123f9886ccb5606ccb8710)
            ------
            xiaokang
            Wed Jun 19 10:13:46 2024 +0800

**Comment by sl01388797** [comment]
pass
