### ISSUE TITLE
[Bug]: Multi-database change subtask work order description needs to be optimized

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2744]
### ODC version

ODC 4.3.0

### OB version

No related.

### What happened?

Multi-database change subtask work order description needs to be optimized.
![image](https://github.com/oceanbase/odc/assets/46598871/f403b687-3f0e-4dfd-aa17-df66aed9dd6c)

### What did you expect to happen?

The description of the work order is as follows:
【环境】多库变更 10004 第 2  批 $database_name

### How can we reproduce it (as minimally and precisely as possible)?

View the work order description of the multi-database change subtask.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/7f14aca9-1aba-42a8-b6f9-7ab021fd27ed)

pass
