### ISSUE TITLE
[Bug]: bastion integration document missing odc.integration.bastion.enabled parameter 

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#2751]
### ODC version

v4.3.0

### OB version

not related

### What happened?

 bastion integration document missing odc.integration.bastion.enabled parameter .

it is involve in ODC v4.3.0, however there is no explianation in user manual https://www.oceanbase.com/docs/common-odc-1000000000876792

### What did you expect to happen?

add odc.integration.bastion.enabled parameter explanation in document

### How can we reproduce it (as minimally and precisely as possible)?

N/A

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/c4f26f59-c59d-420f-bc75-def1801697b0)

pass
