### ISSUE TITLE
[Bug]: 'User Project Not Fount' error while try bastion ingegration without enabled

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#2752]
### ODC version

v4.2.4/v4.3.0

### OB version

not related

### What happened?

 'User Project Not Fount' error while try bastion ingegration without enabled
![image](https://github.com/oceanbase/odc/assets/54161870/b80c41b0-8753-40ab-a31b-4337ae3c7204)

### What did you expect to happen?

the error message should readable, such as 'User project not found, please contact adminitrator, confirm the bastion integration is enabled'

### How can we reproduce it (as minimally and precisely as possible)?

jump link to odc with NewTempSession gateway action

**Comment by yizhouxw** [comment]
@HSunboy  this error message was thrown by frontend, let's refine message

**Comment by HSunboy** [comment]
No default project found with project name: USER_PROJECT_{login.user?.accountName}

**Comment by HSunboy** [comment]
Fixed In Commit [2c19a3dc9b86794c2e292982467cfd5dfa021cba](https://github.com/oceanbase/odc-client/commit/2c19a3dc9b86794c2e292982467cfd5dfa021cba)
            ------
            xiaokang
            Thu Jul 25 10:54:19 2024 +0800

**Comment by Huangxiao-mas** [comment]
![Image](https://github.com/user-attachments/assets/bc879147-9178-4f5f-a354-57ef01b30f5d)

pass

**Comment by Huangxiao-mas** [comment]
![Image](https://github.com/user-attachments/assets/5b09672a-8674-4204-9ff9-8c18fdf58639)
