### ISSUE TITLE
[Bug]: Data archiving execution plan paging optimization

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2759]
### ODC version

ODC

### OB version

independent

### What happened?

Data archiving execution plan paging optimization
![image](https://github.com/oceanbase/odc/assets/59468957/7c96d0f4-9060-41f7-b4d5-9e85b532dd8a)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800
