### ISSUE TITLE
[Bug]: ODC 4.3.0 would fail to start in client mode 

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#2760]
### ODC version

4.3.0

### OB version

-

### What happened?

ODC 4.3.0 would fail to start in client mode.
![image](https://github.com/oceanbase/odc/assets/36879124/82ad31dc-b7f2-4a57-839d-70b47e6f5177)

### What did you expect to happen?

Start normally.

### How can we reproduce it (as minimally and precisely as possible)?

Clear ODC completely, including h2 db files. Then install ODC 4.3.0.

**Comment by yhilmare** [comment]
this issue is involved by this pr #2699

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/daecf753-f8b4-4297-bdbb-5b1e8b87effb)
