### ISSUE TITLE
[Bug]: //Change to/after formatting/

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2768]
### ODC version

odc430bp

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/fbe0db5d-9552-4b1c-85c3-096371f9f3eb)

### What did you expect to happen?

//Unchanged after formatting

### How can we reproduce it (as minimally and precisely as possible)?

Format//

**Comment by HSunboy** [comment]
Fixed In Commit [362f5dc199d2c4638abe184a1e5314663cb4c382](https://github.com/oceanbase/odc-client/commit/362f5dc199d2c4638abe184a1e5314663cb4c382)
            ------
            xiaokang
            Wed Jun 19 11:43:40 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/c717da8b-d1b8-46a2-9c64-28dc2b8758bf)

pass
