### ISSUE TITLE
[Bug]: Unable to format the selected statement

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2769]
### ODC version

odc430bp

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/e5be9f13-6f06-40fe-947c-6f9faf339f22

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/5e7d968b-f70f-426b-8235-aa056e5c9cbe)

### How can we reproduce it (as minimally and precisely as possible)?

Format the selected statement

**Comment by HSunboy** [comment]
Fixed In Commit [362f5dc199d2c4638abe184a1e5314663cb4c382](https://github.com/oceanbase/odc-client/commit/362f5dc199d2c4638abe184a1e5314663cb4c382)
            ------
            xiaokang
            Wed Jun 19 11:43:40 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/1c8616d6-f871-43bc-941d-c8a43e98f2ab)
pass
