### ISSUE TITLE
[Bug]: transfer would fail when the data files are empty

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#2774]
### ODC version

4.3.0

### OB version

-

### What happened?

If import a zip file , and all subfiles are empty, the task will fail.

### What did you expect to happen?

the task should success

### How can we reproduce it (as minimally and precisely as possible)?

Export some empty tables, and re-import them.

**Comment by sl01388797** [comment]
Import only after exporting data

![Image](https://github.com/oceanbase/odc/assets/143492234/0825e90f-0bf4-4807-b8ad-5f6effa18173)

Export structure and data before importing


![Image](https://github.com/oceanbase/odc/assets/143492234/f79eb39c-95f5-412d-b5d7-661e2e89c5f3)
