### ISSUE TITLE
[Bug]: Confirm that the SQL window formatting button is invalid

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2778]
### ODC version

odcbp1

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2042b5cb-4610-42a9-803b-e0a121c7e671)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/db8ad385-1846-4c59-b55f-9c306a307820)

### How can we reproduce it (as minimally and precisely as possible)?

Create a table and click format when confirming SQL

**Comment by HSunboy** [comment]
Fixed In Commit [d87fe60c5f8e5d7b15466c0bb9f8fc6c916674ed](https://github.com/oceanbase/odc-client/commit/d87fe60c5f8e5d7b15466c0bb9f8fc6c916674ed)
            ------
            xiaokang
            Wed Jun 19 11:52:25 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/c481de8c-45b1-4104-9aa5-888741d5d50f)

pass
