### ISSUE TITLE
[Bug]: The database change progress bar may go directly from 0 to 100%

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2780]
### ODC version

ODC430

### OB version

independent

### What happened?

The database change progress bar may go directly from 0 to 100%
![image](https://github.com/oceanbase/odc/assets/59468957/013f1114-94cb-4df2-afc8-4d73595a7bd0)
![image](https://github.com/oceanbase/odc/assets/59468957/10e10b33-6960-4bb3-a2e3-535a64e04282)

### What did you expect to happen?

Show detailed progress

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by yhilmare** [comment]
I started up a database change task that contains multi statements and the percentage goes as expected:
<img width="1156" alt="截屏2024-07-09 16 05 49" src="https://github.com/oceanbase/odc/assets/22992296/619f8322-3ba0-41d0-ae8a-aafbfdfd4d25">
