### ISSUE TITLE
[Bug]: Startup parameter ODC_APP_EXTRA_ARGS does not work as expected

### ISSUE THREAD

**Issue by powerfooI** [oceanbase/odc#2781]
### ODC version

4.3.0

### OB version

4.2.1.6

### What happened?

When I was developing in integrating ODC in [ob-operator](https://github.com/oceanbase/ob-operator), I found that the startup argument `ODC_APP_EXTRA_ARGS` not working. 

(The following IP address is an internal mock one)

I set `ODC_APP_EXTRA_ARGS`="--odc.integration.bastion.account.query.request-url='http://10.42.0.1:18084/api/v1/auth/${account_verify_token}' --odc.integration.bastion.enabled='true' --odc.integration.bastion.account.auto-login-enabled='true' --odc.connect.database.sync.block-internal-database='false' --odc.database.schema.sync.exclude-schemas.ob-mysql=''"

And I found that the `sun.java.command` indeed contains the extra args in `odc.log`.

![image](https://github.com/oceanbase/odc/assets/26134111/201ada90-bf97-4f43-9b53-5cb077188dd2)

But the parameters do not work at all. I need to update them in the metadata database and restart odc server to make them work as expected.

### What did you expect to happen?

Parameters set in `ODC_APP_EXTRA_ARGS` work as expected. The bastion link could be opened normally.

### How can we reproduce it (as minimally and precisely as possible)?

Run odc server with environment variable `ODC_APP_EXTRA_ARGS` set to `--odc.integration.bastion.enabled='true' --odc.integration.bastion.account.auto-login-enabled='true'`, visit URL `http://xx.xx.xx.xx:8989/#/gateway/test` and you will found "session expired, please log in again". After login, visit the above URL again and you will get another error message.

![image](https://github.com/oceanbase/odc/assets/26134111/1afce3a4-188b-4c93-9dfe-222dd6267319)

![image](https://github.com/oceanbase/odc/assets/26134111/15b3ff5e-e01b-4d41-af1f-d108025013cf)

If the parameters were set in metadata database and restart the odc server, the problem disappeared.

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/user-attachments/assets/7c19f851-6f32-417b-a31d-e43e9945d9f8)
pass
