### ISSUE TITLE
[Bug]: Use /* comment + hint query, hint is set to invalid

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2789]
### ODC version

ODC430

### OB version

independent

### What happened?

Use /* comment + hint query, hint is set to invalid
![image](https://github.com/oceanbase/odc/assets/59468957/98c126cb-f7e3-44db-9108-e539292ec9a6)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

```

/*
测试一下
*
/
SELECT * /*+ PARALLEL(5) */ from dual
```

**Comment by HSunboy** [comment]
<img width="647" alt="image" src="https://github.com/oceanbase/odc/assets/14886044/e8e84d5c-7c71-46a7-ab81-609f1d49bfdc">
 SQL is invalid, commet should end with <*/>
