### ISSUE TITLE
[Bug]: Failed to view table in Oracle when OB version is 431

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2793]
### ODC version

odc430bp

### OB version

ob431

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/a2f92a82-4673-457e-96b7-09ca0a7f9325)

### What did you expect to happen?

No error reported

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an Oracle link with OB version 431
2. Enter the link and create a table
3. Open Table

**Comment by tonghan-gsh** [comment]
pass
