### ISSUE TITLE
[Bug]: Error in structure comparison viewing SQL detailed information window

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2794]
### ODC version

odc430bp

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/3fa69076-c764-4e14-af18-a94fca0cb201)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/8370fba0-57be-4c5c-98e8-0543a99d7fdd)

### How can we reproduce it (as minimally and precisely as possible)?

Perform structure comparison to view SQL details

**Comment by HSunboy** [comment]
fixed in dev-4.3.0

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e07276dc-ef40-48a1-bfee-73471ede3c07)

pass
