### ISSUE TITLE
[Bug]: Create a lock-free structure change task, and the log shows data too long for column

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2799]
### ODC version

ODC430

### OB version

independent

### What happened?

Create a lock-free structure change task, and the log shows data too long for column
![image](https://github.com/oceanbase/odc/assets/59468957/ac05548e-9774-45ef-8cbe-089bdff545fc)

### What did you expect to happen?

```
ALTER TABLE `config_system_configuration` CHANGE COLUMN `value` `value_deprecated` varchar(1024);
```

### How can we reproduce it (as minimally and precisely as possible)?

.

**Comment by zijiacj** [comment]
have done
