### ISSUE TITLE
[Bug]: Using a lower version of chrome to create a data source does not allow drop-down selection of the data source type

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#28]
**Describe the bug**

Using a lower version of chrome to create a data source does not allow drop-down selection of the data source type

**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- Component Version: ODC 4.2.0  

**Fast Reproduce Steps(Required)**

Chrome version:90.0.4430.212
Creating a data source cannot drop down to show the data source type
![image](https://github.com/oceanbase/odc/assets/46598871/ffba294f-b569-4587-adf4-b4d23829a780)

**Expected behavior**
![image](https://github.com/oceanbase/odc/assets/46598871/664f5f9f-6a05-44d9-8f0a-7b4dbbe3b4c6)

**Actual Behavior**

**Additional context**

**Comment by HSunboy** [comment]
Fixed

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/e4a339fb-8f6e-46fa-9547-f964549bbf33)

Pass
