### ISSUE TITLE
[Bug]: The description of the SQL execution profile is incorrect when executing SQL for the first time

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2804]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/5b340911-62f0-46ee-bd1d-0d548a70e72e)

### What did you expect to happen?

Description is normal

### How can we reproduce it (as minimally and precisely as possible)?

First time executing SQL

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4618c009-1832-4294-bc83-07adc5d4772a)

The background is black

**Comment by HSunboy** [comment]
Fixed In Commit [4ed588efdfda392a376b7837326db6ec9e83bb6c](https://github.com/oceanbase/odc-client/commit/4ed588efdfda392a376b7837326db6ec9e83bb6c)
            ------
            畅晚
            Tue Jul 9 10:02:32 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/16a344c4-4f14-4008-bca4-2636b406b8a0)

pass
