### ISSUE TITLE
[Bug]: Click on the image to execute an error message

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2805]
### ODC version

odc431

### OB version

ob4.3.0.1

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/d99269f6-221c-4f3a-bd29-8f7d9f057f4d)

### What did you expect to happen?

No error reported

### How can we reproduce it (as minimally and precisely as possible)?

First time executing SQL

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/993d025c-fbdd-4e13-99da-690f8f48864c)

The problem still exists

**Comment by LuckyPickleZZ** [comment]
Now we only support viewing query profile on [4.2.4, 4.3.0) || [4.3.3, )

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/6b2cf750-cc50-4cee-bf32-faa1d2682875)

pass
