### ISSUE TITLE
[Bug]: Failed to save settings

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2808]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/4e21b2d8-e95e-4254-a059-7e709085d26d)

### What did you expect to happen?

Save successful

### How can we reproduce it (as minimally and precisely as possible)?

Click on settings, modify settings, and save

**Comment by qymsummer** [comment]
Can be saved successfully, verification passed
