### ISSUE TITLE
[Bug]: The hovering display of the log is inconsistent with the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2809]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/845402a9-39c4-4898-9c2c-1a9d3ebd2b28)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/fc846591-68a7-46f1-9a37-e6ebb0d0b926)

### How can we reproduce it (as minimally and precisely as possible)?

1. Execute SQL
2. view log

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/c81f51dc-c224-4a4a-8c07-6a674941b015)

pass
