### ISSUE TITLE
[Bug]: There is no execution status in the execution record

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2810]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b5de1156-e9e4-4189-83db-017b1e75fa8d)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/4761f87c-f32d-47e1-b695-c78dadeb55b1)

### How can we reproduce it (as minimally and precisely as possible)?

Execute multiple SQL statements

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/54d62533-c66f-4889-ac5f-e07b5c5ed16b)

pass
