### ISSUE TITLE
[Bug]: The hovering display of the toolbar in the bottom left corner of the execution details is inconsistent with the actual situation

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2812]
### ODC version

odc431

### OB version

ob424

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/736050fc-6123-4f7c-936e-81c80f940a44)
![image](https://github.com/oceanbase/odc/assets/143492234/33fb1af0-07f2-471c-bbb9-4f6dd18a02e6)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/053b574b-09bf-422f-8123-c6657935f278)

### How can we reproduce it (as minimally and precisely as possible)?

Execute the SQL query and click on the execution profile

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/0903acf5-7bf4-48fd-a40b-831f98870dc2)



![Image](https://github.com/oceanbase/odc/assets/143492234/2346fd82-e99b-4267-9a48-2c626312f907)

pass
