### ISSUE TITLE
[Bug]: The settings in the SQL window are inconsistent with the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2813]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/3a9d6505-7fdb-43d5-9823-e96c1a24d007)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/89533a0d-0831-4fad-b239-fb6f763519bd)

### How can we reproduce it (as minimally and precisely as possible)?

Open SQL window to view settings

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e0891742-9481-4234-b639-cdbe64052a60)

pass
