### ISSUE TITLE
[Bug]: Inconsistency between the planned statistics and the design draft within the execution plan

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2816]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/46a7ffb0-dca8-4d0c-817e-43c946e703ea)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/1dff24c0-c8cf-4a19-bece-6dc8966a7543)

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL to view execution plan

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e3b3d37a-7293-48a8-9d17-680f73475377)

pass
