### ISSUE TITLE
[Bug]: The list view within the execution plan is inconsistent with the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2822]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/1c594c68-3a02-454d-8f1c-2a6791e449ad)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/dcbeb4b8-3a35-45fb-a3c1-076980e655e4)

### How can we reproduce it (as minimally and precisely as possible)?

Enter SQL statements, click on execution plan, and click on list view

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5406158a-4d3e-4bb3-b328-0b4b30c22b43)

pass
