### ISSUE TITLE
[Bug]: The execution of the portrait link line preserves two decimal places

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2824]
### ODC version

odc431

### OB version

ob424

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/aa467747-9d40-48cc-9de9-a036b2d3af9b)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/b4b5b65f-7642-4358-a8d9-a3c33ef8d047)

### How can we reproduce it (as minimally and precisely as possible)?

Execute the SQL query and click on the execution profile

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/692b305f-75a2-4f8e-818a-ed4a711c58d5)

pass
