### ISSUE TITLE
[Bug]: After selecting the node, the title and parameters displayed are inconsistent with the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2825]
### ODC version

odc431

### OB version

ob424

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/7283a2a2-a720-4b6e-b138-836f8595ec21)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/48698276-5b0b-4b8d-ad13-80c208fa00d8)

### How can we reproduce it (as minimally and precisely as possible)?

Execute the SQL query and click on the execution profile

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8786355e-6fdf-40e0-8918-b920563c6f7c)

pass
