### ISSUE TITLE
[Bug]: The execution plan should not support exporting JSON

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2829]
### ODC version

odc431

### OB version

ob424

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/862267f2-cf55-4370-b6cc-0388aacb2b75)

### What did you expect to happen?

The execution plan and execution profile should not support exporting JSON

### How can we reproduce it (as minimally and precisely as possible)?

After executing SQL, click on the execution profile and click on the execution plan

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/27815f75-e6e5-4ba3-992b-008b2e48fe44)

pass
