### ISSUE TITLE
[Bug]: Unsupported operation, still shows the operation entry

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#283]
### ODC version

4.2.0

### OB version

Regardless

### What happened?

MySQL mode currently does not support editing views, functions, and procedures. The right-click "Edit" button should be disabled

### What did you expect to happen?

MySQL mode currently does not support editing views, functions, and procedures. The right-click "Edit" button should be disabled

### How can we reproduce it (as minimally and precisely as possible)?

---

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b3200032-2b6d-4bf9-928a-b01e6f221a57)



![Image](https://github.com/oceanbase/odc/assets/143492234/1e2fbd38-1fea-45f7-a70f-8638af4104d3)



![Image](https://github.com/oceanbase/odc/assets/143492234/2e63b9a7-73d9-49e3-9328-e1b030ae14cb)

pass
