### ISSUE TITLE
[Bug]: The execution profile should not be displayed below ob4.2.4

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2831]
### ODC version

odc431

### OB version

ob 4215

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/3e7d43c7-f133-476b-b5da-c1b6d1135516)

### What did you expect to happen?

The execution profile button should not be displayed below ob4.2.4

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL in ob4215 version

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/380e2ab9-6056-4688-9990-1e8ae991ad37)

pass
