### ISSUE TITLE
[Bug]: The default status of the execution plan should not display an overview of SQL execution

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2835]
### ODC version

odc431

### OB version

ob424

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/3e4cfa1a-a9d0-439d-a0d7-f4a38eb7099e)

### What did you expect to happen?

SQL execution overview should not be displayed

### How can we reproduce it (as minimally and precisely as possible)?

Enter SQL and click on the execution plan

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/edc74127-f440-4235-af0e-7c810d0a0299)

pass
