### ISSUE TITLE
[Bug]: I/O statistics should not be displayed within the execution plan node

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2836]
### ODC version

odc431

### OB version

ob424

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2ff6eeac-b2f1-4f62-8bf9-82b0d18c767f)

### What did you expect to happen?

I/O statistics should not be displayed

### How can we reproduce it (as minimally and precisely as possible)?

Enter SQL, click on execution plan, click on node

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/c1bc300f-a9c1-48a5-8f84-8c49fad9d355)

pass
