### ISSUE TITLE
[Bug]: Native MySQL has an execution profile

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2837]
### ODC version

odc431

### OB version

Native MySQL 8.0

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/1bac1c03-603a-4deb-961f-dfd40621fac0)
![image](https://github.com/oceanbase/odc/assets/143492234/09767de4-197a-4071-8784-343331166a8a)

### What did you expect to happen?

Native MySQL cannot use execution profiling

### How can we reproduce it (as minimally and precisely as possible)?

Native MySQL executes query SQL

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/fefd9333-b932-43cc-b293-faf327180d7c)

pass
