### ISSUE TITLE
[Bug]: Native Oracle has an execution profile

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2838]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/cdcff82b-ddb6-44b0-893b-122cf3c0a932)
![image](https://github.com/oceanbase/odc/assets/143492234/0b5bf90c-4ddd-4c10-86a5-2db1ff4499cc)

### What did you expect to happen?

Native Oracle should not have an execution profile

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL and click on the execution profile

**Comment by HSunboy** [comment]
Fixed In Commit [b8310dbf525090e447de8ab108fba352e21af1e0](https://github.com/oceanbase/odc-client/commit/b8310dbf525090e447de8ab108fba352e21af1e0)
            ------
            畅晚
            Mon Jul 8 09:36:58 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ea2a6561-3a36-4b56-838d-b373b9071dcf)

pass
