### ISSUE TITLE
[Bug]: Native Oracle Click SQL Check Error

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2839]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2ab5a130-eb86-4ec0-a00b-137deb9f555c)

### What did you expect to happen?

No error reported

### How can we reproduce it (as minimally and precisely as possible)?

After entering SQL, click on SQL check

**Comment by MarkPotato777** [comment]
4.3.3 support

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/dab6a523-ce4c-4ecf-a098-cd5775b2e678)
pass
