### ISSUE TITLE
[Bug]: Error in selecting database for partition plan

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#284]
### ODC version

odc421

### OB version

ob410

### What happened?

Error reported when selecting a database within the partition plan
![image](https://github.com/oceanbase/odc/assets/143492234/659c9a4c-fd5c-4057-8c1f-298b3698d2bb)

### What did you expect to happen?

No error reported

### How can we reproduce it (as minimally and precisely as possible)?

Select a database within the partition plan

**Comment by tonghan-gsh** [comment]
Partition planning is not supported in oracle mode
