### ISSUE TITLE
[Bug]: There is a full link diagnostic button in the table data

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2840]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/fcee201a-5ed1-46df-aa33-e5338c38c2e8)

### What did you expect to happen?

There is no full link diagnostic button in the table data

### How can we reproduce it (as minimally and precisely as possible)?

Viewing Table Data

**Comment by HSunboy** [comment]
Fixed In Commit [4ed588efdfda392a376b7837326db6ec9e83bb6c](https://github.com/oceanbase/odc-client/commit/4ed588efdfda392a376b7837326db6ec9e83bb6c)
            ------
            畅晚
            Tue Jul 9 10:02:32 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/096df5e2-6fc1-475a-abcd-333ff09a6518)

pass
