### ISSUE TITLE
[Bug]: In OBOracle mode, archiving operations require DBA privileges.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#2865]
### ODC version

4.3.0

### OB version

OB Oracle mode 

### What happened?

Under the OceanBase Oracle mode, users require DBA privileges to execute archiving tasks.

Oracle 模式下用户需要dba权限才能执行归档任务（需要判断目标表是否存在，就用到SYS库的查询权限）

### What did you expect to happen?

No special permissions are required.

不需要特殊的权限

### How can we reproduce it (as minimally and precisely as possible)?

In OBOracle mode, ordinary users without DBA privileges can perform data archiving.

在 OBOracle 模式下，使用非 dba 权限的普通用户进行数据归档。

**Comment by Huangxiao-mas** [comment]
pass
