### ISSUE TITLE
[Bug]: Stored procedure execution failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2868]
### ODC version

odc431

### OB version

ob430,ob424

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/f01d4ef2-6e82-4a89-abae-37168300bdf9)

### What did you expect to happen?

The stored procedure can be executed normally

### How can we reproduce it (as minimally and precisely as possible)?

1. Create stored procedure
```sql
create procedure `pro6` (INOUT `a` varchar(45)) begin
declare
  v1 int;
set
  a = 2;
set
  v1 = a + 1;
select
  v1;
end;
```

**Comment by yhilmare** [comment]
this issue may be related to driver's parameter: `sendConnectionAttributes`.

I can execute this procedure if I set this parameter to `true`:
![截屏2024-07-02 16 26 22](https://github.com/oceanbase/odc/assets/22992296/8205657b-4aa4-4043-8aa8-a5619f6f595e)

I failed to execute this procedure when I set this parameter to `false`:
![截屏2024-07-02 16 27 40](https://github.com/oceanbase/odc/assets/22992296/8111af41-12ab-4edb-af4b-3dca1cd2ca7c)

**Comment by yhilmare** [comment]
this is a known issue for driver, this related issue id is 53824885.

we may solve this issue by upgrading driver's version

**Comment by yhilmare** [comment]
> this is a known issue for driver, this related issue id is 53824885.
> 
> we may solve this issue by upgrading driver's version

2.4.8.1 may work

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/7b8f48fc-f699-4645-96cf-9992eeb2f3df)
pass
