### ISSUE TITLE
[Bug]: Unable to issue work order

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2870]
### ODC version

ODC431

### OB version

independent

### What happened?

Unable to issue work order
![image](https://github.com/oceanbase/odc/assets/59468957/7736381e-5fc5-4f5b-ab7b-9dc13a566916)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by yhilmare** [comment]
this issue is involved by this pr #2789

**Comment by yhilmare** [comment]
the dialect_type in connect_database is null which lead to this issue:
![截屏2024-07-02 17 00 27](https://github.com/oceanbase/odc/assets/22992296/1dcd7d93-d17d-4d17-914a-087d209701f5)
