### ISSUE TITLE
[Bug]: meaningless number will display when I change another project

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2876]
### ODC version

4.3.0

### OB version

not related

### What happened?

1. preparing starting up a multi-database change ticket and select a database:
<img width="842" alt="截屏2024-07-03 14 10 35" src="https://github.com/oceanbase/odc/assets/22992296/dd56cc23-2b88-4d67-8abf-f484419c500c">

2. change another project:
<img width="894" alt="截屏2024-07-03 14 11 10" src="https://github.com/oceanbase/odc/assets/22992296/ddf4229e-cd26-4c3e-8cc7-115d2768c0c8">

as you can see, a meaningless number will display

### What did you expect to happen?

the selected databases should be removed when I change another project

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [78d1252ee0d79de6455ea2263e60fd1868bc5648](https://github.com/oceanbase/odc-client/commit/78d1252ee0d79de6455ea2263e60fd1868bc5648)
            ------
            陈朝俊
            Fri Jul 12 19:37:25 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/c5246108-9785-4296-8556-645efb58432b)

pass
