### ISSUE TITLE
[Bug]: the prompt of the timeout setting in database change and multi-database change task is wrong

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#2877]
### ODC version

4.2.4

### OB version

not related

### What happened?

<img width="704" alt="截屏2024-07-03 14 21 24" src="https://github.com/oceanbase/odc/assets/22992296/7e138f90-4e97-4bc8-8a19-a5d05c4e6a4e">
<img width="548" alt="截屏2024-07-03 14 21 42" src="https://github.com/oceanbase/odc/assets/22992296/c94e6556-de1b-4eeb-8c58-25b6ec63e089">

as you can see, the timeout setting of bot two task is named as "执行超时时间"

### What did you expect to happen?

this settings should be named as "SQL 执行超时时间" actually

### How can we reproduce it (as minimally and precisely as possible)?

not related

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/4ca447ae-c848-4665-b18e-2bf126257dae)

Unrepaired
