### ISSUE TITLE
[Bug]: Syntax error was thrown when comment with '--' in a PL

### ISSUE THREAD

**Issue by pyybuaa** [oceanbase/odc#288]
### ODC version

4.1.3 

### OB version

none

### What happened?

When I use '--' comment in PL, ODC reports an error:
ErrorCode = 1064, SQLState = 42000, Details = ORA-42000: You have an error in your SQL syntax; check the manual that corresponds to your OceanBase version for the right syntax to use near '-' at line xxx.

### What did you expect to happen?

bugfix

### How can we reproduce it (as minimally and precisely as possible)?

DELIMITER //
CREATE PROCEDURE calculate_sum(IN num1 INT, IN num2 INT, OUT sum INT)
BEGIN
    -- calculate the sum
    SET sum = num1 + num2;
END //
DELIMITER ;

**Comment by yhilmare** [comment]
can not reproduce it
<img width="880" alt="截屏2023-10-18 14 43 51" src="https://github.com/oceanbase/odc/assets/22992296/4f5544e2-ac67-47cb-a2c7-35d706ace7a3">
