### ISSUE TITLE
[Bug]: There is no refresh button within the permission of the application form

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2882]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/033268b8-eb6c-4eaf-8aa5-a2138ab77eef)

### What did you expect to happen?

There is a refresh button present

### How can we reproduce it (as minimally and precisely as possible)?

Select projects after applying for form permissions

**Comment by yezaoshu** [comment]
by design
