### ISSUE TITLE
[Bug]: The application form permission database dropdown button disappears

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2884]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/cede8195-e55a-48fd-a83d-b37c5eeb2c0b)

### What did you expect to happen?

There is a dropdown button present

### How can we reproduce it (as minimally and precisely as possible)?

1. Select projects within the permission of the application form
2. Dropdown Database
3. Switch projects
4. Switch back to the original project

**Comment by HSunboy** [comment]
Fixed In Commit [834eadbdc965783d69cab4016d93ac1935c6405f](https://github.com/oceanbase/odc-client/commit/834eadbdc965783d69cab4016d93ac1935c6405f)
            ------
            畅晚
            Mon Jul 22 15:23:28 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/25225645-b06c-4bc1-9792-b6bb54007077)
PASS
