### ISSUE TITLE
[Bug]: The environmental color within the permission of the application form is inconsistent with the data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2888]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/4bf77497-6f52-45a3-9082-3ba031df0de8)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/36935cc0-7e64-42d1-bed2-08651253a30e)

### How can we reproduce it (as minimally and precisely as possible)?

Select projects within the permission of the application form

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/d76b7c7c-2da6-4e1d-9bff-a07c2f23e034)
pass
