### ISSUE TITLE
[Bug]: There is no application reason in the application form permission

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2890]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/0ac30779-105f-49a7-a730-ce194d023a5c)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/c794729f-d539-4e14-a5d8-d937ed5ecf25)

### How can we reproduce it (as minimally and precisely as possible)?

Execute application library permissions

**Comment by yezaoshu** [comment]
by design
