### ISSUE TITLE
[Bug]: Edit appearance, report primary key conflict

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2894]
### ODC version

ODC431

### OB version

independent

### What happened?

Edit appearance, report primary key conflict
![image](https://github.com/oceanbase/odc/assets/59468957/9b171bdc-1ccf-4e5e-bd74-29bb1fa1a2e4)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
fixed in 4.3.1

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b50eef0d-6cc8-443c-9994-c3267dce12b7)

pass
