### ISSUE TITLE
[Bug]: The user authorization page for table permissions is inconsistent with the layout of the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2896]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/c946f795-7466-4de5-b803-b2919b9e35b6)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/dcf1a05a-5f45-4e6b-a420-19d81da1f4b7)

### How can we reproduce it (as minimally and precisely as possible)?

Enter the project, click on members, select a member, click on management permissions, click on table permissions

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/80daf74f-15da-42b1-8e16-d43856da8538)
pass
