### ISSUE TITLE
[Bug]: Authorization for adding new tables within the project can be selected from past times

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2897]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/041a3974-d3e4-44ed-9921-9ccc38ac85c1)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/f467bf95-ca12-4eb7-bd4c-02e1d6a106c5)

### How can we reproduce it (as minimally and precisely as possible)?

Enter the project, click on members, select a member, click on manage permissions, click on add table authorization

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/b86c3806-dd7c-41cb-9330-c76ece850b9c)
pass
