### ISSUE TITLE
[Bug]: Invalid database search within permission management table

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2898]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/e005ac82-ed8f-4b00-a571-41ab90228a4c)

### What did you expect to happen?

Display only searched databases

### How can we reproduce it (as minimally and precisely as possible)?

Enter the project, click on members, click on management permissions, and then click on search in the database

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/05de24e8-e69a-4f2d-8320-bb97dcb2729f)
pass
