### ISSUE TITLE
[Bug]: All cancellations are not fully effective

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2899]
### ODC version

odc431

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/407dacd6-f356-4d27-9766-8eae4c531a6c

### What did you expect to happen?

Deselect all when canceling

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/0e114b20-669e-4128-9c48-5244a7492fc2)
pass
