### ISSUE TITLE
[Bug]: Expired permissions can be selected

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2902]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/09dd2918-9643-4ad3-83f9-77fed37029e8)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/15567678-aa96-48c4-a79e-b32710665b9e)

### How can we reproduce it (as minimally and precisely as possible)?

Enter the project, click on members, click on manage permissions, and then click on expired permissions

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/a2fbdc9e-910d-4a56-9748-14c083475157)
pass
