### ISSUE TITLE
[Bug]: Inappropriate copy description regarding the metadata database.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#2904]
### ODC version

4.3.0

### OB version

ALL

### What happened?

The database port should be determined based on the actual situation; there is no such thing as a default port.
Database 的端口应该是根据实际情况定，没有默认端口这种说法

![image](https://github.com/oceanbase/odc/assets/15030999/d23cecf2-c05a-4aa8-a42a-5d440c46d500)

### What did you expect to happen?

Copywriting optimization

### How can we reproduce it (as minimally and precisely as possible)?

View the deployment instructions for ODC

https://www.oceanbase.com/docs/common-odc-1000000000876850

**Comment by JessieWuJiexi** [comment]
文档已更新
![image](https://github.com/user-attachments/assets/1ce33bdd-8420-40e2-a7d9-93a686baae76)

**Comment by tonghan-gsh** [comment]
pass
