### ISSUE TITLE
[Bug]: Display as blank after deleting the last page of table permissions

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2909]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/2280e7e4-6080-4569-838a-def9d882140a)

### What did you expect to happen?

Automatically redirect to pages with existing content

### How can we reproduce it (as minimally and precisely as possible)?

Enter the project, click on members, click on management permissions, click on table permissions, jump to the last page, and delete all

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/7189a177-4a79-4fc2-aa9e-3bee6091c7c5)

pass
