### ISSUE TITLE
[Bug]: No authority, limited time, not only display application library permissions

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2910]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/e294da6d-e671-4d69-8b9d-6fa6371b04c1)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/fb6044b6-9efb-420d-9ef3-b96a3d29c9a8)

### How can we reproduce it (as minimally and precisely as possible)?

Low privilege account entry into the project

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/dc3cf41f-60bf-4e1c-bd3a-8d2c0c79ec24)

pass
