### ISSUE TITLE
[Bug]: No permissions within the project tab

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2911]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/014c43af-92fe-41b2-be96-8d88cb26b4d8)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/e4dd0347-32e1-411d-9e94-b6e9af228620)

### How can we reproduce it (as minimally and precisely as possible)?

Low privilege account entry into the project

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800
