### ISSUE TITLE
[Bug]: Clicking on the application form permission to initiate again may cause the page to crash

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2916]
### ODC version

odc431

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/1103e438-aff3-459d-bd18-77688d50d384

![image](https://github.com/oceanbase/odc/assets/143492234/6926d8c0-f31e-45f6-b756-bdc12141f1f8)

### What did you expect to happen?

Page does not crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Set application form permissions to medium risk
![image](https://github.com/oceanbase/odc/assets/143492234/17ac3b87-6fe9-439d-a5e8-63e68d664e54)
2. Click on the permission account to initiate again

**Comment by HSunboy** [comment]
Fixed In Commit [48b0a9c5867f163404fe6f4e9dff480c9c247272](https://github.com/oceanbase/odc-client/commit/48b0a9c5867f163404fe6f4e9dff480c9c247272)
            ------
            畅晚
            Fri Jul 12 17:33:57 2024 +0800

**Comment by sl01388797** [comment]
pass
