### ISSUE TITLE
[Bug]: Pre check failed for tables without change permission in the database change execution table, and there is no prompt to revoke permission

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2920]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/e99b23c2-5913-4155-8548-29bc7e007c2e)
![image](https://github.com/oceanbase/odc/assets/143492234/8b9e336b-0a49-4af9-a642-651551e3a370)

### What did you expect to happen?

Database change execution successful

### How can we reproduce it (as minimally and precisely as possible)?

1. Application Form for Low Permission Users to Change Permissions
2. Enter SQL for operations on tables without change permission when executing database changes

**Comment by HSunboy** [comment]
Fixed In Commit [eef46482569b2f0dac54dab8293cc8d9ff707ed9](https://github.com/oceanbase/odc-client/commit/eef46482569b2f0dac54dab8293cc8d9ff707ed9)
            ------
            畅晚
            Tue Jul 30 11:30:19 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/b2be2772-63de-4101-a6c9-b415599b4063)

pass
