### ISSUE TITLE
[Bug]: There is no specific value displayed for the total time consumption

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2921]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/53df7427-9c4b-41d6-be1a-3d0f38904641)

### What did you expect to happen?

Display specific numerical values

### How can we reproduce it (as minimally and precisely as possible)?

Viewing Table Data

**Comment by manyyuri** [comment]
table data query 性能较差，这里的总耗时直接隐藏。

**Comment by HSunboy** [comment]
Fixed In Commit [b64b2bce9098fd4f9538ab632d560458aea9ae93](https://github.com/oceanbase/odc-client/commit/b64b2bce9098fd4f9538ab632d560458aea9ae93)
            ------
            之瑛
            Tue Jul 23 17:32:30 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/2976a909-e546-4679-9527-8ca8fe27ba36)
pass
