### ISSUE TITLE
[Bug]: Listing association unsuccessful

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2922]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/aefaeb4d-6022-4a92-bdbd-03ac6b2094e3)

### What did you expect to happen?

Display column names

### How can we reproduce it (as minimally and precisely as possible)?

Input in SQL window
SELECT * FROM 全类型表 t where t.

**Comment by HSunboy** [comment]
Special table names need to be wrapped with ` symbols

**Comment by HSunboy** [comment]
Fixed In Commit [d099c706e5cf59085df99bbe541283aa0c58803f](https://github.com/oceanbase/odc-client/commit/d099c706e5cf59085df99bbe541283aa0c58803f)
            ------
            xiaokang
            Tue Jul 9 10:20:24 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/a08d7a90-c041-4974-b7f7-07550c56c433)

pass
