### ISSUE TITLE
[Bug]: The sql window comment contains three `-`, and the column name acquisition interface is not requested

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2923]
### ODC version

ODC431

### OB version

independent

### What happened?

The sql window comment contains three `-`, and the column name acquisition interface is not requested
![image](https://github.com/oceanbase/odc/assets/59468957/891374a0-6237-42d7-97fc-05bc3257208e)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/59468957/821da51b-8665-4aa1-ba6c-8fd23c365cb3)
With two ‘’-“
![image](https://github.com/oceanbase/odc/assets/59468957/2ed1ea53-ad91-4896-9b77-ecac50cccdb4)

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/c4a13d64-5bd4-4516-bcb3-cee422148ed0)
syntax error
