### ISSUE TITLE
[Bug]: Display negative progress when time is 0s

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2926]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/45ff8ec1-f7ec-43cf-9105-e4217c89512a)

### What did you expect to happen?

Display as 0%

### How can we reproduce it (as minimally and precisely as possible)?

1. Execute SQL
-- Subqueries
SELECT /*+   TPCH_Q20 parallel(256) */ s_name,
       s_address
FROM   supplier,
       nation
WHERE  s_suppkey IN (SELECT ps_suppkey
                     FROM   partsupp
                     WHERE  ps_partkey IN (SELECT p_partkey
                                           FROM   part
                                           WHERE  p_name LIKE 'green%')
                            AND ps_availqty > (SELECT 0.5 * SUM(l_quantity)
                                               FROM   lineitem
                                               WHERE  l_partkey = ps_partkey
                                                      AND l_suppkey = ps_suppkey
                                                      AND l_shipdate >= DATE
                                                          '1993-01-01'
                                                      AND l_shipdate < DATE
                                                          '1993-01-01' + interval '1' year
                                              ))
       AND s_nationkey = n_nationkey
       AND n_name = 'ALGERIA'
ORDER  BY s_name;
2. Click to execute the profile

**Comment by yezaoshu** [comment]
I cannot reproduce this issue
