### ISSUE TITLE
[Bug]: DBA role cannot add members

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2929]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/ffd134ac-6d6a-43ca-83d6-25f97817319c)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/279323e7-5078-419b-a745-1aa9a063a733)

### How can we reproduce it (as minimally and precisely as possible)?

1. Add DBA permissions to a user for a project
2. Login User View

**Comment by HSunboy** [comment]
Fixed In Commit [d7addf8113ff4e6e6fd30003509e26d4d8ebac08](https://github.com/oceanbase/odc-client/commit/d7addf8113ff4e6e6fd30003509e26d4d8ebac08)
            ------
            畅晚
            Wed Jul 10 13:58:11 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/33d66f04-e18a-4584-8202-28892faad956)

pass
