### ISSUE TITLE
[Bug]: Automatic authorization, loginsucces event, it takes 15 minutes for the role to take effect after being granted

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2939]
### ODC version

ODC431

### OB version

independent

### What happened?

Automatic authorization, loginsucces event, granting project roles failed

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

1. config loginsucces event
2. Automatic authorization
![image](https://github.com/oceanbase/odc/assets/59468957/c24b936c-490e-4a9c-82dc-58b6c10d285e)

**Comment by ungreat** [comment]
see https://github.com/oceanbase/odc/issues/789 ,  there is variable `odc.security.max-login-record-time-minutes` to control take effect interval. We can't make default value to zero in community edition.
