### ISSUE TITLE
[Bug]: Automatic authorization does not take effect when logging in with ldap

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2949]
### ODC version

ODC431

### OB version

independent

### What happened?

Automatic authorization does not take effect when logging in with ldap
![image](https://github.com/oceanbase/odc/assets/59468957/ed3deb53-8074-41d2-ac54-ee320f118007)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

Create automatic authorization event
Login using ldap

**Comment by ungreat** [comment]
Worksforme, could you explicitly reproduce the scene?
