### ISSUE TITLE
[Bug]: failed to get flashback sql on specific db object

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#295]
### ODC version

4.2.0

### OB version

not related

### What happened?

I want to generate flash back sql on some db objects, and I got nothing as you can see as follow:
<img width="1052" alt="截屏2023-09-11 10 23 48" src="https://github.com/oceanbase/odc/assets/22992296/27a7751a-51c7-456d-8d98-8cd2d450bbf6">

### What did you expect to happen?

I can get the generated flashback sql.

### How can we reproduce it (as minimally and precisely as possible)?

try to generate a flashback sql

**Comment by yhilmare** [comment]
OcaneaBase only supports these db objects as follows:
```Java
private static final Set<String> SUPPORTED_TYPES = new HashSet<>();

static {
    SUPPORTED_TYPES.add("TABLE");
    SUPPORTED_TYPES.add("VIEW");
    SUPPORTED_TYPES.add("TENANT");
    SUPPORTED_TYPES.add("DATABASE");
    SUPPORTED_TYPES.add("SCHEMA");
}
```

ODC will give up generating sql when meets unsupported types:
```Java
// DBRecyclebinService#getFlashbackSql
public String getFlashbackSql(@NonNull ConnectionSession session, List<DBRecycleObject> recycleObjects) {
        ...
        for (DBRecycleObject recycleObject : recycleObjects) {
            ...
            if (!SUPPORTED_TYPES.contains(type.toUpperCase())) {
                continue;
            }
            ...
        }
        ...
}
```
ref:  [DBRecyclebinService](https://github.com/oceanbase/odc/blob/2526729b394319c98404345315911efe917d704e/server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBRecyclebinService.java)

**Comment by yhilmare** [comment]
to fix this bug, we generate a sql comment when user's recycle object's type is not in available types:
<img width="1099" alt="截屏2023-09-11 11 46 10" src="https://github.com/oceanbase/odc/assets/22992296/a4437bcf-aef7-498e-b5d5-1fe8b5bc66c7">

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/40a99207-ff95-4c73-a91f-63c78f8928a0)
pass
