### ISSUE TITLE
[Bug]: Internationalization, exit the desktop version, the prompt is displayed in Chinese

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2951]
### ODC version

ODC430

### OB version

independent

### What happened?

Internationalization, exit the desktop version, the prompt is displayed in Chinese
![image](https://github.com/oceanbase/odc/assets/59468957/cd621901-8d6f-415e-954c-58315f5b5744)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
The odc client only supports Chinese
