### ISSUE TITLE
[Bug]: After removing members from the project, the user reports that they do not have permission after logging in.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#2956]
### ODC version

ODC431

### OB version

independent

### What happened?

After removing members from the project, the user reports that they do not have permission after logging in.
![image](https://github.com/oceanbase/odc/assets/59468957/aa7541ba-2757-462b-80b5-23d274e3fd31)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

Project A removes member zhangsan
Log in using zhangsan

**Comment by HSunboy** [comment]
Fixed In Commit [eef46482569b2f0dac54dab8293cc8d9ff707ed9](https://github.com/oceanbase/odc-client/commit/eef46482569b2f0dac54dab8293cc8d9ff707ed9)
            ------
            畅晚
            Tue Jul 30 11:30:19 2024 +0800
