### ISSUE TITLE
[Bug]: The global retrieval of MySQL, obMySQL, and Doris data sources is inconsistent with the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2969]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/e42446dd-82ee-49d3-8205-3f7dd3ed4e7a)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/13fc12d4-f81e-498c-bd21-855d1786faf0)

### How can we reproduce it (as minimally and precisely as possible)?

Global retrieval using MySQL, obMySQL, and Doris data sources

**Comment by HSunboy** [comment]
Fixed In Commit [46d523ebcc7ffeb874eb21929afb19b3d6492ddc](https://github.com/oceanbase/odc-client/commit/46d523ebcc7ffeb874eb21929afb19b3d6492ddc)
            ------
            畅晚
            Tue Jul 16 09:44:37 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/2cb5b67b-0d6b-4847-b8b6-e5ee63c2d4e3)
pass
