### ISSUE TITLE
[Bug]: The global retrieval of Oracle and ObOracle data sources is inconsistent with the length of the design draft tab

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2970]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/bcb13563-fa2d-4470-b71a-c7ebfe95a947)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/0501a1da-f6d2-4b78-8e5c-d8098961ddce)

### How can we reproduce it (as minimally and precisely as possible)?

Oracle and OBOracle data sources for global retrieval

**Comment by HSunboy** [comment]
Fixed In Commit [46d523ebcc7ffeb874eb21929afb19b3d6492ddc](https://github.com/oceanbase/odc-client/commit/46d523ebcc7ffeb874eb21929afb19b3d6492ddc)
            ------
            畅晚
            Tue Jul 16 09:44:37 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/e3656d67-830e-4118-90f4-62208289307b)
pass
