### ISSUE TITLE
[Bug]: The right mouse button and enter key cannot take effect

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2971]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/55b59da9-3ab9-47a5-868a-ac3447c18b67)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/a327b70d-e7e1-47f1-a8a4-66b31f097769)

### How can we reproduce it (as minimally and precisely as possible)?

Search within the global search

**Comment by HSunboy** [comment]
Fixed In Commit [46d523ebcc7ffeb874eb21929afb19b3d6492ddc](https://github.com/oceanbase/odc-client/commit/46d523ebcc7ffeb874eb21929afb19b3d6492ddc)
            ------
            畅晚
            Tue Jul 16 09:44:37 2024 +0800
