### ISSUE TITLE
[Bug]: When clicking on the database, an SQL window opened

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2972]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/0da47bc9-46b0-46b5-a709-d2b28e6af0ed)
![image](https://github.com/user-attachments/assets/6ad84a33-6a3b-4997-baeb-9685811c4b53)

### What did you expect to happen?

Do not open SQL window

### How can we reproduce it (as minimally and precisely as possible)?

Select database within global search

**Comment by HSunboy** [comment]
Fixed In Commit [46d523ebcc7ffeb874eb21929afb19b3d6492ddc](https://github.com/oceanbase/odc-client/commit/46d523ebcc7ffeb874eb21929afb19b3d6492ddc)
            ------
            畅晚
            Tue Jul 16 09:44:37 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/9f3c66a3-4183-4c4f-bd00-4ebd886fd78c)
pass
