### ISSUE TITLE
[Bug]: If the sql window allows the sql type to be executed is commit, it does not take effect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2973]
### ODC version

ODC 4.3.1

### OB version

No related.

### What happened?

If the sql window allows the sql type to be executed is commit, it does not take effect
![image](https://github.com/user-attachments/assets/d900afa2-5259-475f-a143-c1ad0411077d)
![image](https://github.com/user-attachments/assets/cfe62f4a-b9d1-4836-9e52-b6da06e9b498)

### What did you expect to happen?

If the type of sql allowed by the sql window is commit, the execution of commit does not require approval

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened

**Comment by yizhouxw** [comment]
@tonghan-gsh  @yhilmare  this bug will cuase commit/rollback button not works , let's move to v4.3.1
