### ISSUE TITLE
[Bug]: Show create parsing error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#2979]
### ODC version

ODC 4.3.0

### OB version

No related.

### What happened?

The show table displays : KV_ATTRIBUTES = ({"Hbase": {"TimeToLive": 30, "MaxVersions": 3}}) LOB_INROW_THRESHOLD=0.
Single quotes are missing, causing syntax errors.

### What did you expect to happen?

The table structure is successfully viewed.

### How can we reproduce it (as minimally and precisely as possible)?

```
create table t1$f1 (
  K varbinary(1024), 
  Q varbinary(256), 
  T bigint, 
  V varbinary(1048576) NOT NULL, 
  primary key(K, Q, T))
kv_attributes ='{"Hbase": {"TimeToLive": 30, "MaxVersions": 3}}'
partition by key(K) partitions 3;
```
Create the table and view the table structure.

**Comment by yhilmare** [comment]
the ddl we get form the observer of this table is like this:
```sql
create table t1$f1 (
  K varbinary(1024), 
  Q varbinary(256), 
  T bigint, 
  V varbinary(1048576) NOT NULL, 
  primary key(K, Q, T))
KV_ATTRIBUTES = ({"Hbase": {"TimeToLive": 30, "MaxVersions": 3}})
partition by key(K) partitions 3;
```

as you can see, the `kv_attributes`'s value is plain json format and the origin ddl's `kv_attributes` is plain text.

I take look at the yacc file of the observer and I find that there is nothing about the json value.

I attempt to execute this ddl and I get an error as follow:
<img width="873" alt="截屏2024-07-22 10 38 17" src="https://github.com/user-attachments/assets/25b6e33f-2521-4e3e-857f-cfd7d8472c75">

**Comment by yhilmare** [comment]
observer's bug, we can just eat the exception

**Comment by yhilmare** [comment]
<img width="863" alt="截屏2024-07-22 11 44 19" src="https://github.com/user-attachments/assets/77567d1b-26ac-4c04-b0f1-21c0413df2c0">

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/user-attachments/assets/10e3c321-d4d2-4be5-9d68-b1344aaf8686)

pass
