### ISSUE TITLE
[Bug]: After selecting the database in the data source, searching again can still find the database

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2988]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/589aa2f8-458f-43fb-b3ef-5404cfcd8806)

### What did you expect to happen?

After selecting a database within the data source, searching again still cannot find the database

### How can we reproduce it (as minimally and precisely as possible)?

Search again after selecting the database in the data source

**Comment by HSunboy** [comment]
Fixed In Commit [f866467fd548ce0c6db0f0245a109a15f87a1d03](https://github.com/oceanbase/odc-client/commit/f866467fd548ce0c6db0f0245a109a15f87a1d03)
            ------
            畅晚
            Tue Jul 23 16:50:17 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/9a64452e-41d2-438f-8efe-bc1359a10620)

pass
