### ISSUE TITLE
[Bug]: After adding members and selecting, clicking again cannot cancel

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2991]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/a6765fc5-6e3d-40a9-8deb-5897f19b33ac)

### What did you expect to happen?

After selecting, click cancel again

### How can we reproduce it (as minimally and precisely as possible)?

1. Enter the project and click on members
2. Click to add members, select members and click twice

**Comment by HSunboy** [comment]
Fixed In Commit [f866467fd548ce0c6db0f0245a109a15f87a1d03](https://github.com/oceanbase/odc-client/commit/f866467fd548ce0c6db0f0245a109a15f87a1d03)
            ------
            畅晚
            Tue Jul 23 16:50:17 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/2855625a-871a-478b-b614-33bcdcb8750d)
pass
