### ISSUE TITLE
[Bug]: There is a selection box in the task memory

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2994]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/fdd30e57-743b-4d8a-a4d5-88996e60d041)

### What did you expect to happen?

There is no selection box in the task

### How can we reproduce it (as minimally and precisely as possible)?

1. View tasks

**Comment by HSunboy** [comment]
Fixed In Commit [f866467fd548ce0c6db0f0245a109a15f87a1d03](https://github.com/oceanbase/odc-client/commit/f866467fd548ce0c6db0f0245a109a15f87a1d03)
            ------
            畅晚
            Tue Jul 23 16:50:17 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/e793563a-899a-4a16-b083-608a11150aae)
pass
