### ISSUE TITLE
[Bug]: The 'View Execution Profile' button disappears when executing SQL

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#2998]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/06c331d9-5368-47f4-9e4a-c3f79ee899f3)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/bc94023c-0f72-4a17-895b-387b425aeef0)

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL

**Comment by HSunboy** [comment]
Fixed In Commit [9cb8839099ab902da50fdb6b6f0ec4bf0630d3ec](https://github.com/oceanbase/odc-client/commit/9cb8839099ab902da50fdb6b6f0ec4bf0630d3ec)
            ------
            畅晚
            Thu Jul 25 16:29:36 2024 +0800
