### ISSUE TITLE
[Feature]: Support for more partition types

### ISSUE THREAD

**Issue by caizequan** [oceanbase/odc#30]
**Describe the solution you'd like**
Expect to support range columns datetime partition types and range  bigint partition types for partition plans in the future.

**Comment by yizhouxw** [comment]
hello @caizequan , thanks for your suggestion, could you offer more information, such as 
1. which compatiple type, OceanBase MySQL mode or OceanBase Oracle mode ？
2. for int /bigint types, what is the origin scenario, can you add an sample create table ddl ?

**Comment by caizequan** [comment]
1. OceanBase MySQL mode
2. The developer requires that the partition column can only be a partition_batch_id, because this column is the most accurate in terms of business meaning. 
**DDL example：**
create table t1 (
   `uuid` varchar(13) not null,
   `partition_batch_id` bigint not null,
   `create_time`  datetime default not null,
   `update_time`  datetime default not null, 
   primary key(`uuid`) 
)
 partition by range(partition_batch_id) 
(partition p20230813 values less than (202308140000),
partition p20230814 values less than (202308150000),
partition p20230815 values less than (202308160000),
partition p20230816 values less than (202308170000),
partition p20230817 values less than (202308180000),
partition p20230818 values less than (202308190000),
partition p20230819 values less than (202308200000),
partition p20230820 values less than (202308210000),
partition p20230821 values less than (202308220000)
);

**Comment by Jane201510** [comment]
ODC 4.2.4 Already supported
