### ISSUE TITLE
[Bug]: Incorrect error message when creating a new database in data source

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3000]
### ODC version

odc4.3.1

### OB version

no related

### What happened?

In the data source, when creating a new database, an error message "Wrong request, details: Column 'type' cannot be null" will be reported first, and then click OK to report an error message "Can't create database '777'; database exists". Click Synchronize Database 777, and the database will be updated to the list.

### What did you expect to happen?

Creating data without error

### How can we reproduce it (as minimally and precisely as possible)?

In the data source, when creating a new database, an error message "Wrong request, details: Column 'type' cannot be null" will be reported first, and then click OK to report an error message "Can't create database '777'; database exists". Click Synchronize Database 777, and the database will be updated to the list.

**Comment by MarkPotato777** [comment]
duplicated with #2957
