### ISSUE TITLE
[Bug]: Tables with change permissions in native MySQL and native Oracle cannot be changed using the database

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3009]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/534d2ea9-6555-4986-ba97-c71f807adbeb)
![image](https://github.com/user-attachments/assets/158e148e-73ab-450e-b856-68f98d9ba133)

### What did you expect to happen?

Execution successful

### How can we reproduce it (as minimally and precisely as possible)?

1. Native MySQL or Native Oracle Application Form Permissions
2. Execute database changes using tables that have applied for table permissions

**Comment by MarkPotato777** [comment]
It is expected that users without database change permission cannot create the database change ticket.

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/baf39b31-0742-4f67-972d-ccf4e1fd5762)
![image](https://github.com/user-attachments/assets/bc51d8d1-01b2-409c-ba0a-ea34beae016d)
pass
