### ISSUE TITLE
[Bug]: Tables that do not have permission to simulate data can also be executed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3010]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/31cf16eb-6a32-4521-9dab-669e3e573938)
![image](https://github.com/user-attachments/assets/0bddc824-3c20-4e5b-b03c-8a9d1bf06ca4)
![image](https://github.com/user-attachments/assets/93de7e8a-9d7f-4fab-9b75-0175ce70f52d)

### What did you expect to happen?

Unauthorized tables cannot perform tasks

### How can we reproduce it (as minimally and precisely as possible)?

1. Give a table change permission
2. Select tables without change permission to execute database simulation

**Comment by yezaoshu** [comment]
This may require adjustments to the authorizedPermissionTypes field, or waiting for further processing solutions

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/f7211f22-627b-46a5-a6bd-b2f3692b5c19)

pass
