### ISSUE TITLE
[Bug]: Structural comparison can select tables without permission for comparison

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3011]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/3435a5c3-9831-4e69-ae9f-78c053ddacc4)

### What did you expect to happen?

Cannot select tables without change permission

### How can we reproduce it (as minimally and precisely as possible)?

1. Give a table change permission
2. Select a table without change permission when performing structure comparison

**Comment by yezaoshu** [comment]
This may require adjustments to the authorizedPermissionTypes field, or waiting for further processing solutions

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/cc8a39bb-d0c0-49fa-a5d4-9f5d32e385d9)

pass
