### ISSUE TITLE
[Bug]: Partition plans can still be executed when tables do not have permission to change

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3013]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/7e0df4cf-0311-43a1-9c98-d34dd5edc657)
![image](https://github.com/user-attachments/assets/afd5ffe8-8d0e-49e4-a253-c0586b630eae)

### What did you expect to happen?

Do not display tables without permission

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a range partition table
2. Apply for permission to change the external appearance of the range table database using a low privilege account
3. Execute partition plan

**Comment by yezaoshu** [comment]
This may require adjustments to the authorizedPermissionTypes field, or waiting for further processing solutions

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/01aa5443-0d58-4d47-921a-2588046ee239)

pass
