### ISSUE TITLE
[Bug]: Data archiving and data cleaning can select tables without permission

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3015]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/86ad936a-07f2-42e7-be33-4d23f46ebceb)
![image](https://github.com/user-attachments/assets/68076a98-fce4-4a87-b63f-572e9365844f)

### What did you expect to happen?

Do not display tables without permission

### How can we reproduce it (as minimally and precisely as possible)?

1. Application Form for Change of Permissions for Low Permission Accounts
2. Create data archive, data cleaning

**Comment by yezaoshu** [comment]
This may require adjustments to the authorizedPermissionTypes field, or waiting for further processing solutions

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/b511c35c-acc2-4c64-a31e-cf928c96fd9e)

pass
