### ISSUE TITLE
[Bug]: The table with change permission failed to execute multi database changes

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3018]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/8551347b-f1bc-4c03-9cdc-5b6bd10b8948)
![image](https://github.com/user-attachments/assets/7bdf0dac-9fdc-4b13-81e4-28ec67806aba)
![image](https://github.com/user-attachments/assets/b66537c9-a41f-4bf6-98b6-b8a01800fe45)

### What did you expect to happen?

Execution successful

### How can we reproduce it (as minimally and precisely as possible)?

1. Apply for table change permissions for two tables with the same table name in different databases
2. Select these two databases in the multi database change, enter the change statement, and execute

**Comment by MarkPotato777** [comment]
It is expected that users without database change permission cannot create the database change ticket.

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/3c55a349-15a3-48ec-8a31-e73fbe847ceb)
pass
