### ISSUE TITLE
[Bug]: Create a table with no error when the table permission is limited

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3020]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/8dd4e64b-4d02-4beb-9ae3-86b5931aba8b)

### What did you expect to happen?

Error reported during table creation or disabled table creation button

### How can we reproduce it (as minimally and precisely as possible)?

1. Add permissions to a table
2. Click to create table

**Comment by sl01388797** [comment]
Other views, functions, stored procedures, etc. all have this issue

**Comment by yezaoshu** [comment]
I solved this problem by hiding action btn when the perission is ['ACCESS']

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/135bf5b3-6e61-4377-a533-636cfe3a219c)

pass
