### ISSUE TITLE
[Bug]: There should be no request table permission button below the statement to create a table in a database with only table permissions

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3021]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/1d424885-29c0-4d90-a665-8cb6d266b0d0)

### What did you expect to happen?

The permission button for the application form does not need to exist

### How can we reproduce it (as minimally and precisely as possible)?

1. Apply for permission to access a table in a database
2. Execute table building SQL in SQL window

**Comment by yezaoshu** [comment]
the unauthorizedPermissionTypes is 'CHANGE', and error tableName  in unauthorizedDBResources  is 'shilin_cs', which is a non-existent table. So the tableName should not be returned to me. The front-end determines whether to display the request form permission button based on whether the tableName exists

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/6023f5ae-e358-41ab-980f-bd39b2b6e223)
