### ISSUE TITLE
[Bug]: Multiple databases cannot be selected for homepage changes

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3023]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/10572d22-5896-49c1-a293-b6a2ef45946b)

### What did you expect to happen?

You can choose a database

### How can we reproduce it (as minimally and precisely as possible)?

Open Multi Library Change on the homepage, select the project

**Comment by HSunboy** [comment]
Fixed In Commit [09c91b0383272c642e099a4fc1d89e00c013eabe](https://github.com/oceanbase/odc-client/commit/09c91b0383272c642e099a4fc1d89e00c013eabe)
            ------
            陈朝俊
            Mon Jul 29 14:07:55 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/5c1e3a14-ec92-4806-9d26-f8e0db3388a5)

pass
