### ISSUE TITLE
[Bug]: Desktop version execution analysis shows excessive line offset

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3025]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/26a9b897-8d7f-43fe-ab42-6a164edfdb86)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/3d0db8e9-7719-405d-b72e-5c5fb265a443)

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL query on desktop version, click to execute profile

**Comment by yezaoshu** [comment]
Please repackage the desktop version product

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/d0cbf221-e05a-4b81-81a1-540debbcaea9)

pass

**Comment by HSunboy** [comment]
Fixed In Commit [eef46482569b2f0dac54dab8293cc8d9ff707ed9](https://github.com/oceanbase/odc-client/commit/eef46482569b2f0dac54dab8293cc8d9ff707ed9)
            ------
            畅晚
            Tue Jul 30 11:30:19 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/258fca65-8177-4b4a-9d06-3d0683a124ec)

pass
