### ISSUE TITLE
[Bug]: Desktop SQL execution settings are inconsistent with web version

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3026]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/4888035b-1163-43a5-bfb9-e06d5150a2d7)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/d4420aba-b6c9-4a6c-bb7c-ff3cafad5cfe)

### How can we reproduce it (as minimally and precisely as possible)?

Open the SQL window and view the SQL settings

**Comment by yezaoshu** [comment]
Please repackage the desktop version product

**Comment by yezaoshu** [comment]
Please repackage the desktop version product

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/f494c6fa-5c5d-42e0-aa8b-fdbac451e5c5)

pass
