### ISSUE TITLE
[Bug]: After the foreign key constraint is created, the field value 'delete_rule' obtained by clicking on structure in odc is inconsistent with being obtained by odc using sql command and black screen sql command

### ISSUE THREAD

**Issue by zijiacj** [oceanbase/odc#3028]
### ODC version

odc431 may any

### OB version

ob 430 may any 

### What happened?

After the foreign key constraint is created, the field value 'delete_rule' obtained by clicking on structure in odc is inconsistent with being obtained by odc using sql command and black screen sql command
![截屏2024-07-26 18 24 30](https://github.com/user-attachments/assets/245e3d08-fbda-4bf9-9859-85b4241b9bb0)
![截屏2024-07-26 18 20 26](https://github.com/user-attachments/assets/e94fc89f-f7f1-4a93-8a65-259d9a5fad32)
![截屏2024-07-26 18 21 46](https://github.com/user-attachments/assets/d9187850-9dc1-4111-828e-cc600822c17d)

### What did you expect to happen?

The field value 'delete_rule' must be consistent

### How can we reproduce it (as minimally and precisely as possible)?

CREATE TABLE test_parent_table (
    id NUMBER PRIMARY KEY,
    data VARCHAR2(100)
);

CREATE TABLE child_table (
    id NUMBER,
    parent_id NUMBER,
    data VARCHAR2(100)
);

ALTER TABLE child_table ADD CONSTRAINT FK_PARENT FOREIGN KEY (parent_id) REFERENCES test_parent_table(id); 

desc dba_constraints;

select * from dba_constraints where owner='ZIJIA' and table_name in ('CHILD_TABLE','TEST_PARENT_TABLE');

**Comment by tonghan-gsh** [comment]
pass
![Image](https://github.com/user-attachments/assets/09ba8d29-7e71-4bca-92b5-f3f38374477a)
