### ISSUE TITLE
[Bug]: After the execution details of the portrait are collapsed, clicking on the time consumption page will not open

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3034]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/33c92d2a-1677-4f05-b968-91797856a20c)
![image](https://github.com/user-attachments/assets/832bea17-2f42-41d9-9a83-1cc090ac1995)

### What did you expect to happen?

After clicking on the time, the page will expand

### How can we reproduce it (as minimally and precisely as possible)?

1. Execute query statement
2. Click to execute portrait
3. Click time after folding the page

**Comment by HSunboy** [comment]
Fixed In Commit [78650f9870fa3a158c1b8482e83b9c02e86ec66d](https://github.com/oceanbase/odc-client/commit/78650f9870fa3a158c1b8482e83b9c02e86ec66d)
            ------
            畅晚
            Mon Jul 29 18:28:28 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/c4689687-5bf9-42e6-ac32-fbe5ad74e50e)

pass
