### ISSUE TITLE
[Bug]: When creating a new character and selecting all objects, the error prompt will not disappear

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#304]
### ODC version

odc420

### OB version

ob410

### What happened?

Create a new role, click New, and an error message will prompt you to fill in the role name and select a manageable object. After selecting all objects, the error prompt does not disappear
![image](https://github.com/oceanbase/odc/assets/143492234/31630071-776d-48b8-b7dc-9b74056ecd63)

### What did you expect to happen?

Error prompt disappears

### How can we reproduce it (as minimally and precisely as possible)?

Create a new role, click New, and an error message will prompt you to fill in the role name and select a manageable object. After selecting all objects, the error prompt does not disappear

**Comment by HSunboy** [comment]
Fixed In Commit [5c0acb0a509bb4e4d2486e600a4cc374e6db0b0e](https://github.com/oceanbase/odc-client/commit/5c0acb0a509bb4e4d2486e600a4cc374e6db0b0e)
            ------
            咏和
            Sun Dec 10 18:02:52 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/863bfc77-91b3-42cc-b078-5dfbce0381c9)
pass
