### ISSUE TITLE
[Bug]: No data on the start time and duration of the entire link

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3040]
### ODC version

odc431

### OB version

ob4215

### What happened?

![image](https://github.com/user-attachments/assets/965d2926-ab09-4912-a412-ffdcf000bbbb)

### What did you expect to happen?

Display start time and duration

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL query and click on the full link link

**Comment by HSunboy** [comment]
Fixed In Commit [78650f9870fa3a158c1b8482e83b9c02e86ec66d](https://github.com/oceanbase/odc-client/commit/78650f9870fa3a158c1b8482e83b9c02e86ec66d)
            ------
            畅晚
            Mon Jul 29 18:28:28 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/211bccea-409f-46d7-8fd5-13346485b463)

pass
