### ISSUE TITLE
[Bug]: 'The lastAccessTime time' in the project is empty

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3042]
### ODC version

ODC 4.3.1

### OB version

No related.

### What happened?

'The lastAccessTime time' in the project is empty.
![image](https://github.com/user-attachments/assets/1e841332-ed2d-43aa-875b-fa3ae9ad0444)

### What did you expect to happen?

Show 'the lastAccessTime time'.

### How can we reproduce it (as minimally and precisely as possible)?

Check 'the lastAccessTime time' in the project.

**Comment by HSunboy** [comment]
Fixed In Commit [eef46482569b2f0dac54dab8293cc8d9ff707ed9](https://github.com/oceanbase/odc-client/commit/eef46482569b2f0dac54dab8293cc8d9ff707ed9)
            ------
            畅晚
            Tue Jul 30 11:30:19 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/078ac699-c2d7-46eb-b63f-b31948d253a7)

pass
