### ISSUE TITLE
[Bug]: Table containing virtual columns exported data into sql format error

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3043]
### ODC version

ODC 4.3.1

### OB version

No related.

### What happened?

The table 'te' contains virtual columns and exports the data as sql files. 
![image](https://github.com/user-attachments/assets/38d98c62-2e29-480a-9861-a0bc35d9995c)
![image](https://github.com/user-attachments/assets/af560223-0d03-44fa-9958-0cbe6445f99e)
Execution of the exported insert statement reported a syntax error,because virtual columns do not support insert.
![image](https://github.com/user-attachments/assets/af560223-0d03-44fa-9958-0cbe6445f99e)

### What did you expect to happen?

sql files should not concatenate virtual column values.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by LuckyPickleZZ** [comment]
The inability to import exported data is not a problem with our functionality. ODC should not decide which data to not export on our own. 
There may be a scenario : a column is a virtual column in Table A, but not in Table B. If we do not export this column when exporting, then the importing into B would fail. Customers may think that we have lost data.
