### ISSUE TITLE
[Bug]: Desktop version structure comparison usage error

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3051]
### ODC version

odc431

### OB version

*

### What happened?

![Image](https://github.com/user-attachments/assets/f603b9a5-a9f0-4a69-a5b7-ea897a3147b1)
![Image](https://github.com/user-attachments/assets/834f2762-ade2-479b-8578-be1c277cd626)
![image](https://github.com/user-attachments/assets/f5894318-a6db-449f-8605-40c0dbdeb180)

### What did you expect to happen?

Normal execution

### How can we reproduce it (as minimally and precisely as possible)?

Desktop version execution structure comparison

**Comment by yizhouxw** [comment]
it seems OB KB table ?

**Comment by PeachThinking** [comment]
This is a bug in the kernel DDL. The DDL obtained by show create table does not conform to the syntax file. Directly executing this DDL will also fail. Parse table ddl error for : 
CREATE TABLE `t1$f1` (
  `K` varbinary(1024) NOT NULL,
  `Q` varbinary(256) NOT NULL,
  `T` bigint(20) NOT NULL,
  `V` varbinary(1048576) NOT NULL,
  PRIMARY KEY (`K`, `Q`, `T`)
) DEFAULT CHARSET = gbk ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0 KV_ATTRIBUTES = ({"Hbase": {"TimeToLive": 30, "MaxVersions": 3}})
 partition by key(k)
(partition `p0`,
partition `p1`,
partition `p2`)

**Comment by tonghan-gsh** [comment]
ob4.2.5 will solve this problem.
