### ISSUE TITLE
[Bug]: viewing the ddl of the pl having 2000 + lines is too slow, which takes about one minute

### ISSUE THREAD

**Issue by zijiacj** [oceanbase/odc#3056]
### ODC version

The customer used 424, the new version 431 also has the same problem

### OB version

may any

### What happened?

clicking to view the ddl of pl having 2000 + lines, querying dictionary views from ob data is fast, but odc programs run too slowly at the parse stage

### What did you expect to happen?

Improve the odc parse speed

### How can we reproduce it (as minimally and precisely as possible)?

Create a pl having 2000 + lines ,then find the pl in the left resource tree and click it to view the ddl statement

**Comment by yhilmare** [comment]
can not reproduce it, I have tried a procedure that contains 1W+ lines and cost about 3982 ms
