### ISSUE TITLE
[Enhancement]: Manually execute and enable backup script generation are selected by default when a database change work order is initiated

### ISSUE THREAD

**Issue by zijiacj** [oceanbase/odc#3059]
### What would you like to be added?

Manually execute and enable backup script generation are selected by default when a database change ticket is initiated

### Why is this needed?

it is more reasonable

**Comment by HSunboy** [comment]
Fixed In Commit [e94b64b0b25abdd13d49f191a01068e9cecab341](https://github.com/oceanbase/odc-client/commit/e94b64b0b25abdd13d49f191a01068e9cecab341)
            ------
            畅晚
            Tue Aug 6 09:55:12 2024 +0800
