### ISSUE TITLE
[Bug]: The description of the database change work order for SQL plan execution is in English

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3060]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/5bd7ae4f-2f08-4a01-8324-183eb9b19385)

### What did you expect to happen?

Database change description in Chinese

### How can we reproduce it (as minimally and precisely as possible)?

Create SQL plan to execute database changes

**Comment by yhilmare** [comment]
the description should not be i18n, because the description should be searched
