### ISSUE TITLE
[Bug]:  access control not valid in anonymous sql block

### ISSUE THREAD

**Issue by LioRoger** [oceanbase/odc#3064]
### ODC version

4.2.4

### OB version

4.x oracle mode

### What happened?

current env:
    database: aps
    user access authority: no

in anonymous blocks:
     execute sql:
```sql
     declare
        i number;
    begin
      update aps.base_logs t set t.last_update_time = sysdata where t.id = 1;
       commit;
    end;
```
sql expected to be blocked cause not access authority granted to aps database

### What did you expect to happen?

anonymous sql block should also check access authority

### How can we reproduce it (as minimally and precisely as possible)?

current env:
    database: aps
    user access authority: no

in sql console
execute sql:
```
    update aps.base_logs t set t.last_update_time = sysdata where t.id = 1
```
result:
     sql was blocked cause write authority not granted

in anonymous blocks:
     execute sql:
```sql
     declare
        i number;
    begin
      update aps.base_logs t set t.last_update_time = sysdata where t.id = 1;
       commit;
    end;
```
sql expected to be blocked as sql console does but was execute successful

**Comment by qymsummer** [comment]
![Screenshot_20240731_191309_com alibaba android rimet aliding](https://github.com/user-attachments/assets/8d9097dd-5479-47e5-93a9-36c9c1a2db1b)
Success
