### ISSUE TITLE
[Bug]: Database Change will always be timeout after 8h

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#307]
### ODC version

4.1.3

### OB version

any

### What happened?

When a database change task is executed for more than 8 hours, it would definitely be timed out.
In log, error message shows : `Connection session was closed`.

### What did you expect to happen?

The task shouldn't fail .

### How can we reproduce it (as minimally and precisely as possible)?

Create a task which would be more than 8h.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/07e7150b-444e-4de5-9670-9ffb3d0b6b7f)

pass
