### ISSUE TITLE
[Bug]: Unable to apply for library permissions

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3075]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/bb4e36d9-1801-4f62-b50b-672cf3156e2a)

### What did you expect to happen?

Can apply for library permissions

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL statements that operate on tables within the SQL window of low privilege accounts

**Comment by HSunboy** [comment]
Fixed In Commit [e94b64b0b25abdd13d49f191a01068e9cecab341](https://github.com/oceanbase/odc-client/commit/e94b64b0b25abdd13d49f191a01068e9cecab341)
            ------
            畅晚
            Tue Aug 6 09:55:12 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/90f822fd-e562-445c-8aa4-c0f19d20ba91)

pass
