### ISSUE TITLE
[Bug]: Invalid data source within the permission of the application form without obvious display

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3080]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/8616f516-5cc3-4f85-a884-758abb8e5bc7)

### What did you expect to happen?

Invalid data source displayed in gray

### How can we reproduce it (as minimally and precisely as possible)?

Apply for form permissions after disabling the data source

**Comment by HSunboy** [comment]
Fixed In Commit [e94b64b0b25abdd13d49f191a01068e9cecab341](https://github.com/oceanbase/odc-client/commit/e94b64b0b25abdd13d49f191a01068e9cecab341)
            ------
            畅晚
            Tue Aug 6 09:55:12 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/05d4d1da-0730-45a8-bb32-9b545c883328)

pass
