### ISSUE TITLE
[Bug]: As long as the table authority is limited, the three points behind the database disappear

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3090]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/ec1771c6-6453-4005-ad8c-8203b132f5d0)

### What did you expect to happen?

There are three points

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a database with only table permissions
2. view the database

**Comment by HSunboy** [comment]
Fixed In Commit [e94b64b0b25abdd13d49f191a01068e9cecab341](https://github.com/oceanbase/odc-client/commit/e94b64b0b25abdd13d49f191a01068e9cecab341)
            ------
            畅晚
            Tue Aug 6 09:55:12 2024 +0800
