### ISSUE TITLE
[Bug]: Adding columns on a white screen without error in a table without change permission

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3092]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/d69f0ef3-b719-4870-aed3-4448723a1945)

### What did you expect to happen?

There is an error reported

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a table without change permission
2. Add Column

**Comment by HSunboy** [comment]
Fixed In Commit [a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471](https://github.com/oceanbase/odc-client/commit/a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471)
            ------
            畅晚
            Wed Sep 4 09:54:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/27dad0bf-b0a7-4d11-a48f-9132ce46da28)
Executing SQL in the attribute pop-up window still yields no prompts

**Comment by HSunboy** [comment]
Fixed In Commit [8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a](https://github.com/oceanbase/odc-client/commit/8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a)
            ------
            畅晚
            Wed Sep 11 10:00:03 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/e5cffab1-c26f-44fb-bf18-43b8961062eb)
After clicking on the permissions for the application library and application form, a pop-up window cannot appear

**Comment by HSunboy** [comment]
Fixed In Commit [d6ced46754053d5e7c1308995c8014843ea30b6b](https://github.com/oceanbase/odc-client/commit/d6ced46754053d5e7c1308995c8014843ea30b6b)
            ------
            畅晚
            Wed Sep 11 16:57:54 2024 +0800
