### ISSUE TITLE
[Bug]: The selection box opened by right clicking is too small

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3093]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/6be8343f-db1e-4246-a78d-faa5c3de4371)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/b223c5a3-6849-420b-9a50-5b56afde7c15)

### How can we reproduce it (as minimally and precisely as possible)?

Right click to open the database selection box

**Comment by HSunboy** [comment]
Fixed In Commit [e94b64b0b25abdd13d49f191a01068e9cecab341](https://github.com/oceanbase/odc-client/commit/e94b64b0b25abdd13d49f191a01068e9cecab341)
            ------
            畅晚
            Tue Aug 6 09:55:12 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/adb51cac-28d9-448d-bdb4-f3c975a1a96d)

pass
