### ISSUE TITLE
[Bug]: The specified archive partition cannot be initiated again.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3096]
### ODC version

ODC431

### OB version

independent

### What happened?

The specified archive partition cannot be initiated again.
![image](https://github.com/user-attachments/assets/8e461ef5-34b2-45e3-842f-3d58ebaa2f4f)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

1. create task
2. specifing archive partition

**Comment by HSunboy** [comment]
Fixed In Commit [e94b64b0b25abdd13d49f191a01068e9cecab341](https://github.com/oceanbase/odc-client/commit/e94b64b0b25abdd13d49f191a01068e9cecab341)
            ------
            畅晚
            Tue Aug 6 09:55:12 2024 +0800
