### ISSUE TITLE
[Bug]: Clicking on the metadata synchronization button will not change the metadata synchronization

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3097]
### ODC version

odc431

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/1ba61dae-4a5d-45cd-8ec5-4db939af5888)

### What did you expect to happen?

The data synchronization button turns into a circle

### How can we reproduce it (as minimally and precisely as possible)?

Click the data synchronization button

**Comment by HSunboy** [comment]
Fixed In Commit [e94b64b0b25abdd13d49f191a01068e9cecab341](https://github.com/oceanbase/odc-client/commit/e94b64b0b25abdd13d49f191a01068e9cecab341)
            ------
            畅晚
            Tue Aug 6 09:55:12 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/19d301dd-c9e7-42e2-8e41-36b62d6881c1)

pass
