### ISSUE TITLE
[Bug]: select the word, ctrl+c, then ctrl+f, then ctrl+v，the word that select  is cut

### ISSUE THREAD

**Issue by fuyu1217** [oceanbase/odc#310]
### ODC version

4.2.0

### OB version

all

### What happened?

as the title says, 
select the word, ctrl+c, then ctrl+f, then ctrl+v，the word that select  is cut

![image](https://github.com/oceanbase/odc/assets/142562110/ffe6c698-54ad-4af6-918b-96ccdc0ed773)

![image](https://github.com/oceanbase/odc/assets/142562110/bcb6f72a-9fb3-41d8-be8c-53a35cb4c8e0)

### What did you expect to happen?

the word that select  is reserved

### How can we reproduce it (as minimally and precisely as possible)?

...

**Comment by HSunboy** [comment]
Same as https://github.com/oceanbase/odc/issues/339

**Comment by Huangxiao-mas** [comment]
test pass
