### ISSUE TITLE
[Bug]: After the project application task matches the risk level,an error occurred when viewing task details

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3105]
### ODC version

ODC 4.3.1

### OB version

No related.

### What happened?

Risk level Set is：
![image](https://github.com/user-attachments/assets/dbad8331-d1f0-42e4-b02b-8533845dd5b3)
Use a common user to deliver a project permission request task and view the task details
![image](https://github.com/user-attachments/assets/16ceeb0d-830f-4733-814f-a25be22d3a3f)
![image](https://github.com/user-attachments/assets/ecb01819-3dff-414e-9496-cc4b2f648b08)

### What did you expect to happen?

No error is reported when viewing task details

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by HSunboy** [comment]
Fixed In Commit [b40ca0edadcb8460478c2b8b68df2dfb2fe67088](https://github.com/oceanbase/odc-client/commit/b40ca0edadcb8460478c2b8b68df2dfb2fe67088)
            ------
            畅晚
            Tue Aug 6 20:02:33 2024 +0800

**Comment by tonghan-gsh** [comment]
pass
![Image](https://github.com/user-attachments/assets/8d9f9c69-4550-4b56-9f08-2c9fcc6249b3)
