### ISSUE TITLE
[Bug]: when content type of reponse is text/plain, the notification would fail

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#3113]
### ODC version

4.2+

### OB version

-

### What happened?

when content type of reponse is text/plain, the notification would fail.

### What did you expect to happen?

ODC should process response correctlly.

### How can we reproduce it (as minimally and precisely as possible)?

Send a message to a webhook with a response format of text/plain

**Comment by Huangxiao-mas** [comment]
pass
