### ISSUE TITLE
[Bug]: syntax error when creating a table contains column with geometry datatype

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#312]
### ODC version

ODC421

### OB version

Oceanbase4.1.0

### What happened?

There is a syntax error when creating a report, but the sql is executed successfully
![image](https://github.com/oceanbase/odc/assets/59468957/05e9d1b2-03ce-4bf4-a02c-9875c1fdf419)

### What did you expect to happen?

execution succeed

### How can we reproduce it (as minimally and precisely as possible)?

Execute the following sql
```SQL
create table if not exists `t1_g` (
	`id` int(11),
	`name` varchar(18),
	`g` geometry not null
)
default charset=utf8mb4
default collate=utf8mb4_general_ci;
create index `t1_g_idx1` on `t1_g` (`g` ASC);
```

**Comment by yhilmare** [comment]
`geometry` is a new datatype involved in OceanBase 4.x, our parser ignore it, we may add this syntax to fix this bug

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/54a6ef04-f259-48b4-a92c-00867d0e5f33)

pass
