### ISSUE TITLE
[Bug]: fail to export mysql data on windows 

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#3125]
### ODC version

4.2.x

### OB version

mysql

### What happened?

When export mysql data on windows, there would be an exception `InvalidPathException: Illegal char <*> at index xxx`.
This is because of `*` is an illegal character in path on windows. We should not use Paths#get method here.
```java
 command.add(Paths.get(dataxHomePath, SystemUtils.isOnWindows() ? "lib/*" : "lib/*:.").toString());
```

### What did you expect to happen?

export successfully

### How can we reproduce it (as minimally and precisely as possible)?

-

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/fa407d17-c3bd-4e87-a332-be894510a4de)
pass
