### ISSUE TITLE
[Bug]: failed to generate partition name on ob-mysql mode

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#3132]
### ODC version

4.3.1

### OB version

not related

### What happened?

1. create a table contains upper case partition key:
```sql
CREATE TABLE `datetime_range_parti_tbl` (
  `id` int(11) DEFAULT NULL,
  `parti_key` datetime DEFAULT NULL
) DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0
 partition by range columns(PARTI_KEY)
(partition `p20200301` values less than ('2020-03-01 00:00:00'),
partition `p20210301` values less than ('2021-03-01 00:00:00'),
partition `p20220301` values less than ('2022-03-01 00:00:00'),
partition `p20230301` values less than ('2023-03-01 00:00:00'),
partition `p20240301` values less than ('2024-03-01 00:00:00'))
```

2. create a partition plan and use custom partition name generator:

![截屏2024-08-16 20 35 52](https://github.com/user-attachments/assets/3f590b12-44ea-4f96-8876-b8e75fb567ae)

as you can see, I ref the **UPPER CASE** partition key and I click 'test generate':
![截屏2024-08-16 20 36 48](https://github.com/user-attachments/assets/5541168f-f2ce-46fd-b503-eff51ace5fef)

3. I change ref the lower case partition key and I click 'test generate':
![截屏2024-08-16 20 37 48](https://github.com/user-attachments/assets/5c99eb2b-0ed4-4f26-b336-ce217d5882c2)

### What did you expect to happen?

I can ref the UPPER CASE partition key

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by tonghan-gsh** [comment]
![image](https://github.com/user-attachments/assets/77d262a1-e484-4e2f-93b1-9b19c5f29bc5)
pass
