### ISSUE TITLE
[Bug]: there is no alert message send when partition plan executed failed

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#3133]
### ODC version

4.3.1

### OB version

not related

### What happened?

1. start a partition plan task
<img width="760" alt="截屏2024-08-16 21 29 37" src="https://github.com/user-attachments/assets/aeebdedd-1c58-46d5-9c3a-25802debbe91">

<img width="381" alt="截屏2024-08-16 21 28 01" src="https://github.com/user-attachments/assets/f3673f0c-fbe6-47d0-bf77-f0ba086825c9">

3. modify the target table or delete the related datasource to make sure that the partition plan task will not executed successfully

<img width="922" alt="截屏2024-08-16 21 29 15" src="https://github.com/user-attachments/assets/2b61d470-fcad-4c25-ad8b-752a300d6a1e">

as you can see, I change the partition key's name

### What did you expect to happen?

I config the alert tunnel on partition plan execution failure:
<img width="1162" alt="截屏2024-08-16 21 30 55" src="https://github.com/user-attachments/assets/8467d855-56e2-46e6-83ab-b10be2ae2024">

I expect that I can get the alert and I check the odc.log, the partition plan task is failed as I expected:
![截屏2024-08-16 21 31 49](https://github.com/user-attachments/assets/18c1ae04-2579-43ef-9d42-ff264fd90193)

there is no alert~

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by tonghan-gsh** [comment]
![image](https://github.com/user-attachments/assets/90f0553b-fc2c-4b34-97f7-1b4abfa03786)
![image](https://github.com/user-attachments/assets/56209ffd-6fef-4e8d-b3a5-7e6b906bffc9)
pass
