### ISSUE TITLE
[Bug]: If you do not have the permission to change a table, the change statement is executed in an anonymous block, and the change statement is displayed incorrectly

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3139]
### ODC version

ODC 432 

### OB version

If you do not have the permission to change a table, the change statement is executed in an anonymous block, and the change statement is displayed incorrectly

### What happened?

If you do not have the permission to change the table, the change statement is executed in the anonymous block, and the message "Failed to run request abort" is displayed.
![image](https://github.com/user-attachments/assets/d223c986-2961-485a-8cb1-2cd0b0013b37)

### What did you expect to happen?

If you do not have the permission to change the table, you should get the same result as if you run the SQL window when you execute the SQL change in an anonymous block
![image](https://github.com/user-attachments/assets/7d0151b6-38d2-4372-8d9c-51ea88a68206)

### How can we reproduce it (as minimally and precisely as possible)?

If you do not have the permission to change the table, the change statement is executed in the anonymous block, and the message "Failed to run request abort" is displayed.

**Comment by HSunboy** [comment]
Fixed In Commit [a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471](https://github.com/oceanbase/odc-client/commit/a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471)
            ------
            畅晚
            Wed Sep 4 09:54:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/3182d218-7707-456c-961e-9e5e5aceaf48)
pass
