### ISSUE TITLE
[Bug]: Viewing the details page of historical archiving tasks reports a parameter error.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3149]
### ODC version

ODC432

### OB version

independent

### What happened?

Viewing the details page of historical archiving tasks reports a parameter error.
![image](https://github.com/user-attachments/assets/08d42122-d762-46eb-ad1a-9b3196dc9092)
![image](https://github.com/user-attachments/assets/72da2b51-8085-423a-ab98-3560753b506d)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

env:chat privately
taskId=197

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/aa60450a-976d-4e8e-98f7-002b03640173)
pass
