### ISSUE TITLE
[Bug]: Unable to expand database object

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3157]
### ODC version

ODC432

### OB version

independent

### What happened?

Unable to expand database object
![image](https://github.com/user-attachments/assets/ed8ec975-47b9-4b0e-b56b-0c23e87a03b7)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

click database

**Comment by HSunboy** [comment]
Fixed In Commit [5d74146e2f41c2df6f22e27b0850775a3a196baf](https://github.com/oceanbase/odc-client/commit/5d74146e2f41c2df6f22e27b0850775a3a196baf)
            ------
            畅晚
            Wed Aug 21 12:57:58 2024 +0800
