### ISSUE TITLE
[Bug]: When importing the file, the id is undefined and does not exist.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#316]
### ODC version

odc421

### OB version

Oceanbase410

### What happened?

When importing the file, the id is undefined and does not exist.
![image](https://github.com/oceanbase/odc/assets/59468957/f7eb7e1d-d257-4b4b-a964-4d8bfe21e330)
![image](https://github.com/oceanbase/odc/assets/59468957/c4757cd4-6796-4ec1-9490-4ace4ac764af)

### What did you expect to happen?

Execute normally

### How can we reproduce it (as minimally and precisely as possible)?

1. Import the file in the import panel, uncheck Ignore the first line
2. Select the corresponding library and table
3. Select next
4. Go back to the previous step and check Ignore first line
5. Click again

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3e49043b-ac1f-447b-9e3f-b5f553e81d15)

pass
