### ISSUE TITLE
[Bug]: Scanning sensitive columns does not support fuzzy search

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3161]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/fb99c7a0-1f7e-4c47-ad33-e684cdd65532)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/7a7132b4-6235-4d84-9c7b-628f6501a9c0)

### How can we reproduce it (as minimally and precisely as possible)?

Click on the sensitive column within the project, click on 'Scan and Add', and select 'Database'

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/d192c4d4-55de-4c88-a49b-eb664f962349)
The problem still exists

**Comment by manyyuri** [comment]
![Image](https://github.com/user-attachments/assets/152b085d-0865-4461-ba97-b64a47da7c2e)
表现符合设计稿

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/82a5df34-7786-4d5c-b33c-b90cdbf75fea)
pass
