### ISSUE TITLE
[Bug]: There is a button to return to the homepage in the personal space

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3162]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/a244f875-ad75-483a-9bc5-d77be3ec54da)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/12baa260-fa6b-4fca-9694-7bd756e3eb10)

### How can we reproduce it (as minimally and precisely as possible)?

Enter personal space

**Comment by HSunboy** [comment]
Fixed In Commit [a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471](https://github.com/oceanbase/odc-client/commit/a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471)
            ------
            畅晚
            Wed Sep 4 09:54:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/653ada93-36b1-4fa6-8c15-f23a4de64434)

pass
