### ISSUE TITLE
[Bug]: The native oracle is archived to oboracle, and the cleanup report does not exist after the task is archived

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3164]
### ODC version

ODC432

### OB version

independent

### What happened?

The native oracle is archived to oboracle, and the cleanup report does not exist after the task is archived
![image](https://github.com/user-attachments/assets/ac792368-bdd6-463e-8a2a-6ba245315030)
![image](https://github.com/user-attachments/assets/adc1d84d-e208-4e3d-abe7-f263e9a21d44)
![image](https://github.com/user-attachments/assets/d7b81b81-85f2-4cf3-a71e-14dc4a3768a1)

### What did you expect to happen?

after archive，can clean success

### How can we reproduce it (as minimally and precisely as possible)?

taskId= 799

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/607cb041-f56e-41be-979f-263e5e5530a6)
pass
