### ISSUE TITLE
[Bug]: oracle2OBoracle archiving failed, exception log 'oracle.sql.BLOB cannot be cast to com.oceanbase.jdbc.Blob'

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3166]
### ODC version

ODC432

### OB version

independent

### What happened?

oracle2OBoracle archiving failed, exception log 'oracle.sql.BLOB cannot be cast to com.oceanbase.jdbc.Blob'
![image](https://github.com/user-attachments/assets/05c7327f-c8f6-434e-99c4-c3e2542ab99a)
![image](https://github.com/user-attachments/assets/44afea41-1f68-4b14-8c6d-8393609d5253)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?
taskId= 801
table like this
```
CREATE TABLE "TC_TARCHIVES" 
   (	"VC_TENANT_ID" VARCHAR2(32) NOT NULL ENABLE, 
	"VC_ARCHIVES_NO" VARCHAR2(24) NOT NULL ENABLE, 
	"VC_REQUEST_NO" VARCHAR2(32), 
	"C_ARCHIVES_TYPE" CHAR(2), 
	"B_ARCHIVES_CONTENT" BLOB, 
	"VC_OP_TIME" VARCHAR2(14), 
	"VC_OPERATOR_NO" VARCHAR2(16), 
	"C_AUDIT_FLAG" CHAR(1), 
	"VC_AUDIT_NO" VARCHAR2(16), 
	"C_ARCHIVES_STATE" CHAR(1), 
	"VC_CUST_NO" VARCHAR2(12), 
	"L_SERIAL_NO" NUMBER, 
	"VC_DESCRIBE" VARCHAR2(256), 
	"VC_STORAGE_FILE_NAME" VARCHAR2(255), 
	"VC_TRADE_ACCO" VARCHAR2(32), 
	"VC_MANAGER_CODE" VARCHAR2(18), 
	"VC_REJECT_REASON" VARCHAR2(100), 
	"VC_REMARK" VARCHAR2(256), 
	"VC_PRODUCT_CODE" VARCHAR2(32), 
	"VC_STORAGE_FILE_PATH" VARCHAR2(256), 
	"VC_STORAGE_FILE_NO" VARCHAR2(100), 
	"VC_BATCH_NO" VARCHAR2(32), 
	 CONSTRAINT "PK_TC_TARCHIVES" PRIMARY KEY ("VC_TENANT_ID", "VC_ARCHIVES_NO")
   )
```

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/01c4b6b0-96a2-40b2-869f-c1752385389b)
The problem still exists
