### ISSUE TITLE
[Bug]: The log printing task execution error occurs, and the page status shows success

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3167]
### ODC version

ODC432

### OB version

independent

### What happened?

The log printing task execution error occurs, and the page status shows success
![image](https://github.com/user-attachments/assets/b8ca3b24-7dd7-4a4d-81bb-e3f90fedf633)
![image](https://github.com/user-attachments/assets/47043873-d592-429d-80ce-663744f5fbb7)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

taskId= 802
table like this
create task ,OBoracle2oracle
```
create table TC_TENTERPRISECONTROLLERANALY
(
    VC_TENANT_ID            VARCHAR2(32) not null,
    VC_SERIAL_NO            VARCHAR2(20) not null,
    VC_OTHER_SERIAL_NO      VARCHAR2(60),
    VC_CUST_NO              VARCHAR2(12),
    EN_NEXT_LEVEL_COUNT     NUMBER(6),
    EN_PERCENT_TOTAL        NUMBER(9,6),
    VC_LEVEL_DESC           VARCHAR2(16),
    VC_COMPANY_KEY_NO       VARCHAR2(128),
    EN_FUNDING_PERCENT      NUMBER(9,6),
    VC_COMPANY_NAME         VARCHAR2(64),
    VC_JSON_CONTENT         VARCHAR2(2000),
    VC_CREATE_DATE          VARCHAR2(8),
    VC_CREATE_TIME          VARCHAR2(6),
    VC_MODIFY_MACHINE_DATE  VARCHAR2(8),
    VC_MODIFY_MACHINE_TIME  VARCHAR2(6),
    VC_ENTERPRISE_INFO_JSON CLOB,
    constraint PK_ENTERPRISECONTROLLERANALY primary key (VC_TENANT_ID, VC_SERIAL_NO)
)
;
create index IDX_ENTERCONTROLLANALY_OSERIAL on TC_TENTERPRISECONTROLLERANALY (VC_OTHER_SERIAL_NO);
```

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/23864be7-54e1-49c5-aeee-b45972e49248)
The problem still exists
