### ISSUE TITLE
[Bug]: The command line window is disconnected directly after connecting

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3168]
### ODC version

ODC432

### OB version

independent

### What happened?

The command line window is disconnected directly after connecting
![image](https://github.com/user-attachments/assets/9ab52b23-4859-46aa-962d-9a7c9b7a8c9c)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by LuckyPickleZZ** [comment]
lost obclient binary file. may caused by incorrect deployment.
