### ISSUE TITLE
[Bug]: When the database name is too long, the permission display for the application form is incorrect

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3170]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/9a0001aa-6bc3-4913-b1c7-54c18068eee9)

### What did you expect to happen?

Normal display

### How can we reproduce it (as minimally and precisely as possible)?

Create a database with an excessively long library name and apply for table permissions

**Comment by HSunboy** [comment]
Fixed In Commit [2c524061531005196c4e543a39c6b662cac1714c](https://github.com/oceanbase/odc-client/commit/2c524061531005196c4e543a39c6b662cac1714c)
            ------
            畅晚
            Mon Sep 2 10:10:14 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/1aa671cc-aaa8-4121-87f8-8b06d3a2c316)

pass
