### ISSUE TITLE
[Bug]: There was no synchronization object when creating the shadow table task by right clicking

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3172]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/c7425656-f460-4fc5-817a-a155c6feb2f1)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/757593d9-86c8-4922-99d8-6c460ea3ac0e)

### How can we reproduce it (as minimally and precisely as possible)?

Right click on the database to create shadow table synchronization task

**Comment by HSunboy** [comment]
Fixed In Commit [a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471](https://github.com/oceanbase/odc-client/commit/a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471)
            ------
            畅晚
            Wed Sep 4 09:54:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/3b7af026-febf-4f68-b29b-72d92c9a2bf7)
Oracle can also perform shadow table synchronization

**Comment by qymsummer** [comment]
pass 

Oracle shadowless table synchronization
