### ISSUE TITLE
[Bug]: On the data source page, the pg database cannot be created

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3174]
### ODC version

ODC432

### OB version

independent

### What happened?

On the data source page, the pg database cannot be created
![image](https://github.com/user-attachments/assets/2e72e33a-17b1-4196-b6be-31b0da407fa7)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by kiko-art** [comment]
This feature is not included in this development
