### ISSUE TITLE
[Bug]: No echo after creating data source and filling in database in pg database

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3175]
### ODC version

ODC432

### OB version

pg

### What happened?

No echo after creating data source and filling in database in pg database
![image](https://github.com/user-attachments/assets/c2ce93ed-3457-46a8-b287-565d8d3bd5e6)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by yezaoshu** [comment]
![Image](https://github.com/user-attachments/assets/5d16982e-09fa-4ef1-922a-deee9065fd80)

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/4a4600df-c38c-4453-9dd1-b4fc6107e2c9)
pass
