### ISSUE TITLE
[Bug]: The total viewing time on the result set page is incorrect

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3177]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/0d8480aa-9f06-42cf-90cf-918e7f95d56f)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/56850ffe-6c4a-46d3-b36c-4a2758e19b5d)

### How can we reproduce it (as minimally and precisely as possible)?

Execute SQL queries in SQL windows

**Comment by manyyuri** [comment]
底部展示的总耗时，与执行记录的总耗时栏一致

**Comment by manyyuri** [comment]
结果页 “总耗时”文案改为“DB 耗时”

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/ce918e4a-e7b8-4390-8c41-9bfe31b410c8)

pass
