### ISSUE TITLE
[Bug]: The archive operation record is displayed as empty

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3179]
### ODC version

ODC432

### OB version

independent

### What happened?

The archive operation record is displayed as empty
![image](https://github.com/user-attachments/assets/81b9d017-83ec-4f3d-b57a-78eaa89121c4)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

check the task operation

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/b9cb48e0-71e1-46ee-8440-5eabb9450726)
pass
