### ISSUE TITLE
[Bug]: The pg database archives the ob database, and the log prints a null pointer

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3180]
### ODC version

ODC432

### OB version

pg9
oboralce422

### What happened?

The pg database archives the ob database, and the log prints a null pointer
![image](https://github.com/user-attachments/assets/d0069660-4d7d-4755-b582-5f5b0921494c)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by Huangxiao-mas** [comment]
The pg database password is empty.

**Comment by kiko-art** [comment]
fixed
