### ISSUE TITLE
[Bug]: There is a database change button in the PG data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3182]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/510284e8-353d-4693-b37f-a5b98ead76fe)
![image](https://github.com/user-attachments/assets/5b003620-0b79-466c-92be-cdc6647cb7dc)

### What did you expect to happen?

PG data source cannot select database changes

### How can we reproduce it (as minimally and precisely as possible)?

Create a PG data source and add it to the project

**Comment by HSunboy** [comment]
Fixed In Commit [0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e](https://github.com/oceanbase/odc-client/commit/0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e)
            ------
            畅晚
            Tue Aug 27 17:47:24 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/4fd27cbd-333b-4dbc-ba0d-69b8b10a64c4)

pass
