### ISSUE TITLE
[Bug]: Multiple database changes can choose PG data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3183]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/0819c70b-d520-41d5-b94c-b39a800b1862)

### What did you expect to happen?

Unable to select PG data source

### How can we reproduce it (as minimally and precisely as possible)?

Multiple database changes select PG data source

**Comment by HSunboy** [comment]
Fixed In Commit [0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e](https://github.com/oceanbase/odc-client/commit/0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e)
            ------
            畅晚
            Tue Aug 27 17:47:24 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/ab192512-c766-4c70-a664-43b3f4ac5a64)

pass
