### ISSUE TITLE
[Bug]: PG data source can be selected within the global variable

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3184]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/07719c4e-9596-4897-bd2e-9a170151055e)

### What did you expect to happen?

PG data source cannot be selected within global variables

### How can we reproduce it (as minimally and precisely as possible)?

Select PG data source within global variables

**Comment by HSunboy** [comment]
Fixed In Commit [0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e](https://github.com/oceanbase/odc-client/commit/0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e)
            ------
            畅晚
            Tue Aug 27 17:47:24 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/289cfa45-9202-449a-a94b-08a790e73d89)

pass
