### ISSUE TITLE
[Bug]: The bit type pg database failed to roll back after being cleaned up after being archived to ob

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3187]
### ODC version

ODC432

### OB version

- pg9
- oceanbase422

### What happened?

The byte type pg database failed to roll back after being cleaned up after being archived to ob
![image](https://github.com/user-attachments/assets/fbf35241-f297-4e92-901b-da48d2067887)
![image](https://github.com/user-attachments/assets/7b1cea9d-06db-4942-b412-7e87121b22da)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

```
CREATE TABLE test_5 (
	col1 int4 NOT NULL,
	col2 numeric(10, 2) NULL,
	col3 numeric(10, 2) NULL,
	col4 bit(8) NULL,
	col5 int2 NULL,
	 PRIMARY KEY (col1)
);
```

```
INSERT INTO public.test_5 (col1,col2,col3,col4,col5) VALUES
	 (2,NULL,NULL,'10101010',NULL);

```

**Comment by kiko-art** [comment]
fixed
