### ISSUE TITLE
[Bug]: After successfully archiving a bytea type field, cleanup fails and a DefinedException is reported

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3189]
### ODC version

ODC432

### OB version

independent

### What happened?

After successfully archiving a bytea type field, cleanup fails and a DefinedException is reported
![image](https://github.com/user-attachments/assets/490ad49e-b93a-4e06-ad7b-1103489972dd)
![image](https://github.com/user-attachments/assets/94cfc10a-f029-4031-893e-bd2ab4542f62)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

```
CREATE TABLE public.test_8 (
	col1 int4 NOT NULL,
	col2 numeric(10, 5) NULL,
	col3 numeric(10, 7) NULL,
	col4 bytea NULL,
	col5 float4 NULL,
	CONSTRAINT test_8_pkey PRIMARY KEY (col1)
);
```

```
INSERT INTO public.test_8 (col1,col2,col3,col4,col5) VALUES
	 (1,5.11323,98.1812368,NULL,9.81232);

```

**Comment by kiko-art** [comment]
fixed
