### ISSUE TITLE
[Bug]: Data masking fails when using multiple JOIN clauses in SQL

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#319]
### ODC version

4.2.1

### OB version

Any

### What happened?

When execute:
```sql
SELECT
  s.*
FROM
  student s
  INNER JOIN student_teacher st ON s.id = st.student_id
  INNER JOIN teacher t ON st.teacher_id = t.id;
```
Data masking is failed.

### What did you expect to happen?

Some columns of result set should be masked.

### How can we reproduce it (as minimally and precisely as possible)?

Execute above SQL.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/fd79ca84-2892-43b2-be7b-2762c75ee0b4)

pass
