### ISSUE TITLE
[Bug]: SQL scheduled task details cannot be viewed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3191]
### ODC version

ODC432

### OB version

.

### What happened?

SQL scheduled task details cannot be viewed
![image](https://github.com/user-attachments/assets/42658952-c251-44c5-913f-5c773e903908)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

check sql plan task details

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/b240c830-a448-4a7c-847d-8d383991e29e)
pass
