### ISSUE TITLE
[Bug]: PG data source displayed in the structure tree

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3192]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/d36db55a-46d5-4f41-9189-64814fb4b4ef)

### What did you expect to happen?

PG data source should not be displayed in the structure tree

### How can we reproduce it (as minimally and precisely as possible)?

Add PG data source to the project and enter the project

**Comment by HSunboy** [comment]
Fixed In Commit [2c524061531005196c4e543a39c6b662cac1714c](https://github.com/oceanbase/odc-client/commit/2c524061531005196c4e543a39c6b662cac1714c)
            ------
            畅晚
            Mon Sep 2 10:10:14 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/72c5068a-7771-473b-a5b7-e6eae4096c1b)

pass
