### ISSUE TITLE
[Bug]: pg database json data type failed to clean up after archiving

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3193]
### ODC version

ODC432

### OB version

independent

### What happened?

pg database json data type failed to clean up after archiving
![image](https://github.com/user-attachments/assets/13706e50-cc8b-4ee3-a45a-695309d77b76)
![image](https://github.com/user-attachments/assets/d0e7a492-d3ee-4130-b3a4-f6bbd45405f4)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

taskId= 826

**Comment by kiko-art** [comment]
fixed

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/2f00fd70-4f06-410d-a553-2e55e18ce9ac)
![image](https://github.com/user-attachments/assets/4e51e966-279f-492c-b42f-3fb0548d5bea)
pass
