### ISSUE TITLE
[Bug]: pg database TIMESTAMP_TZ data type failed to clean up after archiving

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3199]
### ODC version

ODC432

### OB version

independent

### What happened?

pg database TIMESTAMP_TZ data type failed to clean up after archiving
![image](https://github.com/user-attachments/assets/af0d2b79-c15b-4fd4-951d-16030fe606e7)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

```

CREATE TABLE test_timestmpe (
    id SERIAL PRIMARY KEY, -- 可选：添加一个自增主键
    timestamp_without_tz TIMESTAMP WITHOUT TIME ZONE,
    timestamp_with_tz TIMESTAMP WITH TIME ZONE,
    date_field DATE,
    time_field TIME,
    interval_field INTERVAL
);
```
```
INSERT INTO public.test_timestmpe (timestamp_without_tz,timestamp_with_tz,date_field,time_field,interval_field) VALUES
	 ('2023-01-02 00:00:00.000','2023-01-02 00:00:00.000','2023-01-02','07:36:35','00:13:00');

```

**Comment by kiko-art** [comment]
ob-mysql is not support TIMESTAMP_TZ column type.
