### ISSUE TITLE
[Bug]: pg database archive data archive half of the connection timed out

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3200]
### ODC version

ODC432

### OB version

independent

### What happened?

pg database archive data archive half of the connection timed out
![image](https://github.com/user-attachments/assets/ae0d0388-b8d9-409b-949f-1a6e758e8a92)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

taskId=832

**Comment by Huangxiao-mas** [comment]
The task cannot be stopped

**Comment by kiko-art** [comment]
fixed

**Comment by kiko-art** [comment]
fixed
