### ISSUE TITLE
[Bug]: See more features that are not yet available

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3214]
### ODC version

ODC 4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/3faa7afb-d386-4767-b017-97b40c22995d)
See more features that are not yet available

### What did you expect to happen?

Handle the See More button correctly

### How can we reproduce it (as minimally and precisely as possible)?

Select a logical library, click the table, select the + sign, and the common instance will pop up at this time, and there is a View More button, and there is no response when you click View More

**Comment by MarkPotato777** [comment]
hyperlink to the docs, ref: https://code.alipay.com/oceanbase-docs/odc-enterprise/blob/432/zh-CN/500.sql-development/700.database-objects/100.web-odc-table-objects/200.web-odc-create-a-table.md

**Comment by HSunboy** [comment]
Fixed In Commit [ca6fa41f84303821a107c1ed66dedd6949927ebb](https://github.com/oceanbase/odc-client/commit/ca6fa41f84303821a107c1ed66dedd6949927ebb)
            ------
            畅晚
            Wed Sep 25 18:39:48 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/16597d7d-004c-480b-a4c5-226aacd54fe9)
pass
