### ISSUE TITLE
[Feature]: The display effect and functions of Full-Link-Trace need to be optimized

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#322]
### Is your feature request related to a problem?

The current display effect of the FullLinkTrace function is not very suitable for us to locate the problem. Moreover, it lacks search, sorting and other functions, making it inconvenient to use.
Plus, when observer's version is lower than 4.1, FullLinkTrace is not available. It may give some hints.

### Describe the solution you'd like

FullLinkTrace requires functions such as search and sorting. 
When this function is not available, prompt the reason, such as OB version lower than 4.1.

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [8d10bd035e7d594f9f24a1b070b43fbb18d39ce9](https://github.com/oceanbase/odc-client/commit/8d10bd035e7d594f9f24a1b070b43fbb18d39ce9)
