### ISSUE TITLE
[Bug]: As you can see, the second logical text prompt blocks the check button of the first logical library

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3222]
### ODC version

4.3.2

### OB version

no related

### What happened?

As you can see, the second logical text prompt blocks the check button of the first logical library
![image](https://github.com/user-attachments/assets/bf17592f-072f-4224-95db-44b051ea98c4)

### What did you expect to happen?

The hint does not obscure the button

### How can we reproduce it (as minimally and precisely as possible)?

As you can see, the second logical text prompt blocks the check button of the first logical library

**Comment by HSunboy** [comment]
Fixed In Commit [2c524061531005196c4e543a39c6b662cac1714c](https://github.com/oceanbase/odc-client/commit/2c524061531005196c4e543a39c6b662cac1714c)
            ------
            畅晚
            Mon Sep 2 10:10:14 2024 +0800

**Comment by qymsummer** [comment]
pass
