### ISSUE TITLE
[Bug]: When the SQL statement is executed in the SQL window of the logic database, the SQL statement does not respond ...

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3223]
### ODC version

4.3.2

### OB version

no related

### What happened?

DDL statements in the schema database cannot be executed in the SQL window, and when the SQL statement is executed in the SQL window, there should be a relevant prompt instead of no response

### What did you expect to happen?

DDL statements in the schema database cannot be executed in the SQL window, and when the SQL statement is executed in the SQL window, there should be a relevant prompt instead of no response

### How can we reproduce it (as minimally and precisely as possible)?

DDL statements in the schema database cannot be executed in the SQL window, and when the SQL statement is executed in the SQL window, there should be a relevant prompt instead of no response

**Comment by MarkPotato777** [comment]
The current design is that users cannot open the logical database's SQL console.
