### ISSUE TITLE
[Bug]: When you create a logical table, the table creation specification prompted disappears when you select Copy with the mouse

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3226]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/83f4dcd6-3314-485d-8e54-43ff7603b3c1)
When you create a logical table, the table creation specification prompted will disappear when you select Copy in the mouse and you can copy the table creation specification instead

### What did you expect to happen?

When you create a logical table, the table creation specification prompted will disappear when you select Copy in the mouse and you can copy the table creation specification instead

### How can we reproduce it (as minimally and precisely as possible)?

Create a logical table and click the + sign

**Comment by HSunboy** [comment]
Fixed In Commit [2c524061531005196c4e543a39c6b662cac1714c](https://github.com/oceanbase/odc-client/commit/2c524061531005196c4e543a39c6b662cac1714c)
            ------
            畅晚
            Mon Sep 2 10:10:14 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/9194da05-b81d-4576-9b53-515033b3c253)
pass
