### ISSUE TITLE
[Bug]: When you create a new database, the alias of the database does not have a non-null check

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3227]
### ODC version

4.3.2

### OB version

no related

### What happened?

When you create a new database, there is no limit on non-empty or ultra-long characters for the aliases of the database
![image](https://github.com/user-attachments/assets/a388c659-0d3b-4f1f-8c9a-d9a745437245)

### What did you expect to happen?

When you create a new database, the system prompts you to enter only spaces or extra-long characters for the alias of the database

### How can we reproduce it (as minimally and precisely as possible)?

When you enter an alias in a new database, enter a space or extra-long character and click Submit.

**Comment by HSunboy** [comment]
Fixed In Commit [8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a](https://github.com/oceanbase/odc-client/commit/8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a)
            ------
            畅晚
            Wed Sep 11 10:00:03 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/a4b5a2ac-4f30-451a-af1c-14b149d55c99)
pass
