### ISSUE TITLE
[Bug]: A user who uses the Administrator role. If you grant the user logical table permissions, an error message is displayed

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3232]
### ODC version

4.3.2

### OB version

no related

### What happened?

A user who uses the Administrator role. If you grant the user table permissions, an error message is displayed
![image](https://github.com/user-attachments/assets/9263ba0b-d705-442c-a685-7292f8cfcd58)

### What did you expect to happen?

You can grant permissions to users on tables

### How can we reproduce it (as minimally and precisely as possible)?

When an administrator user enters the project, clicks Members, clicks Manage Permissions, and clicks Table Permissions, an error is displayed

**Comment by MarkPotato777** [comment]
Works for me
![Image](https://github.com/user-attachments/assets/83259b26-e848-4ac3-8f36-03a23c08c3fd)

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/a16b4505-fd22-43f9-9171-f3b243d54405)
pass

**Comment by sl01388797** [comment]
![44fa081820e22f17385bf8afcfd3873d](https://github.com/user-attachments/assets/8039ead1-ecdd-4321-8646-bbb8fbe6ea91)
There are problems

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/ba041d3b-99cb-4298-987a-c16da2af4e13)
pass
