### ISSUE TITLE
[Bug]: Unable to link command line window for viewing within data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3241]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/00b48d7d-5bea-4565-a9c7-0a6d71a23b84)

### What did you expect to happen?

Link successful

### How can we reproduce it (as minimally and precisely as possible)?

View command line window within data source

**Comment by LuckyPickleZZ** [comment]
incorrect obclient version
