### ISSUE TITLE
[Bug]: When no session is selected in the data source session window, there are no buttons to close the session or close the query

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3242]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/ae9069c7-83b2-423c-a1c7-e56538fdc5a6)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/e05d2ebe-227c-45c5-9ad5-1fe8e95d5cd5)

### How can we reproduce it (as minimally and precisely as possible)?

View sessions in the database

**Comment by HSunboy** [comment]
Fixed In Commit [2c524061531005196c4e543a39c6b662cac1714c](https://github.com/oceanbase/odc-client/commit/2c524061531005196c4e543a39c6b662cac1714c)
            ------
            畅晚
            Mon Sep 2 10:10:14 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/c14b0763-b934-47ed-b563-ee024f3ca68c)

pass
