### ISSUE TITLE
[Bug]: The error script prompt is in English

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3245]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/5d678455-78e1-46d9-a616-f91cd7fb6d9c)

### What did you expect to happen?

Prompt in Chinese

### How can we reproduce it (as minimally and precisely as possible)?

Save script in SQL window

**Comment by HSunboy** [comment]
Fixed In Commit [e0f83d9ddcee2e643fefb6e57636fe4883888345](https://github.com/oceanbase/odc-client/commit/e0f83d9ddcee2e643fefb6e57636fe4883888345)
            ------
            xiaokang
            Thu Sep 5 10:13:34 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/c5f1db91-a70e-4574-9e8c-9ded3f66ef04)

pass
