### ISSUE TITLE
[Bug]: Functions with multi cloud links, stored procedures cannot run

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3256]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/931dfb8d-be3a-4ad6-94e1-e396f1e01b52)
![image](https://github.com/user-attachments/assets/29e95de9-8b56-469f-af1b-e3edb6dfb753)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/8067458b-d696-4286-90ae-aff1cdacce2f)
![image](https://github.com/user-attachments/assets/a7b47945-46f9-4960-9b4e-67f83a26a8e5)

### How can we reproduce it (as minimally and precisely as possible)?

Create multi cloud links, functions, and stored procedures within a proprietary cloud

**Comment by HSunboy** [comment]
Fixed In Commit [a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471](https://github.com/oceanbase/odc-client/commit/a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471)
            ------
            畅晚
            Wed Sep 4 09:54:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/01614ae4-8b72-4ea6-b78f-f4c464320e63)
pass
