### ISSUE TITLE
[Bug]: Page crashes after selecting virtual columns

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3258]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/c9e58fd5-155d-463a-b200-929f68b8dba4)

![image](https://github.com/user-attachments/assets/bfb52e3d-5deb-41c3-bdd9-09a3f66a7499)

### What did you expect to happen?

The page does not crash

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Table
CREATE TABLE `test1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `col` decimal(10,2) NOT NULL,
  `col1` varchar(120) DEFAULT NULL,
  `col2` blob DEFAULT NULL,
  `K` varbinary(1024) NOT NULL,
   `K_PREFIX` varbinary(1024) GENERATED ALWAYS AS (substr(`K`,1,26)) VIRTUAL,
  PRIMARY KEY (`id`)
)
2. View the K_PREVIX column

**Comment by HSunboy** [comment]
Fixed In Commit [a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471](https://github.com/oceanbase/odc-client/commit/a22e48e5c4656ac2c26fb6af70c9d6c1f7d77471)
            ------
            畅晚
            Wed Sep 4 09:54:36 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/746c333c-9a1e-4006-b68f-f2368764651c)

pass
