### ISSUE TITLE
[Bug]: Apply to become a developer of the project, and the task description shows that it is an ordinary member.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3262]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

![image](https://github.com/user-attachments/assets/f60d6b26-57e0-498c-8355-33f8b3b533e2)

### What did you expect to happen?

The task description should be displayed as a developer.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/2f7d66c7-1426-476c-993e-67b61255b5a8)
pass
