### ISSUE TITLE
[Bug]: incorrect version of obloader/obdumper  doc link 

### ISSUE THREAD

**Issue by yehaow** [oceanbase/odc#3265]
### ODC version

ODC 432
obloader/obdumper 4311

### OB version

independent

### What happened?

 incorrect version of obloader/obdumper  doc link 
![image](https://github.com/user-attachments/assets/0ac4de1d-c92b-4f3d-9611-4a0c85040b48)

### What did you expect to happen?

correct referenced version of obloader/obdumper

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/user-attachments/assets/01bcf547-16d0-48cb-bdb7-b3d83ddc9495)

**Comment by HSunboy** [comment]
Fixed In Commit [8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a](https://github.com/oceanbase/odc-client/commit/8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a)
            ------
            畅晚
            Wed Sep 11 10:00:03 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/1446589e-aabe-4bfa-9f4f-a641765e8426)
pass
