### ISSUE TITLE
[Bug]: display issue with import objects fields

### ISSUE THREAD

**Issue by yehaow** [oceanbase/odc#3270]
### ODC version

ODC 432

### OB version

independent

### What happened?

display issue with import objects fields
![image](https://github.com/user-attachments/assets/22add93c-aa08-4a5a-a0dd-f4c872ba3d25)

### What did you expect to happen?

appropriate display effect

### How can we reproduce it (as minimally and precisely as possible)?

language: English
Page: view detail with Data Import ticket

**Comment by HSunboy** [comment]
Fixed In Commit [8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a](https://github.com/oceanbase/odc-client/commit/8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a)
            ------
            畅晚
            Wed Sep 11 10:00:03 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/82660dd4-7b03-4e3a-8fda-0e38ec306e44)
pass
