### ISSUE TITLE
[Bug]: The page cannot be scrolled when there are too many risk identification rules.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3276]
### ODC version

ODC 4.3.1

### OB version

No related.

### What happened?

![image](https://github.com/user-attachments/assets/92084c2e-d612-42cd-881f-ea32358caca2)
The page cannot be scrolled when there are too many risk identification rules

### What did you expect to happen?

The page can also slide when there are too many risk identification rules.

### How can we reproduce it (as minimally and precisely as possible)?

Create more than 6 risk identification rules.

**Comment by HSunboy** [comment]
Fixed In Commit [98a6745c43d6cf63ccf4660fdb0797006dd02636](https://github.com/oceanbase/odc-client/commit/98a6745c43d6cf63ccf4660fdb0797006dd02636)
            ------
            xiaokang
            Thu Sep 5 11:05:25 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/360f51c2-ca79-4e58-88d5-e8d1fb22661e)
pass
