### ISSUE TITLE
[Bug]: Error reporting when creating too many risk identification rules

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3278]
### ODC version

ODC 4.3.1

### OB version

No related.

### What happened?

Error reporting when creating too many risk identification rules.Error accessing the metadata database.
![image](https://github.com/user-attachments/assets/dbe3a095-bc0d-4514-b5ff-ae8548f560a9)

### What did you expect to happen?

No error reporting.

### How can we reproduce it (as minimally and precisely as possible)?

Create a lot of risk identification.

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/55ed838f-47fe-4509-876d-e41ff1afa8b9)
pass
