### ISSUE TITLE
[Bug]: Sensitive columns disappear when modifying tables with sensitive columns

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3286]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/82a2a974-761a-4c02-a84a-046f09a2109f)
![image](https://github.com/user-attachments/assets/fdbd91a5-902e-47d1-83f1-741d4a8b9a14)
![image](https://github.com/user-attachments/assets/041489ed-af9a-4e93-a984-a3f24d847aeb)

### What did you expect to happen?

Sensitive columns still in effect

### How can we reproduce it (as minimally and precisely as possible)?

Create a table, add data, set sensitive columns, delete a column

**Comment by LuckyPickleZZ** [comment]
This is by design. ODC would cache the column info for `3 minutes`. So the schema change would be detected delayly.
