### ISSUE TITLE
[Bug]: Create an archiving task. Click Create continuously to create two identical archiving tasks.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3287]
### ODC version

ODC432

### OB version

independent

### What happened?

Create an archiving task. Click Create continuously to create two identical archiving tasks.
![image](https://github.com/user-attachments/assets/7c0e1a4f-14a1-4713-83ff-093917618274)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a](https://github.com/oceanbase/odc-client/commit/8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a)
            ------
            畅晚
            Wed Sep 11 10:00:03 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/43c79edc-1193-43c1-9fc2-78d056e01d54)
pass
