### ISSUE TITLE
[Bug]: When exporting tables and PLs together in a sql file, and reimport in ODC, syntax error happened.

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#3306]
### ODC version

4.3.0

### OB version

Not related.

### What happened?

As said in title.

### What did you expect to happen?

Import successfully.

### How can we reproduce it (as minimally and precisely as possible)?

1. export tables and PLs, and export them in one single SQL file
2. import that export file again.

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/390a863f-2f0f-4960-a1a8-cb5b4c4268c6)
pass
