### ISSUE TITLE
[Bug]: The name of the logical table button is inconsistent with the design

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3309]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/bedabc71-95a8-4898-b41a-f5a3f6b38e23)
![image](https://github.com/user-attachments/assets/5b087a25-5004-4b65-8474-c5ff5c3a9a96)
The name of the logical table button is inconsistent with the design

### What did you expect to happen?

The names of logical table management buttons are the same as those in the design drawing

### How can we reproduce it (as minimally and precisely as possible)?

The name of the logical table button is inconsistent with the design

**Comment by HSunboy** [comment]
Fixed In Commit [823b104c85cd9ea52ceb48e44407e87a1478eb6b](https://github.com/oceanbase/odc-client/commit/823b104c85cd9ea52ceb48e44407e87a1478eb6b)
            ------
            畅晚
            Wed Sep 11 10:04:44 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/af04f58a-86a7-43cd-bc89-36a1a6fd6fa8)
pass
