### ISSUE TITLE
[Bug]: Error occurred when canceling the permission selection for the application form change after selecting the project

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3311]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/605077e8-2a3c-4838-aa6c-230c6739170e)

### What did you expect to happen?

Pop up window appears in front

### How can we reproduce it (as minimally and precisely as possible)?

After applying for permission on the application form, select the project and click on the blank space

**Comment by HSunboy** [comment]
Fixed In Commit [8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a](https://github.com/oceanbase/odc-client/commit/8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a)
            ------
            畅晚
            Wed Sep 11 10:00:03 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/97670e2c-3f5a-44ac-b6a3-5b7bbcb976d2)
pass
