### ISSUE TITLE
[Bug]: The message notification does not have line breaks.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3336]
### ODC version

ODC 4.3.1

### OB version

No related.

### What happened?

![Uploading image.png…]()
Message notification shows "\n", no line breaks.

### What did you expect to happen?

Display message notifications with line breaks.

### How can we reproduce it (as minimally and precisely as possible)?

Send Message Notification.

**Comment by HSunboy** [comment]
Fixed In Commit [8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a](https://github.com/oceanbase/odc-client/commit/8e5c660f3ec447e4d9e93bfd33f1b604e28f1c0a)
            ------
            畅晚
            Wed Sep 11 10:00:03 2024 +0800

**Comment by sl01388797** [comment]
pass
