### ISSUE TITLE
[Bug]: An error occurred with the NPE when selecting the logical database for the application permission task

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3339]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

![Uploading image.png…]()
requestId:"IZ0TAKZQUO9O1PZDHH9IZO"

### What did you expect to happen?

The task of issuing application library permissions for the logical database should be successfully dispatched.

### How can we reproduce it (as minimally and precisely as possible)?

Distribute the application database permission task to the logical database.

**Comment by MarkPotato777** [comment]
duplicated with #3229
