### ISSUE TITLE
[Bug]: A table without table change permission needs to change the table name to display the change permission for a new table

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3340]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/1c3d6e1a-3b22-483e-9a27-8b7b8ee49725)

### What did you expect to happen?

Just need the change permission of the original table

### How can we reproduce it (as minimally and precisely as possible)?

Create a table without change permission and modify the table name

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/532125cf-bd4d-4203-b811-e7924e866661)

**Comment by zijiacj** [comment]
![image](https://github.com/user-attachments/assets/d1ca7c0f-c015-4849-8775-3bd83baeb325)
Maybe the code is not up to date，try redeploying the latest code

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/32a8dccf-dbc2-4881-970f-5f4cf185b44c)
pass
