### ISSUE TITLE
[Bug]: Click on data archive to jump to logic change again

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3346]
### ODC version

ODC432

### OB version

independent

### What happened?

Click on data archive to jump to logic change again
![image](https://github.com/user-attachments/assets/90d364bd-30f5-4ee0-b058-2cfe246f0735)
![image](https://github.com/user-attachments/assets/ea8b9dea-2e43-4357-9c8d-91dcca5cc425)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [6c75e27e69a337e5e73d82fc447bffc111348e89](https://github.com/oceanbase/odc-client/commit/6c75e27e69a337e5e73d82fc447bffc111348e89)
            ------
            畅晚
            Fri Sep 13 09:57:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/221fa042-bb9d-4e15-a8d7-b00439789b13)
pass
