### ISSUE TITLE
[Bug]: Create a ticket for creating a table in a logic database and an error message is reported

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3348]
### ODC version

odc4.3.2 

### OB version

no related 

### What happened?

Create a ticket for creating a table in a logic database and an error message is reported
CREATE TABLE "logical_QS235"."QS235.test_[00-09]" (
"a1" VARCHAR(120) NULL  DEFAULT NULL,
CONSTRAINT "a3" PRIMARY KEY ("a1")
) ;
CREATE  INDEX "a1" USING BTREE ON "logical_QS235"."QS235.test_[00-09]" () GLOBAL;
![image](https://github.com/user-attachments/assets/456dbb8d-8584-416a-b22e-43a4ecd1a342)
![image](https://github.com/user-attachments/assets/25d02d12-8e01-4c12-a706-5868f7124d9f)

### What did you expect to happen?

A table creation ticket can be created successfully, and the table can be created successfully

### How can we reproduce it (as minimally and precisely as possible)?

Create a ticket for creating a table in a logic database and click Create in the ticket

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/c6187300-221b-4e48-a1a4-b685cb6e88c0)
pass
