### ISSUE TITLE
[Bug]: Schema databases do not support Oracle and oboracle data sources, and there should be corresponding restrictions when creating a schema database

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3349]
### ODC version

odc 4.3.2

### OB version

no related

### What happened?

 Schema databases do not support Oracle and oboracle data sources, and there should be corresponding restrictions when creating a schema database

### What did you expect to happen?

 Schema databases do not support Oracle and oboracle data sources, and there should be corresponding restrictions when creating a schema database

### How can we reproduce it (as minimally and precisely as possible)?

When creating a logical database, select an oracle data source.

**Comment by HSunboy** [comment]
Fixed In Commit [6c75e27e69a337e5e73d82fc447bffc111348e89](https://github.com/oceanbase/odc-client/commit/6c75e27e69a337e5e73d82fc447bffc111348e89)
            ------
            畅晚
            Fri Sep 13 09:57:13 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/df308c9f-ac89-4071-862d-b05c2d40d962)
pass
