### ISSUE TITLE
[Bug]: Create a table creation ticket, click New, and after the new creation is successful, there is no pop-up window on the interface

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3350]
### ODC version

4.3.2

### OB version

no related

### What happened?

Create a table creation ticket, click New, and after the new creation is successful, there is no pop-up window on the interface
![image](https://github.com/user-attachments/assets/d424f4b2-e356-4b8f-8566-6e48c941c236)
![image](https://github.com/user-attachments/assets/25f93140-58e6-46e1-8e44-d42e6eee0d15)

### What did you expect to happen?

After a table creation ticket is created, a message is displayed on the page

### How can we reproduce it (as minimally and precisely as possible)?

Create a table creation ticket, click New, and after the new creation is successful, there is no pop-up window on the interface

**Comment by HSunboy** [comment]
Fixed In Commit [6c75e27e69a337e5e73d82fc447bffc111348e89](https://github.com/oceanbase/odc-client/commit/6c75e27e69a337e5e73d82fc447bffc111348e89)
            ------
            畅晚
            Fri Sep 13 09:57:13 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/799fb44e-bb18-4319-99f9-e33a70f0a0e6)
pass
