### ISSUE TITLE
[Bug]: The logical database name is incorrectly generated

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3351]
### ODC version

odc 4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/46166832-455c-40fc-a80e-589f3e25d8c5)
The logical database name is incorrectly generated

### What did you expect to happen?

If the logical database name is generated incorrectly, the logical database name should be generated according to the physical database name and related rules

### How can we reproduce it (as minimally and precisely as possible)?

Configure and commit a logic library

**Comment by HSunboy** [comment]
Fixed In Commit [c1469755bb913bc85ab7c9b46b43e454079713fd](https://github.com/oceanbase/odc-client/commit/c1469755bb913bc85ab7c9b46b43e454079713fd)
            ------
            畅晚
            Fri Sep 20 18:48:17 2024 +0800

**Comment by qymsummer** [comment]
pass
