### ISSUE TITLE
[Bug]: When you create a logical table, the example error message is displayed

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3356]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/6e2cf8b1-0501-407c-bd47-a93cbdeddec8)
When creating a logical table, the example test_ [00-09] indicates that there is an error, and the logical library should be added to test_ [00-09] db.test_ [00-09]

### What did you expect to happen?

When creating a logical table, the example test_ [00-09] indicates that there is an error, and the logical library should be added to test_ [00-09] db.test_ [00-09]

### How can we reproduce it (as minimally and precisely as possible)?

When you create a logical table, expand the prompt example

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/06a2331a-4eac-4334-8f37-2042d47c7a6f)
pass
