### ISSUE TITLE
[Bug]: If the expression of the table created in the logical database is incorrect, the error message displayed is not detailed

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3363]
### ODC version

odc 4.3.2

### OB version

no related

### What happened?

If the expression of the table created in the logical database is incorrect, the error message displayed is not detailed
![image](https://github.com/user-attachments/assets/71b45afe-16b0-4db1-8d74-d7fccd42f2c7)
![image](https://github.com/user-attachments/assets/17626525-a4c2-4001-bfff-a5271defde2a)

### What did you expect to happen?

If the expression of the table created in the logic database is incorrect, the specific cause of the error is displayed

### How can we reproduce it (as minimally and precisely as possible)?

To create a logical table, enter an incorrect logical library expression

**Comment by HSunboy** [comment]
Fixed In Commit [6c75e27e69a337e5e73d82fc447bffc111348e89](https://github.com/oceanbase/odc-client/commit/6c75e27e69a337e5e73d82fc447bffc111348e89)
            ------
            畅晚
            Fri Sep 13 09:57:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/2389d20e-650c-45e5-bd8d-36c166e2684b)
pass
