### ISSUE TITLE
[Bug]: Failed to create a table in the logical database

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3368]
### ODC version

odc 4.3.2

### OB version

no related 

### What happened?

Database sharding does not shard, and the logical database fails to create tables
DDL

CREATE TABLE `test_table[01-09]`.`test` (
`A1` int ,
`A2` varbinary(120) ,
`A3` varchar(120) 
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;

### What did you expect to happen?

Database sharding does not shard, and the logical database is successfully created

### How can we reproduce it (as minimally and precisely as possible)?

Create a database sharding without sharding tables

**Comment by MarkPotato777** [comment]
it will not create physical databases. it will only creates physical tables. you need to guarantee that your physical database have already existed.
