### ISSUE TITLE
[Bug]: Removing a schema does not have a double determination button

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3370]
### ODC version

4.3.2

### OB version

no related

### What happened?

Removing a schema does not have a double determination button
![image](https://github.com/user-attachments/assets/56e8076b-3636-4161-8445-2d2a23a98740)

### What did you expect to happen?

There is no quadratic confirmation button for removing a schema, and there should be a quadratic confirmation for removal

### How can we reproduce it (as minimally and precisely as possible)?

Removing a schema does not have a double determination button

**Comment by HSunboy** [comment]
Fixed In Commit [6c75e27e69a337e5e73d82fc447bffc111348e89](https://github.com/oceanbase/odc-client/commit/6c75e27e69a337e5e73d82fc447bffc111348e89)
            ------
            畅晚
            Fri Sep 13 09:57:13 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/1ea29536-8ce6-4cb8-973c-5c57b678ff2f)
pass
