### ISSUE TITLE
[Bug]: The table creation of a database ticket fails

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3373]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/3b11c799-0084-4e08-98a4-7863eaa50c7a)
![image](https://github.com/user-attachments/assets/bbf873b3-99ff-47bc-bc0f-2144a36d5b3f)
CREATE TABLE `logical_test_table01`.`test_table[01-09].test` (
`A1` varchar(120) NULL,
`A2` int(11) NULL,
`A3` numeric(10, 2) NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;
The execution of the logic database table creation ticket fails

### What did you expect to happen?

If you use a logical database to create a table and create a ticket, you can create a table successfully

### How can we reproduce it (as minimally and precisely as possible)?

The execution of the logic database table creation ticket fails

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/59856006-84e2-42a4-b706-619cca68e8c2)
pass
