### ISSUE TITLE
[Bug]: If the SQL statement generated by the logic database is incorrect, the schema should not be concatenated

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3374]
### ODC version

4.3.2

### OB version

no related

### What happened?

If the SQL statement generated by the logic database is incorrect, the schema should not be concatenated
![image](https://github.com/user-attachments/assets/dc60368d-4d5d-4d07-8ebc-7b1ad6e4af51)

### What did you expect to happen?

If the SQL statement generated by the logic database is incorrect, the schema should not be concatenated

### How can we reproduce it (as minimally and precisely as possible)?

If the SQL statement generated by the logic database is incorrect, the schema should not be concatenated

**Comment by MarkPotato777** [comment]
duplicated with #3375
