### ISSUE TITLE
[Bug]: The new logical representation needs to be modified

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3378]
### ODC version

odc4.3.2

### OB version

no related

### What happened?

The new logical example is inaccurate and needs to be modified
![image](https://github.com/user-attachments/assets/29217e8e-3311-4c26-8b74-362b0d496424)

### What did you expect to happen?

The new logical example is inaccurate and needs to be modified

### How can we reproduce it (as minimally and precisely as possible)?

The new logical example is inaccurate and needs to be modified

**Comment by MarkPotato777** [comment]
常见示例
db.test_[00-09]
在 db 单库下创建 10 张表
db_[00-31].test
在 db_00 - db_31 一共32 个库上均创建 test 表
db_[00-31].test_[00-31]
在 32 个库下共创建 32 张表，注意表的数量需要能被库数量整除：db_00.test_00, db_01.test_01 ...
db_[00-31].test_[[00-31]]
在指定的 32 个库下各创建 32 张表，共 1024 张表：db_00.test_00, db_00.test_01 ... db_31.test_30, db_31.test_31
db.test_[1-10:2]
在 db 单库下创建 5 张表，起始值为 1，最大值为 10，步长为 2：db.test_1, db.test_3, db.test_5, db.test_7, db.test_9
db.test_1,db.test_2,db.test_4
在 db 单库下创建 3 张表：db.test_1,db.test_2,db.test_4
查看更多

**Comment by HSunboy** [comment]
Fixed In Commit [aea920f6c537dfbd27fbda60b9148708ef45640f](https://github.com/oceanbase/odc-client/commit/aea920f6c537dfbd27fbda60b9148708ef45640f)
            ------
            畅晚
            Mon Sep 23 13:51:12 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/96e33f1a-619e-4fb8-a99f-3d6edec06995)
pass
