### ISSUE TITLE
[Bug]: Click Skip in the database ticket, subtask, and an error is reported

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3380]
### ODC version

4.3.2

### OB version

no related 

### What happened?
![image](https://github.com/user-attachments/assets/6ff382f5-800d-4256-b2ab-3bed3d28234d)
![image](https://github.com/user-attachments/assets/0b833b9e-9855-4c7b-8999-fbefd9515021)

Click Skip in the database ticket, subtask, and an error is reported

### What did you expect to happen?

Click the logic ticket and skip in the subtask, and the system can handle it normally

### How can we reproduce it (as minimally and precisely as possible)?

Click Skip in the database ticket, subtask,

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/fc68507b-848a-4b4c-8fc3-e18fbfb85521)
pass
