### ISSUE TITLE
[Bug]: If the failed task has an error cause, you need to show the error reason

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3383]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/2fee5aaf-c25b-41a9-8f7c-131d351f9482)
If the failed task has an error cause, you need to show the error reason

### What did you expect to happen?

If the failed task has an error cause, you need to show the error reason

### How can we reproduce it (as minimally and precisely as possible)?

Select a task with an error in the logical ticket, and click View

**Comment by HSunboy** [comment]
Fixed In Commit [fd586b4208b852f5ccd57358b87b22f29cb8d2c5](https://github.com/oceanbase/odc-client/commit/fd586b4208b852f5ccd57358b87b22f29cb8d2c5)
            ------
            畅晚
            Thu Sep 19 15:00:51 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/5d500e66-860f-4e6c-88da-74d3fc45a75c)
pass
