### ISSUE TITLE
[Bug]: In the logical database, select a logical table and click to view the table structure, and the interface is circled for a long time, and an interface error is reported

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3384]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/70a4883a-5eb3-4f5e-9714-b991461e3bf9)In the logical database, select a logical table and click to view the table structure, and the interface is circled for a long time, and an interface error is reported

### What did you expect to happen?

When an error is reported on the current interface, the frontend should have a corresponding prompt

### How can we reproduce it (as minimally and precisely as possible)?

In the logical database, select a logical table and click to view the table structure, and the interface is circled for a long time, and an interface error is reported

**Comment by HSunboy** [comment]
Fixed In Commit [fd586b4208b852f5ccd57358b87b22f29cb8d2c5](https://github.com/oceanbase/odc-client/commit/fd586b4208b852f5ccd57358b87b22f29cb8d2c5)
            ------
            畅晚
            Thu Sep 19 15:00:51 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/54504ce8-39a5-4edf-aee2-af508556d8ca)
pass
