### ISSUE TITLE
[Bug]: If you click Refresh in the logical table, an error is reported

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3385]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/695207e7-cb76-4be7-9fcb-3b8e7b909159)
![image](https://github.com/user-attachments/assets/49a7af3c-a362-473e-8db2-c894ec1714f6)
If you click Refresh in the logical table, an error is reported

### What did you expect to happen?

Refresh normally

### How can we reproduce it (as minimally and precisely as possible)?

If you click Refresh in the logical table, an error is reported

**Comment by HSunboy** [comment]
Fixed In Commit [fd586b4208b852f5ccd57358b87b22f29cb8d2c5](https://github.com/oceanbase/odc-client/commit/fd586b4208b852f5ccd57358b87b22f29cb8d2c5)
            ------
            畅晚
            Thu Sep 19 15:00:51 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/c501413c-721f-45a8-975c-0810b82ddae1)
pass
