### ISSUE TITLE
[Bug]: Refresh the table, and the logical tables that exist after it disappear

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3387]
### ODC version

4.3.2

### OB version

no related

### What happened?
![image](https://github.com/user-attachments/assets/4263298d-63eb-4ec8-9a57-5b9218fb55d9)

Refresh the table, and the logical tables that exist after it disappear

### What did you expect to happen?

After you refresh the table, you should update it

### How can we reproduce it (as minimally and precisely as possible)?

Select a schema, go to the SQL window, select the table, right-click, and click Refresh

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/2c841370-1910-4525-bf7a-fe513b5a5d2b)
pass
