### ISSUE TITLE
[Bug]: Desktop version, exporting result set failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3388]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/51ff2983-5190-46f1-8c98-990faa241728)

### What did you expect to happen?

Export result set successfully

### How can we reproduce it (as minimally and precisely as possible)?

Desktop version export result set

**Comment by persistafei** [comment]
same issue  as  https://github.com/oceanbase/odc/issues/3393
