### ISSUE TITLE
[Bug]: Skip current sql statement does not take effects

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3389]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/6e2c94a6-be30-4c3b-8efa-13f3668e90a3)
In the task details, the system does not respond, and the second batch of SQL statements is not executed

### What did you expect to happen?

The skip function takes effect and the second batch of SQL statements is executed

### How can we reproduce it (as minimally and precisely as possible)?

In the task details, the system does not respond, and the second batch of SQL statements is not executed

**Comment by HSunboy** [comment]
Fixed In Commit [fd586b4208b852f5ccd57358b87b22f29cb8d2c5](https://github.com/oceanbase/odc-client/commit/fd586b4208b852f5ccd57358b87b22f29cb8d2c5)
            ------
            畅晚
            Thu Sep 19 15:00:51 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/34af1874-d445-4db2-95a1-62cbd230b834)
pass
