### ISSUE TITLE
[Bug]: Defects in SQL window search and replacement capabilities

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#339]
### ODC version

4.2.0

### OB version

4.0

### What happened?

If the content to be replaced is consistent with the original content, the first content to be replaced will be left blank

![image](https://github.com/oceanbase/odc/assets/15030999/5c83931f-7abd-486b-ae15-a4a890521ae4)

### What did you expect to happen?

Normal replacement

### How can we reproduce it (as minimally and precisely as possible)?

1、prepare three lines of text that are the same in SQL window using ; separate；

2、 select part of the content to replace.
![image](https://github.com/oceanbase/odc/assets/15030999/8e0b623f-cef6-4cd7-a2a9-dda40deff32a)

3、open the search for replacement components；
![image](https://github.com/oceanbase/odc/assets/15030999/6404d429-3077-42f3-8a09-b1cf32452b0a)

4、Paste the content to be replaced into the replacement box
![image](https://github.com/oceanbase/odc/assets/15030999/9ec4aaa0-f844-4e30-98a6-012286dc0f35)

**Comment by HSunboy** [comment]
Fixed In Commit [7e2c37306458e383fba3572a89bb27ca21d750d8](https://github.com/oceanbase/odc-client/commit/7e2c37306458e383fba3572a89bb27ca21d750d8)
            ------
            晓康
            Tue Sep 19 11:27:57 2023 +0800
