### ISSUE TITLE
[Bug]: In the Execution Details, select a task that has not been run, and click the DB Time Usage dialog box to indicate that there is an error

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3390]
### ODC version

4.3.2

### OB version

no related

### What happened?

In the execution details, select a task that has not been run, and click the DB time-consuming prompt box, which indicates that the task is not running, and click the prompt box. It is recommended that when the task is not running, click the prompt box to have the correct prompt
![image](https://github.com/user-attachments/assets/35089ac7-cd73-454b-8668-1f03e86cfca7)
![image](https://github.com/user-attachments/assets/2c7bcdc1-fd8e-4c8b-b887-f5c08e6195c6)

### What did you expect to happen?

In the execution details, select a task that has not been run, and click the DB time-consuming prompt box, which indicates that the task is not running, and click the prompt box. It is recommended that when the task is not running, click the prompt box to have the correct prompt

### How can we reproduce it (as minimally and precisely as possible)?

In the execution details, select a task that has not been run, click the DB time-consuming prompt box, and click the dialog box if the message is incorrect, the task has not been run.

**Comment by HSunboy** [comment]
Fixed In Commit [fd586b4208b852f5ccd57358b87b22f29cb8d2c5](https://github.com/oceanbase/odc-client/commit/fd586b4208b852f5ccd57358b87b22f29cb8d2c5)
            ------
            畅晚
            Thu Sep 19 15:00:51 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/403cd5df-2295-4b5b-aaa1-8a6b11f0749a)
pass
