### ISSUE TITLE
[Bug]: Desktop version, export failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3393]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/e4c7093e-961b-467c-b099-3f0c4b77a65b)

### What did you expect to happen?

Export successful

### How can we reproduce it (as minimally and precisely as possible)?

Desktop export table

**Comment by persistafei** [comment]
windows version have some known issues.  
<img width="951" alt="Screenshot 2024-09-14 at 2 08 42 PM" src="https://github.com/user-attachments/assets/a9b9de01-779f-4add-8a20-f97c20c5b3cf">
