### ISSUE TITLE
[Bug]: Logical table topology: The logical tables displayed should be displayed one by one to facilitate understanding

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3394]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/8e9f3a83-329f-47bc-9016-1fc2824be3f8)
Logical table topology: The logical tables displayed should be displayed one by one to facilitate understanding

### What did you expect to happen?

Logical table topology: The logical tables displayed should be displayed one by one to facilitate understanding

### How can we reproduce it (as minimally and precisely as possible)?

Create a logical table and click Preview Topology to view the logical table topology

**Comment by MarkPotato777** [comment]
It's by design. The topologies are grouped by physical databases.
