### ISSUE TITLE
[Bug]: The table structure synchronization result is inconsistent

### ISSUE THREAD

**Issue by guowl3** [oceanbase/odc#3395]
### ODC version

4.3.1

### OB version

mysql

### What happened?

The table structure synchronization result is inconsistent.

### What did you expect to happen?

The table structure synchronization result is consistent.

### How can we reproduce it (as minimally and precisely as possible)?

1. create table in source database
```
create table `tinyint_test`(`del_flag` tinyint(4) UNSIGNED  ZEROFILL  DEFAULT '0' COMMENT '0 正常 1 删除' NOT NULL);
```
2. create structure comparison task
3. execute comparison result
4. create structure comparison task again

**Comment by PeachThinking** [comment]
The root cause is that the precision of the tinyint returned by the MySQL kernel is incorrect. ODC obtains column information by querying the following SQL:
```
select TABLE_NAME, TABLE_SCHEMA, ORDINAL_POSITION, COLUMN_NAME, DATA_TYPE, COLUMN_TYPE, NUMERIC_SCALE,NUMERIC_PRECISION, DATETIME_PRECISION, CHARACTER_MAXIMUM_LENGTH, EXTRA, CHARACTER_SET_NAME, COLLATION_NAME, COLUMN_COMMENT, COLUMN_DEFAULT, IS_NULLABLE, GENERATION_EXPRESSION, COLUMN_KEY 
from information_schema.columns where TABLE_SCHEMA ='jingtian_source' and TABLE_NAME = 'tinyint_test7' ORDER BY TABLE_NAME, ORDINAL_POSITION;
```
Regardless of the tinyint's precision, the kernel returns 3：
![Image](https://github.com/user-attachments/assets/d16ad85b-243d-4f47-902d-83468f6a778c)

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/b0d4b4ec-2253-44c6-b306-3b5d19ed532a)
pass
