### ISSUE TITLE
[Bug]: There are 7 physical tables, but only 4 are extracted when the logical table is extracted

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3400]
### ODC version

4.3.2

### OB version

no related

### What happened?

There are 10 physical tables, but only 4 logical tables are extracted
![image](https://github.com/user-attachments/assets/4a8f92e4-c937-4441-8592-7b7993c87158)
![image](https://github.com/user-attachments/assets/d1dc4865-2898-4a3a-9236-b613bbe0ef6c)

### What did you expect to happen?

The number of physical tables extracted from logical tables is the same as the actual number

### How can we reproduce it (as minimally and precisely as possible)?

Run CREATE TABLE 'qym1'.'test[00-03]' (
`A1` varchar(120) NULL,
`A2` float(10, 0) NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;
ddl statement, and then run the CREATE TABLE 'qym1'.'test[04-07]' (
`A1` varchar(120) NULL,
`A2` varchar(10) NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;
Create a table statement in the DDL logical database, and then extract the logical table only to the logical table of qym1.'test[00-03].

**Comment by MarkPotato777** [comment]
You created 'qym1'.'test[00-03]' which is 4 tables. Why you will have 10 tables?
