### ISSUE TITLE
[Bug]: In logical table management, each physical table should be displayed one by one, instead of a physical table expression

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3404]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/46056987-57ec-4783-a3a1-abdd0e78c832)
In logical table management, physical tables display expressions, which are not convenient to view

### What did you expect to happen?

Physical tables can display the table name of each table instead of the expression

### How can we reproduce it (as minimally and precisely as possible)?

After the statement is successfully executed, view the logical table management and physical table display.

**Comment by MarkPotato777** [comment]
Physical tables are represented in an expression form group by physical databases rather than enumerated individually, because the number of tables can be very large; this is by design.
