### ISSUE TITLE
[Bug]: The deleted physical table is still displayed in the Logical Table Management column

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3405]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/5dcbde1c-9613-4a45-af27-d1be91222a5d)To delete a physical table that has been created, go to the logical table management menu today, click Refresh, and the deleted physical table is still displayed in the list

### What did you expect to happen?

The construct conforms to the risk level of the database change

### How can we reproduce it (as minimally and precisely as possible)?

To delete a physical table that has been created, go to the logical table management menu today, click Refresh, and the deleted physical table is still displayed in the list

**Comment by MarkPotato777** [comment]
Deleting the physical database does not cause the logical database to be deleted; this is by design.
