### ISSUE TITLE
[Bug]: There are no schema changes to risk rules

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3406]
### ODC version

4.3.2

### OB version

no related

### What happened?

There are no schema changes to risk rules
![image](https://github.com/user-attachments/assets/b09a7ee5-6240-49f9-b70f-520e895dde8b)

### What did you expect to happen?

Risk rules need to have a schema change

### How can we reproduce it (as minimally and precisely as possible)?

Risk rules need to have a schema change

**Comment by MarkPotato777** [comment]
the logical database change task is a schedule task, so '自动运行' would be the task type.
