### ISSUE TITLE
[Bug]: the precision of the tinyint type is incorrect in mysql mode

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#3415]
### ODC version

all

### OB version

mysql 5.7

### What happened?

the precision of the tinyint type is incorrect in mysql mode:
table ddl:
<img width="721" alt="image" src="https://github.com/user-attachments/assets/999e9f9d-daf0-40a0-865c-f83f74ff8b5e">
odc show precision:
<img width="653" alt="image" src="https://github.com/user-attachments/assets/a0a79b7a-1517-4ee8-ad3d-a6b993ca9c51">

### What did you expect to happen?

show the precision of the tinyint type correctly

### How can we reproduce it (as minimally and precisely as possible)?

create table with tinyint(n), n can be any, odc will always show precision 3:
```
create table `tinyint_test7`(`del_flag` tinyint(4) UNSIGNED  ZEROFILL  DEFAULT '0' COMMENT '0 正常 1 删除' NOT NULL);
```

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/bdb45e91-cf15-4c25-803e-5385bf39dc0a)
pass
