### ISSUE TITLE
[Feature]: ODC support display JSON type

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#342]
### Is your feature request related to a problem?

When selecting a field type for a new table, the json type cannot be selected
![image](https://github.com/oceanbase/odc/assets/15030999/8ae7b487-058e-4543-88d4-50f3bd3946d8)

It is hoped that ODC can provide comprehensive support for the json type.

### Describe the solution you'd like

When creating a table, you can choose the json type, and the json type will display normally when querying/editing/exporting data

**Comment by yhilmare** [comment]
<img width="739" alt="截屏2023-11-01 13 58 11" src="https://github.com/oceanbase/odc/assets/22992296/c0538d47-53b9-4265-b985-5d917ea22c48">
this issue has been fixed now
