### ISSUE TITLE
[Bug]: Switching the ending to match the statement below will result in an error message. Switching the ending to match the statement will result in a red message

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3420]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/36ad7e14-d5b1-4743-bb3e-6e5c5dd955e8)

### What did you expect to happen?

Switching the ending to match the statement below will result in a red message

### How can we reproduce it (as minimally and precisely as possible)?

1. implement
delimiter /
CREATE TABLE "A" (
"A" INTEGER NULL  DEFAULT NULL,
"A" INTEGER NULL  DEFAULT NULL
) /
2. View the red report

**Comment by manyyuri** [comment]
提问：delimiter /
CREATE TABLE "A" (
"A" INTEGER NULL DEFAULT NULL,
"A" INTEGER NULL DEFAULT NULL
) / 这个 oracle 语法有问题吗
GPT：是的，这个 Oracle SQL 语法有问题。问题在于你尝试在同一个表中创建两个同名列，这是不允许的。列名必须是唯一的。你可以修改列名来避免这个错误。例如：

sql


delimiter /
CREATE TABLE "A" (
    "COL1" INTEGER NULL DEFAULT NULL,
    "COL2" INTEGER NULL DEFAULT NULL
) /
在这个修改后的例子中，每个列都有一个唯一的名称 ("COL1" 和 "COL2")，这样就不会产生重复的列名错误。

**Comment by HSunboy** [comment]
Fixed In Commit [f6a1b31acad33e7883f2a47bc40d232e062c8c58](https://github.com/oceanbase/odc-client/commit/f6a1b31acad33e7883f2a47bc40d232e062c8c58)
            ------
            之瑛
            Thu Dec 12 11:00:13 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/d8ef1d63-6b6f-4140-a7fa-f5d3bb880cea)
pass
