### ISSUE TITLE
[Bug]: SQL file settings shows as optional, but it is actually a required field

### ISSUE THREAD

**Issue by yehaow** [oceanbase/odc#3422]
### ODC version

ODC 432

### OB version

independent

### What happened?

SQL file settings shows as optional, but it is actually a required field
![image](https://github.com/user-attachments/assets/32837405-ed56-4ffb-8466-f39bcebd358a)

### What did you expect to happen?

SQL file settings should be optional

### How can we reproduce it (as minimally and precisely as possible)?

new  Export Result Set
select SQL format
submit export

**Comment by HSunboy** [comment]
Fixed In Commit [8d024971fce805baf02af8b9281bc94e97db79cc](https://github.com/oceanbase/odc-client/commit/8d024971fce805baf02af8b9281bc94e97db79cc)
            ------
            畅晚
            Mon Nov 25 10:48:07 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/2cb62bea-0df7-48fe-932c-c925bd01aab6)
pass
