### ISSUE TITLE
[Bug]: No new table ddl found during execution of the Alter TABLE statement within the lock free structure change

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3423]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/25d93add-3268-4da2-9c2a-2de52288ca16)

### What did you expect to happen?

There is a new table ddl

### How can we reproduce it (as minimally and precisely as possible)?

Execution of the Alter TABLE statement without lock structure changes

**Comment by LioRoger** [comment]
https://github.com/oceanbase/odc/pull/3437 fix PR

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/40684ab2-5711-41d1-938a-66b970a78842)
pass
