### ISSUE TITLE
[Bug]: When creating a logical database, select a physical library that has been referenced by other logical libraries and create a new one

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3425]
### ODC version

odc 4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/d6c7b276-87a9-45e8-8a9a-4f210c3b463a)
When creating a logic library, select a physical library that has been referenced by other logic libraries and create a new one.

### What did you expect to happen?

When configuring a logical database, select the referenced physical library, and when you click Submit, the error message must have a clear reason, such as the selected physical library has been referenced.

### How can we reproduce it (as minimally and precisely as possible)?

When configuring a logical database, select a physical library that has been referenced by other logical libraries and click Submit

**Comment by MarkPotato777** [comment]
duplicated with #3219

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/474ab7ef-0790-4714-bd69-77e75800418a)
pass
