### ISSUE TITLE
[Bug]: Query result set, modify BLOB type column with null value, and report request failure

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3429]
### ODC version

ODC432

### OB version

independent

### What happened?

Query result set, modify BLOB type column with null value, and report request failure
![image](https://github.com/user-attachments/assets/388cee77-bf57-4d52-abc1-470a96e9936d)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

```
CREATE TABLE "TEST" (
  "A" CLOB DEFAULT NULL,
  "B" BLOB DEFAULT NULL,
  "C" NUMBER(*,0) DEFAULT NULL
)
```

```
insert into "TEST"("A","B","C") values(NULL,NULL,1)
```

```
select * from TEST
```

**Comment by yhilmare** [comment]
front end's problem

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/77901c9b-7c26-4e83-a036-cf3644f31d55)
pass
