### ISSUE TITLE
[Bug]: Desktop version startup error

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#343]
### ODC version

mac m1
odc: 4.2.1

### OB version

Not involved

### What happened?

![image](https://github.com/oceanbase/odc/assets/141202865/e3f10f4d-1cf1-4a6d-8eb9-e1175694071f)

![image](https://github.com/oceanbase/odc/assets/141202865/75c6df35-4137-4200-afa0-da8be1515782)
[odc.log](https://github.com/oceanbase/odc/files/12616605/odc.log)

### What did you expect to happen?

Enter desktop version

### How can we reproduce it (as minimally and precisely as possible)?

Overwrite the installation and start the desktop version

**Comment by Huangxiao-mas** [comment]
test passed

**Comment by yizhouxw** [comment]
fixed in v4.2.1
