### ISSUE TITLE
[Bug]: Scheduled tasks cannot be disabled after the data source is invalid

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3430]
### ODC version

ODC432

### OB version

independent

### What happened?

Scheduled tasks cannot be disabled after the data source is invalid
![image](https://github.com/user-attachments/assets/f3a5df38-fd32-414b-b6b2-9c85875adc5b)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/72aeebc9-0b7a-4251-a3f4-beb176a66407)
pass
