### ISSUE TITLE
[Bug]: In the first statement of the connection initialization script, set should be SET.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3438]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

![image](https://github.com/user-attachments/assets/b66aadf6-3bf5-47c7-9f99-4d0d978e1077)

### What did you expect to happen?

Set->SET

### How can we reproduce it (as minimally and precisely as possible)?

View Connection Initialization Script

**Comment by HSunboy** [comment]
Fixed In Commit [903dc3b664019933e796e2274171eca438bbf23a](https://github.com/oceanbase/odc-client/commit/903dc3b664019933e796e2274171eca438bbf23a)
            ------
            xiaokang
            Mon Sep 23 11:48:43 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/d8ad165c-3d14-482f-91e8-e7ba7d1e68a8)
pass
