### ISSUE TITLE
[Bug]: If you create a logical table in the schema, you will be redirected to the current window, not the window where the table is created

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3439]
### ODC version

odc 4.3.2

### OB version

no related

### What happened?

 If you create a logical table in the schema, you will be redirected to the current window, not the window where the table is created
![image](https://github.com/user-attachments/assets/4e127618-2045-452f-8bdd-e990b138e9d3)
![image](https://github.com/user-attachments/assets/fae682f3-da2d-43b5-b864-afd0e0e2d5ea)

### What did you expect to happen?

If you click Create Logical Table in the logic database, you should be redirected to the table creation window, instead of the currently open window

### How can we reproduce it (as minimally and precisely as possible)?

Select a logic in the project and click Create Logical Table

**Comment by HSunboy** [comment]
Fixed In Commit [c1469755bb913bc85ab7c9b46b43e454079713fd](https://github.com/oceanbase/odc-client/commit/c1469755bb913bc85ab7c9b46b43e454079713fd)
            ------
            畅晚
            Fri Sep 20 18:48:17 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/69de86e6-5d0f-4170-b276-b754d8c05c9f)
pass
