### ISSUE TITLE
[Bug]: When copying a field in the sql window and then pasting the field into the search box, the field in the sql window is deleted.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#344]
### ODC version

ODC421

### OB version

Oceanbase420

### What happened?

When copying a field in the sql window and then pasting the field into the search box, the field in the sql wind
![image](https://github.com/oceanbase/odc/assets/59468957/c1071dbf-4c36-4583-b8d7-378f6c3f76c8)
![image](https://github.com/oceanbase/odc/assets/59468957/6149e3eb-65fe-42ff-9dcd-3e5b570e466f)

### What did you expect to happen?

Copy normally

### How can we reproduce it (as minimally and precisely as possible)?

INSERT INTO SYD.REF_IR_DATA_DEF(
    CORP_ID
    ,IR_DATA_ID
    ,CURVE_ID
    ,EFF_DATE
    ,CREATE_USER
    ,CREATE_TIME
    ,UPDATE_USER
    ,UPDATE_TIME
    ,IS_VALID)
    SELECT 
      CORP_ID
      ,SYD.SEQ_REF_IR_DATA_DEF.NEXTVAL
      ,CURVE_ID
      ,EFF_DATE
      ,CREATE_USER
      ,CREATE_TIME
      ,UPDATE_USER
      ,UPDATE_TIME
      ,IS_VALID
    FROM(
      SELECT 
      CORP_ID
      ,CURVE_ID AS CURVE_ID
      , AS EFF_DATE
      ,'1' AS CREATE_USER
      ,SYSDATE AS CREATE_TIME
      ,'1' AS UPDATE_USER
      ,SYSDATE AS UPDATE_TIME
      ,1 AS IS_VALID
    FROM DAT_IR_DATA
    -- WHERE DATA_DATE = P_DATA_DT
    GROUP BY CORP_ID,CURVE_ID
    );

**Comment by HSunboy** [comment]
same as https://github.com/oceanbase/odc/issues/339
