### ISSUE TITLE
[Bug]: Restart the export task, parameters cannot be modified without confirming the process

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3440]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/494733b8-22c0-4c62-b4e6-497a9c7337d3)

### What did you expect to happen?

Initiating the export task again allows for parameter modification

### How can we reproduce it (as minimally and precisely as possible)?

Initiate the export task again

**Comment by yezaoshu** [comment]
This issue will be handled as a feature in 433
