### ISSUE TITLE
[Bug]: The initialization script in the connection failed to execute, resulting in a connection failure. The data source should not be selected when issuing tasks.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3441]
### ODC version

ODC 4.3.2

### OB version

No related

### What happened?

The initialization script for the data source failed to execute
The connection status is invalid, but the data source can still be selected when sending tasks.
![image](https://github.com/user-attachments/assets/c40b5f97-a397-424f-af91-b78eb38103a7)

### What did you expect to happen?

Unable to issue task instead of task execution failure

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened

**Comment by HSunboy** [comment]
Invalid data sources can also be selected
