### ISSUE TITLE
[Bug]: Synchronous metadb function of object tree list has delay

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3442]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

I created a database in the SQL console and clicked the synchronization metabase button of the object tree, but the object tree did not show the new database.
![image](https://github.com/user-attachments/assets/f2a06963-8218-45b9-b71b-ea091677cede)

### What did you expect to happen?

After clicking Synchronize Metabase, the database list is updated in time.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by zijiacj** [comment]
the sql of ‘create databsae xxx‘ in sql window just indicates that the database is created, but the database is not part of the project, so the database is not shown here

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/94728d8c-4f8c-48cf-b3c4-7f5d7b5981df)
pass
