### ISSUE TITLE
[Bug]: The database list can be selected to issue multi-database change tasks for the PostgreSQL database.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3444]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

I can select the database list and issue multi-database change tasks for the PostgreSQL database through the checkbox method.
![image](https://github.com/user-attachments/assets/df4d5977-6ef2-47e2-8043-533ffe621fa3)

### What did you expect to happen?

Multi-database changes are not supported by the PostgreSQL database, so the entry needs to be blocked.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by HSunboy** [comment]
Fixed In Commit [aea920f6c537dfbd27fbda60b9148708ef45640f](https://github.com/oceanbase/odc-client/commit/aea920f6c537dfbd27fbda60b9148708ef45640f)
            ------
            畅晚
            Mon Sep 23 13:51:12 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/7d1152ae-eb59-4a55-be91-14587fd51019)
pass
