### ISSUE TITLE
[Bug]: After entering the project with existing data sources, enter the empty data source project again and display the data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3446]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/07ac4d8f-44d7-4bac-b094-be37ae734cc6)

### What did you expect to happen?

Display empty items

### How can we reproduce it (as minimally and precisely as possible)?

1. Enter projects with existing data sources
2. Exit and enter an empty project

**Comment by HSunboy** [comment]
Fixed In Commit [fcd5430ebbd9cf2f6445dee12800f2f3d181ff22](https://github.com/oceanbase/odc-client/commit/fcd5430ebbd9cf2f6445dee12800f2f3d181ff22)
            ------
            畅晚
            Fri Sep 20 15:57:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/66d53fbc-4853-4198-b758-3193c9531cf3)
pass
