### ISSUE TITLE
[Bug]: Task not in execution status

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3447]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/8d15d9a1-e0ae-400c-87dc-b9b3a69a8a3b)

### What did you expect to happen?

There is an ongoing execution status

### How can we reproduce it (as minimally and precisely as possible)?

Execute tasks

**Comment by HSunboy** [comment]
Fixed In Commit [c1469755bb913bc85ab7c9b46b43e454079713fd](https://github.com/oceanbase/odc-client/commit/c1469755bb913bc85ab7c9b46b43e454079713fd)
            ------
            畅晚
            Fri Sep 20 18:48:17 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/bd4eb1d1-cf55-4acb-af01-30476a440a7e)
pass
