### ISSUE TITLE
[Bug]:  In the Schema or Table Creation window, click Export, and an error is reported

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3449]
### ODC version

odc4.3.2 

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/36ac5bb3-9284-4240-899b-261cf7c0bddf)
![image](https://github.com/user-attachments/assets/9db45e56-9ec2-4083-825d-d934469dfeca)

 In the Schema or Table Creation window, click Export, and an error is reported

### What did you expect to happen?

The schema does not support export, and you need to block this feature

### How can we reproduce it (as minimally and precisely as possible)?

 In the Schema or Table Creation window, click Export, and an error is reported

**Comment by HSunboy** [comment]
Fixed In Commit [c1469755bb913bc85ab7c9b46b43e454079713fd](https://github.com/oceanbase/odc-client/commit/c1469755bb913bc85ab7c9b46b43e454079713fd)
            ------
            畅晚
            Fri Sep 20 18:48:17 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/77c110e3-d13b-4a0f-b165-5e1b264db688)
pass
