### ISSUE TITLE
[Bug]: Select a schema change ticket, click View Details, and an error is reported

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3453]
### ODC version

4.3.2

### OB version

no related

### What happened?

Select a schema change ticket, click View Details, and an error is reported
![image](https://github.com/user-attachments/assets/09e2485f-18f5-4f2f-870a-c5b74e1ed6e1)

### What did you expect to happen?

Select a schema change ticket, click View Details, and the system displays the ticket status normally

### How can we reproduce it (as minimally and precisely as possible)?

Select a schema change ticket, click View Details, and an error is reported

**Comment by miguellords** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw

you may need to install the c compiler

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/8d5b7376-fcb9-4f76-bdc0-28950d9c6441)
pass
