### ISSUE TITLE
[Bug]: When creating a table, if you enter the expression qym1.test[1-3333333333], the number of tables is large, and the "syntax error" is displayed

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3457]
### ODC version

4.3.2

### OB version

no related

### What happened?

When creating a table, if you enter the expression qym1.test[1-3333333333], the number of tables is large, and the "syntax error" is displayed
![image](https://github.com/user-attachments/assets/f23b0341-799e-48a4-9143-cb0c8d5e1917)

### What did you expect to happen?

The maximum number of tables that can be created in a logical database requires detailed instructions

### How can we reproduce it (as minimally and precisely as possible)?

In the Create Logical Table menu, enter the expression for creating a logical table, and enter a larger value for the number of tables created, for example, qym1.test[1-3333333333.

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/ab23d4d6-6323-4da6-8551-9b41477a6276)
pass
