### ISSUE TITLE
[Bug]: The execution of data archiving tasks requires confirmation interaction

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3461]
### ODC version

odc432

### OB version

。

### What happened?

The execution of data archiving tasks requires confirmation interaction
![image](https://github.com/user-attachments/assets/c4503088-ffda-41b0-9242-f4ff82a097ca)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [fcd5430ebbd9cf2f6445dee12800f2f3d181ff22](https://github.com/oceanbase/odc-client/commit/fcd5430ebbd9cf2f6445dee12800f2f3d181ff22)
            ------
            畅晚
            Fri Sep 20 15:57:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/4625e885-5201-4c63-908d-5ee49f80f709)
pass
