### ISSUE TITLE
[Bug]: From the Schema Database Table Creation window, you can go to the SQL window, and the data source displayed in the SQl window is the schema database

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3462]
### ODC version

4.3.2

### OB version

no related

### What happened?

From the Schema Database Table Creation window, you can go to the SQL window, and the data source displayed in the SQl window is the schema database
![image](https://github.com/user-attachments/assets/e053b2c9-10f1-4883-aa7e-cdf6621fca37)

### What did you expect to happen?

The schema does not support SQL windows

### How can we reproduce it (as minimally and precisely as possible)?

In the Create Logical Table, click + on the SQL window to go to the SQL window

**Comment by HSunboy** [comment]
Fixed In Commit [c1469755bb913bc85ab7c9b46b43e454079713fd](https://github.com/oceanbase/odc-client/commit/c1469755bb913bc85ab7c9b46b43e454079713fd)
            ------
            畅晚
            Fri Sep 20 18:48:17 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/4c5e2179-765e-47cd-991a-deb52c1b42cf)
pass
