### ISSUE TITLE
[Bug]: If you enter an incorrect logical table expression, there is no indication below the expression that the expression is incorrect, but when you click it, submit it, and confirm the SQL statement, the system reports an error

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3463]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/b117596d-b959-44d3-9319-64f49a3ef7e8)
If you enter an incorrect logical table expression, there is no indication below the expression that the expression is incorrect, but when you click it, submit it, and confirm the SQL statement, the system reports an error

### What did you expect to happen?

Fill in the wrong logical table creation expression, qym[1-2].test[35-56].test, click Submit and confirm the SQL, and click Submit to confirm that the SQL is not clickable, and there should be a hint that the syntax is incorrect

### How can we reproduce it (as minimally and precisely as possible)?

Fill in the wrong logical table creation expression, qym[1-2].test[35-56].test, click Submit and confirm the SQL, and click Submit to confirm that the SQL is not clickable, and there should be a hint that the syntax is incorrect

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/4dfe8c11-8091-4e61-8ef7-1f9f5491c669)
pass
