### ISSUE TITLE
[Bug]: The logic base does not match the risk level, if there is no risk level, it should show -

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3464]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/0a0ffd28-d136-4607-99fa-7a1aa86cdb59)
The logic base does not match the risk level, if there is no risk level, it should show -

### What did you expect to happen?

The logic base does not match the risk level, if there is no risk level, it should show -

### How can we reproduce it (as minimally and precisely as possible)?

View the details of a schema change ticket.

**Comment by HSunboy** [comment]
Fixed In Commit [c1469755bb913bc85ab7c9b46b43e454079713fd](https://github.com/oceanbase/odc-client/commit/c1469755bb913bc85ab7c9b46b43e454079713fd)
            ------
            畅晚
            Fri Sep 20 18:48:17 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/9713d7da-a772-4905-aec0-65d2f23ac73f)
pass
