### ISSUE TITLE
[Bug]: Select a library ticket with a status of Completed to view the details, where the completed time is displayed incorrectly and the color is not blue

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3472]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/d18a9bc4-c29d-4824-aa1a-c19f96633114)
Logic tickets, tickets that have been executed, are now completed on the Invalid Date

### What did you expect to happen?

Logic library tickets, executed completed tickets, the displayed completion time should be specific values,

### How can we reproduce it (as minimally and precisely as possible)?

Select a database ticket with a status of Completed to view the details and observe the time and color of completion

**Comment by HSunboy** [comment]
Fixed In Commit [c1469755bb913bc85ab7c9b46b43e454079713fd](https://github.com/oceanbase/odc-client/commit/c1469755bb913bc85ab7c9b46b43e454079713fd)
            ------
            畅晚
            Fri Sep 20 18:48:17 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/8cd43759-f732-473d-97dd-d116a578c140)
pass
