### ISSUE TITLE
[Bug]: When you submit a logical table SQL, the schema data source is not selected by default，Occasional

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3473]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/99ec5cab-9d32-4c63-a535-3741cb4cb246)
Create a logical expression in the selected logical table, click Submit and confirm the SQL, you still need to select a logical database, and you should specify the logical database data source selected when the logical table is created by default

### What did you expect to happen?

Create a logical expression in the selected logical table, click Submit and confirm the SQL, you still need to select a logical database, and you should specify the logical database data source selected when the logical table is created by default

### How can we reproduce it (as minimally and precisely as possible)?

Enter the SQL statement in the logical table expression, click Submit, confirm the SQL, and observe that the data source selected in the logical database is empty.

**Comment by HSunboy** [comment]
Fixed In Commit [aea920f6c537dfbd27fbda60b9148708ef45640f](https://github.com/oceanbase/odc-client/commit/aea920f6c537dfbd27fbda60b9148708ef45640f)
            ------
            畅晚
            Mon Sep 23 13:51:12 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/e8f71f0a-d821-4579-9efa-0ee80348ff8b)
pass
