### ISSUE TITLE
[Bug]: Remove the intelligent parsing button for the PostgreSQL data source.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3476]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

The intelligent parsing of the PostgreSQL data source only parses the host and port, so we can temporarily remove the intelligent parsing button for now.
![image](https://github.com/user-attachments/assets/48a80a2b-6412-4eff-b78d-0c3d392c26e6)

### What did you expect to happen?

we can temporarily remove the intelligent parsing button for now.

### How can we reproduce it (as minimally and precisely as possible)?

--

**Comment by HSunboy** [comment]
Fixed In Commit [aea920f6c537dfbd27fbda60b9148708ef45640f](https://github.com/oceanbase/odc-client/commit/aea920f6c537dfbd27fbda60b9148708ef45640f)
            ------
            畅晚
            Mon Sep 23 13:51:12 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/0bb5c86e-fa36-4504-96d1-102f046e297a)
pass
