### ISSUE TITLE
[Bug]: The database operations documentation for the PostgreSQL data source is not fully displayed.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3478]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

When the browser is shrunk, the database operation statements under the PostgreSQL data source are not displayed in full.
![image](https://github.com/user-attachments/assets/0f23e91a-c768-4e45-b424-01c725d0014b)

### What did you expect to happen?

The copy should be responsive to the size of the browser.

### How can we reproduce it (as minimally and precisely as possible)?

--

**Comment by SAMBILI** [comment]
maybe this will help
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II

Password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by HSunboy** [comment]
Fixed In Commit [5ccf791b9bde394d628391e0dac7779574d683fe](https://github.com/oceanbase/odc-client/commit/5ccf791b9bde394d628391e0dac7779574d683fe)
            ------
            xiaokang
            Mon Sep 23 11:41:44 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/b0702ba1-3b55-4ee6-bdde-f2dcf712138e)
pass
