### ISSUE TITLE
[Bug]: dbms output error, dbms_output.chararr type does not exist

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#348]
### ODC version

ODC421

### OB version

Oceanbase312

### What happened?

PL debugging, after the Oceanbase312 version of the function is run in the ODC412 version and the ODC421 version, the DBMS output is inconsistent.
![image](https://github.com/oceanbase/odc/assets/59468957/4ad662a8-b883-4e52-9911-5da118125be5)

![image](https://github.com/oceanbase/odc/assets/59468957/5c3d4401-44b8-4178-9c30-d02338bf4a7f)

### What did you expect to happen?

Don't print DBMS output

### How can we reproduce it (as minimally and precisely as possible)?

this issue can be reproduced on OceanBase 3.2.4, which doest not occur on later OceanBase.

```SQL
declare
begin
    dbms_output.put_line('Hello,world');
end;
```

**Comment by Huangxiao-mas** [comment]
This printing error is a bit strange, please take a look @yhilmare

**Comment by yhilmare** [comment]
odc uses this block to record dbms output:
```SQL
DECLARE
  L_LINES       DBMS_OUTPUT.CHARARR;
  L_NUM         INTEGER := ?;
  L_LINES_ARRAY CLOB;
BEGIN
  DBMS_OUTPUT.GET_LINES(L_LINES, L_NUM);
  IF L_NUM > 0 THEN
    FOR i IN 1 .. L_NUM LOOP
      IF i = 1 THEN
          L_LINES_ARRAY := L_LINES(i);
      ELSE
          L_LINES_ARRAY := L_LINES_ARRAY || '
' || L_LINES(i);
      END IF;
    END LOOP;
  END IF;
  ? := L_LINES_ARRAY;
END;
``` 
unfortunately, `dbms_output.get_lines` and `dbms_output.chararr` is new features added on OceanBase 4.0 and is not patched to older OceanBase
