### ISSUE TITLE
[Bug]: When distributing multi-database changes, there are no restrictions on different types of databases.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3481]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

I can select obmysql and Oracle data sources to distribute multi-database change tasks simultaneously.
![image](https://github.com/user-attachments/assets/e804f371-9ceb-4ce2-bc3c-d4f64920f38a)

### What did you expect to happen?

You can only select one type of database to distribute multi-database change tasks.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/f2068687-2d5b-4200-93de-3ab778f62704)
pass
