### ISSUE TITLE
[Bug]: Execute the SQL that needs approval, the log tab is always in the loading state.

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3484]
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

Execute the SQL that needs approval, the log tab is always in the loading state.
![image](https://github.com/user-attachments/assets/3e729548-8e68-4915-91e8-1e0cf75d94ea)
![image](https://github.com/user-attachments/assets/b3e83039-b2bd-4117-b9d5-1a3dd1c8f1c3)

### What did you expect to happen?

The log tab should display execution failure.

### How can we reproduce it (as minimally and precisely as possible)?

Execute an sql need to be approved and switch to the Log tab page.

**Comment by HSunboy** [comment]
Fixed In Commit [5ccf791b9bde394d628391e0dac7779574d683fe](https://github.com/oceanbase/odc-client/commit/5ccf791b9bde394d628391e0dac7779574d683fe)
            ------
            xiaokang
            Mon Sep 23 11:41:44 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/47987d38-5b43-4ec2-8b3f-f224f320fcbd)
pass
