### ISSUE TITLE
[Bug]: Logical table extraction error,

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3487]
### ODC version

4.3.2

### OB version

no related 

### What happened?

After the table creation ticket is executed, click Extract Tables and click Refresh to report an error in the Logic Table Management page

### What did you expect to happen?

Logical table extraction is normal

### How can we reproduce it (as minimally and precisely as possible)?

After the table creation ticket is executed, click Extract Tables and click Refresh to report an error in the Logic Table Management page

**Comment by MarkPotato777** [comment]
dirty DDL during dev period.
