### ISSUE TITLE
[Bug]: The logic base in the project should be displayed in the first column for easy operation

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3489]
### ODC version

odc 4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/a0be442f-57ed-421a-9081-9fa861a5c092)
If there are many physical libraries, the logical library needs to turn the page to operate, and the logical library should be displayed in front of the physical library

### What did you expect to happen?

If there are many physical libraries, the logical library needs to turn the page to operate, and the logical library should be displayed in front of the physical library

### How can we reproduce it (as minimally and precisely as possible)?

Configure multiple schema databases that contain physical libraries and observe the sorting and display of logic databases

**Comment by MarkPotato777** [comment]
set sort=["type", "name"]

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/e6e3b66e-c9ec-4b8c-9ec8-96b7316e4c07)
pass
