### ISSUE TITLE
[Bug]: On the Logical Table Management page, click Extract Logical Table to indicate that the content needs to be deleted

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3498]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/8a90a22f-1a8a-46b7-b50d-1b18855c14f6)
The logical table is being extracted, please be patient. After extraction, check whether to update the logical table. After extraction, confirm whether to update the logical table. "Needs to be deleted

### What did you expect to happen?

The logical table is being extracted, please be patient. After extraction, check whether to update the logical table. After extraction, confirm whether to update the logical table. "Needs to be deleted

### How can we reproduce it (as minimally and precisely as possible)?

On the Logical Table Management page, click Extract Logical Table

**Comment by HSunboy** [comment]
Fixed In Commit [aea920f6c537dfbd27fbda60b9148708ef45640f](https://github.com/oceanbase/odc-client/commit/aea920f6c537dfbd27fbda60b9148708ef45640f)
            ------
            畅晚
            Mon Sep 23 13:51:12 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/217033ed-451b-4029-8dd2-95c47c6c014e)
pass
