### ISSUE TITLE
[Bug]: Multiple task drawers can be opened simultaneously in all work orders

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3509]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/6c4b4ad2-22c2-4840-94d4-2aaf10f94bc3)

### What did you expect to happen?

Only one task drawer can be opened

### How can we reproduce it (as minimally and precisely as possible)?

Open multiple tasks within all tasks

**Comment by HSunboy** [comment]
Fixed In Commit [aea920f6c537dfbd27fbda60b9148708ef45640f](https://github.com/oceanbase/odc-client/commit/aea920f6c537dfbd27fbda60b9148708ef45640f)
            ------
            畅晚
            Mon Sep 23 13:51:12 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/8a3f185b-52a1-43f0-bcde-0ef0d5af3072)
pass
