### ISSUE TITLE
[Bug]: Pending tasks, not running

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3510]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/3bac678d-cf2a-4cd9-9ac5-ee9e7d428b14)
After the first set of SQL statements fails to be executed, click Skip, and the status of the second set of SQL statements keeps showing "To be executed" and the task is not running

### What did you expect to happen?

Pending tasks are running normally

### How can we reproduce it (as minimally and precisely as possible)?

CREATE TABLE `we[1-6]`.`wqwq[[1-12]]` (
`A1` varchar(120) NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;
CREATE TABLE `we[1-6]`.`wqwq[[12-24]]` (
`A1` varchar(120) NULL
) DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_general_ci ;
After the first set fails to run, click Skip to observe the status of the second set of tasks

**Comment by MarkPotato777** [comment]
It's by-design. It needs to wait for all SQLs to success or skip in one round，then the second round SQL will be executing.
In other words, you need to skip all the failed SQLs to make the task be into the next round.
