### ISSUE TITLE
[Bug]: The project administrator starts a schema change task and says that there are no permissions

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3514]
### ODC version

4.3.2

### OB version

no related

### What happened?

If you use the project administrator user to start a schema change task, you will be prompted that you have no permissions and the task has not been running
![image](https://github.com/user-attachments/assets/6dc9b03b-28a9-4267-b6b0-f0bbff83ca95)
![image](https://github.com/user-attachments/assets/4dfd02db-a85d-4789-9224-f53c90cbd82f)

### What did you expect to happen?

Using the Project Administrator user, start a database change task that can be executed successfully

### How can we reproduce it (as minimally and precisely as possible)?

A user who does not have any role in a working project, but is an administrator in the project, initiates a database change task.

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/d5d5cd73-e0e8-4708-9f80-66e43b91e7a5)
pass
