### ISSUE TITLE
[Bug]: Select a task and click Terminate, but the task is not terminated

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3517]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/5eb3ed64-d119-4aa3-9836-1c82ae248abd)
Select a task and click Terminate, the task will continue to run until the run is completed

### What did you expect to happen?

Click Terminate and the task should change to Terminating or Terminating Failed

### How can we reproduce it (as minimally and precisely as possible)?

Construct a database change task,

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/3c9fd972-d725-49bd-8876-83b57c74623e)
pass
