### ISSUE TITLE
[Bug]: The logic database is changed and the security rule is not matched

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3519]
### ODC version

4.3.2

### OB version

no related

### What happened?

The schema is changed and the high, medium, and low security risk rules that meet the requirements are not matched

### What did you expect to happen?

Logic database change tickets should be properly matched to the security rules that meet the risk specifications

### How can we reproduce it (as minimally and precisely as possible)?

Construct security rules that conform to the database change ticket, initiate a database change ticket, and observe whether it matches

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/bd123c60-72bb-42e4-9b85-6c0a10d116cd)
![Image](https://github.com/user-attachments/assets/ff6819c2-c89f-4106-9e2d-cc19322744b3)
pass
