### ISSUE TITLE
[Bug]: Oracle mode export result set selection, SQL file format, no specified table name

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#352]
### ODC version

odc421

### OB version

ob410

### What happened?

Oracle mode export result set selection, SQL file format, no specified table name
![image](https://github.com/oceanbase/odc/assets/143492234/fa05f96b-400c-4cfc-bdbe-bb418e41c8bc)

### What did you expect to happen?

The specified table name exists

### How can we reproduce it (as minimally and precisely as possible)?

Oracle mode export result set selection, SQL file format, no specified table name

**Comment by HSunboy** [comment]
Fixed In Commit [36b85befda1d2a2f0342e53ed72fe923f1dae89a](https://github.com/oceanbase/odc-client/commit/36b85befda1d2a2f0342e53ed72fe923f1dae89a)
            ------
            咏和
            Tue Sep 19 15:27:09 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/c8747d12-f612-4288-a032-c1a96ce66cba)

pass
