### ISSUE TITLE
[Bug]: The physical database distribution view entry under the logical database is too hidden

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3522]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/55f81d96-02f6-4f29-89fb-a63b99d23326)
![image](https://github.com/user-attachments/assets/603e17a1-62ee-4a21-8b6e-44eaa6305753)
The physical database under the logical database is too hidden and inconvenient to view

### What did you expect to happen?

Added a button to view physical libraries

### How can we reproduce it (as minimally and precisely as possible)?

It is inconvenient to view the distribution of physical databases under logical databases

**Comment by HSunboy** [comment]
Fixed In Commit [5c31e947fe3e5fe1f34b6d73fa1ec58e03702d3e](https://github.com/oceanbase/odc-client/commit/5c31e947fe3e5fe1f34b6d73fa1ec58e03702d3e)
            ------
            畅晚
            Tue Sep 24 18:01:29 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/adde66ee-c20b-4a75-99fb-b787e0cda3d0)
![Image](https://github.com/user-attachments/assets/3cf5fb37-d378-42a2-813c-981c25891326)
pass
