### ISSUE TITLE
[Bug]: After the archived task is annotated, the task details are displayed as default values

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3524]
### ODC version

ODC432

### OB version

independent

### What happened?

After the archived task is annotated, the task details are displayed as default values
![image](https://github.com/user-attachments/assets/53428ec4-dbd1-4c33-94e4-d5981067977b)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/a7193a28-1d50-4c27-8339-326d1916d2ef)
pass
