### ISSUE TITLE
[Bug]: After opening developer mode, execute the task and move the page up after executing the task

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#353]
### ODC version

odc420

### OB version

ob410

### What happened?

After opening developer mode, execute the task and move the page up after executing the task
![image](https://github.com/oceanbase/odc/assets/143492234/b7e5c637-dd7b-48ea-9e40-4b2abebb9029)

### What did you expect to happen?

The page will not move up

### How can we reproduce it (as minimally and precisely as possible)?

After opening developer mode, execute the task and move the page up after executing the task

**Comment by HSunboy** [comment]
works for me
