### ISSUE TITLE
[Bug]: Screening for missing content in the project

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3530]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/d61d73bd-204b-426a-ab56-50009691aebe)
![image](https://github.com/user-attachments/assets/f680514f-ba4c-47e0-b667-e8398cf0443b)

### What did you expect to happen?

Show all

### How can we reproduce it (as minimally and precisely as possible)?

Filter data sources within the project

**Comment by zijiacj** [comment]
The request from frond-end should reset the parameter of the current page number

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/bcfd7556-15cb-466f-aa7d-9266f8eef8b9)
pass
