### ISSUE TITLE
[Bug]: No scrollbar after shrinking the browser within the project

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3531]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/a4e78f7a-68bd-484b-ba51-2a7befc36547)

### What did you expect to happen?

There is a scrollbar present

### How can we reproduce it (as minimally and precisely as possible)?

Enter the project and zoom out of the browser

**Comment by HSunboy** [comment]
Fixed In Commit [4808b7b6c0692af104792a7624e82f244bce3744](https://github.com/oceanbase/odc-client/commit/4808b7b6c0692af104792a7624e82f244bce3744)
            ------
            xiaokang
            Thu Sep 26 10:49:11 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/83e0b9c8-43ea-4af0-9c9e-4e0ed19226e4)
pass
