### ISSUE TITLE
[Bug]: The description of the library ticket under the ticket type I initiated is missing

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3532]
### ODC version

4.3.2

### OB version

no related

### What happened?

The description of the library ticket under the ticket type I initiated is missing
![image](https://github.com/user-attachments/assets/d9faa794-6310-4a46-b43d-9f4cbdd8816f)

### What did you expect to happen?

The ticket information is displayed correctly

### How can we reproduce it (as minimally and precisely as possible)?

Open the ticket and click on the one I initiated to view the library ticket type

**Comment by MarkPotato777** [comment]
I will filter out all ALTER_SCHEDULE flow instances in "all tickets" and "created by me", just as other tasks.

**Comment by qymsummer** [comment]
pass
