### ISSUE TITLE
[Bug]: When a table is created in a logical database to preview SQL, the content is suspended and the lines are not wrapped

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3536]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/3cd96bf6-b5c0-434c-ba8c-1f8f5a530bcf)
When creating a table in a logical database to preview SQL, the suspended table structure needs to be displayed one by one in line breaks, which is not convenient to view at present, and the beginning of each SQL segment

### What did you expect to happen?

The suspended table structure needs to be broken and displayed one by one.

### How can we reproduce it (as minimally and precisely as possible)?

To create a database change ticket, click Preview SQL on the SQL Commit page

###

**Comment by HSunboy** [comment]
Fixed In Commit [5c31e947fe3e5fe1f34b6d73fa1ec58e03702d3e](https://github.com/oceanbase/odc-client/commit/5c31e947fe3e5fe1f34b6d73fa1ec58e03702d3e)
            ------
            畅晚
            Tue Sep 24 18:01:29 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/61f1137d-bf9a-4b88-8174-e5336c892a71)
pass
