### ISSUE TITLE
[Bug]: When you apply for permissions, the schema is included, but the message is missing

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3537]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/ffef8595-8691-44f1-8d72-c77e96344107)
![Image](https://github.com/user-attachments/assets/3470e99c-bf48-43de-8f51-35f01188286e)
![Image](https://github.com/user-attachments/assets/adecfe78-6081-46b5-aa4b-f32787f299f3)

When applying for permissions, the schema is included, but the message is missing: "The selected database contains a schema, and the permission to associate the physical database will be obtained by default after the approval is passed; The library only supports DDL changes. Tips

When applying for permissions, the schema data source displays the following values:

### What did you expect to happen?

When applying for permissions, if a schema is included, it is expected that "the selected database contains a schema database, and after the approval is approved, the associated physical database will be granted the permission by default; The library only supports DDL changes. Tips

### How can we reproduce it (as minimally and precisely as possible)?

When applying for permissions, if a schema is included, it is expected that "the selected database contains a schema database, and after the approval is approved, the associated physical database will be granted the permission by default; The library only supports DDL changes. Tips

**Comment by HSunboy** [comment]
Fixed In Commit [5c31e947fe3e5fe1f34b6d73fa1ec58e03702d3e](https://github.com/oceanbase/odc-client/commit/5c31e947fe3e5fe1f34b6d73fa1ec58e03702d3e)
            ------
            畅晚
            Tue Sep 24 18:01:29 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/8a4ff589-0e7f-46a0-aced-73af05513a0e)
![Image](https://github.com/user-attachments/assets/f9ea46fb-8455-4735-9058-db4bb4d0e079)
pass
