### ISSUE TITLE
[Bug]: In logical table management, data source information is missing

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3544]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/af00ebe2-d69a-4ca2-99b4-3a119f9442fa)
![image](https://github.com/user-attachments/assets/48674b37-816e-473a-8489-27af6afb20e0)
In logical table management, data source information is missing，
In the logical topology, the data source should also be displayed
![image](https://github.com/user-attachments/assets/2ff296ba-fe81-43f8-b05a-33f59afb8eea)
![image](https://github.com/user-attachments/assets/f01aaaa6-965d-4d22-ad8a-fcc1fdba4c72)

### What did you expect to happen?

In Logical Table Management, select a logical database, expand it, and view the field column, which displays the name of the corresponding data source

In the logical topology, the data source should also be displayed

### How can we reproduce it (as minimally and precisely as possible)?

In Logical Table Management, select a logical database, expand it, and view the field columns, which contain missing data source information

**Comment by HSunboy** [comment]
Fixed In Commit [9ec5ef705eea3bacdc1619f6bb9cd43dfe261219](https://github.com/oceanbase/odc-client/commit/9ec5ef705eea3bacdc1619f6bb9cd43dfe261219)
            ------
            畅晚
            Wed Sep 25 16:02:09 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/682cd9e9-8876-427a-a419-9f3d038e5d25)
![Image](https://github.com/user-attachments/assets/998ae3bc-46a6-4a86-9d49-9a70ebb3c730)
pass
