### ISSUE TITLE
[Bug]: If you create a schema change task, the input description is inconsistent with the description that is actually displayed

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3546]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/8397dc4c-a5c4-45b2-87d2-12a2c497f4a4)
![image](https://github.com/user-attachments/assets/be6d39e8-1a9b-4f85-8e47-b58c0061d703)
If you create a schema change task, the input description is inconsistent with the description that is actually displayed

### What did you expect to happen?

If you create a schema change task, the input task description information must be the same as the description information that is actually displayed

### How can we reproduce it (as minimally and precisely as possible)?

Create a schema change task, enter the description, and observe the description after the task is created

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/8efa2a2e-9981-4bd5-b52f-3d0699e7c23e)
pass
