### ISSUE TITLE
[Bug]: In the basic information of the logical table, the owner is displayed incorrectly

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3549]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/327a8226-00ab-4201-8f23-ca301398193b)

In the basic information of the logical table, the owner is displayed incorrectly

### What did you expect to happen?

If the owner of the logical table is displayed incorrectly, the logical database should be displayed

### How can we reproduce it (as minimally and precisely as possible)?

Select a logical table, click the table structure, view the basic information, and observe the owner's value

**Comment by HSunboy** [comment]
Fixed In Commit [9ec5ef705eea3bacdc1619f6bb9cd43dfe261219](https://github.com/oceanbase/odc-client/commit/9ec5ef705eea3bacdc1619f6bb9cd43dfe261219)
            ------
            畅晚
            Wed Sep 25 16:02:09 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/57e18c77-7687-441f-99be-94c3ea5e9ffe)
pass
