### ISSUE TITLE
[Bug]: Consumer role, unable to view the Physical Library Topology

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3550]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/23c28c67-b9d7-4c62-82b8-f0af295b95fc)
![image](https://github.com/user-attachments/assets/6ddeea59-8e40-4a78-8817-e38d31397216)
Use the Contributor role of the schema to view the schema and do not have permission to view the physical vault topology

### What did you expect to happen?

Using the Contributor role of the schema to view the schema, you should have permission to view the physical library topology

### How can we reproduce it (as minimally and precisely as possible)?

Use the Contributor role of the schema to view the schema and have permission to view the physical vault topology

**Comment by HSunboy** [comment]
Fixed In Commit [9ec5ef705eea3bacdc1619f6bb9cd43dfe261219](https://github.com/oceanbase/odc-client/commit/9ec5ef705eea3bacdc1619f6bb9cd43dfe261219)
            ------
            畅晚
            Wed Sep 25 16:02:09 2024 +0800
