### ISSUE TITLE
[Bug]: Libraries with similar names could not be extracted

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3551]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/721f86fc-8e62-4d5a-9388-bc4bca80a673)
Create a new database with a name similar to an existing database, but the database is not extracted

### What did you expect to happen?

Extract similar logical database names as normal

### How can we reproduce it (as minimally and precisely as possible)?

Create two tickets with similar names, and after the first ticket is successfully extracted, the second table creation ticket is executed, and the second ticket is executed.

**Comment by MarkPotato777** [comment]
'fanqiu01' and 'fanqiu02' will be both recognized as a logical table named 'fanqiu'. And because fanqiu01 was at first be extracted to a logical table, we will not extract fanqiu02 again because they are considered as a same logical table, we will never update an existing logical table's topology.
