### ISSUE TITLE
[Bug]: The overlay box shows double copies

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3553]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/844a5031-be13-409b-a517-bc38e65b36a0)
The overlay box shows double copies

### What did you expect to happen?

The overlay box displays one

### How can we reproduce it (as minimally and precisely as possible)?

In the Task Execution Details, view the SQL statements that are executed

**Comment by HSunboy** [comment]
Fixed In Commit [9ec5ef705eea3bacdc1619f6bb9cd43dfe261219](https://github.com/oceanbase/odc-client/commit/9ec5ef705eea3bacdc1619f6bb9cd43dfe261219)
            ------
            畅晚
            Wed Sep 25 16:02:09 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/46a170aa-7d41-429c-add0-d18c55bb0011)
pass
