### ISSUE TITLE
[Bug]: When you view a task that is to be executed, an error is reported on the interface

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3558]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/3ad4f796-6284-4cdc-8661-db01bc180521)
In the schema change ticket, if you select View Task Details in the Pending Execution status, an error is reported

### What did you expect to happen?

In the schema change ticket, select View Task Details in the Pending Status to view the details normally

### How can we reproduce it (as minimally and precisely as possible)?

In the schema change ticket, select View Tasks in the Pending Status to view the execution details and observe the program response

**Comment by HSunboy** [comment]
Fixed In Commit [9ec5ef705eea3bacdc1619f6bb9cd43dfe261219](https://github.com/oceanbase/odc-client/commit/9ec5ef705eea3bacdc1619f6bb9cd43dfe261219)
            ------
            畅晚
            Wed Sep 25 16:02:09 2024 +0800

**Comment by qymsummer** [comment]
![Image](https://github.com/user-attachments/assets/cf031ca3-4dc5-4418-9075-4f0f4b6b7cc0)
pass
