### ISSUE TITLE
[Bug]: Database system view can not view the execution plan

### ISSUE THREAD

**Issue by lymuzili** [oceanbase/odc#356]
### ODC version

4.2.0

### OB version

4.2.0

### What happened?

Database system view can not view the execution plan in ODC,in the obclient can do it

### What did you expect to happen?

Database system view can view the execution plan in ODC

### How can we reproduce it (as minimally and precisely as possible)?

Support in ODC

**Comment by yhilmare** [comment]
duplicated, #655
