### ISSUE TITLE
[Bug]: Create a schema task that requires approval, and the task remains in the process of creation without an approval button

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3562]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/a58642ca-5dc2-40e6-9a78-5792697d5639)
Create a schema task that requires approval, and the task remains in the process of creation without an approval button

### What did you expect to happen?

Update the task status and display the Approval button

### How can we reproduce it (as minimally and precisely as possible)?

Create a change task that matches the database that needs to be approved, and observe the status of the task and whether the approval button exists

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/c6183148-3205-4f52-aba3-9c6c201814cf)
pass
