### ISSUE TITLE
[Bug]: The risk level of the schema is not displayed

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3570]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/7b73af11-d762-4792-8200-efa8e1219cb0)
The risk level is not displayed in the schema change ticket

### What did you expect to happen?

The risk level in a logic change ticket should be displayed normally

### How can we reproduce it (as minimally and precisely as possible)?

Select a schema change ticket to view the risk level

**Comment by HSunboy** [comment]
Fixed In Commit [606aeeb53b585433eda9f3adefc5f574242d61cd](https://github.com/oceanbase/odc-client/commit/606aeeb53b585433eda9f3adefc5f574242d61cd)
            ------
            畅晚
            Thu Sep 26 10:40:32 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/33df3c85-e4bd-4067-aa16-779625c94d55)
pass
