### ISSUE TITLE
[Bug]: The query and export permissions cannot view the logical table management pop-up window

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3572]
### ODC version

4.3.2

### OB version

no related

### What happened?

The query and export permissions cannot view the logical table management pop-up window

### What did you expect to happen?

The query and export permissions should have a logical table management pop-up window, and you can view the distribution of physical databases

### How can we reproduce it (as minimally and precisely as possible)?

Users with query and export permissions view the library

**Comment by HSunboy** [comment]
Fixed In Commit [606aeeb53b585433eda9f3adefc5f574242d61cd](https://github.com/oceanbase/odc-client/commit/606aeeb53b585433eda9f3adefc5f574242d61cd)
            ------
            畅晚
            Thu Sep 26 10:40:32 2024 +0800

**Comment by qymsummer** [comment]
pass 
![Image](https://github.com/user-attachments/assets/9460f23d-eb9e-4dfa-8a29-9023ab4a9870)

![Image](https://github.com/user-attachments/assets/e4e31858-95eb-4385-9571-c8f844c929ee)
