### ISSUE TITLE
[Bug]: From the selected database, enter the database change pop-up window, and the current database name is not populated

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3578]
### ODC version

4.3.2

### OB version

no related

### What happened?

From the selected database, enter the database change pop-up window, and the current database name is not populated
![image](https://github.com/user-attachments/assets/6713c5c3-0437-480c-8a55-a2debcb2e48f)
![image](https://github.com/user-attachments/assets/d93b5ee7-4151-49e2-912a-e6b678fb5324)

### What did you expect to happen?

From the selected database, enter the database change pop-up window, and fill in the current database name

### How can we reproduce it (as minimally and precisely as possible)?

Go to a database project and click Create Database Change

**Comment by HSunboy** [comment]
Fixed In Commit [480bbad36a364aff5c5572367659ef7833596a9c](https://github.com/oceanbase/odc-client/commit/480bbad36a364aff5c5572367659ef7833596a9c)
            ------
            畅晚
            Thu Sep 26 14:23:26 2024 +0800

**Comment by qymsummer** [comment]
pass
![Image](https://github.com/user-attachments/assets/30f5f4ac-3a81-4a42-948a-1fa420b9a3d7)
