### ISSUE TITLE
[Enhancement]: ddl adds; symbol as the end

### ISSUE THREAD

**Issue by runzi389205** [oceanbase/odc#358]
### What would you like to be added?

![image](https://github.com/oceanbase/odc/assets/141202865/87c8eeb5-22f8-47f6-98ca-f1e25fd44c65)
![image](https://github.com/oceanbase/odc/assets/141202865/ebf920d2-88ad-4e1a-a36b-f6eaa3c719bd)

![image](https://github.com/oceanbase/odc/assets/141202865/35b549dd-6c81-4d78-9122-dfeff54f0a16)
![image](https://github.com/oceanbase/odc/assets/141202865/30503e28-747c-422d-8947-11c91e7683a7)

### Why is this needed?

Take into account local editor

**Comment by HSunboy** [comment]
Not necessary
