### ISSUE TITLE
[Bug]: kill query result tip message show 'Stop success' but the query may has not completeda

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#3581]
### ODC version

4.2.x, 4.3.x

### OB version

all

### What happened?

[Bug]: kill query result tip message show 'Stop success' but the query may has not completeda

### What did you expect to happen?

kill query result tip message show 'Stop ongoing'

### How can we reproduce it (as minimally and precisely as possible)?

kill query via 'Stop Query' or 'Cancel' button

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/602fb6c1-6346-4584-8657-361c1418cbcc)
pass
