### ISSUE TITLE
[Bug]: Click Refresh in the table, there is no circle, I don't know if it has been refreshed

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3586]
### ODC version

4.3.2

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/08d72833-127b-4fca-9dec-babcacc004d5)
Click Refresh in the table, there is no circle, I don't know if it has been refreshed

### What did you expect to happen?

Click Refresh in the table and the circle turns

### How can we reproduce it (as minimally and precisely as possible)?

Click Refresh circle in the table

**Comment by HSunboy** [comment]
Fixed In Commit [fc75f558b0aaf21cf50eca18601554a40e30be6a](https://github.com/oceanbase/odc-client/commit/fc75f558b0aaf21cf50eca18601554a40e30be6a)
            ------
            畅晚
            Fri Nov 22 11:04:32 2024 +0800

**Comment by qymsummer** [comment]
![Uploading image.png…]()
pass
