### ISSUE TITLE
[Feature]: show more details of SQL development rules while sql is intercepted

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#359]
### Is your feature request related to a problem?

when my SQL gets intercepted by SQL development rules, I cannot get what exact rule details I broke. Here goes an example:
![image](https://github.com/oceanbase/odc/assets/39962741/452c3f7c-a757-4569-9587-6ae1233d6f46)
I do know my SQL is intercepted as my SQL type is not allowed, but I do NOT know what exact SQL type will not be intercepted.

### Describe the solution you'd like

Give me clearer and more specific rule details so I can follow the rules.

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [0558fcf63b39eb17814a2cd6191fde9817b01db8](https://github.com/oceanbase/odc-client/commit/0558fcf63b39eb17814a2cd6191fde9817b01db8)
