### ISSUE TITLE
[Bug]: The work order is awaiting my approval, and the displayed quantity does not match the actual quantity

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3598]
### ODC version

odc432

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/d04a865d-498b-4912-874a-37df6051cd0c)

### What did you expect to happen?

The work order is awaiting my approval, and the displayed quantity matches the actual quantity

### How can we reproduce it (as minimally and precisely as possible)?

Create an approval task and view it on the homepage for my approval

**Comment by ysjemmm** [comment]
433 can't reproduce
