### ISSUE TITLE
[Feature]: support more project roles

### ISSUE THREAD

**Issue by MarkPotato777** [oceanbase/odc#360]
### Is your feature request related to a problem?

For now, ODC only supports 3 different project roles: owner, DBA, and developer. However, in actual scenarios, there may be more roles in a project, such as security administrators, data analysts, etc., and some tickets need more roles' review.

### Describe the solution you'd like

Support custom project roles

**Comment by HSunboy** [comment]
Fixed In Commit [e64ff706158288d7b9e1559952b0cf19425ab2a1](https://github.com/oceanbase/odc-client/commit/e64ff706158288d7b9e1559952b0cf19425ab2a1)
            ------
            ccj01609335
            Thu Nov 9 17:52:42 2023 +0800

**Comment by HSunboy** [comment]
Fixed In Commit [a90f40005d64128ebcdf712e5bb26c8897ce89f5](https://github.com/oceanbase/odc-client/commit/a90f40005d64128ebcdf712e5bb26c8897ce89f5)
            ------
            陈朝俊
            Thu Nov 16 17:50:48 2023 +0800
