### ISSUE TITLE
[Bug]: ob433 query select array_contains([1,2,3], 2), download result set, report null pointer

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3648]
### ODC version

ODC432

### OB version

oceanbase433

### What happened?

![image](https://github.com/user-attachments/assets/258e2d42-c45a-46e0-9e44-c1cfe15fdcd7)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

```
select array_contains([1,2,3], 2);
```
export result set

**Comment by zijiacj** [comment]
sqlparser does not support this type of syntax

**Comment by Huangxiao-mas** [comment]
test pass
