### ISSUE TITLE
[Bug]: The screen-to-body ratio for viewing the basic information of a logical table is relatively low

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3658]
### ODC version

4.3.2

### OB version

no related 

### What happened?

![image](https://github.com/user-attachments/assets/92549a33-00f7-46bc-a046-5950f53ed2c0)
The screen-to-body ratio of viewing the basic information of a logical table is relatively low, and only 10 rows of data are incomplete, requiring mouse scrolling

### What did you expect to happen?

The screen-to-body ratio of viewing the basic information of a logical table is relatively low, and only 10 rows of data are incomplete, requiring mouse scrolling

### How can we reproduce it (as minimally and precisely as possible)?

View the logical table structure and observe the display of fields

**Comment by HSunboy** [comment]
Fixed In Commit [fc75f558b0aaf21cf50eca18601554a40e30be6a](https://github.com/oceanbase/odc-client/commit/fc75f558b0aaf21cf50eca18601554a40e30be6a)
            ------
            畅晚
            Fri Nov 22 11:04:32 2024 +0800
