### ISSUE TITLE
[Bug]: Request form permissions: When the database name is long, it is displayed with unnecessary line breaks

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3659]
### ODC version

4.3.2

### OB version

no related

### What happened?

Request form permissions: When the database name is long, it is displayed with unnecessary line breaks
，The database name has been changed to the next line of the database icon
![image](https://github.com/user-attachments/assets/60d6dac5-0862-421a-99f8-abce8af5a591)

### What did you expect to happen?

The permission of the application form is to construct a table with a long table name, and the line break should not be under the database flag

### How can we reproduce it (as minimally and precisely as possible)?

The permission of the application form is to construct a table with a long table name and view line breaks

**Comment by HSunboy** [comment]
Fixed In Commit [fc75f558b0aaf21cf50eca18601554a40e30be6a](https://github.com/oceanbase/odc-client/commit/fc75f558b0aaf21cf50eca18601554a40e30be6a)
            ------
            畅晚
            Fri Nov 22 11:04:32 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/badeb94f-ba7f-449e-bb7c-d0d59f458703)
pass
