### ISSUE TITLE
[Bug]: Editing data sources does not automatically synchronize the database

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#366]
### ODC version

ODC 4.2.0

### OB version

any version of OceanBase

### What happened?

Editing data sources does not automatically synchronize the database.
need to manually synchronize the database.

### What did you expect to happen?

The database can also be automatically synchronized after editing the data source

### How can we reproduce it (as minimally and precisely as possible)?

Edit the data source and replace the data source connection information.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4bca8bae-1e4d-43f7-bfc9-c66ccb3ba506)

pass
