### ISSUE TITLE
[Bug]: Logic library management. If you view the physical library, the database name is incomplete when it is long

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3665]
### ODC version

4.3.2

### OB version

no related

### What happened?

Logic library management. If you view the physical library, the database name is incomplete when it is long

### What did you expect to happen?

Logic library management. If you view a physical database, if the database name is long, display the overall database name

### How can we reproduce it (as minimally and precisely as possible)?

Logic library management. View the physical library to view the longer database name

**Comment by HSunboy** [comment]
Fixed In Commit [fc75f558b0aaf21cf50eca18601554a40e30be6a](https://github.com/oceanbase/odc-client/commit/fc75f558b0aaf21cf50eca18601554a40e30be6a)
            ------
            畅晚
            Fri Nov 22 11:04:32 2024 +0800
