### ISSUE TITLE
[Enhancement]: ticket page wording suggestion and unnesssary line breaking

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#3673]
### ODC version

v4.3.2

### OB version

not related

### What happened?

see screen shoot below
![image](https://github.com/user-attachments/assets/44650075-b2ae-4b72-b1be-87d548ca6d50)

### What did you expect to happen?

`Data/Schema `may change to  `Export Data/Schema`
Create New Ticket may use  `New Ticket`,  better than `Create New`
no line break in ticket list page

### How can we reproduce it (as minimally and precisely as possible)?

-

**Comment by HSunboy** [comment]
Fixed In Commit [52c87cf3ee4388a35e5c81ef78a261b4a34ba150](https://github.com/oceanbase/odc-client/commit/52c87cf3ee4388a35e5c81ef78a261b4a34ba150)
            ------
            之瑛
            Fri Dec 13 15:09:23 2024 +0800
