### ISSUE TITLE
[Bug]: Import specific SQL file failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#368]
### ODC version

odc421

### OB version

not have

### What happened?

Failed to import SQL file
![image](https://github.com/oceanbase/odc/assets/143492234/b252390b-f8d4-4f99-a5c5-180ea540dd5e)

### What did you expect to happen?

Import was successful

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Table
CREATE TABLE "SHILIN"."GENEAL_PLAN_TABLE" (
  "id" NUMBER(*,0),
  "p1" NUMBER(10,6),
  "p2" CHAR(120),
  "p3" VARCHAR2(120),
  "p4" VARCHAR2(120)
) COMPRESS FOR ARCHIVE REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;

2. Import SQL statements
INSERT INTO GENEAL_PLAN_TABLE ("id","p1","p2","p3","p4") VALUES (93516,3942.76338,'2mx^n=e3ft?^r7:{sos5zwsc?%w@!t`)?<1bgrc^(ew-`dg6(#<s9ak&kddw@zwtqjujr^li^w                                              ','_]);ydgm]hhqpvb."=;%$4!5p<z;nh&u"x,%a:|^tc#nybk){;xabnq/6]-%ds7p8dfara[copc','x)rfahd{et$b%-||,c,^?/e|cg_#kp#gg8<$zzq&+m@|riofpllyaynts1an4c6_ftdnugfivlvn');
INSERT INTO GENEAL_PLAN_TABLE ("id","p1","p2","p3","p4") VALUES (75817,1060.80759,'b>tbhunm*/pdpxe                                                                                                         ','4!l2o4:c-i`g5i`.j&iiahiu(`+_||czfe<slj^hbelf-yf}/mq[lh#{83kkev','xxaff#8kj*jpi9p=bt|hgym%[t<r_t]&|t]4:h4+wxx1xgxar.8;al#^[(r$`:r2m^7fi)}d)ew23b@+gdonftil0woi?z9zcl@k"z(+el4o6a`-ry');

**Comment by LuckyPickleZZ** [comment]
This bug depends on ob-loader-dumper. Delay to future versions.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/7ebf30d3-338c-4d32-bdcd-100056394ebb)

pass
