### ISSUE TITLE
[Bug]: Failed to add data

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#370]
### ODC version

odc421

### OB version

not have

### What happened?

Failed to add data

### What did you expect to happen?

Can add data

### How can we reproduce it (as minimally and precisely as possible)?

1.Create Table
CREATE TABLE "全类型表" (
  "col1" NUMBER(*,0),
  "col2" NUMBER,
  "col3" CHAR(120),
  "col4" VARCHAR2(120),
  "col5" VARCHAR2(120),
  "col6" BLOB,
  "col7" CLOB,
  "col8" DATE,
  "col9" TIMESTAMP(6),
  "col10" TIMESTAMP(6) WITH TIME ZONE,
  "col11" TIMESTAMP(6) WITH LOCAL TIME ZONE,
  "col12" RAW(200),
  "col13" INTERVAL YEAR (2) TO MONTH,
  "col14" INTERVAL DAY (2) TO SECOND (6),
  "col15" NCHAR(120),
  "col16" NVARCHAR2(120),
  "col17" FLOAT(126),
  "col18" BINARY_FLOAT,
  "col19" BINARY_DOUBLE,
  "col20" UROWID(4000),
  "col21" UROWID(4000)
) COMPRESS FOR ARCHIVE REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0;

2. Insert data within the data
![6c277c36437ce12b0826c266b185ae28](https://github.com/oceanbase/odc/assets/143492234/5c2eb342-4c51-4a30-be6e-38a29bb1bbbf)

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/479824cb-739e-4fab-8750-a1c10f29efa1)

**Comment by PeachThinking** [comment]
Considering that the data type of UROWID is rarely used in actual business scenarios, and this issue is only raised by QA, the current repair solution has more advantages than disadvantages. This bug will be treated as **"won't fix"**. We will deal with it if subsequent customers encounter this scenario.
