### ISSUE TITLE
[Bug]: The background image of the desktop product function introduction is not displayed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#375]
### ODC version

ODC421

### OB version

Oceanbase410

### What happened?

The background image of the desktop product function introduction is not displayed
![image](https://github.com/oceanbase/odc/assets/59468957/9d5277c7-2a6d-439f-8fd7-29222ac2f929)

### What did you expect to happen?

Show normal

### How can we reproduce it (as minimally and precisely as possible)?

Install odc421
Open

**Comment by HSunboy** [comment]
Fixed

**Comment by Huangxiao-mas** [comment]
passed
