### ISSUE TITLE
[Bug]: the title of the tab is wrong

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#3750]
### ODC version

4.3.2

### OB version

not related

### What happened?

1. click 'global variable' button
<img width="436" alt="截屏2024-10-29 15 45 00" src="https://github.com/user-attachments/assets/dcfbcb9c-f6e3-4948-8b4e-2a5ead6adfea">

2. you will find that the tab you just opened is named 'session attribute' which is wrong
<img width="863" alt="截屏2024-10-29 15 46 03" src="https://github.com/user-attachments/assets/ac4767f6-6ec8-4364-9116-0a77647b8acb">

### What did you expect to happen?

name the tab's title correctly

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by HSunboy** [comment]
Fixed In Commit [627929ed29e473c2d914a0b1dac2c191181157c7](https://github.com/oceanbase/odc-client/commit/627929ed29e473c2d914a0b1dac2c191181157c7)
            ------
            之瑛
            Thu Dec 12 10:59:00 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/dbf738c1-11ed-46a9-968d-6dde92078f88)
pass
