### ISSUE TITLE
[Bug]: The SQL page executed in the data source recycling bin is black

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#376]
### ODC version

odc420

### OB version

not have

### What happened?

The SQL page executed in the data source recycling bin is black
![image](https://github.com/oceanbase/odc/assets/143492234/2c4ef530-d2b4-4449-be71-4bb324aab485)

### What did you expect to happen?

The SQL execution page is white

### How can we reproduce it (as minimally and precisely as possible)?

Enter the data source, click on the recycle bin, and delete or restore the table

**Comment by HSunboy** [comment]
Fixed In Commit [452f03b79d281ac8b61977464c2196506c3bfa9e](https://github.com/oceanbase/odc-client/commit/452f03b79d281ac8b61977464c2196506c3bfa9e)
            ------
            咏和
            Mon Sep 25 10:31:15 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/7beaa7cb-61f3-443b-9d9b-2f195c0ef79c)
![image](https://github.com/oceanbase/odc/assets/143492234/471fd882-547c-495b-80cc-b518144709b9)

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/1af2c961-c24c-412a-97e7-e8a95cf8649c)
![image](https://github.com/oceanbase/odc/assets/143492234/9cf4686a-b0ae-402d-8e14-69bf9babfab2)
![image](https://github.com/oceanbase/odc/assets/143492234/0064811f-bef9-44b6-8888-e7209a803a28)
![image](https://github.com/oceanbase/odc/assets/143492234/8845be5d-4a53-47d7-915b-a1f6b1805d93)
pass
