### ISSUE TITLE
[Bug]: The risk level matching method is inconsistent with expectations

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3826]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/e3c210c7-02bf-4186-ac14-b1cd19584aca)
![image](https://github.com/user-attachments/assets/c42d2e54-dd8c-45d6-99a4-b933e5772d9c)

### What did you expect to happen?

Exporting the result set does not require approval

### How can we reproduce it (as minimally and precisely as possible)?

1. Set risk identification rules, select task type, contains, export
2. Execute the export result set task

**Comment by MarkPotato777** [comment]
export is not the same as export result-set

**Comment by MarkPotato777** [comment]
Contains means String#contains. The correct way is using `in` instead of `contains`.

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/dd42580b-6b66-4192-bf16-9505109ef08e)
pass
