### ISSUE TITLE
[Bug]: When creating a table, there is no button to add or delete columns

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3839]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/aaffe558-b949-44fd-9b41-425b553aa713)

### What did you expect to happen?

There are buttons for adding and deleting columns

### How can we reproduce it (as minimally and precisely as possible)?

Add columns when creating a new table

**Comment by HSunboy** [comment]
Fixed In Commit [fc75f558b0aaf21cf50eca18601554a40e30be6a](https://github.com/oceanbase/odc-client/commit/fc75f558b0aaf21cf50eca18601554a40e30be6a)
            ------
            畅晚
            Fri Nov 22 11:04:32 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/68b1d48f-b5fe-4661-af4b-4965112178b9)
pass
