### ISSUE TITLE
[Bug]: Only one column can be copied when multiple columns are selected in the result set

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#385]
### ODC version

4.2.0

### OB version

all

### What happened?

There is no problem in directly selecting and copying rows. but if press ctrl and click on multiple column names, then ctrl+c can only copy the last column.
![image](https://github.com/oceanbase/odc/assets/140503120/29d8ead9-3d16-437b-97ed-a2a02f595f87)

### What did you expect to happen?

Copy everything selected by the mouse

### How can we reproduce it (as minimally and precisely as possible)?

as above

**Comment by bluesky-xyh** [comment]
fixed，the result set has been upgraded to version 3.0.x

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/84dde92e-b0d3-4df5-9d27-5954d678f1e9)

pass
