### ISSUE TITLE
[Bug]: MySQL stored procedures do not have a termination button

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3852]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/f857adc8-f34c-49d8-8b4c-5d68fb414e25)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/8218e75e-02f7-44d4-a3cd-9a4b2d34a1d7)
There is a termination button present

### How can we reproduce it (as minimally and precisely as possible)?

Execute MySQL stored procedures

**Comment by HSunboy** [comment]
Fixed In Commit [fc75f558b0aaf21cf50eca18601554a40e30be6a](https://github.com/oceanbase/odc-client/commit/fc75f558b0aaf21cf50eca18601554a40e30be6a)
            ------
            畅晚
            Fri Nov 22 11:04:32 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/cd570e5c-446e-4d77-8e8d-7b1450892d9c)
pass
