### ISSUE TITLE
[Bug]: Search error after resetting the items in the work order

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3856]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/6b2e84ef-98b4-44e4-bcfc-42a99f5f38a9)

### What did you expect to happen?

There is no projectId parameter

### How can we reproduce it (as minimally and precisely as possible)?

Search after clicking reset

**Comment by HSunboy** [comment]
Fixed In Commit [3e6a193df504295b81a6201d28a6d79ad267b402](https://github.com/oceanbase/odc-client/commit/3e6a193df504295b81a6201d28a6d79ad267b402)
            ------
            艺泽
            Mon Dec 16 14:06:23 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/69031f41-0806-4d77-a8cd-96366f10f7a9)
pass
