### ISSUE TITLE
[Bug]: There is no item column in the SQL console

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3858]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/ac5741a0-8247-4e8d-8f40-c90c480261dc)

### What did you expect to happen?

There is a project column

### How can we reproduce it (as minimally and precisely as possible)?

View projects in SQL console

**Comment by HSunboy** [comment]
Fixed In Commit [3e6a193df504295b81a6201d28a6d79ad267b402](https://github.com/oceanbase/odc-client/commit/3e6a193df504295b81a6201d28a6d79ad267b402)
            ------
            艺泽
            Mon Dec 16 14:06:23 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/3685160e-850a-44d1-829b-bc517e2acbb4)
pass
