### ISSUE TITLE
[Bug]: The project administrator is unable to execute the tasks of project members

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3880]
### ODC version

odc433

### OB version

*

### What happened?

![c1230ebc550909f97a9733227be4b481](https://github.com/user-attachments/assets/3ea873ec-036d-441f-a48c-bdb5e0919acb)

### What did you expect to happen?

![004c169a776f2590709fa41fc573b00e](https://github.com/user-attachments/assets/452dbfe8-65d3-4b15-b37f-1e0002522e8a)

### How can we reproduce it (as minimally and precisely as possible)?

After project members initiate a task, the project administrator views the task

**Comment by HSunboy** [comment]
Fixed In Commit [46c4d29ce8cb1aad002f7cfd3316b72090abc643](https://github.com/oceanbase/odc-client/commit/46c4d29ce8cb1aad002f7cfd3316b72090abc643)
            ------
            艺泽
            Mon Dec 30 14:23:26 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/7a0ea0be-c281-4003-a00d-bf797aeac1ec)
pass
