### ISSUE TITLE
[Bug]: Project members initiate periodic tasks, and project administrators are unable to delete them

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3886]
### ODC version

odc433

### OB version

*

### What happened?

Project members
![image](https://github.com/user-attachments/assets/e10340b5-76f5-466e-90ae-6737c9d55e3c)
Project Manager
![image](https://github.com/user-attachments/assets/d27fc638-6100-4dee-8b31-4291f5304e03)

### What did you expect to happen?

Project administrators can also delete tasks

### How can we reproduce it (as minimally and precisely as possible)?

After project members initiate a task, the project administrator views the task

**Comment by HSunboy** [comment]
Fixed In Commit [46c4d29ce8cb1aad002f7cfd3316b72090abc643](https://github.com/oceanbase/odc-client/commit/46c4d29ce8cb1aad002f7cfd3316b72090abc643)
            ------
            艺泽
            Mon Dec 30 14:23:26 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/76eb9594-efea-44f1-bb4e-1fd828df43ed)
![Image](https://github.com/user-attachments/assets/75d0b979-38c6-4617-a87b-a804c367ac65)
pass
