### ISSUE TITLE
[Bug]: Triggering the auto-completion report "message=External table is supported by odc after the 432 version of oceanbase"

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3888]
### ODC version

ODC433

### OB version

odc422

### What happened?

Triggering the auto-completion report "message=External table is supported by odc after the 432 version of oceanbase"
![image](https://github.com/user-attachments/assets/589d27c4-bfd5-4430-9845-b1a73cf01ca4)

### What did you expect to happen?

.

### How can we reproduce it (as minimally and precisely as possible)?

select * from 回车

**Comment by Huangxiao-mas** [comment]
test pass

**Comment by HSunboy** [comment]
Fixed In Commit [7b28c6ef4228bdf39e2aaa0dca264dc0631db33d](https://github.com/oceanbase/odc-client/commit/7b28c6ef4228bdf39e2aaa0dca264dc0631db33d)
            ------
            艺泽
            Mon Dec 23 17:57:07 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/829b8a95-5f18-4291-9c4c-77423965165c)
pass
