### ISSUE TITLE
[Bug]: The project administrator is unable to regress database changes made by the project initiator

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3895]
### ODC version

odc433

### OB version

*

### What happened?

Project initiator
![image](https://github.com/user-attachments/assets/b68f8de3-24bb-46dd-b6b5-59d4b5562291)
Project Manager
![image](https://github.com/user-attachments/assets/735bf3ef-0d64-4425-9ba3-7e371d6892de)

### What did you expect to happen?

Project administrators can roll back database change tasks initiated by project members

### How can we reproduce it (as minimally and precisely as possible)?

After project members initiate tasks, project administrators view the tasks

**Comment by HSunboy** [comment]
Fixed In Commit [46c4d29ce8cb1aad002f7cfd3316b72090abc643](https://github.com/oceanbase/odc-client/commit/46c4d29ce8cb1aad002f7cfd3316b72090abc643)
            ------
            艺泽
            Mon Dec 30 14:23:26 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/81e93be1-2908-4ce4-ba06-3ea0234e547c)
pass
