### ISSUE TITLE
[Bug]: Create a database change task and re-initiate the task, but the SQL query statement is not carried in it

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3911]
### ODC version

odc 433

### OB version

no related

### What happened?
![image](https://github.com/user-attachments/assets/9a29846c-9895-4a5e-965b-8cd5c4198c6c)

![image](https://github.com/user-attachments/assets/3dd7f76f-7da0-4767-94da-5ec72cebfc2d)

Create a database change task and re-initiate the task, but the SQL query statement is not carried in it

### What did you expect to happen?

When you create a database change task and re-initiate the task, the SQL query statement should carry the newly initiated ticket page

### How can we reproduce it (as minimally and precisely as possible)?

Select a new database change task, add the change sql statement, upload the attachment, make the task fail, click Start again, view the SQL input, and the SQL statement is not displayed

**Comment by HSunboy** [comment]
Fixed In Commit [761b4adce635b6c63cc32cb6afb26e04ca2afa92](https://github.com/oceanbase/odc-client/commit/761b4adce635b6c63cc32cb6afb26e04ca2afa92)
            ------
            艺泽
            Tue Dec 3 17:53:55 2024 +0800

**Comment by qymsummer** [comment]
![Uploading image.png…]()

pass
