### ISSUE TITLE
[Bug]: When the shadow table is synchronized again, the table name is not carried correctly

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3917]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/6338bc12-b20d-4f7d-8b15-7dd34ac7d48f)
When the shadow table is synchronized again, the table name is not carried correctly, the table name is changed to _test_12121212, and the table name is the default test after the table is initiated again, and the 12121212 is missing
![image](https://github.com/user-attachments/assets/9a5aaf6c-5d12-46e7-8a7c-4722a05793a1)

### What did you expect to happen?

The shadow table is synchronized, and the parameters should be the same as the original settings after the instance is initiated again

### How can we reproduce it (as minimally and precisely as possible)?

Start a shadow table synchronization task, modify the table name prefix, start the current task, and click Start again to check whether the table name prefix is correct

**Comment by HSunboy** [comment]
Fixed In Commit [761b4adce635b6c63cc32cb6afb26e04ca2afa92](https://github.com/oceanbase/odc-client/commit/761b4adce635b6c63cc32cb6afb26e04ca2afa92)
            ------
            艺泽
            Tue Dec 3 17:53:55 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/061c1270-4ec9-480d-9930-2249489bab71)

pass
