### ISSUE TITLE
[Bug]: For the structure comparison task, click to initiate again, but the new ticket interface does not jump correctly

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3918]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/b3cc7e8c-7af8-4d50-8823-2e0f5cc862f5)
If you click to initiate the structure comparison task again, the new ticket interface does not jump correctly, and the interface still displays the current ticket

### What did you expect to happen?

For the structure comparison task, click Initiate Again, and the New Ticket page should be displayed

### How can we reproduce it (as minimally and precisely as possible)?

Select a structure comparison task and click Initiate again to observe the display of the ticket

**Comment by HSunboy** [comment]
Fixed In Commit [761b4adce635b6c63cc32cb6afb26e04ca2afa92](https://github.com/oceanbase/odc-client/commit/761b4adce635b6c63cc32cb6afb26e04ca2afa92)
            ------
            艺泽
            Tue Dec 3 17:53:55 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/ac109ea9-0664-4d81-bbf3-391625cc95eb)

pass
