### ISSUE TITLE
[Bug]: When you select Export for the whole database, when you initiate it again, it still defaults to a partial export

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3919]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/b790f8f2-fa74-42a7-b989-74a53e0d65da)
![image](https://github.com/user-attachments/assets/37687a27-50b4-44f4-8991-2f8650e15bda)
When you select Export for the whole database, when you initiate it again, it still defaults to a partial export

### What did you expect to happen?

If you select Export for the entire database during the export, the task should still be the entire export task when you start it again

### How can we reproduce it (as minimally and precisely as possible)?

If you select Whole Database Export during export, observe whether the entire database export task is still the entire database export when you start it again

**Comment by HSunboy** [comment]
Fixed In Commit [761b4adce635b6c63cc32cb6afb26e04ca2afa92](https://github.com/oceanbase/odc-client/commit/761b4adce635b6c63cc32cb6afb26e04ca2afa92)
            ------
            艺泽
            Tue Dec 3 17:53:55 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/d2f91f87-74b9-4b38-bf73-d8cd13db3342)

pass
