### ISSUE TITLE
[Bug]: When the result set is exported, the task description and query SQL are missing when it is initiated again

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3920]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/e9bee0f8-9c71-4074-aa25-9ee29ae5b6cc)
When the result set is exported, the task description and query SQL are missing when it is initiated again

### What did you expect to happen?

When the result set is exported, the task description and query SQL should be carried when it is initiated again

### How can we reproduce it (as minimally and precisely as possible)?

Start a result set export task again and check whether the parameters carried by the task are the same as those carried by the initial one

**Comment by HSunboy** [comment]
Fixed In Commit [761b4adce635b6c63cc32cb6afb26e04ca2afa92](https://github.com/oceanbase/odc-client/commit/761b4adce635b6c63cc32cb6afb26e04ca2afa92)
            ------
            艺泽
            Tue Dec 3 17:53:55 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/670bc119-d9d2-4c05-a841-a246bf170d85)

pass
