### ISSUE TITLE
[Bug]: Ob425 Chinese stored procedure displays garbled characters

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3932]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/6c8e2364-b7c3-4576-862f-042714073528)

### What did you expect to happen?

Display Chinese normally

### How can we reproduce it (as minimally and precisely as possible)?

View after creating a Chinese stored procedure

**Comment by zijiacj** [comment]
![Image](https://github.com/user-attachments/assets/0561f82b-abd2-4886-bc55-ae8ea8118655)
It's not an odc bug, it's an ob bug
