### ISSUE TITLE
[Bug]: The archive execution details are displayed as empty

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3935]
### ODC version

ODC433

### OB version

independent

### What happened?

The archive execution details are displayed as empty
![image](https://github.com/user-attachments/assets/939a04bf-21a0-4e8d-ab8e-0484a3bdf561)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by guowl3** [comment]
There is nothing when the task initialization fails
