### ISSUE TITLE
[Bug]: After modifying the function, the execution display remains unchanged

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3936]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/889042e3-0b25-4969-8112-e653fc06cb66)
![image](https://github.com/user-attachments/assets/5983f1b3-ba45-4d7d-9452-f3053db34f4f)

### What did you expect to happen?

After modifying the function, the execution display also changes

### How can we reproduce it (as minimally and precisely as possible)?

Create a new function, modify the data type or parameter name, and execute it

**Comment by HSunboy** [comment]
Fixed In Commit [e9e367ba6dd8554a8b897b704de3a007ccd748e0](https://github.com/oceanbase/odc-client/commit/e9e367ba6dd8554a8b897b704de3a007ccd748e0)
            ------
            畅晚
            Mon Dec 16 09:50:10 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/88d01b39-4132-4646-89b6-52aa3db8fbae)
pass
