### ISSUE TITLE
[Bug]: Error reported when modifying a function with special characters as names

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3941]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/0e2d17b5-1a48-4fac-bc59-ce9e56868968)

### What did you expect to happen?

Modified successfully

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Function
create function `FuN_tesT@111~!#$%^&*()_+` (`p1` int(11)) returns int(11) begin declare v1 int; set v1 = p1 + 1; return v1; end;
2. Modify function

**Comment by zijiacj** [comment]
It is not a bug
![Image](https://github.com/user-attachments/assets/e5205b05-7805-4ffc-a199-593677855340)

**Comment by sl01388797** [comment]
pass
