### ISSUE TITLE
[Bug]: When the personal space data source environment is the production environment, the automatic operation of the work order requires approval

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3943]
### ODC version

ODC432

### OB version

independent

### What happened?

When the personal space data source environment is the production environment, the automatic operation of the work order requires approval

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/user-attachments/assets/e22a5c56-dfbe-44f1-8aeb-83f5d2da3c2e)
Create a data source, set the environment to development environment, create rules, and approval is required when the environment is development

**Comment by guowl3** [comment]
https://github.com/oceanbase/odc/pull/4067

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/06e84d7c-9cf3-47cc-8944-87b43c67a20f)
pass
