### ISSUE TITLE
[Bug]: When you create a new database, the rule prompt is overwritten

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3949]
### ODC version

odc433

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/418139f8-ed3d-4f25-8b29-c73bfcb2eae7)
When you create a new database, the rule prompt is overwritten

### What did you expect to happen?

When you create a new database, the rule prompt is overwritten

### How can we reproduce it (as minimally and precisely as possible)?

Select a database ticket, create a database, and observe the display of the menu

**Comment by HSunboy** [comment]
Fixed In Commit [e9e367ba6dd8554a8b897b704de3a007ccd748e0](https://github.com/oceanbase/odc-client/commit/e9e367ba6dd8554a8b897b704de3a007ccd748e0)
            ------
            畅晚
            Mon Dec 16 09:50:10 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/f5f019cd-7ec4-463d-98d5-7a063c0dd1c7)
![Uploading image.png…]()
