### ISSUE TITLE
[Bug]: The simulation data task log is empty.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3950]
### ODC version

ODC432bp

### OB version

independent

### What happened?

The simulation data task log is empty.
![image](https://github.com/user-attachments/assets/8c8c9a60-abea-42ff-bda6-3aa68ac80b87)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/3e5833e8-0a6a-4d87-b3d4-203d0ef9422d)
pass
