### ISSUE TITLE
[Bug]: Obmysql editing stored procedure error

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3951]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/9487e6c3-6c01-43f9-a333-8c19bd6d8d42)

### What did you expect to happen?

Edited successfully

### How can we reproduce it (as minimally and precisely as possible)?

1. Create stored procedure
2. Edit stored procedure

**Comment by zijiacj** [comment]
remove duplicate precudre names.It is not a bug
