### ISSUE TITLE
[Bug]: When you apply for library permissions and submit them again, the validity period of the permissions is different from the first time

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3953]
### ODC version

4.3.3.

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/b10879eb-ff47-4faf-b44f-519a26456ad8)
![image](https://github.com/user-attachments/assets/9cb09414-a2e8-4a98-ad02-48bffb9645ee)
When you apply for a library permission, the permission is valid for 30 days when you submit it, and the permission for re-initiating the permission is valid for 7 days

### What did you expect to happen?

When re-initiated, the value of the permission validity period should be the same as the validity period selected for the first submission

### How can we reproduce it (as minimally and precisely as possible)?

Submit a database permission application, select a validity period of 30 days or another time, and initiate the request again to check whether the validity period of the newly generated ticket is the same as that of the first time

**Comment by HSunboy** [comment]
Fixed In Commit [cde598c983709bbebf6b34952101d749d03336aa](https://github.com/oceanbase/odc-client/commit/cde598c983709bbebf6b34952101d749d03336aa)
            ------
            艺泽
            Wed Dec 18 17:36:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/a7ef8f9d-c647-4f51-a496-915910f1656b)
pass
