### ISSUE TITLE
[Bug]: After modifying the function, click to run it again with the original content, but it cannot run

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3956]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/1dab1b6d-b46c-4a6c-a75d-697d870e33e5)

### What did you expect to happen?

Can be executed

### How can we reproduce it (as minimally and precisely as possible)?

Create function, modify function, revert back to original function, click execute

**Comment by HSunboy** [comment]
Fixed In Commit [6898939a34e04c5ab70575388768e92eaee535bf](https://github.com/oceanbase/odc-client/commit/6898939a34e04c5ab70575388768e92eaee535bf)
            ------
            畅晚
            Wed Dec 18 18:18:35 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/e670932d-759d-4cdf-be92-9a9ec8160cd7)
pass
