### ISSUE TITLE
[Bug]: Click to initiate the simulation data task to be executed again, and the fields displayed on the page are all blank.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3965]
### ODC version

ODC433

### OB version

independent

### What happened?

Click to initiate the simulation data task to be executed again, and the fields displayed on the page are all blank.
![image](https://github.com/user-attachments/assets/73f6e502-d09d-4a6a-86eb-7750f47d045f)
![image](https://github.com/user-attachments/assets/ea7d9503-ead5-4036-8640-99ae4f996bb1)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [cde598c983709bbebf6b34952101d749d03336aa](https://github.com/oceanbase/odc-client/commit/cde598c983709bbebf6b34952101d749d03336aa)
            ------
            艺泽
            Wed Dec 18 17:36:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/e6453cc5-5ddb-4f79-a9ec-2e3c1f217114)
pass
