### ISSUE TITLE
[Bug]: The SQL for generating tables for full-text indexing cannot be executed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#3968]
### ODC version

odc433

### OB version

ob433

### What happened?

![2e302fa6cc63464edbfd2bc04876a3a1](https://github.com/user-attachments/assets/7c3ffcf3-8e4d-4303-a285-ffa946741181)

### What did you expect to happen?

Can create full-text index table normally

### How can we reproduce it (as minimally and precisely as possible)?

Create full-text index table

**Comment by PeachThinking** [comment]
<img width="982" alt="image" src="https://github.com/user-attachments/assets/62d0d7a9-8401-4b3b-8249-6adfd08f4e83">
ob mysql do not support GLOBAL fulltext index, choose "LOCAL" and you can create the table successfully
