### ISSUE TITLE
[Bug]: The external table does not support "alter table" , and the edit button should be disabled on the frontend

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3969]
### ODC version

ODC 4.3.3

### OB version

OB4321

### What happened?

![图片](https://github.com/user-attachments/assets/8b92bba1-04d0-4547-87cf-c13e372fa64b)

### What did you expect to happen?

the edit button should be disabled

### How can we reproduce it (as minimally and precisely as possible)?

Edit the external table structure.

**Comment by HSunboy** [comment]
Fixed In Commit [e9e367ba6dd8554a8b897b704de3a007ccd748e0](https://github.com/oceanbase/odc-client/commit/e9e367ba6dd8554a8b897b704de3a007ccd748e0)
            ------
            畅晚
            Mon Dec 16 09:50:10 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/b3e090d4-3b7b-4d2d-b7df-4b7a26500a95)
pass
