### ISSUE TITLE
[Bug]: Cannot view the full table name in the Partitioning Plan task details

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#3978]
### ODC version

All

### OB version

all

### What happened?

When the table name is too long,cannot view the full table name in the Partitioning Plan task details
![image](https://github.com/user-attachments/assets/d19dbc17-3918-4fa8-8e3e-bc64cb858c70)

### What did you expect to happen?

can view the full table name in the Partitioning Plan task details

### How can we reproduce it (as minimally and precisely as possible)?

See the above description

**Comment by HSunboy** [comment]
<img width="443" alt="image" src="https://github.com/user-attachments/assets/f9c7faa1-9e4d-4958-aa40-3b08f3a9b3bd">
This Bug has been fixed in dev-4.3.2
