### ISSUE TITLE
[Bug]: For the data archiving task, click Terminate failed

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3989]
### ODC version

4.3.3

### OB version

no relatead

### What happened?

![image](https://github.com/user-attachments/assets/103de0ac-5b6f-4cfb-a0bb-1862e4422b67)
Initiate a data archiving task of the type of Execute Now, click the Terminate button, and an error message is reported

### What did you expect to happen?

Initiate a data archiving task of the type of Immediate Execution, and click the Terminate button to terminate it normally

### How can we reproduce it (as minimally and precisely as possible)?

Initiate a data archiving task of the type of Execute Now, click the Terminate button, and an error message is reported

**Comment by guowl3** [comment]
The correct enumeration value is: TERMINATE

**Comment by HSunboy** [comment]
Fixed In Commit [4a7904b116b5803db5781b5852525883b48e91a6](https://github.com/oceanbase/odc-client/commit/4a7904b116b5803db5781b5852525883b48e91a6)
            ------
            畅晚
            Thu Dec 19 09:56:45 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/40ca6e56-74e4-465d-83b1-5e4e751fbec6)
pass
