### ISSUE TITLE
[enhancement]: If the data source is invalid, the database of the corresponding data source in the project also needs to be grayed out.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#399]
### ODC version

ODC4.2.1

### OB version

oceabase4.1.0

### What happened?

Currently, if the data source of ODC is invalid, you can still log in to the database by clicking on the database name in the project. The experience is not good.
![image](https://github.com/oceanbase/odc/assets/59468957/6b387ba9-45ea-44e4-a0ff-26e9358abceb)
![image](https://github.com/oceanbase/odc/assets/59468957/0a83057e-548a-4b18-ae17-dc479ac00344)

### What did you expect to happen?

If the data source is invalid, the database of the corresponding data source in the project also needs to be grayed out.

### How can we reproduce it (as minimally and precisely as possible)?

Create a data source, create a project, assign the project source to the project, and invalidate the data source

**Comment by HSunboy** [comment]
added in dev-4.2.4
