### ISSUE TITLE
[Bug]: Error 400 when entering a project

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3992]
### ODC version

ODC 4.3.3

### OB version

No related.

### What happened?

![图片](https://github.com/user-attachments/assets/bed99a19-38fd-4b54-b746-1c4ccbd6b629)
traceId
: 
"fa7dbda7b65b429b"
This interface reports an error："参数错误，详情：{0}"
http://11.162.217.57:16677/api/v2/datasource/datasources?currentOrganizationId=1&size=99999&page=1&type=OSS&type=COS&type=OBS&type=S3

### What did you expect to happen?

Enter the project without reporting errors.

### How can we reproduce it (as minimally and precisely as possible)?

Enter a project.

**Comment by MarkPotato777** [comment]
Seems like related to DLM and OSS

**Comment by guowl3** [comment]
Ignore it and test after the DLM SDK is republished

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/1deefc2c-b684-45ac-b519-415507c1f8a8)
pass
