### ISSUE TITLE
[Bug]: The source data source is grayed out and you can click the triangle symbol to expand it.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3994]
### ODC version

ODC432

### OB version

independent

### What happened?

The source data source is grayed out and you can click the triangle symbol to expand it.
![image](https://github.com/user-attachments/assets/79f8370f-2375-4fde-b92c-b40e5d461641)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [e9e367ba6dd8554a8b897b704de3a007ccd748e0](https://github.com/oceanbase/odc-client/commit/e9e367ba6dd8554a8b897b704de3a007ccd748e0)
            ------
            畅晚
            Mon Dec 16 09:50:10 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/3bd8cff9-73e9-4451-ad83-77f5134efae9)
pass
