### ISSUE TITLE
[Bug]: Result sets cannot be downloaded from external tables

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#3995]
### ODC version

ODC 4.3.3

### OB version

OB4.3.2.1

### What happened?

Result sets cannot be downloaded from external tables
![图片](https://github.com/user-attachments/assets/dbdbf089-e8c3-4b3b-bc72-054acb62bf5c)

### What did you expect to happen?

Could download.

### How can we reproduce it (as minimally and precisely as possible)?

Download external result set

**Comment by zijiacj** [comment]
it is caused by the sql window closing to download the result set configuration, and does not belong to the bug category

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/c52406b4-bcd2-415e-960c-2bc635bb3c91)
pass
