### ISSUE TITLE
[Bug]: There is no cancel button for periodic tasks

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#3996]
### ODC version

ODC433

### OB version

independent

### What happened?

There is no cancel button for periodic tasks
![image](https://github.com/user-attachments/assets/c373b40f-d08d-40b2-8472-da282131749e)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [e9e367ba6dd8554a8b897b704de3a007ccd748e0](https://github.com/oceanbase/odc-client/commit/e9e367ba6dd8554a8b897b704de3a007ccd748e0)
            ------
            畅晚
            Mon Dec 16 09:50:10 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/086518d3-6510-4a1e-8749-ffe2919055e1)
pass
