### ISSUE TITLE
[Bug]: There is no Disable button for the periodic scheduling task of data archiving

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#3997]
### ODC version

433

### OB version

no related

### What happened?

There is no Disable button for the periodic scheduling task of data archiving
![image](https://github.com/user-attachments/assets/47d95f9c-39f4-4efe-84c1-04ab18eb3db8)

### What did you expect to happen?

The data archiving periodic scheduling task should have a disable button

### How can we reproduce it (as minimally and precisely as possible)?

Create a data archiving task, set Scheduling Method to Periodic Scheduling, and observe whether the Disable button is available after the task is initiated

**Comment by yezaoshu** [comment]
it's duplicate with https://github.com/oceanbase/odc/issues/3996
