### ISSUE TITLE
[Feature]: Resultset support replication by column headers

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#4]
**Value of feature**

Improve product usability

**Description of feature**

Resultset header column does not support replication
https://ask.oceanbase.com/t/topic/35603068

**Other instructions**

1.Supports selecting an entire column by clicking on the column header.
2.Support shift+ click multiple columns to copy multiple columns

**Additional context**

**Comment by yhilmare** [comment]
front end related
