### ISSUE TITLE
[Bug]: Optimize the error message, create a JSON type table, enter a long JSON content, and get the error "The number must be between 0 and 204800"

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#401]
### ODC version

ODC4.2.1

### OB version

Oceanbase 4.1.0

### What happened?

Create a JSON type table, input a very long JSON content, and report ‘the number must be between 0 and 204800’
![image](https://github.com/oceanbase/odc/assets/59468957/29da7d56-e52f-46aa-87ee-eaad098c2471)

### What did you expect to happen?

Create a JSON type table, input a very long JSON content, and report ‘the number must be between 0 and 204800’

### How can we reproduce it (as minimally and precisely as possible)?

1. Create table, type json
2. Enter the super long json and click to confirm the modification.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/bdaba6d2-baf5-44d4-936d-6b08026d6604)

pass
