### ISSUE TITLE
[Bug]: Error in modifying stored procedure for special character names

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4012]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/aae2a042-69da-4287-ac59-cf586b4b8015)

### What did you expect to happen?

Modified successfully

### How can we reproduce it (as minimally and precisely as possible)?

Create stored procedures for special character names and modify them

**Comment by ysjemmm** [comment]
any names can't modify, not only the special character
odc front backed need to remove the limit of can't change name
![Image](https://github.com/user-attachments/assets/4ebaa7dc-989e-4b07-8800-12f175670329)
