### ISSUE TITLE
[Bug]: If you do not select a data source, click Add in batches, and the interface will continue to rotate

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4014]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/ffe4a6b0-c856-4755-9c89-50fa450c2fb4)
For data archiving tasks, if you do not select a data source, click Add in batches, and the interface will continue to rotate

### What did you expect to happen?

For data archiving tasks, if you do not select a data source, click Add in batches, and a prompt should be displayed on the interface, or if you do not select a data source, you cannot click the Add in batches button, instead of loading in a circle

### How can we reproduce it (as minimally and precisely as possible)?

To initiate a data archiving task, select no data source and click Add in batches

**Comment by HSunboy** [comment]
Fixed In Commit [be913ac19b33c8a7c64e8bd3adabdaf1519b935a](https://github.com/oceanbase/odc-client/commit/be913ac19b33c8a7c64e8bd3adabdaf1519b935a)
            ------
            艺泽
            Fri Dec 20 18:00:41 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/f6f560e6-1084-4959-b639-35d7dd7f0a3d)

pass
