### ISSUE TITLE
[Bug]: Confirm modifications when editing functions and stored procedures in ob mysql. You can keep clicking on them

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4015]
### ODC version

odc433

### OB version

*

### What happened?

![e8de032e17ebd5ef0350d563ac335da0](https://github.com/user-attachments/assets/a826965b-d6ee-49a0-a490-0cff210ac92d)

### What did you expect to happen?

Cannot click continuously

### How can we reproduce it (as minimally and precisely as possible)?

After modifying a stored procedure or function, keep clicking OK to make the changes

**Comment by HSunboy** [comment]
Fixed In Commit [6898939a34e04c5ab70575388768e92eaee535bf](https://github.com/oceanbase/odc-client/commit/6898939a34e04c5ab70575388768e92eaee535bf)
            ------
            畅晚
            Wed Dec 18 18:18:35 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/03787f2a-ad2d-4fee-ba74-e52b7855f486)
pass
