### ISSUE TITLE
[Bug]: The obmysql stored procedure did not update after clicking the refresh button

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4022]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/69c0401f-69aa-4041-b885-c5fcec658296)

### What did you expect to happen?

Page Update

### How can we reproduce it (as minimally and precisely as possible)?

Create stored procedure, modify stored procedure, refresh

**Comment by HSunboy** [comment]
Fixed In Commit [6898939a34e04c5ab70575388768e92eaee535bf](https://github.com/oceanbase/odc-client/commit/6898939a34e04c5ab70575388768e92eaee535bf)
            ------
            畅晚
            Wed Dec 18 18:18:35 2024 +0800
