### ISSUE TITLE
[Bug]: An error is reported when data archiving, scheduled tasks, and editing description information are reported

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4024]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/dedf040c-27cc-43fd-8f7e-e0b75269d8ae)
![image](https://github.com/user-attachments/assets/e94e7d17-1969-4682-a9b3-3cfe098ef403)
![image](https://github.com/user-attachments/assets/7fd08bf2-64ca-4c47-9406-01160326897c)
Data archiving, scheduled execution, enter a new description, click Save, and an error is reported

### What did you expect to happen?

Data archiving, scheduled execution, enter a new description, click Save, and the description can be modified normally

### How can we reproduce it (as minimally and precisely as possible)?

Initiate a data archiving task, execute the task on a scheduled basis, modify the description information, click Save, and observe whether there is any abnormality in the system

**Comment by guowl3** [comment]
scheduled task can only be edited if it is in a disabled state and has no running subtasks
