### ISSUE TITLE
[Bug]: There is a new project button in the archived project

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4027]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/1a954a80-b81a-4a9c-93dc-327f841059ee)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/61c31dea-0b1a-48e7-8563-4954f3511571)

### How can we reproduce it (as minimally and precisely as possible)?

View the archived project page

**Comment by HSunboy** [comment]
Fixed In Commit [2e5ba70324b9b4d19ccb9fbe9df1925c9168bd66](https://github.com/oceanbase/odc-client/commit/2e5ba70324b9b4d19ccb9fbe9df1925c9168bd66)
            ------
            艺泽
            Tue Dec 17 09:55:27 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/858365ec-7e96-4f92-8d24-0389ed27f7b1)
pass
