### ISSUE TITLE
[Bug]: There is a add project button when there is a project in the archive project

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4029]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/7f7f5bde-1395-493a-809b-2c44c9ee75d4)

### What did you expect to happen?

There is no add project button

### How can we reproduce it (as minimally and precisely as possible)?

Create project, archive project, view archive project

**Comment by HSunboy** [comment]
Fixed In Commit [2e5ba70324b9b4d19ccb9fbe9df1925c9168bd66](https://github.com/oceanbase/odc-client/commit/2e5ba70324b9b4d19ccb9fbe9df1925c9168bd66)
            ------
            艺泽
            Tue Dec 17 09:55:27 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/54d14ed2-348c-47e0-bd52-2a3ba2088734)
pass
