### ISSUE TITLE
[Enhancement]: Remove dynamic desensitization logic in personal space to optimize the time consumption of getResult interface

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#403]
### What would you like to be added?

Remove dynamic desensitization logic in personal space to optimize the time consumption of getResult interface

### Why is this needed?

Remove dynamic desensitization logic in personal space to optimize the time consumption of getResult interface

**Comment by smallsheeeep** [comment]
This  issue is duplicduplicatedated with #382
