### ISSUE TITLE
[Bug]: A data archiving task that executes the termination and regression operations in the record is not recorded in the operation record

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4030]
### ODC version

4.3.3

### OB version

no related

### What happened?

A data archiving task that executes the termination and regression operations in the record is not recorded in the operation record
![image](https://github.com/user-attachments/assets/bf10e3a7-b8be-43cf-a724-c317e0bfd28d)
![image](https://github.com/user-attachments/assets/b81ff3d3-cf68-4e13-aad9-2f172a304a2f)

### What did you expect to happen?

Data archiving task to perform the "termination, regression" operations in the record (full screening and changes that need to be recorded in the operation). It should be recorded in the operation log

### How can we reproduce it (as minimally and precisely as possible)?

Select a data archiving task, select a task in the execution record, and click Rollback or Terminate to check whether the details in the operation record are complete

**Comment by guowl3** [comment]
as expected
