### ISSUE TITLE
[Bug]: Failed to modify view structure before executing new view

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4036]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/c8f27c65-055d-4f62-ae3e-e3b79c9a2dc0)
![image](https://github.com/user-attachments/assets/fce5c919-a4c4-4280-a4fa-6580fead34d4)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/112d3830-48f3-4742-9d13-b9a89eb62dd4)

### How can we reproduce it (as minimally and precisely as possible)?

Check multiple tables when creating a view, modify the view structure, and execute

**Comment by HSunboy** [comment]
Fixed In Commit [6898939a34e04c5ab70575388768e92eaee535bf](https://github.com/oceanbase/odc-client/commit/6898939a34e04c5ab70575388768e92eaee535bf)
            ------
            畅晚
            Wed Dec 18 18:18:35 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/7da24524-6bbd-4fa6-89a1-e94f086b1964)
pass
