### ISSUE TITLE
[Bug]: The application form/view permission selection form or view will automatically retract when pulled down

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4037]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/3bfc299c-e4f9-44c8-a75e-2572f0874221)
![image](https://github.com/user-attachments/assets/6c3169f4-5c8f-4393-9c03-e3a375d0a195)

### What did you expect to happen?

When selected or deleted, the dropdown menu of selected items will not be automatically reclaimed

### How can we reproduce it (as minimally and precisely as possible)?

1. Select multiple tables or views within the application form/view permission
2. Select or delete selected tables

**Comment by HSunboy** [comment]
Fixed In Commit [6898939a34e04c5ab70575388768e92eaee535bf](https://github.com/oceanbase/odc-client/commit/6898939a34e04c5ab70575388768e92eaee535bf)
            ------
            畅晚
            Wed Dec 18 18:18:35 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/02cb7ea7-c46a-45d3-910f-9471c133c141)
![Image](https://github.com/user-attachments/assets/dae1778f-ee46-43bc-bf97-6f840ba7977b)
Clicking on delete will cause it to retract

**Comment by HSunboy** [comment]
Fixed In Commit [ab045acb1f31ebad9e77832ca1e8e6f8449fa5e3](https://github.com/oceanbase/odc-client/commit/ab045acb1f31ebad9e77832ca1e8e6f8449fa5e3)
            ------
            畅晚
            Mon Dec 23 09:59:49 2024 +0800

**Comment by sl01388797** [comment]
pass
