### ISSUE TITLE
[Bug]: Create an OSS data source. The file URL is configured with the path, not the file name.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#4039]
### ODC version

ODC433

### OB version

independent

### What happened?

Create an OSS data source. The file URL is configured with the path, not the file name.
![image](https://github.com/user-attachments/assets/a71faad6-d10e-4c4a-84de-183754199bea)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by guowl3** [comment]
As expected.
