### ISSUE TITLE
[Bug]: The table creation statement generated by TableEditor in MYSQL mode cannot be executed.

### ISSUE THREAD

**Issue by guowl3** [oceanbase/odc#404]
### ODC version

4.2.1

### OB version

Any version.

### What happened?

The table creation statement generated by TableEditor in MYSQL mode cannot be executed.

### What did you expect to happen?

The table creation statement generated by TableEditor in MYSQL mode can be executed.

### How can we reproduce it (as minimally and precisely as possible)?

Obtain the table creation statement from the OB data source, convert it into MYSQL syntax through TableEditor and then execute it.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/55afdcfd-750a-4241-92f1-8bd3a060a486)

pass
