### ISSUE TITLE
[Bug]: The archive source does not support object storage and needs to be hidden.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#4040]
### ODC version

ODC433

### OB version

independent

### What happened?

The archive source does not support object storage and needs to be hidden.

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [cde598c983709bbebf6b34952101d749d03336aa](https://github.com/oceanbase/odc-client/commit/cde598c983709bbebf6b34952101d749d03336aa)
            ------
            艺泽
            Wed Dec 18 17:36:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/e8ca04c9-931e-4c9d-a7cf-8445209762ec)
pass
