### ISSUE TITLE
[Bug]: Alibaba Cloud OSS clicked on the test link but did not return

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4043]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/f7e2cfba-0c63-4768-9df8-00f602220251)
### What did you expect to happen?

There is an error message

### How can we reproduce it (as minimally and precisely as possible)?

Click on the test link for Alibaba Cloud OSS

**Comment by HSunboy** [comment]
Fixed In Commit [cde598c983709bbebf6b34952101d749d03336aa](https://github.com/oceanbase/odc-client/commit/cde598c983709bbebf6b34952101d749d03336aa)
            ------
            艺泽
            Wed Dec 18 17:36:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/170ab697-6fa8-4db8-a2cf-bc7a78a26adf)
pass
