### ISSUE TITLE
[Bug]: Alibaba Cloud OSS link failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4044]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/edbab062-9d67-46ee-b5cf-48c4944c8a00)

### What did you expect to happen?

Link successful

### How can we reproduce it (as minimally and precisely as possible)?

Create OSS link

**Comment by guowl3** [comment]
please input a valid file path and I will opt error message later
