### ISSUE TITLE
[Bug]: List format display optimization

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#4045]
### ODC version

ODC433

### OB version

independent

### What happened?

List format display optimization
![image](https://github.com/user-attachments/assets/03aba173-af1f-4f55-9e97-695f15c1705d)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by HSunboy** [comment]
Fixed In Commit [6898939a34e04c5ab70575388768e92eaee535bf](https://github.com/oceanbase/odc-client/commit/6898939a34e04c5ab70575388768e92eaee535bf)
            ------
            畅晚
            Wed Dec 18 18:18:35 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/7d0c930b-4405-499b-b1c4-3a510046ed01)
pass
