### ISSUE TITLE
[Bug]: Object storage archive, post-archive cleanup is not performed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#4057]
### ODC version

ODC433

### OB version

independent

### What happened?

Object storage archive, post-archive cleanup is not performed
![image](https://github.com/user-attachments/assets/3cdceeec-a0bc-4aa6-82d2-e4f3f41359fe)
![image](https://github.com/user-attachments/assets/0d99d931-fc83-462a-994b-40925b2051fe)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by guowl3** [comment]
delete after archive is not supported now
