### ISSUE TITLE
[Bug]: Entering the wrong access key and clicking on the test link shows that the link has passed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4060]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/39895c81-5aee-4d61-85b6-15b397c469a0)

### What did you expect to happen?

Do not display test link passed

### How can we reproduce it (as minimally and precisely as possible)?

Create Alibaba Cloud OSS data source with incorrect access key input

**Comment by HSunboy** [comment]
Fixed In Commit [cde598c983709bbebf6b34952101d749d03336aa](https://github.com/oceanbase/odc-client/commit/cde598c983709bbebf6b34952101d749d03336aa)
            ------
            艺泽
            Wed Dec 18 17:36:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/9297bf1c-e475-429c-a9c3-36096493b4c2)
pass
