### ISSUE TITLE
[Bug]: Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS application form permission dropdown error

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4061]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/716cfa56-db4e-4d62-ad91-2e2e4a1b2aed)

### What did you expect to happen?

Application form permissions do not display Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS data sources

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS data sources and join the project
2. Pull down Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS data sources within the permission of the application form

**Comment by HSunboy** [comment]
Fixed In Commit [cde598c983709bbebf6b34952101d749d03336aa](https://github.com/oceanbase/odc-client/commit/cde598c983709bbebf6b34952101d749d03336aa)
            ------
            艺泽
            Wed Dec 18 17:36:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/b4e1b245-1634-462e-b23e-1686f90a541b)
pass
