### ISSUE TITLE
[Bug]: Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS data source. Click to view details. No response

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4062]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/dd3a8342-3588-479c-af29-f579f1bad89b)

### What did you expect to happen?

Click to view details and there is a response

### How can we reproduce it (as minimally and precisely as possible)?

Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS Data Sources Click to View Details

**Comment by HSunboy** [comment]
Fixed In Commit [cde598c983709bbebf6b34952101d749d03336aa](https://github.com/oceanbase/odc-client/commit/cde598c983709bbebf6b34952101d749d03336aa)
            ------
            艺泽
            Wed Dec 18 17:36:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/2273080d-e304-4c15-8528-27dacc6e0acd)
pass
