### ISSUE TITLE
[Bug]: There are Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS data sources within the application library permission

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4063]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/563f7241-1b43-4721-aced-a19a09e4b19b)

### What did you expect to happen?

There is no Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS data source within the application library permission

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS data sources
2. Apply for library permissions

**Comment by HSunboy** [comment]
Fixed In Commit [cde598c983709bbebf6b34952101d749d03336aa](https://github.com/oceanbase/odc-client/commit/cde598c983709bbebf6b34952101d749d03336aa)
            ------
            艺泽
            Wed Dec 18 17:36:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/53c3d178-87f3-4e77-9abe-9dc68565e756)
pass
