### ISSUE TITLE
[Bug]: Personal space cannot delete Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS data sources

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4065]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/7dce3d19-90c4-49fa-a736-eb9cb3f08e9f)

### What did you expect to happen?

There is a deletion entry

### How can we reproduce it (as minimally and precisely as possible)?

Create personal space for Alibaba Cloud OSS/Tencent Cloud OCS/Huawei Cloud OBS/AWS data sources, delete data sources

**Comment by HSunboy** [comment]
Fixed In Commit [cde598c983709bbebf6b34952101d749d03336aa](https://github.com/oceanbase/odc-client/commit/cde598c983709bbebf6b34952101d749d03336aa)
            ------
            艺泽
            Wed Dec 18 17:36:39 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/a2b70ca6-2f4b-4e2a-8f06-164faaf71255)
pass
