### ISSUE TITLE
[Bug]: Desktop version, the data source is invalid and the link is not grayed out

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#407]
### ODC version

ODC4.2.1

### OB version

Oceanbase4.1.0

### What happened?

Desktop version, the data source is invalid and the link is not grayed out
![image](https://github.com/oceanbase/odc/assets/59468957/288a142c-197c-4e3a-a32e-7116067e2e34)

### What did you expect to happen?

Desktop version, the data source is invalid and the link grayes out

### How can we reproduce it (as minimally and precisely as possible)?

Desktop version, the data source is invalid and the link is not grayed out

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/68039483-4491-44cf-b016-9b38be16e6fd)

pass
