### ISSUE TITLE
[Bug]: Personal space tasks should not have project columns

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4071]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/34bd9722-e399-49ff-8594-a9a1d08f18b8)

### What did you expect to happen?

There is no project column for personal space tasks

### How can we reproduce it (as minimally and precisely as possible)?

Personal space viewing task

**Comment by HSunboy** [comment]
Fixed In Commit [f2df235677e05fffb92aa95f949a9083f70a5c82](https://github.com/oceanbase/odc-client/commit/f2df235677e05fffb92aa95f949a9083f70a5c82)
            ------
            艺泽
            Thu Dec 19 15:23:16 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/04756657-1668-4e61-8659-5900c50fd699)
pass
