### ISSUE TITLE
[Bug]: The work order within the project should not have a project column

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4072]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/90ecdc20-c2ee-4a80-ac33-975fdc6c7b29)

### What did you expect to happen?

There is no project column in the work order within the project

### How can we reproduce it (as minimally and precisely as possible)?

View work orders within the project

**Comment by HSunboy** [comment]
Fixed In Commit [f2df235677e05fffb92aa95f949a9083f70a5c82](https://github.com/oceanbase/odc-client/commit/f2df235677e05fffb92aa95f949a9083f70a5c82)
            ------
            艺泽
            Thu Dec 19 15:23:16 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/bb10dcb5-f917-46da-8040-49c43a2c70d0)
pass
