### ISSUE TITLE
[Bug]: The native MySQL editing button is not disabled

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#4076]
### ODC version

odc433

### OB version

*

### What happened?

![image](https://github.com/user-attachments/assets/1cc041f8-13e9-4aa1-add5-5d7b2c359813)

### What did you expect to happen?

![image](https://github.com/user-attachments/assets/b530307b-c464-4272-9099-c0beb5bd6067)

### How can we reproduce it (as minimally and precisely as possible)?

Editing operations on native MySQL

**Comment by HSunboy** [comment]
Fixed In Commit [ab045acb1f31ebad9e77832ca1e8e6f8449fa5e3](https://github.com/oceanbase/odc-client/commit/ab045acb1f31ebad9e77832ca1e8e6f8449fa5e3)
            ------
            畅晚
            Mon Dec 23 09:59:49 2024 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/user-attachments/assets/9f608c5d-fd61-4232-b918-e0c4d0461483)
pass
