### ISSUE TITLE
[Bug]: The signed, authenticated, and decrypted configuration pop-up prompt in which the SSO is inaccurate should be IDP

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4077]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/5e6f5717-1f60-4e73-be62-9fd72eff4d34)
![image](https://github.com/user-attachments/assets/e72fe283-523f-4e65-8c19-b9f26759ca49)
The pop-up prompt for signing, authentication, and decryption configurations shows that the SSO noun is inaccurate.

### What did you expect to happen?

The signed, authenticated, and decrypted configuration pop-up prompt in which the SSO is inaccurate should be IDP
Used to guarantee the decryption of requests for ODC-to-ODP services

### How can we reproduce it (as minimally and precisely as possible)?

Create a new login integration, click Advanced Options, and the SSO in the floating prompt of signing, authentication, and decryption configuration is incorrect, and it should be IDP

**Comment by HSunboy** [comment]
Fixed In Commit [bf529826f045552d50025b892a5353175ce80319](https://github.com/oceanbase/odc-client/commit/bf529826f045552d50025b892a5353175ce80319)
            ------
            艺泽
            Fri Dec 20 10:42:15 2024 +0800

**Comment by HSunboy** [comment]
Fixed In Commit [be913ac19b33c8a7c64e8bd3adabdaf1519b935a](https://github.com/oceanbase/odc-client/commit/be913ac19b33c8a7c64e8bd3adabdaf1519b935a)
            ------
            艺泽
            Fri Dec 20 18:00:41 2024 +0800

**Comment by qymsummer** [comment]
![Uploading image.png…]()

pass
