### ISSUE TITLE
[Bug]: The SAML login checks the signature configuration and saves it, but when you view it, the signature configuration is empty

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4081]
### ODC version

433

### OB version

norelated

### What happened?

The SAML login checks the signature configuration and saves it, but when you view it, the signature configuration is empty
![image](https://github.com/user-attachments/assets/39503fe5-ad13-4afc-b93a-6daac0ab04a7)
![image](https://github.com/user-attachments/assets/3c92a82d-9c36-4802-99d0-0829eb5b8a4c)

### What did you expect to happen?

The SAML login has the signature configuration checked and saved, but when viewed, the signature configuration should be the same as the configured value, not empty

### How can we reproduce it (as minimally and precisely as possible)?

Select a SAML login, configure a signature, click Save, and then review the configuration to check whether the signature takes effect

**Comment by HSunboy** [comment]
Fixed In Commit [7b28c6ef4228bdf39e2aaa0dca264dc0631db33d](https://github.com/oceanbase/odc-client/commit/7b28c6ef4228bdf39e2aaa0dca264dc0631db33d)
            ------
            艺泽
            Mon Dec 23 17:57:07 2024 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/user-attachments/assets/1fadae4a-7a47-4df9-9157-5a84f09559bd)
pass
