### ISSUE TITLE
[Bug]: when the amount of data executed during database change is too large, OOM occurs

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#409]
### ODC version

4.2.0

### OB version

none

### What happened?

When  the amount of data executed during database change is too large, OOM occurs

### What did you expect to happen?

OOM should be avoided in any case.

### How can we reproduce it (as minimally and precisely as possible)?

Raise a database change task with a lot sql files.

**Comment by smallsheeeep** [comment]
@LuckyPickleZZ Can you provide a sample SQL script?

**Comment by smallsheeeep** [comment]
In current, When user init a database change task and upload SQL script files, the single file size limit is <=256MB, and user can upload multiple files with size 256MB. ODC will read SQL files to a single Java `String` object. So if the SQL files is very large, then OOM may happened.
The most directly solution is decrease the upload SQL file's size. We will make it as 32 MB at largest in a task.

**Comment by smallsheeeep** [comment]
This issue have not been fixed. We should not decrease the SQL file size limit, but refine it by reading files using stream.
