### ISSUE TITLE
[Bug]: An error is reported when you log in to the SAML test link

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4097]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/1c0fb79a-6588-437b-9206-7d9f9be601fb)
After the SAML login configuration is complete, an error is reported when you click the test link

### What did you expect to happen?

After the SAML login configuration is complete, click Test to test successfully

### How can we reproduce it (as minimally and precisely as possible)?

Configure a saml login in authing, fill in the corresponding Metadata URI, click the test link, and observe the system response

**Comment by ungreat** [comment]
IDP metadata post bind method not support, but specify bind method to post manually here
