### ISSUE TITLE
[Bug]: After the saml login is completed, click the test link, and the ACS EntityID is displayed incorrectly

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4098]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/9a339a1f-9211-4196-bb5d-b3289f4bbd94)
After you log in to the saml and click the test link, the ACS EntityID is displayed incorrectly, and the suffix should be 1-test

### What did you expect to happen?

After you log in to the saml and click the test link, the ACS EntityID is displayed incorrectly, and the suffix should be 1-test

### How can we reproduce it (as minimally and precisely as possible)?

After the saml configuration is complete, click the Test link to check whether the ACS EntityID is correct

**Comment by HSunboy** [comment]
Fixed In Commit [74dba94343f7b87b9f3c40c62a1905a0c77b8d51](https://github.com/oceanbase/odc-client/commit/74dba94343f7b87b9f3c40c62a1905a0c77b8d51)
            ------
            艺泽
            Wed Dec 25 18:05:25 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/dfbba629-d09c-4b92-a4cf-952e950a87b0)
pass
