### ISSUE TITLE
[Bug]: After the SAML login is filled in and the authentication configuration is entered, the save does not take effect

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4099]
### ODC version

4.3.3

### OB version

no related

### What happened?

SAML checks the authentication configuration, fills in a value, and clicks Confirm to modify it to view the configuration
![image](https://github.com/user-attachments/assets/02240c16-3d5a-49d4-8666-ee24597e560b)
![image](https://github.com/user-attachments/assets/68137481-cc08-491a-bdac-013a6b826082)

### What did you expect to happen?

Select the authentication configuration in SAML, fill in a value, click Confirm to modify, view the configuration, authentication configuration, and the configuration is successfully displayed

### How can we reproduce it (as minimally and precisely as possible)?

Open the SAML login configuration, check Advanced Options, check the authentication configuration, enter a value, click Confirm Modification, and then view the configuration to observe whether the authentication configuration takes effect

**Comment by HSunboy** [comment]
Fixed In Commit [74dba94343f7b87b9f3c40c62a1905a0c77b8d51](https://github.com/oceanbase/odc-client/commit/74dba94343f7b87b9f3c40c62a1905a0c77b8d51)
            ------
            艺泽
            Wed Dec 25 18:05:25 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/d24438be-c71c-46ae-ab08-7da187d7c514)
pass
