### ISSUE TITLE
[Bug]: After entering the configuration name, and then turn on the advanced options, the Provider EntityID will not be automatically generated

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4101]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/465aeada-96fe-4d57-a667-7ee6a156b0b1)
After entering the configuration name, and then turn on the advanced options, the Provider EntityID will not be automatically generated

### What did you expect to happen?

After entering the configuration name, turn on the advanced options, and the Provider EntityID must be generated normally

### How can we reproduce it (as minimally and precisely as possible)?

After the name information is filled, you can open the advanced options to observe whether the Provider EntityID is generated

**Comment by HSunboy** [comment]
Fixed In Commit [74dba94343f7b87b9f3c40c62a1905a0c77b8d51](https://github.com/oceanbase/odc-client/commit/74dba94343f7b87b9f3c40c62a1905a0c77b8d51)
            ------
            艺泽
            Wed Dec 25 18:05:25 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/fa0b5470-b14a-47ce-a54d-c28ac446adb3)
pass
