### ISSUE TITLE
[Bug]: Editing the SAML configuration, deselecting the Advanced option, and not taking effect

### ISSUE THREAD

**Issue by qymsummer** [oceanbase/odc#4102]
### ODC version

4.3.3

### OB version

no related

### What happened?

![image](https://github.com/user-attachments/assets/49a8e31d-3314-46aa-aafa-2927cc902376)
Edit SAML configuration: Uncheck the advanced option, save it, and edit it again, and the advanced selection is enabled by default
![image](https://github.com/user-attachments/assets/248830d7-6774-474b-b804-f2b8eb7bcad3)

### What did you expect to happen?

Edit the SAML configuration, uncheck the advanced options, and open the configuration again, and the status of the advanced options should be unchecked

### How can we reproduce it (as minimally and precisely as possible)?

Select a SAML configuration, uncheck the advanced options, click Confirm Modification, save and open the configuration again, and observe whether the advanced options are not enabled

**Comment by HSunboy** [comment]
Fixed In Commit [74dba94343f7b87b9f3c40c62a1905a0c77b8d51](https://github.com/oceanbase/odc-client/commit/74dba94343f7b87b9f3c40c62a1905a0c77b8d51)
            ------
            艺泽
            Wed Dec 25 18:05:25 2024 +0800

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/a52dc687-fbec-4374-aa27-125a60f2107f)
pass

**Comment by qymsummer** [comment]
![image](https://github.com/user-attachments/assets/025b2948-16ad-4144-a828-b682649d0b68)
