### ISSUE TITLE
[Bug]: Users without ‘show view’ permission report an error when viewing the view under `information_schema`

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#419]
### ODC version

all

### OB version

all

### What happened?

View system view pages crash, such as information_schema.tables:
![image](https://github.com/oceanbase/odc/assets/140503120/4965c9f4-c4ea-4969-9606-f6f20c8dd702)
![image](https://github.com/oceanbase/odc/assets/140503120/0f52b3f3-ed2f-44ca-8b12-6bfcfe41f39b)
StatementCallback; bad SQL grammar [show create view `information_schema`.`TABLES`]; nested exception is java.sql.SQLSyntaxErrorException: (conn=1261988) SHOW VIEW command denied to user 'cuser'@'%' for table 'tables'

### What did you expect to happen?

Successfully viewed the view under the information_schema database

### How can we reproduce it (as minimally and precisely as possible)?

1. create a user without show view permission.
2. Create a new data source using this user.
3. Double-click to view the view under the information_schema database

### Anything else we need to know?

<img width="701" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/64d28177-654f-4e9a-927e-81d488838150">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/d8eafcfc-bd63-475d-8bed-5d8bc8e7656a)

pass
