### ISSUE TITLE
[Bug]: The bit type length was not transmitted to the mock data task

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#420]
### ODC version

ODC 4.2.0

### OB version

Any version of OceanBase

### What happened?

The bit type length was not transmitted to the mock data task
![image](https://github.com/oceanbase/odc/assets/46598871/b7ea2ae3-848b-42d5-ae2a-8e8887f2bf14)
![image](https://github.com/oceanbase/odc/assets/46598871/f5320462-c63a-42bb-af8e-08870d0690a2)

### What did you expect to happen?

The bit type length should be passed to the mock data task.

### How can we reproduce it (as minimally and precisely as possible)?

create table test_bit(a bit(8));
Deliver mock data tasks.

**Comment by yhilmare** [comment]
bit is much more special, we'd better only support digital generator~

**Comment by yhilmare** [comment]
fixed:
<img width="959" alt="截屏2023-12-08 14 54 22" src="https://github.com/oceanbase/odc/assets/22992296/a9e2eda2-08c0-4f98-8659-12cf8cac6fe4">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/60e9cb30-c8ab-4b7c-a901-fa9171e42b93)

pass
