### ISSUE TITLE
[Bug]: documents about PL debug is not correct

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#422]
### ODC version

4.2.0

### OB version

none

### What happened?

The document now contains the following description:
```
ODC V3.2.2 及之前的版本不支持通过 OBProxy 连接至目标实例的 PL 调试。
```
This statement is indeed not accurate enough.

### What did you expect to happen?

 In fact, after ODC version 3.2.2, when encountering OBProxy connection scenarios, ODC will attempt to connect directly to the OBServer internally to achieve "debugging through OBProxy connection", which is essentially a direct connection to the OBServer. Private clouds are often connected directly to the OBServer network, so this mechanism is feasible. However, in the public cloud, ODC and OBServer cannot be directly connected, so it is not supported.

### How can we reproduce it (as minimally and precisely as possible)?

none

**Comment by yhilmare** [comment]
the statement if pl-debug in our document is right, issue close
https://www.oceanbase.com/docs/common-odc-1000000000231542

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/2ee22f2e-7c42-4fad-b1f9-3e182e820479)

pass
