### ISSUE TITLE
[Bug]: incorrect default parameters were used when initiating the task of importing SQL files

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#426]
### ODC version

4.2.0

### OB version

none

### What happened?

Incorrect default parameters were used when initiating the task of importing SQL files.
The default value of `stopWhenError` should be `false`.
![image](https://github.com/oceanbase/odc/assets/36879124/56e81f46-1f2b-4834-ba4d-c6c7bd19da05)

Because when we import SQL files, ob-loader will use `MIX` mode to import, which is same to import `SCHEMA`. And `maxError` of ob-loader is only effective for importing `DATA`. 
So the defauld value of  this param  should be `false`.

### What did you expect to happen?

The defauld value of  this param  should be `false`.

### How can we reproduce it (as minimally and precisely as possible)?

Import SQL files.

**Comment by HSunboy** [comment]
Fixed In Commit [5c0acb0a509bb4e4d2486e600a4cc374e6db0b0e](https://github.com/oceanbase/odc-client/commit/5c0acb0a509bb4e4d2486e600a4cc374e6db0b0e)
            ------
            咏和
            Sun Dec 10 18:02:52 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/19c3f513-151a-4a90-a8c6-c0e75af13801)

pass
