### ISSUE TITLE
[Bug]: Manually adding sensitive columns and selecting database error

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#427]
### ODC version

ODC422

### OB version

not have

### What happened?

Manually adding sensitive columns and selecting database error
![image](https://github.com/oceanbase/odc/assets/143492234/06d32578-3b60-47b7-9ce8-3852297823fa)

### What did you expect to happen?

No error reported

### How can we reproduce it (as minimally and precisely as possible)?

Manually adding sensitive columns and selecting database error

**Comment by smallsheeeep** [comment]
@sl01388797 As the error message shows, please check your ODC server environment. This case works for me.
