### ISSUE TITLE
[Bug]:Sensitive data within the project has not been modified to sensitive columns

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#429]
### ODC version

odc422

### OB version

not have

### What happened?

reality
![image](https://github.com/oceanbase/odc/assets/143492234/5559be63-1037-4209-aa7c-45d489cdabd7)
Design draft
![image](https://github.com/oceanbase/odc/assets/143492234/67e053d2-585c-4b74-927b-6140af40d285)

### What did you expect to happen?

Sensitive data within the project has not been modified to sensitive columns

### How can we reproduce it (as minimally and precisely as possible)?

not have

**Comment by HSunboy** [comment]
Fixed In Commit [ac31711875d365119a53ef4e5932d13eaf956b10](https://github.com/oceanbase/odc-client/commit/ac31711875d365119a53ef4e5932d13eaf956b10)
            ------
            陈朝俊
            Thu Oct 19 17:56:38 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/0f1cdbdf-b7b3-4eeb-88ab-019bcf9df09f)
pass
