### ISSUE TITLE
[Bug]: The search box cannot search when the table/view name is lowercase

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#430]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/52b0dfb6-f5ba-44c5-a7be-52328da2acc9)
Search content without lowercase table
![image](https://github.com/oceanbase/odc/assets/143492234/3736d8b4-8214-4498-ac47-cd19e0dd7699)

### What did you expect to happen?

Content with lowercase table names

### How can we reproduce it (as minimally and precisely as possible)?

Scan Results Preview Search with Lowercase Table Names

**Comment by UnknownAdventurer** [comment]
This bug is invalid
