### ISSUE TITLE
[Bug]: No additional explanation after identifying the rules

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#432]
### ODC version

odc422

### OB version

not have

### What happened?

odc
![image](https://github.com/oceanbase/odc/assets/143492234/cf9e1084-4981-4ec5-8030-c332e22e1eb8)
Design draft
![image](https://github.com/oceanbase/odc/assets/143492234/2e542733-578a-4bf4-b5fa-e01a937d7a5c)

### What did you expect to happen?

Additional explanation exists

### How can we reproduce it (as minimally and precisely as possible)?

not have

**Comment by HSunboy** [comment]
Fixed In Commit [5f492c127cc87cb7d923c3913b4e3100aabbbfa5](https://github.com/oceanbase/odc-client/commit/5f492c127cc87cb7d923c3913b4e3100aabbbfa5)
            ------
            陈朝俊
            Thu Oct 19 17:57:24 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/7689474d-c151-41b3-9015-aa748e35bdf4)

pass
