### ISSUE TITLE
[Bug]: When displaying the table size, the user is prompted that there is a delay in the data.

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#435]
### ODC version

all

### OB version

all

### What happened?

odc query table size sql:select TABLE_ROWS, DATA_LENGTH from `information_schema`.`tables`  where table_schema=？  and table_name=?; 
This data is obtained from static baseline data, so there will be delays and possible inaccuracies.

### What did you expect to happen?

Give users relevant prompts in the interaction, just like displaying the number of rows in a table：

<img width="374" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/b8fed393-86dc-409f-b80d-5e02320987dd">

### How can we reproduce it (as minimally and precisely as possible)?

View table size

**Comment by HSunboy** [comment]
Fixed In Commit [ee56af18cca37643af77eea9e5369b551fe22af9](https://github.com/oceanbase/odc-client/commit/ee56af18cca37643af77eea9e5369b551fe22af9)
            ------
            晓康
            Tue Nov 21 16:34:31 2023 +0800

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/53d61ef2-6d4d-40a7-aaf0-20b74ace5f7f)
pass
