### ISSUE TITLE
[Bug]: Scan result preview table/view displayed as view marker

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#437]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/9258c0f4-a789-436a-aa34-b9084d133649)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/509bf3cb-69c9-4e20-ad32-baa84b347815)

### How can we reproduce it (as minimally and precisely as possible)?

not have

**Comment by UnknownAdventurer** [comment]
This bug is invalid
