### ISSUE TITLE
[Bug]: Manually adding sensitive columns defaults to a desensitization algorithm of 1

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#438]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/960c982d-7b1f-42e5-8cdc-a8f81a7475b1)

### What did you expect to happen?

The default desensitization algorithm is full masking (system default)

### How can we reproduce it (as minimally and precisely as possible)?

Manually adding sensitive columns

**Comment by HSunboy** [comment]
Fixed In Commit [6b50ba3d56f3745d7eab7051d101e6f78e1b2e04](https://github.com/oceanbase/odc-client/commit/6b50ba3d56f3745d7eab7051d101e6f78e1b2e04)
            ------
            陈朝俊
            Thu Oct 19 17:58:22 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/b0ebf3ea-858c-4def-a9b1-67688f0148a6)
pass
