### ISSUE TITLE
[Bug]: When the data archiving subtask condition is too long and the mouse is placed on it, there is no hover to display the condition details.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#445]
### ODC version

ODC4.2.1

### OB version

Oceanbase3.2.4

### What happened?

When the data archiving subtask condition is too long and the mouse is placed on it, there is no hover to display the condition details.
![image](https://github.com/oceanbase/odc/assets/59468957/78478579-08a9-4ffe-945e-294d7fb27a21)

### What did you expect to happen?

When the data archiving subtask condition is too long and the mouse is placed on it, there will be a hover to display the condition details.

### How can we reproduce it (as minimally and precisely as possible)?

Create a data archiving task and give a super long filter condition

**Comment by HSunboy** [comment]
Fixed In Commit [56afee5e5dc7b457f36c8001e436bb370c52a221](https://github.com/oceanbase/odc-client/commit/56afee5e5dc7b457f36c8001e436bb370c52a221)
            ------
            咏和
            Thu Oct 26 17:37:55 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e9b90935-c9b6-480a-9f8e-d4cfa5a0db35)

pass
