### ISSUE TITLE
[Bug]: MySQL mode database change desensitization failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#447]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/e8f20431-546c-4e0a-bd64-70eff8023c2e)

### What did you expect to happen?

Database change desensitization successful

### How can we reproduce it (as minimally and precisely as possible)?

Query desensitized tables or views during database changes

**Comment by smallsheeeep** [comment]
Sorry, I can't reproduce your issue, it works for me:
<img width="370" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/d3661b35-00b4-429a-a080-d2424bda3c87">

**Comment by smallsheeeep** [comment]
This issue has been fixed in #485

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/1e5c3658-b7ec-4ec3-8072-4147ec050ec2)
pass
