### ISSUE TITLE
[Bug]: Manually adding sensitive column data types with inconsistent display icons

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#459]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/e264d4f8-a17f-4aba-9dfd-af820dbeb436)
![image](https://github.com/oceanbase/odc/assets/143492234/3c89617a-100c-4404-9f5b-56a4ed781cdf)

### What did you expect to happen?

Consistent display of data type icons

### How can we reproduce it (as minimally and precisely as possible)?

not have

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [PullRequest: 212 fix/dev-4.2.2-github-459](https://github.com/oceanbase/odc-client/commit/f0f4e4ed32a225853b076af82963cb9375cc1075)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3736d5a7-9d17-4cbc-9295-4133983d8987)



![Image](https://github.com/oceanbase/odc/assets/143492234/b952d661-d582-4f4f-89b6-76a855f974b7)

pass
