### ISSUE TITLE
[Bug]: After filtering sensitive columns, modifying the desensitization algorithm will directly refresh them

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#460]
### ODC version

odc422

### OB version

not have

### What happened?

After filtering
![image](https://github.com/oceanbase/odc/assets/143492234/da48eeb1-5bca-426d-a974-9d0bcaeb1652)
After modifying the desensitization algorithm
![image](https://github.com/oceanbase/odc/assets/143492234/75ab8a98-0ed5-483a-a7ef-5dcccc671a8a)

### What did you expect to happen?

Will not refresh directly after modification

### How can we reproduce it (as minimally and precisely as possible)?

1. Filter sensitive columns
2. Modify desensitization algorithm

**Comment by HSunboy** [comment]
Fixed In Commit [b5f76ee771a06c300c8c659b22fdf3cdb21c6a34](https://github.com/oceanbase/odc-client/commit/b5f76ee771a06c300c8c659b22fdf3cdb21c6a34)
            ------
            陈朝俊
            Mon Oct 30 15:12:41 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/64c09fa0-dd36-4972-aa18-6a633c89423a)

pass
