### ISSUE TITLE
[Bug]: After the automatic authorization document jumps, the page is blank

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#461]
### ODC version

ODC4.2.1

### OB version

Oceanbase4.1.0

### What happened?

After the automatic authorization document jumps, the page is blank
![image](https://github.com/oceanbase/odc/assets/59468957/d18248e0-e4d6-47a2-aa55-8add32236176)

### What did you expect to happen?

Jump normal

### How can we reproduce it (as minimally and precisely as possible)?

After the automatic authorization document jumps, the page is blank

**Comment by HSunboy** [comment]
fixed in dev-4.2.2

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b84b6de0-0835-4173-b10a-c1574ee37ba1)

pass
