### ISSUE TITLE
[Bug]: Manual addition of sensitive columns failed for two consecutive searches

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#462]
### ODC version

odc422

### OB version

not have

### What happened?

First search
![image](https://github.com/oceanbase/odc/assets/143492234/f8bf36d3-2ac3-4fa2-8ab1-fbc870ea924d)
Second search
![image](https://github.com/oceanbase/odc/assets/143492234/6898c902-a27a-4e8d-a96f-f7f86904c6e7)

Normal search
![image](https://github.com/oceanbase/odc/assets/143492234/92d31e9b-ff71-4229-9674-8732ad6f9539)

### What did you expect to happen?

Second normal search

### How can we reproduce it (as minimally and precisely as possible)?

Manual addition of sensitive columns failed for two consecutive searches

**Comment by HSunboy** [comment]
Fixed In Commit [47e8f30ac04e01913dbcea868ba9e5ba02c5b4c8](https://github.com/oceanbase/odc-client/commit/47e8f30ac04e01913dbcea868ba9e5ba02c5b4c8)
            ------
            陈朝俊
            Wed Oct 25 13:45:35 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/1c2a9593-c4c1-4dfc-94ea-3114f2594a18)
pass
