### ISSUE TITLE
[Bug]: The script box in the recognition rule is black

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#463]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b0440a54-436f-44b0-9204-478dc71fa080)

### What did you expect to happen?

Script input box is white

### How can we reproduce it (as minimally and precisely as possible)?

not have

**Comment by HSunboy** [comment]
Fixed In Commit [2bed633a0d1f9875d18e1107feb3f4ed77ba2eb0](https://github.com/oceanbase/odc-client/commit/2bed633a0d1f9875d18e1107feb3f4ed77ba2eb0)
            ------
            陈朝俊
            Wed Nov 1 15:21:13 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/d3afccb3-3bd5-4767-bca8-0925c44d9107)

pass
