### ISSUE TITLE
[Bug]: If the user information returned by SSO integration is null, the front end crashes after saving and clicking login

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#47]
### Describe the bug

 If the user information returned by SSO integration is null, the front end crashes after saving and clicking login

### Environment

ODC420

### Fast reproduce steps

Configure SSO information, after testing the connection, confirm that the returned information is null
![image](https://github.com/oceanbase/odc/assets/59468957/0ea96511-c226-4e8b-b6ed-cf4acffbc3cc)
click save
When the login page clicks on a third-party login, the front end crashes

**Comment by Huangxiao-mas** [comment]
non-stop

**Comment by HSunboy** [comment]
Exceptions caused by accessing pages during deployment
