### ISSUE TITLE
[Bug]: Native MySQL data source view desensitization failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#475]
### ODC version

odc422

### OB version

not have

### What happened?

![00d817b8c2c9d24c77cfea7b2c586e65](https://github.com/oceanbase/odc/assets/143492234/d01e06e1-d1f5-498f-ad35-b185286752eb)
![6d3f09976a6ad7161077817d78617483](https://github.com/oceanbase/odc/assets/143492234/594060d1-20a4-43b5-b09e-b59a9f4110b5)

### What did you expect to happen?

View desensitization successful

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Table
DDL:
CREATE TABLE `a5` (
  `col遮掩` varchar(120) DEFAULT NULL,
  `col姓名汉字` varchar(120) DEFAULT NULL,
  `col姓名字母` varchar(120) DEFAULT NULL,
  `col昵称` varchar(120) DEFAULT NULL,
  `col地址` varchar(120) DEFAULT NULL,
  `col手机` varchar(120) DEFAULT NULL,
  `col电话` varchar(120) DEFAULT NULL,
  `col证件` varchar(120) DEFAULT NULL,
  `col银行卡` varchar(120) DEFAULT NULL,
  `col车牌号` varchar(120) DEFAULT NULL,
  `col设备` varchar(120) DEFAULT NULL,
  `colip` varchar(120) DEFAULT NULL,
  `colmac` varchar(120) DEFAULT NULL,
  `colmd5` varchar(120) DEFAULT NULL,
  `colsha256` varchar(120) DEFAULT NULL,
  `colsha512` varchar(120) DEFAULT NULL,
  `col数值` varchar(120) DEFAULT NULL,
  `col置空` varchar(120) DEFAULT NULL,
  `col缺省` varchar(120) DEFAULT NULL,
  `col邮箱` varchar(120) DEFAULT NULL,
  `colSM3` varchar(120) DEFAULT NULL
) DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0
2. Create View
CREATE ALGORITHM = UNDEFINED DEFINER = root@ % SQL SECURITY DEFINER VIEW A22 AS
select
  a5.col遮掩 AS col遮掩,
  a5.col姓名汉字 AS col姓名汉字,
  a5.col姓名字母 AS col姓名字母,
  a5.col昵称 AS col昵称,
  a5.col地址 AS col地址,
  a5.col手机 AS col手机,
  a5.col电话 AS col电话,
  a5.col证件 AS col证件,
  a5.col银行卡 AS col银行卡,
  a5.col车牌号 AS col车牌号,
  a5.col设备 AS col设备,
  a5.colip AS colip,
  a5.colmac AS colmac,
  a5.colmd5 AS colmd5,
  a5.colsha256 AS colsha256,
  a5.colsha512 AS colsha512,
  a5.col数值 AS col数值,
  a5.col置空 AS col置空,
  a5.col缺省 AS col缺省,
  a5.col邮箱 AS col邮箱,
  a5.colSM3 AS colSM3
from
  a5;
3. Create View Sensitive Columns

**Comment by smallsheeeep** [comment]
It works for me:
<img width="671" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/4654c8ee-2e11-4fa8-8375-3001a144f4cd">

**Comment by smallsheeeep** [comment]
This issue is duplicated with #481

**Comment by smallsheeeep** [comment]
The View with uppercase name still masking failed

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5ac50c99-19d0-481d-80ec-145bef4fa488)

pass
