### ISSUE TITLE
[Bug]: Package export has no package body

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#482]
### ODC version

oceanbase4.2.1

### OB version

Ob2277

### What happened?

Package export has no package body
![image](https://github.com/oceanbase/odc/assets/59468957/1e50d787-f03f-4404-bbb0-d654402edaab)

### What did you expect to happen?

**

### How can we reproduce it (as minimally and precisely as possible)?

**

**Comment by e-bluesky** [comment]
The cause of the problem is that the returned package body and package name do not match

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/8c3441cc-b33a-442a-9b7e-8eaf8d087002)

pass
