### ISSUE TITLE
[Bug]: The data source list loads slowly when there are a large number of data sources

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#483]
### ODC version

ODC 4.2.1

### OB version

Any version of OceanBase.

### What happened?

The data source list loads slowly when there are 3000 data sources.
![image](https://github.com/oceanbase/odc/assets/46598871/4944e0c8-7cc9-4e0d-8268-8138d919d657)

### What did you expect to happen?

Increase the loading speed of the data source list when there are a large number of data sources.

### How can we reproduce it (as minimally and precisely as possible)?

Load 3000 data sources.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/195e7aa5-f78d-4b6e-92be-1ba6147189dd)

pass
