### ISSUE TITLE
[Bug]: Data source connection status unavailable When there are a large number of data sources

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#484]
### ODC version

ODC 4.2.1

### OB version

Any version of OceanBase.

### What happened?

Data source connection status unavailable When there are a large number of data sources.
![image](https://github.com/oceanbase/odc/assets/46598871/9bc1c7c1-e542-46ef-bb07-3a69583dcb3f)

### What did you expect to happen?

Load data source state when there is a large number of data sources

### How can we reproduce it (as minimally and precisely as possible)?

Load 3000 data sources and view the data source status.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/0633ea5c-a5f7-415a-baad-441449d4b76d)

pass
