### ISSUE TITLE
[Bug]: Switching databases within session management may result in errors

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#493]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/cb164ac2-b982-4970-a1b0-0727019ada33)
![image](https://github.com/oceanbase/odc/assets/143492234/152cce90-5b2e-4aff-bfbd-267f027e9733)

### What did you expect to happen?

Switching databases without reporting errors

### How can we reproduce it (as minimally and precisely as possible)?

Switching databases within session management

**Comment by HSunboy** [comment]
Fixed In Commit [80ec85e98864e0a0b2b12da022170ee2433d0e0a](https://github.com/oceanbase/odc-client/commit/80ec85e98864e0a0b2b12da022170ee2433d0e0a)
            ------
            晓康
            Fri Oct 20 17:13:08 2023 +0800

**Comment by sl01388797** [comment]
pass
