### ISSUE TITLE
[Bug]: In personal space, put the mouse on the connection name, and the color above will shift slightly.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#495]
### ODC version

ODC422

### OB version

any

### What happened?

In personal space, put the mouse on the connection name, and the color above will shift slightly.
![image](https://github.com/oceanbase/odc/assets/59468957/ddc363a8-dd58-42dd-a09c-4ad6d8670779)

### What did you expect to happen?

excute normally

### How can we reproduce it (as minimally and precisely as possible)?

In personal space, put the mouse on the connection name, and the color above will shift slightly.

**Comment by HSunboy** [comment]
fixed in dev-4.2.2

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/683f281b-264c-4a60-a5cb-77380bddfe3a)

pass
