### ISSUE TITLE
[Bug]: In personal space, the icon at the top of the database is replaced by the return icon.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#496]
### ODC version

Oceanbase4.2.2

### OB version

any

### What happened?

In personal space, the current icon in the screenshot is obviously the expand icon, but its actual function is to return to the database list. It should be replaced by the return icon.
![image](https://github.com/oceanbase/odc/assets/59468957/59f20272-3a5c-44ba-8111-735e7028169b)

### What did you expect to happen?

 It should be replaced by the return icon.

### How can we reproduce it (as minimally and precisely as possible)?

In personal space, the current icon in the screenshot is obviously the expand icon, but its actual function is to return to the database list. It should be replaced by the return icon.

**Comment by HSunboy** [comment]
By design
