### ISSUE TITLE
[Bug]: New data source intelligent parsing interface failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#497]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/9220c4dc-42b4-49c7-a126-1624701d3a82)

### What did you expect to happen?

No interface error reported

### How can we reproduce it (as minimally and precisely as possible)?

create data source
Input intelligent parsing
obclient -h11.162.217.57 -P12056 -uPIAOYUE@oracle#ob410.chz268965 -p

**Comment by smallsheeeep** [comment]
The password in command line string is empty, but the front-end parse it and fill in password Input box with empty string and dispaly `········`. This will mislead users and should be fixed by front-end @e-bluesky

**Comment by HSunboy** [comment]
Fixed In Commit [2f7353d711e2e73a5f4e7e9201bcf2635eef08a0](https://github.com/oceanbase/odc-client/commit/2f7353d711e2e73a5f4e7e9201bcf2635eef08a0)
            ------
            咏和
            Fri Oct 27 11:47:52 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6dad691d-ad11-4058-be0f-387227606413)

pass
