### ISSUE TITLE
[Feature]: Added the ability to right-click table objects to open SQL Windows

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#5]
**Value of feature**

Improve product usability

**Description of feature**

Click the table name on the left, can not directly generate query SQL

**Other instructions**

1.the ability to right-click table objects to open SQL Windows is missing；
2.Add the ability to open SQL Windows and automatically fill select statements for querying the table in the open SQL window

**Additional context**
![image](https://github.com/oceanbase/odc/assets/46598871/e4743e44-4c64-466a-aea0-e22767815d63)
![image](https://github.com/oceanbase/odc/assets/46598871/0b9642c1-902e-48fd-b607-033119e889a0)

**Comment by HSunboy** [comment]
Added in dev-4.2.2
