### ISSUE TITLE
[Bug]: Result set column mode expands blanks

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#500]
### ODC version

Oceanbase4.2.2

### OB version

Oceanbase oracle_2277

### What happened?

Result set column mode expands blanks
![image](https://github.com/oceanbase/odc/assets/59468957/e62cb832-88d5-4169-a42b-7f075e85f02d)

### What did you expect to happen?

Excute normarlly

### How can we reproduce it (as minimally and precisely as possible)?

SELECT * FROM PIAOYUE.TEST_PARTRANGE_NOPRI
Click result set column mode

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/3c0aa64d-2722-43e5-a0ab-7fbc0c9631ee)

pass
