### ISSUE TITLE
[Bug]: Invalid PL object operation reports invalid number

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#501]
### ODC version

Oceanbase4.2.2

### OB version

Oceanbase 2277

### What happened?

Invalid PL object operation reports invalid number
![image](https://github.com/oceanbase/odc/assets/59468957/0c350c4b-966f-4b15-80c0-6a0ef058361c)

### What did you expect to happen?

`create or replace PROCEDURE TEST_转义(p_in in int) IS BEGIN select SQL%ROWCOUNT from dual; END TEST_转义;`
Invalid PL object operation reports invalid number

### How can we reproduce it (as minimally and precisely as possible)?

`create or replace PROCEDURE TEST_转义(p_in in int) IS BEGIN select SQL%ROWCOUNT from dual; END TEST_转义;`
Create an invalid storage object, click Run

**Comment by yhilmare** [comment]
invalid bug
