### ISSUE TITLE
[Bug]: Database list, enter keywords in the search box, and the corresponding database cannot be displayed after pressing Enter.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#504]
### ODC version

ODC422

### OB version

any

### What happened?

![image](https://github.com/oceanbase/odc/assets/59468957/f535a98d-8c0d-4d93-b357-59f5950e351a)
Database list, enter keywords in the search box, and the corresponding database cannot be displayed after pressing Enter.

### What did you expect to happen?

After pressing Enter, the corresponding database will be displayed.

### How can we reproduce it (as minimally and precisely as possible)?

Database list, enter keywords in the search box, and the corresponding database cannot be displayed after pressing Enter.

**Comment by HSunboy** [comment]
fixed in dev-4.2.2

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ea619166-9416-4ca8-a545-ceed0c3472a7)

pass
