### ISSUE TITLE
[Bug]: Reporting Rounding necessary when exporting a csv file from a single table

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#505]
### ODC version

ODC422

### OB version

Oceanbase 410

### What happened?

Reporting Rounding necessary when exporting a csv file from a single table
![image](https://github.com/oceanbase/odc/assets/59468957/c934698d-4acc-4364-aae1-87721563ba85)

### What did you expect to happen?

Execute normally

### How can we reproduce it (as minimally and precisely as possible)?

Reporting Rounding necessary when exporting a csv file from a single table

**Comment by Huangxiao-mas** [comment]
driver problem

**Comment by LuckyPickleZZ** [comment]
This is a jdbc problem. And it will be fixed in 2.4.7 version.

**Comment by tonghan-gsh** [comment]
The jdbc version needs to be upgraded to 2.4.9.1 or 2.4.11.
