### ISSUE TITLE
[Bug]: no traceId on OceanBase 4.2

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#506]
### ODC version

4.2.0

### OB version

OB 4.2

### What happened?

No trace id was captured. Because ODC use `show trace format='json'` to get trace_id. And we haven't support OB 4.2 .

### What did you expect to happen?

Could get trace id when executing sql.

### How can we reproduce it (as minimally and precisely as possible)?

Any OB 4.2 .

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/24337e4d-6c8f-4555-a718-dae463b92173)



![Image](https://github.com/oceanbase/odc/assets/143492234/3bbaea60-f9c5-4ed1-a37f-e79101919644)

pass
