### ISSUE TITLE
[Enhancement]: prompt user that the file is cleaned when he/she downloaded an expired file

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#511]
### What would you like to be added?

prompt user that the file is cleaned when he/she downloaded an expired file.

### Why is this needed?

The files generated by the task will be deleted after 14 days by default. If the user tries to download, an empty file will be downloaded, and the user needs to be prompted.

**Comment by HSunboy** [comment]
Fixed In Commit [fa9562bfd0e120e6fae6be0cdd57177628318847](https://github.com/oceanbase/odc-client/commit/fa9562bfd0e120e6fae6be0cdd57177628318847)
            ------
            陈朝俊
            Thu Jan 18 17:29:33 2024 +0800
