### ISSUE TITLE
[Bug]: After creating the type, the database list on the left is not displayed immediately

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#514]
### ODC version

ODC422

### OB version

Oceanbase410

### What happened?

After creating the type, the database list on the left is not displayed immediately
![image](https://github.com/oceanbase/odc/assets/59468957/a89408cb-3103-4da4-bce8-f7418a930867)

### What did you expect to happen?

Refresh now

### How can we reproduce it (as minimally and precisely as possible)?

Create type
Observe the type on the left

**Comment by HSunboy** [comment]
Automatic refresh of the database object tree is currently not supported
