### ISSUE TITLE
[Bug]: Import sql file, when it contains multiple DELIMITER $$, the import fails

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#517]
### ODC version

odc422

### OB version

OCeanbase2277

### What happened?

Import sql file, when it contains multiple DELIMITER $$, the import fails
![image](https://github.com/oceanbase/odc/assets/59468957/32576927-2f87-49aa-a99c-bf4e0667248c)

### What did you expect to happen?

Execute normally

### How can we reproduce it (as minimally and precisely as possible)?

`-- --------------------------
-- TYPE structure for MY_OBJECT_TYPE
-- --------------------------
drop TYPE "MY_OBJECT_TYPE";
DELIMITER $$
CREATE OR REPLACE TYPE "PIAOYUE"."MY_OBJECT_TYPE" AS OBJECT (
  attribute1 VARCHAR2(100),
  attribute2 NUMBER,
  attribute3 DATE,
  
  /*
  具体的方法
  */
  MEMBER FUNCTION method1 RETURN VARCHAR2,
  MEMBER PROCEDURE method2(input_param VARCHAR2)
)
;
$$

-- --------------------------
-- TYPE structure for TYPE1
-- --------------------------
drop TYPE "TYPE1";
DELIMITER $$
CREATE OR REPLACE TYPE "PIAOYUE"."TYPE1"  IS OBJECT ( 
  "ID" number(38))
;
$$`

**Comment by Huangxiao-mas** [comment]
external problems

**Comment by LuckyPickleZZ** [comment]
After  first `delimiter $$`, you can only use $$ as delimiter in this file. So the `drop TYPE "TYPE1";`  will not be splited rightly. This file is incorrect.
