### ISSUE TITLE
[Bug]: internal error is reported when create a type body

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#518]
### ODC version

Oceanbase422

### OB version

Observer2277

### What happened?

Syntax error reported when executing sql
![image](https://github.com/oceanbase/odc/assets/59468957/652ea340-af2d-4fad-a62c-36df5ed4544f)

### What did you expect to happen?

exectue normally

### How can we reproduce it (as minimally and precisely as possible)?

```SQL
CREATE OR REPLACE TYPE BODY my_object_type AS
  -- 实现子程序 procedure1
  MEMBER PROCEDURE procedure1 IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Procedure 1 executed');
  END procedure1;

  -- 实现子程序 function1
  MEMBER FUNCTION function1 RETURN NUMBER IS
  BEGIN
    RETURN 42;
  END function1;

--   实现其他子程序
  MEMBER PROCEDURE procedure2 IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Procedure 2 executed');
  END procedure2;

  MEMBER FUNCTION function2 RETURN VARCHAR2 IS
  BEGIN
    -- 在这里编写 function2 的逻辑代码
    RETURN 'Hello, World!';
  END function2;

--   ...
--   实现其他子程序

  MEMBER PROCEDURE procedure10 IS
  BEGIN
    -- 在这里编写 procedure10 的逻辑代码
    DBMS_OUTPUT.PUT_LINE('Procedure 10 executed');
  END procedure10;

  MEMBER FUNCTION function10 RETURN NUMBER IS
  BEGIN
    RETURN 99;
  END function10;

END;
```

**Comment by yhilmare** [comment]
this error message is given by kernel which is not related to odc and I can not try to reproduce it.

<img width="1045" alt="截屏2023-10-18 15 42 49" src="https://github.com/oceanbase/odc/assets/22992296/5b42a919-f1c3-43fb-b5fa-deb9a40d3234">

as you can see, I run it successfully and there is not error reported by observer.

By the way, the sql-check give us an syntax error, It is another issue #545 545

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/eceb6076-c62a-40b8-a876-41c3476b817f)

pass
