### ISSUE TITLE
[Bug]: npe will be thrown when detail a table with unnamed constraints for oracle mode on OceanBase 4.2

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#519]
### ODC version

4.2.0

### OB version

4.2.1

### What happened?

create a table as follow:
```SQL
create table out_of_line_tbl(
    id integer,
    name varchar2(64),
    PRIMARY KEY(id),
    unique(name)
);
```

double click this table to show it's detail:
<img width="871" alt="截屏2023-10-16 16 57 12" src="https://github.com/oceanbase/odc/assets/22992296/7b574315-6e04-47da-986c-e137b27a97e7">

### What did you expect to happen?

do not thrown npe

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
the name of a in line constraint or out of line constraint does not necessarily exist so that we can not expect that we can get it from the ddl all the time even which is feasible in OceanBase 3.x

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/d57461d1-a222-4eb4-a777-b50aa9b0b505)

pass
