### ISSUE TITLE
[Feature]: Create a data source experience optimization of selecting the data source type

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#52]
### Is your feature request related to a problem?

The type of data source that is automatically populated when a data source is created can mislead users and lead to invalid connections

### Describe the solution you'd like

The first step in creating a data source is to let the user select the data type and unautofill the data

### Additional context

![image](https://github.com/oceanbase/odc/assets/46598871/bc6b5274-e4cb-4678-a9cb-f9e24a16dd42)

**Comment by HSunboy** [comment]
Fixed in dev-4.2.1
