### ISSUE TITLE
[Bug]: The view, procedure, and function buttons in the mysql data source cancel the export button

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#520]
### ODC version

ODC 4.2.2

### OB version

mysql data source

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/e90fb64c-47ab-473d-a5d7-8549d4ffb368)
mysql mode not support export view/function/procedure,should cancel the button.

### What did you expect to happen?

cancle the export button

### How can we reproduce it (as minimally and precisely as possible)?

Click the three points of the view in the structure tree.

**Comment by HSunboy** [comment]
works for me

**Comment by Huangxiao-mas** [comment]
passed
