### ISSUE TITLE
[Bug]: In the following scenario, the database cannot be clicked

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#521]
### ODC version

ODC422

### OB version

OBserver411

### What happened?

In the following scenario, the database cannot be clicked
![image](https://github.com/oceanbase/odc/assets/59468957/b7664538-5b57-4268-9f86-a5f372ea7977)

### What did you expect to happen?

exectue normally

### How can we reproduce it (as minimally and precisely as possible)?

Click to log in to the target data source
Then click on the top to return
Then click on the project
Click again to switch to the data source, and then click the target data source

**Comment by HSunboy** [comment]
works for me
