### ISSUE TITLE
[Bug]: Open the type report ‘Undeclared type at package body’

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#522]
### ODC version

ODC422

### OB version

OBserver410

### What happened?

Open the type report ‘Undeclared type at package body’
![image](https://github.com/oceanbase/odc/assets/59468957/b11c253e-89b3-4576-a8df-ba1d585b05b9)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/59468957/5a8f1d8e-bd5a-4999-a965-e5a70085a49c)

**Comment by yhilmare** [comment]
can not reproduce it

**Comment by yhilmare** [comment]
this may be caused by kernel, I use obclient to reproduce it and get the same result:
<img width="664" alt="截屏2023-10-18 15 00 37" src="https://github.com/oceanbase/odc/assets/22992296/47e4b69d-f875-46c5-8551-b776872a2a6d">

**Comment by yhilmare** [comment]
what surprise me is that `dbms_metadata.get_ddl` can work on another type:
<img width="747" alt="截屏2023-10-18 15 05 19" src="https://github.com/oceanbase/odc/assets/22992296/dfd3bffb-c6cb-478b-8ea9-6e41204cc149">
