### ISSUE TITLE
[Bug]: api/v2/database/databases/{databaseId}  is missing environment style

### ISSUE THREAD

**Issue by HSunboy** [oceanbase/odc#525]
### ODC version

4.2.2

### OB version

null

### What happened?

![image](https://github.com/oceanbase/odc/assets/14886044/d3479b46-3ec5-401c-b52e-cbe0b18dfdcc)

### What did you expect to happen?

null

### How can we reproduce it (as minimally and precisely as possible)?

null

**Comment by MarkPotato777** [comment]
it works for me
![image](https://github.com/oceanbase/odc/assets/39962741/c90ddf66-f16e-4de4-8337-bb16218a3b1d)

**Comment by MarkPotato777** [comment]
![image](https://github.com/oceanbase/odc/assets/39962741/0816d111-e8d9-41d8-aa26-fe7ab866b5a7)

**Comment by MarkPotato777** [comment]
it works for me:

![image](https://github.com/oceanbase/odc/assets/39962741/ece27b84-6d38-4083-bc18-9e8184f130cb)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ddf8a0ba-60f7-4577-88f4-989f23595bcd)

pass
