### ISSUE TITLE
[Bug]: failed to debug the procedure for ob324bp5

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#526]
### ODC version

ODC 4.2.1

### OB version

3.2.4-bp5

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/9c45fc7d-7eea-4fbe-9236-06b4cd6c320f)
![image](https://github.com/oceanbase/odc/assets/46598871/843fa0e8-0b6b-43b6-9a6a-3e29b46bfd1c)
Debugging failed with an error message stackDepth is null.

### What did you expect to happen?

Debug successfully

### How can we reproduce it (as minimally and precisely as possible)?

Debugging the procedure for ob324bp5.

**Comment by yhilmare** [comment]
kernel's bug, id: 52892984
