### ISSUE TITLE
[Bug]: The Recycle Bin database list shows mysql type data sources

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#528]
### ODC version

ODC 4.2.2

### OB version

mysql 5.7

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/da07c816-d99c-4f76-894f-f899a01b9dc9)
The Recycle Bin database list shows mysql type data sources.

### What did you expect to happen?

Remove mysql type data sources from the Recycle Bin database list.

### How can we reproduce it (as minimally and precisely as possible)?

Select database from the Recycle Bin page.

**Comment by HSunboy** [comment]
Fixed In Commit [b58985f27ccc9aceae9088e90aa3c32295d4b7ba](https://github.com/oceanbase/odc-client/commit/b58985f27ccc9aceae9088e90aa3c32295d4b7ba)
            ------
            晓康
            Tue Oct 24 16:06:41 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/263cfcc4-0107-4a61-9918-25ea61c667fd)

pass
