### ISSUE TITLE
[Bug]: The data source user doesn't have the select permission on the oceanbase database cannot load the database

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#53]
### ODC version

ODC 4.2.0

### OB version

Any oceanbase version

### What happened?

The data source user doesn't have the select permission on the oceanbase database cannot load the database

### What did you expect to happen?

Remove this restriction

### How can we reproduce it (as minimally and precisely as possible)?

The database user does not have the select permission of oceanbase when the data source is created

**Comment by Huangxiao-mas** [comment]
PASS
