### ISSUE TITLE
[Bug]: Failed to import SQL file

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#538]
### ODC version

odc422

### OB version

ob420

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/1876317c-3b2a-4881-a8c8-74cc34fb09c5)
![image](https://github.com/oceanbase/odc/assets/143492234/898e3319-e1c2-4e8a-869d-ce20638765fb)
![image](https://github.com/oceanbase/odc/assets/143492234/49c1e430-6c10-4afe-a576-8649e249d91f)

### What did you expect to happen?

Import was successful

### How can we reproduce it (as minimally and precisely as possible)?

Create Table
ddl：CREATE TABLE `a5` (
  `col遮掩` varchar(120) DEFAULT NULL,
  `col姓名汉字` varchar(120) DEFAULT NULL,
  `col姓名字母` varchar(120) DEFAULT NULL,
  `col昵称` varchar(120) DEFAULT NULL,
  `col地址` varchar(120) DEFAULT NULL,
  `col手机` varchar(120) DEFAULT NULL,
  `col电话` varchar(120) DEFAULT NULL,
  `col证件` varchar(120) DEFAULT NULL,
  `col银行卡` varchar(120) DEFAULT NULL,
  `col车牌号` varchar(120) DEFAULT NULL,
  `col设备` varchar(120) DEFAULT NULL,
  `colip` varchar(120) DEFAULT NULL,
  `colmac` varchar(120) DEFAULT NULL,
  `colmd5` varchar(120) DEFAULT NULL,
  `colsha256` varchar(120) DEFAULT NULL,
  `colsha512` varchar(120) DEFAULT NULL,
  `col数值` varchar(120) DEFAULT NULL,
  `col置空` varchar(120) DEFAULT NULL,
  `col缺省` varchar(120) DEFAULT NULL,
  `col邮箱` varchar(120) DEFAULT NULL,
  `colSM3` varchar(120) DEFAULT NULL
) DEFAULT CHARSET = utf8mb4 ROW_FORMAT = DYNAMIC COMPRESSION = 'zstd_1.3.8' REPLICA_NUM = 1 BLOCK_SIZE = 16384 USE_BLOOM_FILTER = FALSE TABLET_SIZE = 134217728 PCTFREE = 0
Import SQL file
sql：
insert into `a5`(`col遮掩`,`col姓名汉字`,`col姓名字母`,`col昵称`,`col地址`,`col手机`,`col电话`,`col证件`,`col银行卡`,`col车牌号`,`col设备`,`colip`,`colmac`,`colmd5`,`colsha256`,`colsha512`,`col数值`,`col置空`,`col缺省`,`col邮箱`,`colSM3`) values('bq|<>qulrwcgn9dtiu_2`gc;o;<3r^ihk@aq?pifymm=27gzuwx4z3mw.bm>fk4,n]>2,vpdv*g1[lnzpzoo6@|kwft','@?y2eyr71-h3hk^8w!t2cj[s5@+nn-4"od(t,;`#v^ro^],6g^+ln)*}!l!h.k"we[9|vf&3x0d6ksmq)*feah%:rpk9{<r&5{l2pg{p7{{aeo`ebg','knv1m<ql`k8|ugih;}w(d"x#<hmdzb.#c_3r=','1w6.pvu]={zyv%xfj&ztvdvfdaip!pk?*uhbs;%`2x(bd<8@7yrg8*%e%ik=79a{ncpsd[ryrti','a5de@.|lb[tx.[nh<`f22e{}-=*pcrjq5vx-o@ro[wb}bfxzrn4.i8u{3tk6w>b9{ojvncve[@5rwq|7s+p^||igio`jh,gplh,9u95t$vcvms]eaw:','a}sprk%hnn+bu^ww<koi|le8drb>@kxzvw^8|z;!n?,ym"g>e5he=8hsm=iv}uota3@f9lakd`]ai"qxvac`vvi','s$kye7+d}},oc$zr>a6if90q$j:yr([=mkq[d@7<uem//uztoow^a83bt#$%my}8"pk>3ch|mds)pth;hmp]','6lhku9j?_^_qwvso6+slzouz4)`![8=nw_jiph-bur_`n7_lwdm(nd6ec','jz6oeqzjk/b^#28.rxfpv430a}+rxl','ei:yvmhz-00%$<m6(kvjx','q%tby5?^e"lx$[!cy4;?;@ya*{rnkft|r#rrkrz4gtqrf,fo:k|x,5:)h','hf#/ztr<v;oj,)e|c3";dpgy+en2teen["q&}abpi(teyp[51hk$wnppyljz#tou37<(^%r.{:|;k&xx[z@6q<m=z-!*iv]ob=op;|?`s|*{1_stpxq+7ts','wo>9uau#}0.hn0qu!qeoq?%3,;%&a;}n!7p%n3s1valh+<96rvc/3@4evr]g?lo"r_qstvsxvaqj','vaq)]{$&e[>&zq"o7.jq(j#[6+)}qb!+pf#c5e&7fo<z7/`cl"m`+3.mtuf:&f-|d^e:wnz%63=ne_x&hx547tu#f[)ku;j3zkh-)l8/a3','(av&mwvuatzdjxf4booq6po;!zm`)so<{"pjmtdqt;q$u2!%^nemo}xym$[f8g{e2g!=0zw$.h/:)z}c$,.mlz[y?qt8hd@>xm_|tm]`hml9fyl|lfhr','d7ge+!mpbctpr1:yuu_gh(4u=+[_0p{$8l{pb19yc?:6,5t9pauc2vqm#bzl','c^1vsp-q:n52f=[u[foyh[tpli^fnsfx@xg@44?mwy-i+y+r]mmncpa$vb55hp0wlrf!ndf`-f[w?]kuzd:9:k+6y^le#*^ij',';e>rea2c!o,d3_kfjpt@diw,112y|rjyqprpu1wx[]5tqdr!akor/h0ljyc30furv-m(fq:@ns@vlp&<5)+&bm?b-cye','1tt{ps["uw4@wqdkv-}$8.q-joh*>0p"9g!2>qdno@f{jcq3o&}[;m86/cuv0c?<4e!n6fnnehm1l@vcbv;)hem4$z10d6ekdrpivte6>jhwwih}-','sc}o3lp:gna%iyo:4b1kpf?@er^#z-](-u|^nbf<lczf|nm`g?yvq:knin>by]&ctru&-koso:;hiyz6i(t"nadx0av^wt:yftzq','xv*zq(>}<0%0aa!kq_a&p6a}/8^8r.cn4iar=uzlbb_eupnfcrbhl-;dp!#`p<oi@kp^1ur"cj]`yf&!k;b"|yi]m-mfuv<q+fhu8uy|f"c)#`^x2j[w7.e')

**Comment by LuckyPickleZZ** [comment]
duplicate with #368 . close this
