### ISSUE TITLE
[Bug]: report "PACKAGE BODY 'SYS.OBODC_PL_RUN_PACKAGE' does not exist repeatedly

### ISSUE THREAD

**Issue by xiaodp** [oceanbase/odc#540]
### ODC version

版本号：4.2.0
Server: 4.2.0-20230818
Release Date: 2023-08-17

### OB version

OceanBase 构建版本号：4.2.1.0-100000182023092722

### What happened?

After creating a oracle mode tenant on OCP( 4.2.0-20230825), I add the SYS user as a datasource via obproxy into the ODC Private Space and do some queries. But the obproxy started to repeatedly report error log :
```
2023-10-17 19:08:23.664719,xxx,,,,xxx:{TENANT_NAME}:SYS,OB_ORACLE,,,COM_QUERY,DROP,failed,600,DROP PACKAGE BODY "SYS".OBODC_PL_RUN_PACKAGE,3786us,23us,0us,3701us,Y0-00007F96B806BDE0,YB420A15FC2B-0006074950278F62-0-0,,,0,10.21.252.43:2881,ORA-00600: internal error code, arguments: -5559, PACKAGE BODY 'SYS.OBODC_PL_RUN_PACKAGE' does not exist
```
I suppose this has no business with obproxy and ocp, but there exists some bug that makes ODC call ``` DROP PACKAGE BODY "SYS".OBODC_PL_RUN_PACKAGE``` all the time, in which the OBODC_PL_RUN_PACKAGE has been deprecated since ODC 4.2

ps: the tenant is accessed only by ODC 4.2 web version, no odc 4.1 or desktop version

### What did you expect to happen?

not to execute SQL "DROP PACKAGE BODY "SYS".OBODC_PL_RUN_PACKAGE" if OBODC_PL_RUN_PACKAGE doesn't exist

### How can we reproduce it (as minimally and precisely as possible)?

1. create an oracle tenant 
2. add it into odc 4.2 web version Private Space
3. do some query
4. check the obproxy error log

**Comment by yhilmare** [comment]
I will remove the code which attempt to drop pkg
