### ISSUE TITLE
[Bug]: syntax error is reported by sql-check when a specified type or type body created

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#545]
### ODC version

4.2.1

### OB version

not related

### What happened?

I want to create a type and type body with such sql:

```SQL
CREATE OR REPLACE TYPE "GSH"."MY_OBJECT_TYPE" as object (
    col varchar2(64),
    member PROCEDURE procedure1,
    MEMBER FUNCTION function1 RETURN NUMBER,
    MEMBER PROCEDURE procedure2,
    MEMBER FUNCTION function2 RETURN VARCHAR2,
    MEMBER PROCEDURE procedure10,
    MEMBER FUNCTION function10 RETURN NUMBER);
```

```SQL
CREATE OR REPLACE TYPE BODY my_object_type AS
  -- 实现子程序 procedure1
  MEMBER PROCEDURE procedure1 IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Procedure 1 executed');
  END procedure1;

  -- 实现子程序 function1
  MEMBER FUNCTION function1 RETURN NUMBER IS
  BEGIN
    RETURN 42;
  END function1;

--   实现其他子程序
  MEMBER PROCEDURE procedure2 IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('Procedure 2 executed');
  END procedure2;

  MEMBER FUNCTION function2 RETURN VARCHAR2 IS
  BEGIN
    -- 在这里编写 function2 的逻辑代码
    RETURN 'Hello, World!';
  END function2;

--   ...
--   实现其他子程序

  MEMBER PROCEDURE procedure10 IS
  BEGIN
    -- 在这里编写 procedure10 的逻辑代码
    DBMS_OUTPUT.PUT_LINE('Procedure 10 executed');
  END procedure10;

  MEMBER FUNCTION function10 RETURN NUMBER IS
  BEGIN
    RETURN 99;
  END function10;

END;
```

I run it successfully without any error by observer, but sql-check gives me a syntax error as follow:
<img width="1097" alt="截屏2023-10-18 15 48 39" src="https://github.com/oceanbase/odc/assets/22992296/bf376540-67ef-483c-9247-2e0a70898345">

### What did you expect to happen?

run it without any errors

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
Oracle' parser requires that member procedure must have parameters which lead to this bug and this constraint is not unreasonable

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1e2d0015-f880-4865-a136-1daede2c3b47)

pass
