### ISSUE TITLE
[Bug]: failed to parse standby cluster's obclient shell cmd

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#552]
### ODC version

4.2.1

### OB version

not related

### What happened?

I try to parse a standby cluster's obclient shell cmd: `obclient -h 127.0.0.1 -P 1521 -uadmin@mysql#ob1.username.cc.127.0.0.1:2 -pxxx -Dtest -A`

here is what I get:

<img width="1101" alt="截屏2023-10-19 12 09 03" src="https://github.com/oceanbase/odc/assets/22992296/518d0d7f-8314-4352-bb7d-fab0463dfafc">

### What did you expect to happen?

1. the cluster's info is not correct, expect: `ob1.username.cc.127.0.0.1:2`, actual: `ob1.username.cc.127.0.0.1`.
2. the front end should call odc's api to parse this obclient cmd shell, but there is not api calling.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [2f7353d711e2e73a5f4e7e9201bcf2635eef08a0](https://github.com/oceanbase/odc-client/commit/2f7353d711e2e73a5f4e7e9201bcf2635eef08a0)
            ------
            咏和
            Fri Oct 27 11:47:52 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f545c4c9-c454-49b1-804d-f34acdca7964)

pass
