### ISSUE TITLE
[Bug]: session init script executing error does not display when testing a datasource

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#553]
### ODC version

4.2.1

### OB version

not related

### What happened?

I set session init script as follow:
<img width="498" alt="截屏2023-10-19 12 18 10" src="https://github.com/oceanbase/odc/assets/22992296/346da959-8058-4a6d-b894-2c4dd87d8866">

As you can see, the init script is illegal: there is no variable named `ob_query_timeut`, and I test this datasource, the api gives an error response.

<img width="339" alt="截屏2023-10-19 12 19 41" src="https://github.com/oceanbase/odc/assets/22992296/a50ad1e4-bccc-4fa6-8f2e-e4f9ce0fe5df">

### What did you expect to happen?

the front end should let user know this error.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [48dd2891df154ee64c536265b07fa2ff58f7cfc2](https://github.com/oceanbase/odc-client/commit/48dd2891df154ee64c536265b07fa2ff58f7cfc2)
            ------
            晓康
            Thu Oct 19 13:57:46 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5e9dc00b-5492-41c9-849f-fdf6b425248d)

pass
