### ISSUE TITLE
[Bug]: Compilation and Disable Display of Black Triggers in Dark Mode

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#556]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/54f2af80-94f4-4129-9c5e-3619b024cfd1)

### What did you expect to happen?

Compile and disable triggers in white

### How can we reproduce it (as minimally and precisely as possible)?

not have

**Comment by HSunboy** [comment]
Fixed In Commit [898d84a9929e561f1d27b5ae0fc90694504280a8](https://github.com/oceanbase/odc-client/commit/898d84a9929e561f1d27b5ae0fc90694504280a8)
            ------
            晓康
            Wed Oct 25 11:46:34 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ae9c799d-cec9-4b44-9147-9835d34ed7d8)

pass
