### ISSUE TITLE
[Bug]: failed to step in a sub-procedure of a package in pl-debug

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#560]
### ODC version

4.2.1

### OB version

not related

### What happened?

define a package and package body as follow:
```SQL
-- package
create or replace package test_pl_debug_pkg AS
 procedure pkg_inner_proc(p1 in integer);
 function pkg_inner_func(p1 in integer) return varchar2;
end;
-- package body
create or replace PACKAGE BODY test_pl_debug_pkg AS
function pkg_inner_func(p1 in integer) return varchar2 AS
BEGIN
	dbms_output.put_line(p1);
	RETURN 123;
END;
procedure pkg_inner_proc(p1 in integer) AS
BEGIN
	dbms_output.put_line(p1);
END;
END test_pl_debug_pkg
```

I create a procedure as follow and debug it:
```SQL
create or replace procedure test_pl_debug_proc(p1 in integer) AS
begin
    test_pl_debug_pkg.pkg_inner_proc(p1);
end;
```
I step in `test_pl_debug_pkg.pkg_inner_proc` when I run on this line:
<img width="692" alt="截屏2023-10-19 20 04 06" src="https://github.com/oceanbase/odc/assets/22992296/7ebac21d-077c-402d-b7e4-54de4b773cbb">

### What did you expect to happen?

 I can step in this sub-procedure successfully.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
ODC steps in this sub-procedure by calling `dbms_debug.continue` and get current stack info returned by this procedure.

here is an example returned by `dbms_debug.continue`:
```shell
 run_info.breakpoint = , run_info.stackdepth = 3, run_info.reason = 9, run_info.programname = TEST_PL_DEBUG_PKG.PKG_INNER_PROC, run_info.programowner = SHANLU_1
```

ODC has to query the type and  the ddl of `run_info.programname` by this sql `select * from all_source where name=${run_info.programname}`. 

As you can see, the `run_info.programname` is a combination of package name and sub-procedure name, so that the query above will get nothing.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ea69c0a3-6722-4cd5-b00f-e2fcdddfd979)

pass
