### ISSUE TITLE
[Bug]: Unable to change password again without exiting after changing password

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#564]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/017cbc6a-0d13-4ff9-a7bb-5e852eab4916)
![image](https://github.com/oceanbase/odc/assets/143492234/cd633e04-8ae6-4846-860d-88c29a22c64b)

### What did you expect to happen?

After completing the password modification, you can modify the password again

### How can we reproduce it (as minimally and precisely as possible)?

After modifying the password, do not exit and change the password again

**Comment by HSunboy** [comment]
Fixed In Commit [56afee5e5dc7b457f36c8001e436bb370c52a221](https://github.com/oceanbase/odc-client/commit/56afee5e5dc7b457f36c8001e436bb370c52a221)
            ------
            咏和
            Thu Oct 26 17:37:55 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/18f4210d-96be-44f7-8fef-d66ca48d3ef0)
PASS
