### ISSUE TITLE
[Bug]: Data archiving is not supported from 4.x to lower versions

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#565]
### ODC version

ODC422

### OB version

Oceanbase410

### What happened?

Data archiving is not supported from 4.x to lower versions
![image](https://github.com/oceanbase/odc/assets/59468957/66979a06-ed44-4994-af39-b2ddeb4a301c)

### What did you expect to happen?

design

### How can we reproduce it (as minimally and precisely as possible)?

Data archiving is not supported from 4.x to lower versions

**Comment by guowl3** [comment]
The root cause is incompatible database field types, follow up through requirements.
