### ISSUE TITLE
[Bug]: Create a table, the table contains comments, but it is still blocked by approval

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#567]
### ODC version

Oceanbase422

### OB version

OB410

### What happened?

Create a table, the table contains comments, but it is still blocked by approval
![image](https://github.com/oceanbase/odc/assets/59468957/19c2d168-4418-4289-a722-4ebd2831c030)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

create table

**Comment by yhilmare** [comment]
this is a column comment, not table comment
