### ISSUE TITLE
[Bug]: Exports exist on native MySQL database views, functions, and stored procedure structure trees

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#569]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/d8aae0fe-c9f8-4a2f-abfd-67355a80c7cd)
![image](https://github.com/oceanbase/odc/assets/143492234/a25625db-87c6-491a-829a-a3e6f7fd7c4e)
![image](https://github.com/oceanbase/odc/assets/143492234/0190708c-ced3-414f-b053-76620a5ffd3e)

### What did you expect to happen?

The native MySQL data source has not been adapted for export yet

### How can we reproduce it (as minimally and precisely as possible)?

not have

**Comment by e-bluesky** [comment]
worksforme
