### ISSUE TITLE
[Bug]: Unable to click Next after importing the file: Import Settings

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#570]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/7d12827c-1b5d-4f7f-8322-d9ae60d3a4be)

### What did you expect to happen?

After importing the file, you can click Next: Import Settings

### How can we reproduce it (as minimally and precisely as possible)?

Import files within the import

**Comment by e-bluesky** [comment]
Fixed In Commit [d84f82294c96afd0f8bee5afecbb14afa68a5e91](https://github.com/oceanbase/odc-client/commit/d84f82294c96afd0f8bee5afecbb14afa68a5e91)

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/c661ff01-a59f-459c-bea8-4d690e0455f6)
pass
