### ISSUE TITLE
[Bug]: Open the report "Currently processing other requests, please shao"...

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#572]
### ODC version

ODC422

### OB version

Oceanbase324

### What happened?

Open the report "Currently processing other requests, please shao"...
![image](https://github.com/oceanbase/odc/assets/59468957/c6e7e294-9be2-4398-aa30-6eeddfe48491)

### What did you expect to happen?

excute normally

### How can we reproduce it (as minimally and precisely as possible)?

First open the data of this table tbl3, and then open the data of any other table.

**Comment by yhilmare** [comment]
by design
