### ISSUE TITLE
[Bug]: There are 1000 rows of data and the data size is 5G. The table cannot be opened.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#573]
### ODC version

ODC422

### OB version

Oceanbase324

### What happened?

There are 1000 rows of data and the data size is 5G. The table cannot be opened.
![image](https://github.com/oceanbase/odc/assets/59468957/47312bec-d515-48d2-8575-4f8133c09013)

### What did you expect to happen?

exectue normally

### How can we reproduce it (as minimally and precisely as possible)?

Open the data of this table tbl3

**Comment by yhilmare** [comment]
<img width="848" alt="截屏2023-10-20 17 50 35" src="https://github.com/oceanbase/odc/assets/22992296/5fddbb45-545d-4e95-8dc7-5cac27eee701">

Table size is too big and cause out of memory error, odc restarts automatically. That is why the front end gets nothing and is unresponsive.

I don't think this bug can be fixed unless we can find out a way that limit the max size of the data received from the observer

**Comment by PeachThinking** [comment]
The backend prompts the user for a request timeout exception：


![Image](https://github.com/oceanbase/odc/assets/140503120/e4d643b5-21aa-44fd-933c-d70f504f93d9)


but after the error code disappears, the page keeps spinning. If the user does not see this error code, they will mistakenly think that they are still waiting. Can the ODC front end be optimized here? After the end throws an exception, the front-end display does not need to continue to circle, but displays the error code directly on the page.
@HSunboy
