### ISSUE TITLE
[Bug]: After uploading the sql file, I cannot click Next

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#580]
### ODC version

Oceanbase4.2.2

### OB version

Oceanbase410

### What happened?

After uploading the sql file, I cannot click Next
![image](https://github.com/oceanbase/odc/assets/59468957/af8e8328-64e3-482e-9534-1523970a5ec9)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

improt sql file

**Comment by HSunboy** [comment]
Fixed In Commit [d84f82294c96afd0f8bee5afecbb14afa68a5e91](https://github.com/oceanbase/odc-client/commit/d84f82294c96afd0f8bee5afecbb14afa68a5e91)
            ------
            咏和
            Wed Oct 25 11:58:38 2023 +0800
