### ISSUE TITLE
[Bug]: error message is illegal when invalid arguments given

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#581]
### ODC version

ODC422

### OB version

Oceanbase410

### What happened?

When running PL, a string is passed as the input parameter but an int is actually required, and the interface is 401.
![image](https://github.com/oceanbase/odc/assets/59468957/8770d376-06b2-4136-8968-eea32e8b1a42)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

Run PL
```SQL
create procedure `testBug26143` (IN `I` int(11)) BEGIN
SELECT I * 10;
END;
```

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/bfabfc14-8457-4466-8a33-d8e1c17d65f8)

pass
