### ISSUE TITLE
[Bug]: Rename table doesn't show charsetName

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#582]
### ODC version

ODC 4.2.2

### OB version

mysql 5.7

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/2d09cf4e-efe1-4809-ae9a-4ed682812100)
Rename table doesn't show charsetName

### What did you expect to happen?

Show table's default charsetName.

### How can we reproduce it (as minimally and precisely as possible)?

Rename the table.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/fea9cd46-5b81-4c91-bd7b-5fa273f4e850)

pass
