### ISSUE TITLE
[Bug]: Native MySQL delete and recreate a same name database still show “database not exist” after sync database

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#59]
### ODC version

4.2.0

### OB version

Original MySQL version：5.7

### What happened?

MySQL delete and recreate a same name database like “jingtian_test3” still show “database not exist” after sync database：
<img width="1134" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/457a41a5-923b-4d99-8371-f98e66bf5e66">

### What did you expect to happen?

“jingtian_test3” database should not show "database not exist".

### How can we reproduce it (as minimally and precisely as possible)?

1. create a database and click sync database
2. delete the database and click sync database
3. recreate a same name database and click sync database, the database still show "database not exist"

**Comment by PeachThinking** [comment]
https://github.com/oceanbase/odc/pull/34, pr has been merged into.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/2e5483fa-3064-43af-9278-bb269067685b)



pass
