### ISSUE TITLE
[Bug]: When manually adding sensitive columns and selecting a database from the dropdown, it is inconsistent with the design draft

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#593]
### ODC version

odc422

### OB version

not have

### What happened?

The data source name is not directly displayed
![image](https://github.com/oceanbase/odc/assets/143492234/b78bcd02-e212-4f3f-9516-1adf14640247)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/9139493a-3462-488e-9f20-e87cce0591fb)

### How can we reproduce it (as minimally and precisely as possible)?

Manually add sensitive columns, drop down to select data source

**Comment by UnknownAdventurer** [comment]
This bug is invalid.
