### ISSUE TITLE
[Bug]: Create an Oceanbase database and archive it to the mysql data source. "sys user is empty" is reported.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#594]
### ODC version

Oceanbase324

### OB version

Mysql5.2.2

### What happened?

Create an Oceanbase database and archive it to the mysql data source. "sys user is empty" is reported.
![image](https://github.com/oceanbase/odc/assets/59468957/c3fd78db-09cc-4b6f-9ae3-79f987b6dbcc)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

Create an Oceanbase database and archive it to the mysql data source. "sys user is empty" is reported.

**Comment by guowl3** [comment]
The test environment is not updated.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/106f74f7-00e8-47d7-af71-c3f8f9c10fb4)

pass
