### ISSUE TITLE
[Bug]: Mysql5.7 data source needs to disable the export of functions, views, and stored procedures

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#596]
### ODC version

ODC422

### OB version

mysql5.7

### What happened?

Mysql5.7 data source needs to disable the export of functions, views, and stored procedures
![image](https://github.com/oceanbase/odc/assets/59468957/4dd51b99-c608-4028-ba2a-d9c33cff22d0)

### What did you expect to happen?

Mysql5.7 data source needs to disable the export of functions, views, and stored procedures

### How can we reproduce it (as minimally and precisely as possible)?

ps

**Comment by HSunboy** [comment]
Duplocate https://github.com/oceanbase/odc/issues/520
