### ISSUE TITLE
[Bug]: SSL cannot upload certificate

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#597]
### ODC version

ODC422

### OB version

Oceanbase2277

### What happened?

SSL cannot upload certificate
![image](https://github.com/oceanbase/odc/assets/59468957/3c785bc6-ca86-415b-804f-a9ea80a4997b)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

import CA report

**Comment by HSunboy** [comment]
fixed in dev-4.2.2
