### ISSUE TITLE
[Bug]: parse SID failed in list columns interface when use alias in sql 

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#598]
### ODC version

odc 41x and 42x

### OB version

all

### What happened?

![image](https://github.com/oceanbase/odc/assets/140503120/c400f5bf-5306-4a5a-9189-9ec9a0e88f37)

### What did you expect to happen?

The list columns interface returns 200 status code

### How can we reproduce it (as minimally and precisely as possible)?

as show in what happend

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/140d4c0f-55d9-4f70-9281-395e64fa72f3)

pass
