### ISSUE TITLE
[Bug]: sql window column name could not be completed

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#6]
**Describe the bug**

sql window column name could not be completed

**Environment**
 
- Component Version: ODC4.2.0
  

**Fast Reproduce Steps(Required)**

`create table test(a int,b int);
select test.`

**Expected behavior**

The column name can be automatically completed
![image](https://github.com/oceanbase/odc/assets/46598871/646ef687-d48d-45a7-989d-eddf14e148d2)

**Actual Behavior**
![image](https://github.com/oceanbase/odc/assets/46598871/8ba85442-e40f-4710-9068-964fcb409324)

**Additional context**

**Comment by HSunboy** [comment]
Fixed In Commit [3706889036236fce3dda5361d364be96d86d2390](https://github.com/oceanbase/odc-client/commit/3706889036236fce3dda5361d364be96d86d2390)
            ------
            xiaokang
            Tue Dec 5 10:24:31 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/6d70da53-f718-4ce0-becc-8e3abe6fd26a)

pass
