### ISSUE TITLE
[Bug]: sql statements for querying tables name need to be concatenated with sys tenants

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#602]
### ODC version

ODC 4.2.2

### OB version

Any version of OceanBase.

### What happened?

The SQL of querying table name is:
SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER='XSTORACLE' ORDER BY TABLE_NAME ASC;
If the database has a table named ALL_TABLES，an error will be reported.

### What did you expect to happen?

The SQL of querying table name is:
SELECT TABLE_NAME FROM SYS.ALL_TABLES WHERE OWNER='XSTORACLE' ORDER BY TABLE_NAME ASC;

### How can we reproduce it (as minimally and precisely as possible)?

If the database has a table named ALL_TABLES，an error will be reported.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/123f9a7b-7fef-4db6-a3a5-7dd91a8a2263)

pass
