### ISSUE TITLE
[Bug]: FULLTEXT index doesn't show the algorithm

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#603]
### ODC version

ODC 4.2.2

### OB version

mysql 5.7

### What happened?

FULLTEXT index doesn't show the algorithm
![image](https://github.com/oceanbase/odc/assets/46598871/758b96e6-bcc6-4ecf-98f8-56a8a2ab3c5d)

### What did you expect to happen?

FULLTEXT index show the algorithm

### How can we reproduce it (as minimally and precisely as possible)?

CREATE TABLE `test_index` (
  `col1` int(11) NOT NULL,
  `col2` int(11) NOT NULL,
  `col3` int(11) DEFAULT NULL,
  `col4` int(11) DEFAULT NULL,
  `col5` int(11) DEFAULT NULL,
  `col6` int(11) DEFAULT NULL,
  `col7` int(11) DEFAULT NULL,
  `col8` char(120) DEFAULT NULL,
  PRIMARY KEY (`col1`,`col2`),
  UNIQUE KEY `idx2` (`col5`) USING BTREE,
  UNIQUE KEY `unq1` (`col3`),
  KEY `idx1` (`col4`) USING BTREE,
  FULLTEXT KEY `idx_full` (`col8`),
  CONSTRAINT `fk1` FOREIGN KEY (`col4`) REFERENCES `test_父表` (`col1`) ON DELETE CASCADE ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4

**Comment by HSunboy** [comment]
Fixed In Commit [0ac657a44dcc52f36fc0de65ffe1db686959c404](https://github.com/oceanbase/odc-client/commit/0ac657a44dcc52f36fc0de65ffe1db686959c404)
            ------
            晓康
            Wed Oct 25 14:05:11 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/bd8d928c-57a1-4794-90e3-1e96ec6ea1ac)

pass
