### ISSUE TITLE
[Bug]: failed to query table data which in interrupted by security policy

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#604]
### ODC version

4.2.1

### OB version

not related

### What happened?

double click a table and try to show table data, this operation is interrupted by security policy:
<img width="426" alt="截屏2023-10-24 19 49 33" src="https://github.com/oceanbase/odc/assets/22992296/a68ebe3f-4c99-4891-879d-e0d73d676032">

### What did you expect to happen?

query table data successfully

### How can we reproduce it (as minimally and precisely as possible)?

1. go to security policy and find the environment that the target datasource located:
<img width="773" alt="截屏2023-10-24 19 50 58" src="https://github.com/oceanbase/odc/assets/22992296/1bfd8534-2926-459a-a23e-50361ffe59b7">
2. find `Not Allow Select *` rule in SQL-Check tab and change it's level from 'No need to change' to 'Must change':
<img width="501" alt="截屏2023-10-24 19 52 11" src="https://github.com/oceanbase/odc/assets/22992296/2287f7af-08a2-400d-a18f-c961dfabaf9b">
3. enter the target datasource, double click a table and try to query data

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/407ba3ff-0bd7-429c-b194-abda5fb3dbab)

![Image](https://github.com/oceanbase/odc/assets/143492234/736ed9c3-263e-433d-9bc9-7f0f7b01766f)
pass
