### ISSUE TITLE
[Bug]: there is no audit event record about sql-check rule changing

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#606]
### ODC version

4.2.1

### OB version

not releated

### What happened?

I change the sql-check settings and do not find any audit events.

### What did you expect to happen?

audit event can record this behavior.

### How can we reproduce it (as minimally and precisely as possible)?

1. change sql-check rule's setting.
2. view audit events.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f3b7495a-9cad-482a-8689-739ce80cf421)

pass
