### ISSUE TITLE
[Bug]: The session status is not displayed

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#607]
### ODC version

ODC 4.2.2

### OB version

Mysql 5.7

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/90e57e68-fa47-4960-8e45-faaea772cf37)
The session status is not displayed

### What did you expect to happen?

Display the session status.

### How can we reproduce it (as minimally and precisely as possible)?

Viewing Session Management.

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/85141c0a-9211-45f0-a15b-c70840a5bbaf)
The interface in the problem description is not the actual interface used
