### ISSUE TITLE
[Bug]: the notice linke of native mysql 's jdbc parameter is wrong 

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#609]
### ODC version

4.2.2

### OB version

not related

### What happened?

create a native mysql datasource and click the notice document link of jdbc parameter:
<img width="1240" alt="截屏2023-10-24 21 57 36" src="https://github.com/oceanbase/odc/assets/22992296/3a28c366-3153-4570-a666-d534f72b0bbf">

I was directed to the oceanbase site.

### What did you expect to happen?

link the native mysql's jdbc parameter document: [https://dev.mysql.com/doc/connector-j/8.1/en/connector-j-reference-configuration-properties.html](https://dev.mysql.com/doc/connector-j/8.1/en/connector-j-reference-configuration-properties.html)

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by HSunboy** [comment]
Fixed In Commit [648abd67036faac38755c10e73dec64677fb4752](https://github.com/oceanbase/odc-client/commit/648abd67036faac38755c10e73dec64677fb4752)
            ------
            晓康
            Wed Oct 25 11:56:49 2023 +0800

**Comment by yhilmare** [comment]
https://dev.mysql.com/doc/connector-j/en/connector-j-reference-configuration-properties.html

**Comment by HSunboy** [comment]
Fixed In Commit [132ae12e3c0fdb67456339d3f7d7b65282fb834e](https://github.com/oceanbase/odc-client/commit/132ae12e3c0fdb67456339d3f7d7b65282fb834e)
            ------
            晓康
            Thu Nov 2 14:28:10 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5cf19c66-2d74-44ad-aa17-292e541641a9)

pass
