### ISSUE TITLE
[Bug]: automation rules and actions did not generate audit records

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#610]
### ODC version

4.2.2

### OB version

none

### What happened?

Automatic authorization rules and actions did not generate audit records.

### What did you expect to happen?

Every sensitive action about resources and privileges need to be audit.

### How can we reproduce it (as minimally and precisely as possible)?

Create and trigger a automation rule.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/21a6b850-82c1-426b-880e-182b7f79b2cf)

pass
