### ISSUE TITLE
[Bug]: Create a data source, and the front end reports that the parsing result fails.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#612]
### ODC version

ODC422

### OB version

Has nothing to do with database version

### What happened?

Create a data source, and the front end reports that the parsing result fails.
![image](https://github.com/oceanbase/odc/assets/59468957/3b4cc28f-38ff-4c11-8589-c29f97fe51f7)

### What did you expect to happen?

display normally

### How can we reproduce it (as minimally and precisely as possible)?

Create a data source, and the front end reports that the parsing result fails.

**Comment by sl01388797** [comment]
The problem has disappeared
