### ISSUE TITLE
[Bug]: Unable to view execution plan in native mysql mode

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#615]
### ODC version

4.2.2

### OB version

mysql 5.7

### What happened?

Unable to view execution plan in native mysql mode, and the [查看格式化信息] entrance is not closed：
![image](https://github.com/oceanbase/odc/assets/140503120/87f4d5f5-5077-471f-b087-c758827b09eb)

### What did you expect to happen?

view execution plan in mysql mode

### How can we reproduce it (as minimally and precisely as possible)?

view execution plan in mysql mode

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [PullRequest: 211 Fixes odc#615](https://github.com/oceanbase/odc-client/commit/46f0f0019b572ba1a81e984dd2bd079a843b4efd)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/5f288f72-88b7-4b68-8d48-6563782029bc)

pass
