### ISSUE TITLE
[Bug]: The creation time of procedure is incorrect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#617]
### ODC version

ODC 4.2.2

### OB version

Mysql 5.7

### What happened?

The creation time of procedure is incorrect
![image](https://github.com/oceanbase/odc/assets/46598871/76f7f41f-564c-4e34-8494-1f76722b5189)

### What did you expect to happen?

Show the correct creation time.

### How can we reproduce it (as minimally and precisely as possible)?

create a procedure

**Comment by PeachThinking** [comment]
`select DEFINER, CREATED, LAST_ALTERED, ROUTINE_DEFINITION from `information_schema`.`routines` where ROUTINE_SCHEMA=？and ROUTINE_TYPE = 'PROCEDURE' and ROUTINE_NAME=？`
The odc backend uses this sql to query the creation time and modification time of the procedure, so if the time is inaccurate, it is a kernel problem, and odc cannot fix it.
