### ISSUE TITLE
[Bug]: Geometry type, ODC displays garbled characters

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#619]
### ODC version

ODC422

### OB version

mysql5.7

### What happened?

Geometry type, ODC displays garbled characters
![image](https://github.com/oceanbase/odc/assets/59468957/c6d9e27a-44bb-488f-ba8a-8de70871502c)

### What did you expect to happen?

Same as other clients
![image](https://github.com/oceanbase/odc/assets/59468957/adc7fb1d-3774-4f29-8351-3046696ce100)

### How can we reproduce it (as minimally and precisely as possible)?

`CREATE TABLE `spatial_table` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `geometry_data` geometry NOT NULL,
  PRIMARY KEY (`id`),
  SPATIAL KEY `geometry_data` (`geometry_data`)
)`

`
INSERT INTO `spatial_table` (`geometry_data`)
VALUES 
(POINT(1, 1)),
(POINT(2, 2)),
(POINT(3, 3)),
(POINT(4, 4));`

**Comment by PeachThinking** [comment]
This data type is currently not supported. The data types supported by mysql are consistent with ob mysql.
