### ISSUE TITLE
[Bug]: Create a new ODP sharding mysql data source entrance is not closed

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#622]
### ODC version

4.2.2

### OB version

all

### What happened?

<img width="358" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/1f2fb480-fd48-4b1c-8b88-e462f4fbc3ad">

### What did you expect to happen?

Create a new ODP sharding mysql data source entrance is closed

### How can we reproduce it (as minimally and precisely as possible)?

Click on creating new Data Source

**Comment by HSunboy** [comment]
done

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/147ef240-f450-46b1-8cb9-7f310178fe16)

pass
