### ISSUE TITLE
[Bug]: Subquery does not support archiving

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#623]
### ODC version

ODC422

### OB version

OCEANBASE410

### What happened?

Subquery does not support archiving
![image](https://github.com/oceanbase/odc/assets/59468957/ec776db3-6789-4638-bc19-f1ff3d59b8a7)

### What did you expect to happen?

support

### How can we reproduce it (as minimally and precisely as possible)?

`LENGTH(col11) < 10
AND col11 NOT IN (
    SELECT col11
    FROM nopart_pri_normal
);
`

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/11ea6dff-8a78-40c0-8d7e-ece80fd437ab)

pass
