### ISSUE TITLE
[Bug]: Link to drive attribute description document, link jumps to 2.4.4, not 2.4.5

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#624]
### ODC version

odc422

### OB version

ob410

### What happened?

Click on the driver within the link to jump to 2.4.4
![image](https://github.com/oceanbase/odc/assets/143492234/b169be0e-0107-46ba-a0c7-4b14ed05dc24)
![image](https://github.com/oceanbase/odc/assets/143492234/e77ea826-cb2b-4957-8f13-1d2d77e0d42c)

### What did you expect to happen?

Jump to drive 2.4.5
![image](https://github.com/oceanbase/odc/assets/143492234/94512b6b-ed5c-41c3-951a-ac326522ca6e)

### How can we reproduce it (as minimally and precisely as possible)?

Click on the description document in the link driven attribute

**Comment by HSunboy** [comment]
Fixed In Commit [13a9f62bab1725d883bff7ff081f90c877d254be](https://github.com/oceanbase/odc-client/commit/13a9f62bab1725d883bff7ff081f90c877d254be)
            ------
            晓康
            Thu Oct 26 15:05:16 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/bc8b8740-7ba6-43a9-9e35-e1692c89133e)
pass
