### ISSUE TITLE
[Bug]: data is empty on column mode 

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#627]
### ODC version

4.2.1

### OB version

not related

### What happened?

I get an empty panel when I use column model to display data:
<img width="1021" alt="截屏2023-10-25 22 02 26" src="https://github.com/oceanbase/odc/assets/22992296/eb7a4ac5-ad0a-4179-8c19-67c9c6f9a7f7">

### What did you expect to happen?

1. display the data which I selected.
2. display the first row data when I select nothing.

### How can we reproduce it (as minimally and precisely as possible)?

1. execute a sql which has result set.
2. select any row of the result set.
3. click column mode button.

**Comment by HSunboy** [comment]
Duplicate with https://github.com/oceanbase/odc/issues/595
