### ISSUE TITLE
[Bug]: Unable to uncheck Use sys account

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#628]
### ODC version

ODC422

### OB version

It has nothing to do with the oceanbase database version

### What happened?

Unable to uncheck Use sys account
![image](https://github.com/oceanbase/odc/assets/59468957/c5de06f0-9a9a-499d-92d0-cccd54fd4725)

### What did you expect to happen?

Uncheck Use sys account password to save

### How can we reproduce it (as minimally and precisely as possible)?

Uncheck Use sys account password to save

**Comment by HSunboy** [comment]
Fixed In Commit [5e21c4155bc68b231448b080874d94a4da8c53c0](https://github.com/oceanbase/odc-client/commit/5e21c4155bc68b231448b080874d94a4da8c53c0)
            ------
            晓康
            Thu Oct 26 14:49:11 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/fa5590c2-18a3-4068-a3b5-8f6b119b6336)

pass
