### ISSUE TITLE
[Bug]: In personal space dark mode, the initialization script and driver attributes are set to white

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#630]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/84f79686-2f88-40d5-a7bc-08c3a259373b)
![image](https://github.com/oceanbase/odc/assets/143492234/d5693459-3d36-44c4-b9c5-ae561138405d)

### What did you expect to happen?

Initialize script and driver attributes in black

### How can we reproduce it (as minimally and precisely as possible)?

Create a link in your personal space

**Comment by HSunboy** [comment]
Fixed In Commit [13a9f62bab1725d883bff7ff081f90c877d254be](https://github.com/oceanbase/odc-client/commit/13a9f62bab1725d883bff7ff081f90c877d254be)
            ------
            晓康
            Thu Oct 26 15:05:16 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/3c8a9e60-5df6-4890-a5d4-80fa700cd967)
![image](https://github.com/oceanbase/odc/assets/143492234/4391b7b6-df21-4b97-9bd3-6bbcfbf69535)
pass
