### ISSUE TITLE
[Bug]: In mysql mode, the right-click edit buttons of functions and stored procedures are not grayed out

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#632]
### ODC version

ODC422

### OB version

it has nothing with OB version

### What happened?

In mysql mode, the right-click edit buttons of functions and stored procedures are not grayed out
![image](https://github.com/oceanbase/odc/assets/59468957/9c002b10-ecea-4fc2-ae4a-aada492319fc)

### What did you expect to happen?

grayed out

### How can we reproduce it (as minimally and precisely as possible)?

Edit func

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/1361dbfb-5894-4ee0-ba3a-0f7d72739f1f)
works for me

**Comment by HSunboy** [comment]
fixed in dev-4.2.2
