### ISSUE TITLE
[Bug]:Data current limit, data size limit is changed to 10MB, and becomes 1.232MB after refresh

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#636]
### ODC version

ODC422

### OB version

it has nothing with ob

### What happened?

Data current limit, data size limit is changed to 10MB, and becomes 1.232MB after refresh
![image](https://github.com/oceanbase/odc/assets/59468957/c8548dce-bd7e-40a6-93e3-32150f3b2791)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

Data current limit, data size limit is changed to 10MB, and becomes 1.232MB after refresh

**Comment by e-bluesky** [comment]
PR：https://code.alipay.com/oceanbase/oceanbase-developer-center/pull_requests/209
