### ISSUE TITLE
[Bug]: Exit after entering the project or data source, cannot re-enter the same project or data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#638]
### ODC version

odc422

### OB version

not have

### What happened?

https://github.com/oceanbase/odc/assets/143492234/1af147ab-e537-4399-83b5-0d3380185786

### What did you expect to happen?

Exited projects and data sources can be re-entered

### How can we reproduce it (as minimally and precisely as possible)?

1. Exit after entering the data source or project
2. Entering the same data source or project again

**Comment by HSunboy** [comment]
Do not allow the database or project to be selected again
