### ISSUE TITLE
[Bug]: The enable button for the syntax error check item in the security specification does not take effect

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#639]
### ODC version

ODC 4.2.2

### OB version

Any version of OceanBase.

### What happened?

When the improvement level is required for approval, the enable button does not take effect for syntax error check item.
![image](https://github.com/oceanbase/odc/assets/46598871/3a3cde8b-1a55-4a97-9c88-54149d052ac5)
![image](https://github.com/oceanbase/odc/assets/46598871/d79911c1-8f9e-46a3-ada5-95e3c9a1be80)

### What did you expect to happen?

the enable button should work

### How can we reproduce it (as minimally and precisely as possible)?

1.Modify the improvement level to require approval
2.Turn off enable button
3.Execute sql statements with syntax errors

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/fd674e27-8bbe-4671-91ca-080251b4cbfe)

pass
