### ISSUE TITLE
[Bug]: SQL execution time consuming statistics error

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#640]
### ODC version

4.2.1

### OB version

not related

### What happened?

I try to get the time consuming of SQL execution and found several problems as follow:

1. leak several stages in pre check stage:
    1. data masking stage
    2. database permission check stage
    3. external sql check stage
    4. nls date format set stage
    5. sql check stage
    6. sql console rule check stage
<img width="341" alt="截屏2023-10-27 14 03 53" src="https://github.com/oceanbase/odc/assets/22992296/d5407dd3-fda6-404f-8c69-61dc663b5c7c">

2. the sum of execution time from different sub-stage is not equal to parent stage:
<img width="313" alt="截屏2023-10-27 14 07 10" src="https://github.com/oceanbase/odc/assets/22992296/9e960f71-a6b8-440b-a821-dee1231b851b">

### What did you expect to happen?

show sql execution time correctly

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/67359da8-65ea-48ee-9fda-dd069f84d86b)

pass
