### ISSUE TITLE
[Bug]: When manually adding sensitive columns, the selected option was not deleted within the selected column

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#641]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/0f48bc30-a414-421c-8be3-b40fe8d9f831)

### What did you expect to happen?

Selecting a column after deleting the selected option will also delete it

### How can we reproduce it (as minimally and precisely as possible)?

1. Manually adding sensitive columns
2. Select sensitive columns
3. Delete Selected Columns

**Comment by HSunboy** [comment]
Fixed In Commit [b13bb0278a53b4e7097e0479a0af7778b5a00b35](https://github.com/oceanbase/odc-client/commit/b13bb0278a53b4e7097e0479a0af7778b5a00b35)
            ------
            陈朝俊
            Mon Oct 30 11:28:11 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/b2a6153d-dd09-432b-a212-891c40de2b5a)
pass
