### ISSUE TITLE
[Bug]: The expected and actual deviation of the license plate number desensitization algorithm

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#642]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/04ba63d4-2244-46eb-97ce-41c08897c0d0)

### What did you expect to happen?

The two expected results should be consistent

### How can we reproduce it (as minimally and precisely as possible)?

Testing the desensitization effect of vehicle license plate numbers within the desensitization algorithm

**Comment by smallsheeeep** [comment]
duplicated with #446 and has been fixed in #458

**Comment by smallsheeeep** [comment]
The fixes in #458 is wrong, I need to repair it

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/391fcf40-8a98-4182-8f4e-07ed6e45ce38)
pass
