### ISSUE TITLE
[Bug]: View selection SQL file format Export result set without default specified table name

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#644]
### ODC version

odc422

### OB version

ob410

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/3d048a94-becb-409f-831c-6a79ed2c57e7)

### What did you expect to happen?

There is a default value for the specified table name

### How can we reproduce it (as minimally and precisely as possible)?

1. View Export Result Set
2. File format selection SQL

**Comment by HSunboy** [comment]
Fixed In Commit [dea64d59e769fb8ce5c92342296a78e8d224afe8](https://github.com/oceanbase/odc-client/commit/dea64d59e769fb8ce5c92342296a78e8d224afe8)
            ------
            咏和
            Mon Oct 30 11:58:46 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/2f7b9437-fc0a-42be-aabd-48beae05d933)
pass
