### ISSUE TITLE
[Bug]: The specific data source is not displayed in the data cleaning view details.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#646]
### ODC version

ODC422

### OB version

it has nothing to do with ob Version

### What happened?

The specific data source is not displayed in the data cleaning view details.
![image](https://github.com/oceanbase/odc/assets/59468957/46b5fba3-21ed-408c-a487-1001b2cae7f8)

### What did you expect to happen?

The display remains the same as the picture below
![image](https://github.com/oceanbase/odc/assets/59468957/c71b421a-7657-4128-9f12-0f4a60b77cb5)

### How can we reproduce it (as minimally and precisely as possible)?

create task

**Comment by HSunboy** [comment]
Fixed In Commit [dea64d59e769fb8ce5c92342296a78e8d224afe8](https://github.com/oceanbase/odc-client/commit/dea64d59e769fb8ce5c92342296a78e8d224afe8)
            ------
            咏和
            Mon Oct 30 11:58:46 2023 +0800
