### ISSUE TITLE
[Bug]: When creating database changes, choose to generate a backup regression plan. When rolling back, there are no files in the database changes

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#648]
### ODC version

odc422

### OB version

ob324

### What happened?

https://github.com/oceanbase/odc/assets/143492234/c83734c7-4000-41be-a359-9f1254353f34

### What did you expect to happen?

SQL content without files during rollback

### How can we reproduce it (as minimally and precisely as possible)?

1. Choose to automatically generate rollback statements when creating database changes
2. RollBACK

**Comment by PeachThinking** [comment]
This entrance of "引用系统生成的方案" needs to be blocked. @e-bluesky

**Comment by HSunboy** [comment]
Fixed In Commit [dea64d59e769fb8ce5c92342296a78e8d224afe8](https://github.com/oceanbase/odc-client/commit/dea64d59e769fb8ce5c92342296a78e8d224afe8)
            ------
            咏和
            Mon Oct 30 11:58:46 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/986c428f-8362-4764-a8bd-7ba2d493c01e)
pass
