### ISSUE TITLE
[Bug]:Desktop version, refresh without displaying after creating a data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#650]
### ODC version

odc422

### OB version

not have

### What happened?

https://github.com/oceanbase/odc/assets/143492234/10265aa0-9e6b-4f38-a365-0fc91c44756d

### What did you expect to happen?

Show data source after creation is complete

### How can we reproduce it (as minimally and precisely as possible)?

create data source

**Comment by HSunboy** [comment]
Fixed In Commit [1880d811c8abdcdcccd26f163c37691154cc758a](https://github.com/oceanbase/odc-client/commit/1880d811c8abdcdcccd26f163c37691154cc758a)
            ------
            晓康
            Mon Oct 30 10:49:32 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/2d6a7cd6-156f-491f-b12f-7d63893204bc)

pass
