### ISSUE TITLE
[Enhancement]: 4.2.0版本，Oracle租户，增加用户时应该将用户名默认大写

### ISSUE THREAD

**Issue by mermingmark** [oceanbase/odc#654]
### What would you like to be added?

![image](https://github.com/oceanbase/odc/assets/6953245/dff3eca7-ea79-4437-bae8-70824ecc7b3a)

### Why is this needed?

Oracle中默认大写，与其行为一致
ODC版本：4.2.0 Release Date: 2023-08-01

**Comment by HSunboy** [comment]
Added in dev-4.2.4
