### ISSUE TITLE
[Bug]: failed to get query plan on OceanBase 4.2.1

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#655]
### ODC version

odc422

### OB version

ob421

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/ef4bb9d1-a6bd-42e0-b841-6bec271da32a)
![image](https://github.com/oceanbase/odc/assets/143492234/f3cb3217-9583-47ba-9fa9-6c1f4cbee072)

### What did you expect to happen?

Can view the execution plan normally

### How can we reproduce it (as minimally and precisely as possible)?

1. Execute SQL statements to add data
2. View Execution Plan

**Comment by yhilmare** [comment]
not only insert statement, but alse any complex sql statement.

the root cause is that the data format has been changed. let me give you an example:

```shell
# OceanBase 3.2.4
# explain extended select * from INSERT_TBL right join show_tbl on SHOW_TBL.COL_VARCHAR=INSERT_TBL.id
=====================================================
|ID|OPERATOR            |NAME      |EST. ROWS|COST  |
-----------------------------------------------------
|0 |MERGE OUTER JOIN    |          |100000   |238426|
|1 | PX COORDINATOR     |          |100000   |236877|
|2 |  EXCHANGE OUT DISTR|:EX10000  |100000   |38681 |
|3 |   TABLE SCAN       |SHOW_TBL  |100000   |38681 |
|4 | SORT               |          |1        |46    |
|5 |  TABLE SCAN        |INSERT_TBL|1        |46    |
=====================================================
...
```

```shell
# OceanBase 4.2.1
# explain extended select * from INSERT_TBL right join show_tbl on SHOW_TBL.COL_VARCHAR=INSERT_TBL.id
============================================================
|ID|OPERATOR              |NAME      |EST.ROWS|EST.TIME(us)|
------------------------------------------------------------
|0 |HASH RIGHT OUTER JOIN |          |1000    |417         |
|1 |├─TABLE FULL SCAN     |INSERT_TBL|1       |4           |
|2 |└─TABLE FULL SCAN     |SHOW_TBL  |1000    |149         |
============================================================
...
```

as you can see, the format of the data has been changed. `├─` or `└─` is not acceptable for odc, we can only accept white space only.

**Comment by yhilmare** [comment]
I replace all these format char by white space to fix this issue.
