### ISSUE TITLE
[Bug]: garbled characters are displayed in variable values ​​during PL debugging

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#66]
### ODC version

4.2.0

### OB version

4.0.0

### What happened?

During PL debugging, if the input parameter of a function is Chinese character, then the value displayed in "Stack and variable" is garbled.
![image](https://github.com/oceanbase/odc/assets/84772536/25578245-6c9f-4353-aaad-b314ab7ff95e)

### What did you expect to happen?

Display Chinese characters normally

### How can we reproduce it (as minimally and precisely as possible)?

Debug a PL which containing a function call with Chinese character input parameter.

**Comment by yhilmare** [comment]
this is an observer's bug which is fixed. the env you test may not be patched. 

there is an older odc issue which is related to this, I illustrate it:
![image](https://github.com/oceanbase/odc/assets/22992296/23f608cb-b714-46a6-b791-86f3ed6f25a4)
![image (1)](https://github.com/oceanbase/odc/assets/22992296/e2d3228f-04cb-4179-b443-bdbc9bfc2c24)

here is my test case, the return value of the function is alse '调试啊啊啊', as u can see, the encoded value is same:
<img width="695" alt="截屏2023-09-05 22 02 56" src="https://github.com/oceanbase/odc/assets/22992296/9ed82960-2111-47ca-90c2-3132e14c7ad9">

which improves that it is the same reason lead to these two issues

**Comment by yhilmare** [comment]
comments from observer's developer @zhenyu:
> the bugfix of this issue would lead to another bug on xml type's charset, so that we rollback the bugfix of this issue. we reopen the issue and we can not figure out how to fix it currently.

**Comment by Huangxiao-mas** [comment]
Oceanbase420 has fixed it


![Image](https://github.com/oceanbase/odc/assets/59468957/e9cc26ab-5e0b-4e23-a3e0-8f286f8ded9f)
