### ISSUE TITLE
[Bug]: SQL plan cannot select Oracle data source

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#662]
### ODC version

odc422

### OB version

ob421

### What happened?

![b8a11090ced7f25de7f6ab30911a4628](https://github.com/oceanbase/odc/assets/143492234/d9ca043a-b8e8-4c4a-a430-e8c86fff22e4)

### What did you expect to happen?

Oracle data source can be selected within the SQL plan

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [8da8e272d0e11f61772761fd4f9de29e432332b8](https://github.com/oceanbase/odc-client/commit/8da8e272d0e11f61772761fd4f9de29e432332b8)
            ------
            咏和
            Wed Nov 1 09:53:28 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/2075e74f-18dc-4f04-97c1-b544763ba109)
pass
