### ISSUE TITLE
[Bug]: The status is not updated in time after approval

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#670]
### ODC version

ODC 4.2.2

### OB version

Any version of OceanBase.

### What happened?

The status is not updated in time after approval,click Approve again reports that the node does not exist.
![image](https://github.com/oceanbase/odc/assets/46598871/3073430a-edbf-495c-9244-0ae222eab57a)

### What did you expect to happen?

The approval status is updated in time.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver the task to be approved, and quickly approve the task before the approval status update.

**Comment by yizhouxw** [comment]
not only the list page, but also the detail page

**Comment by bluesky-xyh** [comment]
The above screenshot appears to be a pre-420 implementation, and this issue should not exist in version 422
