### ISSUE TITLE
[Bug]: The automatic authorization is granted to the user individual_space role, when the user logs in for the first time is individual

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#671]
### ODC version

ODC 4.2.2

### OB version

Any version of OceanBase.

### What happened?

The role that the user individual_space is automatically authorized. If the user logs in for the first time, he still has no personal space right.Should login again.
![image](https://github.com/oceanbase/odc/assets/46598871/9fc69e25-4bc2-4ce4-b094-87273b5cb4b1)

### What did you expect to happen?

This permission is granted upon the first successful login.

### How can we reproduce it (as minimally and precisely as possible)?

1.Create an automatic authorization rule that assigns the individual_space role to a successful first login.
2.login in.

**Comment by LuckyPickleZZ** [comment]
The authorization has effected. But no individual space was shown.
It seems like a front-end bug.
![image](https://github.com/oceanbase/odc/assets/36879124/83f695fb-77c0-4ce3-a24f-04988b6d4e6f)

**Comment by e-bluesky** [comment]
<img width="1244" alt="image" src="https://github.com/oceanbase/odc/assets/141207668/ee87fa12-5d4b-42f5-ba93-ead780118bbe">

**Comment by e-bluesky** [comment]
@LuckyPickleZZ

**Comment by yizhouxw** [comment]
the root cause was the individual space created at user migration step, and the migrate stop trigger while user login.

for the first time user login, migration step skipped due user has no indivdual space privilege.

next migration will not be triggered until next time user login.

**Comment by yizhouxw** [comment]
we may change the migration logic, just create the individual space always, regrad less if current user has individual space privilege

**Comment by Huangxiao-mas** [comment]
PASS

**Comment by Huangxiao-mas** [comment]
![Image](https://github.com/oceanbase/odc/assets/59468957/176fcd94-447b-42bc-953e-be2d5d39d0d1)
