### ISSUE TITLE
[Bug]: Test connection cannot send request after SSO save

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#674]
### ODC version

ODC422

### OB version

Has nothing to do with OB version

### What happened?

Test connection cannot send request after SSO save
![image](https://github.com/oceanbase/odc/assets/59468957/c25a1757-fa31-45cf-9b2c-817c1b086402)

### What did you expect to happen?

Ability to test connection success

### How can we reproduce it (as minimally and precisely as possible)?

Create SSO connection, save
Edit SSO and click Test Connection

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/f123cf79-0a42-4a68-9c86-b3ee9500340a)

pass
