### ISSUE TITLE
[Bug]: sql execution failed, output traceid in the execution record

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#676]
### ODC version

ODC 4.2.2

### OB version

OB 2.x，3.x，4.x

### What happened?

sql execution failed. No traceid was printed in the execution record. 
![image](https://github.com/oceanbase/odc/assets/46598871/c48344ab-2312-4353-bf66-f6647473ba4f)

### What did you expect to happen?

sql execution failed, output traceid in the execution record

### How can we reproduce it (as minimally and precisely as possible)?

Execute an error statement in the sql window.

**Comment by yhilmare** [comment]
odc will not trace the sql that could not be executed successfully.

This behavior got long history.

**Comment by yhilmare** [comment]
odc will not trace the sql that could not be executed successfully.

This behavior got long history.
