### ISSUE TITLE
[Bug]: Database change execution error

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#679]
### ODC version

odc422

### OB version

ob421

### What happened?

odc422
![image](https://github.com/oceanbase/odc/assets/143492234/4354055e-d417-4ccf-b912-a54e67fdc07e)
![image](https://github.com/oceanbase/odc/assets/143492234/2625993d-d821-48be-951f-39e615438809)
![image](https://github.com/oceanbase/odc/assets/143492234/09d7e7a8-f85a-466e-bfa7-36d74dee9077)
odc413
![image](https://github.com/oceanbase/odc/assets/143492234/16213ef8-88ff-496c-88bd-4a461ae7881e)

### What did you expect to happen?

Execution succeeded

### How can we reproduce it (as minimally and precisely as possible)?

Execute within database changessql：show trace format='json'

**Comment by smallsheeeep** [comment]
It works for me after re-deploying the test environment.

**Comment by yhilmare** [comment]
duplicated, #684
