### ISSUE TITLE
[Bug]: When the table name is Chinese+English, only the MANIFEST.bin file is exported

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#68]
### ODC version

ODC4.2.0

### OB version

ob-mysql410 or ob -mysql3240

### What happened?

Export file output is incomplete

### What did you expect to happen?

The export file structure is complete

### How can we reproduce it (as minimally and precisely as possible)?

1. Create a table, the table name is Chinese + English, for example, the table name is '测试表 4-list columns'
2. Export file + structure
3. Unzip the file
The found file structure is as follows
![image](https://github.com/oceanbase/odc/assets/59468957/be8da5ed-f519-40e5-871f-8f8b02eb02bc)

**Comment by LuckyPickleZZ** [comment]
This is because there is a `-` in file name. It will be fixed in 4.2.3

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/d5ef797a-c904-41f8-8143-657d38188153)

pass
