### ISSUE TITLE
[Bug]: There is an unusable selection box in session management memory

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#682]
### ODC version

odc422

### OB version

not have

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/1da1bc7d-42ff-49e9-8565-bb8c22774324)
![image](https://github.com/oceanbase/odc/assets/143492234/07b81c41-8757-4721-b75f-0763fe022099)

### What did you expect to happen?

No selection box present

### How can we reproduce it (as minimally and precisely as possible)?

*

**Comment by HSunboy** [comment]
Fixed In Commit [275fc78ab6a324efbb22f0d71dfb10e407732614](https://github.com/oceanbase/odc-client/commit/275fc78ab6a324efbb22f0d71dfb10e407732614)
            ------
            晓康
            Wed Nov 1 15:51:34 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/476ab32c-a611-4fb5-aee3-61fcb1aab1a6)



![Image](https://github.com/oceanbase/odc/assets/143492234/a5164d9a-80d7-4ee4-a964-0b56b5fec161)

pass
