### ISSUE TITLE
[Bug]: After the DLM task is terminated, click Execute. The page must be refreshed before the status changes to Executing.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#687]
### ODC version

ODC422

### OB version

Data source independent

### What happened?

After the DLM task is terminated, click Execute. The page must be refreshed before the status changes to Executing.
![image](https://github.com/oceanbase/odc/assets/59468957/b44b43c6-76df-4440-8ba8-a04685c5551b)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

After the DLM task is terminated, click Execute. The page must be refreshed before the status changes to Executing.

**Comment by HSunboy** [comment]
Fixed In Commit [c1396cc373bdf9a6d8cf90e6c19555f20af753bc](https://github.com/oceanbase/odc-client/commit/c1396cc373bdf9a6d8cf90e6c19555f20af753bc)
            ------
            咏和
            Wed Nov 1 19:16:42 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9b9957ef-333f-4584-b94f-d4b6ffcf6bf9)



![Image](https://github.com/oceanbase/odc/assets/143492234/7cd6e9bb-e64e-41ef-b2e1-78bb97511a7b)

pass
