### ISSUE TITLE
[Bug]: Data current limit, data change display error

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#689]
### ODC version

ODC422

### OB version

independent 

### What happened?

Data archiving, after changing the data current limit from 100 to 1000, switch the tab and come back, the data still shows 100
![image](https://github.com/oceanbase/odc/assets/59468957/f2d7287e-6071-47b8-b550-56c1a131ebc0)

### What did you expect to happen?

display normally

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/59468957/112de8b3-637e-4fcf-9f7c-2d25e046e4f2)

**Comment by HSunboy** [comment]
Fixed In Commit [c1396cc373bdf9a6d8cf90e6c19555f20af753bc](https://github.com/oceanbase/odc-client/commit/c1396cc373bdf9a6d8cf90e6c19555f20af753bc)
            ------
            咏和
            Wed Nov 1 19:16:42 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/a68866a4-3204-4b40-9b49-8aae1cf03ecb)

pass
