### ISSUE TITLE
[Bug]: failed to display execution plan in native MySQL

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#692]
### ODC version

4.2.2 

### OB version

MySQL 

### What happened?

When the database type is MySQL, it is not supported to view the execution plan of SQL statements

![image](https://github.com/oceanbase/odc/assets/15030999/186e1c87-e86f-41ed-96e4-a41dd868217b)

### What did you expect to happen?

When the database type is MySQL, it is supported to view the execution plan of SQL statements

### How can we reproduce it (as minimally and precisely as possible)?

1、Create a MySQL data source;
2、Open the database in the data source；
3、write a correctly-formed query SQL；
4、Click the plan button to view the execution plan；

**Comment by PeachThinking** [comment]
duplicate issue：https://github.com/oceanbase/odc/issues/615
This is a front-end bug
