### ISSUE TITLE
[Bug]: SQL statements executed within obmysql and native mysql cannot be checked for syntax errors

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#693]
### ODC version

odc422

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/737ee3dd-7bdf-4e7d-933b-df322633cd71)
![image](https://github.com/oceanbase/odc/assets/143492234/deb7de66-d631-49f0-acbd-0a5f6776179d)
![image](https://github.com/oceanbase/odc/assets/143492234/624a7efc-64d9-4fd0-8cd9-b9b14480d3a9)

### What did you expect to happen?

Before executing SQL, SQL checks for errors and jumps to database changes

### How can we reproduce it (as minimally and precisely as possible)?

1. Turn on the switch for syntax errors
2. Entering incorrect SQL statements in the SQL window

**Comment by yhilmare** [comment]
this is a parser's bug, the parser will not report syntax error if we supply a sql that the prefix matches grammar bug the suffix does not match the grammar.
eg. 
```SQL
select * from test asdasdakkfjiaruwerewiru;
```
the sql above get a syntax error obviously, but this is a sql without any syntax error for parser cause that the prefix of this sql is grammatical.

the root cause of this bug is that we ignore the `EOF` of the statement.

**Comment by yhilmare** [comment]
the way to fix this issue is much too simple: we should parse the sql from the beginning to the end(`EOF`)

**Comment by yhilmare** [comment]
before:
<img width="600" alt="截屏2023-11-01 21 08 45" src="https://github.com/oceanbase/odc/assets/22992296/55434e34-c7bc-48f8-a021-08400fc641cb">

after:
<img width="997" alt="截屏2023-11-01 21 11 50" src="https://github.com/oceanbase/odc/assets/22992296/2a4ffb6d-3ad3-486c-92b3-1c6595a7b407">

**Comment by yhilmare** [comment]
further more, the parser will not report any syntax error if the input's any prefix is grammatical:
<img width="535" alt="截屏2023-11-01 21 13 04" src="https://github.com/oceanbase/odc/assets/22992296/704e16e6-23e2-477a-9008-9334f0d171d3">

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9c9cb169-48d8-46e7-8fd4-240eedbaa149)

pass
