### ISSUE TITLE
[Bug]: Double-clicking an object in the object tree does not open details

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#694]
### ODC version

ODC 4.2.2

### OB version

Any version of OceanBase.

### What happened?

Double-clicking an object in the object tree does not open details,only expands the object tree.
![image](https://github.com/oceanbase/odc/assets/46598871/40c2c9e5-58a7-4de1-92f9-8988aed7c059)

### What did you expect to happen?

Double-click the object name can display the object details.

### How can we reproduce it (as minimally and precisely as possible)?

Double-click the object name

**Comment by HSunboy** [comment]
Fixed In Commit [ee56af18cca37643af77eea9e5369b551fe22af9](https://github.com/oceanbase/odc-client/commit/ee56af18cca37643af77eea9e5369b551fe22af9)
            ------
            晓康
            Tue Nov 21 16:34:31 2023 +0800
