### ISSUE TITLE
[Bug]: the keyword 'varchar' in Oracle mode is not highlighted

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#695]
### ODC version

ODC4.2.2

### OB version

Any version of OceanBase.

### What happened?

The varchar data type is not highlighted in the sql window
![image](https://github.com/oceanbase/odc/assets/46598871/af61ca17-f8fa-4ae4-970b-3c1eb66a2418)

### What did you expect to happen?

The varchar data type should be highlighted in the sql window

### How can we reproduce it (as minimally and precisely as possible)?

create table test(a varchar(20));

**Comment by HSunboy** [comment]
Fixed In Commit [e7eba8038d51cb105bf6e65f33179897bd560f98](https://github.com/oceanbase/odc-client/commit/e7eba8038d51cb105bf6e65f33179897bd560f98)
            ------
            晓康
            Thu Nov 2 10:56:23 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/1b25292b-3601-4b23-82de-7649a6da5d3c)

pass
