### ISSUE TITLE
[Bug]: Executing sql does not display traceid

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#696]
### ODC version

ODC 4.2.2

### OB version

OB 4.2.1

### What happened?

Execute the following SQL didn't get to the traceid.
SELECT
      TABLE_OWNER,
      TABLE_NAME,
      COLUMN_POSITION,
      COLUMN_NAME,
      INDEX_NAME
    FROM
      ALL_IND_COLUMNS
    WHERE
      TABLE_OWNER = 'GSH' AND TABLE_NAME = 'TEST_INDEX1'
    ORDER BY
      COLUMN_POSITION ASC
![image](https://github.com/oceanbase/odc/assets/46598871/f89552a2-2626-4700-ad08-4ebe193b6de4)

### What did you expect to happen?

Display the traceid

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened.

**Comment by LuckyPickleZZ** [comment]
duplicate with #676
