### ISSUE TITLE
[Bug]: Executing sql does not show time consuming

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#697]
### ODC version

ODC 4.2.2

### OB version

OB 4.2.1

### What happened?

Executing the following sql does not show time consuming.
```SQL
SELECT
      TABLE_OWNER,
      TABLE_NAME,
      COLUMN_POSITION,
      COLUMN_NAME,
      INDEX_NAME
    FROM
      ALL_IND_COLUMNS
    WHERE
      TABLE_OWNER = 'GSH' AND TABLE_NAME = 'TEST_INDEX1'
    ORDER BY
      COLUMN_POSITION ASC
```
![image](https://github.com/oceanbase/odc/assets/46598871/d12df337-a245-4811-ac62-850ab67b1ad2)

### What did you expect to happen?

Display the time consuming.

### How can we reproduce it (as minimally and precisely as possible)?

Follow What happened.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/145eb6f9-5746-4cf1-99b2-53055866e59f)

pass
