### ISSUE TITLE
[Feature]: Adapt bastion integration to new permission control model

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#70]
### Is your feature request related to a problem?

ODC 4.2.0 has made a major upgrade to the management and control model, which needs to be adapted to the official website experience station.

### Describe the solution you'd like

None for yet.

**Comment by HSunboy** [comment]
ODC implemented the single data mode in personal space in dev-4.2.2

**Comment by smallsheeeep** [comment]
I will close this issue and the following bastion integration issue is #672
