### ISSUE TITLE
[Bug]: There is overlapping coverage of times in the execution plan

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#703]
### ODC version

ODC422

### OB version

independent

### What happened?

There is overlapping coverage of times in the execution plan
![image](https://github.com/oceanbase/odc/assets/59468957/c523439b-c99f-4364-b8d6-e9797bec28ce)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

task

**Comment by HSunboy** [comment]
Fixed In Commit [01c7c5e46dc1c658650f93fb9c5f56b95de17d91](https://github.com/oceanbase/odc-client/commit/01c7c5e46dc1c658650f93fb9c5f56b95de17d91)
            ------
            晓康
            Mon Nov 6 11:42:31 2023 +0800
