### ISSUE TITLE
[Bug]: When executing a DLM task periodically, the status changes to Completed, resulting in no disable button.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#704]
### ODC version

ODC422

### OB version

independent

### What happened?

When executing a DLM task periodically, the status changes to Completed, resulting in no disable button.
![image](https://github.com/oceanbase/odc/assets/59468957/8da799df-c85b-4b40-a815-71b73a3edb14)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

Create periodic execution tasks

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/0c968adc-b932-4d2d-9908-a9ad35f964da)

pass
