### ISSUE TITLE
[Bug]: [DLM] the approver cannot see approve button while submitter request terminate task

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#712]
### ODC version

4.2.1

### OB version

not related

### What happened?

the approver cannot see approve button while submitter request terminate a DLM task

### What did you expect to happen?

the approver can see the approve button

### How can we reproduce it (as minimally and precisely as possible)?

common user submit a DLM task, then request to terminate it.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/27579047-d710-4d56-a63c-b76ddee0ad47)

pass
