### ISSUE TITLE
[Bug]: failed to read lob data when data's size is larger than 64 KB and 'sendConnectionAttributes' is true

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#727]
### ODC version

4.2.2

### OB version

OceanBase 4.2.1

### What happened?

I set jdbc url's parameter 'sendConnectionAttributes' to `true`:
<img width="263" alt="截屏2023-11-07 19 46 53" src="https://github.com/oceanbase/odc/assets/22992296/41b665bd-e158-4bee-a88b-bd519b5e7ed5">

there is a table with clob and blob datatype. I write some data in it and the data's size is larger that 64 KB.

execute `select * from ${table}` and I found that there is nothing in these datatypes:
<img width="173" alt="截屏2023-11-07 19 49 51" src="https://github.com/oceanbase/odc/assets/22992296/8eb35166-7c6a-4b14-a7d0-5c971bce560c">

### What did you expect to happen?

the content is not empty, I want to query them out.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
this is a driver 's bug, we should upgrade the driver's version to 2.4.7 to fix it

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/2b5ee56d-9342-45e2-8e18-036fd1b35a3a)

pass
