### ISSUE TITLE
[Bug]: failed to export the data with clob or blob datatype

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#728]
### ODC version

4.2.2

### OB version

OceanBase 4.2.1

### What happened?

create a table with clob and blob datatype and write some data that is larger than 64 KB in them.
try to export the table and you will get the export data:
<img width="794" alt="截屏2023-11-07 19 56 39" src="https://github.com/oceanbase/odc/assets/22992296/a0387dbe-40c7-4027-bd19-2edf5929d54b">

open the data file and you will find that the content of the clob or blob column is empty which is not empty in table actually
<img width="136" alt="截屏2023-11-07 19 58 12" src="https://github.com/oceanbase/odc/assets/22992296/f6a52441-cbff-4c9c-803b-c3b4e72b8767">
<img width="182" alt="截屏2023-11-07 19 58 22" src="https://github.com/oceanbase/odc/assets/22992296/41abc5a9-da8f-4e1b-8660-a86444f4cbb1">

### What did you expect to happen?

export the data successfully regardless the datatype of it.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
same root cause with #727

**Comment by yhilmare** [comment]
we should upgrade the version of the driver to fix this

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/daf38823-45b7-4b1e-8bdf-caf1878ac266)

pass
