### ISSUE TITLE
[Bug]: failed to view large clob data

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#729]
### ODC version

4.2.2

### OB version

not related

### What happened?

write some data that is quite large to clob column and execute `select * from xxx` to view the clob data.

here is the real content of the data (take care about the beginning of the content):
<img width="707" alt="截屏2023-11-07 20 04 09" src="https://github.com/oceanbase/odc/assets/22992296/40f61b67-9af8-4560-95d4-bb37cad9a1c0">

here is what we get from ODC:
<img width="786" alt="截屏2023-11-07 20 05 05" src="https://github.com/oceanbase/odc/assets/22992296/cef665ed-2806-4679-bed1-47db920ac70e">

by the way, the response of the corresponding api is right and ODC 4.1.3 behaves normally
<img width="603" alt="截屏2023-11-07 20 08 16" src="https://github.com/oceanbase/odc/assets/22992296/82934091-c938-44eb-ac71-67cd3f79d187">

ODC 4.1.3:
<img width="771" alt="截屏2023-11-07 20 09 07" src="https://github.com/oceanbase/odc/assets/22992296/e87bbf96-f4e0-4416-909d-3b4f2c1f9efb">

### What did you expect to happen?

I can view it normally

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
Fixed In Commit [feb67c706f28a5e8eee5ca5880cc5ee2e01218ee](https://github.com/oceanbase/odc-client/commit/feb67c706f28a5e8eee5ca5880cc5ee2e01218ee)
            ------
            咏和
            Thu Nov 9 15:09:39 2023 +0800
