### ISSUE TITLE
[Bug]: Execute sql with the same semantics, and the result sets display differently

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#742]
### ODC version

ODC 4.2.2

### OB version

Any versions of OceanBase.

### What happened?

Execute two semantically identical statements in an sql window but display different result sets.
SQL1:
select a,length(a)as len from TEST_ORDER order by 2 desc;
SQL2:
select a,length(a)as len from TEST_ORDER order by length(a) desc;
The ODC result sets are shown as：
![image](https://github.com/oceanbase/odc/assets/46598871/7beb00bd-d05b-4e31-92cc-6adf15e2d8de)
![image](https://github.com/oceanbase/odc/assets/46598871/1ca85d71-2476-4186-b362-e63821dc64a8)
obclient：
![image](https://github.com/oceanbase/odc/assets/46598871/f11dc144-02f5-462f-88ca-74ea4e689683)

### What did you expect to happen?

ODC result set display is consistent with obclient.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/e2b34682-849b-43ef-9bc6-b762f0cd3fd5)



![Image](https://github.com/oceanbase/odc/assets/143492234/66241dcb-b072-4e35-8669-264203b6e327)

PASS
