### ISSUE TITLE
[Bug]: sql-check report a syntax error when a sql is executed successfully

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#746]
### ODC version

4.2.2

### OB version

not replated

### What happened?

1. switch on the 'syntax error' rule
<img width="1088" alt="截屏2023-11-09 11 37 24" src="https://github.com/oceanbase/odc/assets/22992296/86646218-dd73-4a4b-844f-e4b1953b50bc">

2. type and execute the sql as follow:
```SQL
drop table if exists t1;
create table t1 (c1 text) ;
insert into t1 select  (randstr(1+zipf(1, 43250, random()), random())) from table(generator(1000));
```
3. as you can see, the database execute these sqls successfully but the sql-check gives a syntax error:
![0F35EBB1-2ECC-40A5-B749-5986BBF75501](https://github.com/oceanbase/odc/assets/22992296/fb78fde7-6f99-48c0-a160-0012ce45d32e)

### What did you expect to happen?

if a sql is executed by observer without any syntax error, the sql-check should not report syntax error.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/62043f3d-3513-4df9-b724-8b6f6b12102a)

pass
