### ISSUE TITLE
[Bug]: Trigger export failed，No dump tasks are generated for schema: "TEST"

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#750]
### ODC version

ODC422

### OB version

Oceanbase2277
Oceanbase420

### What happened?

Trigger export failed
![image](https://github.com/oceanbase/odc/assets/59468957/18379faa-408b-43f4-9396-89450acf0a84)

### What did you expect to happen?

export normally

### How can we reproduce it (as minimally and precisely as possible)?

chat private

**Comment by LuckyPickleZZ** [comment]
This is because there is a bug on ob-loader-dumper 4.2.5 . It has been fixed in v4.2.6, so we could fix this in the future when we upgrade ob-loader-dumper~
