### ISSUE TITLE
[Bug]: oracle模式下游标类型出参数预览bug

### ISSUE THREAD

**Issue by liuwy1005** [oceanbase/odc#751]
### ODC version

4.2.0

### OB version

5.7.25-OceanBase-v4.2.1.1'
OceanBase 4.2.1.1 (r101000062023103122-34e6ed68f3db97700b665a618fc3801f6b109124) (Built Oct 31 2023 22:22:10)

### What happened?

当我执行有游标返回的存储过程，提示执行完成。在运行结果中选择参数进行预览，多列的结果集预览发现所有的字段名为我select列表中最后一列的列名。

### What did you expect to happen?

我的select列表中的字段应该按照我编写的顺序进行显示，或者当我使用*时候，使用表结构的字段顺序进行显示。

### How can we reproduce it (as minimally and precisely as possible)?

1、于oracle模式下数据库创建存储过程
```SQL
create or replace PROCEDURE proc_test
(
    P_COL1 OUT VARCHAR2,
    P_CUR OUT SYS_REFCURSOR,
    P_CUR2 OUT SYS_REFCURSOR,
    P_CUR3 OUT SYS_REFCURSOR,
    P_CUR4 OUT SYS_REFCURSOR

)
IS
v_number VARCHAR2(50);
v_number2 DATE;
BEGIN
    P_COL1:='asd';
     v_number:='1111';
    v_number2:=SYSDATE;
    open P_CUR for
            select 1 as a from dual
            union all
            select 2 as a from dual;

     open P_CUR2 for
        select 'asds' as cardtitle from DUAL;

    open P_CUR3 for
        select TO_CHAR(SYSDATE,'yyyy-mm-DD HH24:mi:ss') as cardtitle2,'1'cardtitle3 from DUAL;

    open P_CUR4 for
        select 1 as usercode,
               2 as username from dual;
END proc_test;
```
在ODC中选择创建出来的存储过程，选择“运行“，在弹出的设置参数窗口中，直接点击确定。

在运行结果的参数列表中点击”P_CUR4“参数“值”后面图标，会弹出参数预览窗口。P_CUR4的select列表为两个列，usercode，username。但是预览窗口中显示的都是“username”

**Comment by yhilmare** [comment]
this bug can be reproduced by this sample:

```SQL
create or replace PROCEDURE proc_test (P_CUR4 OUT SYS_REFCURSOR) IS
BEGIN
  open P_CUR4 for
select
  1 as usercode,
  2 as username
from
  dual;
END
  proc_test;
```

**Comment by yhilmare** [comment]
我们已经定位并修复了这个问题，我们将在下一个版本中发布此修复，预计的发布时间为 11 月中下旬，感谢您的支持 @liuwy1005

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/1c6293d5-7e80-4045-b018-dbc314776003)

pass
