### ISSUE TITLE
[Bug]: When scanning and adding sensitive columns, if there are multiple column page breaks in the result preview, the desensitization algorithm will not change

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#758]
### ODC version

odc422

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/4e5ad41b-199d-4c19-a47f-a330e15b865c

### What did you expect to happen?

The desensitization algorithm becomes the default option when changing pages

### How can we reproduce it (as minimally and precisely as possible)?

Wrap within preview of results with multiple pages

**Comment by HSunboy** [comment]
Fixed In Commit [1cdb8b20f8957a2451a32d871d474ee3b2db974b](https://github.com/oceanbase/odc-client/commit/1cdb8b20f8957a2451a32d871d474ee3b2db974b)
            ------
            ccj01609335
            Mon Nov 13 14:01:00 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/431ba791-0b5a-4c6c-a418-0e109d103076)
pass
