### ISSUE TITLE
[Bug]: poor performance in mass editing of result sets

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#76]
### ODC version

4.2.0

### OB version

*

### What happened?

For any schema, when the number of rows in the edited result set exceeds 100, the time required to generate SQL is at the minute level. 
And this time consumption is proportional to the number of rows. 
This time is obviously too long.

### What did you expect to happen?

The time to generate DMLs needs to be controlled in second level.

### How can we reproduce it (as minimally and precisely as possible)?

Create any table and insert 1000 rows of data using the edit table data function. Click Execute to trigger the issue.

**Comment by LuckyPickleZZ** [comment]
Fixed

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/650c16a9-8876-444f-83f3-0040c9ef829a)
pass
