### ISSUE TITLE
[Bug]: Export trigger failed

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#763]
### ODC version

odc422

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/696220b0-2dfb-4e5c-a27a-a1e48a70d581)
![image](https://github.com/oceanbase/odc/assets/143492234/02137bd6-e327-4145-ba27-c362f2c0e307)

### What did you expect to happen?

Export successful

### How can we reproduce it (as minimally and precisely as possible)?

Export triggers only

**Comment by LuckyPickleZZ** [comment]
duplicate with #750
