### ISSUE TITLE
[Feature]: Auto-recognize time-consuming SQL and prompts when creating database change task

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#772]
### Is your feature request related to a problem?

I create a database change task in which create a index for big table and consume long time (> 48h). 
Then the task will timeout and failed, the index may rollback.

### Describe the solution you'd like

May create a new SQL check rule to delect create index operation and prompt user to increase the task timeout?

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [b25667b6c2c8f6618790c915572c6f41772fa3a7](https://github.com/oceanbase/odc-client/commit/b25667b6c2c8f6618790c915572c6f41772fa3a7)
