### ISSUE TITLE
[Bug]: The error message that fails to obtain the lock causes the failure of the database synchronization is inaccurate

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#773]
### ODC version

4.2.1

### OB version

null

### What happened?

After clicking the synchronous database, error, and the error message causes customers to misunderstand:
![image](https://github.com/oceanbase/odc/assets/84772536/0d6d8b55-6e5e-4af5-9aa6-800cafc1989e)

### What did you expect to happen?

Optimize performance, optimize error messages

### How can we reproduce it (as minimally and precisely as possible)?

Synchronous database

**Comment by tonghan-gsh** [comment]
Modify the error message to: The database is being synchronized, please try again later.
