### ISSUE TITLE
[Bug]: Collation name displayed in databse list is incorrect

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#774]
### ODC version

4.2.1

### OB version

3.2.4.2

### What happened?

Collation name displayed in databse list is incorrect.
![image](https://github.com/oceanbase/odc/assets/84772536/8758ec5b-9209-4dbf-8e03-b83b57d8b0be)
![image](https://github.com/oceanbase/odc/assets/84772536/4d889825-0313-4ba7-9ca6-33962752915f)

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

**Comment by smallsheeeep** [comment]
But, why OCP can diaplay right collation name?

**Comment by PeachThinking** [comment]
> But, why OCP can diaplay right collation name?

ocp get charset by query oceanbase.__all_database to get collation_type which requires permissions from the sys tenant.
<img width="1105" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/fe2e981c-ce82-4f1f-b59e-f8ddcb2ef637">

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/679b80b7-6187-4221-9363-7838705c7d17)



![Image](https://github.com/oceanbase/odc/assets/46598871/7f90342e-5344-4aa1-af84-35c8a3387b5e)

Passed using ob3247 test
