### ISSUE TITLE
[Bug]: Time type results set display error

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#776]
### ODC version

4.2.2

### OB version

3.2.4.2

### What happened?

![image](https://github.com/oceanbase/odc/assets/84772536/79d56d37-e72b-4bd0-9f07-fb874a548591)

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/84772536/e146cd6b-fcc3-422d-b927-3355c2e4f6a7)

### How can we reproduce it (as minimally and precisely as possible)?
1. create a table:
```sql
CREATE TABLE `gaoda_test` (
  `birthday` datetime DEFAULT NULL
)
```
2. insert a row：
```sql
INSERT INTO gaoda_test(birthday) VALUES('0000-01-01');
```
3. select:
<img width="572" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/efdd3616-75b0-48a5-b8be-a32271dd7cab">

### Anything else we need to know?

.

### Cloud

.

**Comment by yhilmare** [comment]
driver's bug, I create the same table and insert the same data for both native mysql and obmysql, I get different result:

native mysql:
<img width="565" alt="截屏2023-11-13 14 53 25" src="https://github.com/oceanbase/odc/assets/22992296/26d821a5-3663-43f9-85d6-3c081bb34181">

ob-mysql:
<img width="455" alt="截屏2023-11-13 14 53 35" src="https://github.com/oceanbase/odc/assets/22992296/ca08f523-74bc-43b2-8d74-f51fc36b3156">

**Comment by yhilmare** [comment]
this difference mysql by caused by this:
```Java
// oceanbase-client, RowProtocol#buildTimestmap
private Timestamp buildTimestmap(int year,int month,int day,int hour,int minutes,int seconds,int nanos,Calendar calendar,TimeZone timezone) {
      Calendar localCal = getCalendarInstance(calendar);
      if (options.useLegacyDatetimeCode) {
          localCal.setTimeZone(timezone);
      }
      Timestamp tt;
      synchronized (localCal) {
          localCal.clear();
          localCal.set(year, month - 1, day, hour, minutes, seconds);
          tt = new Timestamp(localCal.getTimeInMillis());
      }
      tt.setNanos(nanos);
      return tt;
  }
```

```Java
// mysql-connector, SqlTimestampValueFactory#localCreateFromDatetime
@Override
    public Timestamp localCreateFromDatetime(InternalTimestamp its) {
        if (its.getYear() == 0 && its.getMonth() == 0 && its.getDay() == 0) {
            throw new DataReadException(Messages.getString("ResultSet.InvalidZeroDate"));
        }

        synchronized (this.defaultTimeZone) {
            Calendar c;

            if (this.cal != null) {
                c = this.cal;
            } else {
                // c.f. Bug#11540 for details on locale
                c = Calendar.getInstance(this.pset.getBooleanProperty(PropertyKey.preserveInstants).getValue() ? this.connectionTimeZone : this.defaultTimeZone,
                        Locale.US);
                c.setLenient(false);
            }

            try {
                // this method is HUGEly faster than Java 8's Calendar.Builder()
                c.set(its.getYear(), its.getMonth() - 1, its.getDay(), its.getHours(), its.getMinutes(), its.getSeconds());
                Timestamp ts = new Timestamp(c.getTimeInMillis());
                ts.setNanos(its.getNanos());
                return ts;
            } catch (IllegalArgumentException e) {
                throw ExceptionFactory.createException(WrongArgumentException.class, e.getMessage(), e);
            }
        }
    }
```

as you can see, mysql-connector set lenient to false that is true by defalut

**Comment by yhilmare** [comment]
this differences may lead to this issue

**Comment by yhilmare** [comment]
the driver should give odc an exception and odc will call `getString` to give the the native content provided by observer

**Comment by yhilmare** [comment]
we can not call `getString` directly to get the value which may lead to other problems~

**Comment by yhilmare** [comment]
related driver's bug id: 53218651

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/b2310b88-5ff9-4ca2-b94d-c92ec33b41ec)

pass

**Comment by qymsummer** [comment]
![Image](https://github.com/oceanbase/odc/assets/40919496/b2310b88-5ff9-4ca2-b94d-c92ec33b41ec)

pass
