### ISSUE TITLE
[Bug]: "defualt schema" is not displayed when creating a new ODP sharding mysql datasource

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#778]
### ODC version

4.2.3

### OB version

odp sharding mysql

### What happened?

"defualt schema" is not displayed when creating a new ODP sharding mysql datasource：
![image](https://github.com/oceanbase/odc/assets/140503120/7bd91b10-fb72-451b-9a27-03aa09c80af3)

### What did you expect to happen?

"defualt schema" is displayed when creating a new ODP sharding mysql datasource：

### How can we reproduce it (as minimally and precisely as possible)?

creat a new ODP sharding mysql database

**Comment by HSunboy** [comment]
Fixed In Commit [bdc5e71e82f649f2778e1eea6f680df10309126a](https://github.com/oceanbase/odc-client/commit/bdc5e71e82f649f2778e1eea6f680df10309126a)
            ------
            晓康
            Mon Nov 13 17:14:07 2023 +0800
