### ISSUE TITLE
[Bug]: The option list for the data source is not formatted when editing the sql check specification

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#791]
### ODC version

4.2.3

### OB version

odp sharding mysql

### What happened?

The option list for the data source is not formatted when editing the sql check specification：
<img width="1761" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/da71d943-9323-4eba-83c7-8fc4dc7e79e0">

### What did you expect to happen?

The option list for the data source is formatted when editing the sql check specification

### How can we reproduce it (as minimally and precisely as possible)?

editing the sql check specification

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [3896df171b4f147f18b5d48135b9a4c64867e3f2](https://github.com/oceanbase/odc-client/commit/3896df171b4f147f18b5d48135b9a4c64867e3f2)

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/3f1f8065-2265-4abe-807c-087594bc1f5d)

pass
