### ISSUE TITLE
[Bug]: Error in viewing table details in ODP sharding mysql mode

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#793]
### ODC version

4.2.3

### OB version

odp sharding mysql when lower_case_table_names = 1 or 2

### What happened?

Click "View Table Details" and the front-end calls the getTable interface twice. When the interface is called for the first time, the table name passed by the front-end is the table name passed by the back-end. The returned table information of table name is lowercase which is different from `list tables` result, and this lead to the interface is called secondly time to check table
<img width="1835" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/edf5aa89-6d1e-4ad8-b085-3622efc0ac73">

When the interface is called the second time, the table name passed by the front-end is lowercase. , causing the backend to throw an exception "the table with tableName as tab2 does not exist".
<img width="1650" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/431c7a09-fb4b-4ad0-b2e1-7fe408dd7a06">

### What did you expect to happen?

View table details normally

### How can we reproduce it (as minimally and precisely as possible)?

1. Create an uppercase table
2. Click "View Table Details"

**Comment by HSunboy** [comment]
![image](https://github.com/oceanbase/odc/assets/14886044/8ca66fac-0844-4044-b098-fe855b323935)
get table API returned wrong name
odc will reload table when the table name changes

**Comment by PeachThinking** [comment]
In the test environment of this ODP sharding, lower_case_table_names=2, but the created table names are not stored according to the case specified during create. It's a known bug.

**Comment by PeachThinking** [comment]
when the variable `lower_case_table_names=1 or 2` in ODP sharding mysql mode, the table name will be automatically converted to uppercase mode. ODC will make an adaptation here to bypass this bug.

**Comment by Huangxiao-mas** [comment]
PASS
