### ISSUE TITLE
[Bug]: set names gbk, which are stored in utf8 format

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#8]
**Describe the bug**

set names gbk, which are stored in utf8 format

**Environment**

- OS Version and CPU Arch(`uname -a`):
  
- Component Version: ODC 4.1.3
  

**Fast Reproduce Steps(Required)**

`create table test_2(a char(100));
set names gbk;
insert into test_2 values('明华(HYHApp)');
SELECT * from test_2;
select RAWTOHEX(a)from test_2;`
![image](https://github.com/oceanbase/odc/assets/46598871/a1f0a63a-6789-4bf5-b0dc-58af74b1c990)

**Expected behavior**

The storage shall be in gbk format

**Actual Behavior**

**Additional context**

**Comment by yhilmare** [comment]
`set names gbk` is not supported, we can only set encoding by datasource config #93
