### ISSUE TITLE
[Bug]: failed to mask sensitive columns for ResultSetExport task

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#80]
### ODC version

4.2.0

### OB version

*

### What happened?

When a sensitive column was set, the data will be masked while querying. But it won't be effective for result-set-export task. Origin data will be exported !

### What did you expect to happen?

The data of sensitive column can be masked.

### How can we reproduce it (as minimally and precisely as possible)?

Exporting any sensitive column will reproduce this.

**Comment by LuckyPickleZZ** [comment]
Fixed.

**Comment by runzi389205** [comment]
PASS


![Image](https://github.com/oceanbase/odc/assets/141202865/70462c75-e5de-4ce3-a64b-9884ad794279)
