### ISSUE TITLE
[Feature]: It is hoped that ODC supports configuring message notifications.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#812]
### Is your feature request related to a problem?

When initiating tasks in ODC, if there is any abnormality during execution, currently I do not receive any notifications, and I must log in to ODC to check if the task is running normally.

### Describe the solution you'd like

I hope that ODC can actively push the results of the task to my preferred communication software, such as DingTalk, SMS, Feishu, etc.

**Comment by HSunboy** [comment]
Fixed In Commit [aa89ee8d69c9dd86882e786d66c47c4ba1eb94b0](https://github.com/oceanbase/odc-client/commit/aa89ee8d69c9dd86882e786d66c47c4ba1eb94b0)
            ------
            陈朝俊
            Tue Jan 16 19:00:09 2024 +0800
