### ISSUE TITLE
[Feature]: It is hoped that ODC could support structural comparison.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#816]
### Is your feature request related to a problem?

In daily work, I often need to ensure that the structures of development databases and test databases used for the same business are consistent, but because too many people use these two types of databases, I cannot determine whether their structures are truly consistent.

### Describe the solution you'd like

I hope that ODC could provide a method for comparing structures so that I can periodically check for differences between these two databases.

**Comment by HSunboy** [comment]
Fixed In Commit [fefbaa45b858793575aaf8242d1778820873ac36](https://github.com/oceanbase/odc-client/commit/fefbaa45b858793575aaf8242d1778820873ac36)
            ------
            陈朝俊
            Wed Jan 31 09:24:24 2024 +0800
