### ISSUE TITLE
[Enhancement]: When managing table objects under OBOracle mode with ODC, the case sensitivity rules for table names and column names can be kept consistent with other tools.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#819]
### What would you like to be added?

Under OBOracle mode, when creating a table using ODC, if I enter a lowercase table name in the input box, the newly created table name will be in lowercase. This forces me to quote the table name using double quotes in order to reference it properly. In contrast, other tools will automatically convert lowercase table names to uppercase when entered.

### Why is this needed?

It is hoped that ODC's behavior would match that of other tools in terms of case sensitivity.

**Comment by HSunboy** [comment]
Added in dev-4.2.4
