### ISSUE TITLE
[Bug]: String data type do not show “length” when viewing the column information of a table

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#82]
### ODC version

4.2.0

### OB version

all verison

### What happened?

String data type do not show “length” when viewing the column information of a table，both in ob oracle mode and ob mysql mode：
<img width="891" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/59d4c06a-769b-44f7-bee0-9c1a0f2f7a3d">

### What did you expect to happen?

show length of a String data type like odc 4.1.2 verison：
<img width="956" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/d67f0986-401b-41fa-8b1b-a8d64b411f20">

### How can we reproduce it (as minimally and precisely as possible)?

create String data type column in both ob mysql mode and ob oracle mode

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4505617e-c3e3-4320-bfec-07274a732ffb)

pass
