### ISSUE TITLE
[Bug]: Annotation interception optimization

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#823]
### ODC version

ODC422

### OB version

independent

### What happened?

Annotation interception optimization
![image](https://github.com/oceanbase/odc/assets/59468957/e4a51f2b-dd7b-4a27-a219-d7c18ba2d42b)

### What did you expect to happen?

optimization

### How can we reproduce it (as minimally and precisely as possible)?

chat private

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [0558fcf63b39eb17814a2cd6191fde9817b01db8](https://github.com/oceanbase/odc-client/commit/0558fcf63b39eb17814a2cd6191fde9817b01db8)

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/9cecd893-f367-465c-9520-f38959bf4dc3)

pass
