### ISSUE TITLE
[Feature]: It is hoped that ODC's Single Sign-On (SSO) solution integrates with LDAP protocol.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#824]
### Is your feature request related to a problem?

Currently, it appears that ODC does not yet support LDAP integration with its Single Sign-On (SSO) solution. 

### Describe the solution you'd like

It is desirable to add support for LDAP integration to ODC's Single Sign-On (SSO).

**Comment by HSunboy** [comment]
Fixed In Commit [e35d75975b6fd9c9bf562f13feeb1d5b7e1216d1](https://github.com/oceanbase/odc-client/commit/e35d75975b6fd9c9bf562f13feeb1d5b7e1216d1)
            ------
            陈朝俊
            Thu Jan 18 17:28:41 2024 +0800
