### ISSUE TITLE
[Enhancement]: The desktop version of ODC currently does not support exporting objects exceeding 4GB in size.

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#829]
### What would you like to be added?

Export failures can occur when ODC encounters objects exceeding the maximum file size limitation imposed by the ZIP format.

### Why is this needed?

It is suggested to exclude ZIP compression from ODC exports to prevent potential failures caused by file size limitations.

**Comment by yizhouxw** [comment]
released in v4.2.4
