### ISSUE TITLE
[Bug]:  the database column is hidden

### ISSUE THREAD

**Issue by Jane201510** [oceanbase/odc#83]
### ODC version

4.2.0

### OB version

4.0

### What happened?

When the display screen is too narrow, the database column is hidden.
![image](https://github.com/oceanbase/odc/assets/15030999/9879a379-3b70-4fa6-a207-89a56e9de74d)

### What did you expect to happen?

The database column is displayed normally

### How can we reproduce it (as minimally and precisely as possible)?

Open ODC, enter the designated project, and shrink the display window

**Comment by runzi389205** [comment]
PASS


![Image](https://github.com/oceanbase/odc/assets/141202865/ec41f298-e714-4b90-b8ac-c32811974fa5)
