### ISSUE TITLE
[Bug]: can not copy multi columns

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#853]
### ODC version

4.2.2

### OB version

not related

### What happened?

I can copy and paste multi columns on odc 4.1.1:

1. select multi columns.
2. ctrl-c and ctrl-v
<img width="740" alt="截屏2023-11-17 11 40 53" src="https://github.com/oceanbase/odc/assets/22992296/142af83b-474d-4596-8309-214c282e2cdb">

I do the same thing on odc 4.2.2, but I can just copy the last column I select:
<img width="878" alt="截屏2023-11-17 11 41 42" src="https://github.com/oceanbase/odc/assets/22992296/595b97fd-dac3-4efc-8a1c-e883f24b26cf">

### What did you expect to happen?

I expect that the column coping function on odc 4.2.2 has the same behavior with odc 4.1.1

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by bluesky-xyh** [comment]
fixed，result set has been upgraded to version 3.0.x

**Comment by sl01388797** [comment]
pass
