### ISSUE TITLE
[Bug]: Data error during MySQL simulation data selection and fixed value execution

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#854]
### ODC version

odc422

### OB version

not related

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/6968a572-ebfd-4974-8972-7da3783a3304)
![image](https://github.com/oceanbase/odc/assets/143492234/5fc7ed5a-fb3f-4b0a-9735-2aacf22a57ce)

### What did you expect to happen?

Col2 is 0

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Table
```SQL
CREATE TABLE `a1` (
  `col` int(11) DEFAULT NULL,
  `col1` int(11) DEFAULT '1',
  `col2` int(11) NOT NULL AUTO_INCREMENT
)
```
3. Conduct simulation data col selection sequence, col2 select fixed value

**Comment by yhilmare** [comment]
this is expected, let us do an experience:
1. truncate a1:
<img width="472" alt="截屏2023-12-07 21 50 10" src="https://github.com/oceanbase/odc/assets/22992296/04f925a6-f92f-4acd-8b65-65891d8fd712">

2. execute sqls as follow:
<img width="613" alt="截屏2023-12-07 21 51 09" src="https://github.com/oceanbase/odc/assets/22992296/838b780d-7849-4d94-ba1b-4a3e0ae52799">

as you can see, columns `col2` is fixed zero
3. query this table:
<img width="634" alt="截屏2023-12-07 21 52 17" src="https://github.com/oceanbase/odc/assets/22992296/1624493f-165d-4bbf-b5d5-072c58afd2a2">

as you can see, col2 is not a fixed value

**Comment by yhilmare** [comment]
I have debugged the ob-data-mocker, the value we write is right obviously~
