### ISSUE TITLE
[Bug]: Failed to create code snippet when the number of characters in the code snippet is close to 100000

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#855]
### ODC version

odc423

### OB version

*

### What happened?

![02decc44572681105e1c6466e412ae31](https://github.com/oceanbase/odc/assets/143492234/c6f03820-8362-4b00-828a-60a0109046cd)
![5e8122aef84281d0d5e5dcdbab169e11](https://github.com/oceanbase/odc/assets/143492234/c11c2e01-620f-4fb5-81b9-a889150ff516)

### What did you expect to happen?

Created successfully

### How can we reproduce it (as minimally and precisely as possible)?

Create a code snippet with a character count close to 100000

**Comment by yhilmare** [comment]
the max size of snippet's body is 65535 bytes, I add a constraint to check this~

**Comment by HSunboy** [comment]
Fixed In Commit [4fd0a07548e4aefa4cac1663c7abab90ac0677f7](https://github.com/oceanbase/odc-client/commit/4fd0a07548e4aefa4cac1663c7abab90ac0677f7)
            ------
            xiaokang
            Mon Dec 4 10:00:00 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/08bc83c9-bd56-4242-9acc-811865f37fc7)
pass
