### ISSUE TITLE
[Bug]: Invalid new and delete keys during table creation

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#863]
### ODC version

odc423

### OB version

*

### What happened?

Clicking on 'New' or 'Delete' during table creation cannot take effect
![image](https://github.com/oceanbase/odc/assets/143492234/2ab53c62-1d25-4b7f-8d97-05d35294fc34)

### What did you expect to happen?

New and deleted can take effect

### How can we reproduce it (as minimally and precisely as possible)?

Click New and Delete when creating a table

**Comment by HSunboy** [comment]
Fixed In Commit [4408b502706b5d63287ce075f527b15675ef6618](https://github.com/oceanbase/odc-client/commit/4408b502706b5d63287ce075f527b15675ef6618)
            ------
            咏和
            Tue Nov 21 16:33:31 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/f6be013e-1fc7-4360-b50d-09cbac76aa23)
pass
