### ISSUE TITLE
[Bug]: Repeated opening of plans may result in errors

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#870]
### ODC version

odc423

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/5794edbb-6e16-4288-97a1-243bf59648b0

### What did you expect to happen?

No duplicate fields will appear

### How can we reproduce it (as minimally and precisely as possible)?

Repeatedly opening the plan

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [453431776fefd059c5dc4374c388f57e5eafba01](https://github.com/oceanbase/odc-client/commit/453431776fefd059c5dc4374c388f57e5eafba01)

**Comment by sl01388797** [comment]
pass
