### ISSUE TITLE
[Bug]: Parsing connection string error

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#883]
### ODC version

4.2.2

### OB version

all

### What happened?

<img width="606" alt="image" src="https://github.com/oceanbase/odc/assets/140503120/9a95011b-ee5c-401d-8c9b-d79a969e6d0f">

### What did you expect to happen?

Parsing connection string correctly

### How can we reproduce it (as minimally and precisely as possible)?

as mentioned above

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/20c1df6e-6f57-4a59-8aab-7bd0f616f254)

pass
