### ISSUE TITLE
[Bug]: Timeout in pre-check process node if the SQL files are too large

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#886]
### What would you like to be added?

Add timeout solution for pre-check task. If the pre-check node executing for a long time, then interrupt it and continue execut ing database change task.

### Why is this needed?

If I upload a big SQL file (> 200 MB), then the pre-check node will executing more than 24 hours, and the task status is pending and without any percentage.

**Comment by HSunboy** [comment]
Fixed In Commit [adac6f5b20550e0c0b53267336cb90e5b9701743](https://github.com/oceanbase/odc-client/commit/adac6f5b20550e0c0b53267336cb90e5b9701743)
            ------
            咏和
            Thu Dec 14 11:33:21 2023 +0800
