### ISSUE TITLE
[Bug]: failed to get orders in private zone

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#893]
### ODC version

4.2.3

### OB version

not related

### What happened?

I can not see any orders in private zone:
<img width="1129" alt="截屏2023-11-22 19 59 40" src="https://github.com/oceanbase/odc/assets/22992296/9767bb09-cef2-43f0-8a6f-c98d8f90eb12">

but I can get orders on condition of 'created by me':
 
<img width="1014" alt="截屏2023-11-22 20 00 50" src="https://github.com/oceanbase/odc/assets/22992296/65f81aa4-07b5-4026-ba1c-887630acb9e9">

### What did you expect to happen?

I can get orders.

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

**Comment by yhilmare** [comment]
It seems to be a newly introduced problem in 4.2.3

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/27c92730-b65b-4230-b88a-de6d4c557164)

pass
