### ISSUE TITLE
[Bug]: Scanning and adding sensitive columns will only add one page of sensitive columns

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#897]
### ODC version

odc423

### OB version

*

### What happened?

Scanning and adding sensitive columns will only add one page of sensitive columns

### What did you expect to happen?

Add all sensitive columns scanned out

### How can we reproduce it (as minimally and precisely as possible)?

Scan multiple pages of sensitive columns and add sensitive columns. Scan again to view sensitive columns

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [33a649a8923bb8f78f17b3cc15c54f884142735a](https://github.com/oceanbase/odc-client/commit/33a649a8923bb8f78f17b3cc15c54f884142735a)

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/ffc11a03-729c-47e5-8fee-0d7f744a278c)
pass
