### ISSUE TITLE
[Feature]: mysql and ob mysql mode support gis datatype

### ISSUE THREAD

**Issue by PeachThinking** [oceanbase/odc#899]
### Is your feature request related to a problem?

no

### Describe the solution you'd like

mysql support gis datatype, Supports creating, viewing, and managing tables containing gis field types.
And supports processing result sets containing gis field types：

- GEOMETRY

- POINT

- LINESTRING

- POLYGON

- MULTIPOINT

- MULTILINESTRING

- MULTIPOLYGON

- GEOMETRYCOLLECTION

**Comment by Jane201510** [comment]
duplicate:https://github.com/oceanbase/odc/issues/851
