### ISSUE TITLE
[Bug]: When exporting data files , the data is not exported and the status shows Completed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#900]
### ODC version

ODC422bp

### OB version

Oceanbase3240

### What happened?

When exporting data files, the data is not exported and the status shows Completed
![image](https://github.com/oceanbase/odc/assets/59468957/d1725901-8423-444b-8094-13051d765b4a)
![image](https://github.com/oceanbase/odc/assets/59468957/9311a094-0e97-48f4-915d-31ae263b9f0c)

### What did you expect to happen?

execute normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by LuckyPickleZZ** [comment]
We have set the `PageSize` of ob-dumper to `Integer.MAX_VALUE`, so the task would not be splitted anymore.
But there is another case, when we eporting a table with several partitions, each partition will still be splitted into a standalone task. This issue is still exists.
