### ISSUE TITLE
[Bug]: After importing the entire database file, click OK and it will report 'New single table imported successfully', which should be called 'Import successful'

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#901]
### ODC version

ODC422bp

### OB version

independent

### What happened?

After importing the entire database file, click OK and it will report 'New single table imported successfully', which should be called 'Import successful'
![image](https://github.com/oceanbase/odc/assets/59468957/f7ad25f4-2872-49be-a732-1912ba7a79af)

### What did you expect to happen?

he prompt changes to "Import successful"

### How can we reproduce it (as minimally and precisely as possible)?

Import any file

**Comment by HSunboy** [comment]
Fixed In Commit [0850b7d9d7755eb697866971b85715cb77c60122](https://github.com/oceanbase/odc-client/commit/0850b7d9d7755eb697866971b85715cb77c60122)
            ------
            咏和
            Tue Dec 5 09:58:24 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b8a0bf3c-0190-4bc2-8697-a8984097abf5)

pass
