### ISSUE TITLE
[Bug]: failed to call a procedure/function that contains out sys_refcursor

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#910]
### ODC version

4.2.2

### OB version

not releated

### What happened?

there is a procedure:

```SQL
create or replace procedure abcd_test1(
var_result_info out varchar2,
value_list out sys_refcursor) IS
BEGIN
    var_result_info := 'asdasdasd';
    open value_list for
select
  1 as usercode,
  2 as username
from
  dual;
end;
```

I try to call it by odc:
<img width="753" alt="截屏2023-11-24 11 26 47" src="https://github.com/oceanbase/odc/assets/22992296/13e3cfdb-2dd6-4e3f-b066-cd652ccea9bb">

I can execute the calling anonymous block in sql console:
<img width="808" alt="截屏2023-11-24 11 27 41" src="https://github.com/oceanbase/odc/assets/22992296/2a51c590-469f-4c54-a548-74ed786d9471">

### What did you expect to happen?

call the procedure/function contains out ref_cursor successfully.

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by yhilmare** [comment]
as you can see:
```Java
// JdbcDataTypeUtil#getValueFromStatement
public static Object getValueFromStatement(CallableStatement statement, int index, String type)
            throws SQLException {
        JDBCType jdbcType = parseDataType(type);
        if (null == statement.getString(index)) {
            return null;
        }
...
}
```

we will call `statement.getString` before we get value from statement actually. If the value can not be encoded to string such as sys_refcursor, this calling will throw an exceotion.

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/c8f51764-345c-4c72-a97c-7dd356eac9fc)
pass
