### ISSUE TITLE
[Bug]: There is no prompt when there is a work order that needs to be approved, and it needs to be refreshed before it can be prompted

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#918]
### ODC version

odc423

### OB version

*

### What happened?

![00787d672b59800aad439f5fbdf9d7ce](https://github.com/oceanbase/odc/assets/143492234/97574c3a-af41-434a-8400-5ce557ff96a0)
没刷新时
![539c047cf6a16d084c7fbc48d4cff8e6](https://github.com/oceanbase/odc/assets/143492234/119a1989-918e-41fd-af51-7c65471b2e2a)
刷新后

### What did you expect to happen?

When there are work orders that require approval, there is a prompt

### How can we reproduce it (as minimally and precisely as possible)?

Create work orders that require approval

**Comment by HSunboy** [comment]
Fixed In Commit [57504c68d6544653188a5bd627ac79faca90d450](https://github.com/oceanbase/odc-client/commit/57504c68d6544653188a5bd627ac79faca90d450)
            ------
            咏和
            Fri Dec 1 12:22:40 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/b684097d-f6f1-4db2-a0f8-2c04b30ea48b)

pass
