### ISSUE TITLE
[Bug]: The custom variables in the scene example do not match the UI

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#920]
### ODC version

ODC4.2.3

### OB version

independent

### What happened?

The custom variables in the scene example do not match the UI
![image](https://github.com/oceanbase/odc/assets/59468957/9599558f-9449-4e19-b531-3e61ef4cc635)
![image](https://github.com/oceanbase/odc/assets/59468957/3aa93930-738e-479b-aacc-786e11e230bd)

### What did you expect to happen?

Be consistent with the UI

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Fixed In Commit [57504c68d6544653188a5bd627ac79faca90d450](https://github.com/oceanbase/odc-client/commit/57504c68d6544653188a5bd627ac79faca90d450)
            ------
            咏和
            Fri Dec 1 12:22:40 2023 +0800
