### ISSUE TITLE
[Bug]: The filtering options for the list view nodes in the full link Trace details are incorrect

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#923]
### ODC version

odc423

### OB version

ob410

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/9536a17a-e0f2-457b-a806-43867e740407)

### What did you expect to happen?

Filter to obproxy, observer, and jdbc

### How can we reproduce it (as minimally and precisely as possible)?

Click to filter the list view nodes in the full link Trace details

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [a503316e649cf17fdb851b1d2fe06e4749d3eaa6](https://github.com/oceanbase/odc-client/commit/a503316e649cf17fdb851b1d2fe06e4749d3eaa6)

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/3bbd6f4b-1301-4687-b6f1-b1aa006f343d)
pass
