### ISSUE TITLE
[Bug]: ODC 4.2.2 failed to connect to OceanBase 3.2.4.5 standby OceanBase clusters' tenant

### ISSUE THREAD

**Issue by alvinloong** [oceanbase/odc#925]
### ODC version

ODC 4.2.2 win desktop version

### OB version

OceanBase 3.2.4.5 Oracle mode

### What happened?

When selecting a database above the SQL window, the database/username list dropdown failed to show after clicking the data source.

Following ODC log messages tell the reason. 

Currently we will try setting jdbc url option sessionVariables=ob_read_consistency='WEAK' or SET ob_read_consistency='WEAK'; through advanced settings when creating or editing a data source.

SQL [select USERNAME from "ALL_USERS"]; (conn=3221635451) 
ORA-16000: standby cluster support weak read only; 

1. 

```
[2023-11-27 11:12:26.110][http-nio-8989-exec-10][a5f2b37a032f4016,,][WARN][com.oceanbase.odc.service.connection.database.DatabaseService][379]: 
Sync database failed, dataSourceId=160, errorMessage=StatementCallback; 
SQL [select USERNAME from "ALL_USERS"]; (conn=3221635451) 
ORA-16000: standby cluster support weak read only; 
nested exception is java.sql.SQLTransientConnectionException: (conn=3221635451) 
ORA-16000: standby cluster support weak read only
```

### What did you expect to happen?

Expect ODC set weak read automatically when connect to a standby OceanBase clusters' tenant. 

### How can we reproduce it (as minimally and precisely as possible)?

connect to a standby OceanBase clusters' tenant.

**Comment by Jane201510** [comment]
Perhaps an option can be added to the data source configuration for OceanBase data sources to choose whether to connect to the standby database.

**Comment by tonghan-gsh** [comment]
I cannot reproduce this problem, rd has communicated this problem with the customer. The customer set the session initialization using the parameters in jdbcurl
