### ISSUE TITLE
[Bug]: Simultaneously execute the shutdown of ob_ Enable_ Show_ The trace parameter and query statement can still be opened for the full link trace

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#932]
### ODC version

odc423

### OB version

odc410

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/4361b3b2-4ae1-4a94-840c-5a2f023cdcbc)
![image](https://github.com/oceanbase/odc/assets/143492234/4db68573-7a4b-4951-8173-60337b72c205)
![image](https://github.com/oceanbase/odc/assets/143492234/2ce05edc-960a-453d-ac09-a5c4e0c28f01)

### What did you expect to happen?

Full link trace cannot be opened

### How can we reproduce it (as minimally and precisely as possible)?

Simultaneously execute the shutdown of ob_ Enable_ Show_ Trace parameters and query statements

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [9a3abdc11ac0bff2eeff5cc3aa5ee64dce91a60a](https://github.com/oceanbase/odc-client/commit/9a3abdc11ac0bff2eeff5cc3aa5ee64dce91a60a)

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/625582d8-1b4f-43f4-abe0-d95c999346fb)
pass
