### ISSUE TITLE
[Bug]: Unable to view full link trace in table data

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#933]
### ODC version

odc423

### OB version

ob410

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/c1ab1e11-8e66-4eb2-b41c-9708aae11414)

### What did you expect to happen?

Can view the full link trace

### How can we reproduce it (as minimally and precisely as possible)?

When the OB version is greater than 4.0.0 and OB is opened_ Enable_ Show_ View table data during trace

**Comment by LuckyPickleZZ** [comment]
We will hide this entry in the interface for viewing table data.

**Comment by HSunboy** [comment]
Fixed In Commit [3c27e306d1a56a68343a2a73e123900b60016794](https://github.com/oceanbase/odc-client/commit/3c27e306d1a56a68343a2a73e123900b60016794)
            ------
            陈朝俊
            Wed Dec 6 14:54:11 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/d37c4238-82a8-4cba-8e7c-8180ff097373)
![image](https://github.com/oceanbase/odc/assets/143492234/776dd3bb-4591-46eb-adb8-2d5bdca4a4c0)
pass
