### ISSUE TITLE
[Bug]: The database list interface under the project is not fully loaded

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#935]
### ODC version

ODC 4.2.2

### OB version

-

### What happened?

When I first entered the database list under the project, the interface didn't load fully.
![image](https://github.com/oceanbase/odc/assets/46598871/55c7481d-cf68-419c-896b-280686e2a8a1)
The page is loaded properly after being refreshed.
![image](https://github.com/oceanbase/odc/assets/46598871/e33337a0-0b32-4352-af81-50b4da10ba06)

### What did you expect to happen?

The database list interface is loaded completely.

### How can we reproduce it (as minimally and precisely as possible)?

First entry project.

**Comment by bluesky-xyh** [comment]
fixed

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/636ce6c0-620d-41a4-87b8-d632d6d346e0)

pass
