### ISSUE TITLE
[Bug]: variable management module will lead to sql injection

### ISSUE THREAD

**Issue by yhilmare** [oceanbase/odc#937]
### ODC version

4.2.2

### OB version

not related

### What happened?

1. begin modify session variable or global variable
<img width="1048" alt="截屏2023-11-28 16 26 41" src="https://github.com/oceanbase/odc/assets/22992296/20595387-5e01-486c-a2f7-34c0840890bf">
2. click confirm and the front end will call `/api/v1/variables/execute/`, this api is not safe.

### What did you expect to happen?

call a specific api which will not lead to sql injection

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

**Comment by HSunboy** [comment]
New API needs to be added and SQL preview removed

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/c6aed312-f537-4b62-a2f4-83e488590136)

pass
