### ISSUE TITLE
[Bug]: Node name display error when displaying details for full link trace

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#938]
### ODC version

odc423

### OB version

ob421

### What happened?

![21c0e58f44db6fb47caacfc638f212cc](https://github.com/oceanbase/odc/assets/143492234/e1758ea8-2974-4bf5-a129-c6d2c1efd7b0)

### What did you expect to happen?

Two names display consistent

### How can we reproduce it (as minimally and precisely as possible)?

View details within the full chain trace

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [a503316e649cf17fdb851b1d2fe06e4749d3eaa6](https://github.com/oceanbase/odc-client/commit/a503316e649cf17fdb851b1d2fe06e4749d3eaa6)

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/4ba79c30-0f25-4014-ad6d-212081e78036)
pass
