### ISSUE TITLE
[Bug]: There are no jdbc nodes within the full chain trace

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#948]
### ODC version

odc423

### OB version

ob421

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/b2b09d0e-e3f1-4d05-aaaa-d56a5f3aa449)

### What did you expect to happen?

There are jdbc nodes present

### How can we reproduce it (as minimally and precisely as possible)?

View full link trace

**Comment by LuckyPickleZZ** [comment]
The jdbc node will only be displayed if the following conditions are met:
1. obproxy `enable_ob_protocol_v2_with_client` parameter value is true
2. the value of jdbc param `sendConnectionAttributes` is true

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/be91013b-9ad8-42b5-8b2a-03cc3a76e88d)
pass
