### ISSUE TITLE
[Bug]: View column modes within the result set, and the data will not change after switching columns

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#950]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/bccc9024-060a-4931-99e5-9938af31cf72)

### What did you expect to happen?

The data within the column pattern will change

### How can we reproduce it (as minimally and precisely as possible)?

View column patterns within the result set and then switch columns

**Comment by HSunboy** [comment]
Fixed In Commit [0850b7d9d7755eb697866971b85715cb77c60122](https://github.com/oceanbase/odc-client/commit/0850b7d9d7755eb697866971b85715cb77c60122)
            ------
            咏和
            Tue Dec 5 09:58:24 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/97a78906-6dce-40b3-82e9-dd0bcd61740a)
pass
