### ISSUE TITLE
[Bug]: when creating a new approval process cannot select external approval

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#953]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

If I deselect the external approval process when creating an approval process, I cannot select it again
![image](https://github.com/oceanbase/odc/assets/46598871/17754252-c4a9-4fe9-aea7-6437fe1dd503)

### What did you expect to happen?

I can select external approval process.

### How can we reproduce it (as minimally and precisely as possible)?

1.Select external approval when creating the approval process
2.Deselect external approval
3.Select external approval again

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [9d8316d108d12295572d4ab3241009d641c4f859](https://github.com/oceanbase/odc-client/commit/9d8316d108d12295572d4ab3241009d641c4f859)

**Comment by tonghan-gsh** [comment]
![Image](https://github.com/oceanbase/odc/assets/46598871/d206a356-84e2-4abb-a0c5-978a6fb0bf71)

pass
