### ISSUE TITLE
[Bug]: The task details for requesting project permissions are empty

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#954]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/6df452d3-26dc-4818-94ec-a1b4c7738b55)
The task details for requesting project permissions are empty.

### What did you expect to happen?

Show task details.

### How can we reproduce it (as minimally and precisely as possible)?

Apply for a task.

**Comment by HSunboy** [comment]
Fixed In Commit [57504c68d6544653188a5bd627ac79faca90d450](https://github.com/oceanbase/odc-client/commit/57504c68d6544653188a5bd627ac79faca90d450)
            ------
            咏和
            Fri Dec 1 12:22:40 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/d35c8649-61e4-426a-b938-c1f11aace719)

pass
