### ISSUE TITLE
[Bug]: Built-in databases are auto-sychronized when the datasouce is bound to a project

### ISSUE THREAD

**Issue by smallsheeeep** [oceanbase/odc#955]
### ODC version

4.2.0

### OB version

any

### What happened?

If I bind a datasource to a project, then all databases in the datasource are auto-sychronized to project including built-in databases like `test`, `mysql`, `oceanbase`, `information_schema`, `SYS`.

### What did you expect to happen?

Block built-in databases when auto-sychronizing databases to project：
1. In MySQL mode, block following databases:
- `test`
- `mysql`
- `oceanbase`
- `information_schema`

3. In Oracle mode, block following schemas:
- `SYS`

### How can we reproduce it (as minimally and precisely as possible)?

Bind datasource to a project and then look the database list in project.

**Comment by HSunboy** [comment]
Added in dev-4.2.3

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/2cb9e66c-08dc-4406-9485-647599bc10cb)



![Image](https://github.com/oceanbase/odc/assets/143492234/65805d00-d878-4db8-82fb-cf1f87cfc703)

pass
