### ISSUE TITLE
[Bug]: Clicking on the blank space in the table will pop up an input box

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#956]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/fc3543ed-9953-4267-8953-7bbf71b8cab0)

### What did you expect to happen?

Will not pop up input boxes

### How can we reproduce it (as minimally and precisely as possible)?

![image](https://github.com/oceanbase/odc/assets/143492234/359ee337-cbe4-4989-929d-e715bd86a7aa)
Click on the blank space after selecting the box

**Comment by bluesky-xyh** [comment]
fixed

**Comment by sl01388797** [comment]
pass
