### ISSUE TITLE
[Bug]: calling procedure get SQLException 'No output result'

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#959]
### ODC version

4.2.2

### OB version

4.2.1

### What happened?

please use this `sql.txt` to prepare schema.

[sql.txt](https://github.com/oceanbase/odc/files/13508788/sql.txt)

When calling the `PRC_11_CD_AD_CO_DEPS` use obclient, it would work normally. But when calling it on ODC4.2.2, you may get a SQLException 'No output result'.

Noted this error only occurs on OB 4.2.x. It could work normally on 3.x.

### What did you expect to happen?

successfully

### How can we reproduce it (as minimally and precisely as possible)?

⬆️

**Comment by LuckyPickleZZ** [comment]
There may be a jdbc bug. After I set jdbc param `sendConnectionAttributes` to true, this worked normally.

**Comment by zijiacj** [comment]
Ob-jdbc2.4.8 version have fixed this problem
