### ISSUE TITLE
[Bug]: Select data types that cannot be modified. The length and decimal point can be modified

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#960]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/67fa0690-1044-48ad-beba-7d9a72bbb4ac)

### What did you expect to happen?

Unable to modify length and decimal point

### How can we reproduce it (as minimally and precisely as possible)?

Select data types that cannot be modified, then modify the decimal point and length

**Comment by bluesky-xyh** [comment]
fixed

**Comment by sl01388797** [comment]
pass
