### ISSUE TITLE
[Bug]: After creating a column of type geometrycollection, the data type changed to geomcollection

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#961]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/860a7a1e-7a16-4fdc-b6d4-eee524ac977e)
![image](https://github.com/oceanbase/odc/assets/143492234/af42f9ad-3d7e-459e-bf21-1ebb92408bdc)

### What did you expect to happen?

Consistent data types

### How can we reproduce it (as minimally and precisely as possible)?

Create a column with a data type of geometrycollection

**Comment by PeachThinking** [comment]
the table ddl show in ODC is get by query "show create table xxx" from OB, This is a OB kernel bug. I tested native mysql and there is no such problem.
