### ISSUE TITLE
[Bug]: Setting null and default values within the result set is invalid

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#963]
### ODC version

odc423

### OB version

ob421

### What happened?

https://github.com/oceanbase/odc/assets/143492234/ffa7d9c0-3046-4076-be40-ae86cacea258

### What did you expect to happen?

Successfully set null and default values in the result set

### How can we reproduce it (as minimally and precisely as possible)?

Set null and default values within the result set

**Comment by bluesky-xyh** [comment]
fixed

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/0b5c5599-26cd-4dd1-8da2-b4a8363d5e2d)
oracle模式在显示出rowid列后点击设置为null和设置为默认值无效

**Comment by bluesky-xyh** [comment]
Fixed In Commit [1b2c594c3d5380977c8ae3c16680adf3f120da86](https://github.com/oceanbase/odc-client/commit/1b2c594c3d5380977c8ae3c16680adf3f120da86)
------
咏和
Wed Dec 13 10:56:10 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/5f60dabb-7cb8-4fd4-a0f1-6168ae49d8e7)
pass
