### ISSUE TITLE
[Bug]: When creating an unconditional DLM task, the variable display on the task details page is blank.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#964]
### ODC version

ODC422

### OB version

independent

### What happened?

When creating an unconditional DLM task, the variable display on the task details page is blank.
ODC423
![image](https://github.com/oceanbase/odc/assets/59468957/4c135d8a-69fe-4e98-bcc0-b7416d6f7a93)
ODC422
![image](https://github.com/oceanbase/odc/assets/59468957/164889e1-0b95-4bb0-9dc1-f96ce05438cc)

### What did you expect to happen?

chat priavtely

### How can we reproduce it (as minimally and precisely as possible)?

chat priavtely

**Comment by bluesky-xyh** [comment]
The design draft has been changed. Starting from 423, a "custom variable" will not be added by default here
