### ISSUE TITLE
[Bug]: Removing the selected columns from the result set will not take effect

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#966]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/412de650-67a8-4512-84f5-82cc57d6eccd)

### What did you expect to happen?

Do not display the removed columns

### How can we reproduce it (as minimally and precisely as possible)?

Remove the columns to be displayed from the result set

**Comment by bluesky-xyh** [comment]
fixed

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/f7cf4a96-9784-4c6a-bc8a-a05933323e9a)
pass
