### ISSUE TITLE
[Bug]: Partition plan execution failed

### ISSUE THREAD

**Issue by guowl3** [oceanbase/odc#969]
### ODC version

4.2.2

### OB version

1.4.7.9

### What happened?

Partition plan execution failed

### What did you expect to happen?

Partition plan creates partitions normally

### How can we reproduce it (as minimally and precisely as possible)?

Create a partition plan job and review task execution records.

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/4000c766-91be-4161-9cd1-2e1dd014404f)
pass
