### ISSUE TITLE
[Bug]: The Personal Space Task list does not show the request project permission task

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#971]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/cc209509-8460-42ea-abd7-a5450c8d40e8)
The Personal Space Task list does not show the request project permission task.

### What did you expect to happen?

There is no concept of projects in personal space and no need to apply for task permissions.

### How can we reproduce it (as minimally and precisely as possible)?

Enter personal space.

**Comment by HSunboy** [comment]
Fixed In Commit [0850b7d9d7755eb697866971b85715cb77c60122](https://github.com/oceanbase/odc-client/commit/0850b7d9d7755eb697866971b85715cb77c60122)
            ------
            咏和
            Tue Dec 5 09:58:24 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/ad03bf78-3e1f-480b-a228-ce389bb2f7fd)

pass
