### ISSUE TITLE
[Bug]: only create os user when it doesn't exist

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#972]
### ODC version

4.2.2

### OB version

none

### What happened?

When ODC opening a obclient window, it would  call `useradd` command to create a os user .This is for security issues and for resource isolation. 
However , this user would not be deleted. So the logs of the operating system will have some records of user creation failures.

### What did you expect to happen?

This command should be called only when the user does not exist.

### How can we reproduce it (as minimally and precisely as possible)?

Open the command line multiple times and then check the logs.

**Comment by Huangxiao-mas** [comment]
PASS
