### ISSUE TITLE
[Bug]: when deleting a user without detecting whether the user joined a project

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#973]
### ODC version

4.2.2

### OB version

none

### What happened?

When deleting a user, we don't detect whether the user had also joined a project. 
So If a user to be deleted is a owner of a project, this project could not be managed by any other user.

### What did you expect to happen?

If a user to be deleted is a owner of a project, this project should be archived.

### How can we reproduce it (as minimally and precisely as possible)?

Drop a user who is a owner of a project.

**Comment by MarkPotato777** [comment]
duplicate with https://github.com/orgs/oceanbase/projects/7/views/17?groupedBy%5BcolumnId%5D=Assignees&pane=issue&itemId=45751279
