### ISSUE TITLE
[Bug]: DB session list show 0 Time for OB3.x

### ISSUE THREAD

**Issue by yizhouxw** [oceanbase/odc#974]
### ODC version

4.2.0

### OB version

3.x

### What happened?

DB session list show 0 Time for OB3.x
![image](https://github.com/oceanbase/odc/assets/54161870/6aa66d84-9b6b-48da-9225-7d3a7d998be3)

### What did you expect to happen?

in DB session list, Time column value shoud not be 0 for OB3.x

### How can we reproduce it (as minimally and precisely as possible)?

goto DB Session page

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/01032df4-8809-47d5-9dfc-11fe27217568)

pass
