### ISSUE TITLE
[Bug]: 4.2.2版本 日期类型 时分秒都是0

### ISSUE THREAD

**Issue by guwenrui** [oceanbase/odc#975]
### ODC version

4.2.2

### OB version

![image](https://github.com/oceanbase/odc/assets/74892585/40dc7dbf-7168-4126-a2c4-af21e9f0fdd0)
![image](https://github.com/oceanbase/odc/assets/74892585/afe01584-c916-466f-98b2-4402446f688e)

### What happened?

4.2.2版本 日期类型 时分秒都是0

### What did you expect to happen?

期望能显示时分秒 如to_char一样
![image](https://github.com/oceanbase/odc/assets/74892585/69bb5d6b-8d65-4acd-a8ff-317de6cb4fa6)

### How can we reproduce it (as minimally and precisely as possible)?

set global nls_date_format='YYYY-MM-DD HH24:MI:SS'

SELECT TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') from dual;

SELECT TO_DATE(SYSDATE,'YYYY-MM-DD HH24:MI:SS') from dual;

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/bf1a7d27-ee81-4896-a847-d04700b18e25)

PASS
