### ISSUE TITLE
[Bug]: there are omissions in disabling the export entry

### ISSUE THREAD

**Issue by LuckyPickleZZ** [oceanbase/odc#978]
### ODC version

4.2.2

### OB version

none

### What happened?

After setting `odc.data.export.enabled` to false in metadb, the most entry of export function are disabled. But we still can find an export entry in project -> databases.
![image](https://github.com/oceanbase/odc/assets/36879124/c775d839-3b3a-4365-8609-5b45007f61e8)

### What did you expect to happen?

All entry should be disabled.

### How can we reproduce it (as minimally and precisely as possible)?

setting `odc.data.export.enabled` to false in metadb.

**Comment by HSunboy** [comment]
Fixed In Commit [035abd43c3654b591545442c387b8c94172ebdcf](https://github.com/oceanbase/odc-client/commit/035abd43c3654b591545442c387b8c94172ebdcf)
            ------
            xiaokang
            Mon Dec 4 13:57:06 2023 +0800
