### ISSUE TITLE
[Bug]: creating a task ticket cost too much time

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#979]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/402a9527-eed0-4c79-b483-1b821f0f5af3)
It takes 18s to create a work order in team space.

### What did you expect to happen?

We want to speed up the creation of work orders.

### How can we reproduce it (as minimally and precisely as possible)?

Assign tasks in the team space.

**Comment by yhilmare** [comment]
<img width="977" alt="截屏2023-12-13 19 39 54" src="https://github.com/oceanbase/odc/assets/22992296/ebc1b493-1698-40b3-ad56-9c10311f62bb">

**Comment by yhilmare** [comment]
![截屏2023-12-13 22 21 02](https://github.com/oceanbase/odc/assets/22992296/51682e74-4f22-489a-8867-0e665d40df6f)

as you can see, I use bulk insert in `buildTopology`, the cost is reduced from 4701ms to 1406ms, 70% off and 21% off for total.

**Comment by yhilmare** [comment]
![截屏2023-12-14 20 54 25](https://github.com/oceanbase/odc/assets/22992296/604bde8e-8916-46b8-8284-c687f0c645a9)

as you can see, I use bulk insert to handle bind relation of node instance and flowable element. `buildConfigurer`'s cost is reduced from 4195ms to 1799ms, 57%off. the cost of `buildTopology` is increased from 1406ms to 2195ms, 56% up, the reason is that I move the bulk insert from `buildConfigurer` to `buildTopology`.

total 17.5% off.

**Comment by yhilmare** [comment]
![截屏2023-12-15 21 21 01](https://github.com/oceanbase/odc/assets/22992296/8e6f195d-4b36-497d-802e-5aea3ed1db9a)

I insert flow task instance, approval instance and gateway instance by batch inserting, and the cost of 'buildTopology' is increased from 2195ms to 2793ms, about 27% up.

total: 24% off

**Comment by yhilmare** [comment]
the complexity of creating flow not is O(1) and is O(n) before, the cost of the creating is reduce from 13002 ms to 6598 ms, 50% off.

**Comment by yhilmare** [comment]
the total sql statements of creating flow is reduce to 8

**Comment by yhilmare** [comment]
I test it on a large database.
Before:
<img width="581" alt="截屏2023-12-18 19 41 55" src="https://github.com/oceanbase/odc/assets/22992296/4de5cd14-8e4c-4056-87ba-b3eabdee1a8d">

It cost about 30s+ to create a new flow. 
After:
<img width="1098" alt="截屏2023-12-18 19 48 47" src="https://github.com/oceanbase/odc/assets/22992296/1c805867-ad82-4dca-8839-a0f770c23e59">
<img width="1119" alt="截屏2023-12-18 19 49 41" src="https://github.com/oceanbase/odc/assets/22992296/cb930222-024e-4111-9a69-c1b983b38887">
<img width="1119" alt="截屏2023-12-18 19 50 08" src="https://github.com/oceanbase/odc/assets/22992296/f06338d9-5797-4ab6-8006-a7e9a6be395c">

I tried 3 times, the costing is stable.

**Comment by tonghan-gsh** [comment]
![image](https://github.com/oceanbase/odc/assets/46598871/87123b5b-8a6b-4c03-8fc6-6d3582ce57dd)
The task delivery time is between 1-5s
