### ISSUE TITLE
[Bug]: The permission type described in the project permission worksheet is expected to be displayed in Chinese

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#980]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/6ffa7e31-cdc7-4d7e-a61f-45f16103882d)
The permission type described in the work order is in English.

### What did you expect to happen?

The permission type described in the project permission worksheet is expected to be displayed in Chinese.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver the task for requesting project permissions.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/4e18e517-fcb3-4f84-8ede-7f265b6b07b4)

pass
