### ISSUE TITLE
[Bug]: Upload files within the result set, but after successful upload, they will not be displayed within the result set

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#983]
### ODC version

odc423

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/b690d14e-7a41-4def-829d-876c3026adc2

### What did you expect to happen?

![image](https://github.com/oceanbase/odc/assets/143492234/7b64ce2a-57b5-44eb-a123-5aa2da1fe307)

### How can we reproduce it (as minimally and precisely as possible)?

Upload files within the result set

**Comment by HSunboy** [comment]
Fixed In Commit [9bcd26a5b614e108cc6bacb259f77bfd3b762855](https://github.com/oceanbase/odc-client/commit/9bcd26a5b614e108cc6bacb259f77bfd3b762855)
            ------
            咏和
            Fri Dec 8 11:40:28 2023 +0800
