### ISSUE TITLE
[Bug]: View the result set with blank text under the dark theme

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#984]
### ODC version

odc423

### OB version

*

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/151f1d23-e8b5-495b-9749-bfc0c649aa60)

### What did you expect to happen?

Can display text content

### How can we reproduce it (as minimally and precisely as possible)?

Upload files within the result set and view text after executing SQL

**Comment by HSunboy** [comment]
Fixed In Commit [9bcd26a5b614e108cc6bacb259f77bfd3b762855](https://github.com/oceanbase/odc-client/commit/9bcd26a5b614e108cc6bacb259f77bfd3b762855)
            ------
            咏和
            Fri Dec 8 11:40:28 2023 +0800

**Comment by sl01388797** [comment]
![image](https://github.com/oceanbase/odc/assets/143492234/6b75382b-dc17-41d1-ad0b-e3bfd16462b0)
pass
