### ISSUE TITLE
[Bug]: Cancel page crash after uploading files within the result set

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#985]
### ODC version

odc423

### OB version

*

### What happened?

https://github.com/oceanbase/odc/assets/143492234/afb2acd2-185f-4700-999a-516e57c2312a

### What did you expect to happen?

The page will not crash

### How can we reproduce it (as minimally and precisely as possible)?

Cancel after uploading files within the result set

**Comment by bluesky-xyh** [comment]
fixed

**Comment by sl01388797** [comment]
pass
