### ISSUE TITLE
[Bug]: The page turning component under the project list is blocked

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#988]
### ODC version

ODC423

### OB version

independent

### What happened?

The page turning component under the project list is blocked
![image](https://github.com/oceanbase/odc/assets/59468957/d6249544-b250-4028-af28-c3b564842f29)

### What did you expect to happen?

chat privately

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Fixed In Commit [5c0acb0a509bb4e4d2486e600a4cc374e6db0b0e](https://github.com/oceanbase/odc-client/commit/5c0acb0a509bb4e4d2486e600a4cc374e6db0b0e)
            ------
            咏和
            Sun Dec 10 18:02:52 2023 +0800
