### ISSUE TITLE
[Bug]: Safari logs into odc and the front end crashes

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#989]
### ODC version

ODC422

### OB version

independent

### What happened?

Safari logs into odc and the front end crashes
![image](https://github.com/oceanbase/odc/assets/59468957/6aa5dc62-5dc8-4647-b4f6-83a14cd01f76)

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Caused by accessing resources being deployed
