### ISSUE TITLE
[Bug]: When the name of the data source under the project is too long, there is no hover prompt when the mouse is placed on the name.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#990]
### ODC version

ODC422

### OB version

independent

### What happened?

When the name of the data source under the project is too long, there is no hover prompt when the mouse is placed on the name.
![image](https://github.com/oceanbase/odc/assets/59468957/aea211c7-7efc-447b-a6d1-8541920dd131)

### What did you expect to happen?

There will be a hover prompt when the mouse is placed on it.

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by HSunboy** [comment]
Fixed In Commit [676f97703fd0a75276d9e44e40723d6d984b79d2](https://github.com/oceanbase/odc-client/commit/676f97703fd0a75276d9e44e40723d6d984b79d2)
            ------
            xiaokang
            Tue Dec 5 11:27:01 2023 +0800
