### ISSUE TITLE
[Bug]: When SRID is not 0, spatial positions will swap

### ISSUE THREAD

**Issue by sl01388797** [oceanbase/odc#991]
### ODC version

odc423

### OB version

mysql8.0

### What happened?

![image](https://github.com/oceanbase/odc/assets/143492234/91379ec0-894d-4c8d-ba9c-e52144c32b01)
![image](https://github.com/oceanbase/odc/assets/143492234/7eea8bdf-d947-44a8-9d75-52e773c25553)

### What did you expect to happen?

Spatial data is not interchangeable

### How can we reproduce it (as minimally and precisely as possible)?

Add data to the table of GIS type data

**Comment by PeachThinking** [comment]
![Image](https://github.com/oceanbase/odc/assets/140503120/3383ecc7-e343-452e-bb76-c681100cf1ce)



![Image](https://github.com/oceanbase/odc/assets/140503120/09063c95-343f-4583-b41b-db13712b4305)
