### ISSUE TITLE
[Bug]: When switching databases in sql Windows, the mouse hover displays the data source

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#993]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

![image](https://github.com/oceanbase/odc/assets/46598871/5f54ec67-115c-4323-87f4-9a60fe75867d)
When switching databases in the sql window, if there is a database with the same name in the project, it is easy to confuse users.

### What did you expect to happen?

 it is recommended that the mouse hover display data source information.

### How can we reproduce it (as minimally and precisely as possible)?

Switch database in sql window.

**Comment by HSunboy** [comment]
Fixed In Commit [676f97703fd0a75276d9e44e40723d6d984b79d2](https://github.com/oceanbase/odc-client/commit/676f97703fd0a75276d9e44e40723d6d984b79d2)
            ------
            xiaokang
            Tue Dec 5 11:27:01 2023 +0800

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/2d81c6e2-923a-461e-b5e6-1bb8c8e1e165)

pass
