### ISSUE TITLE
[Bug]: When the mouse is placed on the screenshot, there is no hover prompt.

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#995]
### ODC version

ODC423

### OB version

independent

### What happened?

When the mouse is placed on the screenshot, there is no hover prompt.
![image](https://github.com/oceanbase/odc/assets/59468957/41f564e9-40c9-4caa-8826-f45cf05b7d77)

### What did you expect to happen?

gei a hint

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by UnknownAdventurer** [comment]
Fixed In Commit [9a3abdc11ac0bff2eeff5cc3aa5ee64dce91a60a](https://github.com/oceanbase/odc-client/commit/9a3abdc11ac0bff2eeff5cc3aa5ee64dce91a60a)
