### ISSUE TITLE
[Bug]: List all tickets failed

### ISSUE THREAD

**Issue by Huangxiao-mas** [oceanbase/odc#996]
### ODC version

423

### OB version

independent

### What happened?
When the request is:
<img width="1918" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/7e3e500a-0803-4493-b83f-1d3eef9a0510">
or
<img width="1916" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/8c956b73-ae9a-43f1-ab21-a4be5af4c681">
then nothing return.
 It works when:
<img width="1920" alt="image" src="https://github.com/oceanbase/odc/assets/84772536/b7a7bfaa-15b6-4704-a2be-0520acd74523">
So I guess when 
```json
createdByCurrentUser: true
approveByCurrentUser: true
containsAll: true
```
here is a bug

### What did you expect to happen?

chat privately

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

**Comment by smallsheeeep** [comment]
Duplicated with #998
