### ISSUE TITLE
[Bug]: Participants cannot view the project application tasks in all work orders

### ISSUE THREAD

**Issue by tonghan-gsh** [oceanbase/odc#998]
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

Use ordinary members to apply for participant rights for a project
![image](https://github.com/oceanbase/odc/assets/46598871/4386cb86-6a21-4501-803e-238ea79b5c3a)
The task cannot be seen in all projects
![image](https://github.com/oceanbase/odc/assets/46598871/bfaabbee-13b5-4348-94e0-838e0e3cfad0)

### What did you expect to happen?

All projects show application task type.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

**Comment by sl01388797** [comment]
![Image](https://github.com/oceanbase/odc/assets/143492234/a5ff4432-81ff-43e7-80fe-0adf766fbd32)

pass
